//go:build linux

package access

import (
	"bufio"
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"strconv"
	"strings"
	"syscall"
	"time"
)

const (
	linuxAuthorizedKeysRoot = "/etc/ssh/authorized_keys"
	linuxTerminalRoot = "/run/cyberpanel/terminals"
)

type LinuxCredentialExecutor struct{Files *LinuxFileExecutor}
func NewLinuxCredentialExecutor(files *LinuxFileExecutor)(*LinuxCredentialExecutor,error){if files==nil{return nil,ErrInvalidState};return &LinuxCredentialExecutor{Files:files},nil}
func accessReceipt(parts ...string)string{hash:=sha256.Sum256([]byte(strings.Join(parts,"\x00")));return "access-"+hex.EncodeToString(hash[:])}
func runFixedAccess(ctx context.Context,path string,stdin []byte,args ...string)([]byte,error){command:=exec.CommandContext(ctx,path,args...);command.Env=[]string{"PATH=/usr/sbin:/usr/bin:/sbin:/bin","LANG=C"};if stdin!=nil{command.Stdin=bytes.NewReader(stdin)};output,err:=command.CombinedOutput();if len(output)>64<<10{output=output[:64<<10]};if err!=nil{return output,fmt.Errorf("%s failed: %w: %s",path,err,string(output))};return output,nil}
func(executor *LinuxCredentialExecutor)binding(ctx context.Context,site SiteID)(LinuxSiteBinding,error){if executor==nil||executor.Files==nil{return LinuxSiteBinding{},ErrInvalidState};binding,err:=executor.Files.Resolver.ResolveAccessSite(ctx,site);if err!=nil{return LinuxSiteBinding{},err};if !validLinuxBinding(binding){return LinuxSiteBinding{},ErrIntegrity};return binding,nil}
func accessRootPath(binding LinuxSiteBinding,root SiteRoot,home RelativePath)string{base:=LinuxAccessSitesRoot+"/"+binding.SiteKey+"/roots/g"+strconv.FormatUint(binding.Generation,10);switch root.Kind{case RootSite:base+="/releases/current";case RootPublic:base+="/releases/current/public";case RootPrivate:base+="/private";case RootLogs:base+="/logs";case RootStaging:base+="/tmp/staging"};if !home.IsRoot(){base+="/"+home.String()};return base}
func(executor *LinuxCredentialExecutor)ApplyFTPSAccount(ctx context.Context,a FTPSAccount,s SecretMaterial)(string,error){if err:=a.Validate();err!=nil{return "",err};binding,err:=executor.binding(ctx,a.SiteID);if err!=nil{return "",err};password:=s.bytes();defer wipeAccess(password);input:=append(append([]byte(nil),[]byte(a.Username+":"+string(password))...), '\n');home:=accessRootPath(binding,a.Root,a.Home);args:=[]string{"--home-dir",home,"--shell","/usr/sbin/nologin","--gid",strconv.FormatUint(uint64(binding.GID),10),"--no-user-group",a.Username};if _,lookupErr:=user.Lookup(a.Username);lookupErr!=nil{if _,err=runFixedAccess(ctx,"/usr/sbin/useradd",nil,args...);err!=nil{return "",err}};if _,err=runFixedAccess(ctx,"/usr/sbin/chpasswd",input);err!=nil{return "",err};if _,err=runFixedAccess(ctx,"/usr/sbin/usermod",nil,"--unlock",a.Username);err!=nil{return "",err};return accessReceipt("ftps",string(a.ID),strconv.FormatUint(a.Generation,10)),nil}
func(executor *LinuxCredentialExecutor)RotateFTPSPassword(ctx context.Context,a FTPSAccount,s SecretMaterial)(string,error){if err:=a.Validate();err!=nil{return "",err};password:=s.bytes();defer wipeAccess(password);input:=[]byte(a.Username+":"+string(password)+"\n");if _,err:=runFixedAccess(ctx,"/usr/sbin/chpasswd",input);err!=nil{return "",err};return accessReceipt("ftps-password",string(a.ID),strconv.FormatUint(a.Generation,10)),nil}
func(executor *LinuxCredentialExecutor)SetFTPSAccountEnabled(ctx context.Context,a FTPSAccount,enabled bool)(string,error){if err:=a.Validate();err!=nil{return "",err};option:="--lock";if enabled{option="--unlock"};if _,err:=runFixedAccess(ctx,"/usr/sbin/usermod",nil,option,a.Username);err!=nil{return "",err};return accessReceipt("ftps-enabled",string(a.ID),strconv.FormatBool(enabled)),nil}
func(executor *LinuxCredentialExecutor)DeleteFTPSAccount(ctx context.Context,a FTPSAccount)(string,error){if err:=a.Validate();err!=nil{return "",err};if _,err:=runFixedAccess(ctx,"/usr/sbin/userdel",nil,a.Username);err!=nil&&!strings.Contains(err.Error(),"does not exist"){return "",err};return accessReceipt("ftps-delete",string(a.ID)),nil}
func(executor *LinuxCredentialExecutor)ApplySSHKey(ctx context.Context,key SSHKey)(string,error){if err:=key.Validate();err!=nil{return "",err};return accessReceipt("ssh-key",string(key.ID),key.PublicKey.Fingerprint),nil}
func(executor *LinuxCredentialExecutor)RemoveSSHKey(ctx context.Context,key SSHKey)(string,error){if err:=key.Validate();err!=nil{return "",err};entries,err:=os.ReadDir(linuxAuthorizedKeysRoot);if errors.Is(err,os.ErrNotExist){return accessReceipt("ssh-key-remove",string(key.ID)),nil};if err!=nil{return "",err};for _,entry:=range entries{if entry.IsDir()||!strings.HasPrefix(entry.Name(),"cyberpanel-"){continue};_ = rewriteAuthorizedKeys(linuxAuthorizedKeysRoot+"/"+entry.Name(),"key="+string(key.ID),"")};return accessReceipt("ssh-key-remove",string(key.ID)),nil}
func grantKeyLine(grant AccessGrant,key SSHKey)string{options:=[]string{"no-agent-forwarding","no-port-forwarding","no-X11-forwarding"};if grant.Permission==AccessReadOnly{options=append(options,"restrict")};marker:="cyberpanel grant="+string(grant.ID)+" key="+string(key.ID);return strings.Join(options,",")+" "+key.PublicKey.AuthorizedKey()+" "+marker}
func ensureAuthorizedKeysRoot()error{info,err:=os.Lstat(linuxAuthorizedKeysRoot);if errors.Is(err,os.ErrNotExist){if err=os.Mkdir(linuxAuthorizedKeysRoot,0755);err!=nil{return err};info,err=os.Lstat(linuxAuthorizedKeysRoot)};if err!=nil||!info.IsDir()||info.Mode()&os.ModeSymlink!=0||info.Mode().Perm()&0002!=0{return ErrIntegrity};return os.Chmod(linuxAuthorizedKeysRoot,0755)}
func(executor *LinuxCredentialExecutor)ApplyAccessGrant(ctx context.Context,grant AccessGrant,key SSHKey)(string,error){if err:=grant.Validate(time.Now().UTC());err!=nil{return "",err};binding,err:=executor.binding(ctx,grant.SiteID);if err!=nil{return "",err};if grant.Protocol==ProtocolTerminal{return accessReceipt("terminal-grant",string(grant.ID)),nil};if err=key.Validate();err!=nil{return "",err};if err=ensureAuthorizedKeysRoot();err!=nil{return "",err};path:=linuxAuthorizedKeysRoot+"/cyberpanel-"+binding.Username;line:=grantKeyLine(grant,key);if err=rewriteAuthorizedKeys(path,"grant="+string(grant.ID),line);err!=nil{return "",err};return accessReceipt("ssh-grant",string(grant.ID),key.PublicKey.Fingerprint),nil}
func(executor *LinuxCredentialExecutor)RemoveAccessGrant(ctx context.Context,grant AccessGrant)(string,error){binding,err:=executor.binding(ctx,grant.SiteID);if err!=nil{return "",err};path:=linuxAuthorizedKeysRoot+"/cyberpanel-"+binding.Username;if err=rewriteAuthorizedKeys(path,"grant="+string(grant.ID),"");err!=nil&&!errors.Is(err,os.ErrNotExist){return "",err};return accessReceipt("ssh-grant-remove",string(grant.ID)),nil}
func rewriteAuthorizedKeys(path,marker,replacement string)error{if !strings.HasPrefix(path,linuxAuthorizedKeysRoot+"/cyberpanel-"){return ErrInvalidPath};content,err:=os.ReadFile(path);if err!=nil&&!errors.Is(err,os.ErrNotExist){return err};lines:=[]string{};scanner:=bufio.NewScanner(bytes.NewReader(content));scanner.Buffer(make([]byte,4096),64<<10);for scanner.Scan(){line:=scanner.Text();if !strings.Contains(line,marker)&&strings.TrimSpace(line)!=""{lines=append(lines,line)}};if err=scanner.Err();err!=nil{return err};if replacement!=""{lines=append(lines,replacement)};encoded:=[]byte(strings.Join(lines,"\n"));if len(encoded)>0{encoded=append(encoded,'\n')};temporary:=path+".new";fd,err:=syscall.Open(temporary,syscall.O_WRONLY|syscall.O_CREAT|syscall.O_TRUNC|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0600);if err!=nil{return err};file:=os.NewFile(uintptr(fd),temporary);if _,err=file.Write(encoded);err==nil{err=file.Sync()};if closeErr:=file.Close();err==nil{err=closeErr};if err!=nil{_ = os.Remove(temporary);return err};if err=os.Chmod(temporary,0600);err==nil{err=os.Rename(temporary,path)};return err}

type LinuxTerminalBroker struct{Credentials *LinuxCredentialExecutor;ControlGID uint32}
func NewLinuxTerminalBroker(credentials *LinuxCredentialExecutor,controlGID uint32)(*LinuxTerminalBroker,error){if credentials==nil||controlGID==0{return nil,ErrInvalidState};return &LinuxTerminalBroker{Credentials:credentials,ControlGID:controlGID},nil}
func terminalID()(TerminalSessionID,error){var random [16]byte;if _,err:=rand.Read(random[:]);err!=nil{return "",err};return TerminalSessionID("terminal-"+hex.EncodeToString(random[:])),nil}
func(executor *LinuxTerminalBroker)Issue(ctx context.Context,grant AccessGrant,request TerminalRequest)(TerminalSession,error){binding,err:=executor.Credentials.binding(ctx,grant.SiteID);if err!=nil{return TerminalSession{},err};id,err:=terminalID();if err!=nil{return TerminalSession{},err};if err=ensureAccessDirectory(linuxTerminalRoot,0710,0,int(executor.ControlGID));err!=nil{return TerminalSession{},err};directory:=linuxTerminalRoot+"/"+string(id);if err=os.Mkdir(directory,0700);err!=nil{return TerminalSession{},err};private:=directory+"/identity";if _,err=runFixedAccess(ctx,"/usr/bin/ssh-keygen",nil,"-q","-t","ed25519","-N","","-C","cyberpanel terminal="+string(id),"-f",private);err!=nil{return TerminalSession{},err};public,err:=os.ReadFile(private+".pub");if err!=nil{return TerminalSession{},err};key,err:=ParsePublicKey(strings.TrimSpace(string(public)));if err!=nil{return TerminalSession{},err};path:=linuxAuthorizedKeysRoot+"/cyberpanel-"+binding.Username;if err=ensureAuthorizedKeysRoot();err!=nil{return TerminalSession{},err};line:="restrict,from=\"127.0.0.1,::1\" "+key.AuthorizedKey()+" cyberpanel terminal="+string(id);if err=rewriteAuthorizedKeys(path,"terminal="+string(id),line);err!=nil{return TerminalSession{},err};privateMaterial,err:=os.ReadFile(private);if err!=nil{return TerminalSession{},err};defer wipeAccess(privateMaterial);hostKeyOutput,err:=runFixedAccess(ctx,"/usr/bin/ssh-keygen",nil,"-lf","/etc/ssh/ssh_host_ed25519_key.pub","-E","sha256");if err!=nil{return TerminalSession{},err};fields:=strings.Fields(string(hostKeyOutput));if len(fields)<2{return TerminalSession{},ErrIntegrity};now:=time.Now().UTC();return TerminalSession{ID:id,GrantID:grant.ID,Endpoint:"ssh://127.0.0.1:22/"+binding.Username,OneTimeToken:base64.RawStdEncoding.EncodeToString(privateMaterial),HostKeyFingerprint:fields[1],IssuedAt:now,ExpiresAt:now.Add(5*time.Minute),State:StateActive},nil}
func(executor *LinuxTerminalBroker)Revoke(ctx context.Context,session TerminalSession)error{if !validID(string(session.ID)){return ErrInvalidID};directory:=linuxTerminalRoot+"/"+string(session.ID);entries,err:=os.ReadDir(linuxAuthorizedKeysRoot);if err==nil{for _,entry:=range entries{if strings.HasPrefix(entry.Name(),"cyberpanel-"){_ = rewriteAuthorizedKeys(linuxAuthorizedKeysRoot+"/"+entry.Name(),"terminal="+string(session.ID),"")}}};if _,err=runFixedAccess(ctx,"/usr/bin/rm",nil,"-rf","--",directory);err!=nil&&!errors.Is(err,os.ErrNotExist){return err};return nil}
func wipeAccess(values ...[]byte){for _,value:=range values{for index:=range value{value[index]=0}}}

var _ CredentialExecutor=(*LinuxCredentialExecutor)(nil)
var _ TerminalBroker=(*LinuxTerminalBroker)(nil)
