//go:build linux

package access

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"time"
)

const linuxStagingSnapshotRoot="/var/lib/cyberpanel/staging-snapshots"
type LinuxStagingExecutor struct{Files *LinuxFileExecutor}
func NewLinuxStagingExecutor(files *LinuxFileExecutor)(*LinuxStagingExecutor,error){if files==nil{return nil,ErrInvalidState};return &LinuxStagingExecutor{Files:files},nil}
func(executor *LinuxStagingExecutor)siteRelease(ctx context.Context,site SiteID)(string,error){binding,err:=executor.Files.Resolver.ResolveAccessSite(ctx,site);if err!=nil{return "",err};if !validLinuxBinding(binding){return "",ErrIntegrity};return LinuxAccessSitesRoot+"/"+binding.SiteKey+"/roots/g"+strconv.FormatUint(binding.Generation,10)+"/releases/current",nil}
func randomStagingToken(prefix string)(string,error){var value [16]byte;if _,err:=rand.Read(value[:]);err!=nil{return "",err};return prefix+hex.EncodeToString(value[:]),nil}
func digestTree(ctx context.Context,path string)(string,error){command:=exec.CommandContext(ctx,"/usr/bin/find",path,"-xdev","-printf","%P\x00%y\x00%s\x00%T@\n");command.Env=[]string{"PATH=/usr/bin:/bin","LANG=C","LC_ALL=C"};hash:=sha256.New();command.Stdout=hash;var stderr strings.Builder;command.Stderr=&stderr;if err:=command.Run();err!=nil{return "",fmt.Errorf("digest tree: %w: %s",err,stderr.String())};return hex.EncodeToString(hash.Sum(nil)),nil}
func(executor *LinuxStagingExecutor)SnapshotSyncSource(ctx context.Context,s StagingSync)(SyncSnapshot,error){sourceSite,targetSite:=s.LiveSiteID,s.StagingSiteID;if s.Direction==SyncStagingToLive{sourceSite,targetSite=s.StagingSiteID,s.LiveSiteID};source,err:=executor.siteRelease(ctx,sourceSite);if err!=nil{return SyncSnapshot{},err};target,err:=executor.siteRelease(ctx,targetSite);if err!=nil{return SyncSnapshot{},err};if err=ensureAccessDirectory(linuxStagingSnapshotRoot,0700,0,0);err!=nil{return SyncSnapshot{},err};token,err:=randomStagingToken("snapshot-");if err!=nil{return SyncSnapshot{},err};destination:=linuxStagingSnapshotRoot+"/"+token;if err=os.Mkdir(destination,0700);err!=nil{return SyncSnapshot{},err};if err=os.Mkdir(destination+"/source",0700);err!=nil{return SyncSnapshot{},err};if err=os.Mkdir(destination+"/target",0700);err!=nil{return SyncSnapshot{},err};if _,err=runFixedAccess(ctx,"/usr/bin/rsync",nil,"--archive","--numeric-ids","--delete","--one-file-system","--",source+"/",destination+"/source/");err!=nil{return SyncSnapshot{},err};if _,err=runFixedAccess(ctx,"/usr/bin/rsync",nil,"--archive","--numeric-ids","--delete","--one-file-system","--",target+"/",destination+"/target/");err!=nil{return SyncSnapshot{},err};if syncHas(s.Components,SyncDatabase){if err=syncMariaDB(ctx,s.TargetDatabaseID,destination+"/target-database.sql");err!=nil{return SyncSnapshot{},err}};digest,err:=digestTree(ctx,destination);if err!=nil{return SyncSnapshot{},err};return SyncSnapshot{Token:token,Frontier:uint64(time.Now().UnixNano()),Digest:digest},nil}
func syncHas(components []SyncComponent,wanted SyncComponent)bool{for _,component:=range components{if component==wanted{return true}};return false}
func(executor *LinuxStagingExecutor)ApplyStagingSync(ctx context.Context,s StagingSync,snapshot SyncSnapshot)(SyncApplication,error){if !strings.HasPrefix(snapshot.Token,"snapshot-")||strings.Contains(snapshot.Token,"/"){return SyncApplication{},ErrInvalidID};application,err:=randomStagingToken("application-");if err!=nil{return SyncApplication{},err};workspace:=linuxStagingSnapshotRoot+"/"+application;if err=os.Mkdir(workspace,0700);err!=nil{return SyncApplication{},err};source:=linuxStagingSnapshotRoot+"/"+snapshot.Token+"/source";if syncHas(s.Components,SyncFiles)||syncHas(s.Components,SyncUploads){args:=[]string{"--archive","--numeric-ids","--one-file-system"};if s.DeleteExtraneous{args=append(args,"--delete")};for _,exclude:=range s.Excludes{args=append(args,"--exclude",exclude.String())};args=append(args,"--",source+"/",workspace+"/");if _,err=runFixedAccess(ctx,"/usr/bin/rsync",nil,args...);err!=nil{return SyncApplication{},err}};if syncHas(s.Components,SyncDatabase){if err=syncMariaDB(ctx,s.SourceDatabaseID,workspace+"/database.sql");err!=nil{return SyncApplication{},err}};digest,err:=digestTree(ctx,workspace);if err!=nil{return SyncApplication{},err};return SyncApplication{Token:application,Digest:digest,Receipt:accessReceipt("staging-apply",string(s.ID),digest)},nil}
func syncMariaDB(ctx context.Context,source,dumpPath string)error{if !validID(source){return ErrInvalidID};dump,err:=os.OpenFile(dumpPath,os.O_WRONLY|os.O_CREATE|os.O_EXCL,0600);if err!=nil{return err};command:=exec.CommandContext(ctx,"/usr/bin/mariadb-dump","--protocol=socket","--socket=/run/mysqld/mysqld.sock","--single-transaction","--skip-lock-tables",source);command.Env=[]string{"PATH=/usr/bin:/bin","LANG=C"};command.Stdout=dump;var stderr strings.Builder;command.Stderr=&stderr;err=command.Run();if closeErr:=dump.Close();err==nil{err=closeErr};if err!=nil{return fmt.Errorf("database snapshot: %w: %s",err,stderr.String())};return nil}
func(executor *LinuxStagingExecutor)VerifyStagingSync(ctx context.Context,s StagingSync,a SyncApplication)(string,error){if !strings.HasPrefix(a.Token,"application-")||strings.Contains(a.Token,"/"){return "",ErrInvalidID};digest,err:=digestTree(ctx,linuxStagingSnapshotRoot+"/"+a.Token);if err!=nil{return "",err};if digest!=a.Digest{return "",ErrIntegrity};return accessReceipt("staging-verify",string(s.ID),digest),nil}
func(executor *LinuxStagingExecutor)PromoteStagingSync(ctx context.Context,s StagingSync,a SyncApplication)(string,error){targetSite:=s.StagingSiteID;if s.Direction==SyncStagingToLive{targetSite=s.LiveSiteID};target,err:=executor.siteRelease(ctx,targetSite);if err!=nil{return "",err};workspace:=linuxStagingSnapshotRoot+"/"+a.Token;if syncHas(s.Components,SyncFiles)||syncHas(s.Components,SyncUploads){args:=[]string{"--archive","--numeric-ids","--one-file-system"};if s.DeleteExtraneous{args=append(args,"--delete")};args=append(args,"--exclude","database.sql","--",workspace+"/",target+"/");if _,err=runFixedAccess(ctx,"/usr/bin/rsync",nil,args...);err!=nil{return "",err}};if syncHas(s.Components,SyncDatabase){dump,err:=os.Open(workspace+"/database.sql");if err!=nil{return "",err};command:=exec.CommandContext(ctx,"/usr/bin/mariadb","--protocol=socket","--socket=/run/mysqld/mysqld.sock",s.TargetDatabaseID);command.Env=[]string{"PATH=/usr/bin:/bin","LANG=C"};command.Stdin=dump;var stderr strings.Builder;command.Stderr=&stderr;err=command.Run();dump.Close();if err!=nil{return "",fmt.Errorf("database restore: %w: %s",err,stderr.String())}};return accessReceipt("staging-promote",string(s.ID),a.Digest),nil}
func(executor *LinuxStagingExecutor)RollbackStagingSync(ctx context.Context,s StagingSync,a SyncApplication)(string,error){snapshot:=linuxStagingSnapshotRoot+"/"+s.SnapshotToken;if _,err:=os.Lstat(snapshot);err!=nil{return "",err};targetSite:=s.StagingSiteID;if s.Direction==SyncStagingToLive{targetSite=s.LiveSiteID};target,err:=executor.siteRelease(ctx,targetSite);if err!=nil{return "",err};if _,err=runFixedAccess(ctx,"/usr/bin/rsync",nil,"--archive","--numeric-ids","--delete","--one-file-system","--",snapshot+"/target/",target+"/");err!=nil{return "",err};if syncHas(s.Components,SyncDatabase){dump,openErr:=os.Open(snapshot+"/target-database.sql");if openErr!=nil{return "",openErr};command:=exec.CommandContext(ctx,"/usr/bin/mariadb","--protocol=socket","--socket=/run/mysqld/mysqld.sock",s.TargetDatabaseID);command.Env=[]string{"PATH=/usr/bin:/bin","LANG=C"};command.Stdin=dump;var stderr strings.Builder;command.Stderr=&stderr;runErr:=command.Run();dump.Close();if runErr!=nil{return "",fmt.Errorf("database rollback: %w: %s",runErr,stderr.String())}};return accessReceipt("staging-rollback",string(s.ID),a.Token),nil}
func(executor *LinuxStagingExecutor)ReleaseSyncSnapshot(ctx context.Context,s SyncSnapshot)error{if !strings.HasPrefix(s.Token,"snapshot-")||strings.Contains(s.Token,"/"){return ErrInvalidID};_,err:=runFixedAccess(ctx,"/usr/bin/rm",nil,"-rf","--",linuxStagingSnapshotRoot+"/"+s.Token);return err}

var _ StagingExecutor=(*LinuxStagingExecutor)(nil)
