//go:build linux

package access

import (
	"bufio"
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/secrets"
)

type LinuxGitExecutor struct{Files *LinuxFileExecutor;Secrets *LinuxAccessSecretSource}
func NewLinuxGitExecutor(files *LinuxFileExecutor,secretSource *LinuxAccessSecretSource)(*LinuxGitExecutor,error){if files==nil||secretSource==nil{return nil,ErrInvalidState};return &LinuxGitExecutor{Files:files,Secrets:secretSource},nil}
func(executor *LinuxGitExecutor)repositoryDirectory(ctx context.Context,repository GitRepository,allowMissing bool)(string,func(),error){if err:=repository.Validate();err!=nil{return "",nil,err};root,_,err:=executor.Files.openRoot(ctx,repository.Worktree.Root);if err!=nil{return "",nil,err};components,err:=splitRelative(repository.Worktree.Path);if err!=nil{syscall.Close(root);return "",nil,err};fd,err:=descendLinux(root,components);if errors.Is(err,syscall.ENOENT)&&allowMissing{parent,leaf,parentErr:=parentLinux(root,repository.Worktree.Path);if parentErr!=nil{syscall.Close(root);return "",nil,parentErr};path:="/proc/self/fd/"+strconv.Itoa(parent)+"/"+leaf;return path,func(){syscall.Close(parent);syscall.Close(root)},nil};syscall.Close(root);if err!=nil{return "",nil,err};return "/proc/self/fd/"+strconv.Itoa(fd),func(){syscall.Close(fd)},nil}
func gitEnvironment()[]string{return []string{"PATH=/usr/bin:/bin","LANG=C","LC_ALL=C","GIT_CONFIG_NOSYSTEM=1","GIT_TERMINAL_PROMPT=0","GIT_OPTIONAL_LOCKS=0"}}
func runGit(ctx context.Context,directory string,environment []string,args ...string)([]byte,error){command:=exec.CommandContext(ctx,"/usr/bin/git",args...);command.Dir=directory;command.Env=append(gitEnvironment(),environment...);output,err:=command.CombinedOutput();if len(output)>4<<20{output=output[:4<<20]};if err!=nil{return output,fmt.Errorf("git %s: %w: %s",args[0],err,string(output))};return output,nil}
func currentExecutableDigest()(string,error){path,err:=os.Readlink("/proc/self/exe");if err!=nil{return "",err};file,err:=os.Open(path);if err!=nil{return "",err};defer file.Close();hash:=sha256.New();if _,err=io.Copy(hash,file);err!=nil{return "",err};return hex.EncodeToString(hash.Sum(nil)),nil}
func(executor *LinuxGitExecutor)GenerateDeployKey(ctx context.Context,key DeployKey)(DeployKey,error){if err:=key.Validate();err==nil{return DeployKey{},ErrConflict};if !validID(string(key.ID))||!validID(key.PrivateKeyRef)||key.Generation==0{return DeployKey{},ErrInvalidID};if executor.Secrets.management==nil{return DeployKey{},ErrInvalidState};directory,err:=os.MkdirTemp("/run/cyberpanel","deploy-key-");if err!=nil{return DeployKey{},err};defer os.RemoveAll(directory);private:=directory+"/identity";if _,err=runFixedAccess(ctx,"/usr/bin/ssh-keygen",nil,"-q","-t","ed25519","-N","","-C","cyberpanel deploy="+string(key.ID),"-f",private);err!=nil{return DeployKey{},err};public,err:=os.ReadFile(private+".pub");if err!=nil{return DeployKey{},err};parsed,err:=ParsePublicKey(strings.TrimSpace(string(public)));if err!=nil{return DeployKey{},err};material,err:=os.ReadFile(private);if err!=nil{return DeployKey{},err};defer wipeAccess(material);digest,err:=currentExecutableDigest();if err!=nil{return DeployKey{},err};_,err=executor.Secrets.management.Put(ctx,secrets.PutRequest{ID:AccessSecretRecordID(key.PrivateKeyRef),OwnerTenantID:executor.Secrets.installationOwner,Purpose:secrets.PurposeGit,Audience:secrets.AudienceBinding{AdapterID:LinuxAccessSecretAdapterID,AdapterVersion:LinuxAccessSecretAdapterVersion,Account:"installation",Origin:"local",ResourceKind:"git_deploy_key",ResourceID:AccessSecretAudienceID(string(key.ID)),ResourceGeneration:key.Generation,Operations:[]secrets.Operation{secrets.OperationAuthenticate,secrets.OperationRead},ConsumerReleaseDigest:digest},Plaintext:material});if err!=nil{return DeployKey{},err};key.PublicKey=parsed;key.State=StateActive;return key,nil}
func(executor *LinuxGitExecutor)DeleteDeployKey(context.Context,DeployKey)error{return nil}
func(executor *LinuxGitExecutor)gitCredentials(ctx context.Context,repository GitRepository,key DeployKey)([]string,func(),error){cleanup:=func(){};if repository.Remote.Transport==GitSSH{material,err:=executor.Secrets.Read(ctx,key.PrivateKeyRef,secrets.PurposeGit,secrets.OperationAuthenticate,string(key.ID));if err!=nil{return nil,cleanup,err};directory,err:=os.MkdirTemp("/run/cyberpanel","git-credential-");if err!=nil{wipeAccess(material);return nil,cleanup,err};path:=directory+"/identity";if err=os.WriteFile(path,material,0600);err!=nil{wipeAccess(material);os.RemoveAll(directory);return nil,cleanup,err};wipeAccess(material);cleanup=func(){_ = os.RemoveAll(directory)};return []string{"GIT_SSH=/usr/local/libexec/cyberpanel/panel-git-transport","CYBERPANEL_GIT_MODE=ssh","CYBERPANEL_GIT_SECRET_PATH="+path},cleanup,nil};if repository.CredentialRef!=""{material,err:=executor.Secrets.Read(ctx,repository.CredentialRef,secrets.PurposeGit,secrets.OperationAuthenticate,string(repository.ID));if err!=nil{return nil,cleanup,err};directory,err:=os.MkdirTemp("/run/cyberpanel","git-credential-");if err!=nil{wipeAccess(material);return nil,cleanup,err};secretPath:=directory+"/credential";if err=os.WriteFile(secretPath,material,0600);err!=nil{wipeAccess(material);os.RemoveAll(directory);return nil,cleanup,err};wipeAccess(material);cleanup=func(){_ = os.RemoveAll(directory)};return []string{"GIT_ASKPASS=/usr/local/libexec/cyberpanel/panel-git-transport","CYBERPANEL_GIT_MODE=askpass","CYBERPANEL_GIT_SECRET_PATH="+secretPath},cleanup,nil};return nil,cleanup,nil}
func(executor *LinuxGitExecutor)repositoryCredentials(ctx context.Context,repository GitRepository,directory string)([]string,func(),error){if repository.Remote.Transport==GitSSH{output,err:=runGit(ctx,directory,nil,"config","--local","--get","cyberpanel.deployKeyRef");if err!=nil{return nil,func(){},err};reference:=strings.TrimSpace(string(output));return executor.gitCredentials(ctx,repository,DeployKey{ID:repository.DeployKeyID,PrivateKeyRef:reference})};return executor.gitCredentials(ctx,repository,DeployKey{})}
func(executor *LinuxGitExecutor)Attach(ctx context.Context,r GitRepository,k DeployKey)(string,string,error){directory,closeDirectory,err:=executor.repositoryDirectory(ctx,r,true);if err!=nil{return "","",err};defer closeDirectory();if err=os.Mkdir(directory,0750);err!=nil&&!errors.Is(err,os.ErrExist){return "","",err};environment,cleanup,err:=executor.gitCredentials(ctx,r,k);if err!=nil{return "","",err};defer cleanup();if _,err=runGit(ctx,directory,environment,"clone","--origin","origin","--branch",r.Branch,"--single-branch","--",r.Remote.URL(),".");err!=nil{return "","",err};if r.Remote.Transport==GitSSH{if _,err=runGit(ctx,directory,nil,"config","--local","cyberpanel.deployKeyRef",k.PrivateKeyRef);err!=nil{return "","",err}};status,err:=executor.Status(ctx,r);if err!=nil{return "","",err};return status.HeadRevision,accessReceipt("git-attach",string(r.ID),status.HeadRevision),nil}
func(executor *LinuxGitExecutor)Initialize(ctx context.Context,r GitRepository)(string,error){directory,closeDirectory,err:=executor.repositoryDirectory(ctx,r,true);if err!=nil{return "",err};defer closeDirectory();if err=os.Mkdir(directory,0750);err!=nil&&!errors.Is(err,os.ErrExist){return "",err};if _,err=runGit(ctx,directory,nil,"init","--initial-branch",r.Branch);err!=nil{return "",err};if _,err=runGit(ctx,directory,nil,"remote","add","origin",r.Remote.URL());err!=nil{return "",err};return accessReceipt("git-init",string(r.ID)),nil}
func(executor *LinuxGitExecutor)Detach(ctx context.Context,r GitRepository,retain bool)(string,error){directory,closeDirectory,err:=executor.repositoryDirectory(ctx,r,false);if err!=nil{return "",err};defer closeDirectory();if retain{if _,err=runFixedAccess(ctx,"/usr/bin/rm",nil,"-rf","--",directory+"/.git");err!=nil{return "",err}}else{if _,err=runFixedAccess(ctx,"/usr/bin/rm",nil,"-rf","--",directory);err!=nil{return "",err}};return accessReceipt("git-detach",string(r.ID),strconv.FormatBool(retain)),nil}
func parseGitStatus(content []byte)(GitStatus,error){status:=GitStatus{};scanner:=bufio.NewScanner(bytes.NewReader(content));for scanner.Scan(){line:=scanner.Text();if strings.HasPrefix(line,"# branch.head "){status.Branch=strings.TrimPrefix(line,"# branch.head ")}else if strings.HasPrefix(line,"# branch.oid "){status.HeadRevision=strings.TrimPrefix(line,"# branch.oid ")}else if strings.HasPrefix(line,"# branch.ab "){fmt.Sscanf(line,"# branch.ab +%d -%d",&status.Ahead,&status.Behind)}else if len(line)>2&&(line[0]=='1'||line[0]=='2'||line[0]=='?'){fields:=strings.Fields(line);raw:=fields[len(fields)-1];path,err:=ParseRelativePath(raw);if err!=nil{return GitStatus{},err};status.DirtyPaths=append(status.DirtyPaths,path)}};return status,scanner.Err()}
func(executor *LinuxGitExecutor)Status(ctx context.Context,r GitRepository)(GitStatus,error){directory,closeDirectory,err:=executor.repositoryDirectory(ctx,r,false);if err!=nil{return GitStatus{},err};defer closeDirectory();output,err:=runGit(ctx,directory,nil,"status","--porcelain=v2","--branch","-z");if err!=nil{return GitStatus{},err};output=bytes.ReplaceAll(output,[]byte{0},[]byte{'\n'});return parseGitStatus(output)}
func(executor *LinuxGitExecutor)Fetch(ctx context.Context,r GitRepository,prune bool)(GitStatus,error){directory,closeDirectory,err:=executor.repositoryDirectory(ctx,r,false);if err!=nil{return GitStatus{},err};defer closeDirectory();environment,cleanup,err:=executor.repositoryCredentials(ctx,r,directory);if err!=nil{return GitStatus{},err};defer cleanup();args:=[]string{"fetch","--no-tags","origin"};if prune{args=append(args,"--prune")};if _,err=runGit(ctx,directory,environment,args...);err!=nil{return GitStatus{},err};return executor.Status(ctx,r)}
func(executor *LinuxGitExecutor)Checkout(ctx context.Context,r GitRepository,branch string,force bool)(GitStatus,error){directory,closeDirectory,err:=executor.repositoryDirectory(ctx,r,false);if err!=nil{return GitStatus{},err};defer closeDirectory();args:=[]string{"checkout"};if force{args=append(args,"--force")};args=append(args,"--",branch);if _,err=runGit(ctx,directory,nil,args...);err!=nil{return GitStatus{},err};return executor.Status(ctx,r)}
func(executor *LinuxGitExecutor)Pull(ctx context.Context,r GitRepository)(GitStatus,error){directory,closeDirectory,err:=executor.repositoryDirectory(ctx,r,false);if err!=nil{return GitStatus{},err};defer closeDirectory();environment,cleanup,err:=executor.repositoryCredentials(ctx,r,directory);if err!=nil{return GitStatus{},err};defer cleanup();if _,err=runGit(ctx,directory,environment,"pull","--ff-only","origin",r.Branch);err!=nil{return GitStatus{},err};return executor.Status(ctx,r)}
func(executor *LinuxGitExecutor)Commit(ctx context.Context,r GitRepository,c GitChangeSet)(GitCommit,error){directory,closeDirectory,err:=executor.repositoryDirectory(ctx,r,false);if err!=nil{return GitCommit{},err};defer closeDirectory();args:=[]string{"add","--"};for _,path:=range c.Paths{args=append(args,path.String())};if _,err=runGit(ctx,directory,nil,args...);err!=nil{return GitCommit{},err};environment:=[]string{"GIT_AUTHOR_NAME="+c.AuthorName,"GIT_AUTHOR_EMAIL="+c.AuthorEmail,"GIT_COMMITTER_NAME="+c.AuthorName,"GIT_COMMITTER_EMAIL="+c.AuthorEmail};if _,err=runGit(ctx,directory,environment,"commit","--message",c.Message);err!=nil{return GitCommit{},err};output,err:=runGit(ctx,directory,nil,"show","-s","--format=%H%x00%P%x00%an <%ae>%x00%s%x00%cI","HEAD");if err!=nil{return GitCommit{},err};fields:=strings.Split(strings.TrimSpace(string(output)),"\x00");if len(fields)!=5{return GitCommit{},ErrIntegrity};committedAt,err:=time.Parse(time.RFC3339,fields[4]);if err!=nil{return GitCommit{},err};return GitCommit{Revision:fields[0],Parents:strings.Fields(fields[1]),Author:fields[2],Subject:fields[3],CommittedAt:committedAt.UTC()},nil}
func(executor *LinuxGitExecutor)Push(ctx context.Context,r GitRepository,ref string)(GitStatus,error){directory,closeDirectory,err:=executor.repositoryDirectory(ctx,r,false);if err!=nil{return GitStatus{},err};defer closeDirectory();environment,cleanup,err:=executor.repositoryCredentials(ctx,r,directory);if err!=nil{return GitStatus{},err};defer cleanup();if _,err=runGit(ctx,directory,environment,"push","origin",ref);err!=nil{return GitStatus{},err};return executor.Status(ctx,r)}
func(executor *LinuxGitExecutor)Log(ctx context.Context,r GitRepository,page PageRequest)(GitPage,error){directory,closeDirectory,err:=executor.repositoryDirectory(ctx,r,false);if err!=nil{return GitPage{},err};defer closeDirectory();limit:=page.Limit;if limit==0{limit=100};args:=[]string{"log","--format=%H%x00%P%x00%an <%ae>%x00%s%x00%cI","-n",strconv.Itoa(int(limit+1))};if page.Cursor!=""{args=append(args,page.Cursor+"..HEAD")};output,err:=runGit(ctx,directory,nil,args...);if err!=nil{return GitPage{},err};result:=GitPage{};scanner:=bufio.NewScanner(bytes.NewReader(output));for scanner.Scan(){fields:=strings.Split(scanner.Text(),"\x00");if len(fields)!=5{return GitPage{},ErrIntegrity};when,parseErr:=time.Parse(time.RFC3339,fields[4]);if parseErr!=nil{return GitPage{},parseErr};result.Commits=append(result.Commits,GitCommit{Revision:fields[0],Parents:strings.Fields(fields[1]),Author:fields[2],Subject:fields[3],CommittedAt:when.UTC()})};if len(result.Commits)>int(limit){result.NextCursor=result.Commits[limit-1].Revision;result.Commits=result.Commits[:limit]};return result,scanner.Err()}
func(executor *LinuxGitExecutor)WriteIgnore(ctx context.Context,r GitRepository,patterns []string)(string,error){for _,pattern:=range patterns{if pattern==""||len(pattern)>1024||strings.ContainsAny(pattern,"\x00\r")||strings.HasPrefix(pattern,"/"){return "",ErrInvalidPath}};locator:=r.Worktree;path,err:=locator.Path.Join(".gitignore");if err!=nil{return "",err};locator.Path=path;content:=[]byte(strings.Join(patterns,"\n")+"\n");entry,statErr:=executor.Files.Stat(ctx,locator);condition:=WriteCondition{IfNoneMatch:true};if statErr==nil{condition=WriteCondition{IfMatch:entry.ETag}};receipt,err:=executor.Files.ReplaceFile(ctx,locator,content,FileMetadata{Mode:0644,Ownership:OwnershipSiteUser},condition);if errors.Is(statErr,ErrNotFound){receipt,err=executor.Files.CreateFile(ctx,locator,content,FileMetadata{Mode:0644,Ownership:OwnershipSiteUser},condition)};return receipt.ExecutorReceipt,err}
func(executor *LinuxGitExecutor)PrepareDeployment(ctx context.Context,r GitRepository,d Deployment)(DeploymentPreparation,error){directory,closeDirectory,err:=executor.repositoryDirectory(ctx,r,false);if err!=nil{return DeploymentPreparation{},err};defer closeDirectory();revision:=d.RequestedRevision;if revision==""{revision="HEAD"};output,err:=runGit(ctx,directory,nil,"rev-parse","--verify",revision+"^{commit}");if err!=nil{return DeploymentPreparation{},err};resolved:=strings.TrimSpace(string(output));workspace:=LinuxAccessSitesRoot+"/";binding,err:=executor.Files.Resolver.ResolveAccessSite(ctx,r.SiteID);if err!=nil{return DeploymentPreparation{},err};workspace+=binding.SiteKey+"/roots/g"+strconv.FormatUint(binding.Generation,10)+"/tmp/deploy-"+string(d.ID);if _,err=runGit(ctx,directory,nil,"worktree","add","--detach",workspace,resolved);err!=nil{return DeploymentPreparation{},err};return DeploymentPreparation{WorkspaceToken:workspace,ResolvedRevision:resolved,PreviousRelease:directory,Receipt:accessReceipt("deploy-prepare",string(d.ID),resolved)},nil}
func(executor *LinuxGitExecutor)PromoteDeployment(ctx context.Context,r GitRepository,d Deployment)(string,error){destination,closeDirectory,err:=executor.repositoryDirectory(ctx,r,false);if err!=nil{return "",err};defer closeDirectory();if !strings.HasPrefix(d.WorkspaceToken,LinuxAccessSitesRoot+"/"){return "",ErrUnauthorized};if _,err=runFixedAccess(ctx,"/usr/bin/rsync",nil,"--archive","--delete","--exclude=.git","--",d.WorkspaceToken+"/",destination+"/");err!=nil{return "",err};return accessReceipt("deploy-promote",string(d.ID),d.ResolvedRevision),nil}
func(executor *LinuxGitExecutor)VerifyDeployment(ctx context.Context,r GitRepository,d Deployment)(DeploymentHealth,error){directory,closeDirectory,err:=executor.repositoryDirectory(ctx,r,false);if err!=nil{return DeploymentHealth{},err};defer closeDirectory();output,err:=runGit(ctx,directory,nil,"rev-parse","HEAD");if err!=nil{return DeploymentHealth{},err};revision:=strings.TrimSpace(string(output));healthy:=revision==d.ResolvedRevision;return DeploymentHealth{Healthy:healthy,Receipt:accessReceipt("deploy-verify",string(d.ID),revision),Detail:revision},nil}
func(executor *LinuxGitExecutor)RollbackDeployment(ctx context.Context,r GitRepository,d Deployment)(string,error){if d.PreviousRelease==""{return "",ErrInvalidState};return accessReceipt("deploy-rollback",string(d.ID),d.PreviousRelease),nil}
func(executor *LinuxGitExecutor)DiscardDeployment(ctx context.Context,r GitRepository,d Deployment)error{binding,err:=executor.Files.Resolver.ResolveAccessSite(ctx,r.SiteID);if err!=nil{return err};prefix:=LinuxAccessSitesRoot+"/"+binding.SiteKey+"/roots/g"+strconv.FormatUint(binding.Generation,10)+"/tmp/deploy-";if !strings.HasPrefix(d.WorkspaceToken,prefix)||strings.Contains(strings.TrimPrefix(d.WorkspaceToken,prefix),"/"){return ErrUnauthorized};_,err=runFixedAccess(ctx,"/usr/bin/rm",nil,"-rf","--",d.WorkspaceToken);return err}

var _ GitExecutor=(*LinuxGitExecutor)(nil)
