//go:build linux

package access

import (
	"bufio"
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"os/user"
	"sort"
	"strconv"
	"strings"
	"syscall"
	"time"
)

const LinuxAccessSitesRoot = "/var/lib/cyberpanel/sites"

type LinuxSiteBinding struct{SiteKey string;Username string;UID uint32;GID uint32;Generation uint64}
type LinuxSiteResolver interface{ResolveAccessSite(context.Context,SiteID)(LinuxSiteBinding,error)}
type LinuxSiteResolverFunc func(context.Context,SiteID)(LinuxSiteBinding,error)
func(function LinuxSiteResolverFunc)ResolveAccessSite(ctx context.Context,id SiteID)(LinuxSiteBinding,error){return function(ctx,id)}

type LinuxFileExecutor struct{Resolver LinuxSiteResolver}
func NewLinuxFileExecutor(resolver LinuxSiteResolver)(*LinuxFileExecutor,error){if resolver==nil{return nil,ErrInvalidState};return &LinuxFileExecutor{Resolver:resolver},nil}

func validLinuxBinding(binding LinuxSiteBinding)bool{if binding.Generation==0||binding.UID<1000||binding.GID!=binding.UID||binding.Username==""||len(binding.SiteKey)<3||!strings.HasPrefix(binding.SiteKey,"s-"){return false};for _,c:=range binding.SiteKey{if !(c>='a'&&c<='z'||c>='A'&&c<='Z'||c>='0'&&c<='9'||c=='-'||c=='_'||c=='.'){return false}};return true}
func(executor *LinuxFileExecutor)openRoot(ctx context.Context,root SiteRoot)(int,LinuxSiteBinding,error){if executor==nil||executor.Resolver==nil||root.Validate()!=nil{return -1,LinuxSiteBinding{},ErrInvalidPath};binding,err:=executor.Resolver.ResolveAccessSite(ctx,root.SiteID);if err!=nil{return -1,LinuxSiteBinding{},err};if !validLinuxBinding(binding){return -1,LinuxSiteBinding{},ErrIntegrity};suffix:="";switch root.Kind{case RootSite:suffix="releases/current";case RootPublic:suffix="releases/current/public";case RootPrivate:suffix="private";case RootLogs:suffix="logs";case RootStaging:suffix="tmp/staging";default:return -1,LinuxSiteBinding{},ErrInvalidPath};fd,err:=syscall.Open(LinuxAccessSitesRoot,syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if err!=nil{return -1,LinuxSiteBinding{},err};components:=[]string{binding.SiteKey,"roots","g"+strconv.FormatUint(binding.Generation,10)};components=append(components,strings.Split(suffix,"/")...);for _,component:=range components{next,openErr:=syscall.Openat(fd,component,syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if errors.Is(openErr,syscall.ENOENT)&&root.Kind==RootStaging&&component=="staging"{if mkdirErr:=syscall.Mkdirat(fd,component,0750);mkdirErr!=nil&&!errors.Is(mkdirErr,syscall.EEXIST){syscall.Close(fd);return -1,LinuxSiteBinding{},mkdirErr};next,openErr=syscall.Openat(fd,component,syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if openErr==nil{_ = syscall.Fchown(next,int(binding.UID),int(binding.GID))}};syscall.Close(fd);if openErr!=nil{return -1,LinuxSiteBinding{},openErr};fd=next};return fd,binding,nil}
func splitRelative(path RelativePath)([]string,error){if _,err:=ParseRelativePath(path.String());err!=nil{return nil,err};if path.IsRoot(){return nil,nil};return strings.Split(path.String(),"/"),nil}
func descendLinux(root int,components []string)(int,error){current,err:=syscall.Dup(root);if err!=nil{return -1,err};for _,component:=range components{next,openErr:=syscall.Openat(current,component,syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);syscall.Close(current);if openErr!=nil{return -1,openErr};current=next};return current,nil}
func parentLinux(root int,path RelativePath)(int,string,error){components,err:=splitRelative(path);if err!=nil||len(components)==0{return -1,"",ErrInvalidPath};parent,err:=descendLinux(root,components[:len(components)-1]);return parent,components[len(components)-1],err}
func statLinux(parent int,leaf string,path RelativePath)(FileEntry,error){info,err:=os.Lstat("/proc/self/fd/"+strconv.Itoa(parent)+"/"+leaf);if errors.Is(err,os.ErrNotExist){return FileEntry{},ErrNotFound};if err!=nil{return FileEntry{},err};kind:=EntryRegular;if info.IsDir(){kind=EntryDirectory}else if info.Mode()&os.ModeSymlink!=0{kind=EntrySymlink}else if !info.Mode().IsRegular(){return FileEntry{},ErrInvalidPath};metadata,ok:=info.Sys().(*syscall.Stat_t);if !ok{return FileEntry{},ErrIntegrity};owner,group:=strconv.FormatUint(uint64(metadata.Uid),10),strconv.FormatUint(uint64(metadata.Gid),10);if value,e:=user.LookupId(owner);e==nil{owner=value.Username};if value,e:=user.LookupGroupId(group);e==nil{group=value.Name};target:="";if kind==EntrySymlink{target,_=os.Readlink("/proc/self/fd/"+strconv.Itoa(parent)+"/"+leaf)};etag:=fileETag(metadata,kind,target);return FileEntry{Path:path,Kind:kind,Size:info.Size(),Mode:uint32(info.Mode().Perm()),Owner:owner,Group:group,ModifiedAt:info.ModTime().UTC(),ETag:etag,LinkTarget:target},nil}
func fileETag(stat *syscall.Stat_t,kind EntryKind,target string)string{sum:=sha256.Sum256([]byte(fmt.Sprintf("%d:%d:%d:%d:%d:%s:%s",stat.Dev,stat.Ino,stat.Size,stat.Mtim.Sec,stat.Mtim.Nsec,kind,target)));return hex.EncodeToString(sum[:])}
func mutationReceipt(entry FileEntry)FileMutationReceipt{return FileMutationReceipt{ETag:entry.ETag,Size:entry.Size,ExecutorReceipt:"fs-"+entry.ETag,CommittedAt:time.Now().UTC()}}
func checkCondition(entry FileEntry,exists bool,condition WriteCondition)error{if condition.IfNoneMatch&&exists{return ErrConflict};if condition.IfMatch!=""&&(!exists||entry.ETag!=condition.IfMatch){return ErrConflict};return nil}

func(executor *LinuxFileExecutor)List(ctx context.Context,root SiteRoot,directory RelativePath,page PageRequest)(FilePage,error){fd,_,err:=executor.openRoot(ctx,root);if err!=nil{return FilePage{},err};defer syscall.Close(fd);components,err:=splitRelative(directory);if err!=nil{return FilePage{},err};dir,err:=descendLinux(fd,components);if err!=nil{return FilePage{},err};duplicate,err:=syscall.Dup(dir);if err!=nil{syscall.Close(dir);return FilePage{},err};file:=os.NewFile(uintptr(duplicate),"access-list");infos,err:=file.Readdir(-1);file.Close();if err!=nil{syscall.Close(dir);return FilePage{},err};sort.Slice(infos,func(i,j int)bool{return infos[i].Name()<infos[j].Name()});start:=0;if page.Cursor!=""{for start<len(infos)&&infos[start].Name()<=page.Cursor{start++}};limit:=int(page.Limit);if limit==0{limit=200};end:=start+limit;if end>len(infos){end=len(infos)};result:=FilePage{};for _,info:=range infos[start:end]{child,parseErr:=directory.Join(info.Name());if parseErr!=nil{syscall.Close(dir);return FilePage{},parseErr};entry,statErr:=statLinux(dir,info.Name(),child);if statErr!=nil{syscall.Close(dir);return FilePage{},statErr};result.Entries=append(result.Entries,entry)};if end<len(infos)&&end>start{result.NextCursor=infos[end-1].Name()};syscall.Close(dir);return result,nil}
func(executor *LinuxFileExecutor)Stat(ctx context.Context,locator FileLocator)(FileEntry,error){root,_,err:=executor.openRoot(ctx,locator.Root);if err!=nil{return FileEntry{},err};defer syscall.Close(root);if locator.Path.IsRoot(){var stat syscall.Stat_t;if err=syscall.Fstat(root,&stat);err!=nil{return FileEntry{},err};return FileEntry{Path:locator.Path,Kind:EntryDirectory,Mode:uint32(stat.Mode&0777),Size:stat.Size,ModifiedAt:time.Unix(stat.Mtim.Sec,stat.Mtim.Nsec).UTC(),ETag:fileETag(&stat,EntryDirectory,"")},nil};parent,leaf,err:=parentLinux(root,locator.Path);if err!=nil{return FileEntry{},err};defer syscall.Close(parent);return statLinux(parent,leaf,locator.Path)}
func(executor *LinuxFileExecutor)ReadRange(ctx context.Context,locator FileLocator,offset,length int64)([]byte,Integrity,error){if offset<0||length<0||length>MaxUploadChunk{return nil,Integrity{},ErrLimitExceeded};root,_,err:=executor.openRoot(ctx,locator.Root);if err!=nil{return nil,Integrity{},err};defer syscall.Close(root);parent,leaf,err:=parentLinux(root,locator.Path);if err!=nil{return nil,Integrity{},err};defer syscall.Close(parent);fd,err:=syscall.Openat(parent,leaf,syscall.O_RDONLY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if err!=nil{return nil,Integrity{},err};defer syscall.Close(fd);var stat syscall.Stat_t;if err=syscall.Fstat(fd,&stat);err!=nil||stat.Mode&syscall.S_IFMT!=syscall.S_IFREG{return nil,Integrity{},ErrInvalidPath};if offset>stat.Size{return nil,Integrity{},ErrInvalidState};if offset+length>stat.Size{length=stat.Size-offset};content:=make([]byte,length);read:=0;for read<len(content){count,readErr:=syscall.Pread(fd,content[read:],offset+int64(read));if readErr!=nil{return nil,Integrity{},readErr};if count==0{break};read+=count};content=content[:read];sum:=sha256.Sum256(content);return content,Integrity{Algorithm:"sha256",Digest:hex.EncodeToString(sum[:]),Size:int64(len(content))},nil}
func applyOwnership(fd int,metadata FileMetadata,binding LinuxSiteBinding)error{uid,gid:=int(binding.UID),int(binding.GID);if metadata.Ownership==OwnershipRuntime{uid=0};if err:=syscall.Fchown(fd,uid,gid);err!=nil{return err};return syscall.Fchmod(fd,metadata.Mode)}
func randomLinuxLeaf(prefix string)(string,error){var value [12]byte;if _,err:=io.ReadFull(rand.Reader,value[:]);err!=nil{return "",err};return prefix+hex.EncodeToString(value[:]),nil}
func writeLinuxFile(parent int,leaf string,content []byte,metadata FileMetadata,binding LinuxSiteBinding,condition WriteCondition,replace bool)(FileMutationReceipt,error){existing,err:=statLinux(parent,leaf,RelativePath{});exists:=err==nil;if err!=nil&&!errors.Is(err,ErrNotFound){return FileMutationReceipt{},err};if err=checkCondition(existing,exists,condition);err!=nil{return FileMutationReceipt{},err};if !replace&&exists{return FileMutationReceipt{},ErrConflict};temporary,err:=randomLinuxLeaf(".access-write-");if err!=nil{return FileMutationReceipt{},err};fd,err:=syscall.Openat(parent,temporary,syscall.O_WRONLY|syscall.O_CREAT|syscall.O_EXCL|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,metadata.Mode);if err!=nil{return FileMutationReceipt{},err};committed:=false;defer func(){syscall.Close(fd);if !committed{_ = os.Remove("/proc/self/fd/"+strconv.Itoa(parent)+"/"+temporary)}}();if err=applyOwnership(fd,metadata,binding);err==nil{for len(content)>0{count,writeErr:=syscall.Write(fd,content);if writeErr!=nil{err=writeErr;break};content=content[count:]}};if err==nil{err=syscall.Fsync(fd)};if err==nil{err=syscall.Renameat(parent,temporary,parent,leaf)};if err==nil{err=syscall.Fsync(parent)};if err!=nil{return FileMutationReceipt{},err};committed=true;entry,err:=statLinux(parent,leaf,RelativePath{});if err!=nil{return FileMutationReceipt{},err};return mutationReceipt(entry),nil}
func(executor *LinuxFileExecutor)CreateDirectory(ctx context.Context,l FileLocator,m FileMetadata)(FileMutationReceipt,error){if err:=m.Validate();err!=nil{return FileMutationReceipt{},err};root,binding,err:=executor.openRoot(ctx,l.Root);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(root);parent,leaf,err:=parentLinux(root,l.Path);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(parent);if err=syscall.Mkdirat(parent,leaf,m.Mode);err!=nil{return FileMutationReceipt{},err};fd,err:=syscall.Openat(parent,leaf,syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if err!=nil{return FileMutationReceipt{},err};err=applyOwnership(fd,m,binding);syscall.Close(fd);if err!=nil{return FileMutationReceipt{},err};entry,err:=statLinux(parent,leaf,l.Path);if err!=nil{return FileMutationReceipt{},err};return mutationReceipt(entry),syscall.Fsync(parent)}
func(executor *LinuxFileExecutor)CreateFile(ctx context.Context,l FileLocator,b []byte,m FileMetadata,c WriteCondition)(FileMutationReceipt,error){root,binding,err:=executor.openRoot(ctx,l.Root);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(root);parent,leaf,err:=parentLinux(root,l.Path);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(parent);return writeLinuxFile(parent,leaf,b,m,binding,c,false)}
func(executor *LinuxFileExecutor)ReplaceFile(ctx context.Context,l FileLocator,b []byte,m FileMetadata,c WriteCondition)(FileMutationReceipt,error){root,binding,err:=executor.openRoot(ctx,l.Root);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(root);parent,leaf,err:=parentLinux(root,l.Path);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(parent);return writeLinuxFile(parent,leaf,b,m,binding,c,true)}
func(executor *LinuxFileExecutor)Move(ctx context.Context,s,d FileLocator,c WriteCondition)(FileMutationReceipt,error){if s.Root!=d.Root{return FileMutationReceipt{},ErrUnauthorized};root,_,err:=executor.openRoot(ctx,s.Root);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(root);sp,sl,err:=parentLinux(root,s.Path);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(sp);dp,dl,err:=parentLinux(root,d.Path);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(dp);existing,e:=statLinux(dp,dl,d.Path);if e!=nil&&!errors.Is(e,ErrNotFound){return FileMutationReceipt{},e};if e=checkCondition(existing,e==nil,c);e!=nil{return FileMutationReceipt{},e};if err=syscall.Renameat(sp,sl,dp,dl);err!=nil{return FileMutationReceipt{},err};_ = syscall.Fsync(sp);_ = syscall.Fsync(dp);entry,err:=statLinux(dp,dl,d.Path);if err!=nil{return FileMutationReceipt{},err};return mutationReceipt(entry),nil}
func(executor *LinuxFileExecutor)Copy(ctx context.Context,s,d FileLocator,c WriteCondition)(FileMutationReceipt,error){if s.Root!=d.Root{return FileMutationReceipt{},ErrUnauthorized};root,binding,err:=executor.openRoot(ctx,s.Root);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(root);sourceParent,sourceLeaf,err:=parentLinux(root,s.Path);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(sourceParent);sourceFD,err:=syscall.Openat(sourceParent,sourceLeaf,syscall.O_RDONLY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(sourceFD);var sourceStat syscall.Stat_t;if err=syscall.Fstat(sourceFD,&sourceStat);err!=nil||sourceStat.Mode&syscall.S_IFMT!=syscall.S_IFREG{return FileMutationReceipt{},ErrInvalidPath};destinationParent,destinationLeaf,err:=parentLinux(root,d.Path);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(destinationParent);existing,statErr:=statLinux(destinationParent,destinationLeaf,d.Path);if statErr!=nil&&!errors.Is(statErr,ErrNotFound){return FileMutationReceipt{},statErr};if err=checkCondition(existing,statErr==nil,c);err!=nil{return FileMutationReceipt{},err};temporary,err:=randomLinuxLeaf(".access-copy-");if err!=nil{return FileMutationReceipt{},err};temporaryPath:="/proc/self/fd/"+strconv.Itoa(destinationParent)+"/"+temporary;if _,err=runFixedAccess(ctx,"/usr/bin/cp",nil,"--reflink=auto","--sparse=always","--","/proc/self/fd/"+strconv.Itoa(sourceFD),temporaryPath);err!=nil{return FileMutationReceipt{},err};temporaryFD,err:=syscall.Openat(destinationParent,temporary,syscall.O_RDONLY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if err!=nil{return FileMutationReceipt{},err};err=syscall.Fchown(temporaryFD,int(binding.UID),int(binding.GID));if err==nil{err=syscall.Fchmod(temporaryFD,sourceStat.Mode&0777)};if err==nil{err=syscall.Fsync(temporaryFD)};syscall.Close(temporaryFD);if err==nil{err=syscall.Renameat(destinationParent,temporary,destinationParent,destinationLeaf)};if err!=nil{_ = os.Remove(temporaryPath);return FileMutationReceipt{},err};entry,err:=statLinux(destinationParent,destinationLeaf,d.Path);return mutationReceipt(entry),err}
func(executor *LinuxFileExecutor)SetMetadata(ctx context.Context,l FileLocator,m FileMetadata,c WriteCondition)(FileMutationReceipt,error){entry,err:=executor.Stat(ctx,l);if err!=nil{return FileMutationReceipt{},err};if err=checkCondition(entry,true,c);err!=nil{return FileMutationReceipt{},err};root,binding,err:=executor.openRoot(ctx,l.Root);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(root);parent,leaf,err:=parentLinux(root,l.Path);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(parent);fd,err:=syscall.Openat(parent,leaf,syscall.O_RDONLY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if err!=nil{return FileMutationReceipt{},err};err=applyOwnership(fd,m,binding);syscall.Close(fd);if err!=nil{return FileMutationReceipt{},err};updated,err:=statLinux(parent,leaf,l.Path);return mutationReceipt(updated),err}
func(executor *LinuxFileExecutor)CreateSymlink(ctx context.Context,l FileLocator,t RelativePath,c WriteCondition)(FileMutationReceipt,error){if t.IsRoot(){return FileMutationReceipt{},ErrInvalidPath};root,binding,err:=executor.openRoot(ctx,l.Root);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(root);parent,leaf,err:=parentLinux(root,l.Path);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(parent);if _,e:=statLinux(parent,leaf,l.Path);e==nil||!errors.Is(e,ErrNotFound){return FileMutationReceipt{},ErrConflict};if err=syscall.Symlinkat(t.String(),parent,leaf);err!=nil{return FileMutationReceipt{},err};_ = os.Lchown("/proc/self/fd/"+strconv.Itoa(parent)+"/"+leaf,int(binding.UID),int(binding.GID));entry,err:=statLinux(parent,leaf,l.Path);return mutationReceipt(entry),err}

func(executor *LinuxFileExecutor)ensurePrivateDir(ctx context.Context,site SiteID,kind RootKind,name string)(int,LinuxSiteBinding,error){root,binding,err:=executor.openRoot(ctx,SiteRoot{SiteID:site,Kind:kind});if err!=nil{return -1,LinuxSiteBinding{},err};fd,err:=syscall.Openat(root,name,syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if errors.Is(err,syscall.ENOENT){if err=syscall.Mkdirat(root,name,0700);err==nil{fd,err=syscall.Openat(root,name,syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if err==nil{_ = syscall.Fchown(fd,int(binding.UID),int(binding.GID))}}};syscall.Close(root);return fd,binding,err}
func(executor *LinuxFileExecutor)MoveToTrash(ctx context.Context,l FileLocator,id TrashEntryID)(TrashEntry,FileMutationReceipt,error){trash,_,err:=executor.ensurePrivateDir(ctx,l.Root.SiteID,RootPrivate,"access-trash");if err!=nil{return TrashEntry{},FileMutationReceipt{},err};defer syscall.Close(trash);root,_,err:=executor.openRoot(ctx,l.Root);if err!=nil{return TrashEntry{},FileMutationReceipt{},err};defer syscall.Close(root);parent,leaf,err:=parentLinux(root,l.Path);if err!=nil{return TrashEntry{},FileMutationReceipt{},err};defer syscall.Close(parent);stored:=string(id);if err=syscall.Renameat(parent,leaf,trash,stored);err!=nil{return TrashEntry{},FileMutationReceipt{},err};entry,err:=statLinux(trash,stored,l.Path);if err!=nil{return TrashEntry{},FileMutationReceipt{},err};trashEntry:=TrashEntry{StoredToken:stored,Kind:entry.Kind,Size:entry.Size};return trashEntry,mutationReceipt(entry),nil}
func(executor *LinuxFileExecutor)RestoreTrash(ctx context.Context,e TrashEntry,d FileLocator,c WriteCondition)(FileMutationReceipt,error){trash,_,err:=executor.ensurePrivateDir(ctx,e.SiteID,RootPrivate,"access-trash");if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(trash);root,_,err:=executor.openRoot(ctx,d.Root);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(root);parent,leaf,err:=parentLinux(root,d.Path);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(parent);existing,se:=statLinux(parent,leaf,d.Path);if se!=nil&&!errors.Is(se,ErrNotFound){return FileMutationReceipt{},se};if err=checkCondition(existing,se==nil,c);err!=nil{return FileMutationReceipt{},err};if err=syscall.Renameat(trash,e.StoredToken,parent,leaf);err!=nil{return FileMutationReceipt{},err};entry,err:=statLinux(parent,leaf,d.Path);return mutationReceipt(entry),err}
func(executor *LinuxFileExecutor)PurgeTrash(ctx context.Context,e TrashEntry)(FileMutationReceipt,error){if !validID(e.StoredToken)||!validID(string(e.SiteID)){return FileMutationReceipt{},ErrInvalidID};trash,_,err:=executor.ensurePrivateDir(ctx,e.SiteID,RootPrivate,"access-trash");if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(trash);command:=exec.CommandContext(ctx,"/usr/bin/rm","-rf","--","/proc/self/fd/"+strconv.Itoa(trash)+"/"+e.StoredToken);command.Env=[]string{"PATH=/usr/bin:/bin"};if output,runErr:=command.CombinedOutput();runErr!=nil{return FileMutationReceipt{},fmt.Errorf("purge trash: %w: %s",runErr,string(output))};digest:=sha256.Sum256([]byte(e.StoredToken));return FileMutationReceipt{ExecutorReceipt:"purge-"+hex.EncodeToString(digest[:]),CommittedAt:time.Now().UTC()},nil}
func uploadHandle(site SiteID,id UploadID)string{return strconv.Itoa(len(site))+":"+string(site)+string(id)}
func parseUploadHandle(handle string)(SiteID,string,error){colon:=strings.IndexByte(handle,':');if colon<1{return "","",ErrInvalidID};size,err:=strconv.Atoi(handle[:colon]);if err!=nil||size<1||colon+1+size>=len(handle){return "","",ErrInvalidID};site:=SiteID(handle[colon+1:colon+1+size]);token:=handle[colon+1+size:];if !validID(string(site))||!validID(token){return "","",ErrInvalidID};return site,token,nil}
func(executor *LinuxFileExecutor)BeginUpload(ctx context.Context,s UploadSession)(string,error){directory,binding,err:=executor.ensurePrivateDir(ctx,s.Destination.Root.SiteID,RootPrivate,"access-uploads");if err!=nil{return "",err};defer syscall.Close(directory);leaf:=string(s.ID);fd,err:=syscall.Openat(directory,leaf,syscall.O_WRONLY|syscall.O_CREAT|syscall.O_EXCL|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0600);if err!=nil{return "",err};_ = syscall.Fchown(fd,int(binding.UID),int(binding.GID));err=syscall.Close(fd);return uploadHandle(s.Destination.Root.SiteID,s.ID),err}
func(executor *LinuxFileExecutor)AppendUpload(ctx context.Context,h string,c UploadChunk)error{site,leaf,err:=parseUploadHandle(h);if err!=nil{return err};directory,_,err:=executor.ensurePrivateDir(ctx,site,RootPrivate,"access-uploads");if err!=nil{return err};defer syscall.Close(directory);fd,err:=syscall.Openat(directory,leaf,syscall.O_WRONLY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if err!=nil{return err};defer syscall.Close(fd);written:=0;for written<len(c.Data){count,writeErr:=syscall.Pwrite(fd,c.Data[written:],c.Offset+int64(written));if writeErr!=nil{return writeErr};written+=count};return syscall.Fsync(fd)}
func(executor *LinuxFileExecutor)CommitUpload(ctx context.Context,s UploadSession)(FileMutationReceipt,error){site,leaf,err:=parseUploadHandle(s.Handle);if err!=nil||site!=s.Destination.Root.SiteID{return FileMutationReceipt{},ErrUnauthorized};directory,_,err:=executor.ensurePrivateDir(ctx,site,RootPrivate,"access-uploads");if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(directory);fd,err:=syscall.Openat(directory,leaf,syscall.O_RDONLY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if err!=nil{return FileMutationReceipt{},err};hash:=sha256.New();size,err:=io.Copy(hash,os.NewFile(uintptr(fd),"access-upload"));syscall.Close(fd);if err!=nil||size!=s.Integrity.Size||hex.EncodeToString(hash.Sum(nil))!=s.Integrity.Digest{return FileMutationReceipt{},ErrIntegrity};root,_,err:=executor.openRoot(ctx,s.Destination.Root);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(root);parent,target,err:=parentLinux(root,s.Destination.Path);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(parent);if err=syscall.Renameat(directory,leaf,parent,target);err!=nil{return FileMutationReceipt{},err};entry,err:=statLinux(parent,target,s.Destination.Path);return mutationReceipt(entry),err}
func(executor *LinuxFileExecutor)AbortUpload(ctx context.Context,h string)error{site,leaf,err:=parseUploadHandle(h);if err!=nil{return err};directory,_,err:=executor.ensurePrivateDir(ctx,site,RootPrivate,"access-uploads");if err!=nil{return err};defer syscall.Close(directory);err=os.Remove("/proc/self/fd/"+strconv.Itoa(directory)+"/"+leaf);if errors.Is(err,os.ErrNotExist){return nil};return err}
func(executor *LinuxFileExecutor)OpenDownload(ctx context.Context,l DownloadLease)(DownloadLease,error){entry,err:=executor.Stat(ctx,l.Source);if err!=nil||entry.Kind!=EntryRegular{return DownloadLease{},ErrInvalidPath};_,integrity,err:=executor.ReadRange(ctx,l.Source,0,entry.Size);if err!=nil{return DownloadLease{},err};l.Handle="download-"+integrity.Digest;l.Integrity=integrity;return l,nil}
func(executor *LinuxFileExecutor)ReadDownload(ctx context.Context,l DownloadLease,o,n int64)([]byte,error){content,_,err:=executor.ReadRange(ctx,l.Source,o,n);return content,err}
func(executor *LinuxFileExecutor)CloseDownload(context.Context,DownloadLease)error{return nil}

func(executor *LinuxFileExecutor)CreateArchive(ctx context.Context,a Archive)(Archive,error){if len(a.Sources)==0{return Archive{},ErrInvalidState};root,binding,err:=executor.openRoot(ctx,a.Destination.Root);if err!=nil{return Archive{},err};defer syscall.Close(root);parent,leaf,err:=parentLinux(root,a.Destination.Path);if err!=nil{return Archive{},err};defer syscall.Close(parent);temporary,err:=randomLinuxLeaf(".archive-");if err!=nil{return Archive{},err};archivePath:="/proc/self/fd/"+strconv.Itoa(parent)+"/"+temporary;binary:="/usr/bin/tar";arguments:=[]string{"--create","--file",archivePath,"--no-recursion","--"};switch a.Format{case ArchiveTarGZ:arguments=[]string{"--create","--gzip","--file",archivePath,"--no-recursion","--"};case ArchiveTarZST:arguments=[]string{"--create","--zstd","--file",archivePath,"--no-recursion","--"};case ArchiveZIP:binary="/usr/bin/zip";arguments=[]string{"-r","-q",archivePath,"--"}};for _,source:=range a.Sources{if source.Root!=a.Destination.Root||source.Path.IsRoot(){return Archive{},ErrUnauthorized};arguments=append(arguments,source.Path.String())};command:=exec.CommandContext(ctx,binary,arguments...);command.Dir="/proc/self/fd/"+strconv.Itoa(root);command.Env=[]string{"PATH=/usr/bin:/bin","LANG=C"};if output,runErr:=command.CombinedOutput();runErr!=nil{return Archive{},fmt.Errorf("archive: %w: %s",runErr,string(output))};if err=os.Chown(archivePath,int(binding.UID),int(binding.GID));err==nil{err=syscall.Renameat(parent,temporary,parent,leaf)};if err!=nil{return Archive{},err};entry,err:=statLinux(parent,leaf,a.Destination.Path);if err!=nil{return Archive{},err};a.State=OperationCommitted;a.Integrity=Integrity{Algorithm:"sha256",Digest:entry.ETag,Size:entry.Size};a.Receipt="archive-"+entry.ETag;return a,nil}
func(executor *LinuxFileExecutor)ExtractArchive(ctx context.Context,a,d FileLocator,p ExtractPolicy)(FileMutationReceipt,error){if a.Root!=d.Root{return FileMutationReceipt{},ErrUnauthorized};root,_,err:=executor.openRoot(ctx,a.Root);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(root);archiveParent,archiveLeaf,err:=parentLinux(root,a.Path);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(archiveParent);destinationComponents,_:=splitRelative(d.Path);destination,err:=descendLinux(root,destinationComponents);if err!=nil{return FileMutationReceipt{},err};defer syscall.Close(destination);archivePath:="/proc/self/fd/"+strconv.Itoa(archiveParent)+"/"+archiveLeaf;header:=make([]byte,4);archiveFD,openErr:=syscall.Openat(archiveParent,archiveLeaf,syscall.O_RDONLY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if openErr!=nil{return FileMutationReceipt{},openErr};_,_ = syscall.Read(archiveFD,header);syscall.Close(archiveFD);zipArchive:=bytes.HasPrefix(header,[]byte{'P','K',3,4});if err=validateArchiveMembers(ctx,archivePath,zipArchive,p.MaxFiles);err!=nil{return FileMutationReceipt{},err};binary:="/usr/bin/tar";arguments:=[]string{"--extract","--file",archivePath,"--directory","/proc/self/fd/"+strconv.Itoa(destination),"--no-same-owner","--no-same-permissions","--delay-directory-restore","--skip-old-files"};if zipArchive{binary="/usr/bin/unzip";arguments=[]string{"-q","-n",archivePath,"-d","/proc/self/fd/"+strconv.Itoa(destination)};if p.Overwrite{arguments[1]="-o"}}else{if p.Overwrite{arguments[len(arguments)-1]="--overwrite"};if p.StripComponents>0{arguments=append(arguments,"--strip-components",strconv.Itoa(int(p.StripComponents)))}};command:=exec.CommandContext(ctx,binary,arguments...);command.Env=[]string{"PATH=/usr/bin:/bin","LANG=C"};if output,runErr:=command.CombinedOutput();runErr!=nil{return FileMutationReceipt{},fmt.Errorf("extract archive: %w: %s",runErr,string(output))};digest:=sha256.Sum256([]byte(a.Path.String()+"\x00"+d.Path.String()));return FileMutationReceipt{ExecutorReceipt:"extract-"+hex.EncodeToString(digest[:]),CommittedAt:time.Now().UTC()},nil}
func validateArchiveMembers(ctx context.Context,path string,zipArchive bool,maximum uint32)error{if maximum==0{maximum=100000};binary:="/usr/bin/tar";arguments:=[]string{"--list","--file",path};if zipArchive{binary="/usr/bin/unzip";arguments=[]string{"-Z1",path}};command:=exec.CommandContext(ctx,binary,arguments...);command.Env=[]string{"PATH=/usr/bin:/bin","LANG=C"};output,err:=command.Output();if err!=nil||len(output)>64<<20{return ErrIntegrity};count:=uint32(0);scanner:=bufio.NewScanner(bytes.NewReader(output));scanner.Buffer(make([]byte,4096),4096);for scanner.Scan(){name:=strings.TrimSuffix(scanner.Text(),"/");if name==""{continue};if _,err=ParseRelativePath(name);err!=nil{return ErrInvalidPath};count++;if count>maximum{return ErrLimitExceeded}};return scanner.Err()}

var _ FileExecutor=(*LinuxFileExecutor)(nil)
