package integrations

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"net/url"
	"strings"
	"time"
)

type SecretManager interface {
	StoreProviderSecret(context.Context, BindingRequest, []byte) (SecretRef, uint64, string, error)
	RotateProviderSecret(context.Context, ProviderBinding, []byte) (uint64, string, error)
	RevokeProviderSecret(context.Context, ProviderBinding) error
}

type BindingRequest struct {
	ID BindingID `json:"id"`
	TenantID TenantID `json:"tenant_id,omitempty"`
	Kind ProviderKind `json:"kind"`
	DisplayName string `json:"display_name"`
	Purpose CredentialPurpose `json:"purpose"`
	Endpoint EndpointPolicy `json:"endpoint"`
	Secret []byte `json:"-"`
}

type BindingService struct { Store Store; Secrets SecretManager; Providers map[ProviderKind]Provider; Now func() time.Time }
func (service BindingService) now() time.Time { if service.Now != nil { return service.Now().UTC() }; return time.Now().UTC() }

func (service BindingService) Enroll(ctx context.Context, request BindingRequest) (ProviderBinding, error) {
	if service.Store == nil || service.Secrets == nil || !request.Kind.Valid() || !purposeMatches(request.Kind,request.Purpose) || strings.TrimSpace(request.DisplayName)=="" || len(request.DisplayName)>128 || len(request.Secret) == 0 || len(request.Secret) > 1<<20 { wipeIntegrationSecret(request.Secret);return ProviderBinding{}, ErrInvalid }
	if err := requireID("binding", string(request.ID)); err != nil { wipeIntegrationSecret(request.Secret);return ProviderBinding{}, err }; if request.TenantID != "" { if err := requireID("tenant", string(request.TenantID)); err != nil { wipeIntegrationSecret(request.Secret);return ProviderBinding{}, err } }
	if err := request.Endpoint.Validate(); err != nil { wipeIntegrationSecret(request.Secret);return ProviderBinding{}, err }
	if err:=validateProviderEndpoint(request.Kind,request.Endpoint);err!=nil{wipeIntegrationSecret(request.Secret);return ProviderBinding{},err}
	provider := service.Providers[request.Kind]; if provider == nil { wipeIntegrationSecret(request.Secret);return ProviderBinding{}, ErrUnsupported }
	secretRef, version, bindingDigest, err := service.Secrets.StoreProviderSecret(ctx, request, request.Secret); if err != nil { return ProviderBinding{}, err }
	now := service.now(); provisional := ProviderBinding{ID: request.ID, TenantID: request.TenantID, Kind: request.Kind, DisplayName: request.DisplayName, Purpose: request.Purpose, SecretRef: secretRef, SecretVersion: version, SecretBindingDigest:bindingDigest, Endpoint: request.Endpoint, Capabilities: CapabilitySet{SchemaVersion: 1, ProviderVersion: "pending", Capabilities: []Capability{CapabilityHealth}, DiscoveredAt: now, Digest: capabilityDigest([]Capability{CapabilityHealth})}, State: BindingPending, Generation: 1, CreatedAt: now, UpdatedAt: now}
	if err := provider.ValidateCredential(ctx, provisional); err != nil { _ = service.Secrets.RevokeProviderSecret(ctx, provisional); return ProviderBinding{}, err }
	capabilities, err := provider.DiscoverCapabilities(ctx, provisional); if err != nil { _ = service.Secrets.RevokeProviderSecret(ctx, provisional); return ProviderBinding{}, err }
	if err := capabilities.Validate(); err != nil { _ = service.Secrets.RevokeProviderSecret(ctx, provisional); return ProviderBinding{}, err }
	if capabilities.Digest != capabilityDigest(capabilities.Capabilities) { _ = service.Secrets.RevokeProviderSecret(ctx, provisional); return ProviderBinding{}, ErrIntegrity }
	for _,required:=range requiredCapabilities(request.Kind){if !capabilities.Has(required){_ = service.Secrets.RevokeProviderSecret(ctx,provisional);return ProviderBinding{},ErrUnsupported}}
	if request.Kind==ProviderCloudflare&&!capabilities.Has(CapabilityAtomicCAS)&&!capabilities.Has(CapabilityObserveApply){_ = service.Secrets.RevokeProviderSecret(ctx,provisional);return ProviderBinding{},ErrUnsupported}
	provisional.Capabilities, provisional.State = capabilities, BindingActive
	if err := provisional.Validate(); err != nil { _ = service.Secrets.RevokeProviderSecret(ctx, provisional); return ProviderBinding{}, err }
	if err := service.Store.CreateBinding(ctx, provisional); err != nil { _ = service.Secrets.RevokeProviderSecret(ctx, provisional); return ProviderBinding{}, err }
	return provisional, nil
}

func (service BindingService) Rotate(ctx context.Context, id BindingID, expectedGeneration, expectedSecretVersion uint64, secret []byte) (ProviderBinding, error) {
	if service.Store==nil||service.Secrets==nil||len(secret)==0||len(secret)>1<<20{wipeIntegrationSecret(secret);return ProviderBinding{},ErrInvalid};binding, err := service.Store.LoadBinding(ctx, id); if err != nil { wipeIntegrationSecret(secret);return ProviderBinding{}, err }; if binding.Generation != expectedGeneration || binding.SecretVersion != expectedSecretVersion { wipeIntegrationSecret(secret);return ProviderBinding{}, ErrStaleGeneration };provider := service.Providers[binding.Kind]; if provider == nil { wipeIntegrationSecret(secret);return ProviderBinding{}, ErrUnsupported }
	version, bindingDigest, err := service.Secrets.RotateProviderSecret(ctx, binding, secret); if err != nil { return ProviderBinding{}, err }
	previous := binding; binding.SecretVersion, binding.SecretBindingDigest, binding.Generation, binding.UpdatedAt = version, bindingDigest, binding.Generation+1, service.now()
	if err := provider.ValidateCredential(ctx, binding); err != nil { return ProviderBinding{}, err }
	capabilities, err := provider.DiscoverCapabilities(ctx, binding); if err != nil { return ProviderBinding{}, err };if err=capabilities.Validate();err!=nil||capabilities.Digest!=capabilityDigest(capabilities.Capabilities){return ProviderBinding{},ErrIntegrity};for _,required:=range requiredCapabilities(binding.Kind){if !capabilities.Has(required){return ProviderBinding{},ErrUnsupported}};if binding.Kind==ProviderCloudflare&&!capabilities.Has(CapabilityAtomicCAS)&&!capabilities.Has(CapabilityObserveApply){return ProviderBinding{},ErrUnsupported};binding.Capabilities = capabilities
	if err := service.Store.UpdateBinding(ctx, binding, previous.Generation); err != nil { return ProviderBinding{}, err }
	return binding, nil
}

func (service BindingService) SetSuspended(ctx context.Context, id BindingID, expected uint64, suspended bool) (ProviderBinding, error) { binding, err := service.Store.LoadBinding(ctx, id); if err != nil { return ProviderBinding{}, err }; if binding.Generation != expected { return ProviderBinding{}, ErrStaleGeneration }; if binding.State == BindingRevoked || binding.State == BindingDeleted { return ProviderBinding{}, ErrConflict }; previous := binding.Generation; if suspended { binding.State = BindingSuspended } else { binding.State = BindingActive }; binding.Generation++; binding.UpdatedAt = service.now(); if err := service.Store.UpdateBinding(ctx, binding, previous); err != nil { return ProviderBinding{}, err }; return binding, nil }
func (service BindingService) ObserveHealth(ctx context.Context, id BindingID) (ProviderHealth, error) { binding, err := service.Store.LoadBinding(ctx, id); if err != nil { return ProviderHealth{}, err }; provider := service.Providers[binding.Kind]; if provider == nil { return ProviderHealth{}, ErrUnsupported }; health, err := provider.Health(ctx, binding); if err != nil { return ProviderHealth{}, err }; if health.BindingID != id || health.CapabilitiesDigest != binding.Capabilities.Digest || health.ObservedAt.IsZero() || !health.StaleAfter.After(health.ObservedAt) { return ProviderHealth{}, ErrIntegrity }; if err := service.Store.SaveHealth(ctx, health); err != nil { return ProviderHealth{}, err }; return health, nil }
func (service BindingService) Delete(ctx context.Context, id BindingID, expected uint64) error { binding, err := service.Store.LoadBinding(ctx, id); if err != nil { return err }; if binding.Generation != expected { return ErrStaleGeneration }; provider := service.Providers[binding.Kind]; if provider == nil { return ErrUnsupported }; now:=service.now();if err := provider.RevokeCredential(ctx, binding); err != nil { return err };if journal,ok:=service.Store.(interface{SaveBindingTombstone(context.Context,BindingTombstone)error});ok{deleting:=binding;deleting.State=BindingDeleting;deleting.Generation++;deleting.UpdatedAt=now;if err=journal.SaveBindingTombstone(ctx,BindingTombstone{Binding:deleting,ProviderRevokedAt:now});err!=nil{return err}}; if err := service.Secrets.RevokeProviderSecret(ctx, binding); err != nil { return err }; previous := binding.Generation; binding.State, binding.Generation, binding.UpdatedAt = BindingDeleted, binding.Generation+1, now; if err=service.Store.UpdateBinding(ctx, binding, previous);err!=nil{return err};if journal,ok:=service.Store.(interface{SaveBindingTombstone(context.Context,BindingTombstone)error});ok{if err=journal.SaveBindingTombstone(ctx,BindingTombstone{Binding:binding,ProviderRevokedAt:now,SecretRevokedAt:now});err!=nil{return err}};return nil }

func digest(value any) (string, error) { payload, err := json.Marshal(value); if err != nil { return "", err }; sum := sha256.Sum256(payload); return hex.EncodeToString(sum[:]), nil }
func observedRRSetDigest(rrset *CloudflareRRSet) string { if rrset != nil { return rrset.Digest }; sum:=sha256.Sum256([]byte("cloudflare.rrset.absent.v1"));return hex.EncodeToString(sum[:]) }
func purposeMatches(kind ProviderKind,purpose CredentialPurpose)bool{switch kind{case ProviderCloudflare:return purpose==PurposeDNS;case ProviderAWSS3,ProviderWasabi,ProviderBackblaze,ProviderDigitalOcean,ProviderMinIO,ProviderGenericS3,ProviderGoogleDrive,ProviderSFTP:return purpose==PurposeBackup;case ProviderExternalMail:return purpose==PurposeMailRelay;case ProviderImunify:return purpose==PurposeSecurity;case ProviderDockerHub:return purpose==PurposeRegistry;case ProviderNotificationSMTP,ProviderNotificationWebhook:return purpose==PurposeNotification};return false}
func requiredCapabilities(kind ProviderKind)[]Capability{switch kind{case ProviderCloudflare:return []Capability{CapabilityHealth,CapabilityDNSZones,CapabilityDNSRRsets,CapabilityDNSProxy,CapabilityDNSChallenge};case ProviderAWSS3,ProviderWasabi,ProviderBackblaze,ProviderDigitalOcean,ProviderMinIO,ProviderGenericS3,ProviderGoogleDrive,ProviderSFTP:return []Capability{CapabilityHealth,CapabilityObjectList,CapabilityObjectResume,CapabilityObjectChecksum};case ProviderExternalMail:return []Capability{CapabilityHealth,CapabilityMailRelay};case ProviderImunify:return []Capability{CapabilityHealth,CapabilitySecurityScan};case ProviderDockerHub:return []Capability{CapabilityHealth,CapabilityOCIResolve,CapabilityOCIPull};case ProviderNotificationSMTP,ProviderNotificationWebhook:return []Capability{CapabilityHealth,CapabilityNotify}};return nil}
func validateProviderEndpoint(kind ProviderKind,endpoint EndpointPolicy)error{parsed,err:=url.Parse(endpoint.URL);if err!=nil{return ErrInvalid};host:=strings.ToLower(parsed.Hostname());suffix:=func(value string)bool{return host==value||strings.HasSuffix(host,"."+value)};switch kind{case ProviderCloudflare:if host!="api.cloudflare.com"{return ErrPolicyDenied};case ProviderAWSS3:if !suffix("amazonaws.com"){return ErrPolicyDenied};case ProviderWasabi:if !suffix("wasabisys.com"){return ErrPolicyDenied};case ProviderBackblaze:if !suffix("backblazeb2.com"){return ErrPolicyDenied};case ProviderDigitalOcean:if !suffix("digitaloceanspaces.com"){return ErrPolicyDenied};case ProviderGoogleDrive:if host!="www.googleapis.com"&&host!="oauth2.googleapis.com"{return ErrPolicyDenied};case ProviderDockerHub:if host!="registry-1.docker.io"&&host!="auth.docker.io"&&host!="hub.docker.com"{return ErrPolicyDenied};case ProviderImunify:if parsed.Scheme!="local"||host!="imunify"{return ErrPolicyDenied};case ProviderMinIO,ProviderGenericS3,ProviderSFTP,ProviderExternalMail,ProviderNotificationSMTP,ProviderNotificationWebhook:default:return ErrUnsupported};return nil}

type CloudflareCoordinator struct { Store Store; Provider CloudflareProvider; Now func() time.Time }
func (coordinator CloudflareCoordinator) now() time.Time { if coordinator.Now != nil { return coordinator.Now().UTC() }; return time.Now().UTC() }

func (coordinator CloudflareCoordinator) Apply(ctx context.Context, binding ProviderBinding, change CloudflareChange) (ProviderEffect, error) {
	if coordinator.Store == nil || coordinator.Provider == nil || binding.Kind != ProviderCloudflare || binding.State != BindingActive { return ProviderEffect{}, ErrPolicyDenied }
	if err := change.Binding.Validate(binding.Capabilities); err != nil { return ProviderEffect{}, err }; if change.Binding.BindingID != binding.ID || change.Effect.BindingID != binding.ID { return ProviderEffect{}, ErrConflict }
	requestDigest, err := digest(struct{ Kind DNSMutationKind; Before *CloudflareRRSet; Desired *CloudflareRRSet; Revision string }{change.Kind, change.Before, change.Desired, change.ExpectedRevision}); if err != nil { return ProviderEffect{}, err }
	change.Effect.RequestDigest, change.Effect.State, change.Effect.CreatedAt, change.Effect.UpdatedAt = requestDigest, EffectAdmitted, coordinator.now(), coordinator.now()
	effect, created, err := coordinator.Store.AdmitEffect(ctx, change.Effect); if err != nil { return ProviderEffect{}, err }; if !created { if effect.State == EffectCommitted { return effect, nil }; return ProviderEffect{}, ErrConflict }
	if err := coordinator.Provider.DryRun(ctx, binding, change); err != nil { return ProviderEffect{}, coordinator.fail(ctx, effect, EffectFailed, err) }
	effect.State, effect.Attempt, effect.UpdatedAt = EffectApplying, effect.Attempt+1, coordinator.now(); _ = coordinator.Store.UpdateEffect(ctx, effect)
	if change.Binding.Concurrency == ConcurrencyAtomicCAS { return coordinator.applyAtomic(ctx, binding, change, effect) }
	return coordinator.applyObserve(ctx, binding, change, effect)
}

func (coordinator CloudflareCoordinator) applyAtomic(ctx context.Context, binding ProviderBinding, change CloudflareChange, effect ProviderEffect) (ProviderEffect, error) { receipt, err := coordinator.Provider.ApplyConditional(ctx, binding, change); if err != nil { return ProviderEffect{}, coordinator.fail(ctx, effect, classifyEffect(err), err) }; if receipt.EffectID != effect.ID || !validDigest(receipt.OutputDigest) || receipt.ProviderRevision == "" || receipt.ProviderReceipt == "" { return ProviderEffect{}, coordinator.fail(ctx, effect, EffectAmbiguous, ErrIntegrity) }; effect.BeforeDigest, effect.OutputDigest, effect.ObservedDigest, effect.ProviderReceipt, effect.ExpectedRevision, effect.State, effect.UpdatedAt = receipt.BeforeDigest, receipt.OutputDigest, receipt.OutputDigest, receipt.ProviderReceipt, receipt.ProviderRevision, EffectCommitted, coordinator.now(); if err := coordinator.Store.UpdateEffect(ctx, effect); err != nil { return ProviderEffect{}, err }; return effect, nil }

func (coordinator CloudflareCoordinator) applyObserve(ctx context.Context, binding ProviderBinding, change CloudflareChange, effect ProviderEffect) (ProviderEffect, error) {
	var before *CloudflareRRSet; var err error
	target := change.Desired; if target == nil { target = change.Before }; if target == nil { return ProviderEffect{}, coordinator.fail(ctx, effect, EffectFailed, ErrInvalid) }
	before, err = coordinator.Provider.ObserveRRSet(ctx, binding, target.ZoneID, target.Owner, target.Type); if err != nil { return ProviderEffect{}, coordinator.fail(ctx, effect, EffectAmbiguous, err) }
	beforeDigest := observedRRSetDigest(before)
	if change.Before != nil && change.Before.Digest != beforeDigest { return ProviderEffect{}, coordinator.fail(ctx, effect, EffectConflict, ErrConflict) }
	receipt, err := coordinator.Provider.Apply(ctx, binding, change); if err != nil { return ProviderEffect{}, coordinator.fail(ctx, effect, classifyEffect(err), err) }
	effect.State, effect.BeforeDigest, effect.OutputDigest, effect.ProviderReceipt, effect.UpdatedAt = EffectObserving, beforeDigest, receipt.OutputDigest, receipt.ProviderReceipt, coordinator.now(); _ = coordinator.Store.UpdateEffect(ctx, effect)
	after, err := coordinator.Provider.ObserveRRSet(ctx, binding, target.ZoneID, target.Owner, target.Type); if err != nil { return ProviderEffect{}, coordinator.fail(ctx, effect, EffectAmbiguous, err) }
	afterDigest := observedRRSetDigest(after); effect.ObservedDigest = afterDigest
	if afterDigest != receipt.OutputDigest { return ProviderEffect{}, coordinator.fail(ctx, effect, EffectConflict, ErrConflict) }
	effect.State, effect.UpdatedAt = EffectCommitted, coordinator.now(); if err := coordinator.Store.UpdateEffect(ctx, effect); err != nil { return ProviderEffect{}, err }; return effect, nil
}

func (coordinator CloudflareCoordinator) Compensate(ctx context.Context, binding ProviderBinding, change CloudflareChange, effectID EffectID) (ProviderEffect, error) { effect, err := coordinator.Store.LoadEffect(ctx, effectID); if err != nil { return ProviderEffect{}, err }; if effect.State != EffectCommitted { return ProviderEffect{}, ErrConflict }; target := change.Desired; if target == nil { target = change.Before }; if target==nil{return ProviderEffect{},ErrInvalid};observed, err := coordinator.Provider.ObserveRRSet(ctx, binding, target.ZoneID, target.Owner, target.Type); if err != nil { return ProviderEffect{}, err }; observedDigest := observedRRSetDigest(observed); if observedDigest != effect.OutputDigest { return ProviderEffect{}, coordinator.fail(ctx, effect, EffectConflict, ErrConflict) }; effect.State, effect.UpdatedAt = EffectCompensating, coordinator.now(); _ = coordinator.Store.UpdateEffect(ctx, effect); receipt := DNSApplyReceipt{EffectID: effect.ID, BeforeDigest: effect.BeforeDigest, OutputDigest: effect.OutputDigest, ProviderRevision: effect.ExpectedRevision, ProviderReceipt: effect.ProviderReceipt}; var compensation DNSApplyReceipt;if change.Binding.Concurrency==ConcurrencyAtomicCAS{compensation,err=coordinator.Provider.CompensateConditional(ctx,binding,change,receipt)}else{inverse:=change;inverse.Before=change.Desired;inverse.Desired=change.Before;switch change.Kind{case DNSCreate:inverse.Kind=DNSDelete;inverse.Desired=nil;case DNSDelete:inverse.Kind=DNSCreate;inverse.Before=nil;default:inverse.Kind=DNSReplace};inverse.Effect.ID=EffectID(string(effect.ID)+":compensate");compensation,err=coordinator.Provider.Apply(ctx,binding,inverse);if err==nil{after,observeErr:=coordinator.Provider.ObserveRRSet(ctx,binding,target.ZoneID,target.Owner,target.Type);if observeErr!=nil{err=observeErr}else{afterDigest:=observedRRSetDigest(after);if afterDigest!=compensation.OutputDigest{err=ErrAmbiguous}}}}; if err != nil { return ProviderEffect{}, coordinator.fail(ctx, effect, classifyEffect(err), err) }; effect.State, effect.OutputDigest, effect.ObservedDigest, effect.ProviderReceipt, effect.UpdatedAt = EffectCompensated, compensation.OutputDigest, compensation.OutputDigest, compensation.ProviderReceipt, coordinator.now(); if err := coordinator.Store.UpdateEffect(ctx, effect); err != nil { return ProviderEffect{}, err }; return effect, nil }

func (coordinator CloudflareCoordinator) fail(ctx context.Context, effect ProviderEffect, state EffectState, cause error) error { effect.State, effect.Failure, effect.UpdatedAt = state, cause.Error(), coordinator.now(); _ = coordinator.Store.UpdateEffect(ctx, effect); return cause }
func classifyEffect(err error) EffectState { var providerError *ProviderError; if errors.As(err, &providerError) { switch providerError.Class { case ErrorConflict: return EffectConflict; case ErrorPartial: return EffectPartial; case ErrorAmbiguous: return EffectAmbiguous } }; return EffectFailed }

type StorageCoordinator struct { Store Store; Provider StorageProvider; Now func() time.Time }
func (coordinator StorageCoordinator) Upload(ctx context.Context, binding ProviderBinding, storage StorageBinding, effect ProviderEffect, key ObjectKey, data []byte, expectedDigest string) (ObjectMetadata, error) { if coordinator.Store == nil || coordinator.Provider == nil || binding.State != BindingActive || !validDigest(expectedDigest) { return ObjectMetadata{}, ErrInvalid }; if err := storage.Validate(binding.Capabilities); err != nil { return ObjectMetadata{}, err }; actual := sha256.Sum256(data); if hex.EncodeToString(actual[:]) != expectedDigest { return ObjectMetadata{}, ErrIntegrity }; effect.RequestDigest, effect.State, effect.CreatedAt, effect.UpdatedAt = expectedDigest, EffectAdmitted, time.Now().UTC(), time.Now().UTC(); admitted, created, err := coordinator.Store.AdmitEffect(ctx, effect); if err != nil { return ObjectMetadata{}, err }; if !created { if admitted.State == EffectCommitted { return coordinator.Provider.StatObject(ctx, binding, storage, key) }; return ObjectMetadata{}, ErrConflict }; session, err := coordinator.Provider.BeginUpload(ctx, binding, storage, key, int64(len(data)), expectedDigest, effect.ID); if err != nil { return ObjectMetadata{}, err }; partSize := int(session.PartSize); if partSize <= 0 { return ObjectMetadata{}, ErrIntegrity }; parts := []UploadedPart{}; for offset, number := 0, uint32(1); offset < len(data); number++ { end := offset+partSize; if end > len(data) { end = len(data) }; sum := sha256.Sum256(data[offset:end]); part, err := coordinator.Provider.UploadPart(ctx, binding, storage, session, number, data[offset:end], hex.EncodeToString(sum[:])); if err != nil { _ = coordinator.Provider.AbortUpload(ctx, binding, storage, session); return ObjectMetadata{}, err }; parts = append(parts, part); offset = end }; object, err := coordinator.Provider.CompleteUpload(ctx, binding, storage, session, parts); if err != nil { return ObjectMetadata{}, err }; if object.Digest != expectedDigest || object.Size != int64(len(data)) { return ObjectMetadata{}, ErrIntegrity }; admitted.State, admitted.OutputDigest, admitted.ObservedDigest, admitted.ProviderReceipt, admitted.UpdatedAt = EffectCommitted, object.Digest, object.Digest, object.ETag, time.Now().UTC(); if err := coordinator.Store.UpdateEffect(ctx, admitted); err != nil { return ObjectMetadata{}, err }; return object, nil }
