package backup

import (
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"sort"
	"time"
)

// StableViewAuthority coordinates application, database, mail and filesystem
// barriers without giving the backup process a generic privileged executor.
type StableViewRequest struct{TenantID string `json:"tenant_id"`;Scope string `json:"scope"`;Components []ComponentKind `json:"components"`;Consistency ConsistencyClass `json:"consistency"`;EffectID string `json:"effect_id"`;ExpiresAt time.Time `json:"expires_at"`}
type StableViewGrant struct{Component ComponentKind `json:"component"`;AuthorityID string `json:"authority_id"`;OpaqueToken string `json:"opaque_token"`;Frontier uint64 `json:"frontier"`;SourceGeneration uint64 `json:"source_generation"`;Consistency ConsistencyClass `json:"consistency"`;CreatedAt time.Time `json:"created_at"`;ExpiresAt time.Time `json:"expires_at"`}
type StableViewAuthority interface{AcquireStableViews(context.Context,StableViewRequest)([]StableViewGrant,error);ReleaseStableViews(context.Context,[]StableViewGrant,string)error}
type ViewTokenKeyring interface{ActiveViewTokenKey(context.Context)(string,[]byte,error);ViewTokenVerificationKey(context.Context,string)([]byte,error)}
type SignedViewToken struct{Version uint8 `json:"version"`;KeyID string `json:"key_id"`;TenantID string `json:"tenant_id"`;Scope string `json:"scope"`;Component ComponentKind `json:"component"`;AuthorityID string `json:"authority_id"`;OpaqueToken string `json:"opaque_token"`;EffectID string `json:"effect_id"`;Frontier uint64 `json:"frontier"`;SourceGeneration uint64 `json:"source_generation"`;Consistency ConsistencyClass `json:"consistency"`;IssuedAt time.Time `json:"issued_at"`;ExpiresAt time.Time `json:"expires_at"`;Signature string `json:"signature"`}

type CoordinatedSnapshotProvider struct{Authority StableViewAuthority;Keys ViewTokenKeyring;MaximumViewLifetime time.Duration;Now func()time.Time}
func (provider CoordinatedSnapshotProvider)CreateViews(ctx context.Context,policy BackupPolicySpec,effect string)([]ReadView,error){if provider.Authority==nil||provider.Keys==nil||effect==""{return nil,ErrInvalidBackup};now:=provider.now();lifetime:=provider.MaximumViewLifetime;if lifetime<time.Minute||lifetime>24*time.Hour{lifetime=6*time.Hour};components:=append([]ComponentKind(nil),policy.Components...);sort.Slice(components,func(i,j int)bool{return components[i]<components[j]});grants,err:=provider.Authority.AcquireStableViews(ctx,StableViewRequest{TenantID:policy.TenantID,Scope:policy.Scope,Components:components,Consistency:policy.Consistency,EffectID:effect,ExpiresAt:now.Add(lifetime)});if err!=nil{return nil,err};valid:=false;defer func(){if !valid{_ = provider.Authority.ReleaseStableViews(context.Background(),grants,effect)}}();if len(grants)!=len(components){return nil,ErrInvalidBackup};keyID,key,err:=provider.Keys.ActiveViewTokenKey(ctx);if err!=nil||keyID==""||len(key)<32{return nil,ErrInvalidBackup};defer zeroSecret(key);views:=make([]ReadView,0,len(grants));seen:=map[ComponentKind]bool{};for _,grant:=range grants{if !validComponent(grant.Component)||seen[grant.Component]||grant.AuthorityID==""||grant.OpaqueToken==""||grant.Frontier==0||grant.SourceGeneration==0||grant.CreatedAt.After(now.Add(time.Minute))||!grant.ExpiresAt.After(now)||grant.ExpiresAt.After(now.Add(lifetime))||grant.Consistency!=policy.Consistency{return nil,ErrInvalidBackup};seen[grant.Component]=true;token:=SignedViewToken{Version:1,KeyID:keyID,TenantID:policy.TenantID,Scope:policy.Scope,Component:grant.Component,AuthorityID:grant.AuthorityID,OpaqueToken:grant.OpaqueToken,EffectID:effect,Frontier:grant.Frontier,SourceGeneration:grant.SourceGeneration,Consistency:grant.Consistency,IssuedAt:now,ExpiresAt:grant.ExpiresAt};signature,signErr:=signViewToken(token,key);if signErr!=nil{return nil,signErr};token.Signature=signature;raw,marshalErr:=json.Marshal(token);if marshalErr!=nil{return nil,marshalErr};views=append(views,ReadView{ID:deriveID("view",effect,string(grant.Component),grant.AuthorityID),Component:grant.Component,Token:string(raw),Frontier:grant.Frontier,Consistency:grant.Consistency,CreatedAt:now,ExpiresAt:grant.ExpiresAt})};valid=true;return views,nil}
func (provider CoordinatedSnapshotProvider)ReleaseViews(ctx context.Context,views []ReadView,effect string)error{if provider.Authority==nil||provider.Keys==nil||effect==""{return ErrInvalidBackup};grants:=make([]StableViewGrant,0,len(views));for _,view:=range views{token,err:=provider.verifyToken(ctx,view.Token,effect);if err!=nil{return err};grants=append(grants,StableViewGrant{Component:token.Component,AuthorityID:token.AuthorityID,OpaqueToken:token.OpaqueToken,Frontier:token.Frontier,SourceGeneration:token.SourceGeneration,Consistency:token.Consistency,CreatedAt:token.IssuedAt,ExpiresAt:token.ExpiresAt})};return provider.Authority.ReleaseStableViews(ctx,grants,effect)}
func (provider CoordinatedSnapshotProvider)verifyToken(ctx context.Context,encoded,effect string)(SignedViewToken,error){var token SignedViewToken;if json.Unmarshal([]byte(encoded),&token)!=nil||token.Version!=1||token.EffectID!=effect||token.Signature==""||token.ExpiresAt.Before(provider.now()){return SignedViewToken{},ErrInvalidBackup};key,err:=provider.Keys.ViewTokenVerificationKey(ctx,token.KeyID);if err!=nil||len(key)<32{return SignedViewToken{},ErrInvalidBackup};defer zeroSecret(key);expected,err:=signViewToken(token,key);if err!=nil||!hmac.Equal([]byte(expected),[]byte(token.Signature)){return SignedViewToken{},ErrInvalidBackup};return token,nil}
func (provider CoordinatedSnapshotProvider)now()time.Time{if provider.Now!=nil{return provider.Now().UTC()};return time.Now().UTC()}

type CaptureObject struct{LogicalKey string `json:"logical_key"`;Size uint64 `json:"size"`;Mode uint32 `json:"mode"`;OpaqueSource string `json:"opaque_source"`}
type CaptureSession struct{ID string `json:"id"`;Tool string `json:"tool"`;SchemaVersion uint32 `json:"schema_version"`;SourceGeneration uint64 `json:"source_generation"`;Objects []CaptureObject `json:"objects"`}
type ComponentCaptureDriver interface{DescribeStableView(context.Context,BackupPolicySpec,ReadView,string)(CaptureSession,error);OpenCaptureObject(context.Context,CaptureSession,CaptureObject,string)(ReadCloser,error)}
type CaptureObjectSink interface{PutCaptureObject(context.Context,CaptureSession,CaptureObject,ReadCloser,string)(ObjectDescriptor,error)}
type StableCapturer struct{Drivers map[ComponentKind]ComponentCaptureDriver;Sink CaptureObjectSink}
func (capturer StableCapturer)CaptureComponent(ctx context.Context,policy BackupPolicySpec,view ReadView,effect string)(ArtifactManifest,error){driver:=capturer.Drivers[view.Component];if driver==nil||capturer.Sink==nil||effect==""||view.Token==""||view.Frontier==0{return ArtifactManifest{},ErrInvalidBackup};session,err:=driver.DescribeStableView(ctx,policy,view,effect);if err!=nil{return ArtifactManifest{},err};if session.ID==""||session.Tool==""||session.SchemaVersion==0||session.SourceGeneration==0||len(session.Objects)>10000000{return ArtifactManifest{},ErrInvalidBackup};objects:=make([]ObjectDescriptor,0,len(session.Objects));seen:=map[string]bool{};root:=sha256.New();var bytes uint64;for _,object:=range session.Objects{if object.LogicalKey==""||object.OpaqueSource==""||seen[object.LogicalKey]{return ArtifactManifest{},ErrInvalidBackup};seen[object.LogicalKey]=true;reader,openErr:=driver.OpenCaptureObject(ctx,session,object,effect);if openErr!=nil{return ArtifactManifest{},openErr};descriptor,putErr:=capturer.Sink.PutCaptureObject(ctx,session,object,reader,effect);closeErr:=reader.Close();if putErr!=nil||closeErr!=nil{return ArtifactManifest{},errors.Join(putErr,closeErr)};if descriptor.Key!=object.LogicalKey||descriptor.Size!=object.Size||!isSHA256(descriptor.Digest){return ArtifactManifest{},ErrInvalidBackup};objects=append(objects,descriptor);bytes+=descriptor.Size;_,_=root.Write([]byte(descriptor.Key));_,_=root.Write([]byte{0});_,_=root.Write([]byte(descriptor.Digest));_,_=root.Write([]byte{0})};sort.Slice(objects,func(i,j int)bool{return objects[i].Key<objects[j].Key});root.Reset();for _,descriptor:=range objects{_,_=root.Write([]byte(descriptor.Key));_,_=root.Write([]byte{0});_,_=root.Write([]byte(descriptor.Digest));_,_=root.Write([]byte{0})};return ArtifactManifest{ID:ArtifactID(deriveID("artifact",effect,string(view.Component),session.ID)),Component:view.Component,ObjectCount:uint64(len(objects)),Bytes:bytes,RootDigest:hex.EncodeToString(root.Sum(nil)),Tool:session.Tool,SchemaVersion:session.SchemaVersion,SourceGeneration:session.SourceGeneration,Consistency:view.Consistency,Objects:objects},nil}
func signViewToken(token SignedViewToken,key []byte)(string,error){token.Signature="";raw,err:=json.Marshal(token);if err!=nil{return "",err};mac:=hmac.New(sha256.New,key);_,_=mac.Write(raw);return hex.EncodeToString(mac.Sum(nil)),nil}
func zeroSecret(value []byte){for index:=range value{value[index]=0}}
