//go:build linux

package backup

import (
	"archive/tar"
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"

	_ "modernc.org/sqlite"

	"github.com/aonsyed/cyberpanel/platform/internal/database"
	"github.com/aonsyed/cyberpanel/platform/internal/mail"
)

const (
	LinuxBackupRuntimeRoot = "/var/lib/cyberpanel/backup-runtime"
	linuxBackupSitesRoot = "/var/lib/cyberpanel/sites"
	linuxBackupDatabaseStateRoot = "/var/lib/cyberpanel/database/databases"
	linuxBackupMailRoot = "/var/lib/cyberpanel/mailboxes"
	linuxBackupControlDatabase = "/var/lib/cyberpanel/control/control.db"
)

type LinuxBackupSiteBinding struct { SiteKey string `json:"site_key"`; TenantID string `json:"tenant_id"`; SiteID string `json:"site_id"`; UID uint32 `json:"uid"`; GID uint32 `json:"gid"`; Generation uint64 `json:"generation"` }
type LinuxBackupSiteResolver interface { ResolveBackupSite(context.Context,string,string)(LinuxBackupSiteBinding,error) }
type LinuxBackupSiteResolverFunc func(context.Context,string,string)(LinuxBackupSiteBinding,error)
func(resolver LinuxBackupSiteResolverFunc)ResolveBackupSite(ctx context.Context,tenant,scope string)(LinuxBackupSiteBinding,error){return resolver(ctx,tenant,scope)}

type linuxBackupViewState struct { EffectID string `json:"effect_id"`; TenantID string `json:"tenant_id"`; Scope string `json:"scope"`; Component ComponentKind `json:"component"`; Token string `json:"token"`; Frontier uint64 `json:"frontier"`; SourceGeneration uint64 `json:"source_generation"`; Consistency ConsistencyClass `json:"consistency"`; Artifact ArtifactManifest `json:"artifact"`; CreatedAt time.Time `json:"created_at"`; ExpiresAt time.Time `json:"expires_at"` }
type linuxRestoreState struct { PlanID RestoreID `json:"plan_id"`; TenantID string `json:"tenant_id"`; TargetScope string `json:"target_scope"`; ScratchID string `json:"scratch_id"`; PreviousGeneration string `json:"previous_generation"`; TargetGeneration string `json:"target_generation,omitempty"`; PreviousRelease string `json:"previous_release,omitempty"`; PreviousReleaseIdentity string `json:"previous_release_identity,omitempty"`; CandidateReleaseIdentity string `json:"candidate_release_identity,omitempty"`; PrivateBackup string `json:"private_backup,omitempty"`; MailBackups map[string]string `json:"mail_backups,omitempty"`; SafetyID string `json:"safety_id,omitempty"`; Watermark uint64 `json:"watermark"`; Fingerprint string `json:"fingerprint,omitempty"`; FirstWriteAt *time.Time `json:"first_write_at,omitempty"`; Frozen bool `json:"frozen"`; Promoted bool `json:"promoted"` }

type LinuxBackupHost struct { Resolver LinuxBackupSiteResolver; Root string; Now func()time.Time; mu sync.Mutex }

func NewLinuxBackupHost(resolver LinuxBackupSiteResolver)(*LinuxBackupHost,error){if os.Geteuid()!=0||resolver==nil{return nil,ErrInvalidBackup};if err:=ensureLinuxBackupDirectory(LinuxBackupRuntimeRoot,0700);err!=nil{return nil,err};for _,name:=range []string{"effects","restores","watermarks"}{if err:=ensureLinuxBackupDirectory(filepath.Join(LinuxBackupRuntimeRoot,name),0700);err!=nil{return nil,err}};return &LinuxBackupHost{Resolver:resolver,Root:LinuxBackupRuntimeRoot,Now:time.Now},nil}
func(host *LinuxBackupHost)now()time.Time{if host.Now!=nil{return host.Now().UTC()};return time.Now().UTC()}

func(host *LinuxBackupHost)CreateViews(ctx context.Context,policy BackupPolicySpec,effect string)([]ReadView,error){
	if host==nil||host.Resolver==nil||effect==""||policy.TenantID==""||policy.Scope==""||policy.Consistency!=ConsistencyFuzzy||len(policy.Components)==0{return nil,ErrInvalidBackup}
	binding,err:=host.resolve(ctx,policy.TenantID,policy.Scope);if err!=nil{return nil,err};host.mu.Lock();defer host.mu.Unlock()
	effectRoot:=host.effectRoot(effect);components:=append([]ComponentKind(nil),policy.Components...);sort.Slice(components,func(i,j int)bool{return components[i]<components[j]});now:=host.now();existing:=make([]ReadView,0,len(components));for _,component:=range components{token:=linuxBackupID("view",effect,string(component),binding.SiteKey,strconv.FormatUint(binding.Generation,10));var state linuxBackupViewState;if readLinuxBackupJSON(filepath.Join(effectRoot,token+".json"),&state)==nil&&state.EffectID==effect&&state.TenantID==policy.TenantID&&state.Scope==policy.Scope&&state.Component==component&&state.SourceGeneration==binding.Generation&&state.Consistency==policy.Consistency&&state.ExpiresAt.After(now){existing=append(existing,ReadView{ID:linuxBackupID("read",token),Component:component,Token:token,Frontier:state.Frontier,Consistency:state.Consistency,CreatedAt:state.CreatedAt,ExpiresAt:state.ExpiresAt})}};if len(existing)==len(components){return existing,nil};if err=removeLinuxBackupTree(effectRoot);err!=nil{return nil,err};if err=ensureLinuxBackupDirectory(effectRoot,0700);err!=nil{return nil,err};objectsRoot:=filepath.Join(effectRoot,"objects");if err=ensureLinuxBackupDirectory(objectsRoot,0700);err!=nil{return nil,err}
	views:=make([]ReadView,0,len(components));expires:=now.Add(6*time.Hour);frontier:=uint64(now.UnixNano());if frontier==0{frontier=1}
	for _,component:=range components{if component!=ComponentFiles&&component!=ComponentDatabase&&component!=ComponentMail{return nil,fmt.Errorf("%w: component %s has no proven local capture",ErrInvalidBackup,component)};token:=linuxBackupID("view",effect,string(component),binding.SiteKey,strconv.FormatUint(binding.Generation,10));state:=linuxBackupViewState{EffectID:effect,TenantID:policy.TenantID,Scope:policy.Scope,Component:component,Token:token,Frontier:frontier,SourceGeneration:binding.Generation,Consistency:ConsistencyFuzzy,CreatedAt:now,ExpiresAt:expires};artifact,captureErr:=host.captureStableComponent(ctx,binding,state,objectsRoot);if captureErr!=nil{return nil,captureErr};state.Artifact=artifact;if err=writeLinuxBackupJSON(filepath.Join(effectRoot,token+".json"),state);err!=nil{return nil,err};views=append(views,ReadView{ID:linuxBackupID("read",token),Component:component,Token:token,Frontier:frontier,Consistency:ConsistencyFuzzy,CreatedAt:now,ExpiresAt:expires})}
	return views,nil
}

func(host *LinuxBackupHost)ReleaseViews(ctx context.Context,views []ReadView,effect string)error{if host==nil||effect==""||len(views)==0{return ErrInvalidBackup};host.mu.Lock();defer host.mu.Unlock();root:=host.effectRoot(effect);for _,view:=range views{var state linuxBackupViewState;if readLinuxBackupJSON(filepath.Join(root,view.Token+".json"),&state)!=nil||state.EffectID!=effect||state.Token!=view.Token{return ErrInvalidBackup}};return removeLinuxBackupTree(root)}
func(host *LinuxBackupHost)CaptureComponent(ctx context.Context,policy BackupPolicySpec,view ReadView,effect string)(ArtifactManifest,error){if host==nil||effect==""||view.Token==""||policy.TenantID==""{return ArtifactManifest{},ErrInvalidBackup};host.mu.Lock();defer host.mu.Unlock();var state linuxBackupViewState;if err:=readLinuxBackupJSON(filepath.Join(host.effectRoot(effect),view.Token+".json"),&state);err!=nil{return ArtifactManifest{},err};if state.EffectID!=effect||state.TenantID!=policy.TenantID||state.Scope!=policy.Scope||state.Component!=view.Component||state.Token!=view.Token||state.Frontier!=view.Frontier||state.Consistency!=view.Consistency||host.now().After(state.ExpiresAt){return ArtifactManifest{},ErrInvalidBackup};return state.Artifact,nil}
func(host *LinuxBackupHost)OpenObject(ctx context.Context,object ObjectDescriptor,effect string,offset uint64)(io.ReadCloser,error){if host==nil||effect==""||object.Key==""||len(object.Digest)!=64||offset>object.Size{return nil,ErrInvalidBackup};path:=filepath.Join(host.effectRoot(effect),"objects",object.Digest);file,err:=openLinuxBackupRegular(path);if err!=nil{return nil,err};info,err:=file.Stat();if err!=nil||uint64(info.Size())!=object.Size{file.Close();return nil,ErrInvalidBackup};if _,err=file.Seek(int64(offset),io.SeekStart);err!=nil{file.Close();return nil,err};return file,nil}

func(host *LinuxBackupHost)captureStableComponent(ctx context.Context,binding LinuxBackupSiteBinding,state linuxBackupViewState,objectsRoot string)(ArtifactManifest,error){
	temporary:=filepath.Join(host.effectRoot(state.EffectID),"capture-"+string(state.Component)+".partial");_ = os.Remove(temporary)
	var tool,key string;var captureErr error
	switch state.Component{case ComponentFiles:tool="cyberpanel-site-tar-v1";key="site/files.tar";captureErr=host.captureFiles(ctx,binding,temporary);case ComponentDatabase:tool="mariadb-dump-v1";key="site/database.sql";captureErr=host.captureDatabase(ctx,binding,temporary);case ComponentMail:tool="dovecot-maildir-tar-v1";key="site/mail.tar";captureErr=host.captureMail(ctx,binding,temporary);default:return ArtifactManifest{},ErrInvalidBackup}
	if captureErr!=nil{_ = os.Remove(temporary);return ArtifactManifest{},captureErr};objects,total,rootDigest,err:=commitLinuxBackupChunks(ctx,temporary,objectsRoot,key);if err!=nil{return ArtifactManifest{},err};return ArtifactManifest{ID:ArtifactID(linuxBackupID("artifact",state.EffectID,string(state.Component),rootDigest)),Component:state.Component,ObjectCount:uint64(len(objects)),Bytes:total,RootDigest:rootDigest,Tool:tool,SchemaVersion:1,SourceGeneration:state.SourceGeneration,Consistency:state.Consistency,Objects:objects},nil
}

func(host *LinuxBackupHost)captureFiles(ctx context.Context,binding LinuxBackupSiteBinding,target string)error{generationRoot:=host.generationRoot(binding);release,err:=safeCurrentRelease(generationRoot);if err!=nil{return err};file,err:=createLinuxBackupFile(target);if err!=nil{return err};writer:=tar.NewWriter(file);err=appendLinuxBackupTree(ctx,writer,release,"release");private:=filepath.Join(generationRoot,"private");if err==nil{if _,statErr:=os.Lstat(private);statErr==nil{err=appendLinuxBackupTree(ctx,writer,private,"private")}else if !errors.Is(statErr,os.ErrNotExist){err=statErr}};closeTar:=writer.Close();syncErr:=file.Sync();closeFile:=file.Close();return errors.Join(err,closeTar,syncErr,closeFile)}

func(host *LinuxBackupHost)captureDatabase(ctx context.Context,binding LinuxBackupSiteBinding,target string)error{names,err:=linuxBackupDatabaseNames(binding);if err!=nil{return err};file,err:=createLinuxBackupFile(target);if err!=nil{return err};if len(names)==0{_,err=file.Write([]byte("-- CyberPanel logical backup: no databases bound to this site\n"));if err==nil{err=file.Sync()};return errors.Join(err,file.Close())};arguments:=[]string{"--protocol=socket","--socket=/run/mysqld/mysqld.sock","--user=root","--single-transaction","--quick","--routines","--events","--triggers","--hex-blob","--add-drop-database","--databases"};arguments=append(arguments,names...);command:=exec.CommandContext(ctx,"/usr/bin/mariadb-dump",arguments...);command.Env=[]string{"PATH=/usr/bin:/bin","LANG=C.UTF-8","LC_ALL=C.UTF-8","HOME=/root"};command.Stdout=file;stderr:=&linuxBackupLimitedBuffer{maximum:1<<20};command.Stderr=stderr;runErr:=command.Run();syncErr:=file.Sync();closeErr:=file.Close();if runErr!=nil{return fmt.Errorf("fixed MariaDB logical capture failed: %w: %s",runErr,stderr.String())};return errors.Join(syncErr,closeErr)}

func(host *LinuxBackupHost)captureMail(ctx context.Context,binding LinuxBackupSiteBinding,target string)error{domains,err:=linuxBackupMailDomains(ctx,binding.TenantID);if err!=nil{return err};stopped,err:=stopLinuxBackupServices(ctx,[]string{"postfix.service","dovecot.service"});if err!=nil{return err};restarted:=false;defer func(){if !restarted{_ = startLinuxBackupServices(context.Background(),stopped)}}();file,err:=createLinuxBackupFile(target);if err!=nil{return err};writer:=tar.NewWriter(file);for _,domain:=range domains{root:=filepath.Join(linuxBackupMailRoot,domain);if _,statErr:=os.Lstat(root);statErr==nil{if err=appendLinuxBackupTree(ctx,writer,root,filepath.Join("mailboxes",domain));err!=nil{break}}else if !errors.Is(statErr,os.ErrNotExist){err=statErr;break}};closeTar:=writer.Close();syncErr:=file.Sync();closeFile:=file.Close();startErr:=startLinuxBackupServices(ctx,stopped);restarted=startErr==nil;return errors.Join(err,closeTar,syncErr,closeFile,startErr)}

func(host *LinuxBackupHost)VerifyCapacity(ctx context.Context,target string,required uint64)error{if required==0{return ErrInvalidBackup};binding,err:=host.resolve(ctx,"",target);if err!=nil{return err};var stat syscall.Statfs_t;if err=syscall.Statfs(host.generationRoot(binding),&stat);err!=nil{return err};available:=stat.Bavail*uint64(stat.Bsize);if available<required{return fmt.Errorf("insufficient restore capacity")};return nil}

func(host *LinuxBackupHost)CreateScratch(ctx context.Context,plan RestorePlanSpec,manifest RecoveryPointManifest,effect string)(string,error){if host==nil||effect==""||plan.ID==""||plan.CollisionPolicy!=CollisionReplaceBlueGreen||plan.SecretPolicy!=SecretResetRequired||len(plan.DomainMapping)!=0||plan.TargetScope==""||manifest.RecoveryPointID!=plan.RecoveryPointID{return "",ErrInvalidBackup};if err:=validateLinuxRestoreScope(plan,manifest);err!=nil{return "",err};if _,err:=host.resolve(ctx,plan.TenantID,plan.TargetScope);err!=nil{return "",err};for component,target:=range plan.ComponentMapping{if component!=ComponentFiles&&component!=ComponentDatabase&&component!=ComponentMail||target!=plan.TargetScope{return "",ErrInvalidBackup}};host.mu.Lock();defer host.mu.Unlock();scratch:=linuxBackupID("scratch",string(plan.ID),string(plan.RecoveryPointID),plan.TargetScope);root:=host.restoreRoot(plan);if err:=ensureLinuxBackupDirectory(root,0700);err!=nil{return "",err};if err:=ensureLinuxBackupDirectory(filepath.Join(root,scratch),0700);err!=nil{return "",err};if err:=writeLinuxBackupJSON(filepath.Join(root,"manifest.json"),manifest);err!=nil{return "",err};state:=linuxRestoreState{PlanID:plan.ID,TenantID:plan.TenantID,TargetScope:plan.TargetScope,ScratchID:scratch,MailBackups:map[string]string{},Watermark:1};if priorErr:=readLinuxBackupJSON(filepath.Join(root,"state.json"),&state);priorErr==nil{if state.ScratchID!=scratch||state.PlanID!=plan.ID{return "",ErrBackupConflict}}else if !errors.Is(priorErr,os.ErrNotExist){return "",priorErr};if err:=writeLinuxBackupJSON(filepath.Join(root,"state.json"),state);err!=nil{return "",err};return scratch,nil}

// SQL dumps and mail archives retain source resource names. Until a validated
// remapping importer exists, importing them at another scope would mutate the
// source, not the requested destination.
func validateLinuxRestoreScope(plan RestorePlanSpec, manifest RecoveryPointManifest) error {
	if manifest.Scope == "" || plan.SourceScope != manifest.Scope { return ErrInvalidBackup }
	for _, component := range []ComponentKind{ComponentDatabase, ComponentMail} {
		if _, selected := plan.ComponentMapping[component]; selected && plan.TargetScope != manifest.Scope { return fmt.Errorf("%w: cross-scope %s restore requires resource remapping", ErrInvalidBackup, component) }
	}
	return nil
}

func(host *LinuxBackupHost)StageArtifactStream(ctx context.Context,plan RestorePlanSpec,scratch string,artifact ArtifactManifest,stream io.Reader,effect string)(string,error){if host==nil||stream==nil||scratch==""||effect==""||artifact.Component==""||len(artifact.Objects)==0{return "",ErrInvalidBackup};if _,required:=plan.ComponentMapping[artifact.Component];!required{return linuxBackupID("skipped",scratch,string(artifact.ID)),drainLinuxBackupArtifact(stream,artifact)};host.mu.Lock();defer host.mu.Unlock();root:=host.restoreRoot(plan);var state linuxRestoreState;if err:=readLinuxBackupJSON(filepath.Join(root,"state.json"),&state);err!=nil{return "",err};if state.ScratchID!=scratch||state.PlanID!=plan.ID{return "",ErrBackupConflict};if err:=expectedLinuxBackupArtifact(root,artifact);err!=nil{return "",err};componentRoot:=filepath.Join(root,scratch,string(artifact.Component));if err:=ensureLinuxBackupDirectory(componentRoot,0700);err!=nil{return "",err};for index,descriptor:=range artifact.Objects{target:=filepath.Join(componentRoot,"object-"+strconv.Itoa(index));file,err:=createLinuxBackupFile(target);if err!=nil{return "",err};hash:=sha256.New();written,copyErr:=io.CopyN(io.MultiWriter(file,hash),stream,int64(descriptor.Size));syncErr:=file.Sync();closeErr:=file.Close();if copyErr!=nil||syncErr!=nil||closeErr!=nil||uint64(written)!=descriptor.Size||hex.EncodeToString(hash.Sum(nil))!=descriptor.Digest{_ = os.Remove(target);return "",errors.Join(ErrInvalidBackup,copyErr,syncErr,closeErr)}};if err:=writeLinuxBackupJSON(filepath.Join(componentRoot,"artifact.json"),artifact);err!=nil{return "",err};return linuxBackupID("stage",scratch,string(artifact.ID),artifact.RootDigest),nil}

func(host *LinuxBackupHost)VerifyScratch(ctx context.Context,plan RestorePlanSpec,scratch string,manifest RecoveryPointManifest)(string,error){host.mu.Lock();defer host.mu.Unlock();root:=host.restoreRoot(plan);var state linuxRestoreState;if err:=readLinuxBackupJSON(filepath.Join(root,"state.json"),&state);err!=nil{return "",err};if state.ScratchID!=scratch{return "",ErrBackupConflict};if err:=verifyLinuxBackupComponents(ctx,root,scratch,plan);err!=nil{return "",err};hash:=sha256.New();for _,artifact:=range manifest.Artifacts{if _,required:=plan.ComponentMapping[artifact.Component];!required{continue};var staged ArtifactManifest;if err:=readLinuxBackupJSON(filepath.Join(root,scratch,string(artifact.Component),"artifact.json"),&staged);err!=nil{return "",err};if staged.ID!=artifact.ID||staged.RootDigest!=artifact.RootDigest||len(staged.Objects)!=len(artifact.Objects){return "",ErrInvalidBackup};for index,descriptor:=range staged.Objects{digest,size,err:=digestLinuxBackupFile(filepath.Join(root,scratch,string(artifact.Component),"object-"+strconv.Itoa(index)));if err!=nil||digest!=descriptor.Digest||size!=descriptor.Size{return "",errors.Join(ErrInvalidBackup,err)};_,_=io.WriteString(hash,digest)}};return hex.EncodeToString(hash.Sum(nil)),nil}

func(host *LinuxBackupHost)CurrentGeneration(ctx context.Context,plan RestorePlanSpec,effect string)(string,uint64,error){if effect==""{return "",0,ErrInvalidBackup};binding,err:=host.resolve(ctx,plan.TenantID,plan.TargetScope);if err!=nil{return "",0,err};host.mu.Lock();defer host.mu.Unlock();root:=host.restoreRoot(plan);var state linuxRestoreState;if err=readLinuxBackupJSON(filepath.Join(root,"state.json"),&state);err!=nil{return "",0,err};release,err:=safeCurrentRelease(host.generationRoot(binding));if err!=nil{return "",0,err};watermark:=host.loadWatermark(plan.TargetScope);state.PreviousGeneration=linuxBackupID("generation",binding.SiteKey,strconv.FormatUint(binding.Generation,10),release);state.PreviousRelease=release;state.Watermark=watermark;if err=writeLinuxBackupJSON(filepath.Join(root,"state.json"),state);err!=nil{return "",0,err};return state.PreviousGeneration,watermark,nil}

func(host *LinuxBackupHost)CreateSafetySnapshot(ctx context.Context,plan RestorePlanSpec,previous string,watermark uint64,effect string)(string,error){binding,err:=host.resolve(ctx,plan.TenantID,plan.TargetScope);if err!=nil{return "",err};host.mu.Lock();defer host.mu.Unlock();root:=host.restoreRoot(plan);var state linuxRestoreState;if err=readLinuxBackupJSON(filepath.Join(root,"state.json"),&state);err!=nil{return "",err};if state.PreviousGeneration!=previous||state.Watermark!=watermark{return "",ErrBackupConflict};safety:=filepath.Join(root,"safety");if err=ensureLinuxBackupDirectory(safety,0700);err!=nil{return "",err};for component:=range plan.ComponentMapping{target:=filepath.Join(safety,string(component));switch component{case ComponentFiles:err=host.captureFiles(ctx,binding,target);case ComponentDatabase:err=host.captureDatabase(ctx,binding,target);case ComponentMail:err=host.captureMail(ctx,binding,target);default:err=ErrInvalidBackup};if err!=nil{return "",err}};state.SafetyID=linuxBackupID("safety",string(plan.ID),previous,strconv.FormatUint(watermark,10));if err=writeLinuxBackupJSON(filepath.Join(root,"state.json"),state);err!=nil{return "",err};return state.SafetyID,nil}

func(host *LinuxBackupHost)FreezeTargetWrites(ctx context.Context,plan RestorePlanSpec,effect string)(uint64,error){host.mu.Lock();defer host.mu.Unlock();root:=host.restoreRoot(plan);var state linuxRestoreState;if err:=readLinuxBackupJSON(filepath.Join(root,"state.json"),&state);err!=nil{return 0,err};services:=[]string{"lsws.service"};if _,ok:=plan.ComponentMapping[ComponentMail];ok{services=append(services,"postfix.service","dovecot.service")};stopped,err:=stopLinuxBackupServices(ctx,services);if err!=nil{return 0,err};if err=writeLinuxBackupJSON(filepath.Join(root,"stopped.json"),stopped);err!=nil{_ = startLinuxBackupServices(ctx,stopped);return 0,err};state.Frozen=true;if err=writeLinuxBackupJSON(filepath.Join(root,"state.json"),state);err!=nil{return 0,err};return state.Watermark,nil}

func(host *LinuxBackupHost)Promote(ctx context.Context,plan RestorePlanSpec,scratch,effect string)(string,error){if err:=validateLinuxRestoreScope(plan,RecoveryPointManifest{Scope:plan.SourceScope});err!=nil{return "",err};binding,err:=host.resolve(ctx,plan.TenantID,plan.TargetScope);if err!=nil{return "",err};host.mu.Lock();defer host.mu.Unlock();root:=host.restoreRoot(plan);var state linuxRestoreState;if err=readLinuxBackupJSON(filepath.Join(root,"state.json"),&state);err!=nil{return "",err};if !state.Frozen||state.ScratchID!=scratch{return "",ErrBackupConflict};if err=verifyLinuxBackupComponents(ctx,root,scratch,plan);err!=nil{return "",err};if _,ok:=plan.ComponentMapping[ComponentFiles];ok{if err=host.promoteFiles(plan,binding,root,&state);err!=nil{return "",err}};if _,ok:=plan.ComponentMapping[ComponentDatabase];ok{if err=host.importDatabase(ctx,filepath.Join(root,scratch,string(ComponentDatabase),"assembled"));err!=nil{return "",err}};if _,ok:=plan.ComponentMapping[ComponentMail];ok{if err=host.promoteMail(plan,root,&state);err!=nil{return "",err}};state.TargetGeneration=linuxBackupID("restored",string(plan.ID),scratch);state.Promoted=true;state.Fingerprint,err=host.targetFingerprint(ctx,plan,binding);if err!=nil{return "",err};if err=writeLinuxBackupJSON(filepath.Join(root,"state.json"),state);err!=nil{return "",err};return state.TargetGeneration,nil}

func(host *LinuxBackupHost)ObserveWrites(ctx context.Context,plan RestorePlanSpec,generation,effect string)(uint64,*time.Time,error){if effect==""{return 0,nil,ErrInvalidBackup};binding,err:=host.resolve(ctx,plan.TenantID,plan.TargetScope);if err!=nil{return 0,nil,err};host.mu.Lock();defer host.mu.Unlock();root:=host.restoreRoot(plan);var state linuxRestoreState;if err=readLinuxBackupJSON(filepath.Join(root,"state.json"),&state);err!=nil{return 0,nil,err};if generation!=state.TargetGeneration&&generation!=state.PreviousGeneration{return 0,nil,ErrBackupConflict};if state.Fingerprint==""{return 0,nil,ErrBackupAmbiguous};fingerprint,err:=host.targetFingerprint(ctx,plan,binding);if err!=nil{return 0,nil,err};if fingerprint!=state.Fingerprint{if state.FirstWriteAt==nil{now:=host.now();state.FirstWriteAt=&now};if state.Watermark==^uint64(0){return 0,nil,ErrBackupConflict};state.Watermark++;state.Fingerprint=fingerprint;if err=writeLinuxBackupJSON(host.watermarkPath(plan.TargetScope),state.Watermark);err!=nil{return 0,nil,err};if err=writeLinuxBackupJSON(filepath.Join(root,"state.json"),state);err!=nil{return 0,nil,err}};return state.Watermark,state.FirstWriteAt,nil}

func(host *LinuxBackupHost)UnfreezeTargetWrites(ctx context.Context,plan RestorePlanSpec,generation,effect string)error{host.mu.Lock();defer host.mu.Unlock();root:=host.restoreRoot(plan);var state linuxRestoreState;if err:=readLinuxBackupJSON(filepath.Join(root,"state.json"),&state);err!=nil{return err};if generation!=state.TargetGeneration&&generation!=state.PreviousGeneration{return ErrBackupConflict};var stopped []string;if err:=readLinuxBackupJSON(filepath.Join(root,"stopped.json"),&stopped);err!=nil{return err};if err:=startLinuxBackupServices(ctx,stopped);err!=nil{return err};state.Frozen=false;if err:=writeLinuxBackupJSON(filepath.Join(root,"state.json"),state);err!=nil{return err};return nil}

func(host *LinuxBackupHost)VerifyPromotedHealth(ctx context.Context,plan RestorePlanSpec,generation,effect string)(string,error){binding,err:=host.resolve(ctx,plan.TenantID,plan.TargetScope);if err!=nil{return "",err};host.mu.Lock();defer host.mu.Unlock();root:=host.restoreRoot(plan);var state linuxRestoreState;if err=readLinuxBackupJSON(filepath.Join(root,"state.json"),&state);err!=nil{return "",err};if !state.Promoted||generation!=state.TargetGeneration||!state.Frozen{return "",ErrBackupConflict};if _,ok:=plan.ComponentMapping[ComponentFiles];ok{identity,releaseErr:=linuxBackupReleaseIdentity(filepath.Join(host.generationRoot(binding),"releases","current"),true);if releaseErr!=nil||state.CandidateReleaseIdentity==""||identity!=state.CandidateReleaseIdentity{return "",errors.Join(ErrInvalidBackup,releaseErr)}};fingerprint,err:=host.targetFingerprint(ctx,plan,binding);if err!=nil{return "",err};return linuxBackupDigest("health",generation,fingerprint),nil}

func(host *LinuxBackupHost)RestorePrevious(ctx context.Context,plan RestorePlanSpec,previous,effect string)error{binding,err:=host.resolve(ctx,plan.TenantID,plan.TargetScope);if err!=nil{return err};host.mu.Lock();defer host.mu.Unlock();root:=host.restoreRoot(plan);var state linuxRestoreState;if err=readLinuxBackupJSON(filepath.Join(root,"state.json"),&state);err!=nil{return err};if state.PreviousGeneration!=previous||!state.Frozen{return ErrBackupConflict};if _,ok:=plan.ComponentMapping[ComponentFiles];ok{if err=host.restoreSafetyFiles(binding,filepath.Join(root,"safety",string(ComponentFiles)));err!=nil{return err}};if _,ok:=plan.ComponentMapping[ComponentDatabase];ok{if err=host.importDatabase(ctx,filepath.Join(root,"safety",string(ComponentDatabase)));err!=nil{return err}};if _,ok:=plan.ComponentMapping[ComponentMail];ok{if err=host.restoreSafetyMail(filepath.Join(root,"safety",string(ComponentMail)));err!=nil{return err}};state.Promoted=false;state.TargetGeneration="";return writeLinuxBackupJSON(filepath.Join(root,"state.json"),state)}
func(host *LinuxBackupHost)Quarantine(ctx context.Context,plan RestorePlanSpec,scratch,effect string)error{host.mu.Lock();defer host.mu.Unlock();root:=host.restoreRoot(plan);return writeLinuxBackupJSON(filepath.Join(root,"QUARANTINED.json"),map[string]any{"plan_id":plan.ID,"scratch_id":scratch,"observed_at":host.now()})}
func(host *LinuxBackupHost)Finalize(ctx context.Context,plan RestorePlanSpec,scratch,effect string)error{host.mu.Lock();defer host.mu.Unlock();root:=host.restoreRoot(plan);var state linuxRestoreState;if err:=readLinuxBackupJSON(filepath.Join(root,"state.json"),&state);err!=nil{return err};if state.Frozen||state.ScratchID!=scratch{return ErrBackupConflict};return removeLinuxBackupTree(filepath.Join(root,"safety"))}

func(host *LinuxBackupHost)promoteFiles(plan RestorePlanSpec,binding LinuxBackupSiteBinding,root string,state *linuxRestoreState)error{
	archive:=filepath.Join(root,state.ScratchID,string(ComponentFiles),"assembled")
	extractRoot:=filepath.Join(root,state.ScratchID,"files-extracted")
	if err:=ensureLinuxBackupDirectory(extractRoot,0700);err!=nil{return err}
	if err:=extractLinuxBackupSiteTar(archive,extractRoot,binding);err!=nil{return err}
	generationRoot:=host.generationRoot(binding)
	releaseSource:=filepath.Join(extractRoot,"release")
	releaseTarget:=filepath.Join(generationRoot,"releases","restore-"+linuxBackupID("release",string(plan.ID))[:24])
	if _,err:=os.Lstat(releaseTarget);errors.Is(err,os.ErrNotExist){if err=os.Rename(releaseSource,releaseTarget);err!=nil{return err}}else if err!=nil{return err}
	current:=filepath.Join(generationRoot,"releases","current")
	if state.CandidateReleaseIdentity==""{
		var err error
		state.PreviousReleaseIdentity,err=linuxBackupReleaseIdentity(current,false);if err!=nil{return err}
		state.CandidateReleaseIdentity,err=linuxBackupReleaseIdentity(releaseTarget,true);if err!=nil{return err}
		state.PreviousRelease=releaseTarget
		if err=writeLinuxBackupJSON(filepath.Join(root,"state.json"),state);err!=nil{return err}
	}
	if err:=switchLinuxBackupCurrent(releaseTarget,current,state.PreviousReleaseIdentity,state.CandidateReleaseIdentity);err!=nil{return err}
	privateSource:=filepath.Join(extractRoot,"private")
	if info,err:=os.Lstat(privateSource);err==nil&&info.IsDir(){privateTarget:=filepath.Join(generationRoot,"private");backup:=filepath.Join(generationRoot,"private-before-"+linuxBackupID("private",string(plan.ID))[:16]);if _,statErr:=os.Lstat(privateTarget);statErr==nil{if err=os.Rename(privateTarget,backup);err!=nil{return err};state.PrivateBackup=backup};if err=os.Rename(privateSource,privateTarget);err!=nil{return err}}
	return nil
}
func(host *LinuxBackupHost)promoteMail(plan RestorePlanSpec,root string,state *linuxRestoreState)error{archive:=filepath.Join(root,state.ScratchID,string(ComponentMail),"assembled");extractRoot:=filepath.Join(root,state.ScratchID,"mail-extracted");if err:=ensureLinuxBackupDirectory(extractRoot,0700);err!=nil{return err};if err:=extractLinuxBackupTar(archive,extractRoot);err!=nil{return err};domains,err:=os.ReadDir(filepath.Join(extractRoot,"mailboxes"));if errors.Is(err,os.ErrNotExist){return nil};if err!=nil{return err};for _,entry:=range domains{if !entry.IsDir()||!safeLinuxBackupName(entry.Name()){return ErrInvalidBackup};source:=filepath.Join(extractRoot,"mailboxes",entry.Name());target:=filepath.Join(linuxBackupMailRoot,entry.Name());backup:=filepath.Join(linuxBackupMailRoot,".before-"+linuxBackupID("mail",string(plan.ID),entry.Name())[:24]);if _,statErr:=os.Lstat(target);statErr==nil{if err=os.Rename(target,backup);err!=nil{return err};state.MailBackups[entry.Name()]=backup};if err=os.Rename(source,target);err!=nil{return err}};return nil}
func(host *LinuxBackupHost)restoreSafetyFiles(binding LinuxBackupSiteBinding,archive string)error{
	temporary:=filepath.Join(host.Root,"restores","rollback-"+linuxBackupID("files",binding.SiteKey)[:24]);_ = removeLinuxBackupTree(temporary)
	if err:=ensureLinuxBackupDirectory(temporary,0700);err!=nil{return err}
	if err:=extractLinuxBackupSiteTar(archive,temporary,binding);err!=nil{return err}
	generationRoot:=host.generationRoot(binding);release:=filepath.Join(temporary,"release")
	target:=filepath.Join(generationRoot,"releases","rollback-"+linuxBackupID("release",binding.SiteKey,strconv.FormatInt(host.now().UnixNano(),10))[:20])
	if err:=os.Rename(release,target);err!=nil{return err}
	current:=filepath.Join(generationRoot,"releases","current")
	previous,err:=linuxBackupReleaseIdentity(current,false);if err!=nil{return err}
	candidate,err:=linuxBackupReleaseIdentity(target,true);if err!=nil{return err}
	if err=switchLinuxBackupCurrent(target,current,previous,candidate);err!=nil{return err}
	private:=filepath.Join(temporary,"private");if _,err:=os.Lstat(private);err==nil{live:=filepath.Join(generationRoot,"private");old:=live+".failed-"+strconv.FormatInt(host.now().Unix(),10);if _,statErr:=os.Lstat(live);statErr==nil{if err=os.Rename(live,old);err!=nil{return err}};if err=os.Rename(private,live);err!=nil{return err}}
	return nil
}
func(host *LinuxBackupHost)restoreSafetyMail(archive string)error{temporary:=filepath.Join(host.Root,"restores","mail-rollback-"+strconv.FormatInt(host.now().UnixNano(),10));if err:=ensureLinuxBackupDirectory(temporary,0700);err!=nil{return err};if err:=extractLinuxBackupTar(archive,temporary);err!=nil{return err};entries,err:=os.ReadDir(filepath.Join(temporary,"mailboxes"));if errors.Is(err,os.ErrNotExist){return nil};if err!=nil{return err};for _,entry:=range entries{if !entry.IsDir()||!safeLinuxBackupName(entry.Name()){return ErrInvalidBackup};source:=filepath.Join(temporary,"mailboxes",entry.Name());target:=filepath.Join(linuxBackupMailRoot,entry.Name());failed:=target+".failed-"+strconv.FormatInt(host.now().Unix(),10);if _,statErr:=os.Lstat(target);statErr==nil{if err=os.Rename(target,failed);err!=nil{return err}};if err=os.Rename(source,target);err!=nil{return err}};return nil}
func(host *LinuxBackupHost)importDatabase(ctx context.Context,dump string)error{file,err:=openLinuxBackupRegular(dump);if err!=nil{return err};defer file.Close();command:=exec.CommandContext(ctx,"/usr/bin/mariadb","--protocol=socket","--socket=/run/mysqld/mysqld.sock","--user=root");command.Env=[]string{"PATH=/usr/bin:/bin","LANG=C.UTF-8","LC_ALL=C.UTF-8","HOME=/root"};command.Stdin=file;stderr:=&linuxBackupLimitedBuffer{maximum:1<<20};command.Stderr=stderr;if err=command.Run();err!=nil{return fmt.Errorf("fixed MariaDB restore failed: %w: %s",err,stderr.String())};return nil}

func(host *LinuxBackupHost)targetFingerprint(ctx context.Context,plan RestorePlanSpec,binding LinuxBackupSiteBinding)(string,error){hash:=sha256.New();if _,ok:=plan.ComponentMapping[ComponentFiles];ok{value,err:=linuxBackupTreeFingerprint(host.generationRoot(binding));if err!=nil{return "",err};_,_=io.WriteString(hash,value)};if _,ok:=plan.ComponentMapping[ComponentDatabase];ok{value,err:=linuxBackupScopedDatabaseFingerprint(ctx,binding);if err!=nil{return "",err};_,_=io.WriteString(hash,value)};if _,ok:=plan.ComponentMapping[ComponentMail];ok{domains,err:=linuxBackupMailDomains(ctx,plan.TenantID);if err!=nil{return "",err};for _,domain:=range domains{value,treeErr:=linuxBackupTreeFingerprint(filepath.Join(linuxBackupMailRoot,domain));if treeErr!=nil&&!errors.Is(treeErr,os.ErrNotExist){return "",treeErr};_,_=io.WriteString(hash,value)}};return hex.EncodeToString(hash.Sum(nil)),nil}
func(host *LinuxBackupHost)resolve(ctx context.Context,tenant,scope string)(LinuxBackupSiteBinding,error){binding,err:=host.Resolver.ResolveBackupSite(ctx,tenant,scope);if err!=nil{return LinuxBackupSiteBinding{},err};if binding.SiteKey==""||binding.SiteID!=scope||binding.Generation==0||binding.UID<1000||binding.GID!=binding.UID||tenant!=""&&binding.TenantID!=tenant||!safeLinuxBackupName(binding.SiteKey){return LinuxBackupSiteBinding{},ErrInvalidBackup};return binding,nil}
func(host *LinuxBackupHost)generationRoot(binding LinuxBackupSiteBinding)string{return filepath.Join(linuxBackupSitesRoot,binding.SiteKey,"roots","g"+strconv.FormatUint(binding.Generation,10))}
func(host *LinuxBackupHost)effectRoot(effect string)string{return filepath.Join(host.Root,"effects",linuxBackupID("effect",effect))}
func(host *LinuxBackupHost)restoreRoot(plan RestorePlanSpec)string{return filepath.Join(host.Root,"restores",linuxBackupID("restore",string(plan.ID),plan.TenantID,plan.TargetScope))}
func(host *LinuxBackupHost)watermarkPath(scope string)string{return filepath.Join(host.Root,"watermarks",linuxBackupID("scope",scope)+".json")}
func(host *LinuxBackupHost)loadWatermark(scope string)uint64{var value uint64;if readLinuxBackupJSON(host.watermarkPath(scope),&value)!=nil||value==0{return 1};return value}
func(host *LinuxBackupHost)saveWatermark(scope string,value uint64){_ = writeLinuxBackupJSON(host.watermarkPath(scope),value)}

func linuxBackupDatabaseNames(binding LinuxBackupSiteBinding)([]string,error){entries,err:=os.ReadDir(linuxBackupDatabaseStateRoot);if errors.Is(err,os.ErrNotExist){return nil,nil};if err!=nil{return nil,err};names:=[]string{};for _,entry:=range entries{if entry.IsDir()||!strings.HasSuffix(entry.Name(),".json")||!safeLinuxBackupName(entry.Name()){return nil,ErrInvalidBackup};var resource database.Database;if err=readLinuxBackupJSON(filepath.Join(linuxBackupDatabaseStateRoot,entry.Name()),&resource);err!=nil{return nil,err};if resource.Metadata.TenantID.String()==binding.TenantID&&resource.Metadata.SiteID.String()==binding.SiteID&&resource.Metadata.Status.Lifecycle!=database.LifecycleDeleted{names=append(names,resource.Name.String())}};sort.Strings(names);return names,nil}
func linuxBackupMailDomains(ctx context.Context,tenant string)([]string,error){if tenant==""{return nil,ErrInvalidBackup};handle,err:=sql.Open("sqlite","file:"+linuxBackupControlDatabase+"?mode=ro&_pragma=busy_timeout(5000)&_pragma=trusted_schema(0)");if err!=nil{return nil,err};defer handle.Close();rows,err:=handle.QueryContext(ctx,`SELECT resource_json FROM mail_resources_v2 WHERE tenant_id=? AND kind=? AND state<>? ORDER BY resource_id`,tenant,mail.ResourceDomain,mail.StateDeleted);if err!=nil{return nil,err};defer rows.Close();domains:=[]string{};for rows.Next(){var raw []byte;if err=rows.Scan(&raw);err!=nil{return nil,err};var envelope mail.ResourceEnvelope;if json.Unmarshal(raw,&envelope)!=nil||envelope.TenantID!=tenant{return nil,ErrInvalidBackup};var domain mail.Domain;if json.Unmarshal(envelope.Spec,&domain)!=nil||domain.Tenant!=tenant||!safeLinuxBackupDomain(domain.Name){return nil,ErrInvalidBackup};domains=append(domains,strings.ToLower(domain.Name))};return domains,rows.Err()}

func drainLinuxBackupArtifact(stream io.Reader,artifact ArtifactManifest)error{for _,descriptor:=range artifact.Objects{written,err:=io.CopyN(io.Discard,stream,int64(descriptor.Size));if err!=nil||uint64(written)!=descriptor.Size{return errors.Join(ErrInvalidBackup,err)}};return nil}

func appendLinuxBackupTree(ctx context.Context,writer *tar.Writer,root,prefix string)error{rootInfo,err:=os.Lstat(root);if err!=nil{return err};if !rootInfo.IsDir()||rootInfo.Mode()&os.ModeSymlink!=0{return ErrInvalidBackup};return filepath.WalkDir(root,func(path string,entry fs.DirEntry,walkErr error)error{if walkErr!=nil{return walkErr};if err:=ctx.Err();err!=nil{return err};relative,err:=filepath.Rel(root,path);if err!=nil{return err};name:=prefix;if relative!="."{name=filepath.ToSlash(filepath.Join(prefix,relative))};info,err:=entry.Info();if err!=nil{return err};mode:=info.Mode();if mode&os.ModeSocket!=0||mode&os.ModeDevice!=0||mode&os.ModeCharDevice!=0||mode&os.ModeNamedPipe!=0{return ErrInvalidBackup};link:="";if mode&os.ModeSymlink!=0{link,err=os.Readlink(path);if err!=nil||!safeLinuxBackupLink(link){return ErrInvalidBackup}};header,err:=tar.FileInfoHeader(info,link);if err!=nil{return err};header.Name=name;header.Uid=0;header.Gid=0;header.Uname="";header.Gname="";header.ModTime=header.ModTime.UTC();header.AccessTime=time.Time{};header.ChangeTime=time.Time{};if err=writer.WriteHeader(header);err!=nil{return err};if mode.IsRegular(){file,err:=openLinuxBackupRegular(path);if err!=nil{return err};_,copyErr:=io.CopyN(writer,file,info.Size());closeErr:=file.Close();return errors.Join(copyErr,closeErr)};return nil})}
func extractLinuxBackupTar(archive,target string)error{file,err:=openLinuxBackupRegular(archive);if err!=nil{return err};defer file.Close();reader:=tar.NewReader(file);count:=0;for{header,readErr:=reader.Next();if errors.Is(readErr,io.EOF){break};if readErr!=nil{return readErr};count++;if count>10000000||header.Name==""||filepath.IsAbs(header.Name){return ErrInvalidBackup};clean:=filepath.Clean(filepath.FromSlash(header.Name));if clean=="."||clean==".."||strings.HasPrefix(clean,".."+string(os.PathSeparator))||filepath.ToSlash(clean)!=strings.TrimPrefix(header.Name,"./"){return ErrInvalidBackup};path:=filepath.Join(target,clean);if path!=target&&!strings.HasPrefix(path,target+string(os.PathSeparator)){return ErrInvalidBackup};switch header.Typeflag{case tar.TypeDir:mode:=os.FileMode(header.Mode)&0770;if mode&0700==0{mode|=0700};if err=ensureLinuxBackupDirectory(path,mode);err!=nil{return err};case tar.TypeReg,tar.TypeRegA:if err=ensureLinuxBackupDirectory(filepath.Dir(path),0700);err!=nil{return err};out,err:=createLinuxBackupFile(path);if err!=nil{return err};written,copyErr:=io.CopyN(out,reader,header.Size);syncErr:=out.Sync();closeErr:=out.Close();if copyErr!=nil||syncErr!=nil||closeErr!=nil||written!=header.Size{return errors.Join(ErrInvalidBackup,copyErr,syncErr,closeErr)};if err=os.Chmod(path,os.FileMode(header.Mode)&0770);err!=nil{return err};case tar.TypeSymlink:if !safeLinuxBackupLink(header.Linkname){return ErrInvalidBackup};if err=ensureLinuxBackupDirectory(filepath.Dir(path),0700);err!=nil{return err};if err=os.Symlink(header.Linkname,path);err!=nil{return err};default:return ErrInvalidBackup}};return nil}

func safeCurrentRelease(generationRoot string)(string,error){releases:=filepath.Join(generationRoot,"releases");current:=filepath.Join(releases,"current");resolved,err:=filepath.EvalSymlinks(current);if err!=nil{return "",err};resolved=filepath.Clean(resolved);if resolved==releases||!strings.HasPrefix(resolved,releases+string(os.PathSeparator)){return "",ErrInvalidBackup};info,err:=os.Lstat(resolved);if err!=nil||!info.IsDir()||info.Mode()&os.ModeSymlink!=0{return "",errors.Join(ErrInvalidBackup,err)};return resolved,nil}
func commitLinuxBackupObject(temporary,objectsRoot,key string)(ObjectDescriptor,error){digest,size,err:=digestLinuxBackupFile(temporary);if err!=nil{return ObjectDescriptor{},err};target:=filepath.Join(objectsRoot,digest);if err=os.Rename(temporary,target);err!=nil{if existingDigest,existingSize,verifyErr:=digestLinuxBackupFile(target);verifyErr!=nil||existingDigest!=digest||existingSize!=size{return ObjectDescriptor{},errors.Join(err,verifyErr)};_ = os.Remove(temporary)};return ObjectDescriptor{Key:key,Digest:digest,Size:size,Mode:0600},nil}
func digestLinuxBackupFile(path string)(string,uint64,error){file,err:=openLinuxBackupRegular(path);if err!=nil{return "",0,err};defer file.Close();hash:=sha256.New();written,err:=io.Copy(hash,file);if err!=nil{return "",0,err};return hex.EncodeToString(hash.Sum(nil)),uint64(written),nil}
func createLinuxBackupFile(path string)(*os.File,error){if err:=ensureLinuxBackupDirectory(filepath.Dir(path),0700);err!=nil{return nil,err};fd,err:=syscall.Open(path,syscall.O_WRONLY|syscall.O_CREAT|syscall.O_EXCL|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0600);if errors.Is(err,syscall.EEXIST){if removeErr:=os.Remove(path);removeErr!=nil{return nil,removeErr};fd,err=syscall.Open(path,syscall.O_WRONLY|syscall.O_CREAT|syscall.O_EXCL|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0600)};if err!=nil{return nil,err};return os.NewFile(uintptr(fd),path),nil}
func openLinuxBackupRegular(path string)(*os.File,error){info,err:=os.Lstat(path);if err!=nil{return nil,err};if !info.Mode().IsRegular()||info.Mode()&os.ModeSymlink!=0||info.Mode().Perm()&0002!=0{return nil,ErrInvalidBackup};fd,err:=syscall.Open(path,syscall.O_RDONLY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if err!=nil{return nil,err};file:=os.NewFile(uintptr(fd),path);opened,err:=file.Stat();if err!=nil||!os.SameFile(info,opened){file.Close();return nil,ErrInvalidBackup};return file,nil}
func ensureLinuxBackupDirectory(path string,mode os.FileMode)error{if !filepath.IsAbs(path)||filepath.Clean(path)!=path||mode.Perm()&0007!=0{return ErrInvalidBackup};if err:=os.MkdirAll(path,mode);err!=nil{return err};info,err:=os.Lstat(path);if err!=nil{return err};stat,ok:=info.Sys().(*syscall.Stat_t);if !ok||!info.IsDir()||info.Mode()&os.ModeSymlink!=0||stat.Uid!=0||info.Mode().Perm()&0007!=0{return ErrInvalidBackup};return nil}
func writeLinuxBackupJSON(path string,value any)error{payload,err:=json.Marshal(value);if err!=nil{return err};if err=ensureLinuxBackupDirectory(filepath.Dir(path),0700);err!=nil{return err};temporary:=path+".new";_ = os.Remove(temporary);file,err:=createLinuxBackupFile(temporary);if err!=nil{return err};_,writeErr:=file.Write(append(payload,'\n'));syncErr:=file.Sync();closeErr:=file.Close();if err=errors.Join(writeErr,syncErr,closeErr);err!=nil{_ = os.Remove(temporary);return err};if err=os.Rename(temporary,path);err!=nil{_ = os.Remove(temporary);return err};directory,err:=os.Open(filepath.Dir(path));if err!=nil{return err};syncErr=directory.Sync();closeErr=directory.Close();return errors.Join(syncErr,closeErr)}
func readLinuxBackupJSON(path string,value any)error{file,err:=openLinuxBackupRegular(path);if err!=nil{return err};defer file.Close();decoder:=json.NewDecoder(io.LimitReader(file,64<<20));decoder.DisallowUnknownFields();if err=decoder.Decode(value);err!=nil{return err};if err=decoder.Decode(&struct{}{});!errors.Is(err,io.EOF){return ErrInvalidBackup};return nil}
func removeLinuxBackupTree(path string)error{if path==""||path=="/"||!strings.HasPrefix(path,LinuxBackupRuntimeRoot+string(os.PathSeparator)){return ErrInvalidBackup};info,err:=os.Lstat(path);if errors.Is(err,os.ErrNotExist){return nil};if err!=nil{return err};if info.Mode()&os.ModeSymlink!=0{return ErrInvalidBackup};return os.RemoveAll(path)}
func stopLinuxBackupServices(ctx context.Context,services []string)([]string,error){stopped:=[]string{};for _,service:=range services{if !validLinuxBackupService(service){return stopped,ErrInvalidBackup};probe:=exec.CommandContext(ctx,"/usr/bin/systemctl","is-active","--quiet",service);probe.Env=[]string{"PATH=/usr/bin:/bin","LANG=C","LC_ALL=C"};if probe.Run()!=nil{continue};command:=exec.CommandContext(ctx,"/usr/bin/systemctl","stop",service);command.Env=[]string{"PATH=/usr/bin:/bin","LANG=C","LC_ALL=C"};output:=&linuxBackupLimitedBuffer{maximum:1<<20};command.Stdout,command.Stderr=output,output;if err:=command.Run();err!=nil{_ = startLinuxBackupServices(ctx,stopped);return stopped,fmt.Errorf("stop fixed backup service %s: %w",service,err)};stopped=append(stopped,service)};return stopped,nil}
func startLinuxBackupServices(ctx context.Context,services []string)error{var result error;for index:=len(services)-1;index>=0;index--{service:=services[index];if !validLinuxBackupService(service){result=errors.Join(result,ErrInvalidBackup);continue};command:=exec.CommandContext(ctx,"/usr/bin/systemctl","start",service);command.Env=[]string{"PATH=/usr/bin:/bin","LANG=C","LC_ALL=C"};output:=&linuxBackupLimitedBuffer{maximum:1<<20};command.Stdout,command.Stderr=output,output;if err:=command.Run();err!=nil{result=errors.Join(result,fmt.Errorf("start fixed backup service %s: %w",service,err))}};return result}
func validLinuxBackupService(value string)bool{switch value{case"lsws.service","postfix.service","dovecot.service":return true};return false}
func safeLinuxBackupName(value string)bool{if value==""||value=="."||value==".."||len(value)>255{return false};for _,character:=range value{if !(character>='a'&&character<='z'||character>='A'&&character<='Z'||character>='0'&&character<='9'||character=='-'||character=='_'||character=='.'){return false}};return true}
func safeLinuxBackupDomain(value string)bool{if value==""||len(value)>253||strings.HasPrefix(value,".")||strings.HasSuffix(value,".")||strings.Contains(value,".."){return false};for _,label:=range strings.Split(value,"."){if !safeLinuxBackupName(label)||strings.HasPrefix(label,"-")||strings.HasSuffix(label,"-"){return false}};return true}
func safeLinuxBackupLink(value string)bool{if value==""||filepath.IsAbs(value){return false};clean:=filepath.Clean(value);return clean!=".."&&!strings.HasPrefix(clean,".."+string(os.PathSeparator))}
func linuxBackupID(parts ...string)string{return "b_"+linuxBackupDigest(parts...)[:48]}
func linuxBackupDigest(parts ...string)string{hash:=sha256.New();for _,part:=range parts{_,_=io.WriteString(hash,strconv.Itoa(len(part)));_,_=io.WriteString(hash,":");_,_=io.WriteString(hash,part)};return hex.EncodeToString(hash.Sum(nil))}
type linuxBackupLimitedBuffer struct{builder strings.Builder;maximum int;overflow bool}
func(buffer *linuxBackupLimitedBuffer)Write(value []byte)(int,error){original:=len(value);remaining:=buffer.maximum-buffer.builder.Len();if remaining>0{if len(value)>remaining{value=value[:remaining];buffer.overflow=true};_,_=buffer.builder.Write(value)}else{buffer.overflow=true};return original,nil}
func(buffer *linuxBackupLimitedBuffer)String()string{return buffer.builder.String()}
