package backup

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"strings"
	"time"
)

type RestorePhase string
const ( RestoreCreated RestorePhase="created";RestoreValidating RestorePhase="validating";RestoreStaging RestorePhase="staging";RestoreProbing RestorePhase="probing";RestoreCutoverReady RestorePhase="cutover_ready";RestorePromoting RestorePhase="promoting";RestoreActive RestorePhase="active";RestoreFailed RestorePhase="failed";RestoreAmbiguous RestorePhase="ambiguous";RestoreRollingBack RestorePhase="rolling_back";RestoreRolledBack RestorePhase="rolled_back";RestoreFailForward RestorePhase="fail_forward_required" )
type CollisionPolicy string
const ( CollisionReject CollisionPolicy="reject";CollisionRename CollisionPolicy="rename";CollisionReplaceBlueGreen CollisionPolicy="replace_blue_green" )
type SecretPolicy string
const ( SecretRotate SecretPolicy="rotate";SecretPreserveEncrypted SecretPolicy="preserve_encrypted";SecretResetRequired SecretPolicy="reset_required" )
type RestorePlanSpec struct { ID RestoreID `json:"id"`; IdempotencyKey string `json:"idempotency_key"`; TenantID string `json:"tenant_id"`; RecoveryPointID RecoveryPointID `json:"recovery_point_id"`; SourceScope string `json:"source_scope"`; TargetScope string `json:"target_scope"`; ComponentMapping map[ComponentKind]string `json:"component_mapping"`; CollisionPolicy CollisionPolicy `json:"collision_policy"`; SecretPolicy SecretPolicy `json:"secret_policy"`; DomainMapping map[string]string `json:"domain_mapping"`; RequiredFreeBytes uint64 `json:"required_free_bytes"`; Generation uint64 `json:"generation"` }
type RestoreReceipt struct { PlanID RestoreID `json:"plan_id"`; TenantID string `json:"tenant_id"`; Phase RestorePhase `json:"phase"`; PlanDigest string `json:"plan_digest"`; ManifestDigest string `json:"manifest_digest"`; ScanDigest string `json:"scan_digest,omitempty"`; ScratchID string `json:"scratch_id,omitempty"`; StageReceipt string `json:"stage_receipt,omitempty"`; StageReceipts map[ComponentKind]string `json:"stage_receipts,omitempty"`; PreviousGeneration string `json:"previous_generation,omitempty"`; SafetySnapshotID string `json:"safety_snapshot_id,omitempty"`; TargetGeneration string `json:"target_generation,omitempty"`; RollbackFrontier uint64 `json:"rollback_frontier"`; PromotionWatermark uint64 `json:"promotion_watermark"`; TargetWriteWatermark uint64 `json:"target_write_watermark"`; FirstWriteAt *time.Time `json:"first_write_at,omitempty"`; ProbeDigest string `json:"probe_digest,omitempty"`; Error string `json:"error,omitempty"`; Generation uint64 `json:"generation"`; UpdatedAt time.Time `json:"updated_at"` }
type RestoreCapacity interface { VerifyCapacity(context.Context,string,uint64)error }
type RestoreSource interface { LoadManifest(context.Context,string,RecoveryPointID)(RecoveryPointManifest,[]CopyReceipt,error); OpenVerifiedObject(context.Context,string,RecoveryPointManifest,ObjectDescriptor)(ReadObject,error) }
type ReadObject struct { Descriptor ObjectDescriptor; Reader ReadCloser }
type ReadCloser interface { Read([]byte)(int,error);Close()error }
type RestoreScanner interface { Inspect(context.Context,RecoveryPointManifest,func(context.Context,ObjectDescriptor)(ReadObject,error))(string,error) }
type RestoreTarget interface { CreateScratch(context.Context,RestorePlanSpec,RecoveryPointManifest,string)(string,error); StageArtifact(context.Context,RestorePlanSpec,string,ArtifactManifest,func(context.Context,ObjectDescriptor)(ReadObject,error),string)(string,error); VerifyScratch(context.Context,RestorePlanSpec,string,RecoveryPointManifest)(string,error); CurrentGeneration(context.Context,RestorePlanSpec)(string,uint64,error); Promote(context.Context,RestorePlanSpec,string,string)(string,error); ObserveWrites(context.Context,RestorePlanSpec,string)(uint64,*time.Time,error); RestorePrevious(context.Context,RestorePlanSpec,string,string)error; Quarantine(context.Context,RestorePlanSpec,string,string)error; Finalize(context.Context,RestorePlanSpec,string,string)error }
type RestoreSafety interface { CreateSafetySnapshot(context.Context,RestorePlanSpec,string,uint64,string)(string,error); FreezeTargetWrites(context.Context,RestorePlanSpec,string)(uint64,error); UnfreezeTargetWrites(context.Context,RestorePlanSpec,string,string)error; VerifyPromotedHealth(context.Context,RestorePlanSpec,string,string)(string,error) }
type RestoreStore struct{DB *sql.DB}
const restoreSchema=`CREATE TABLE IF NOT EXISTS restore_plans_v2(id TEXT PRIMARY KEY,idempotency_key TEXT NOT NULL UNIQUE,tenant_id TEXT NOT NULL,generation INTEGER NOT NULL,plan_json BLOB NOT NULL);CREATE TABLE IF NOT EXISTS restore_receipts_v2(plan_id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,phase TEXT NOT NULL,generation INTEGER NOT NULL,receipt_json BLOB NOT NULL,updated_at TIMESTAMP NOT NULL);`
func (s RestoreStore)Bootstrap(ctx context.Context)error{if s.DB==nil{return errors.New("restore database required")};_,err:=s.DB.ExecContext(ctx,restoreSchema);return err}
func (s RestoreStore)Admit(ctx context.Context,plan RestorePlanSpec)(RestoreReceipt,bool,error){if s.DB==nil{return RestoreReceipt{},false,ErrInvalidBackup};if err:=validateRestorePlan(plan);err!=nil{return RestoreReceipt{},false,err};planRaw,err:=json.Marshal(plan);if err!=nil{return RestoreReceipt{},false,err};planDigest:=restorePlanDigest(planRaw);tx,err:=s.DB.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return RestoreReceipt{},false,err};defer tx.Rollback();var priorRaw,receiptRaw []byte;err=tx.QueryRowContext(ctx,`SELECT p.plan_json,r.receipt_json FROM restore_plans_v2 p JOIN restore_receipts_v2 r ON r.plan_id=p.id AND r.tenant_id=p.tenant_id WHERE p.tenant_id=? AND (p.id=? OR p.idempotency_key=?) LIMIT 1`,plan.TenantID,plan.ID,plan.IdempotencyKey).Scan(&priorRaw,&receiptRaw);if err==nil{var receipt RestoreReceipt;if json.Unmarshal(receiptRaw,&receipt)!=nil||receipt.PlanID!=plan.ID||receipt.TenantID!=plan.TenantID||receipt.PlanDigest!=planDigest||!equalJSONBytes(priorRaw,planRaw){return RestoreReceipt{},false,ErrBackupConflict};return receipt,false,nil};if !errors.Is(err,sql.ErrNoRows){return RestoreReceipt{},false,err};now:=time.Now().UTC();receipt:=RestoreReceipt{PlanID:plan.ID,TenantID:plan.TenantID,Phase:RestoreCreated,PlanDigest:planDigest,StageReceipts:map[ComponentKind]string{},Generation:1,UpdatedAt:now};receiptRaw,err=json.Marshal(receipt);if err!=nil{return RestoreReceipt{},false,err};if _,err=tx.ExecContext(ctx,`INSERT INTO restore_plans_v2(id,idempotency_key,tenant_id,generation,plan_json) VALUES(?,?,?,?,?)`,plan.ID,plan.IdempotencyKey,plan.TenantID,plan.Generation,planRaw);err!=nil{return RestoreReceipt{},false,err};if _,err=tx.ExecContext(ctx,`INSERT INTO restore_receipts_v2(plan_id,tenant_id,phase,generation,receipt_json,updated_at) VALUES(?,?,?,?,?,?)`,plan.ID,plan.TenantID,receipt.Phase,receipt.Generation,receiptRaw,now);err!=nil{return RestoreReceipt{},false,err};if err=tx.Commit();err!=nil{return RestoreReceipt{},false,err};return receipt,true,nil}
func (s RestoreStore)Load(ctx context.Context,tenant string,id RestoreID)(RestorePlanSpec,RestoreReceipt,error){if s.DB==nil||tenant==""||id==""{return RestorePlanSpec{},RestoreReceipt{},ErrInvalidBackup};var planRaw,receiptRaw []byte;if err:=s.DB.QueryRowContext(ctx,`SELECT p.plan_json,r.receipt_json FROM restore_plans_v2 p JOIN restore_receipts_v2 r ON r.plan_id=p.id AND r.tenant_id=p.tenant_id WHERE p.id=? AND p.tenant_id=?`,id,tenant).Scan(&planRaw,&receiptRaw);err!=nil{return RestorePlanSpec{},RestoreReceipt{},err};var plan RestorePlanSpec;var receipt RestoreReceipt;if json.Unmarshal(planRaw,&plan)!=nil||json.Unmarshal(receiptRaw,&receipt)!=nil||validateRestorePlan(plan)!=nil||plan.ID!=id||plan.TenantID!=tenant||receipt.PlanID!=id||receipt.TenantID!=tenant||receipt.PlanDigest!=restorePlanDigest(planRaw){return RestorePlanSpec{},RestoreReceipt{},ErrInvalidBackup};return plan,receipt,nil}
func (s RestoreStore)Save(ctx context.Context,receipt *RestoreReceipt)error{if s.DB==nil||receipt==nil||receipt.PlanID==""||receipt.TenantID==""||receipt.Generation==0||!isSHA256(receipt.PlanDigest){return ErrInvalidBackup};tx,err:=s.DB.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return err};defer tx.Rollback();var current RestorePhase;var generation uint64;if err=tx.QueryRowContext(ctx,`SELECT phase,generation FROM restore_receipts_v2 WHERE plan_id=? AND tenant_id=?`,receipt.PlanID,receipt.TenantID).Scan(&current,&generation);err!=nil{return err};if generation!=receipt.Generation||!validRestoreTransition(current,receipt.Phase){return ErrBackupConflict};next:=*receipt;next.Generation=generation+1;next.UpdatedAt=time.Now().UTC();raw,err:=json.Marshal(next);if err!=nil{return err};result,err:=tx.ExecContext(ctx,`UPDATE restore_receipts_v2 SET phase=?,generation=?,receipt_json=?,updated_at=? WHERE plan_id=? AND tenant_id=? AND generation=?`,next.Phase,next.Generation,raw,next.UpdatedAt,next.PlanID,next.TenantID,generation);if err!=nil{return err};affected,err:=result.RowsAffected();if err!=nil{return err};if affected!=1{return ErrBackupConflict};if err=tx.Commit();err!=nil{return err};*receipt=next;return nil}
func validRestoreTransition(current,next RestorePhase)bool{if current==next{return true};switch current{case RestoreCreated:return next==RestoreValidating||next==RestoreFailed;case RestoreValidating:return next==RestoreStaging||next==RestoreFailed;case RestoreStaging:return next==RestoreProbing||next==RestoreFailed;case RestoreProbing:return next==RestoreCutoverReady||next==RestoreFailed;case RestoreCutoverReady:return next==RestorePromoting||next==RestoreFailed||next==RestoreAmbiguous;case RestorePromoting:return next==RestoreActive||next==RestoreRollingBack||next==RestoreRolledBack||next==RestoreFailForward||next==RestoreAmbiguous;case RestoreActive:return next==RestoreRollingBack||next==RestoreFailForward||next==RestoreAmbiguous;case RestoreRollingBack:return next==RestoreRolledBack||next==RestoreFailForward||next==RestoreAmbiguous;case RestoreAmbiguous:return next==RestoreRollingBack||next==RestoreFailForward||next==RestoreRolledBack};return false}

type RestoreCoordinator struct { Store RestoreStore; Capacity RestoreCapacity; Source RestoreSource; Scanner RestoreScanner; Target RestoreTarget; Safety RestoreSafety; Now func()time.Time }
func (c RestoreCoordinator)Plan(ctx context.Context,plan RestorePlanSpec)(RestoreReceipt,error){if c.Store.DB==nil||c.Capacity==nil||c.Source==nil{return RestoreReceipt{},errors.New("restore planning dependencies required")};if err:=validateRestorePlan(plan);err!=nil{return RestoreReceipt{},err};manifest,copies,err:=c.Source.LoadManifest(ctx,plan.TenantID,plan.RecoveryPointID);if err!=nil{return RestoreReceipt{},err};if err=validateRestoreSource(plan,manifest,copies);err!=nil{return RestoreReceipt{},err};required,err:=requiredRestoreBytes(plan,manifest);if err!=nil||plan.SourceScope!=manifest.Scope||plan.RequiredFreeBytes<required{return RestoreReceipt{},ErrInvalidBackup};if err=c.Capacity.VerifyCapacity(ctx,plan.TargetScope,plan.RequiredFreeBytes);err!=nil{return RestoreReceipt{},err};receipt,_,err:=c.Store.Admit(ctx,plan);if err!=nil{return RestoreReceipt{},err};if receipt.ManifestDigest!=""&&receipt.ManifestDigest!=manifest.ManifestDigest{return RestoreReceipt{},ErrBackupConflict};if receipt.ManifestDigest==""{receipt.ManifestDigest=manifest.ManifestDigest;if err=c.Store.Save(ctx,&receipt);err!=nil{return receipt,err}};return receipt,nil}
func (c RestoreCoordinator)Status(ctx context.Context,tenant string,id RestoreID)(RestorePlanSpec,RestoreReceipt,error){return c.Store.Load(ctx,tenant,id)}
func (c RestoreCoordinator)Apply(ctx context.Context,tenant string,id RestoreID,expectedGeneration uint64)(RestoreReceipt,error){if c.Store.DB==nil||c.Capacity==nil||c.Source==nil||c.Scanner==nil||c.Target==nil||c.Safety==nil{return RestoreReceipt{},errors.New("restore apply dependencies required")};plan,receipt,err:=c.Store.Load(ctx,tenant,id);if err!=nil{return RestoreReceipt{},err};if expectedGeneration==0||receipt.Generation!=expectedGeneration{return receipt,ErrBackupConflict};switch receipt.Phase{case RestoreActive,RestoreRolledBack,RestoreFailForward:return receipt,nil;case RestoreFailed:return receipt,errors.Join(ErrBackupConflict,errors.New(receipt.Error));case RestorePromoting,RestoreRollingBack,RestoreAmbiguous:return receipt,ErrBackupAmbiguous;case RestoreCreated:if receipt.ManifestDigest==""{return receipt,ErrInvalidBackup};receipt.Phase=RestoreValidating;if err=c.Store.Save(ctx,&receipt);err!=nil{return receipt,err};case RestoreValidating,RestoreStaging,RestoreProbing,RestoreCutoverReady:default:return receipt,ErrBackupConflict};return c.apply(ctx,plan,receipt)}
func (c RestoreCoordinator)Execute(ctx context.Context,plan RestorePlanSpec)(RestoreReceipt,error){receipt,err:=c.Plan(ctx,plan);if err!=nil{return receipt,err};return c.Apply(ctx,plan.TenantID,plan.ID,receipt.Generation)}
func (c RestoreCoordinator)apply(ctx context.Context,plan RestorePlanSpec,receipt RestoreReceipt)(RestoreReceipt,error){manifest,copies,err:=c.Source.LoadManifest(ctx,plan.TenantID,plan.RecoveryPointID);if err!=nil{return c.abortBeforePromotion(ctx,plan,receipt,err)};if err=validateRestoreSource(plan,manifest,copies);err!=nil||manifest.ManifestDigest!=receipt.ManifestDigest{if err==nil{err=ErrBackupConflict};return c.abortBeforePromotion(ctx,plan,receipt,err)};if err=c.Capacity.VerifyCapacity(ctx,plan.TargetScope,plan.RequiredFreeBytes);err!=nil{return c.abortBeforePromotion(ctx,plan,receipt,err)}
	if receipt.Phase==RestoreValidating{scan,scanErr:=c.Scanner.Inspect(ctx,manifest,func(readCtx context.Context,object ObjectDescriptor)(ReadObject,error){return c.Source.OpenVerifiedObject(readCtx,plan.TenantID,manifest,object)});if scanErr!=nil||scan==""{if scanErr==nil{scanErr=ErrInvalidBackup};return c.fail(ctx,receipt,scanErr,RestoreFailed)};receipt.ScanDigest=scan;receipt.Phase=RestoreStaging;if err=c.Store.Save(ctx,&receipt);err!=nil{return receipt,err}}
	if receipt.Phase==RestoreStaging{scratch,createErr:=c.Target.CreateScratch(ctx,plan,manifest,string(plan.ID));if createErr!=nil||scratch==""{if createErr==nil{createErr=ErrInvalidBackup};return c.fail(ctx,receipt,createErr,RestoreFailed)};if receipt.ScratchID!=""&&receipt.ScratchID!=scratch{return c.fail(ctx,receipt,ErrBackupConflict,RestoreFailed)};receipt.ScratchID=scratch;if receipt.StageReceipts==nil{receipt.StageReceipts=map[ComponentKind]string{}};if err=c.Store.Save(ctx,&receipt);err!=nil{return receipt,err};for _,artifact:=range manifest.Artifacts{stage,stageErr:=c.Target.StageArtifact(ctx,plan,scratch,artifact,func(readCtx context.Context,object ObjectDescriptor)(ReadObject,error){return c.Source.OpenVerifiedObject(readCtx,plan.TenantID,manifest,object)},string(plan.ID));if stageErr!=nil||stage==""{if stageErr==nil{stageErr=ErrInvalidBackup};return c.fail(ctx,receipt,stageErr,RestoreFailed)};receipt.StageReceipt=stage;receipt.StageReceipts[artifact.Component]=stage;if err=c.Store.Save(ctx,&receipt);err!=nil{return receipt,err}};receipt.Phase=RestoreProbing;if err=c.Store.Save(ctx,&receipt);err!=nil{return receipt,err}}
	if receipt.Phase==RestoreProbing{probe,probeErr:=c.Target.VerifyScratch(ctx,plan,receipt.ScratchID,manifest);if probeErr!=nil||probe==""{if probeErr==nil{probeErr=ErrInvalidBackup};return c.fail(ctx,receipt,probeErr,RestoreFailed)};receipt.ProbeDigest=probe;previous,watermark,currentErr:=c.Target.CurrentGeneration(ctx,plan);if currentErr!=nil||previous==""||watermark==0{if currentErr==nil{currentErr=ErrInvalidBackup};return c.fail(ctx,receipt,currentErr,RestoreFailed)};receipt.PreviousGeneration=previous;receipt.RollbackFrontier=watermark;receipt.TargetWriteWatermark=watermark;if err=c.Store.Save(ctx,&receipt);err!=nil{return receipt,err};safety,safetyErr:=c.Safety.CreateSafetySnapshot(ctx,plan,previous,watermark,string(plan.ID));if safetyErr!=nil||safety==""{if safetyErr==nil{safetyErr=ErrInvalidBackup};return c.fail(ctx,receipt,safetyErr,RestoreFailed)};receipt.SafetySnapshotID=safety;if err=c.Store.Save(ctx,&receipt);err!=nil{return receipt,err};frozen,freezeErr:=c.Safety.FreezeTargetWrites(ctx,plan,string(plan.ID));if freezeErr!=nil{return c.fail(ctx,receipt,freezeErr,RestoreFailed)};if frozen==0||frozen!=watermark{_ = c.Safety.UnfreezeTargetWrites(context.Background(),plan,previous,string(plan.ID));return c.fail(ctx,receipt,ErrBackupConflict,RestoreFailed)};receipt.RollbackFrontier=frozen;receipt.TargetWriteWatermark=frozen;receipt.Phase=RestoreCutoverReady;if err=c.Store.Save(ctx,&receipt);err!=nil{_ = c.Safety.UnfreezeTargetWrites(context.Background(),plan,previous,string(plan.ID));return receipt,errors.Join(ErrBackupAmbiguous,err)}}
	promoteNow:=false;if receipt.Phase==RestoreCutoverReady{receipt.Phase=RestorePromoting;if err=c.Store.Save(ctx,&receipt);err!=nil{return receipt,err};promoteNow=true};if !promoteNow{return receipt,ErrBackupAmbiguous};targetGeneration,promoteErr:=c.Target.Promote(ctx,plan,receipt.ScratchID,string(plan.ID));if promoteErr!=nil||targetGeneration==""{if promoteErr==nil{promoteErr=ErrInvalidBackup};return c.fail(ctx,receipt,errors.Join(ErrBackupAmbiguous,promoteErr),RestoreAmbiguous)};receipt.TargetGeneration=targetGeneration;if err=c.Store.Save(ctx,&receipt);err!=nil{return receipt,errors.Join(ErrBackupAmbiguous,err)};promotionWatermark,firstWrite,observeErr:=c.Target.ObserveWrites(ctx,plan,targetGeneration);if observeErr!=nil{return c.fail(ctx,receipt,observeErr,RestoreAmbiguous)};receipt.PromotionWatermark=promotionWatermark;receipt.TargetWriteWatermark=promotionWatermark;receipt.FirstWriteAt=firstWrite;if promotionWatermark>receipt.RollbackFrontier||firstWrite!=nil{receipt.Phase=RestoreFailForward;receipt.Error=ErrRestoreWriteFrontier.Error();_ = c.Target.Quarantine(ctx,plan,receipt.ScratchID,string(plan.ID));_ = c.Store.Save(ctx,&receipt);return receipt,ErrRestoreWriteFrontier};health,healthErr:=c.Safety.VerifyPromotedHealth(ctx,plan,targetGeneration,string(plan.ID));if healthErr!=nil||health==""{if healthErr==nil{healthErr=ErrInvalidBackup};rolledBack,rollbackErr:=c.Rollback(ctx,plan,receipt);return rolledBack,errors.Join(healthErr,rollbackErr)};receipt.ProbeDigest=health;if err=c.Safety.UnfreezeTargetWrites(ctx,plan,targetGeneration,string(plan.ID));err!=nil{return c.fail(ctx,receipt,err,RestoreAmbiguous)};newWatermark,firstWrite,observeErr:=c.Target.ObserveWrites(ctx,plan,targetGeneration);if observeErr!=nil{return c.fail(ctx,receipt,observeErr,RestoreAmbiguous)};receipt.TargetWriteWatermark=newWatermark;receipt.FirstWriteAt=firstWrite;receipt.Phase=RestoreActive;receipt.Error="";if err=c.Store.Save(ctx,&receipt);err!=nil{return receipt,errors.Join(ErrBackupAmbiguous,err)};return receipt,nil}
func (c RestoreCoordinator)Rollback(ctx context.Context,plan RestorePlanSpec,receipt RestoreReceipt)(RestoreReceipt,error){if receipt.PlanID!=plan.ID||receipt.TenantID!=plan.TenantID||receipt.PreviousGeneration==""||receipt.TargetGeneration==""||receipt.RollbackFrontier==0{return receipt,ErrInvalidBackup};watermark,firstWrite,err:=c.Target.ObserveWrites(ctx,plan,receipt.TargetGeneration);if err!=nil{return c.fail(ctx,receipt,err,RestoreAmbiguous)};if firstWrite!=nil||watermark>receipt.RollbackFrontier{receipt.Phase=RestoreFailForward;receipt.FirstWriteAt=firstWrite;receipt.TargetWriteWatermark=watermark;receipt.Error=ErrRestoreWriteFrontier.Error();_ = c.Target.Quarantine(ctx,plan,receipt.ScratchID,string(plan.ID));if err=c.Store.Save(ctx,&receipt);err!=nil{return receipt,err};return receipt,ErrRestoreWriteFrontier};receipt.Phase=RestoreRollingBack;if err=c.Store.Save(ctx,&receipt);err!=nil{return receipt,err};if err=c.Target.RestorePrevious(ctx,plan,receipt.PreviousGeneration,string(plan.ID));err!=nil{return c.fail(ctx,receipt,err,RestoreAmbiguous)};if err=c.Safety.UnfreezeTargetWrites(ctx,plan,receipt.PreviousGeneration,string(plan.ID));err!=nil{return c.fail(ctx,receipt,err,RestoreAmbiguous)};receipt.Phase=RestoreRolledBack;receipt.Error="";if err=c.Store.Save(ctx,&receipt);err!=nil{return receipt,err};return receipt,nil}
func (c RestoreCoordinator)abortBeforePromotion(ctx context.Context,plan RestorePlanSpec,receipt RestoreReceipt,cause error)(RestoreReceipt,error){if receipt.Phase==RestoreCutoverReady&&receipt.PreviousGeneration!=""{if err:=c.Safety.UnfreezeTargetWrites(ctx,plan,receipt.PreviousGeneration,string(plan.ID));err!=nil{return c.fail(ctx,receipt,errors.Join(cause,err),RestoreAmbiguous)}};return c.fail(ctx,receipt,cause,RestoreFailed)}
func (c RestoreCoordinator)fail(ctx context.Context,receipt RestoreReceipt,cause error,phase RestorePhase)(RestoreReceipt,error){if cause==nil{cause=ErrInvalidBackup};receipt.Phase=phase;receipt.Error=cause.Error();if err:=c.Store.Save(ctx,&receipt);err!=nil{return receipt,errors.Join(cause,err)};return receipt,cause}
func validateRestorePlan(plan RestorePlanSpec)error{if plan.ID==""||plan.IdempotencyKey==""||plan.TenantID==""||plan.RecoveryPointID==""||!safeRestoreReference(plan.SourceScope)||!safeRestoreReference(plan.TargetScope)||len(plan.ComponentMapping)==0||len(plan.ComponentMapping)>64||plan.RequiredFreeBytes==0||plan.Generation==0||len(plan.IdempotencyKey)>1024{return ErrInvalidBackup};if plan.CollisionPolicy!=CollisionReject&&plan.CollisionPolicy!=CollisionRename&&plan.CollisionPolicy!=CollisionReplaceBlueGreen{return ErrInvalidBackup};if plan.SecretPolicy!=SecretRotate&&plan.SecretPolicy!=SecretPreserveEncrypted&&plan.SecretPolicy!=SecretResetRequired{return ErrInvalidBackup};for component,target:=range plan.ComponentMapping{if !validComponent(component)||!safeRestoreReference(target){return ErrInvalidBackup}};if len(plan.DomainMapping)>10000{return ErrInvalidBackup};for source,target:=range plan.DomainMapping{if !safeRestoreReference(source)||!safeRestoreReference(target){return ErrInvalidBackup}};return nil}
func validateRestoreSource(plan RestorePlanSpec,manifest RecoveryPointManifest,copies []CopyReceipt)error{if manifest.RecoveryPointID!=plan.RecoveryPointID||manifest.TenantID!=plan.TenantID||manifest.Scope!=plan.SourceScope{return ErrInvalidBackup};if err:=ValidateRecoveryPointManifest(manifest);err!=nil{return err};verified:=0;seenCopies:=map[RepositoryID]bool{};for _,copyReceipt:=range copies{if copyReceipt.RecoveryPointID!=manifest.RecoveryPointID||copyReceipt.RepositoryID==""||seenCopies[copyReceipt.RepositoryID]||copyReceipt.ManifestDigest!=manifest.ManifestDigest||copyReceipt.Status!=CopyVerified||copyReceipt.VerifiedAt.IsZero(){return ErrInvalidBackup};seenCopies[copyReceipt.RepositoryID]=true;verified++};if verified==0{return fmt.Errorf("recovery point has no verified copy")};present:=map[ComponentKind]bool{};for _,artifact:=range manifest.Artifacts{if _,required:=plan.ComponentMapping[artifact.Component];required{if present[artifact.Component]{return ErrInvalidBackup};if err:=validateArtifact(artifact,ReadView{Component:artifact.Component,Consistency:artifact.Consistency});err!=nil{return err};present[artifact.Component]=true}};for component:=range plan.ComponentMapping{if !present[component]{return fmt.Errorf("recovery point is missing required component %s",component)}};return nil}
func requiredRestoreBytes(plan RestorePlanSpec,manifest RecoveryPointManifest)(uint64,error){var required uint64;for _,artifact:=range manifest.Artifacts{if _,selected:=plan.ComponentMapping[artifact.Component];!selected{continue};if artifact.Bytes>math.MaxUint64-required{return 0,ErrInvalidBackup};required+=artifact.Bytes};if required==0{return 0,ErrInvalidBackup};return required,nil}
func restorePlanDigest(raw []byte)string{sum:=sha256.Sum256(raw);return hex.EncodeToString(sum[:])}
func safeRestoreReference(value string)bool{if value==""||len(value)>1024||strings.TrimSpace(value)!=value||strings.ContainsRune(value,'\x00'){return false};for _,character:=range value{if character<0x20||character==0x7f{return false}};return true}
