package backup

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"database/sql"
	"encoding/json"
	"errors"
	"sort"
	"time"
)

type RetentionCandidate struct { Manifest RecoveryPointManifest `json:"manifest"`; Copies []CopyReceipt `json:"copies"`; Held bool `json:"held"`; Leased bool `json:"leased"`; Tags []string `json:"tags"` }
type SurvivorProof struct { RecoveryPointID RecoveryPointID `json:"recovery_point_id"`; ManifestDigest string `json:"manifest_digest"`; VerifiedCopies []CopyID `json:"verified_copies"`; Repositories []RepositoryID `json:"repositories"`; FailureDomains []string `json:"failure_domains"`; MinimumCopies uint8 `json:"minimum_copies"`; DistinctDomains bool `json:"distinct_domains"`; ObservedAt time.Time `json:"observed_at"`; Digest string `json:"digest"` }
type PruneDecision struct { RecoveryPointID RecoveryPointID `json:"recovery_point_id"`; Keep bool `json:"keep"`; Reasons []string `json:"reasons"`; Survivors []RepositoryID `json:"survivors"`; DeleteFrom []RepositoryID `json:"delete_from"`; SurvivorProof SurvivorProof `json:"survivor_proof"` }
type RetentionPlan struct { ID string `json:"id"`; PolicyID PolicyID `json:"policy_id"`; PolicyGeneration uint64 `json:"policy_generation"`; EvaluatedAt time.Time `json:"evaluated_at"`; InventoryDigest string `json:"inventory_digest"`; Decisions []PruneDecision `json:"decisions"`; Digest string `json:"digest"` }
type RetentionExecutionState string
const(RetentionExecutionRunning RetentionExecutionState="running";RetentionExecutionComplete RetentionExecutionState="complete";RetentionExecutionAmbiguous RetentionExecutionState="ambiguous")
type RetentionExecution struct{PlanID string `json:"plan_id"`;State RetentionExecutionState `json:"state"`;Completed map[string]time.Time `json:"completed"`;Generation uint64 `json:"generation"`;UpdatedAt time.Time `json:"updated_at"`}
type RetentionCatalog interface { Candidates(context.Context,string,PolicyID)([]RetentionCandidate,error); SaveRetentionPlan(context.Context,RetentionPlan)error; MarkPruned(context.Context,RecoveryPointID,RepositoryID,string)error }
type DurableRetentionCatalog interface{RetentionCatalog;LoadExecution(context.Context,string)(RetentionExecution,error);SaveExecution(context.Context,RetentionExecution,uint64)error}
type RetentionRepositoryCatalog interface{Repository(context.Context,string,RepositoryID)(RepositorySpec,error)}
type RetentionCoordinator struct { Catalog RetentionCatalog; ProviderByRepository map[RepositoryID]RepositoryProvider; Repositories map[RepositoryID]RepositorySpec; ProviderByKind map[ProviderKind]RepositoryProvider; RepositoryCatalog RetentionRepositoryCatalog; Leases BackupCatalog; Now func()time.Time }
func (c RetentionCoordinator)Plan(ctx context.Context,policy BackupPolicySpec)(RetentionPlan,error){if err:=validateBackupPolicy(policy);err!=nil{return RetentionPlan{},err};candidates,err:=c.Catalog.Candidates(ctx,policy.TenantID,policy.ID);if err!=nil{return RetentionPlan{},err};now:=c.now();sort.Slice(candidates,func(i,j int)bool{return candidates[i].Manifest.CreatedAt.After(candidates[j].Manifest.CreatedAt)});inventoryDigest:=retentionInventoryDigest(candidates);keep:=selectGFS(candidates,policy.Retention,now);decisions:=make([]PruneDecision,0,len(candidates));for index,candidate:=range candidates{decision:=PruneDecision{RecoveryPointID:candidate.Manifest.RecoveryPointID};if candidate.Held{decision.Keep=true;decision.Reasons=append(decision.Reasons,"legal_or_operator_hold")};if candidate.Leased{decision.Keep=true;decision.Reasons=append(decision.Reasons,"active_backup_restore_or_verification_lease")};if now.Sub(candidate.Manifest.CreatedAt)<policy.Retention.MinimumAge{decision.Keep=true;decision.Reasons=append(decision.Reasons,"minimum_age")};if keep[index]{decision.Keep=true;decision.Reasons=append(decision.Reasons,"gfs_retention")};verified:=verifiedCopies(candidate.Copies);if len(verified)<int(policy.Retention.MinimumVerifiedCopies){decision.Keep=true;decision.Reasons=append(decision.Reasons,"insufficient_verified_survivors")};for _,copyReceipt:=range verified{decision.Survivors=append(decision.Survivors,copyReceipt.RepositoryID)};decision.SurvivorProof=buildSurvivorProof(candidate,policy.Retention,now);if !decision.Keep{verifiedDelete:=len(verified)-int(policy.Retention.MinimumVerifiedCopies);for _,copyReceipt:=range candidate.Copies{if copyReceipt.Status==CopyCommitted{decision.DeleteFrom=append(decision.DeleteFrom,copyReceipt.RepositoryID)}else if copyReceipt.Status==CopyVerified&&verifiedDelete>0{decision.DeleteFrom=append(decision.DeleteFrom,copyReceipt.RepositoryID);verifiedDelete--}};if len(decision.DeleteFrom)==0{decision.Keep=true;decision.Reasons=append(decision.Reasons,"minimum_survivor_floor")}};decisions=append(decisions,decision)};plan:=RetentionPlan{ID:deriveID("retention",string(policy.ID),now.Format(time.RFC3339Nano)),PolicyID:policy.ID,PolicyGeneration:policy.Generation,EvaluatedAt:now,InventoryDigest:inventoryDigest,Decisions:decisions};raw,_:=json.Marshal(plan);plan.Digest=deriveID("digest",string(raw));if err=c.Catalog.SaveRetentionPlan(ctx,plan);err!=nil{return RetentionPlan{},err};return plan,nil}
func (c RetentionCoordinator)Execute(ctx context.Context,policy BackupPolicySpec,plan RetentionPlan,_ []RetentionCandidate)(RetentionPlan,error){if plan.PolicyID!=policy.ID||plan.PolicyGeneration!=policy.Generation||plan.Digest==""||plan.InventoryDigest==""{return plan,ErrInvalidBackup};rawPlan,_:=json.Marshal(RetentionPlan{ID:plan.ID,PolicyID:plan.PolicyID,PolicyGeneration:plan.PolicyGeneration,EvaluatedAt:plan.EvaluatedAt,InventoryDigest:plan.InventoryDigest,Decisions:plan.Decisions});if deriveID("digest",string(rawPlan))!=plan.Digest{return plan,ErrBackupConflict};leaseResource:="retention:"+string(policy.ID);held,err:=c.Leases.AcquireLease(ctx,leaseResource,plan.ID,2*time.Hour);if err!=nil{return plan,err};if !held{return plan,ErrBackupConflict};defer c.Leases.ReleaseLease(context.Background(),leaseResource,plan.ID);fresh,err:=c.Catalog.Candidates(ctx,policy.TenantID,policy.ID);if err!=nil{return plan,err};sort.Slice(fresh,func(i,j int)bool{return fresh[i].Manifest.CreatedAt.After(fresh[j].Manifest.CreatedAt)});if retentionInventoryDigest(fresh)!=plan.InventoryDigest{return plan,ErrBackupConflict};byID:=map[RecoveryPointID]RetentionCandidate{};for _,candidate:=range fresh{byID[candidate.Manifest.RecoveryPointID]=candidate};for _,decision:=range plan.Decisions{if decision.Keep||len(decision.DeleteFrom)==0{continue};candidate,ok:=byID[decision.RecoveryPointID];if !ok||candidate.Held||candidate.Leased{return plan,ErrBackupConflict};proof:=buildSurvivorProof(candidate,policy.Retention,plan.EvaluatedAt);if proof.Digest!=decision.SurvivorProof.Digest{return plan,ErrBackupConflict};deleteSet:=map[RepositoryID]bool{};for _,repositoryID:=range decision.DeleteFrom{deleteSet[repositoryID]=true};remaining:=[]CopyReceipt{};for _,receipt:=range verifiedCopies(candidate.Copies){if !deleteSet[receipt.RepositoryID]{remaining=append(remaining,receipt)}};if len(remaining)<int(policy.Retention.MinimumVerifiedCopies){return plan,ErrBackupConflict};domains:=map[string]bool{};for _,copyReceipt:=range remaining{domains[copyReceipt.FailureDomain]=true};if policy.Retention.RequireDistinctFailureDomains&&len(domains)<int(policy.Retention.MinimumVerifiedCopies){return plan,ErrBackupConflict};for _,repositoryID:=range decision.DeleteFrom{provider:=c.ProviderByRepository[repositoryID];repository,exists:=c.Repositories[repositoryID];if (!exists||provider==nil)&&c.RepositoryCatalog!=nil{repository,err=c.RepositoryCatalog.Repository(ctx,policy.TenantID,repositoryID);if err!=nil{return plan,err};provider=c.ProviderByKind[repository.Repository.Kind];exists=true};if provider==nil||!exists{return plan,ErrInvalidBackup};if err=provider.DeleteRecoveryPoint(ctx,repository,candidate.Manifest,plan.ID);err!=nil{return plan,err};if err=c.Catalog.MarkPruned(ctx,candidate.Manifest.RecoveryPointID,repositoryID,plan.ID);err!=nil{return plan,ErrBackupAmbiguous}}};return plan,nil}
func (c RetentionCoordinator)ExecuteDurable(ctx context.Context,policy BackupPolicySpec,plan RetentionPlan)(RetentionPlan,error){catalog,ok:=c.Catalog.(DurableRetentionCatalog);if !ok{return plan,ErrInvalidBackup};execution,err:=catalog.LoadExecution(ctx,plan.ID);if err!=nil{return plan,err};if execution.State==RetentionExecutionComplete{return plan,nil};for _,decision:=range plan.Decisions{if decision.Keep||len(decision.DeleteFrom)==0{continue};pending:=[]RepositoryID{};for _,repository:=range decision.DeleteFrom{key:=string(decision.RecoveryPointID)+"/"+string(repository);if _,done:=execution.Completed[key];!done{pending=append(pending,repository)}};if len(pending)==0{continue};single:=plan;single.Decisions=[]PruneDecision{{RecoveryPointID:decision.RecoveryPointID,DeleteFrom:pending,SurvivorProof:decision.SurvivorProof}};raw,_:=json.Marshal(RetentionPlan{ID:single.ID,PolicyID:single.PolicyID,PolicyGeneration:single.PolicyGeneration,EvaluatedAt:single.EvaluatedAt,InventoryDigest:single.InventoryDigest,Decisions:single.Decisions});single.Digest=deriveID("digest",string(raw));if _,err=c.Execute(ctx,policy,single,nil);err!=nil{execution.State=RetentionExecutionAmbiguous;previous:=execution.Generation;execution.Generation++;_ = catalog.SaveExecution(ctx,execution,previous);return plan,err};previous:=execution.Generation;execution.Generation++;for _,repository:=range pending{execution.Completed[string(decision.RecoveryPointID)+"/"+string(repository)]=time.Now().UTC()};if err=catalog.SaveExecution(ctx,execution,previous);err!=nil{return plan,ErrBackupAmbiguous}};execution.State=RetentionExecutionComplete;previous:=execution.Generation;execution.Generation++;if err=catalog.SaveExecution(ctx,execution,previous);err!=nil{return plan,err};return plan,nil}
func selectGFS(candidates []RetentionCandidate,policy RetentionPolicy,now time.Time)map[int]bool{selected:=map[int]bool{};for index:=0;index<len(candidates)&&index<int(policy.KeepLast);index++{selected[index]=true};selectBuckets:=func(limit uint32,key func(time.Time)string){seen:=map[string]bool{};for index,candidate:=range candidates{if uint32(len(seen))>=limit{return};bucket:=key(candidate.Manifest.CreatedAt.UTC());if !seen[bucket]{seen[bucket]=true;selected[index]=true}}};selectBuckets(policy.KeepHourly,func(t time.Time)string{return t.Format("2006-01-02T15")});selectBuckets(policy.KeepDaily,func(t time.Time)string{return t.Format("2006-01-02")});selectBuckets(policy.KeepWeekly,func(t time.Time)string{year,week:=t.ISOWeek();return time.Date(year,1,1,0,0,0,0,time.UTC).AddDate(0,0,week*7).Format("2006-01-02")});selectBuckets(policy.KeepMonthly,func(t time.Time)string{return t.Format("2006-01")});_ = now;return selected}
func verifiedCopies(values []CopyReceipt)[]CopyReceipt{out:=make([]CopyReceipt,0,len(values));for _,value:=range values{if value.Status==CopyVerified&&value.CommitMarker!=""&&value.VerifiedAt.IsZero()==false{out=append(out,value)}};return out}
func buildSurvivorProof(candidate RetentionCandidate,policy RetentionPolicy,observed time.Time)SurvivorProof{proof:=SurvivorProof{RecoveryPointID:candidate.Manifest.RecoveryPointID,ManifestDigest:candidate.Manifest.ManifestDigest,MinimumCopies:policy.MinimumVerifiedCopies,DistinctDomains:policy.RequireDistinctFailureDomains,ObservedAt:observed};domains:=map[string]bool{};for _,receipt:=range verifiedCopies(candidate.Copies){proof.VerifiedCopies=append(proof.VerifiedCopies,receipt.ID);proof.Repositories=append(proof.Repositories,receipt.RepositoryID);domains[receipt.FailureDomain]=true};for domain:=range domains{proof.FailureDomains=append(proof.FailureDomains,domain)};sort.Slice(proof.VerifiedCopies,func(i,j int)bool{return proof.VerifiedCopies[i]<proof.VerifiedCopies[j]});sort.Slice(proof.Repositories,func(i,j int)bool{return proof.Repositories[i]<proof.Repositories[j]});sort.Strings(proof.FailureDomains);raw,_:=json.Marshal(proof);sum:=sha256.Sum256(raw);proof.Digest=hex.EncodeToString(sum[:]);return proof}
func retentionInventoryDigest(candidates []RetentionCandidate)string{type inventoryRow struct{Point RecoveryPointID `json:"point"`;Manifest string `json:"manifest"`;Held bool `json:"held"`;Leased bool `json:"leased"`;Copies []CopyReceipt `json:"copies"`};rows:=make([]inventoryRow,0,len(candidates));for _,candidate:=range candidates{copies:=append([]CopyReceipt(nil),candidate.Copies...);sort.Slice(copies,func(i,j int)bool{return copies[i].ID<copies[j].ID});rows=append(rows,inventoryRow{candidate.Manifest.RecoveryPointID,candidate.Manifest.ManifestDigest,candidate.Held,candidate.Leased,copies})};sort.Slice(rows,func(i,j int)bool{return rows[i].Point<rows[j].Point});raw,_:=json.Marshal(rows);sum:=sha256.Sum256(raw);return hex.EncodeToString(sum[:])}
func (c RetentionCoordinator)now()time.Time{if c.Now!=nil{return c.Now().UTC()};return time.Now().UTC()}

type SQLRetentionCatalog struct{DB *sql.DB}
const retentionSchema=`CREATE TABLE IF NOT EXISTS backup_retention_plans_v2(id TEXT PRIMARY KEY,policy_id TEXT NOT NULL,policy_generation INTEGER NOT NULL,plan_json BLOB NOT NULL,evaluated_at TIMESTAMP NOT NULL);CREATE TABLE IF NOT EXISTS backup_prune_receipts_v2(recovery_point_id TEXT NOT NULL,repository_id TEXT NOT NULL,plan_id TEXT NOT NULL,pruned_at TIMESTAMP NOT NULL,PRIMARY KEY(recovery_point_id,repository_id));CREATE TABLE IF NOT EXISTS backup_retention_executions_v2(plan_id TEXT PRIMARY KEY,state TEXT NOT NULL,generation INTEGER NOT NULL,execution_json BLOB NOT NULL,updated_at TIMESTAMP NOT NULL);`
func (c SQLRetentionCatalog)Bootstrap(ctx context.Context)error{if c.DB==nil{return errors.New("retention database required")};_,err:=c.DB.ExecContext(ctx,retentionSchema);return err}
func (c SQLRetentionCatalog)Candidates(ctx context.Context,tenant string,policy PolicyID)([]RetentionCandidate,error){rows,err:=c.DB.QueryContext(ctx,`SELECT manifest_json FROM recovery_points_v2 WHERE tenant_id=? AND policy_id=? AND state='restorable' ORDER BY created_at DESC`,tenant,policy);if err!=nil{return nil,err};defer rows.Close();out:=[]RetentionCandidate{};for rows.Next(){var raw []byte;if err=rows.Scan(&raw);err!=nil{return nil,err};var manifest RecoveryPointManifest;if err=json.Unmarshal(raw,&manifest);err!=nil{return nil,err};candidate:=RetentionCandidate{Manifest:manifest};copyRows,copyErr:=c.DB.QueryContext(ctx,`SELECT copy_json FROM recovery_copies_v2 WHERE recovery_point_id=?`,manifest.RecoveryPointID);if copyErr!=nil{return nil,copyErr};for copyRows.Next(){var copyRaw []byte;if copyErr=copyRows.Scan(&copyRaw);copyErr!=nil{copyRows.Close();return nil,copyErr};var receipt CopyReceipt;if copyErr=json.Unmarshal(copyRaw,&receipt);copyErr!=nil{copyRows.Close();return nil,copyErr};candidate.Copies=append(candidate.Copies,receipt)};copyRows.Close();var holds,leases int;if err=c.DB.QueryRowContext(ctx,`SELECT COUNT(*) FROM backup_holds_v2 WHERE recovery_point_id=? AND (expires_at IS NULL OR expires_at>?)`,manifest.RecoveryPointID,time.Now().UTC()).Scan(&holds);err!=nil{return nil,err};if err=c.DB.QueryRowContext(ctx,`SELECT COUNT(*) FROM backup_leases_v2 WHERE resource IN (?,?) AND expires_at>?`,`restore:`+string(manifest.RecoveryPointID),`verify:`+string(manifest.RecoveryPointID),time.Now().UTC()).Scan(&leases);err!=nil{return nil,err};candidate.Held=holds>0;candidate.Leased=leases>0;out=append(out,candidate)};return out,rows.Err()}
func (c SQLRetentionCatalog)SaveRetentionPlan(ctx context.Context,plan RetentionPlan)error{raw,err:=json.Marshal(plan);if err!=nil{return err};_,err=c.DB.ExecContext(ctx,`INSERT INTO backup_retention_plans_v2(id,policy_id,policy_generation,plan_json,evaluated_at) VALUES(?,?,?,?,?)`,plan.ID,plan.PolicyID,plan.PolicyGeneration,raw,plan.EvaluatedAt);return err}
func (c SQLRetentionCatalog)RetentionPlan(ctx context.Context,id string)(RetentionPlan,error){var raw []byte;err:=c.DB.QueryRowContext(ctx,`SELECT plan_json FROM backup_retention_plans_v2 WHERE id=?`,id).Scan(&raw);if err!=nil{return RetentionPlan{},err};var plan RetentionPlan;if err=json.Unmarshal(raw,&plan);err!=nil{return RetentionPlan{},err};return plan,nil}
func (c SQLRetentionCatalog)LoadExecution(ctx context.Context,plan string)(RetentionExecution,error){var raw []byte;err:=c.DB.QueryRowContext(ctx,`SELECT execution_json FROM backup_retention_executions_v2 WHERE plan_id=?`,plan).Scan(&raw);if errors.Is(err,sql.ErrNoRows){now:=time.Now().UTC();execution:=RetentionExecution{PlanID:plan,State:RetentionExecutionRunning,Completed:map[string]time.Time{},Generation:1,UpdatedAt:now};raw,_=json.Marshal(execution);_,err=c.DB.ExecContext(ctx,`INSERT INTO backup_retention_executions_v2(plan_id,state,generation,execution_json,updated_at) VALUES(?,?,?,?,?)`,plan,execution.State,execution.Generation,raw,now);return execution,err};if err!=nil{return RetentionExecution{},err};var execution RetentionExecution;if err=json.Unmarshal(raw,&execution);err!=nil{return RetentionExecution{},err};if execution.Completed==nil{execution.Completed=map[string]time.Time{}};return execution,nil}
func (c SQLRetentionCatalog)SaveExecution(ctx context.Context,execution RetentionExecution,expected uint64)error{if execution.Generation!=expected+1{return ErrInvalidBackup};execution.UpdatedAt=time.Now().UTC();raw,err:=json.Marshal(execution);if err!=nil{return err};result,err:=c.DB.ExecContext(ctx,`UPDATE backup_retention_executions_v2 SET state=?,generation=?,execution_json=?,updated_at=? WHERE plan_id=? AND generation=?`,execution.State,execution.Generation,raw,execution.UpdatedAt,execution.PlanID,expected);if err!=nil{return err};affected,err:=result.RowsAffected();if err!=nil{return err};if affected!=1{return ErrBackupConflict};return nil}
func (c SQLRetentionCatalog)MarkPruned(ctx context.Context,point RecoveryPointID,repository RepositoryID,plan string)error{tx,err:=c.DB.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return err};defer tx.Rollback();var raw []byte;if err=tx.QueryRowContext(ctx,`SELECT copy_json FROM recovery_copies_v2 WHERE recovery_point_id=? AND repository_id=?`,point,repository).Scan(&raw);err!=nil{return err};var receipt CopyReceipt;if err=json.Unmarshal(raw,&receipt);err!=nil{return err};if receipt.Status==CopyPruned{return tx.Commit()};receipt.Status=CopyPruned;receipt.Detail="pruned by retention plan "+plan;updated,err:=json.Marshal(receipt);if err!=nil{return err};if _,err=tx.ExecContext(ctx,`INSERT INTO backup_prune_receipts_v2(recovery_point_id,repository_id,plan_id,pruned_at) VALUES(?,?,?,?)`,point,repository,plan,time.Now().UTC());err!=nil{return err};if _,err=tx.ExecContext(ctx,`UPDATE recovery_copies_v2 SET status=?,copy_json=? WHERE recovery_point_id=? AND repository_id=?`,CopyPruned,updated,point,repository);err!=nil{return err};var remaining int;if err=tx.QueryRowContext(ctx,`SELECT COUNT(*) FROM recovery_copies_v2 WHERE recovery_point_id=? AND status IN (?,?)`,point,CopyVerified,CopyCommitted).Scan(&remaining);err!=nil{return err};if remaining==0{if _,err=tx.ExecContext(ctx,`UPDATE recovery_points_v2 SET state='pruned' WHERE id=?`,point);err!=nil{return err}};return tx.Commit()}
