package backup

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
)

type RepositoryRestoreReader interface{OpenCommittedObject(context.Context,RepositorySpec,RecoveryPointManifest,CopyReceipt,ObjectDescriptor)(ReadCloser,error)}
type SQLRestoreSource struct{DB *sql.DB;Readers map[ProviderKind]RepositoryRestoreReader}
func (source SQLRestoreSource)LoadManifest(ctx context.Context,tenant string,point RecoveryPointID)(RecoveryPointManifest,[]CopyReceipt,error){if source.DB==nil||tenant==""||point==""{return RecoveryPointManifest{},nil,ErrInvalidBackup};var raw []byte;var storedDigest string;if err:=source.DB.QueryRowContext(ctx,`SELECT manifest_digest,manifest_json FROM recovery_points_v2 WHERE id=? AND tenant_id=? AND state='restorable'`,point,tenant).Scan(&storedDigest,&raw);err!=nil{return RecoveryPointManifest{},nil,err};var manifest RecoveryPointManifest;if err:=json.Unmarshal(raw,&manifest);err!=nil{return RecoveryPointManifest{},nil,errors.Join(ErrInvalidBackup,err)};if manifest.RecoveryPointID!=point||manifest.TenantID!=tenant||manifest.ManifestDigest!=storedDigest{return RecoveryPointManifest{},nil,ErrInvalidBackup};if err:=ValidateRecoveryPointManifest(manifest);err!=nil{return RecoveryPointManifest{},nil,err};rows,err:=source.DB.QueryContext(ctx,`SELECT c.copy_json FROM recovery_copies_v2 c JOIN backup_repositories_v2 r ON r.id=c.repository_id WHERE c.recovery_point_id=? AND c.status=? AND r.tenant_id=? ORDER BY c.repository_id`,point,CopyVerified,tenant);if err!=nil{return RecoveryPointManifest{},nil,err};defer rows.Close();copies:=[]CopyReceipt{};for rows.Next(){var copyRaw []byte;if err=rows.Scan(&copyRaw);err!=nil{return RecoveryPointManifest{},nil,err};var receipt CopyReceipt;if err=json.Unmarshal(copyRaw,&receipt);err!=nil{return RecoveryPointManifest{},nil,errors.Join(ErrInvalidBackup,err)};if receipt.ID==""||receipt.RecoveryPointID!=point||receipt.RepositoryID==""||receipt.ManifestDigest!=manifest.ManifestDigest||receipt.Status!=CopyVerified||receipt.VerifiedAt.IsZero(){return RecoveryPointManifest{},nil,ErrInvalidBackup};copies=append(copies,receipt)};if err=rows.Err();err!=nil{return RecoveryPointManifest{},nil,err};if len(copies)==0{return RecoveryPointManifest{},nil,ErrBackupConflict};return manifest,copies,nil}
func (source SQLRestoreSource)OpenVerifiedObject(ctx context.Context,tenant string,manifest RecoveryPointManifest,object ObjectDescriptor)(ReadObject,error){if source.DB==nil||tenant==""||manifest.TenantID!=tenant||ValidateRecoveryPointManifest(manifest)!=nil||!manifestContainsObject(manifest,object){return ReadObject{},ErrInvalidBackup};rows,err:=source.DB.QueryContext(ctx,`SELECT c.copy_json,r.repository_json FROM recovery_copies_v2 c JOIN backup_repositories_v2 r ON r.id=c.repository_id WHERE c.recovery_point_id=? AND c.status=? AND r.tenant_id=? ORDER BY c.repository_id`,manifest.RecoveryPointID,CopyVerified,tenant);if err!=nil{return ReadObject{},err};defer rows.Close();var failures []error;for rows.Next(){var copyRaw,repositoryRaw []byte;if err=rows.Scan(&copyRaw,&repositoryRaw);err!=nil{return ReadObject{},err};var receipt CopyReceipt;var repository RepositorySpec;if json.Unmarshal(copyRaw,&receipt)!=nil||json.Unmarshal(repositoryRaw,&repository)!=nil||repository.TenantID!=tenant||receipt.RepositoryID!=repository.Repository.ID||receipt.ManifestDigest!=manifest.ManifestDigest||receipt.Status!=CopyVerified{failures=append(failures,ErrInvalidBackup);continue};reader:=source.Readers[repository.Repository.Kind];if reader==nil{failures=append(failures,ErrInvalidBackup);continue};opened,openErr:=reader.OpenCommittedObject(ctx,repository,manifest,receipt,object);if openErr!=nil{failures=append(failures,openErr);continue};return ReadObject{Descriptor:object,Reader:opened},nil};if err=rows.Err();err!=nil{return ReadObject{},err};if len(failures)==0{return ReadObject{},sql.ErrNoRows};return ReadObject{},errors.Join(failures...)}
func manifestContainsObject(manifest RecoveryPointManifest,object ObjectDescriptor)bool{if ValidateObjectDescriptor(object)!=nil{return false};for _,artifact:=range manifest.Artifacts{for _,candidate:=range artifact.Objects{if candidate.Key==object.Key&&candidate.Digest==object.Digest&&candidate.Size==object.Size&&candidate.Mode==object.Mode{return true}}};return false}
