package dns

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"time"
)

type DNSSECAlgorithm string
const ( DNSSECECDSAP256SHA256 DNSSECAlgorithm="ecdsa-p256-sha256"; DNSSECEd25519 DNSSECAlgorithm="ed25519" )
type DNSSECPhase string
const ( DNSSECDisabled DNSSECPhase="disabled"; DNSSECGenerating DNSSECPhase="generating"; DNSSECPublishing DNSSECPhase="publishing_dnskey"; DNSSECAwaitingDS DNSSECPhase="awaiting_ds"; DNSSECActive DNSSECPhase="active"; DNSSECPrepublishing DNSSECPhase="prepublishing_rollover"; DNSSECAwaitingRolloverDS DNSSECPhase="awaiting_rollover_ds"; DNSSECRetiring DNSSECPhase="retiring_old_key"; DNSSECDisabling DNSSECPhase="disabling"; DNSSECFailed DNSSECPhase="failed" )
type DNSSECPolicy struct { Algorithm DNSSECAlgorithm `json:"algorithm"`; SplitKeys bool `json:"split_keys"`; KSKBits uint16 `json:"ksk_bits"`; ZSKBits uint16 `json:"zsk_bits"`; SignatureValidity time.Duration `json:"signature_validity"`; RolloverAfter time.Duration `json:"rollover_after"`; PrepublishFor time.Duration `json:"prepublish_for"` }
type DNSSECKeyDescriptor struct { ID string `json:"id"`; Role string `json:"role"`; Algorithm DNSSECAlgorithm `json:"algorithm"`; KeyTag uint16 `json:"key_tag"`; PublicDNSKEY string `json:"public_dnskey"`; PrivateHandle string `json:"private_handle"`; CreatedAt time.Time `json:"created_at"`; RetireAfter *time.Time `json:"retire_after,omitempty"` }
type DSRecord struct { KeyTag uint16 `json:"key_tag"`; Algorithm uint8 `json:"algorithm"`; DigestType uint8 `json:"digest_type"`; Digest string `json:"digest"` }
type DNSSECStatus struct { ZoneID ZoneID `json:"zone_id"`; TenantID string `json:"tenant_id"`; Generation uint64 `json:"generation"`; Phase DNSSECPhase `json:"phase"`; Policy DNSSECPolicy `json:"policy"`; CurrentKeys []DNSSECKeyDescriptor `json:"current_keys"`; PendingKeys []DNSSECKeyDescriptor `json:"pending_keys,omitempty"`; DS []DSRecord `json:"ds"`; PreviousDS []DSRecord `json:"previous_ds,omitempty"`; DNSKEYPublishedAt *time.Time `json:"dnskey_published_at,omitempty"`; DSObservedAt *time.Time `json:"ds_observed_at,omitempty"`; LastProof DNSSECProof `json:"last_proof"`; Failure string `json:"failure,omitempty"`; UpdatedAt time.Time `json:"updated_at"` }
type DNSSECProof struct { Authoritative bool `json:"authoritative"`; RecursiveValidated bool `json:"recursive_validated"`; DNSKEYDigest string `json:"dnskey_digest"`; DSDigest string `json:"ds_digest"`; ObservedAt time.Time `json:"observed_at"`; ResolverSet []string `json:"resolver_set"` }
type KeyActivationReceipt struct { EffectID string `json:"effect_id"`; Keys []DNSSECKeyDescriptor `json:"keys"`; DS []DSRecord `json:"ds"`; DNSKEYDigest string `json:"dnskey_digest"`; AppliedAt time.Time `json:"applied_at"` }
type DNSSECExecutor interface { GenerateAndPublish(context.Context,ZoneSpec,DNSSECPolicy,string)(KeyActivationReceipt,error); Retire(context.Context,ZoneSpec,[]DNSSECKeyDescriptor,string)error; Remove(context.Context,ZoneSpec,string)error }
type DNSSECObserver interface { Prove(context.Context,ZoneSpec,[]DNSSECKeyDescriptor,[]DSRecord)(DNSSECProof,error) }
type DSPublisher interface { PublishDS(context.Context,ZoneSpec,[]DSRecord,string)error; RemoveDS(context.Context,ZoneSpec,string)error }
type DNSSECRepository struct { DB *sql.DB }
const dnssecSchema=`CREATE TABLE IF NOT EXISTS dnssec_status_v2(zone_id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,generation INTEGER NOT NULL,phase TEXT NOT NULL,status_json BLOB NOT NULL,updated_at TIMESTAMP NOT NULL);`
func (r DNSSECRepository)Bootstrap(ctx context.Context)error{if r.DB==nil{return errors.New("dnssec database required")};_,err:=r.DB.ExecContext(ctx,dnssecSchema);return err}
func (r DNSSECRepository)Load(ctx context.Context,tenant string,zone ZoneID)(DNSSECStatus,bool,error){if r.DB==nil{return DNSSECStatus{},false,errors.New("dnssec database required")};var raw []byte;err:=r.DB.QueryRowContext(ctx,`SELECT status_json FROM dnssec_status_v2 WHERE zone_id=? AND tenant_id=?`,zone,tenant).Scan(&raw);if errors.Is(err,sql.ErrNoRows){return DNSSECStatus{},false,nil};if err!=nil{return DNSSECStatus{},false,err};var status DNSSECStatus;if err=json.Unmarshal(raw,&status);err!=nil{return DNSSECStatus{},false,err};return status,true,nil}
func (r DNSSECRepository)Save(ctx context.Context,status DNSSECStatus,expected uint64)error{if r.DB==nil{return errors.New("dnssec database required")};if status.ZoneID==""||status.TenantID==""||status.Generation!=expected+1||!validDNSSECPhase(status.Phase){return ErrInvalidDNS};raw,err:=json.Marshal(status);if err!=nil{return err};tx,err:=r.DB.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return err};defer tx.Rollback();if expected==0{_,err=tx.ExecContext(ctx,`INSERT INTO dnssec_status_v2(zone_id,tenant_id,generation,phase,status_json,updated_at) VALUES(?,?,?,?,?,?)`,status.ZoneID,status.TenantID,status.Generation,status.Phase,raw,status.UpdatedAt)}else{result,execErr:=tx.ExecContext(ctx,`UPDATE dnssec_status_v2 SET generation=?,phase=?,status_json=?,updated_at=? WHERE zone_id=? AND tenant_id=? AND generation=?`,status.Generation,status.Phase,raw,status.UpdatedAt,status.ZoneID,status.TenantID,expected);if execErr!=nil{return execErr};affected,rowsErr:=result.RowsAffected();if rowsErr!=nil{return rowsErr};if affected!=1{return ErrDNSConflict}};if err!=nil{return err};return tx.Commit()}

type DNSSECCoordinator struct { Store DNSSECRepository; Executor DNSSECExecutor; Observer DNSSECObserver; DSPublisher DSPublisher; Now func()time.Time }
func (c DNSSECCoordinator)Enable(ctx context.Context,zone ZoneSpec,policy DNSSECPolicy,effectID string)(DNSSECStatus,error){if err:=validateDNSSECPolicy(policy);err!=nil{return DNSSECStatus{},err};status,exists,err:=c.Store.Load(ctx,zone.TenantID,zone.ID);if err!=nil{return DNSSECStatus{},err};if exists&&status.Phase!=DNSSECDisabled&&status.Phase!=DNSSECFailed{return status,nil};expected:=uint64(0);if exists{expected=status.Generation};status=DNSSECStatus{ZoneID:zone.ID,TenantID:zone.TenantID,Generation:expected+1,Phase:DNSSECGenerating,Policy:policy,UpdatedAt:c.now()};if err=c.Store.Save(ctx,status,expected);err!=nil{return DNSSECStatus{},err};receipt,err:=c.Executor.GenerateAndPublish(ctx,zone,policy,effectID);if err!=nil{return c.fail(ctx,status,err)};if !validKeyReceipt(receipt,effectID){return c.fail(ctx,status,ErrInvalidDNS)};published:=receipt.AppliedAt.UTC();status.Phase=DNSSECAwaitingDS;status.CurrentKeys=receipt.Keys;status.DS=receipt.DS;status.DNSKEYPublishedAt=&published;status.UpdatedAt=c.now();if c.DSPublisher!=nil{if err=c.DSPublisher.PublishDS(ctx,zone,status.DS,effectID);err!=nil{return c.fail(ctx,status,err)}};expected=status.Generation;status.Generation++;if err=c.Store.Save(ctx,status,expected);err!=nil{return DNSSECStatus{},err};return status,nil}
func (c DNSSECCoordinator)Confirm(ctx context.Context,zone ZoneSpec,expected uint64)(DNSSECStatus,error){status,found,err:=c.Store.Load(ctx,zone.TenantID,zone.ID);if err!=nil{return DNSSECStatus{},err};if !found{return DNSSECStatus{},sql.ErrNoRows};if status.Generation!=expected||(status.Phase!=DNSSECAwaitingDS&&status.Phase!=DNSSECAwaitingRolloverDS){return DNSSECStatus{},ErrInvalidDNS};proof,err:=c.Observer.Prove(ctx,zone,append(status.CurrentKeys,status.PendingKeys...),status.DS);if err!=nil{return status,err};status.LastProof=proof;status.Generation++;status.UpdatedAt=c.now();if !proof.Authoritative||!proof.RecursiveValidated{status.Phase=DNSSECFailed;status.Failure="DNSSEC chain could not be validated"}else{observed:=proof.ObservedAt.UTC();status.DSObservedAt=&observed;if status.Phase==DNSSECAwaitingRolloverDS{status.Phase=DNSSECRetiring}else{status.Phase=DNSSECActive};status.Failure=""};if err=c.Store.Save(ctx,status,expected);err!=nil{return DNSSECStatus{},err};return status,nil}
func (c DNSSECCoordinator)StartRollover(ctx context.Context,zone ZoneSpec,expected uint64,effectID string)(DNSSECStatus,error){status,found,err:=c.Store.Load(ctx,zone.TenantID,zone.ID);if err!=nil{return DNSSECStatus{},err};if !found||status.Generation!=expected||status.Phase!=DNSSECActive{return DNSSECStatus{},ErrInvalidDNS};receipt,err:=c.Executor.GenerateAndPublish(ctx,zone,status.Policy,effectID);if err!=nil{return c.fail(ctx,status,err)};if !validKeyReceipt(receipt,effectID){return c.fail(ctx,status,ErrInvalidDNS)};status.PreviousDS=append([]DSRecord(nil),status.DS...);status.DS=receipt.DS;status.PendingKeys=receipt.Keys;status.Phase=DNSSECAwaitingRolloverDS;status.UpdatedAt=c.now();if c.DSPublisher!=nil{if err=c.DSPublisher.PublishDS(ctx,zone,status.DS,effectID);err!=nil{return c.fail(ctx,status,err)}};status.Generation++;if err=c.Store.Save(ctx,status,expected);err!=nil{return DNSSECStatus{},err};return status,nil}
func (c DNSSECCoordinator)FinishRollover(ctx context.Context,zone ZoneSpec,expected uint64,effectID string)(DNSSECStatus,error){status,found,err:=c.Store.Load(ctx,zone.TenantID,zone.ID);if err!=nil{return DNSSECStatus{},err};if !found||status.Generation!=expected||status.Phase!=DNSSECRetiring||len(status.PendingKeys)==0{return DNSSECStatus{},ErrInvalidDNS};if err=c.Executor.Retire(ctx,zone,status.CurrentKeys,effectID);err!=nil{return c.fail(ctx,status,err)};status.CurrentKeys=status.PendingKeys;status.PendingKeys=nil;status.PreviousDS=nil;status.Phase=DNSSECActive;status.Generation++;status.UpdatedAt=c.now();if err=c.Store.Save(ctx,status,expected);err!=nil{return DNSSECStatus{},err};return status,nil}
func (c DNSSECCoordinator)Disable(ctx context.Context,zone ZoneSpec,expected uint64,effectID string)(DNSSECStatus,error){status,found,err:=c.Store.Load(ctx,zone.TenantID,zone.ID);if err!=nil{return DNSSECStatus{},err};if !found||status.Generation!=expected{return DNSSECStatus{},ErrInvalidDNS};if c.DSPublisher!=nil{if err=c.DSPublisher.RemoveDS(ctx,zone,effectID);err!=nil{return c.fail(ctx,status,err)}};if err=c.Executor.Remove(ctx,zone,effectID);err!=nil{return c.fail(ctx,status,err)};status.Generation++;status.Phase=DNSSECDisabled;status.CurrentKeys=nil;status.PendingKeys=nil;status.DS=nil;status.PreviousDS=nil;status.UpdatedAt=c.now();status.Failure="";if err=c.Store.Save(ctx,status,expected);err!=nil{return DNSSECStatus{},err};return status,nil}
func (c DNSSECCoordinator)fail(ctx context.Context,status DNSSECStatus,cause error)(DNSSECStatus,error){expected:=status.Generation;status.Generation++;status.Phase=DNSSECFailed;status.Failure=cause.Error();status.UpdatedAt=c.now();if err:=c.Store.Save(ctx,status,expected);err!=nil{return DNSSECStatus{},errors.Join(cause,err)};return status,cause}
func (c DNSSECCoordinator)now()time.Time{if c.Now!=nil{return c.Now().UTC()};return time.Now().UTC()}
func validateDNSSECPolicy(policy DNSSECPolicy)error{if policy.Algorithm!=DNSSECECDSAP256SHA256&&policy.Algorithm!=DNSSECEd25519{return ErrInvalidDNS};if policy.SignatureValidity<24*time.Hour||policy.SignatureValidity>90*24*time.Hour||policy.RolloverAfter<7*24*time.Hour||policy.PrepublishFor<time.Hour||policy.PrepublishFor>=policy.RolloverAfter{return ErrInvalidDNS};return nil}
func validKeyReceipt(receipt KeyActivationReceipt,effectID string)bool{if receipt.EffectID!=effectID||receipt.AppliedAt.IsZero()||len(receipt.Keys)==0||len(receipt.DS)==0||receipt.DNSKEYDigest==""{return false};for _,key:=range receipt.Keys{if key.ID==""||key.KeyTag==0||key.PublicDNSKEY==""||key.PrivateHandle==""||key.CreatedAt.IsZero()||(key.Role!="ksk"&&key.Role!="zsk"&&key.Role!="csk"){return false}};return true}
func validDNSSECPhase(phase DNSSECPhase)bool{switch phase{case DNSSECDisabled,DNSSECGenerating,DNSSECPublishing,DNSSECAwaitingDS,DNSSECActive,DNSSECPrepublishing,DNSSECAwaitingRolloverDS,DNSSECRetiring,DNSSECDisabling,DNSSECFailed:return true};return false}
