package dns

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/netip"
	"sort"
	"strconv"
	"strings"
	"time"
)

type ZoneMode string
const ( ZoneNative ZoneMode="native"; ZonePrimary ZoneMode="primary"; ZoneSecondary ZoneMode="secondary" )
type SOAConfig struct { Primary DNSName `json:"primary"`; Hostmaster DNSName `json:"hostmaster"`; Refresh uint32 `json:"refresh"`; Retry uint32 `json:"retry"`; Expire uint32 `json:"expire"`; Minimum uint32 `json:"minimum"`; DefaultTTL uint32 `json:"default_ttl"` }
type ZoneSpec struct { ID ZoneID `json:"id"`; TenantID string `json:"tenant_id"`; Name DNSName `json:"name"`; Mode ZoneMode `json:"mode"`; SOA SOAConfig `json:"soa"`; PrimaryAddresses []netip.Addr `json:"primary_addresses,omitempty"`; Account string `json:"account"`; Generation uint64 `json:"generation"` }
type TSIGAlgorithm string
const ( TSIGHMACSHA256 TSIGAlgorithm="hmac-sha256"; TSIGHMACSHA512 TSIGAlgorithm="hmac-sha512" )
type TransferPeerSpec struct { ID PeerID `json:"id"`; ZoneID ZoneID `json:"zone_id"`; Address netip.Addr `json:"address"`; Direction string `json:"direction"`; TSIGName string `json:"tsig_name"`; TSIGAlgorithm TSIGAlgorithm `json:"tsig_algorithm"`; TSIGSecretRef string `json:"tsig_secret_ref"`; Notify bool `json:"notify"` }
type AuthorityReceipt struct { EffectID string `json:"effect_id"`; ZoneID ZoneID `json:"zone_id"`; Serial uint64 `json:"serial"`; AppliedSets uint32 `json:"applied_sets"`; RemovedSets uint32 `json:"removed_sets"`; ObservedAt time.Time `json:"observed_at"` }

type PowerDNSAuthority struct { DB *sql.DB }
const cyberPanelZoneIDMetadata="CYBERPANEL-ZONE-ID"
const cyberPanelTenantMetadata="CYBERPANEL-TENANT-ID"
const cyberPanelGenerationMetadata="CYBERPANEL-GENERATION"
func (p PowerDNSAuthority)ApplyZone(ctx context.Context,effectID string,spec ZoneSpec,sets []RecordSet,peers []TransferPeerSpec)(AuthorityReceipt,error){if p.DB==nil{return AuthorityReceipt{},errors.New("PowerDNS database required")};if err:=validateZoneSpec(spec,sets,peers);err!=nil{return AuthorityReceipt{},err};tx,err:=p.DB.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return AuthorityReceipt{},err};defer tx.Rollback();var existingID int64;lookupErr:=tx.QueryRowContext(ctx,`SELECT id FROM domains WHERE name=?`,spec.Name.String()).Scan(&existingID);if lookupErr==nil{current,loadErr:=powerDNSZoneByDomain(ctx,tx,existingID);if loadErr!=nil||current.ID!=spec.ID||current.TenantID!=spec.TenantID||current.Name.String()!=spec.Name.String()||current.Generation+1!=spec.Generation{return AuthorityReceipt{},ErrDNSConflict}}else if !errors.Is(lookupErr,sql.ErrNoRows){return AuthorityReceipt{},lookupErr}else if spec.Generation!=1{return AuthorityReceipt{},ErrDNSConflict};var otherName string;duplicateErr:=tx.QueryRowContext(ctx,`SELECT d.name FROM domains d JOIN domainmetadata m ON m.domain_id=d.id AND m.kind=? WHERE m.content=? LIMIT 1`,cyberPanelZoneIDMetadata,spec.ID).Scan(&otherName);if duplicateErr==nil&&otherName!=spec.Name.String(){return AuthorityReceipt{},ErrDNSConflict};if duplicateErr!=nil&&!errors.Is(duplicateErr,sql.ErrNoRows){return AuthorityReceipt{},duplicateErr};domainID,err:=ensurePowerDNSDomain(ctx,tx,spec);if err!=nil{return AuthorityReceipt{},err};serial,err:=nextSerial(ctx,tx,domainID,spec);if err!=nil{return AuthorityReceipt{},err};if _,err=tx.ExecContext(ctx,`DELETE FROM records WHERE domain_id=?`,domainID);err!=nil{return AuthorityReceipt{},err};soa:=fmt.Sprintf("%s %s %d %d %d %d %d",spec.SOA.Primary.FQDN(),spec.SOA.Hostmaster.FQDN(),serial,spec.SOA.Refresh,spec.SOA.Retry,spec.SOA.Expire,spec.SOA.Minimum);if _,err=tx.ExecContext(ctx,`INSERT INTO records(domain_id,name,type,content,ttl,prio,disabled,auth) VALUES(?,?,?,?,?,?,?,?)`,domainID,spec.Name.String(),"SOA",soa,spec.SOA.DefaultTTL,0,false,true);err!=nil{return AuthorityReceipt{},err};for _,set:=range sets{canonical,_:=set.Canonical(spec.Name);owner:=absoluteOwner(canonical.Owner,spec.Name);for _,record:=range canonical.Records{content,priority:=powerDNSContent(canonical.Kind,record);if _,err=tx.ExecContext(ctx,`INSERT INTO records(domain_id,name,type,content,ttl,prio,disabled,auth) VALUES(?,?,?,?,?,?,?,?)`,domainID,owner,canonical.Kind,content,canonical.TTL,priority,false,true);err!=nil{return AuthorityReceipt{},err}}};if err=applyPowerDNSMetadata(ctx,tx,domainID,spec,peers);err!=nil{return AuthorityReceipt{},err};if err=tx.Commit();err!=nil{return AuthorityReceipt{},err};return AuthorityReceipt{EffectID:effectID,ZoneID:spec.ID,Serial:serial,AppliedSets:uint32(len(sets)+1),ObservedAt:time.Now().UTC()},nil}
func (p PowerDNSAuthority)DeleteZone(ctx context.Context,effectID string,spec ZoneSpec)(AuthorityReceipt,error){if p.DB==nil{return AuthorityReceipt{},errors.New("PowerDNS database required")};tx,err:=p.DB.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return AuthorityReceipt{},err};defer tx.Rollback();id,err:=exactPowerDNSDomainID(ctx,tx,spec.TenantID,spec.ID);if err!=nil{return AuthorityReceipt{},err};stored,err:=powerDNSZoneByDomain(ctx,tx,id);if err!=nil{return AuthorityReceipt{},err};if stored.ID!=spec.ID||stored.TenantID!=spec.TenantID||stored.Generation!=spec.Generation||spec.Name.String()!=""&&stored.Name.String()!=spec.Name.String(){return AuthorityReceipt{},ErrDNSConflict};for _,statement:=range []string{`DELETE FROM records WHERE domain_id=?`,`DELETE FROM domainmetadata WHERE domain_id=?`,`DELETE FROM cryptokeys WHERE domain_id=?`,`DELETE FROM comments WHERE domain_id=?`,`DELETE FROM domains WHERE id=?`}{if _,err=tx.ExecContext(ctx,statement,id);err!=nil{return AuthorityReceipt{},err}};if err=tx.Commit();err!=nil{return AuthorityReceipt{},err};return AuthorityReceipt{EffectID:effectID,ZoneID:spec.ID,ObservedAt:time.Now().UTC()},nil}
func (p PowerDNSAuthority)Zone(ctx context.Context,tenant string,id ZoneID)(ZoneSpec,error){if p.DB==nil{return ZoneSpec{},errors.New("PowerDNS database required")};if !validZoneTenant(tenant)||id==""{return ZoneSpec{},ErrInvalidDNS};domainID,err:=exactPowerDNSDomainID(ctx,p.DB,tenant,id);if err!=nil{return ZoneSpec{},err};spec,_,err:=powerDNSZoneObservationByDomain(ctx,p.DB,domainID);if err!=nil{return ZoneSpec{},err};if spec.ID!=id||spec.TenantID!=tenant{return ZoneSpec{},ErrDNSConflict};return spec,nil}
func (p PowerDNSAuthority)ObserveZone(ctx context.Context,tenant string,id ZoneID,effect string)(ZoneSpec,AuthorityReceipt,error){if p.DB==nil{return ZoneSpec{},AuthorityReceipt{},errors.New("PowerDNS database required")};if !validZoneTenant(tenant)||id==""||!validPowerDNSEffectID(effect){return ZoneSpec{},AuthorityReceipt{},ErrInvalidDNS};domainID,err:=exactPowerDNSDomainID(ctx,p.DB,tenant,id);if err!=nil{return ZoneSpec{},AuthorityReceipt{},err};spec,serial,err:=powerDNSZoneObservationByDomain(ctx,p.DB,domainID);if err!=nil{return ZoneSpec{},AuthorityReceipt{},err};if spec.ID!=id||spec.TenantID!=tenant{return ZoneSpec{},AuthorityReceipt{},ErrDNSConflict};return spec,AuthorityReceipt{EffectID:effect,ZoneID:id,Serial:serial,ObservedAt:time.Now().UTC()},nil}
func (p PowerDNSAuthority)ConfirmZoneAbsent(ctx context.Context,id ZoneID,name DNSName)error{if p.DB==nil{return errors.New("PowerDNS database required")};if id==""||name.String()==""||name.String()=="@"{return ErrInvalidDNS};var count uint64;err:=p.DB.QueryRowContext(ctx,`SELECT COUNT(DISTINCT d.id) FROM domains d LEFT JOIN domainmetadata z ON z.domain_id=d.id AND z.kind=? WHERE lower(d.name)=? OR lower(d.name)=? OR z.content=?`,cyberPanelZoneIDMetadata,name.String(),name.FQDN(),id).Scan(&count);if err!=nil{return err};if count!=0{return ErrDNSConflict};return nil}
func (p PowerDNSAuthority)ListZones(ctx context.Context,tenant string,limit int,after string)([]ZoneSpec,string,error){if p.DB==nil{return nil,"",errors.New("PowerDNS database required")};if !validZoneTenant(tenant){return nil,"",ErrInvalidDNS};if limit<1||limit>500{limit=100};rows,err:=p.DB.QueryContext(ctx,`SELECT DISTINCT d.id,d.name FROM domains d JOIN domainmetadata t ON t.domain_id=d.id AND t.kind=? AND t.content=? WHERE d.name>? ORDER BY d.name,d.id LIMIT ?`,cyberPanelTenantMetadata,tenant,after,limit+1);if err!=nil{return nil,"",err};type candidate struct{id int64;name string};candidates:=make([]candidate,0,limit+1);for rows.Next(){var value candidate;if err=rows.Scan(&value.id,&value.name);err!=nil{rows.Close();return nil,"",err};candidates=append(candidates,value)};if err=rows.Err();err!=nil{rows.Close();return nil,"",err};if err=rows.Close();err!=nil{return nil,"",err};items:=make([]ZoneSpec,0,len(candidates));for _,value:=range candidates{spec,_,loadErr:=powerDNSZoneObservationByDomain(ctx,p.DB,value.id);if loadErr==nil{var exactID int64;exactID,loadErr=exactPowerDNSDomainID(ctx,p.DB,tenant,spec.ID);if loadErr==nil&&exactID!=value.id{loadErr=ErrDNSConflict}};if loadErr!=nil||spec.TenantID!=tenant||spec.Name.String()!=value.name{return nil,"",errors.Join(ErrDNSConflict,loadErr)};items=append(items,spec)};next:="";if len(items)>limit{next=items[limit-1].Name.String();items=items[:limit]};return items,next,nil}
func (p PowerDNSAuthority)ListRecordSets(ctx context.Context,spec ZoneSpec,limit int,after string)([]RecordSet,string,error){if p.DB==nil{return nil,"",errors.New("PowerDNS database required")};if limit<1||limit>1000{limit=200};domainID,err:=exactPowerDNSDomainID(ctx,p.DB,spec.TenantID,spec.ID);if err!=nil{return nil,"",err};stored,_,err:=powerDNSZoneObservationByDomain(ctx,p.DB,domainID);if err!=nil{return nil,"",err};if !sameZoneSpec(stored,spec){return nil,"",ErrDNSConflict};afterName:="";afterType:="";if after!=""{parts:=strings.Split(after,"|");if len(parts)!=2{return nil,"",ErrInvalidDNS};afterName,afterType=parts[0],parts[1]};rows,err:=p.DB.QueryContext(ctx,`SELECT name,type,ttl,content,prio FROM records WHERE domain_id=? AND type<>'SOA' AND (name>? OR (name=? AND type>?)) ORDER BY name,type,id LIMIT ?`,domainID,afterName,afterName,afterType,limit*1000+1);if err!=nil{return nil,"",err};defer rows.Close();byKey:=map[string]*RecordSet{};order:=[]string{};for rows.Next(){var owner,kind,content string;var ttl uint32;var priority uint16;if err=rows.Scan(&owner,&kind,&ttl,&content,&priority);err!=nil{return nil,"",err};key:=owner+"|"+kind;set:=byKey[key];if set==nil{parsed,parseErr:=ParseName(owner);if owner==spec.Name.String(){parsed,parseErr=ParseName("@")} ;if parseErr!=nil{return nil,"",ErrInvalidDNS};set=&RecordSet{ZoneID:spec.ID,Owner:parsed,Kind:RRKind(kind),TTL:ttl};byKey[key]=set;order=append(order,key)};if RRKind(kind)==RR_MX{content=fmt.Sprintf("%d %s",priority,content)};set.Records=append(set.Records,content)};if err=rows.Err();err!=nil{return nil,"",err};sort.Strings(order);next:="";if len(order)>limit{next=order[limit-1];order=order[:limit]};result:=make([]RecordSet,0,len(order));for _,key:=range order{set:=*byKey[key];if set.Validate(spec.Name)!=nil{return nil,"",ErrInvalidDNS};result=append(result,set)};return result,next,nil}
func validateZoneSpec(spec ZoneSpec,sets []RecordSet,peers []TransferPeerSpec)error{if spec.ID==""||spec.TenantID==""||spec.Name.String()==""||spec.Generation==0||spec.Account==""||len(sets)>100000||len(peers)>1000{return ErrInvalidDNS};if spec.Mode!=ZoneNative&&spec.Mode!=ZonePrimary&&spec.Mode!=ZoneSecondary{return ErrInvalidDNS};if spec.SOA.Primary.String()==""||spec.SOA.Hostmaster.String()==""||spec.SOA.Refresh<300||spec.SOA.Retry<60||spec.SOA.Expire<86400||spec.SOA.Minimum<30||spec.SOA.DefaultTTL<30{return ErrInvalidDNS};if spec.Mode==ZoneSecondary&&len(spec.PrimaryAddresses)==0{return ErrInvalidDNS};for _,address:=range spec.PrimaryAddresses{if !address.IsValid()||address.IsUnspecified()||address.IsMulticast(){return ErrInvalidDNS}};keys:=map[string]struct{}{};for _,set:=range sets{if err:=set.Validate(spec.Name);err!=nil{return err};key:=set.Owner.String()+"|"+string(set.Kind);if _,ok:=keys[key];ok{return ErrInvalidDNS};keys[key]=struct{}{}};for _,peer:=range peers{if peer.ID==""||peer.ZoneID!=spec.ID||!peer.Address.IsValid()||(peer.Direction!="allow-transfer"&&peer.Direction!="also-notify")||peer.TSIGName==""||peer.TSIGSecretRef==""||(peer.TSIGAlgorithm!=TSIGHMACSHA256&&peer.TSIGAlgorithm!=TSIGHMACSHA512){return ErrInvalidDNS}};return nil}
func ensurePowerDNSDomain(ctx context.Context,tx *sql.Tx,spec ZoneSpec)(int64,error){pdnsType:="NATIVE";masters:="";switch spec.Mode{case ZonePrimary:pdnsType="MASTER";case ZoneSecondary:pdnsType="SLAVE";values:=make([]string,len(spec.PrimaryAddresses));for index,address:=range spec.PrimaryAddresses{values[index]=address.String()};masters=strings.Join(values,",")};var id int64;err:=tx.QueryRowContext(ctx,`SELECT id FROM domains WHERE name=?`,spec.Name.String()).Scan(&id);if errors.Is(err,sql.ErrNoRows){result,insertErr:=tx.ExecContext(ctx,`INSERT INTO domains(name,master,last_check,type,notified_serial,account) VALUES(?,?,?,?,?,?)`,spec.Name.String(),masters,nil,pdnsType,nil,spec.Account);if insertErr!=nil{return 0,insertErr};return result.LastInsertId()};if err!=nil{return 0,err};_,err=tx.ExecContext(ctx,`UPDATE domains SET master=?,type=?,account=? WHERE id=?`,masters,pdnsType,spec.Account,id);return id,err}
func nextSerial(ctx context.Context,tx *sql.Tx,domainID int64,spec ZoneSpec)(uint64,error){var soa string;err:=tx.QueryRowContext(ctx,`SELECT content FROM records WHERE domain_id=? AND type='SOA' LIMIT 1`,domainID).Scan(&soa);current:=uint64(0);if err==nil{parts:=strings.Fields(soa);if len(parts)>=3{current,_=strconv.ParseUint(parts[2],10,64)}}else if !errors.Is(err,sql.ErrNoRows){return 0,err};today:=uint64(time.Now().UTC().Year()*1000000+int(time.Now().UTC().Month())*10000+time.Now().UTC().Day()*100);if current>=today{return current+1,nil};return today+1,nil}
const powerDNSZoneSelect=`SELECT d.name,d.type,COALESCE(d.master,''),COALESCE(d.account,''),z.content,t.content,g.content,r.content,r.ttl FROM domains d JOIN domainmetadata z ON z.domain_id=d.id AND z.kind=? JOIN domainmetadata t ON t.domain_id=d.id AND t.kind=? JOIN domainmetadata g ON g.domain_id=d.id AND g.kind=? JOIN records r ON r.domain_id=d.id AND r.type='SOA'`
type powerDNSScanner interface{Scan(...any)error}
func scanPowerDNSZone(scanner powerDNSScanner)(ZoneSpec,error){var nameText,typeText,masters,account,idText,tenant,generationText,soaText string;var ttl uint32;if err:=scanner.Scan(&nameText,&typeText,&masters,&account,&idText,&tenant,&generationText,&soaText,&ttl);err!=nil{return ZoneSpec{},err};return decodePowerDNSZone(nameText,typeText,masters,account,idText,tenant,generationText,soaText,ttl)}
type powerDNSQuerier interface{QueryContext(context.Context,string,...any)(*sql.Rows,error);QueryRowContext(context.Context,string,...any)*sql.Row}
func decodePowerDNSZone(nameText,typeText,masters,account,idText,tenant,generationText,soaText string,ttl uint32)(ZoneSpec,error){name,err:=ParseName(nameText);if err!=nil{return ZoneSpec{},ErrInvalidDNS};fields:=strings.Fields(soaText);if len(fields)!=7{return ZoneSpec{},ErrInvalidDNS};primary,err:=ParseName(fields[0]);if err!=nil{return ZoneSpec{},ErrInvalidDNS};hostmaster,err:=ParseName(fields[1]);if err!=nil{return ZoneSpec{},ErrInvalidDNS};numbers:=make([]uint64,5);for index:=range numbers{numbers[index],err=strconv.ParseUint(fields[index+2],10,32);if err!=nil{return ZoneSpec{},ErrInvalidDNS}};generation,err:=strconv.ParseUint(generationText,10,64);if err!=nil{return ZoneSpec{},ErrInvalidDNS};mode:=ZoneNative;switch strings.ToUpper(typeText){case"NATIVE":mode=ZoneNative;case"MASTER","PRIMARY":mode=ZonePrimary;case"SLAVE","SECONDARY":mode=ZoneSecondary;default:return ZoneSpec{},ErrInvalidDNS};addresses:=[]netip.Addr{};for _,raw:=range strings.Fields(strings.ReplaceAll(masters,","," ")){address,parseErr:=netip.ParseAddr(raw);if parseErr!=nil{return ZoneSpec{},ErrInvalidDNS};addresses=append(addresses,address)};spec:=ZoneSpec{ID:ZoneID(idText),TenantID:tenant,Name:name,Mode:mode,SOA:SOAConfig{Primary:primary,Hostmaster:hostmaster,Refresh:uint32(numbers[1]),Retry:uint32(numbers[2]),Expire:uint32(numbers[3]),Minimum:uint32(numbers[4]),DefaultTTL:ttl},PrimaryAddresses:addresses,Account:account,Generation:generation};if validateZoneSpec(spec,nil,nil)!=nil{return ZoneSpec{},ErrInvalidDNS};return spec,nil}
func exactPowerDNSDomainID(ctx context.Context,query powerDNSQuerier,tenant string,id ZoneID)(int64,error){rows,err:=query.QueryContext(ctx,`SELECT DISTINCT d.id FROM domains d JOIN domainmetadata z ON z.domain_id=d.id AND z.kind=? AND z.content=? JOIN domainmetadata t ON t.domain_id=d.id AND t.kind=? AND t.content=? ORDER BY d.id LIMIT 2`,cyberPanelZoneIDMetadata,id,cyberPanelTenantMetadata,tenant);if err!=nil{return 0,err};ids:=make([]int64,0,2);for rows.Next(){var domainID int64;if err=rows.Scan(&domainID);err!=nil{rows.Close();return 0,err};ids=append(ids,domainID)};if err=rows.Err();err!=nil{rows.Close();return 0,err};if err=rows.Close();err!=nil{return 0,err};if len(ids)==0{return 0,sql.ErrNoRows};if len(ids)!=1{return 0,ErrDNSConflict};var owners uint64;if err=query.QueryRowContext(ctx,`SELECT COUNT(DISTINCT domain_id) FROM domainmetadata WHERE kind=? AND content=?`,cyberPanelZoneIDMetadata,id).Scan(&owners);err!=nil{return 0,err};if owners!=1{return 0,ErrDNSConflict};return ids[0],nil}
func exactPowerDNSMetadata(ctx context.Context,query powerDNSQuerier,domainID int64,kind string)(string,error){rows,err:=query.QueryContext(ctx,`SELECT content FROM domainmetadata WHERE domain_id=? AND kind=? ORDER BY id LIMIT 2`,domainID,kind);if err!=nil{return "",err};defer rows.Close();values:=make([]string,0,2);for rows.Next(){var value string;if err=rows.Scan(&value);err!=nil{return "",err};values=append(values,value)};if err=rows.Err();err!=nil{return "",err};if len(values)!=1{return "",ErrDNSConflict};return values[0],nil}
func powerDNSSOAMaterial(ctx context.Context,query powerDNSQuerier,domainID int64)(string,uint32,uint64,error){rows,err:=query.QueryContext(ctx,`SELECT content,ttl FROM records WHERE domain_id=? AND type='SOA' ORDER BY id LIMIT 2`,domainID);if err!=nil{return "",0,0,err};defer rows.Close();var soa string;var ttl uint32;count:=0;for rows.Next(){if err=rows.Scan(&soa,&ttl);err!=nil{return "",0,0,err};count++};if err=rows.Err();err!=nil{return "",0,0,err};if count!=1{return "",0,0,ErrDNSConflict};fields:=strings.Fields(soa);if len(fields)!=7{return "",0,0,ErrDNSConflict};serial,err:=strconv.ParseUint(fields[2],10,64);if err!=nil||serial==0{return "",0,0,ErrDNSConflict};return soa,ttl,serial,nil}
func powerDNSZoneObservationByDomain(ctx context.Context,query powerDNSQuerier,domainID int64)(ZoneSpec,uint64,error){var nameText,typeText,masters,account string;if err:=query.QueryRowContext(ctx,`SELECT name,type,COALESCE(master,''),COALESCE(account,'') FROM domains WHERE id=?`,domainID).Scan(&nameText,&typeText,&masters,&account);err!=nil{return ZoneSpec{},0,err};idText,err:=exactPowerDNSMetadata(ctx,query,domainID,cyberPanelZoneIDMetadata);if err!=nil{return ZoneSpec{},0,err};tenant,err:=exactPowerDNSMetadata(ctx,query,domainID,cyberPanelTenantMetadata);if err!=nil{return ZoneSpec{},0,err};generation,err:=exactPowerDNSMetadata(ctx,query,domainID,cyberPanelGenerationMetadata);if err!=nil{return ZoneSpec{},0,err};soa,ttl,serial,err:=powerDNSSOAMaterial(ctx,query,domainID);if err!=nil{return ZoneSpec{},0,err};spec,err:=decodePowerDNSZone(nameText,typeText,masters,account,idText,tenant,generation,soa,ttl);return spec,serial,err}
func powerDNSAdoptionCandidate(ctx context.Context,query powerDNSQuerier,domainID int64,identity ZoneSpec)(ZoneSpec,uint64,error){var nameText,typeText,masters string;if err:=query.QueryRowContext(ctx,`SELECT name,type,COALESCE(master,'') FROM domains WHERE id=?`,domainID).Scan(&nameText,&typeText,&masters);err!=nil{return ZoneSpec{},0,err};soa,ttl,serial,err:=powerDNSSOAMaterial(ctx,query,domainID);if err!=nil{return ZoneSpec{},0,err};spec,err:=decodePowerDNSZone(nameText,typeText,masters,identity.Account,string(identity.ID),identity.TenantID,strconv.FormatUint(identity.Generation,10),soa,ttl);return spec,serial,err}
func powerDNSZoneByDomain(ctx context.Context,tx *sql.Tx,domainID int64)(ZoneSpec,error){spec,_,err:=powerDNSZoneObservationByDomain(ctx,tx,domainID);return spec,err}
func applyPowerDNSMetadata(ctx context.Context,tx *sql.Tx,domainID int64,spec ZoneSpec,peers []TransferPeerSpec)error{if _,err:=tx.ExecContext(ctx,`DELETE FROM domainmetadata WHERE domain_id=? AND kind IN ('ALLOW-AXFR-FROM','ALSO-NOTIFY','TSIG-ALLOW-AXFR','AXFR-MASTER-TSIG',?,?,?)`,domainID,cyberPanelZoneIDMetadata,cyberPanelTenantMetadata,cyberPanelGenerationMetadata);err!=nil{return err};for _,metadata:=range [][2]string{{cyberPanelZoneIDMetadata,string(spec.ID)},{cyberPanelTenantMetadata,spec.TenantID},{cyberPanelGenerationMetadata,strconv.FormatUint(spec.Generation,10)}}{if _,err:=tx.ExecContext(ctx,`INSERT INTO domainmetadata(domain_id,kind,content) VALUES(?,?,?)`,domainID,metadata[0],metadata[1]);err!=nil{return err}};for _,peer:=range peers{kind:="ALLOW-AXFR-FROM";if peer.Direction=="also-notify"{kind="ALSO-NOTIFY"};if _,err:=tx.ExecContext(ctx,`INSERT INTO domainmetadata(domain_id,kind,content) VALUES(?,?,?)`,domainID,kind,peer.Address.String());err!=nil{return err};tsigKind:="TSIG-ALLOW-AXFR";if spec.Mode==ZoneSecondary{tsigKind="AXFR-MASTER-TSIG"};if _,err:=tx.ExecContext(ctx,`INSERT INTO domainmetadata(domain_id,kind,content) VALUES(?,?,?)`,domainID,tsigKind,peer.TSIGName);err!=nil{return err}};return nil}
func absoluteOwner(owner,zone DNSName)string{if owner.String()=="@"{return zone.String()};return owner.String()}
func powerDNSContent(kind RRKind,record string)(string,uint16){if kind==RR_MX{parts:=strings.Fields(record);priority,_:=strconv.ParseUint(parts[0],10,16);return strings.TrimSuffix(parts[1],"."),uint16(priority)};switch kind{case RR_CNAME,RR_NS,RR_PTR:return strings.TrimSuffix(record,"."),0};return record,0}
