package dns

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/netip"
	"sort"
	"strconv"
	"strings"
	"time"
)

type ZoneMode string
const ( ZoneNative ZoneMode="native"; ZonePrimary ZoneMode="primary"; ZoneSecondary ZoneMode="secondary" )
type SOAConfig struct { Primary DNSName `json:"primary"`; Hostmaster DNSName `json:"hostmaster"`; Refresh uint32 `json:"refresh"`; Retry uint32 `json:"retry"`; Expire uint32 `json:"expire"`; Minimum uint32 `json:"minimum"`; DefaultTTL uint32 `json:"default_ttl"` }
type ZoneSpec struct { ID ZoneID `json:"id"`; TenantID string `json:"tenant_id"`; Name DNSName `json:"name"`; Mode ZoneMode `json:"mode"`; SOA SOAConfig `json:"soa"`; PrimaryAddresses []netip.Addr `json:"primary_addresses,omitempty"`; Account string `json:"account"`; Generation uint64 `json:"generation"` }
type TSIGAlgorithm string
const ( TSIGHMACSHA256 TSIGAlgorithm="hmac-sha256"; TSIGHMACSHA512 TSIGAlgorithm="hmac-sha512" )
type TransferPeerSpec struct { ID PeerID `json:"id"`; ZoneID ZoneID `json:"zone_id"`; Address netip.Addr `json:"address"`; Direction string `json:"direction"`; TSIGName string `json:"tsig_name"`; TSIGAlgorithm TSIGAlgorithm `json:"tsig_algorithm"`; TSIGSecretRef string `json:"tsig_secret_ref"`; Notify bool `json:"notify"` }
type AuthorityReceipt struct { EffectID string `json:"effect_id"`; ZoneID ZoneID `json:"zone_id"`; Serial uint64 `json:"serial"`; AppliedSets uint32 `json:"applied_sets"`; RemovedSets uint32 `json:"removed_sets"`; ObservedAt time.Time `json:"observed_at"` }

type PowerDNSAuthority struct { DB *sql.DB }
const cyberPanelZoneIDMetadata="CYBERPANEL-ZONE-ID"
const cyberPanelTenantMetadata="CYBERPANEL-TENANT-ID"
const cyberPanelGenerationMetadata="CYBERPANEL-GENERATION"
func (p PowerDNSAuthority)ApplyZone(ctx context.Context,effectID string,spec ZoneSpec,sets []RecordSet,peers []TransferPeerSpec)(AuthorityReceipt,error){if p.DB==nil{return AuthorityReceipt{},errors.New("PowerDNS database required")};if err:=validateZoneSpec(spec,sets,peers);err!=nil{return AuthorityReceipt{},err};tx,err:=p.DB.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return AuthorityReceipt{},err};defer tx.Rollback();var existingID int64;lookupErr:=tx.QueryRowContext(ctx,`SELECT id FROM domains WHERE name=?`,spec.Name.String()).Scan(&existingID);if lookupErr==nil{current,loadErr:=powerDNSZoneByDomain(ctx,tx,existingID);if loadErr!=nil||current.ID!=spec.ID||current.TenantID!=spec.TenantID||current.Name.String()!=spec.Name.String()||current.Generation+1!=spec.Generation{return AuthorityReceipt{},ErrDNSConflict}}else if !errors.Is(lookupErr,sql.ErrNoRows){return AuthorityReceipt{},lookupErr}else if spec.Generation!=1{return AuthorityReceipt{},ErrDNSConflict};var otherName string;duplicateErr:=tx.QueryRowContext(ctx,`SELECT d.name FROM domains d JOIN domainmetadata m ON m.domain_id=d.id AND m.kind=? WHERE m.content=? LIMIT 1`,cyberPanelZoneIDMetadata,spec.ID).Scan(&otherName);if duplicateErr==nil&&otherName!=spec.Name.String(){return AuthorityReceipt{},ErrDNSConflict};if duplicateErr!=nil&&!errors.Is(duplicateErr,sql.ErrNoRows){return AuthorityReceipt{},duplicateErr};domainID,err:=ensurePowerDNSDomain(ctx,tx,spec);if err!=nil{return AuthorityReceipt{},err};serial,err:=nextSerial(ctx,tx,domainID,spec);if err!=nil{return AuthorityReceipt{},err};if _,err=tx.ExecContext(ctx,`DELETE FROM records WHERE domain_id=?`,domainID);err!=nil{return AuthorityReceipt{},err};soa:=fmt.Sprintf("%s %s %d %d %d %d %d",spec.SOA.Primary.FQDN(),spec.SOA.Hostmaster.FQDN(),serial,spec.SOA.Refresh,spec.SOA.Retry,spec.SOA.Expire,spec.SOA.Minimum);if _,err=tx.ExecContext(ctx,`INSERT INTO records(domain_id,name,type,content,ttl,prio,disabled,auth) VALUES(?,?,?,?,?,?,?,?)`,domainID,spec.Name.String(),"SOA",soa,spec.SOA.DefaultTTL,0,false,true);err!=nil{return AuthorityReceipt{},err};for _,set:=range sets{canonical,_:=set.Canonical(spec.Name);owner:=absoluteOwner(canonical.Owner,spec.Name);for _,record:=range canonical.Records{content,priority:=powerDNSContent(canonical.Kind,record);if _,err=tx.ExecContext(ctx,`INSERT INTO records(domain_id,name,type,content,ttl,prio,disabled,auth) VALUES(?,?,?,?,?,?,?,?)`,domainID,owner,canonical.Kind,content,canonical.TTL,priority,false,true);err!=nil{return AuthorityReceipt{},err}}};if err=applyPowerDNSMetadata(ctx,tx,domainID,spec,peers);err!=nil{return AuthorityReceipt{},err};if err=tx.Commit();err!=nil{return AuthorityReceipt{},err};return AuthorityReceipt{EffectID:effectID,ZoneID:spec.ID,Serial:serial,AppliedSets:uint32(len(sets)+1),ObservedAt:time.Now().UTC()},nil}
func (p PowerDNSAuthority)DeleteZone(ctx context.Context,effectID string,spec ZoneSpec)(AuthorityReceipt,error){if p.DB==nil{return AuthorityReceipt{},errors.New("PowerDNS database required")};tx,err:=p.DB.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return AuthorityReceipt{},err};defer tx.Rollback();var id int64;err=tx.QueryRowContext(ctx,`SELECT d.id FROM domains d JOIN domainmetadata z ON z.domain_id=d.id AND z.kind=? JOIN domainmetadata t ON t.domain_id=d.id AND t.kind=? WHERE z.content=? AND t.content=? LIMIT 1`,cyberPanelZoneIDMetadata,cyberPanelTenantMetadata,spec.ID,spec.TenantID).Scan(&id);if err!=nil{return AuthorityReceipt{},err};stored,err:=powerDNSZoneByDomain(ctx,tx,id);if err!=nil{return AuthorityReceipt{},err};if stored.ID!=spec.ID||stored.TenantID!=spec.TenantID||stored.Generation!=spec.Generation||spec.Name.String()!=""&&stored.Name.String()!=spec.Name.String(){return AuthorityReceipt{},ErrDNSConflict};for _,statement:=range []string{`DELETE FROM records WHERE domain_id=?`,`DELETE FROM domainmetadata WHERE domain_id=?`,`DELETE FROM cryptokeys WHERE domain_id=?`,`DELETE FROM comments WHERE domain_id=?`,`DELETE FROM domains WHERE id=?`}{if _,err=tx.ExecContext(ctx,statement,id);err!=nil{return AuthorityReceipt{},err}};if err=tx.Commit();err!=nil{return AuthorityReceipt{},err};return AuthorityReceipt{EffectID:effectID,ZoneID:spec.ID,ObservedAt:time.Now().UTC()},nil}
func (p PowerDNSAuthority)Zone(ctx context.Context,tenant string,id ZoneID)(ZoneSpec,error){if p.DB==nil{return ZoneSpec{},errors.New("PowerDNS database required")};spec,err:=scanPowerDNSZone(p.DB.QueryRowContext(ctx,powerDNSZoneSelect+` WHERE z.content=? AND t.content=? LIMIT 1`,cyberPanelZoneIDMetadata,cyberPanelTenantMetadata,cyberPanelGenerationMetadata,id,tenant));if err!=nil{return ZoneSpec{},err};if spec.ID!=id||spec.TenantID!=tenant{return ZoneSpec{},ErrInvalidDNS};return spec,nil}
func (p PowerDNSAuthority)ListZones(ctx context.Context,tenant string,limit int,after string)([]ZoneSpec,string,error){if p.DB==nil{return nil,"",errors.New("PowerDNS database required")};if limit<1||limit>500{limit=100};rows,err:=p.DB.QueryContext(ctx,powerDNSZoneSelect+` WHERE t.content=? AND d.name>? ORDER BY d.name LIMIT ?`,cyberPanelZoneIDMetadata,cyberPanelTenantMetadata,cyberPanelGenerationMetadata,tenant,after,limit+1);if err!=nil{return nil,"",err};defer rows.Close();items:=make([]ZoneSpec,0,limit+1);names:=make([]string,0,limit+1);for rows.Next(){spec,scanErr:=scanPowerDNSZone(rows);if scanErr!=nil||spec.TenantID!=tenant{return nil,"",ErrInvalidDNS};items=append(items,spec);names=append(names,spec.Name.String())};if err=rows.Err();err!=nil{return nil,"",err};next:="";if len(items)>limit{next=names[limit-1];items=items[:limit]};return items,next,nil}
func (p PowerDNSAuthority)ListRecordSets(ctx context.Context,spec ZoneSpec,limit int,after string)([]RecordSet,string,error){if p.DB==nil{return nil,"",errors.New("PowerDNS database required")};if limit<1||limit>1000{limit=200};afterName:="";afterType:="";if after!=""{parts:=strings.Split(after,"|");if len(parts)!=2{return nil,"",ErrInvalidDNS};afterName,afterType=parts[0],parts[1]};rows,err:=p.DB.QueryContext(ctx,`SELECT r.name,r.type,r.ttl,r.content,r.prio FROM records r JOIN domains d ON d.id=r.domain_id JOIN domainmetadata z ON z.domain_id=d.id AND z.kind=? JOIN domainmetadata t ON t.domain_id=d.id AND t.kind=? WHERE d.name=? AND z.content=? AND t.content=? AND r.type<>'SOA' AND (r.name>? OR (r.name=? AND r.type>?)) ORDER BY r.name,r.type,r.id LIMIT ?`,cyberPanelZoneIDMetadata,cyberPanelTenantMetadata,spec.Name.String(),spec.ID,spec.TenantID,afterName,afterName,afterType,limit*1000+1);if err!=nil{return nil,"",err};defer rows.Close();byKey:=map[string]*RecordSet{};order:=[]string{};for rows.Next(){var owner,kind,content string;var ttl uint32;var priority uint16;if err=rows.Scan(&owner,&kind,&ttl,&content,&priority);err!=nil{return nil,"",err};key:=owner+"|"+kind;set:=byKey[key];if set==nil{parsed,parseErr:=ParseName(owner);if owner==spec.Name.String(){parsed,parseErr=ParseName("@")} ;if parseErr!=nil{return nil,"",ErrInvalidDNS};set=&RecordSet{ZoneID:spec.ID,Owner:parsed,Kind:RRKind(kind),TTL:ttl};byKey[key]=set;order=append(order,key)};if RRKind(kind)==RR_MX{content=fmt.Sprintf("%d %s",priority,content)};set.Records=append(set.Records,content)};if err=rows.Err();err!=nil{return nil,"",err};sort.Strings(order);next:="";if len(order)>limit{next=order[limit-1];order=order[:limit]};result:=make([]RecordSet,0,len(order));for _,key:=range order{set:=*byKey[key];if set.Validate(spec.Name)!=nil{return nil,"",ErrInvalidDNS};result=append(result,set)};return result,next,nil}
func validateZoneSpec(spec ZoneSpec,sets []RecordSet,peers []TransferPeerSpec)error{if spec.ID==""||spec.TenantID==""||spec.Name.String()==""||spec.Generation==0||spec.Account==""||len(sets)>100000||len(peers)>1000{return ErrInvalidDNS};if spec.Mode!=ZoneNative&&spec.Mode!=ZonePrimary&&spec.Mode!=ZoneSecondary{return ErrInvalidDNS};if spec.SOA.Primary.String()==""||spec.SOA.Hostmaster.String()==""||spec.SOA.Refresh<300||spec.SOA.Retry<60||spec.SOA.Expire<86400||spec.SOA.Minimum<30||spec.SOA.DefaultTTL<30{return ErrInvalidDNS};if spec.Mode==ZoneSecondary&&len(spec.PrimaryAddresses)==0{return ErrInvalidDNS};for _,address:=range spec.PrimaryAddresses{if !address.IsValid()||address.IsUnspecified()||address.IsMulticast(){return ErrInvalidDNS}};keys:=map[string]struct{}{};for _,set:=range sets{if err:=set.Validate(spec.Name);err!=nil{return err};key:=set.Owner.String()+"|"+string(set.Kind);if _,ok:=keys[key];ok{return ErrInvalidDNS};keys[key]=struct{}{}};for _,peer:=range peers{if peer.ID==""||peer.ZoneID!=spec.ID||!peer.Address.IsValid()||(peer.Direction!="allow-transfer"&&peer.Direction!="also-notify")||peer.TSIGName==""||peer.TSIGSecretRef==""||(peer.TSIGAlgorithm!=TSIGHMACSHA256&&peer.TSIGAlgorithm!=TSIGHMACSHA512){return ErrInvalidDNS}};return nil}
func ensurePowerDNSDomain(ctx context.Context,tx *sql.Tx,spec ZoneSpec)(int64,error){pdnsType:="NATIVE";masters:="";switch spec.Mode{case ZonePrimary:pdnsType="MASTER";case ZoneSecondary:pdnsType="SLAVE";values:=make([]string,len(spec.PrimaryAddresses));for index,address:=range spec.PrimaryAddresses{values[index]=address.String()};masters=strings.Join(values,",")};var id int64;err:=tx.QueryRowContext(ctx,`SELECT id FROM domains WHERE name=?`,spec.Name.String()).Scan(&id);if errors.Is(err,sql.ErrNoRows){result,insertErr:=tx.ExecContext(ctx,`INSERT INTO domains(name,master,last_check,type,notified_serial,account) VALUES(?,?,?,?,?,?)`,spec.Name.String(),masters,nil,pdnsType,nil,spec.Account);if insertErr!=nil{return 0,insertErr};return result.LastInsertId()};if err!=nil{return 0,err};_,err=tx.ExecContext(ctx,`UPDATE domains SET master=?,type=?,account=? WHERE id=?`,masters,pdnsType,spec.Account,id);return id,err}
func nextSerial(ctx context.Context,tx *sql.Tx,domainID int64,spec ZoneSpec)(uint64,error){var soa string;err:=tx.QueryRowContext(ctx,`SELECT content FROM records WHERE domain_id=? AND type='SOA' LIMIT 1`,domainID).Scan(&soa);current:=uint64(0);if err==nil{parts:=strings.Fields(soa);if len(parts)>=3{current,_=strconv.ParseUint(parts[2],10,64)}}else if !errors.Is(err,sql.ErrNoRows){return 0,err};today:=uint64(time.Now().UTC().Year()*1000000+int(time.Now().UTC().Month())*10000+time.Now().UTC().Day()*100);if current>=today{return current+1,nil};return today+1,nil}
const powerDNSZoneSelect=`SELECT d.name,d.type,COALESCE(d.master,''),COALESCE(d.account,''),z.content,t.content,g.content,r.content,r.ttl FROM domains d JOIN domainmetadata z ON z.domain_id=d.id AND z.kind=? JOIN domainmetadata t ON t.domain_id=d.id AND t.kind=? JOIN domainmetadata g ON g.domain_id=d.id AND g.kind=? JOIN records r ON r.domain_id=d.id AND r.type='SOA'`
type powerDNSScanner interface{Scan(...any)error}
func scanPowerDNSZone(scanner powerDNSScanner)(ZoneSpec,error){var nameText,typeText,masters,account,idText,tenant,generationText,soaText string;var ttl uint32;if err:=scanner.Scan(&nameText,&typeText,&masters,&account,&idText,&tenant,&generationText,&soaText,&ttl);err!=nil{return ZoneSpec{},err};name,err:=ParseName(nameText);if err!=nil{return ZoneSpec{},ErrInvalidDNS};fields:=strings.Fields(soaText);if len(fields)!=7{return ZoneSpec{},ErrInvalidDNS};primary,err:=ParseName(fields[0]);if err!=nil{return ZoneSpec{},ErrInvalidDNS};hostmaster,err:=ParseName(fields[1]);if err!=nil{return ZoneSpec{},ErrInvalidDNS};numbers:=make([]uint64,5);for index:=range numbers{numbers[index],err=strconv.ParseUint(fields[index+2],10,32);if err!=nil{return ZoneSpec{},ErrInvalidDNS}};generation,err:=strconv.ParseUint(generationText,10,64);if err!=nil{return ZoneSpec{},ErrInvalidDNS};mode:=ZoneNative;switch strings.ToUpper(typeText){case"NATIVE":mode=ZoneNative;case"MASTER","PRIMARY":mode=ZonePrimary;case"SLAVE","SECONDARY":mode=ZoneSecondary;default:return ZoneSpec{},ErrInvalidDNS};addresses:=[]netip.Addr{};for _,raw:=range strings.Fields(strings.ReplaceAll(masters,","," ")){address,parseErr:=netip.ParseAddr(raw);if parseErr!=nil{return ZoneSpec{},ErrInvalidDNS};addresses=append(addresses,address)};spec:=ZoneSpec{ID:ZoneID(idText),TenantID:tenant,Name:name,Mode:mode,SOA:SOAConfig{Primary:primary,Hostmaster:hostmaster,Refresh:uint32(numbers[1]),Retry:uint32(numbers[2]),Expire:uint32(numbers[3]),Minimum:uint32(numbers[4]),DefaultTTL:ttl},PrimaryAddresses:addresses,Account:account,Generation:generation};if validateZoneSpec(spec,nil,nil)!=nil{return ZoneSpec{},ErrInvalidDNS};return spec,nil}
func powerDNSZoneByDomain(ctx context.Context,tx *sql.Tx,domainID int64)(ZoneSpec,error){return scanPowerDNSZone(tx.QueryRowContext(ctx,powerDNSZoneSelect+` WHERE d.id=? LIMIT 1`,cyberPanelZoneIDMetadata,cyberPanelTenantMetadata,cyberPanelGenerationMetadata,domainID))}
func applyPowerDNSMetadata(ctx context.Context,tx *sql.Tx,domainID int64,spec ZoneSpec,peers []TransferPeerSpec)error{if _,err:=tx.ExecContext(ctx,`DELETE FROM domainmetadata WHERE domain_id=? AND kind IN ('ALLOW-AXFR-FROM','ALSO-NOTIFY','TSIG-ALLOW-AXFR','AXFR-MASTER-TSIG',?,?,?)`,domainID,cyberPanelZoneIDMetadata,cyberPanelTenantMetadata,cyberPanelGenerationMetadata);err!=nil{return err};for _,metadata:=range [][2]string{{cyberPanelZoneIDMetadata,string(spec.ID)},{cyberPanelTenantMetadata,spec.TenantID},{cyberPanelGenerationMetadata,strconv.FormatUint(spec.Generation,10)}}{if _,err:=tx.ExecContext(ctx,`INSERT INTO domainmetadata(domain_id,kind,content) VALUES(?,?,?)`,domainID,metadata[0],metadata[1]);err!=nil{return err}};for _,peer:=range peers{kind:="ALLOW-AXFR-FROM";if peer.Direction=="also-notify"{kind="ALSO-NOTIFY"};if _,err:=tx.ExecContext(ctx,`INSERT INTO domainmetadata(domain_id,kind,content) VALUES(?,?,?)`,domainID,kind,peer.Address.String());err!=nil{return err};tsigKind:="TSIG-ALLOW-AXFR";if spec.Mode==ZoneSecondary{tsigKind="AXFR-MASTER-TSIG"};if _,err:=tx.ExecContext(ctx,`INSERT INTO domainmetadata(domain_id,kind,content) VALUES(?,?,?)`,domainID,tsigKind,peer.TSIGName);err!=nil{return err}};return nil}
func absoluteOwner(owner,zone DNSName)string{if owner.String()=="@"{return zone.String()};return owner.String()}
func powerDNSContent(kind RRKind,record string)(string,uint16){if kind==RR_MX{parts:=strings.Fields(record);priority,_:=strconv.ParseUint(parts[0],10,16);return strings.TrimSuffix(parts[1],"."),uint16(priority)};switch kind{case RR_CNAME,RR_NS,RR_PTR:return strings.TrimSuffix(record,"."),0};return record,0}
