package audit

import (
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"syscall"
	"time"
)

type MutationBinding struct { Event Event; Prepared Prepared }
type DecisionManifest struct { RequestID string `json:"request_id"`; PolicyDigest string `json:"policy_digest"`; ScopeDigest string `json:"scope_digest"`; FilterDigest string `json:"filter_digest"`; EvaluatedObjects uint64 `json:"evaluated_objects"`; AllowedObjects uint64 `json:"allowed_objects"`; DeniedObjects uint64 `json:"denied_objects"`; ResultDigest string `json:"result_digest"` }
type FloodSummary struct { WindowStart time.Time `json:"window_start"`; WindowEnd time.Time `json:"window_end"`; Class string `json:"class"`; SourceBucket string `json:"source_bucket"`; Count uint64 `json:"count"`; SampleDigests []string `json:"sample_digests"` }
type Service struct { Writer *Writer; Emergency *EmergencyWriter; MaxPreparedAge time.Duration; clock func()time.Time }
func NewService(writer *Writer,emergency *EmergencyWriter)(*Service,error){if writer==nil||emergency==nil{return nil,ErrInvalid};return &Service{Writer:writer,Emergency:emergency,MaxPreparedAge:24*time.Hour,clock:time.Now},nil}
func(s *Service)PrepareMutation(ctx context.Context,event Event)(MutationBinding,error){if event.Class!=ClassMutation&&event.Class!=ClassAuthorization&&event.Class!=ClassPrivilegedEffect{return MutationBinding{},ErrInvalid};prepared,err:=s.Writer.Prepare(ctx,event);if err!=nil{return MutationBinding{},err};return MutationBinding{Event:event,Prepared:prepared},nil}
func(s *Service)CommitMutation(ctx context.Context,binding MutationBinding)(Record,error){if binding.Prepared.EventID!=binding.Event.ID||binding.Prepared.EventDigest==""||s.clock().UTC().Sub(binding.Prepared.PreparedAt)>s.MaxPreparedAge{return Record{},ErrConflict};return s.Writer.Finalize(ctx,binding.Event)}
func(s *Service)RecordDecision(ctx context.Context,event Event,manifest *DecisionManifest)(Record,error){if event.Class!=ClassAuthorization&&event.Class!=ClassAuthentication&&event.Class!=ClassSensitiveRead&&event.Class!=ClassSecurity{return Record{},ErrInvalid};if manifest!=nil{if manifest.RequestID==""||manifest.PolicyDigest==""||manifest.ScopeDigest==""||manifest.FilterDigest==""||manifest.ResultDigest==""||manifest.AllowedObjects+manifest.DeniedObjects>manifest.EvaluatedObjects{return Record{},ErrInvalid};raw,err:=json.Marshal(manifest);if err!=nil{return Record{},err};sum:=sha256.Sum256(raw);if event.Attributes==nil{event.Attributes=map[string]string{}};event.Attributes["decision_manifest_digest"]=hex.EncodeToString(sum[:]);event.Attributes["evaluated_objects"]=fmt.Sprint(manifest.EvaluatedObjects)};return s.Writer.Append(ctx,event)}
func(s *Service)RecordFloodSummary(ctx context.Context,event Event,summary FloodSummary)(Record,error){if event.Class!=ClassSecurity||summary.Class==""||summary.SourceBucket==""||summary.Count==0||!summary.WindowEnd.After(summary.WindowStart)||len(summary.SampleDigests)>32{return Record{},ErrInvalid};for _,digest:=range summary.SampleDigests{if len(digest)!=64{return Record{},ErrInvalid}};raw,err:=json.Marshal(summary);if err!=nil{return Record{},err};sum:=sha256.Sum256(raw);if event.Attributes==nil{event.Attributes=map[string]string{}};event.Attributes["summary_digest"]=hex.EncodeToString(sum[:]);event.Attributes["summary_count"]=fmt.Sprint(summary.Count);return s.Writer.Append(ctx,event)}
func(s *Service)SafetyRecovery(ctx context.Context,event Event,action func(context.Context)error)(Record,error){if event.Class!=ClassSafetyRecovery{return Record{},ErrInvalid};if action==nil{return Record{},ErrInvalid};if _,err:=s.Writer.Prepare(ctx,event);err==nil{effectErr:=action(ctx);if effectErr!=nil{event.Outcome=OutcomeFailed;event.Attributes=appendAttribute(event.Attributes,"effect_error",boundedError(effectErr));record,auditErr:=s.Writer.Finalize(ctx,event);return record,errors.Join(effectErr,auditErr)};event.Outcome=OutcomeApplied;return s.Writer.Finalize(ctx,event)};emergency,emergencyErr:=s.Emergency.Append(ctx,event);if emergencyErr!=nil{return Record{},errors.Join(ErrIntegrity,emergencyErr)};effectErr:=action(ctx);if effectErr!=nil{return Record{},errors.Join(effectErr,fmt.Errorf("emergency audit sequence %d",emergency.Sequence))};return Record{Sequence:emergency.Sequence,Event:event,Hash:emergency.Hash,WrittenAt:emergency.WrittenAt},nil}
func appendAttribute(values map[string]string,key,value string)map[string]string{out:=make(map[string]string,len(values)+1);for k,v:=range values{out[k]=v};out[key]=value;return out}
func boundedError(err error)string{value:=err.Error();if len(value)>512{return value[:512]};return value}

type EmergencyRecord struct { Sequence uint64 `json:"sequence"`; EventID string `json:"event_id"`; Action string `json:"action"`; RequestDigest string `json:"request_digest"`; Target Target `json:"target"`; PreviousHash string `json:"previous_hash"`; Hash string `json:"hash"`; WrittenAt time.Time `json:"written_at"`; ImportedEventID string `json:"imported_event_id,omitempty"` }
type EmergencyWriter struct { root string; path string; maxBytes int64; mu sync.Mutex; sequence uint64; head string; uid int }
func NewEmergencyWriter(root string,ownerUID int)(*EmergencyWriter,error){if !filepath.IsAbs(root)||ownerUID<0{return nil,ErrInvalid};info,err:=os.Lstat(root);if err!=nil{return nil,err};stat,ok:=info.Sys().(*syscall.Stat_t);if !ok||!info.IsDir()||info.Mode().Perm()!=0700||int(stat.Uid)!=ownerUID{return nil,ErrIntegrity};writer:=&EmergencyWriter{root:root,path:filepath.Join(root,"emergency.jsonl"),maxBytes:8<<20,uid:ownerUID};if err=writer.load();err!=nil&&!errors.Is(err,os.ErrNotExist){return nil,err};return writer,nil}
func(w *EmergencyWriter)Append(ctx context.Context,event Event)(EmergencyRecord,error){w.mu.Lock();defer w.mu.Unlock();if event.Validate()!=nil||event.Class!=ClassSafetyRecovery{return EmergencyRecord{},ErrInvalid};select{case<-ctx.Done():return EmergencyRecord{},ctx.Err();default:};info,err:=os.Lstat(w.root);if err!=nil{return EmergencyRecord{},err};stat,ok:=info.Sys().(*syscall.Stat_t);if !ok||!info.IsDir()||info.Mode().Perm()!=0700||int(stat.Uid)!=w.uid{return EmergencyRecord{},ErrIntegrity};if fileInfo,statErr:=os.Lstat(w.path);statErr==nil{fileStat,valid:=fileInfo.Sys().(*syscall.Stat_t);if !valid||!fileInfo.Mode().IsRegular()||fileInfo.Mode().Perm()!=0600||int(fileStat.Uid)!=w.uid||fileInfo.Size()>w.maxBytes{return EmergencyRecord{},ErrCapacity}}else if !errors.Is(statErr,os.ErrNotExist){return EmergencyRecord{},statErr};record:=EmergencyRecord{Sequence:w.sequence+1,EventID:event.ID,Action:event.Action,RequestDigest:event.RequestDigest,Target:event.Target,PreviousHash:w.head,WrittenAt:time.Now().UTC()};raw,_:=json.Marshal(struct{Domain string `json:"domain"`;Record EmergencyRecord `json:"record"`} {"cyberpanel-emergency-audit-v1",record});sum:=sha256.Sum256(raw);record.Hash=hex.EncodeToString(sum[:]);encoded,_:=json.Marshal(record);if int64(len(encoded))+1>w.maxBytes{return EmergencyRecord{},ErrCapacity};file,err:=os.OpenFile(w.path,os.O_CREATE|os.O_APPEND|os.O_WRONLY,0600);if err!=nil{return EmergencyRecord{},err};if _,err=file.Write(append(encoded,'\n'));err==nil{err=file.Sync()};closeErr:=file.Close();if err==nil{err=closeErr};if err!=nil{return EmergencyRecord{},err};directory,err:=os.Open(w.root);if err!=nil{return EmergencyRecord{},err};err=directory.Sync();directory.Close();if err!=nil{return EmergencyRecord{},err};w.sequence=record.Sequence;w.head=record.Hash;return record,nil}
func(w *EmergencyWriter)load()error{file,err:=os.Open(w.path);if err!=nil{return err};defer file.Close();decoder:=json.NewDecoder(io.LimitReader(file,w.maxBytes+1));previous:="";var sequence uint64;for{var record EmergencyRecord;if err=decoder.Decode(&record);errors.Is(err,io.EOF){break}else if err!=nil{return ErrIntegrity};if record.Sequence!=sequence+1||record.PreviousHash!=previous{return ErrIntegrity};candidate:=record;candidate.Hash="";raw,_:=json.Marshal(struct{Domain string `json:"domain"`;Record EmergencyRecord `json:"record"`}{"cyberpanel-emergency-audit-v1",candidate});sum:=sha256.Sum256(raw);if record.Hash!=hex.EncodeToString(sum[:]){return ErrIntegrity};sequence=record.Sequence;previous=record.Hash};w.sequence=sequence;w.head=previous;return nil}

type Ed25519Signer struct { KeyID string; Private ed25519.PrivateKey; PublicKeys map[string]ed25519.PublicKey }
func NewEd25519Signer(keyID string,private ed25519.PrivateKey,keys map[string]ed25519.PublicKey)(*Ed25519Signer,error){if keyID==""||len(private)!=ed25519.PrivateKeySize||len(keys[keyID])!=ed25519.PublicKeySize{return nil,ErrInvalid};return &Ed25519Signer{KeyID:keyID,Private:append(ed25519.PrivateKey(nil),private...),PublicKeys:keys},nil}
func(s *Ed25519Signer)SignCheckpoint(ctx context.Context,sequence uint64,head string)(string,string,error){select{case<-ctx.Done():return "","",ctx.Err();default:};message:=checkpointMessage(sequence,head);signature:=ed25519.Sign(s.Private,message);return s.KeyID,base64.RawURLEncoding.EncodeToString(signature),nil}
func(s *Ed25519Signer)VerifyCheckpoint(ctx context.Context,checkpoint Checkpoint)error{select{case<-ctx.Done():return ctx.Err();default:};key:=s.PublicKeys[checkpoint.KeyID];signature,err:=base64.RawURLEncoding.DecodeString(checkpoint.Signature);if err!=nil||len(key)!=ed25519.PublicKeySize||!ed25519.Verify(key,checkpointMessage(checkpoint.Sequence,checkpoint.HeadHash),signature){return ErrIntegrity};return nil}
func checkpointMessage(sequence uint64,head string)[]byte{return []byte(fmt.Sprintf("cyberpanel-audit-checkpoint-v1\x00%d\x00%s",sequence,head))}
func GenerateSigningKey()(ed25519.PublicKey,ed25519.PrivateKey,error){return ed25519.GenerateKey(rand.Reader)}

type ExportFormat string
const ( ExportJSONLines ExportFormat="jsonl";ExportCanonicalJSON ExportFormat="canonical_json" )
type ExportRequest struct { Query Query `json:"query"`; Format ExportFormat `json:"format"`; IncludeCheckpoint bool `json:"include_checkpoint"`; MaximumRecords uint32 `json:"maximum_records"` }
type ExportManifest struct { ID string `json:"id"`; Format ExportFormat `json:"format"`; Records uint32 `json:"records"`; FirstSequence uint64 `json:"first_sequence"`; LastSequence uint64 `json:"last_sequence"`; Digest string `json:"digest"`; Checkpoint *Checkpoint `json:"checkpoint,omitempty"`; CreatedAt time.Time `json:"created_at"` }
func(w *Writer)Export(ctx context.Context,request ExportRequest,destination io.Writer)(ExportManifest,error){if destination==nil||(request.Format!=ExportJSONLines&&request.Format!=ExportCanonicalJSON){return ExportManifest{},ErrInvalid};if request.MaximumRecords==0||request.MaximumRecords>100000{request.MaximumRecords=10000};request.Query.Limit=request.MaximumRecords;records,err:=w.index.Query(ctx,request.Query);if err!=nil{return ExportManifest{},err};hasher:=sha256.New();output:=io.MultiWriter(destination,hasher);if request.Format==ExportCanonicalJSON{if _,err=output.Write([]byte("["));err!=nil{return ExportManifest{},err}};for index,record:=range records{select{case<-ctx.Done():return ExportManifest{},ctx.Err();default:};raw,marshalErr:=json.Marshal(record);if marshalErr!=nil{return ExportManifest{},marshalErr};if request.Format==ExportCanonicalJSON&&index>0{if _,err=output.Write([]byte(","));err!=nil{return ExportManifest{},err}};if _,err=output.Write(raw);err!=nil{return ExportManifest{},err};if request.Format==ExportJSONLines{if _,err=output.Write([]byte("\n"));err!=nil{return ExportManifest{},err}}};if request.Format==ExportCanonicalJSON{if _,err=output.Write([]byte("]"));err!=nil{return ExportManifest{},err}};manifest:=ExportManifest{ID:fmt.Sprintf("audit-export-%d",time.Now().UTC().UnixNano()),Format:request.Format,Records:uint32(len(records)),Digest:hex.EncodeToString(hasher.Sum(nil)),CreatedAt:time.Now().UTC()};if len(records)>0{manifest.FirstSequence=records[0].Sequence;manifest.LastSequence=records[len(records)-1].Sequence};if request.IncludeCheckpoint{checkpoint,found,checkpointErr:=w.index.LastCheckpoint(ctx);if checkpointErr!=nil{return ExportManifest{},checkpointErr};if found{manifest.Checkpoint=&checkpoint}};return manifest,nil}
func safeExportFilename(value string)string{value=strings.Map(func(r rune)rune{if r>='a'&&r<='z'||r>='A'&&r<='Z'||r>='0'&&r<='9'||r=='.'||r=='-'||r=='_'{return r};return '_'},value);if value==""{return"audit-export.jsonl"};return value}
var _=safeExportFilename
