package audit

import(
	"bufio"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"
)

const(maxEventBytes=256<<10;maxSegmentBytes=64<<20)
type Signer interface{SignCheckpoint(context.Context,uint64,string)(keyID,signature string,err error);VerifyCheckpoint(context.Context,Checkpoint)error}
type Index interface{Prepared(context.Context,string)(Prepared,bool,error);Prepare(context.Context,Prepared)error;Finalize(context.Context,string,uint64,string)error;Lookup(context.Context,string)(uint64,string,bool,error);Project(context.Context,Record)error;Checkpoint(context.Context,Checkpoint)error;LastCheckpoint(context.Context)(Checkpoint,bool,error);Query(context.Context,Query)([]Record,error)}
type Writer struct{root string;index Index;signer Signer;clock func()time.Time;mu sync.Mutex;sequence uint64;headHash string;segmentID string;segmentBytes int64}
type manifest struct{Version int `json:"version"`;Sequence uint64 `json:"sequence"`;HeadHash,SegmentID string;SegmentBytes int64}

func NewWriter(root string,index Index,signer Signer)(*Writer,error){if !filepath.IsAbs(root)||index==nil||signer==nil{return nil,ErrInvalid};info,err:=os.Lstat(root);if err!=nil{return nil,err};if !info.IsDir()||info.Mode().Perm()!=0700{return nil,ErrInvalid};writer:=&Writer{root:root,index:index,signer:signer,clock:time.Now};if err=writer.loadManifest();err!=nil&&!errors.Is(err,os.ErrNotExist){return nil,err};return writer,nil}
func(w *Writer)Prepare(ctx context.Context,event Event)(Prepared,error){if err:=event.Validate();err!=nil{return Prepared{},err};raw,err:=canonicalEvent(event);if err!=nil{return Prepared{},err};prepared:=Prepared{EventID:event.ID,EventDigest:digest(raw),PreparedAt:w.clock().UTC()};if existing,found,loadErr:=w.index.Prepared(ctx,event.ID);loadErr!=nil{return Prepared{},loadErr}else if found{if existing.EventDigest!=prepared.EventDigest{return Prepared{},ErrConflict};return existing,nil};if err=w.index.Prepare(ctx,prepared);err!=nil{return Prepared{},err};return prepared,nil}
func(w *Writer)Finalize(ctx context.Context,event Event)(Record,error){w.mu.Lock();defer w.mu.Unlock();if err:=event.Validate();err!=nil{return Record{},err};raw,err:=canonicalEvent(event);if err!=nil{return Record{},err};prepared,found,err:=w.index.Prepared(ctx,event.ID);if err!=nil{return Record{},err};if !found||prepared.EventDigest!=digest(raw){return Record{},ErrConflict};if sequence,hash,exists,lookupErr:=w.index.Lookup(ctx,event.ID);lookupErr!=nil{return Record{},lookupErr}else if exists{return w.readRecord(sequence,hash)};if recovered,recoveryFound,recoveryErr:=w.findEvent(event.ID,prepared.EventDigest);recoveryErr!=nil{return Record{},recoveryErr}else if recoveryFound{if err=w.index.Finalize(ctx,event.ID,recovered.Sequence,recovered.Hash);err!=nil{return Record{},err};if err=w.index.Project(ctx,recovered);err!=nil{return Record{},err};return recovered,nil};if w.segmentID==""||w.segmentBytes+int64(len(raw))+512>maxSegmentBytes{w.segmentID=fmt.Sprintf("segment-%020d",w.sequence+1);w.segmentBytes=0};record:=Record{Sequence:w.sequence+1,Event:event,PreviousHash:w.headHash,WrittenAt:w.clock().UTC()};record.Hash=recordHash(record,raw);encoded,err:=json.Marshal(record);if err!=nil{return Record{},err};if len(encoded)>maxEventBytes{return Record{},ErrCapacity};path:=filepath.Join(w.root,w.segmentID+".jsonl");file,err:=os.OpenFile(path,os.O_CREATE|os.O_APPEND|os.O_WRONLY,0600);if err!=nil{return Record{},err};info,statErr:=file.Stat();if statErr!=nil||!info.Mode().IsRegular()||info.Mode().Perm()!=0600{file.Close();return Record{},ErrIntegrity};if _,err=file.Write(append(encoded,'\n'));err!=nil{file.Close();return Record{},err};if err=file.Sync();err!=nil{file.Close();return Record{},err};if err=file.Close();err!=nil{return Record{},err};if err=w.syncRoot();err!=nil{return Record{},err};w.sequence=record.Sequence;w.headHash=record.Hash;w.segmentBytes+=int64(len(encoded)+1);if err=w.persistManifest();err!=nil{return Record{},err};if err=w.index.Finalize(ctx,event.ID,record.Sequence,record.Hash);err!=nil{return Record{},err};if err=w.index.Project(ctx,record);err!=nil{return Record{},err};return record,nil}
func(w *Writer)Append(ctx context.Context,event Event)(Record,error){if _,err:=w.Prepare(ctx,event);err!=nil{return Record{},err};return w.Finalize(ctx,event)}
func(w *Writer)Checkpoint(ctx context.Context)(Checkpoint,error){w.mu.Lock();defer w.mu.Unlock();if w.sequence==0||w.headHash==""{return Checkpoint{},ErrNotFound};key,signature,err:=w.signer.SignCheckpoint(ctx,w.sequence,w.headHash);if err!=nil{return Checkpoint{},err};checkpoint:=Checkpoint{Sequence:w.sequence,HeadHash:w.headHash,SegmentID:w.segmentID,KeyID:key,Signature:signature,CreatedAt:w.clock().UTC()};if err=w.index.Checkpoint(ctx,checkpoint);err!=nil{return Checkpoint{},err};raw,_:=json.Marshal(checkpoint);return checkpoint,atomicWrite(w.root,fmt.Sprintf("checkpoint-%020d.json",checkpoint.Sequence),raw)}
func(w *Writer)Verify(ctx context.Context)(Checkpoint,error){checkpoint,found,err:=w.index.LastCheckpoint(ctx);if err!=nil||!found{return Checkpoint{},err};if err=w.signer.VerifyCheckpoint(ctx,checkpoint);err!=nil{return Checkpoint{},err};records,err:=w.scan(0,checkpoint.Sequence);if err!=nil{return Checkpoint{},err};previous:="";for _,record:=range records{raw,_:=canonicalEvent(record.Event);if record.PreviousHash!=previous||record.Hash!=recordHash(record,raw){return Checkpoint{},ErrIntegrity};previous=record.Hash};if len(records)==0||records[len(records)-1].Sequence!=checkpoint.Sequence||previous!=checkpoint.HeadHash{return Checkpoint{},ErrIntegrity};return checkpoint,nil}
func(w *Writer)Query(ctx context.Context,query Query)([]Record,error){if w==nil||w.index==nil{return nil,ErrInvalid};return w.index.Query(ctx,query)}
func(w *Writer)scan(after,through uint64)([]Record,error){entries,err:=os.ReadDir(w.root);if err!=nil{return nil,err};var names []string;for _,entry:=range entries{if !entry.IsDir()&&strings.HasPrefix(entry.Name(),"segment-")&&strings.HasSuffix(entry.Name(),".jsonl"){names=append(names,entry.Name())}};sort.Strings(names);var records []Record;for _,name:=range names{file,openErr:=os.Open(filepath.Join(w.root,name));if openErr!=nil{return nil,openErr};scanner:=bufio.NewScanner(io.LimitReader(file,maxSegmentBytes+1));scanner.Buffer(make([]byte,64<<10),maxEventBytes);for scanner.Scan(){var record Record;if err=json.Unmarshal(scanner.Bytes(),&record);err!=nil{file.Close();return nil,ErrIntegrity};if record.Sequence>after&&(through==0||record.Sequence<=through){records=append(records,record)}};scanErr:=scanner.Err();file.Close();if scanErr!=nil{return nil,scanErr}};return records,nil}
func(w *Writer)readRecord(sequence uint64,hash string)(Record,error){records,err:=w.scan(sequence-1,sequence);if err!=nil{return Record{},err};if len(records)!=1||records[0].Hash!=hash{return Record{},ErrIntegrity};return records[0],nil}
func(w *Writer)findEvent(eventID,eventDigest string)(Record,bool,error){records,err:=w.scan(0,0);if err!=nil{return Record{},false,err};for index:=len(records)-1;index>=0;index--{if records[index].Event.ID==eventID{raw,_:=canonicalEvent(records[index].Event);if digest(raw)!=eventDigest{return Record{},false,ErrConflict};return records[index],true,nil}};return Record{},false,nil}
func(w *Writer)loadManifest()error{raw,err:=os.ReadFile(filepath.Join(w.root,"manifest.json"));if err!=nil{return err};if len(raw)>4096{return ErrIntegrity};var value manifest;if err=json.Unmarshal(raw,&value);err!=nil{return err};canonical,_:=json.Marshal(value);if string(canonical)!=string(raw)||value.Version!=1||len(value.HeadHash)!=64{return ErrIntegrity};w.sequence=value.Sequence;w.headHash=value.HeadHash;w.segmentID=value.SegmentID;w.segmentBytes=value.SegmentBytes;return nil}
func(w *Writer)persistManifest()error{raw,_:=json.Marshal(manifest{1,w.sequence,w.headHash,w.segmentID,w.segmentBytes});return atomicWrite(w.root,"manifest.json",raw)}
func(w *Writer)syncRoot()error{directory,err:=os.Open(w.root);if err!=nil{return err};defer directory.Close();return directory.Sync()}
func canonicalEvent(event Event)([]byte,error){if len(event.Attributes)>0{keys:=make([]string,0,len(event.Attributes));for key:=range event.Attributes{keys=append(keys,key)};sort.Strings(keys);ordered:=make(map[string]string,len(keys));for _,key:=range keys{ordered[key]=event.Attributes[key]};event.Attributes=ordered};return json.Marshal(event)}
func recordHash(record Record,event []byte)string{sum:=sha256.New();sum.Write([]byte("cyberpanel-audit-v1\x00"));sum.Write([]byte(fmt.Sprintf("%020d\x00",record.Sequence)));sum.Write([]byte(record.PreviousHash));sum.Write([]byte{0});sum.Write(event);sum.Write([]byte{0});sum.Write([]byte(record.WrittenAt.UTC().Format(time.RFC3339Nano)));return hex.EncodeToString(sum.Sum(nil))}
func digest(raw []byte)string{sum:=sha256.Sum256(raw);return hex.EncodeToString(sum[:])}
func atomicWrite(root,name string,raw []byte)error{temporary:=name+".tmp";path:=filepath.Join(root,temporary);file,err:=os.OpenFile(path,os.O_CREATE|os.O_EXCL|os.O_WRONLY,0600);if err!=nil{return err};if _,err=file.Write(raw);err==nil{err=file.Sync()};closeErr:=file.Close();if err==nil{err=closeErr};if err!=nil{return err};if err=os.Rename(path,filepath.Join(root,name));err!=nil{return err};directory,err:=os.Open(root);if err!=nil{return err};defer directory.Close();return directory.Sync()}
