// AdminPages — maps every remaining admin route to a GenericCardPage config.
// Each config defines the visual card layout for that resource type.
import type { Component } from "vue";
import GenericCardPage from "./GenericCardPage.vue";
import type { CardPageConfig } from "./GenericCardPage.vue";

export const adminPageConfigs: Record<string, CardPageConfig> = {
  redis: {
    title: "Redis", subtitle: "Caching servers for your applications",
    listOperation: "redis.instance.list", createLabel: "New Redis",
    icon: "stack", nameField: "id", statusField: "health",
    metaFields: [{ key: "version", label: "Version" }, { key: "purpose", label: "Used for" }],
    emptyTitle: "No Redis instances", emptyBody: "Create a Redis cache to speed up your apps and reduce database load.",
  },
  "database-instances": {
    title: "Database Servers", subtitle: "MariaDB and external database servers",
    listOperation: "database.instance.list", createLabel: "Add Server",
    icon: "database", nameField: "id", statusField: "state",
    metaFields: [{ key: "host", label: "Host" }, { key: "port", label: "Port" }, { key: "version", label: "Version" }],
    emptyTitle: "No database servers", emptyBody: "The local MariaDB server will appear here. You can also connect external database servers.",
    scope: "installation",
  },
  packages: {
    title: "Hosting Plans", subtitle: "Resource limits for different account types",
    listOperation: "identity.plan.list", createLabel: "New Plan",
    icon: "package", nameField: "name", statusField: "state",
    metaFields: [{ key: "disk_bytes", label: "Disk" }, { key: "bandwidth_bytes", label: "Transfer" }, { key: "max_sites", label: "Websites" }],
    emptyTitle: "No hosting plans", emptyBody: "Create plans to control how much disk, bandwidth, and websites each account gets.",
  },
  "mail-queue": {
    title: "Mail Queue", subtitle: "Emails waiting to be delivered",
    listOperation: "mail.queue.list",
    icon: "mail", nameField: "id", statusField: "state",
    metaFields: [{ key: "recipient", label: "To" }, { key: "attempts", label: "Attempts" }, { key: "last_error", label: "Last error" }],
    emptyTitle: "Mail queue is empty", emptyBody: "All emails have been delivered. Pending or failed deliveries will appear here.",
  },
  audit: {
    title: "Activity Log", subtitle: "Who did what, when",
    listOperation: "audit.event.list",
    icon: "file", nameField: "id", subtitleField: "action",
    metaFields: [{ key: "actor", label: "By" }, { key: "created_at", label: "When" }],
    emptyTitle: "No activity", emptyBody: "Actions taken in the panel will be recorded here.",
  },
  "maintenance-windows": {
    title: "Maintenance", subtitle: "Scheduled maintenance windows",
    listOperation: "maintenance.window.list", createLabel: "Schedule Maintenance",
    icon: "clock", nameField: "id", subtitleField: "description",
    statusField: "state",
    metaFields: [{ key: "starts_at", label: "Starts" }, { key: "duration", label: "Duration" }],
    emptyTitle: "No maintenance scheduled", emptyBody: "Schedule maintenance windows for updates that might briefly interrupt service.",
  },
  "reboot-control": {
    title: "Restart Server", subtitle: "Planned server restarts",
    listOperation: "reboot.control.status",
    icon: "server", nameField: "id", statusField: "state",
    metaFields: [{ key: "phase", label: "Phase" }, { key: "boot_id", label: "Boot ID" }],
    emptyTitle: "No restart in progress", emptyBody: "Use this to safely restart the server with minimal downtime.",
    scope: "installation",
  },
  fleet: {
    title: "Servers", subtitle: "Connected CyberPanel servers",
    listOperation: "fleet.node.list", createLabel: "Add Server",
    icon: "server", nameField: "hostname", statusField: "state",
    metaFields: [{ key: "address", label: "Address" }, { key: "role", label: "Role" }],
    emptyTitle: "Single server", emptyBody: "You're running a single server. Add more servers for high availability.",
    scope: "installation",
  },
  integrations: {
    title: "Connections", subtitle: "Third-party services",
    listOperation: "integrations.provider.list", createLabel: "Add Connection",
    icon: "globe", nameField: "name", statusField: "state",
    metaFields: [{ key: "type", label: "Type" }],
    emptyTitle: "No connections", emptyBody: "Connect external services like CloudFlare, S3 storage, or SMTP relays.",
  },
  invitations: {
    title: "Invitations", subtitle: "Pending user invites",
    listOperation: "identity.invitation.list", createLabel: "Invite User",
    icon: "user", nameField: "email", statusField: "state",
    metaFields: [{ key: "role", label: "Role" }, { key: "expires_at", label: "Expires" }],
    emptyTitle: "No pending invitations", emptyBody: "Invite team members by email and they'll get a link to create their account.",
  },
  "product-updates": {
    title: "CyberPanel Updates", subtitle: "Panel software versions",
    listOperation: "product.update.status",
    icon: "cloud", nameField: "version", statusField: "state",
    metaFields: [{ key: "channel", label: "Channel" }, { key: "released_at", label: "Released" }],
    emptyTitle: "Up to date", emptyBody: "You're running the latest version of CyberPanel.",
    scope: "installation",
  },
  "package-maintenance": {
    title: "System Updates", subtitle: "OS package updates",
    listOperation: "package.maintenance.status",
    icon: "cloud", nameField: "name", statusField: "state",
    metaFields: [{ key: "installed_version", label: "Installed" }, { key: "candidate_version", label: "Available" }],
    emptyTitle: "No updates available", emptyBody: "System packages are up to date. Available updates will appear here.",
    scope: "installation",
  },
  "alert-rules": {
    title: "Alert Rules", subtitle: "When to send notifications",
    listOperation: "observability.alert.rule.list", createLabel: "New Rule",
    icon: "bell", nameField: "name", statusField: "state",
    metaFields: [{ key: "condition", label: "When" }, { key: "severity", label: "Severity" }],
    emptyTitle: "No alert rules", emptyBody: "Create rules to get notified when CPU, disk, or other resources cross a threshold.",
  },
  "mail-campaigns": {
    title: "Newsletters", subtitle: "Email campaigns",
    listOperation: "marketing.campaign.list", createLabel: "New Newsletter",
    icon: "mail", nameField: "name", statusField: "state",
    metaFields: [{ key: "recipient_count", label: "Recipients" }, { key: "sent_count", label: "Sent" }],
    emptyTitle: "No newsletters", emptyBody: "Create email campaigns to send updates to your subscribers.",
  },
  "mail-subscribers": {
    title: "Subscribers", subtitle: "Email list contacts",
    listOperation: "marketing.subscriber.list", createLabel: "Add Subscriber",
    icon: "users", nameField: "email", statusField: "state",
    metaFields: [{ key: "lists", label: "Lists" }, { key: "verified", label: "Verified" }],
    emptyTitle: "No subscribers", emptyBody: "Add email subscribers or import a list to start sending newsletters.",
  },
  "mail-templates": {
    title: "Email Templates", subtitle: "Reusable newsletter designs",
    listOperation: "marketing.template.list", createLabel: "New Template",
    icon: "file", nameField: "name", statusField: "state",
    metaFields: [{ key: "updated_at", label: "Updated" }],
    emptyTitle: "No templates", emptyBody: "Create email templates to reuse designs across campaigns.",
  },
  "mail-telemetry": {
    title: "Email Analytics", subtitle: "Delivery and authentication stats",
    listOperation: "mail.telemetry.statistics",
    icon: "file", nameField: "name", statusField: "state",
    metaFields: [{ key: "delivered", label: "Delivered" }, { key: "bounced", label: "Bounced" }],
    emptyTitle: "No email analytics", emptyBody: "Delivery statistics will appear here once you send emails.",
  },
  "mail-abuse": {
    title: "Abuse Alerts", subtitle: "Suspicious email activity",
    listOperation: "mail.abuse.finding.list",
    icon: "shield", nameField: "id", statusField: "state",
    metaFields: [{ key: "kind", label: "Type" }, { key: "observed_at", label: "Detected" }],
    emptyTitle: "No abuse alerts", emptyBody: "Suspicious email activity like brute force or flooding will be flagged here.",
  },
  "mail-abuse-actions": {
    title: "Abuse Actions", subtitle: "Review and respond to abuse alerts",
    listOperation: "mail.abuse.intent.list",
    icon: "shield", nameField: "id", statusField: "state",
    metaFields: [{ key: "action", label: "Action" }, { key: "created_at", label: "Created" }],
    emptyTitle: "No pending actions", emptyBody: "Proposed ban and allowlist actions will appear here for review.",
  },
  "mail-log-policies": {
    title: "Log Settings", subtitle: "Email log retention and privacy",
    listOperation: "mail.telemetry.policy.list", createLabel: "New Policy",
    icon: "lock", nameField: "id", statusField: "state",
    metaFields: [{ key: "retention_days", label: "Keep for" }],
    emptyTitle: "No log policies", emptyBody: "Set how long to keep email delivery logs before automatic deletion.",
  },
  "malware-scans": {
    title: "Malware Scans", subtitle: "Security scan history",
    listOperation: "security.malware.scan.list",
    icon: "bug", nameField: "id", statusField: "state",
    metaFields: [{ key: "started_at", label: "Started" }, { key: "findings", label: "Findings" }],
    emptyTitle: "No scans yet", emptyBody: "Run a malware scan to check your website files for threats.",
  },
  "malware-quarantine": {
    title: "Quarantine", subtitle: "Isolated threat files",
    listOperation: "security.malware.quarantine.list",
    icon: "bug", nameField: "id", statusField: "state",
    metaFields: [{ key: "threat", label: "Threat" }, { key: "quarantined_at", label: "Quarantined" }],
    emptyTitle: "Quarantine is empty", emptyBody: "Files detected as threats during scans will be isolated here.",
  },
  "malware-remediation": {
    title: "Threat Fixes", subtitle: "Malware cleanup actions",
    listOperation: "security.malware.remediation.list",
    icon: "bug", nameField: "id", statusField: "state",
    metaFields: [{ key: "action", label: "Action" }, { key: "status", label: "Status" }],
    emptyTitle: "No threat fixes needed", emptyBody: "When malware is found, cleanup actions will appear here.",
  },
  "installed-packages": {
    title: "Installed Packages", subtitle: "System software versions",
    listOperation: "package.installed.list",
    icon: "package", nameField: "name",
    metaFields: [{ key: "installed_version", label: "Version" }, { key: "architecture", label: "Arch" }],
    emptyTitle: "No packages listed", emptyBody: "Installed system packages will appear here.",
    scope: "installation",
  },
};

// Map route paths to config keys
export const routeToConfig: Record<string, string> = {
  "/redis": "redis",
  "/database-instances": "database-instances",
  "/packages": "packages",
  "/mail/queue": "mail-queue",
  "/audit": "audit",
  "/maintenance-windows": "maintenance-windows",
  "/reboot-control": "reboot-control",
  "/fleet": "fleet",
  "/integrations": "integrations",
  "/invitations": "invitations",
  "/product-updates": "product-updates",
  "/package-maintenance": "package-maintenance",
  "/alert-rules": "alert-rules",
  "/mail/campaigns": "mail-campaigns",
  "/mail/subscribers": "mail-subscribers",
  "/mail/templates": "mail-templates",
  "/mail/telemetry": "mail-telemetry",
  "/mail/abuse": "mail-abuse",
  "/mail/abuse-actions": "mail-abuse-actions",
  "/mail/log-policies": "mail-log-policies",
  "/security/malware": "malware-scans",
  "/security/malware/scans": "malware-scans",
  "/security/malware/quarantine": "malware-quarantine",
  "/security/malware/remediation": "malware-remediation",
  "/packages/installed": "installed-packages",
};

export function adminConfigFor(path: string): CardPageConfig | null {
  const key = routeToConfig[path];
  return key ? adminPageConfigs[key] ?? null : null;
}
