package cpanel

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"crypto/x509"
	"encoding/hex"
	"encoding/pem"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/aonsyed/cyberpanel/platform/internal/migration/cyberpanel"
)

var grantPattern=regexp.MustCompile(`(?i)^\s*GRANT\s+(.+?)\s+ON\s+` + "`?([^`\\s.]+)`?" + `\.\*\s+TO\s+'([^']+)'@'[^']+'(?:\s+IDENTIFIED\s+BY(?:\s+PASSWORD)?\s+'([^']+)')?`)
var createUserPattern=regexp.MustCompile(`(?i)^\s*CREATE\s+USER\s+'([^']+)'@'[^']+'(?:\s+IDENTIFIED(?:\s+(?:WITH|VIA)\s+[^\s]+)?(?:\s+(?:BY(?:\s+PASSWORD)?|AS|USING))?\s+'([^']+)')`)

func(s *ArchiveSource)collectDatabases(archive approvedArchive,index archiveIndex,sites []cyberpanel.SiteRecord,secrets map[SecretRef][]byte)([]cyberpanel.DatabaseRecord,error){
	mainSite:=mainSiteID(sites);grants,passwords,err:=parseMySQLAccountMetadata(index.metadata["mysql.sql"]);if err!=nil{return nil,err};defer func(){for username,password:=range passwords{wipe(password);delete(passwords,username)}}();values:=[]cyberpanel.DatabaseRecord{}
	for _,entry:=range index.entries{if entry.typeflag!=0&&entry.typeflag!='0'{continue};if !strings.HasPrefix(entry.logicalName,"mysql/")||!strings.HasSuffix(entry.logicalName,".sql"){continue};name:=strings.TrimSuffix(strings.TrimPrefix(entry.logicalName,"mysql/"),".sql");if name==""||strings.Contains(name,"/")||strings.Contains(strings.ToLower(name),"roundcube"){continue};sourceID:="database:"+safeOpaque(archive.accountID)+":"+safeOpaque(name);artifactID:=ArtifactID("cpanel-database-dump:"+safeOpaque(archive.accountID)+":"+safeOpaque(name));source:=&archiveArtifactSource{archive:archive,spec:archiveArtifactSpec{exact:entry.logicalName,mediaType:"application/sql",encryptionDomain:"database-dump"},limits:s.limits};if err:=s.artifacts.Register(artifactID,source);err!=nil{return nil,err};record:=cyberpanel.DatabaseRecord{SourceID:sourceID,SiteSourceID:mainSite,Name:name,Charset:"utf8mb4",Collation:"utf8mb4_unicode_ci",DumpArtifact:artifactID};principalIndexes:=map[string]int{};for _,grant:=range grants[name]{password:=passwords[grant.username];ref:=SecretRef("");if len(password)>0{ref=SecretRef("cpanel-database-password:"+safeOpaque(archive.accountID)+":"+safeOpaque(grant.username));secrets[ref]=append([]byte(nil),password...)};if existing,duplicate:=principalIndexes[strings.ToLower(grant.username)];duplicate{record.Principals[existing].GrantSets=appendUniqueString(record.Principals[existing].GrantSets,grant.grants);if record.Principals[existing].Password==""&&ref!=""{record.Principals[existing].Password=ref};continue};principalIndexes[strings.ToLower(grant.username)]=len(record.Principals);record.Principals=append(record.Principals,cyberpanel.DatabasePrincipalRecord{Name:grant.username,GrantSets:[]string{grant.grants},Password:ref})};values=append(values,record)}
	sort.Slice(values,func(i,j int)bool{return values[i].SourceID<values[j].SourceID});return values,nil
}

type databaseGrant struct{username,grants string}
func parseMySQLAccountMetadata(raw []byte)(map[string][]databaseGrant,map[string][]byte,error){grants:=map[string][]databaseGrant{};passwords:=map[string][]byte{};scanner:=bufio.NewScanner(bytes.NewReader(raw));buffer:=make([]byte,64<<10);scanner.Buffer(buffer,8<<20);for scanner.Scan(){line:=strings.TrimSpace(scanner.Text());if matches:=createUserPattern.FindStringSubmatch(line);len(matches)==3{username:=unescapeMySQLIdentifier(matches[1]);passwords[username]=append([]byte(nil),matches[2]...)};matches:=grantPattern.FindStringSubmatch(line);if len(matches)!=5{continue};database,username:=unescapeMySQLIdentifier(matches[2]),unescapeMySQLIdentifier(matches[3]);grants[database]=append(grants[database],databaseGrant{username:username,grants:strings.TrimSpace(matches[1])});if matches[4]!=""{passwords[username]=append([]byte(nil),matches[4]...)}};if err:=scanner.Err();err!=nil{for username,password:=range passwords{wipe(password);delete(passwords,username)};return nil,nil,err};return grants,passwords,nil}
func unescapeMySQLIdentifier(value string)string{var output strings.Builder;escaped:=false;for _,character:=range value{if escaped{output.WriteRune(character);escaped=false;continue};if character=='\\'{escaped=true;continue};output.WriteRune(character)};if escaped{output.WriteByte('\\')};return output.String()}
func appendUniqueString(values []string,value string)[]string{for _,existing:=range values{if existing==value{return values}};return append(values,value)}

func collectDNSZones(accountID string,index archiveIndex)([]cyberpanel.DNSZoneRecord,error){values:=[]cyberpanel.DNSZoneRecord{};for name,raw:=range index.metadata{if !strings.HasPrefix(name,"dnszones/")||!strings.HasSuffix(name,".db"){continue};zoneName:=normalizeHostname(strings.TrimSuffix(strings.TrimPrefix(name,"dnszones/"),".db"));if zoneName==""||strings.Contains(zoneName,"/"){return nil,ErrInvalid};recordSets,err:=parseBindZone(zoneName,raw);if err!=nil{return nil,err};values=append(values,cyberpanel.DNSZoneRecord{SourceID:"cpanel-dns-zone:"+safeOpaque(accountID)+":"+safeOpaque(zoneName),Name:zoneName,Mode:"native",RecordSets:recordSets})};sort.Slice(values,func(i,j int)bool{return values[i].Name<values[j].Name});return values,nil}

func(s *ArchiveSource)collectMail(archive approvedArchive,index archiveIndex,sites []cyberpanel.SiteRecord,secrets map[SecretRef][]byte)([]cyberpanel.MailDomainRecord,error){
	type mailboxKey struct{domain,user string};mailboxes:=map[mailboxKey]struct{}{};for _,entry:=range index.entries{if !strings.HasPrefix(entry.logicalName,"homedir/mail/"){continue};relative:=strings.TrimPrefix(entry.logicalName,"homedir/mail/");parts:=strings.Split(relative,"/");if len(parts)<3||!strings.Contains(parts[0],".")||parts[0]=="mailbox_format.cpanel"||strings.HasPrefix(parts[0],".")||strings.HasPrefix(parts[1],"."){continue};mailboxes[mailboxKey{domain:normalizeHostname(parts[0]),user:parts[1]}]=struct{}{}}
	format:="maildir";if strings.Contains(strings.ToLower(string(index.metadata["homedir/mail/mailbox_format.cpanel"])),"mdbox"){format="mdbox"}
	shadows:=map[string]map[string][]byte{};defer func(){for domain,mailboxes:=range shadows{for username,password:=range mailboxes{wipe(password);delete(mailboxes,username)};delete(shadows,domain)}}();for name,raw:=range index.metadata{if !strings.HasPrefix(name,"homedir/etc/")||!strings.HasSuffix(name,"/shadow"){continue};domain:=strings.TrimSuffix(strings.TrimPrefix(name,"homedir/etc/"),"/shadow");if strings.Contains(domain,"/"){continue};parsed,err:=parseShadow(raw);if err!=nil{return nil,err};shadows[normalizeHostname(domain)]=parsed}
	byDomain:=map[string]int{};domains:=[]cyberpanel.MailDomainRecord{};keys:=make([]mailboxKey,0,len(mailboxes));for key:=range mailboxes{keys=append(keys,key)};sort.Slice(keys,func(i,j int)bool{if keys[i].domain==keys[j].domain{return keys[i].user<keys[j].user};return keys[i].domain<keys[j].domain});for _,key:=range keys{domainIndex,exists:=byDomain[key.domain];if !exists{record:=cyberpanel.MailDomainRecord{SourceID:"cpanel-mail-domain:"+safeOpaque(archive.accountID)+":"+safeOpaque(key.domain),SiteSourceID:siteForHostname(sites,key.domain),Name:key.domain};domains=append(domains,record);domainIndex=len(domains)-1;byDomain[key.domain]=domainIndex};address:=strings.ToLower(key.user+"@"+key.domain);sourceID:="cpanel-mailbox:"+safeOpaque(archive.accountID)+":"+safeOpaque(address);artifactID:=ArtifactID("cpanel-mailbox-data:"+safeOpaque(archive.accountID)+":"+safeOpaque(address));prefix:="homedir/mail/"+key.domain+"/"+key.user+"/";source:=&archiveArtifactSource{archive:archive,spec:archiveArtifactSpec{prefix:prefix,tree:true,mediaType:"application/vnd.cyberpanel.migration.mailbox-"+format+"+tar",encryptionDomain:"mailbox-data"},limits:s.limits};if err:=s.artifacts.Register(artifactID,source);err!=nil{return nil,err};passwordRef:=SecretRef("");password:=shadows[key.domain][key.user];if len(password)>0{passwordRef=SecretRef("cpanel-mailbox-password:"+safeOpaque(archive.accountID)+":"+safeOpaque(address));secrets[passwordRef]=append([]byte(nil),password...)};domains[domainIndex].Mailboxes=append(domains[domainIndex].Mailboxes,cyberpanel.MailboxRecord{SourceID:sourceID,Address:address,Format:format,Password:passwordRef,DataArtifact:artifactID})}
	return domains,nil
}

func parseShadow(raw []byte)(map[string][]byte,error){values:=map[string][]byte{};scanner:=bufio.NewScanner(bytes.NewReader(raw));scanner.Buffer(make([]byte,4096),1<<20);for scanner.Scan(){line:=strings.TrimSpace(scanner.Text());if line==""||strings.HasPrefix(line,"#"){continue};parts:=strings.Split(line,":");if len(parts)<2||parts[0]==""||parts[1]==""||parts[1]=="!"||parts[1]=="!!"||parts[1]=="*"{continue};password:=parts[1];if !strings.HasPrefix(password,"{"){password="{CRYPT}"+password};values[parts[0]]=append([]byte(nil),password...)};if err:=scanner.Err();err!=nil{for username,password:=range values{wipe(password);delete(values,username)};return nil,err};return values,nil}

func(s *ArchiveSource)collectCertificates(accountID string,index archiveIndex,sites []cyberpanel.SiteRecord,secrets map[SecretRef][]byte)([]cyberpanel.CertificateRecord,error){values:=[]cyberpanel.CertificateRecord{};seen:=map[string]struct{}{};for name,raw:=range index.metadata{if !strings.HasPrefix(name,"apache_tls/"){continue};hostname:=normalizeHostname(strings.TrimPrefix(name,"apache_tls/"));if hostname==""||strings.Contains(hostname,"/"){continue};certificates,privateKey,parsed,err:=splitPEMBundle(raw);if err!=nil{return nil,err};if len(certificates)==0||len(privateKey)==0{wipe(privateKey);return nil,ErrInvalid};if err:=cyberpanel.ValidatePrivateKeyForCertificate(privateKey,parsed);err!=nil{wipe(privateKey);return nil,err};names,err:=cyberpanel.ConcreteCertificateNames(parsed,hostname);if err!=nil{wipe(privateKey);return nil,err};sourceID:="cpanel-certificate:"+safeOpaque(accountID)+":"+safeOpaque(hostname);if _,duplicate:=seen[sourceID];duplicate{wipe(privateKey);return nil,ErrInvalid};seen[sourceID]=struct{}{};certificateID:=ArtifactID(sourceID);if err:=s.artifacts.Register(certificateID,&bytesArtifactSource{value:certificates[0],mediaType:"application/pem-certificate-chain",encryptionDomain:"certificate-public"});err!=nil{wipe(privateKey);return nil,err};chainID:=ArtifactID("");if len(certificates)>1{chainID=ArtifactID("cpanel-certificate-chain:"+safeOpaque(accountID)+":"+safeOpaque(hostname));chain:=bytes.Join(certificates[1:],nil);if err:=s.artifacts.Register(chainID,&bytesArtifactSource{value:chain,mediaType:"application/pem-certificate-chain",encryptionDomain:"certificate-public"});err!=nil{wipe(privateKey);return nil,err}};privateRef:=SecretRef("cpanel-tls-private-key:"+safeOpaque(accountID)+":"+safeOpaque(hostname));secrets[privateRef]=append([]byte(nil),privateKey...);wipe(privateKey);issuer:=parsed.Issuer.String();values=append(values,cyberpanel.CertificateRecord{SourceID:sourceID,Names:names,CertificateArtifact:certificateID,ChainArtifact:chainID,PrivateKey:privateRef,Issuer:issuer,NotAfter:parsed.NotAfter});_ = sites};sort.Slice(values,func(i,j int)bool{return values[i].SourceID<values[j].SourceID});return values,nil}

func splitPEMBundle(raw []byte)([][]byte,[]byte,*x509.Certificate,error){certificates:=[][]byte{};privateKey:=[]byte{};remaining:=raw;var parsed *x509.Certificate;for len(remaining)>0{block,rest:=pem.Decode(remaining);if block==nil{if strings.TrimSpace(string(remaining))!=""{return nil,nil,nil,ErrInvalid};break};encoded:=pem.EncodeToMemory(block);switch block.Type{case"CERTIFICATE":certificate,err:=x509.ParseCertificate(block.Bytes);if err!=nil{return nil,nil,nil,err};if parsed==nil{parsed=certificate};certificates=append(certificates,encoded);case"RSA PRIVATE KEY","EC PRIVATE KEY","PRIVATE KEY","ENCRYPTED PRIVATE KEY":privateKey=append(privateKey,encoded...);default:return nil,nil,nil,ErrInvalid};remaining=rest};if parsed==nil&&len(certificates)>0{return nil,nil,nil,ErrInvalid};return certificates,privateKey,parsed,nil}

func collectCronSchedules(accountID string,index archiveIndex,sites []cyberpanel.SiteRecord)([]cyberpanel.ScheduleRecord,error){values:=[]cyberpanel.ScheduleRecord{};siteID:=mainSiteID(sites);keys:=[]string{};for name:=range index.metadata{if strings.HasPrefix(name,"cron/"){keys=append(keys,name)}};sort.Strings(keys);counter:=0;for _,name:=range keys{scanner:=bufio.NewScanner(bytes.NewReader(index.metadata[name]));scanner.Buffer(make([]byte,4096),1<<20);timezone:="source-local";for scanner.Scan(){line:=strings.TrimSpace(scanner.Text());if line==""||strings.HasPrefix(line,"#"){continue};if value,present:=cronTimezone(line);present{timezone=value;continue};if isCronEnvironment(line){continue};expression,command,present,parseErr:=cyberpanel.ParseLegacyCronEntry(line);if parseErr!=nil{return nil,parseErr};if !present{continue};sum:=sha256.Sum256([]byte(command));counter++;values=append(values,cyberpanel.ScheduleRecord{SourceID:"cpanel-cron:"+safeOpaque(accountID)+":"+hex.EncodeToString(sum[:12])+":"+strconv.Itoa(counter),SiteSourceID:siteID,Kind:"legacy-command",Expression:expression,Timezone:timezone,InvocationID:"legacy_invocation_"+hex.EncodeToString(sum[:16]),Enabled:true})};if err:=scanner.Err();err!=nil{return nil,err}};return values,nil}
func isCronEnvironment(value string)bool{equals:=strings.IndexByte(value,'=');space:=strings.IndexAny(value," \t");return equals>0&&(space<0||equals<space)}
func cronTimezone(value string)(string,bool){equals:=strings.IndexByte(value,'=');if equals<=0||!strings.EqualFold(strings.TrimSpace(value[:equals]),"CRON_TZ"){return "",false};timezone:=strings.TrimSpace(value[equals+1:]);if len(timezone)>=2&&((timezone[0]=='"'&&timezone[len(timezone)-1]=='"')||(timezone[0]=='\''&&timezone[len(timezone)-1]=='\'')){timezone=timezone[1:len(timezone)-1]};if timezone==""||len(timezone)>255||strings.ContainsAny(timezone,"\r\n\x00"){return "",false};return timezone,true}

func collectCPanelCredentials(accountID string,index archiveIndex,sites []cyberpanel.SiteRecord,accountUser string,secrets map[SecretRef][]byte)([]cyberpanel.CredentialRecord,error){_ = secrets;siteID:=mainSiteID(sites);rootRelative:="";for _,site:=range sites{if site.SourceID==siteID{rootRelative=site.DocumentRootRelative;break}};if siteID==""||rootRelative==""{return nil,ErrInvalid};values:=[]cyberpanel.CredentialRecord{};seen:=map[string]struct{}{};for _,name:=range []string{"homedir/.ssh/authorized_keys","homedir/.ssh/authorized_keys2"}{raw:=index.metadata[name];if len(raw)==0{continue};keys,err:=cyberpanel.ParseAuthorizedKeys(raw);if err!=nil{return nil,err};for _,key:=range keys{if _,duplicate:=seen[key.Fingerprint];duplicate{continue};seen[key.Fingerprint]=struct{}{};label:=key.Label;if label==""{label=accountUser};if label==""{label=key.Fingerprint[:16]};values=append(values,cyberpanel.CredentialRecord{SourceID:"cpanel-ssh-key:"+safeOpaque(accountID)+":"+key.Fingerprint[:32],SiteSourceID:siteID,Kind:"ssh-public-key",Label:label,RootRelative:rootRelative,PublicKey:key.PublicKey})}};return values,nil}

func mainSiteID(sites []cyberpanel.SiteRecord)string{for _,site:=range sites{if site.ParentSourceID==""{return site.SourceID}};return""}
func siteForHostname(sites []cyberpanel.SiteRecord,hostname string)string{hostname=normalizeHostname(hostname);for _,site:=range sites{if normalizeHostname(site.PrimaryHostname)==hostname{return site.SourceID}};for _,site:=range sites{if site.ParentSourceID==""{return site.SourceID}};return""}

type bindRecord struct{name,recordType string;ttl uint32;value string}
func parseBindZone(origin string,raw []byte)([]cyberpanel.DNSRecordSet,error){scanner:=bufio.NewScanner(bytes.NewReader(raw));scanner.Buffer(make([]byte,64<<10),8<<20);defaultTTL:=uint32(3600);lastOwner:="@";pending:="";pendingOwnerExplicit:=true;records:=[]bindRecord{};for scanner.Scan(){physical:=scanner.Text();trimmed:=strings.TrimSpace(stripZoneComment(physical));if trimmed==""{continue};if pending!=""{pending+=" "+trimmed}else{pending=trimmed;pendingOwnerExplicit=len(physical)>0&&(physical[0]!=' '&&physical[0]!='\t')};balance:=zoneParenthesisBalance(pending);if balance>0{continue};if balance<0{return nil,ErrInvalid};line:=strings.ReplaceAll(strings.ReplaceAll(pending,"("," "),")"," ");pending="";tokens:=zoneTokens(line);if len(tokens)==0{continue};if strings.EqualFold(tokens[0],"$ORIGIN"){if len(tokens)!=2{return nil,ErrInvalid};origin=normalizeHostname(tokens[1]);if origin==""{return nil,ErrInvalid};continue};if strings.EqualFold(tokens[0],"$TTL"){if len(tokens)!=2{return nil,ErrInvalid};ttl,ok:=parseTTL(tokens[1]);if !ok||ttl==0{return nil,ErrInvalid};defaultTTL=ttl;continue};if strings.HasPrefix(tokens[0],"$"){return nil,ErrInvalid};owner:=lastOwner;cursor:=0;if pendingOwnerExplicit{owner=tokens[0];lastOwner=owner;cursor++};ttl:=defaultTTL;if cursor<len(tokens){if parsed,ok:=parseTTL(tokens[cursor]);ok{ttl=parsed;cursor++}};if cursor<len(tokens)&&strings.EqualFold(tokens[cursor],"IN"){cursor++};if cursor>=len(tokens){continue};recordType:=strings.ToUpper(tokens[cursor]);cursor++;if !knownDNSRecordType(recordType)||cursor>=len(tokens){continue};name:=absoluteDNSName(owner,origin);value:=normalizeRData(recordType,tokens[cursor:],origin);records=append(records,bindRecord{name:name,recordType:recordType,ttl:ttl,value:value})};if err:=scanner.Err();err!=nil{return nil,err};if pending!=""{return nil,ErrInvalid};sets:=map[string]*cyberpanel.DNSRecordSet{};for _,record:=range records{key:=record.name+"\x00"+record.recordType;set:=sets[key];if set==nil{set=&cyberpanel.DNSRecordSet{Name:record.name,Type:record.recordType,TTL:record.ttl};sets[key]=set}else if record.ttl>0&&record.ttl<set.TTL{set.TTL=record.ttl};set.Values=append(set.Values,record.value)};values:=make([]cyberpanel.DNSRecordSet,0,len(sets));for _,set:=range sets{sort.Strings(set.Values);values=append(values,*set)};sort.Slice(values,func(i,j int)bool{return values[i].Name+values[i].Type+strconv.FormatUint(uint64(values[i].TTL),10)<values[j].Name+values[j].Type+strconv.FormatUint(uint64(values[j].TTL),10)});return values,nil}

func stripZoneComment(value string)string{quoted:=false;escaped:=false;for index,character:=range value{if escaped{escaped=false;continue};if character=='\\'{escaped=true;continue};if character=='"'{quoted=!quoted;continue};if character==';'&&!quoted{return value[:index]}};return value}
func zoneParenthesisBalance(value string)int{balance:=0;quoted:=false;escaped:=false;for _,character:=range value{if escaped{escaped=false;continue};if character=='\\'{escaped=true;continue};if character=='"'{quoted=!quoted;continue};if !quoted{if character=='('{balance++};if character==')'{balance--}}};return balance}
func zoneTokens(value string)[]string{tokens:=[]string{};var current strings.Builder;quoted:=false;escaped:=false;flush:=func(){if current.Len()>0{tokens=append(tokens,current.String());current.Reset()}};for _,character:=range value{if escaped{current.WriteRune(character);escaped=false;continue};if character=='\\'{current.WriteRune(character);escaped=true;continue};if character=='"'{current.WriteRune(character);quoted=!quoted;continue};if !quoted&&(character==' '||character=='\t'||character=='\r'||character=='\n'){flush();continue};current.WriteRune(character)};flush();return tokens}
func parseTTL(value string)(uint32,bool){multiplier:=uint64(1);upper:=strings.ToUpper(value);if len(upper)>1{switch upper[len(upper)-1]{case'S':multiplier=1;upper=upper[:len(upper)-1];case'M':multiplier=60;upper=upper[:len(upper)-1];case'H':multiplier=3600;upper=upper[:len(upper)-1];case'D':multiplier=86400;upper=upper[:len(upper)-1];case'W':multiplier=604800;upper=upper[:len(upper)-1]}};parsed,err:=strconv.ParseUint(upper,10,32);if err!=nil||parsed*multiplier>1<<32-1{return 0,false};return uint32(parsed*multiplier),true}
func absoluteDNSName(value,origin string)string{value=strings.TrimSpace(value);if value=="@"||value==""{return origin};if strings.HasSuffix(value,"."){return normalizeHostname(value)};return normalizeHostname(value+"."+origin)}
func knownDNSRecordType(value string)bool{switch value{case"A","AAAA","CAA","CNAME","DNAME","DS","HINFO","HTTPS","LOC","MX","NAPTR","NS","PTR","SOA","SRV","SSHFP","SVCB","TLSA","TXT":return true};return false}
func normalizeRData(recordType string,tokens []string,origin string)string{if len(tokens)==0{return""};switch recordType{case"CNAME","DNAME","NS","PTR":tokens[0]=absoluteDNSName(tokens[0],origin);case"MX":if len(tokens)>1{tokens[1]=absoluteDNSName(tokens[1],origin)};case"SRV":if len(tokens)>3{tokens[3]=absoluteDNSName(tokens[3],origin)};case"SOA":if len(tokens)>1{tokens[0]=absoluteDNSName(tokens[0],origin);tokens[1]=absoluteDNSName(tokens[1],origin)}};return strings.Join(tokens," ")}
