//go:build linux

package apps

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"syscall"
	"time"
)

const linuxApplicationSitesRoot = "/var/lib/cyberpanel/sites"
const linuxWPCLIBinary = "/usr/bin/wp"

type LinuxApplicationSiteBinding struct{SiteKey string;UID uint32;GID uint32;Generation uint64}
type LinuxApplicationSiteResolver interface{ResolveApplicationSite(context.Context,SiteID)(LinuxApplicationSiteBinding,error)}
type LinuxApplicationSiteResolverFunc func(context.Context,SiteID)(LinuxApplicationSiteBinding,error)
func(function LinuxApplicationSiteResolverFunc)ResolveApplicationSite(ctx context.Context,id SiteID)(LinuxApplicationSiteBinding,error){return function(ctx,id)}

type LinuxApplicationSecretSource interface{ApplicationSecret(context.Context,SecretRef,TenantID,SiteID,InstallationID,string)([]byte,error)}

type LinuxApplicationRuntime struct{Resolver LinuxApplicationSiteResolver;Secrets LinuxApplicationSecretSource;WPCLI string;Curl string;Tar string}

func NewLinuxApplicationRuntime(resolver LinuxApplicationSiteResolver,secrets LinuxApplicationSecretSource)(*LinuxApplicationRuntime,error){if resolver==nil||secrets==nil{return nil,ErrInvalid};for _,path:=range []string{linuxWPCLIBinary,"/usr/bin/curl","/usr/bin/tar","/usr/bin/cp","/usr/bin/rsync","/usr/bin/rm"}{info,err:=os.Lstat(path);if err!=nil||!info.Mode().IsRegular()||info.Mode()&os.ModeSymlink!=0||info.Mode().Perm()&0022!=0{return nil,fmt.Errorf("untrusted application runtime executable %s",path)}};return &LinuxApplicationRuntime{Resolver:resolver,Secrets:secrets,WPCLI:linuxWPCLIBinary,Curl:"/usr/bin/curl",Tar:"/usr/bin/tar"},nil}

func(runtime *LinuxApplicationRuntime)Handle(ctx context.Context,operation linuxApplicationOperation,payload []byte)([]byte,error){
	encode:=func(value any)([]byte,error){return json.Marshal(value)}
	switch operation{
	case applicationInstall:var value InstallExecution;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};result,err:=runtime.Install(ctx,value);if err!=nil{return nil,err};return encode(result)
	case applicationDiscover:var value DiscoveryExecution;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};candidates,receipt,err:=runtime.Discover(ctx,value);if err!=nil{return nil,err};return encode(discoverResult{candidates,receipt})
	case applicationAdopt:var value AdoptExecution;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};result,err:=runtime.Adopt(ctx,value);if err!=nil{return nil,err};return encode(result)
	case applicationInspect:var value InspectExecution;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};inventory,health,receipt,err:=runtime.Inspect(ctx,value);if err!=nil{return nil,err};return encode(inspectResult{inventory,health,receipt})
	case applicationRepair:var value RepairExecution;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};result,err:=runtime.Repair(ctx,value);if err!=nil{return nil,err};return encode(result)
	case applicationPrepareUpdate,applicationApplyUpdate,applicationProbeUpdate:var value UpdateExecution;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};if operation==applicationPrepareUpdate{result,err:=runtime.PrepareUpdate(ctx,value);if err!=nil{return nil,err};return encode(result)};if operation==applicationApplyUpdate{result,err:=runtime.ApplyUpdate(ctx,value);if err!=nil{return nil,err};return encode(result)};health,receipt,err:=runtime.ProbeUpdate(ctx,value);if err!=nil{return nil,err};return encode(struct{Health HealthObservation `json:"health"`;Receipt ExecutionReceipt `json:"receipt"`}{health,receipt})
	case applicationPromote,applicationRollback:var value PromotionExecution;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};if operation==applicationPromote{result,err:=runtime.Promote(ctx,value);if err!=nil{return nil,err};return encode(result)};result,err:=runtime.Rollback(ctx,value);if err!=nil{return nil,err};return encode(result)
	case applicationQuarantine,applicationRemove:var value RemovalExecution;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};if operation==applicationQuarantine{result,err:=runtime.Quarantine(ctx,value);if err!=nil{return nil,err};return encode(result)};result,err:=runtime.Remove(ctx,value);if err!=nil{return nil,err};return encode(result)
	case applicationWPCLI:var value WPCLIInvocation;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};result,err:=runtime.InvokeWPCLI(ctx,value);if err!=nil{return nil,err};return encode(result)
	case applicationWPComponent:var value ComponentMutation;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};inventory,receipt,err:=runtime.MutateComponent(ctx,value);if err!=nil{return nil,err};return encode(wpComponentResult{inventory,receipt})
	case applicationWPSettings:var value WordPressSettingsMutation;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};settings,receipt,err:=runtime.ApplySettings(ctx,value);if err!=nil{return nil,err};return encode(wpSettingsResult{settings,receipt})
	case applicationLSCacheConfigure:var value CacheMutation;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};policy,receipt,err:=runtime.ConfigureLSCache(ctx,value);if err!=nil{return nil,err};return encode(lsCacheResult{policy,receipt})
	case applicationLSCachePurge:var value CacheMutation;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};result,err:=runtime.PurgeLSCache(ctx,value);if err!=nil{return nil,err};return encode(result)
	case applicationAutologinInstall,applicationAutologinRemove:var value AutologinBridgeRequest;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};if operation==applicationAutologinInstall{result,err:=runtime.InstallAutologinBridge(ctx,value);if err!=nil{return nil,err};return encode(result)};result,err:=runtime.RemoveAutologinBridge(ctx,value);if err!=nil{return nil,err};return encode(result)
	case applicationRouteCreate,applicationRouteRemove,applicationRouteActivate,applicationRouteRestore:var value applicationRouteRequest;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};if operation==applicationRouteCreate{result,err:=runtime.CreateShadowRoute(ctx,value.SiteID,value.InstallationID,value.ReleaseID);if err!=nil{return nil,err};return encode(result)};if operation==applicationRouteRemove{if err:=runtime.RemoveShadowRoute(ctx,value.SiteID,value.InstallationID,value.ReleaseID);err!=nil{return nil,err};return encode(nil)};if operation==applicationRouteActivate{if err:=runtime.ActivateReleaseRoute(ctx,value.SiteID,value.InstallationID,value.ReleaseID,value.Shadow);err!=nil{return nil,err};return encode(nil)};if err:=runtime.RestoreReleaseRoute(ctx,value.SiteID,value.InstallationID,value.ReleaseID);err!=nil{return nil,err};return encode(nil)
	case applicationSnapshotCreate:var value SnapshotRequest;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};result,err:=runtime.CreateApplicationSnapshot(ctx,value);if err!=nil{return nil,err};return encode(result)
	case applicationSnapshotVerify,applicationSnapshotRelease:var value SnapshotID;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};if operation==applicationSnapshotVerify{if err:=runtime.VerifyApplicationSnapshot(ctx,value);err!=nil{return nil,err};return encode(nil)};if err:=runtime.ReleaseApplicationSnapshot(ctx,value);err!=nil{return nil,err};return encode(nil)
	case applicationRecoveryCreate:var value applicationRecoveryInput;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};result,err:=runtime.CreateRecoveryPoint(ctx,value);if err!=nil{return nil,err};return encode(result)
	case applicationRecoveryVerify:var value RecoveryPointID;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};if err:=runtime.VerifyRecoveryPoint(ctx,value);err!=nil{return nil,err};return encode(nil)
	case applicationCloneCreate,applicationCloneProbe:var value CloneExecution;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};if operation==applicationCloneCreate{result,err:=runtime.CreateClone(ctx,value);if err!=nil{return nil,err};return encode(result)};health,receipt,err:=runtime.ProbeClone(ctx,value);if err!=nil{return nil,err};return encode(applicationStagingHealthResult{health,receipt})
	case applicationSyncApply,applicationSyncRewrite,applicationSyncProbe,applicationSyncRollback:var value SyncExecution;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};if operation==applicationSyncApply{result,err:=runtime.ApplySync(ctx,value);if err!=nil{return nil,err};return encode(result)};if operation==applicationSyncRewrite{result,err:=runtime.RewriteApplicationIdentity(ctx,value);if err!=nil{return nil,err};return encode(result)};if operation==applicationSyncRollback{result,err:=runtime.RollbackSync(ctx,value);if err!=nil{return nil,err};return encode(result)};health,receipt,err:=runtime.ProbeSynchronizedApplication(ctx,value);if err!=nil{return nil,err};return encode(applicationStagingHealthResult{health,receipt})
	case applicationCloneDelete:var value StagingDeleteExecution;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};result,err:=runtime.DeleteClone(ctx,value);if err!=nil{return nil,err};return encode(result)
	case applicationResolveScope:var value ApplicationInstallation;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};result,err:=runtime.ResolveExecutionScope(ctx,value);if err!=nil{return nil,err};return encode(result)
	case applicationResolveSite:var value struct{TenantID TenantID `json:"tenant_id"`;SiteID SiteID `json:"site_id"`};if decodeLinuxApplicationPayload(payload,&value)!=nil||!validID(string(value.TenantID))||!validID(string(value.SiteID)){return nil,ErrInvalid};binding,err:=runtime.Resolver.ResolveApplicationSite(ctx,value.SiteID);if err!=nil{return nil,err};if binding.UID<1000||binding.GID!=binding.UID||binding.Generation==0||binding.SiteKey==""{return nil,ErrPolicyDenied};return encode(SiteExecutionScope{TenantID:value.TenantID,SiteID:value.SiteID,SiteUID:SiteUID(binding.UID),Root:MustRelativePath(""),IsolationProfile:"application-runtime",ResourceGeneration:binding.Generation})
	case applicationSecurityScan:var value ScanRequest;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};result,err:=runtime.Scan(ctx,value,nil);if err!=nil{return nil,err};return encode(result)
	case applicationRemediationApply,applicationRemediationRollback:var value RemediationExecution;if decodeLinuxApplicationPayload(payload,&value)!=nil{return nil,ErrInvalid};if operation==applicationRemediationApply{result,err:=runtime.ApplyRemediation(ctx,value);if err!=nil{return nil,err};return encode(result)};result,err:=runtime.RollbackRemediation(ctx,value);if err!=nil{return nil,err};return encode(result)
	default:return nil,ErrUnsupported
	}
}

func(runtime *LinuxApplicationRuntime)ResolveExecutionScope(ctx context.Context,installation ApplicationInstallation)(SiteExecutionScope,error){
	if runtime==nil||installation.Validate(time.Now().UTC())!=nil{return SiteExecutionScope{},ErrInvalid};binding,err:=runtime.Resolver.ResolveApplicationSite(ctx,installation.SiteID);if err!=nil{return SiteExecutionScope{},err};if SiteUID(binding.UID)!=installation.SiteUID{return SiteExecutionScope{},ErrPolicyDenied};scope:=SiteExecutionScope{TenantID:installation.TenantID,SiteID:installation.SiteID,SiteUID:installation.SiteUID,Root:installation.Root,IsolationProfile:"application-runtime",ResourceGeneration:binding.Generation};if _,err=runtime.resolve(ctx,scope);err!=nil{return SiteExecutionScope{},err};return scope,nil
}

func decodeLinuxApplicationPayload(payload []byte,value any)error{decoder:=json.NewDecoder(bytes.NewReader(payload));decoder.DisallowUnknownFields();if err:=decoder.Decode(value);err!=nil{return err};if decoder.Decode(&struct{}{})!=io.EOF{return ErrInvalid};return nil}

type linuxApplicationScope struct{binding LinuxApplicationSiteBinding;root string}
func(runtime *LinuxApplicationRuntime)resolve(ctx context.Context,scope SiteExecutionScope)(linuxApplicationScope,error){if runtime==nil||runtime.Resolver==nil||scope.Validate()!=nil{return linuxApplicationScope{},ErrInvalid};binding,err:=runtime.Resolver.ResolveApplicationSite(ctx,scope.SiteID);if err!=nil{return linuxApplicationScope{},err};if binding.SiteKey==""||!strings.HasPrefix(binding.SiteKey,"s-")||binding.UID<1000||binding.GID!=binding.UID||binding.Generation!=scope.ResourceGeneration||SiteUID(binding.UID)!=scope.SiteUID{return linuxApplicationScope{},ErrPolicyDenied};generationRoot:=filepath.Join(linuxApplicationSitesRoot,binding.SiteKey,"roots","g"+strconv.FormatUint(binding.Generation,10));root:=filepath.Join(generationRoot,"releases","current");if !scope.Root.IsRoot(){root=filepath.Join(root,filepath.FromSlash(scope.Root.String()))};clean:=filepath.Clean(root);if clean!=generationRoot&&!strings.HasPrefix(clean,generationRoot+string(os.PathSeparator)){return linuxApplicationScope{},ErrPolicyDenied};if err=validateLinuxApplicationRoot(generationRoot,clean,binding);err!=nil{return linuxApplicationScope{},err};return linuxApplicationScope{binding,clean},nil}

func validateLinuxApplicationRoot(generationRoot,target string,binding LinuxApplicationSiteBinding)error{if !filepath.IsAbs(generationRoot)||!strings.HasPrefix(target,generationRoot+string(os.PathSeparator)){return ErrPolicyDenied};relative,err:=filepath.Rel(generationRoot,target);if err!=nil||relative=="."||strings.HasPrefix(relative,".."){return ErrPolicyDenied};current:=generationRoot;components:=strings.Split(relative,string(os.PathSeparator));for index,component:=range components{if component==""||component=="."||component==".."{return ErrPolicyDenied};current=filepath.Join(current,component);info,statErr:=os.Lstat(current);if errors.Is(statErr,os.ErrNotExist){if index<2{return statErr};if mkdirErr:=os.Mkdir(current,0750);mkdirErr!=nil{return mkdirErr};if chownErr:=os.Chown(current,int(binding.UID),int(binding.GID));chownErr!=nil{return chownErr};continue};if statErr!=nil{return statErr};if !info.IsDir()||info.Mode()&os.ModeSymlink!=0||info.Mode().Perm()&0002!=0{return ErrPolicyDenied}};return nil}

func(runtime *LinuxApplicationRuntime)command(ctx context.Context,scope linuxApplicationScope,binary string,input []byte,maximum int,args ...string)([]byte,[]byte,int,error){if maximum<=0||maximum>8<<20{maximum=8<<20};command:=exec.CommandContext(ctx,binary,args...);command.Dir=scope.root;command.Env=[]string{"PATH=/usr/local/bin:/usr/bin:/bin","HOME="+scope.root,"LANG=C.UTF-8","WP_CLI_CACHE_DIR="+filepath.Join(scope.root,".wp-cli-cache")};command.SysProcAttr=&syscall.SysProcAttr{Credential:&syscall.Credential{Uid:scope.binding.UID,Gid:scope.binding.GID,NoSetGroups:true}};if input!=nil{command.Stdin=bytes.NewReader(input)};var stdout,stderr limitedApplicationBuffer;stdout.maximum=maximum;stderr.maximum=maximum;command.Stdout=&stdout;command.Stderr=&stderr;err:=command.Run();exitCode:=0;if err!=nil{exitCode=-1;var exit *exec.ExitError;if errors.As(err,&exit){exitCode=exit.ExitCode()}};return stdout.Bytes(),stderr.Bytes(),exitCode,err}
type limitedApplicationBuffer struct{bytes.Buffer;maximum int;truncated bool}
func(buffer *limitedApplicationBuffer)Write(value []byte)(int,error){original:=len(value);remaining:=buffer.maximum-buffer.Len();if remaining<=0{buffer.truncated=true;return original,nil};if len(value)>remaining{value=value[:remaining];buffer.truncated=true};_,err:=buffer.Buffer.Write(value);return original,err}

func(runtime *LinuxApplicationRuntime)wp(ctx context.Context,scope linuxApplicationScope,input []byte,maximum int,args ...string)([]byte,[]byte,int,error){base:=[]string{"--path="+scope.root,"--no-color","--quiet"};return runtime.command(ctx,scope,runtime.WPCLI,input,maximum,append(base,args...)...)}
func receiptForApplication(operation string,scope SiteExecutionScope,installation InstallationID,input,output any,release ReleaseID,snapshot SnapshotID,irreversible bool)ExecutionReceipt{inputJSON,_:=json.Marshal(input);outputJSON,_:=json.Marshal(output);inputDigest:=linuxApplicationDigest(inputJSON);outputDigest:=linuxApplicationDigest(outputJSON);frontier:=uint64(time.Now().UTC().UnixNano());return ExecutionReceipt{Operation:operation,SiteID:scope.SiteID,SiteUID:scope.SiteUID,InstallationID:installation,InputDigest:inputDigest,OutputDigest:outputDigest,ReleaseID:release,SnapshotID:snapshot,WriteFrontier:frontier,Irreversible:irreversible,Attestation:linuxApplicationDigest([]byte(operation+"\x00"+inputDigest+"\x00"+outputDigest)),CompletedAt:time.Now().UTC()}}

func(runtime *LinuxApplicationRuntime)Install(ctx context.Context,execution InstallExecution)(ExecutionReceipt,error){if execution.Validate(time.Now().UTC())!=nil||applicationManifestFromInstall(execution).Validate()!=nil{return ExecutionReceipt{},ErrInvalid};if execution.Definition.Kind!=ApplicationWordPress{return runtime.installCertifiedApplication(ctx,execution)};scope,err:=runtime.resolve(ctx,execution.Scope);if err!=nil{return ExecutionReceipt{},err};if err=os.MkdirAll(scope.root,0750);err!=nil{return ExecutionReceipt{},err};if err=os.Chown(scope.root,int(scope.binding.UID),int(scope.binding.GID));err!=nil{return ExecutionReceipt{},err};artifact:=filepath.Join(scope.root,".cyberpanel-wordpress.tar.gz");stdout,stderr,_,err:=runtime.command(ctx,scope,runtime.Curl,nil,1<<20,"--proto","=https","--tlsv1.2","--location","--fail","--silent","--show-error","--output",artifact,execution.Definition.Artifact.URL);if err!=nil{return ExecutionReceipt{},fmt.Errorf("fetch WordPress artifact: %w: %s %s",err,stdout,stderr)};info,err:=os.Lstat(artifact);if err!=nil||!info.Mode().IsRegular()||info.Size()!=execution.Definition.Artifact.Size{_ = os.Remove(artifact);return ExecutionReceipt{},ErrIntegrity};content,err:=os.ReadFile(artifact);if err!=nil{return ExecutionReceipt{},err};digest:=sha256.Sum256(content);for index:=range content{content[index]=0};if hex.EncodeToString(digest[:])!=execution.Definition.Artifact.Digest{_ = os.Remove(artifact);return ExecutionReceipt{},ErrIntegrity};if _,stderr,_,err=runtime.command(ctx,scope,runtime.Tar,nil,1<<20,"-xzf",artifact,"--strip-components=1","--no-same-owner","--no-same-permissions","-C",scope.root);err!=nil{_ = os.Remove(artifact);return ExecutionReceipt{},fmt.Errorf("extract WordPress artifact: %w: %s",err,stderr)};_ = os.Remove(artifact)
	databasePassword,err:=runtime.Secrets.ApplicationSecret(ctx,execution.Database.PasswordRef,execution.Scope.TenantID,execution.Scope.SiteID,execution.Installation,"database");if err!=nil{return ExecutionReceipt{},err};defer wipeLinuxApplicationBytes(databasePassword);adminPassword,err:=runtime.Secrets.ApplicationSecret(ctx,execution.Administrator.PasswordRef,execution.Scope.TenantID,execution.Scope.SiteID,execution.Installation,"administrator");if err!=nil{return ExecutionReceipt{},err};defer wipeLinuxApplicationBytes(adminPassword)
	dbHost:=execution.Database.EndpointRef;if dbHost=="local-mariadb"{dbHost="localhost"};stdin:=append(append([]byte(nil),databasePassword...), '\n');if _,stderr,_,err=runtime.wp(ctx,scope,stdin,1<<20,"config","create","--dbname="+execution.Database.DatabaseName,"--dbuser="+execution.Database.PrincipalName,"--dbhost="+dbHost,"--dbcharset=utf8mb4","--skip-check","--prompt=dbpass");err!=nil{return ExecutionReceipt{},fmt.Errorf("create WordPress config: %w: %s",err,stderr)};stdin=append(append([]byte(nil),adminPassword...), '\n');if _,stderr,_,err=runtime.wp(ctx,scope,stdin,1<<20,"core","install","--url="+execution.CanonicalURL,"--title="+execution.Title,"--admin_user="+execution.Administrator.Username,"--admin_email="+execution.Administrator.Email,"--skip-email","--prompt=admin_password");err!=nil{return ExecutionReceipt{},fmt.Errorf("install WordPress: %w: %s",err,stderr)};_,_,_,_=runtime.wp(ctx,scope,nil,1<<20,"language","core","install",execution.Locale,"--activate");_,_,_,_=runtime.wp(ctx,scope,nil,1<<20,"option","update","timezone_string",execution.Timezone);_,_,_,_=runtime.wp(ctx,scope,nil,1<<20,"plugin","install","litespeed-cache","--activate");if err=runtime.recordInstalledApplication(execution);err!=nil{return ExecutionReceipt{},err};return receiptForApplication("install",execution.Scope,execution.Installation,execution,execution.Definition.Artifact.Digest,execution.ReleaseID,"",false),nil}

func(runtime *LinuxApplicationRuntime)Discover(ctx context.Context,execution DiscoveryExecution)([]DiscoveryCandidate,ExecutionReceipt,error){return runtime.discoverAdoptableApplications(ctx,execution)}
func(runtime *LinuxApplicationRuntime)Adopt(ctx context.Context,execution AdoptExecution)(ExecutionReceipt,error){return runtime.adoptDiscoveredApplication(ctx,execution)}

type wpListRow struct{Name string `json:"name"`;Status string `json:"status"`;Version string `json:"version"`;Update string `json:"update"`;UpdateVersion string `json:"update_version"`}
func(runtime *LinuxApplicationRuntime)inventory(ctx context.Context,scope linuxApplicationScope,siteScope SiteExecutionScope,installation InstallationID,recipeDigest string)(ComponentInventory,HealthObservation,error){version,stderr,_,err:=runtime.wp(ctx,scope,nil,2<<20,"core","version");if err!=nil{return ComponentInventory{},HealthObservation{},fmt.Errorf("inspect WordPress core: %w: %s",err,stderr)};components:=[]Component{{Kind:ComponentCore,Name:"wordpress",Version:strings.TrimSpace(string(version)),Digest:linuxApplicationDigest(bytes.TrimSpace(version)),State:ComponentActive,Origin:"wordpress.org"}};for _,item:=range []struct{kind ComponentKind;name string}{{ComponentPlugin,"plugin"},{ComponentTheme,"theme"}}{output,_,_,listErr:=runtime.wp(ctx,scope,nil,4<<20,item.name,"list","--format=json","--fields=name,status,version,update,update_version");if listErr!=nil{continue};var rows []wpListRow;if json.Unmarshal(output,&rows)!=nil{continue};for _,row:=range rows{state:=ComponentInactive;if row.Status=="active"||row.Status=="active-network"{state=ComponentActive};component:=Component{Kind:item.kind,Name:row.Name,Version:row.Version,Digest:linuxApplicationDigest([]byte(string(item.kind)+"\x00"+row.Name+"\x00"+row.Version)),State:state,Origin:"wordpress.org"};if row.Update=="available"&&row.UpdateVersion!=""{component.UpdateVersion=row.UpdateVersion;component.UpdateDigest=linuxApplicationDigest([]byte(row.Name+"\x00"+row.UpdateVersion))};components=append(components,component)}};sort.Slice(components,func(i,j int)bool{if components[i].Kind!=components[j].Kind{return components[i].Kind<components[j].Kind};return components[i].Name<components[j].Name});encoded,_:=json.Marshal(components);source:=linuxApplicationDigest(encoded);inventory:=ComponentInventory{InstallationID:installation,Generation:uint64(time.Now().UTC().UnixNano()),ObservedAt:time.Now().UTC(),SourceDigest:source,Components:components};health:=HealthObservation{State:HealthHealthy,CheckedAt:time.Now().UTC(),DefinitionDigest:recipeDigest,ReleaseDigest:source,ProbeReceipts:[]ProbeReceipt{{Name:"wordpress_core",Passed:true,Digest:source,ObservedAt:time.Now().UTC()}}};return inventory,health,nil}
func(runtime *LinuxApplicationRuntime)Inspect(ctx context.Context,execution InspectExecution)(ComponentInventory,HealthObservation,ExecutionReceipt,error){if execution.Kind!=ApplicationWordPress{if inventory,health,receipt,err:=runtime.inspectAdoptedApplication(ctx,execution);err==nil{return inventory,health,receipt,nil}else if !errors.Is(err,os.ErrNotExist){return ComponentInventory{},HealthObservation{},ExecutionReceipt{},err};return runtime.inspectCertifiedApplication(ctx,execution)};scope,err:=runtime.resolve(ctx,execution.Scope);if err!=nil{return ComponentInventory{},HealthObservation{},ExecutionReceipt{},err};inventory,health,err:=runtime.inventory(ctx,scope,execution.Scope,execution.Installation,execution.RecipeDigest);if err!=nil{return ComponentInventory{},HealthObservation{},ExecutionReceipt{},err};return inventory,health,receiptForApplication("inspect",execution.Scope,execution.Installation,execution,inventory,"","",false),nil}

func(runtime *LinuxApplicationRuntime)Repair(ctx context.Context,execution RepairExecution)(ExecutionReceipt,error){if execution.Kind!=ApplicationWordPress{return runtime.repairCertifiedApplication(ctx,execution)};scope,err:=runtime.resolve(ctx,execution.Scope);if err!=nil{return ExecutionReceipt{},err};for _,action:=range execution.Actions{var args []string;switch action{case RepairCoreFiles:args=[]string{"core","download","--force","--skip-content"};case RepairDatabase:args=[]string{"db","repair"};case RepairCache:args=[]string{"cache","flush"};case RepairDependencies:args=[]string{"plugin","verify-checksums","--all"};case RepairConfiguration:args=[]string{"config","shuffle-salts"};case RepairPermissions:if err=os.Chown(scope.root,int(scope.binding.UID),int(scope.binding.GID));err!=nil{return ExecutionReceipt{},err};continue;default:return ExecutionReceipt{},ErrInvalid};if _,stderr,_,runErr:=runtime.wp(ctx,scope,nil,4<<20,args...);runErr!=nil{return ExecutionReceipt{},fmt.Errorf("repair WordPress: %w: %s",runErr,stderr)}};return receiptForApplication("repair",execution.Scope,execution.Installation,execution,execution.Actions,"",SnapshotID(execution.RecoveryPointID),false),nil}
func(runtime *LinuxApplicationRuntime)PrepareUpdate(ctx context.Context,execution UpdateExecution)(ExecutionReceipt,error){if execution.Definition.Kind!=ApplicationWordPress{return runtime.prepareCertifiedApplicationUpdate(ctx,execution)};scope,err:=runtime.resolve(ctx,execution.Scope);if err!=nil{return ExecutionReceipt{},err};if _,stderr,_,err:=runtime.wp(ctx,scope,nil,2<<20,"core","verify-checksums");err!=nil{return ExecutionReceipt{},fmt.Errorf("verify WordPress before update: %w: %s",err,stderr)};return receiptForApplication("prepare_update",execution.Scope,execution.Installation,execution,execution.TargetRelease.ContentDigest,execution.TargetRelease.ID,execution.SnapshotID,false),nil}
func(runtime *LinuxApplicationRuntime)ApplyUpdate(ctx context.Context,execution UpdateExecution)(ExecutionReceipt,error){if execution.Definition.Kind!=ApplicationWordPress{return runtime.applyCertifiedApplicationUpdate(ctx,execution)};scope,err:=runtime.resolve(ctx,execution.Scope);if err!=nil{return ExecutionReceipt{},err};scope,err=runtime.shadowScope(scope,execution.ShadowBinding);if err!=nil{return ExecutionReceipt{},err};if _,stderr,_,err:=runtime.wp(ctx,scope,nil,4<<20,"core","update","--version="+execution.TargetRelease.ProductVersion,"--force");err!=nil{return ExecutionReceipt{},fmt.Errorf("update WordPress core: %w: %s",err,stderr)};for _,component:=range execution.Components{kind:="plugin";if component.Kind==ComponentTheme{kind="theme"}else if component.Kind!=ComponentPlugin{continue};if _,stderr,_,err:=runtime.wp(ctx,scope,nil,4<<20,kind,"update",component.Name,"--version="+component.Version);err!=nil{return ExecutionReceipt{},fmt.Errorf("update WordPress component: %w: %s",err,stderr)}};if _,stderr,_,err:=runtime.wp(ctx,scope,nil,2<<20,"core","update-db");err!=nil{return ExecutionReceipt{},fmt.Errorf("update WordPress database: %w: %s",err,stderr)};if err=runtime.recordUpdatedApplication(execution);err!=nil{return ExecutionReceipt{},err};return receiptForApplication("apply_update",execution.Scope,execution.Installation,execution,execution.TargetRelease.ContentDigest,execution.TargetRelease.ID,execution.SnapshotID,false),nil}
func(runtime *LinuxApplicationRuntime)ProbeUpdate(ctx context.Context,execution UpdateExecution)(HealthObservation,ExecutionReceipt,error){if execution.Definition.Kind!=ApplicationWordPress{return runtime.probeCertifiedApplicationUpdate(ctx,execution)};scope,err:=runtime.resolve(ctx,execution.Scope);if err!=nil{return HealthObservation{},ExecutionReceipt{},err};scope,err=runtime.shadowScope(scope,execution.ShadowBinding);if err!=nil{return HealthObservation{},ExecutionReceipt{},err};inventory,health,err:=runtime.inventory(ctx,scope,execution.Scope,execution.Installation,execution.Definition.Recipe.RecipeDigest);if err!=nil{return HealthObservation{},ExecutionReceipt{},err};return health,receiptForApplication("probe_update",execution.Scope,execution.Installation,execution,inventory,execution.TargetRelease.ID,execution.SnapshotID,false),nil}
func(runtime *LinuxApplicationRuntime)Promote(ctx context.Context,execution PromotionExecution)(ExecutionReceipt,error){return runtime.promoteApplicationRelease(ctx,execution)}
func(runtime *LinuxApplicationRuntime)Rollback(ctx context.Context,execution PromotionExecution)(ExecutionReceipt,error){return runtime.rollbackApplicationRelease(ctx,execution)}
func(runtime *LinuxApplicationRuntime)Quarantine(ctx context.Context,execution RemovalExecution)(ExecutionReceipt,error){scope,err:=runtime.resolve(ctx,execution.Scope);if err!=nil{return ExecutionReceipt{},err};_,_,_,_=runtime.wp(ctx,scope,nil,1<<20,"maintenance-mode","activate");marker:=filepath.Join(scope.root,".cyberpanel-quarantined");if err=os.WriteFile(marker,[]byte(time.Now().UTC().Format(time.RFC3339Nano)+"\n"),0400);err!=nil{return ExecutionReceipt{},err};if err=os.Chown(marker,int(scope.binding.UID),int(scope.binding.GID));err!=nil{return ExecutionReceipt{},err};return receiptForApplication("quarantine",execution.Scope,execution.Installation,execution,"quarantined","",SnapshotID(execution.RecoveryPointID),false),nil}
func(runtime *LinuxApplicationRuntime)Remove(ctx context.Context,execution RemovalExecution)(ExecutionReceipt,error){scope,err:=runtime.resolve(ctx,execution.Scope);if err!=nil{return ExecutionReceipt{},err};if execution.Disposition==RemovalQuarantine{return runtime.Quarantine(ctx,execution)};if scope.root==""||scope.root=="/"||!strings.HasPrefix(scope.root,linuxApplicationSitesRoot+"/"){return ExecutionReceipt{},ErrPolicyDenied};entries,err:=os.ReadDir(scope.root);if err!=nil{return ExecutionReceipt{},err};for _,entry:=range entries{target:=filepath.Join(scope.root,entry.Name());if err=os.RemoveAll(target);err!=nil{return ExecutionReceipt{},err}};if err=runtime.removeApplicationState(execution.Installation);err!=nil{return ExecutionReceipt{},err};return receiptForApplication("remove",execution.Scope,execution.Installation,execution,"removed","",SnapshotID(execution.RecoveryPointID),true),nil}

func(runtime *LinuxApplicationRuntime)InvokeWPCLI(ctx context.Context,invocation WPCLIInvocation)(WPCLIResult,error){if invocation.Validate()!=nil{return WPCLIResult{},ErrInvalid};scope,err:=runtime.resolve(ctx,invocation.Scope);if err!=nil{return WPCLIResult{},err};stdout,stderr,exitCode,runErr:=runtime.wp(ctx,scope,nil,int(invocation.MaximumOutput),invocation.Arguments...);receipt:=receiptForApplication("wp_cli",invocation.Scope,invocation.InstallationID,invocation,append(append([]byte(nil),stdout...),stderr...),"","",!invocation.ReadOnly);result:=WPCLIResult{ExitCode:exitCode,Stdout:stdout,Stderr:stderr,Truncated:len(stdout)+len(stderr)>=int(invocation.MaximumOutput),Receipt:receipt};return result,runErr}

func(runtime *LinuxApplicationRuntime)MutateComponent(ctx context.Context,mutation ComponentMutation)(ComponentInventory,ExecutionReceipt,error){if mutation.Validate()!=nil{return ComponentInventory{},ExecutionReceipt{},ErrInvalid};scope,err:=runtime.resolve(ctx,mutation.Scope);if err!=nil{return ComponentInventory{},ExecutionReceipt{},err};kind:="plugin";if mutation.Kind==ComponentTheme{kind="theme"}else if mutation.Kind==ComponentCore{kind="core"}else{return ComponentInventory{},ExecutionReceipt{},ErrUnsupported};args:=[]string{};switch mutation.Action{case WordPressInstallComponent:args=[]string{kind,"install",mutation.Name};if mutation.Release!=nil{args=append(args,"--version="+mutation.Release.Version)};if mutation.Force{args=append(args,"--force")};case WordPressActivateComponent:args=[]string{kind,"activate",mutation.Name};case WordPressDeactivateComponent:args=[]string{kind,"deactivate",mutation.Name};case WordPressUpdateComponent:args=[]string{kind,"update",mutation.Name};case WordPressDeleteComponent:args=[]string{kind,"delete",mutation.Name};case WordPressReinstallCore:args=[]string{"core","download","--force","--skip-content"};case WordPressVerifyChecksums:args=[]string{"core","verify-checksums"};default:return ComponentInventory{},ExecutionReceipt{},ErrInvalid};if mutation.NetworkWide{args=append(args,"--network")};if _,stderr,_,err:=runtime.wp(ctx,scope,nil,4<<20,args...);err!=nil{return ComponentInventory{},ExecutionReceipt{},fmt.Errorf("mutate WordPress component: %w: %s",err,stderr)};inventory,_,err:=runtime.inventory(ctx,scope,mutation.Scope,mutation.InstallationID,linuxApplicationDigest([]byte(mutation.Name)));if err!=nil{return ComponentInventory{},ExecutionReceipt{},err};return inventory,receiptForApplication("wordpress_component",mutation.Scope,mutation.InstallationID,mutation,inventory,"",SnapshotID(mutation.RecoveryPointID),true),nil}

func(runtime *LinuxApplicationRuntime)ApplySettings(ctx context.Context,mutation WordPressSettingsMutation)(WordPressSettings,ExecutionReceipt,error){if mutation.Settings.Validate()!=nil{return WordPressSettings{},ExecutionReceipt{},ErrInvalid};scope,err:=runtime.resolve(ctx,mutation.Scope);if err!=nil{return WordPressSettings{},ExecutionReceipt{},err};settings:=mutation.Settings;options:=[][2]string{{"home",settings.URLs.HomeURL},{"siteurl",settings.URLs.SiteURL},{"blogname",settings.General.Title},{"blogdescription",settings.General.Tagline},{"admin_email",settings.General.AdminEmail},{"timezone_string",settings.General.Timezone},{"date_format",settings.General.DateFormat},{"time_format",settings.General.TimeFormat},{"start_of_week",strconv.Itoa(int(settings.General.WeekStartsOn))},{"permalink_structure",settings.Runtime.PermalinkStructure}};for _,option:=range options{if _,stderr,_,err:=runtime.wp(ctx,scope,nil,1<<20,"option","update",option[0],option[1]);err!=nil{return WordPressSettings{},ExecutionReceipt{},fmt.Errorf("update WordPress setting: %w: %s",err,stderr)}};constants:=[][2]string{{"WP_DEBUG",strconv.FormatBool(settings.Runtime.Debug)},{"WP_DEBUG_LOG",strconv.FormatBool(settings.Runtime.DebugLog)},{"WP_DEBUG_DISPLAY",strconv.FormatBool(settings.Runtime.DisplayErrors)},{"DISALLOW_FILE_EDIT",strconv.FormatBool(settings.Runtime.DisableFileEditor)},{"DISALLOW_FILE_MODS",strconv.FormatBool(settings.Runtime.DisallowFileMods)},{"WP_POST_REVISIONS",strconv.FormatInt(int64(settings.Runtime.RevisionLimit),10)},{"AUTOSAVE_INTERVAL",strconv.FormatInt(int64(settings.Runtime.AutosaveInterval/time.Second),10)}};for _,constant:=range constants{if _,stderr,_,err:=runtime.wp(ctx,scope,nil,1<<20,"config","set",constant[0],constant[1],"--raw");err!=nil{return WordPressSettings{},ExecutionReceipt{},fmt.Errorf("update WordPress config: %w: %s",err,stderr)}};_,_,_,_=runtime.wp(ctx,scope,nil,1<<20,"rewrite","flush","--hard");if settings.Runtime.Maintenance{_,_,_,_=runtime.wp(ctx,scope,nil,1<<20,"maintenance-mode","activate")}else{_,_,_,_=runtime.wp(ctx,scope,nil,1<<20,"maintenance-mode","deactivate")};return settings,receiptForApplication("wordpress_settings",mutation.Scope,mutation.InstallationID,mutation,settings,"",SnapshotID(mutation.RecoveryPointID),true),nil}

func(runtime *LinuxApplicationRuntime)ConfigureLSCache(ctx context.Context,mutation CacheMutation)(LSCachePolicy,ExecutionReceipt,error){if mutation.Policy==nil||mutation.Policy.Validate()!=nil{return LSCachePolicy{},ExecutionReceipt{},ErrInvalid};scope,err:=runtime.resolve(ctx,mutation.Scope);if err!=nil{return LSCachePolicy{},ExecutionReceipt{},err};policy:=*mutation.Policy;if policy.State==CacheEnabled{if _,stderr,_,err:=runtime.wp(ctx,scope,nil,4<<20,"plugin","install","litespeed-cache","--activate");err!=nil{return LSCachePolicy{},ExecutionReceipt{},fmt.Errorf("enable LSCache: %w: %s",err,stderr)}}else{_,_,_,_=runtime.wp(ctx,scope,nil,1<<20,"plugin","deactivate","litespeed-cache")};values:=[][2]string{{"litespeed.conf.cache",boolString(policy.State==CacheEnabled)},{"litespeed.conf.cache-browser",boolString(policy.BrowserCache)},{"litespeed.conf.object",boolString(policy.ObjectCache)},{"litespeed.conf.ttl-pub",strconv.FormatInt(int64(policy.PublicTTL/time.Second),10)},{"litespeed.conf.ttl-priv",strconv.FormatInt(int64(policy.PrivateTTL/time.Second),10)}};for _,value:=range values{_,_,_,_=runtime.wp(ctx,scope,nil,1<<20,"option","update",value[0],value[1])};_,_,_,_=runtime.wp(ctx,scope,nil,1<<20,"litespeed-purge","all");return policy,receiptForApplication("lscache_configure",mutation.Scope,mutation.InstallationID,mutation,policy,"","",true),nil}
func(runtime *LinuxApplicationRuntime)PurgeLSCache(ctx context.Context,mutation CacheMutation)(ExecutionReceipt,error){scope,err:=runtime.resolve(ctx,mutation.Scope);if err!=nil{return ExecutionReceipt{},err};args:=[]string{"litespeed-purge"};switch mutation.PurgeScope{case PurgeAll:args=append(args,"all");case PurgePath:args=append(args,"url");args=append(args,mutation.PurgeValues...);case PurgeTag:args=append(args,"tag");args=append(args,mutation.PurgeValues...);default:return ExecutionReceipt{},ErrInvalid};if _,stderr,_,err:=runtime.wp(ctx,scope,nil,2<<20,args...);err!=nil{return ExecutionReceipt{},fmt.Errorf("purge LSCache: %w: %s",err,stderr)};return receiptForApplication("lscache_purge",mutation.Scope,mutation.InstallationID,mutation,mutation.PurgeValues,"","",false),nil}

const cyberPanelAutologinBridge = `<?php
/* CyberPanel signed one-time login bridge. */
add_action('rest_api_init', function () {
  register_rest_route('cyberpanel/v1', '/autologin', array('methods'=>'POST','permission_callback'=>'__return_true','callback'=>function($request){
    $endpoint=get_option('cyberpanel_autologin_endpoint');
    if(!is_string($endpoint)||$endpoint===''){return new WP_Error('disabled','Bridge disabled',array('status'=>403));}
    $response=wp_remote_post($endpoint,array('timeout'=>5,'sslverify'=>true,'headers'=>array('Content-Type'=>'application/json'),'body'=>wp_json_encode($request->get_json_params())));
    if(is_wp_error($response)||wp_remote_retrieve_response_code($response)!==200){return new WP_Error('denied','Grant denied',array('status'=>403));}
    $grant=json_decode(wp_remote_retrieve_body($response),true);
    if(!is_array($grant)||empty($grant['wordpress_user_id'])){return new WP_Error('invalid','Invalid grant',array('status'=>403));}
    wp_set_auth_cookie((int)$grant['wordpress_user_id'],false,is_ssl());
    return array('redirect'=>admin_url());
  }));
});
`
func(runtime *LinuxApplicationRuntime)InstallAutologinBridge(ctx context.Context,request AutologinBridgeRequest)(ExecutionReceipt,error){if request.Validate()!=nil||request.BridgeDigest!=linuxApplicationDigest([]byte(cyberPanelAutologinBridge)){return ExecutionReceipt{},ErrRecipeUntrusted};scope,err:=runtime.resolve(ctx,request.Scope);if err!=nil{return ExecutionReceipt{},err};directory:=filepath.Join(scope.root,"wp-content","mu-plugins");if err=os.MkdirAll(directory,0750);err!=nil{return ExecutionReceipt{},err};path:=filepath.Join(directory,"cyberpanel-autologin.php");if err=os.WriteFile(path,[]byte(cyberPanelAutologinBridge),0640);err!=nil{return ExecutionReceipt{},err};if err=os.Chown(path,int(scope.binding.UID),int(scope.binding.GID));err!=nil{return ExecutionReceipt{},err};if _,stderr,_,err:=runtime.wp(ctx,scope,nil,1<<20,"option","update","cyberpanel_autologin_endpoint",request.Endpoint);err!=nil{return ExecutionReceipt{},fmt.Errorf("configure autologin bridge: %w: %s",err,stderr)};return receiptForApplication("install_autologin_bridge",request.Scope,request.InstallationID,request,request.BridgeDigest,"","",true),nil}
func(runtime *LinuxApplicationRuntime)RemoveAutologinBridge(ctx context.Context,request AutologinBridgeRequest)(ExecutionReceipt,error){scope,err:=runtime.resolve(ctx,request.Scope);if err!=nil{return ExecutionReceipt{},err};path:=filepath.Join(scope.root,"wp-content","mu-plugins","cyberpanel-autologin.php");if err=os.Remove(path);err!=nil&&!errors.Is(err,os.ErrNotExist){return ExecutionReceipt{},err};_,_,_,_=runtime.wp(ctx,scope,nil,1<<20,"option","delete","cyberpanel_autologin_endpoint");return receiptForApplication("remove_autologin_bridge",request.Scope,request.InstallationID,request,"removed","","",true),nil}

func applicationShadowToken(installation InstallationID,release ReleaseID)string{return "shadow-"+linuxApplicationDigest([]byte(string(installation)+"\x00"+string(release)))[:40]}
func(runtime *LinuxApplicationRuntime)routeBinding(ctx context.Context,siteID SiteID)(LinuxApplicationSiteBinding,string,error){if runtime==nil||runtime.Resolver==nil||!validID(string(siteID)){return LinuxApplicationSiteBinding{},"",ErrInvalid};binding,err:=runtime.Resolver.ResolveApplicationSite(ctx,siteID);if err!=nil{return LinuxApplicationSiteBinding{},"",err};if binding.SiteKey==""||!strings.HasPrefix(binding.SiteKey,"s-")||binding.UID<1000||binding.GID!=binding.UID||binding.Generation==0{return LinuxApplicationSiteBinding{},"",ErrPolicyDenied};generationRoot:=filepath.Join(linuxApplicationSitesRoot,binding.SiteKey,"roots","g"+strconv.FormatUint(binding.Generation,10));releases:=filepath.Join(generationRoot,"releases");if err=validateLinuxApplicationRoot(generationRoot,filepath.Join(releases,"current"),binding);err!=nil{return LinuxApplicationSiteBinding{},"",err};return binding,releases,nil}
func(runtime *LinuxApplicationRuntime)shadowScope(scope linuxApplicationScope,token string)(linuxApplicationScope,error){if !strings.HasPrefix(token,"shadow-")||len(token)!=47{return linuxApplicationScope{},ErrPolicyDenied};releases:=filepath.Dir(scope.root);if filepath.Base(scope.root)!="current"{releases=filepath.Join(linuxApplicationSitesRoot,scope.binding.SiteKey,"roots","g"+strconv.FormatUint(scope.binding.Generation,10),"releases")};root:=filepath.Join(releases,".app-"+token);info,err:=os.Lstat(root);if err!=nil||!info.IsDir()||info.Mode()&os.ModeSymlink!=0{return linuxApplicationScope{},ErrNotFound};scope.root=root;return scope,nil}
func(runtime *LinuxApplicationRuntime)CreateShadowRoute(ctx context.Context,siteID SiteID,installation InstallationID,release ReleaseID)(string,error){if !validID(string(installation))||!validID(string(release)){return "",ErrInvalid};binding,releases,err:=runtime.routeBinding(ctx,siteID);if err!=nil{return "",err};token:=applicationShadowToken(installation,release);target:=filepath.Join(releases,".app-"+token);if info,statErr:=os.Lstat(target);statErr==nil{if !info.IsDir()||info.Mode()&os.ModeSymlink!=0{return "",ErrConflict};return token,nil}else if !errors.Is(statErr,os.ErrNotExist){return "",statErr};if err=os.Mkdir(target,0750);err!=nil{return "",err};if err=os.Chown(target,int(binding.UID),int(binding.GID));err!=nil{return "",err};scope:=linuxApplicationScope{binding:binding,root:releases};if _,stderr,_,err:=runtime.command(ctx,scope,"/usr/bin/cp",nil,4<<20,"-a","--",filepath.Join(releases,"current")+"/.",target);err!=nil{_ = os.RemoveAll(target);return "",fmt.Errorf("prepare application shadow: %w: %s",err,stderr)};return token,nil}
func(runtime *LinuxApplicationRuntime)RemoveShadowRoute(ctx context.Context,siteID SiteID,installation InstallationID,release ReleaseID)error{if !validID(string(installation))||!validID(string(release)){return ErrInvalid};_,releases,err:=runtime.routeBinding(ctx,siteID);if err!=nil{return err};target:=filepath.Join(releases,".app-"+applicationShadowToken(installation,release));if !strings.HasPrefix(target,releases+string(os.PathSeparator)){return ErrPolicyDenied};if err=os.RemoveAll(target);err!=nil{return err};statePath:=filepath.Join(releases,".application-route-swap.json");encoded,readErr:=os.ReadFile(statePath);if errors.Is(readErr,os.ErrNotExist){return nil};if readErr!=nil{return readErr};var state applicationRouteSwap;if json.Unmarshal(encoded,&state)!=nil||state.InstallationID!=installation||state.TargetRelease!=release||!strings.HasPrefix(state.Rollback,".app-rollback-"){return ErrIntegrity};rollback:=filepath.Join(releases,state.Rollback);if !strings.HasPrefix(rollback,releases+string(os.PathSeparator)){return ErrPolicyDenied};if err=os.RemoveAll(rollback);err!=nil{return err};return os.Remove(statePath)}
type applicationRouteSwap struct{InstallationID InstallationID `json:"installation_id"`;TargetRelease ReleaseID `json:"target_release"`;Shadow string `json:"shadow"`;Rollback string `json:"rollback"`}
func(runtime *LinuxApplicationRuntime)ActivateReleaseRoute(ctx context.Context,siteID SiteID,installation InstallationID,release ReleaseID,shadow string)error{if shadow!=applicationShadowToken(installation,release){return ErrPolicyDenied};_,releases,err:=runtime.routeBinding(ctx,siteID);if err!=nil{return err};current:=filepath.Join(releases,"current");candidate:=filepath.Join(releases,".app-"+shadow);rollback:=".app-rollback-"+linuxApplicationDigest([]byte(string(installation)+"\x00"+string(release)))[:40];rollbackPath:=filepath.Join(releases,rollback);if _,err=os.Lstat(candidate);err!=nil{return ErrNotFound};if _,err=os.Lstat(rollbackPath);err==nil{return ErrConflict}else if !errors.Is(err,os.ErrNotExist){return err};if err=os.Rename(current,rollbackPath);err!=nil{return err};if err=os.Rename(candidate,current);err!=nil{_ = os.Rename(rollbackPath,current);return err};state:=applicationRouteSwap{installation,release,shadow,rollback};encoded,_:=json.Marshal(state);statePath:=filepath.Join(releases,".application-route-swap.json");if err=os.WriteFile(statePath,encoded,0600);err!=nil{_ = os.Rename(current,candidate);_ = os.Rename(rollbackPath,current);return err};return nil}
func(runtime *LinuxApplicationRuntime)RestoreReleaseRoute(ctx context.Context,siteID SiteID,installation InstallationID,release ReleaseID)error{if !validID(string(installation))||!validID(string(release)){return ErrInvalid};_,releases,err:=runtime.routeBinding(ctx,siteID);if err!=nil{return err};statePath:=filepath.Join(releases,".application-route-swap.json");encoded,err:=os.ReadFile(statePath);if errors.Is(err,os.ErrNotExist){return nil};if err!=nil{return err};var state applicationRouteSwap;if json.Unmarshal(encoded,&state)!=nil||state.InstallationID!=installation||!strings.HasPrefix(state.Shadow,"shadow-")||!strings.HasPrefix(state.Rollback,".app-rollback-"){return ErrIntegrity};current:=filepath.Join(releases,"current");failed:=filepath.Join(releases,".app-"+state.Shadow);rollback:=filepath.Join(releases,state.Rollback);if err=os.Rename(current,failed);err!=nil{return err};if err=os.Rename(rollback,current);err!=nil{_ = os.Rename(failed,current);return err};return os.Remove(statePath)}

func boolString(value bool)string{if value{return "1"};return "0"}
func wipeLinuxApplicationBytes(value []byte){for index:=range value{value[index]=0}}

var _ SiteApplicationExecutor=(*LinuxApplicationRuntime)(nil)
var _ WordPressExecutor=(*LinuxApplicationRuntime)(nil)
var _ WPCLIExecutor=(*LinuxApplicationRuntime)(nil)
var _ ApplicationRouteController=(*LinuxApplicationRuntime)(nil)
var _ StagingExecutor=(*LinuxApplicationRuntime)(nil)
var _ ScannerProvider=(*LinuxApplicationRuntime)(nil)
var _ RemediationExecutor=(*LinuxApplicationRuntime)(nil)
