//go:build linux

package apps

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"io"
	"os"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/database"
	"github.com/aonsyed/cyberpanel/platform/internal/hosting/site"
	"github.com/aonsyed/cyberpanel/platform/internal/secrets"
)

const (
	ApplicationSecretAdapterID = "applications.wordpress"
	ApplicationSecretAdapterVersion = "linux-wordpress-v1"
)

func applicationSecretID(prefix,value string)secrets.ID{sum:=sha256.Sum256([]byte(prefix+"\x00"+value));identifier,_:=secrets.NewID(prefix+"_"+hex.EncodeToString(sum[:])[:48]);return identifier}
func ApplicationTenantOwnerID(tenantID string)secrets.ID{if identifier,err:=secrets.NewID(tenantID);err==nil{return identifier};return applicationSecretID("apptenant",tenantID)}
func ApplicationAudienceID(resource string)secrets.ID{if identifier,err:=secrets.NewID(resource);err==nil{return identifier};return applicationSecretID("appresource",resource)}
func ApplicationManagedSecretID(purpose string,installation InstallationID)secrets.ID{return applicationSecretID("appsecret",purpose+"\x00"+string(installation))}

type LinuxApplicationMaterialSource struct{Material *secrets.MaterialClient}
func NewLinuxApplicationMaterialSource(material *secrets.MaterialClient)(*LinuxApplicationMaterialSource,error){if material==nil{return nil,ErrInvalid};return &LinuxApplicationMaterialSource{material},nil}
func(source *LinuxApplicationMaterialSource)ApplicationSecret(ctx context.Context,reference SecretRef,tenant TenantID,siteID SiteID,installation InstallationID,purpose string)([]byte,error){if source==nil||source.Material==nil||!validID(string(reference)){return nil,ErrInvalid};secretID,err:=secrets.NewID(string(reference));if err!=nil{secretID=applicationSecretID("external",string(reference))};secretPurpose:=secrets.PurposeAuthentication;resource:=ApplicationAudienceID(string(installation));if purpose=="administrator"{resource=ApplicationAudienceID(string(siteID))};if purpose=="database"{secretPurpose=secrets.PurposeDatabase};response,err:=source.Material.Read(ctx,secrets.MaterialRequest{SecretID:secretID,OwnerTenantID:ApplicationTenantOwnerID(string(tenant)),Purpose:secretPurpose,Operation:secrets.OperationAuthenticate,AdapterID:ApplicationSecretAdapterID,AdapterVersion:ApplicationSecretAdapterVersion,ResourceID:resource});if err!=nil{return nil,err};if len(response.Material)==0||len(response.Material)>1<<20{wipeLinuxApplicationBytes(response.Material);return nil,ErrIntegrity};return response.Material,nil}

type ApplicationSecretIssuer struct{Management *secrets.ManagementClient;Store SQLRepository;ReleaseDigest string}
func NewApplicationSecretIssuer(management *secrets.ManagementClient,store SQLRepository,releaseDigest string)(*ApplicationSecretIssuer,error){if management==nil||store.DB==nil||len(releaseDigest)!=64{return nil,ErrInvalid};if _,err:=hex.DecodeString(releaseDigest);err!=nil{return nil,ErrInvalid};return &ApplicationSecretIssuer{management,store,strings.ToLower(releaseDigest)},nil}
func(issuer *ApplicationSecretIssuer)IssueApplicationSecret(ctx context.Context,tenant TenantID,siteID SiteID,installation InstallationID,purpose string)(SecretRef,error){if issuer==nil||issuer.Management==nil||issuer.Store.DB==nil||!validID(string(tenant))||!validID(string(siteID))||!validID(string(installation))||!validID(purpose){return "",ErrInvalid};identifier:=ApplicationManagedSecretID(purpose,installation);if lease,err:=issuer.Store.LoadApplicationSecretLease(ctx,identifier);err==nil&&lease.Metadata.State==secrets.StateActive{return SecretRef(identifier.String()),nil}else if err!=nil&&!errors.Is(err,ErrNotFound){return "",err};material:=make([]byte,32);if _,err:=rand.Read(material);err!=nil{return "",err};encoded:=make([]byte,base64.RawURLEncoding.EncodedLen(len(material)));base64.RawURLEncoding.Encode(encoded,material);wipeLinuxApplicationBytes(material);reference,err:=issuer.putApplicationSecret(ctx,tenant,siteID,installation,purpose,encoded);wipeLinuxApplicationBytes(encoded);return reference,err}
func(issuer *ApplicationSecretIssuer)EnrollAdministratorSecret(ctx context.Context,tenant TenantID,siteID SiteID,installation InstallationID,plaintext []byte)(SecretRef,error){if len(plaintext)<12||len(plaintext)>4096{return "",ErrInvalid};return issuer.putApplicationSecret(ctx,tenant,siteID,installation,"administrator",plaintext)}
func(issuer *ApplicationSecretIssuer)putApplicationSecret(ctx context.Context,tenant TenantID,siteID SiteID,installation InstallationID,purpose string,plaintext []byte)(SecretRef,error){if issuer==nil||issuer.Management==nil||issuer.Store.DB==nil||ctx==nil||!validID(string(tenant))||!validID(string(siteID))||!validID(string(installation))||!validID(purpose)||len(plaintext)==0{return "",ErrInvalid};identifier:=ApplicationManagedSecretID(purpose,installation);audience:=issuer.applicationAudience(siteID,installation,purpose);request:=secrets.PutRequest{ID:identifier,OwnerTenantID:ApplicationTenantOwnerID(string(tenant)),Purpose:secrets.PurposeAuthentication,Audience:audience,Plaintext:append([]byte(nil),plaintext...)};if lease,err:=issuer.Store.LoadApplicationSecretLease(ctx,identifier);err==nil{if lease.InstallationID!=installation||lease.Purpose!=purpose||lease.Metadata.OwnerTenantID!=request.OwnerTenantID{return "",ErrPolicyDenied};request.ExpectedVersion=lease.Metadata.Version;request.ExpectedBindingDigest=lease.Metadata.BindingDigest}else if !errors.Is(err,ErrNotFound){return "",err};metadata,err:=issuer.Management.Put(ctx,request);if err!=nil{return "",err};lease:=ApplicationSecretLease{InstallationID:installation,Purpose:purpose,Metadata:metadata,UpdatedAt:time.Now().UTC()};if err=issuer.Store.SaveApplicationSecretLease(ctx,lease);err!=nil{_,_=issuer.Management.Revoke(ctx,secrets.RevokeRequest{ID:metadata.ID,OwnerTenantID:metadata.OwnerTenantID,Purpose:metadata.Purpose,Audience:metadata.Audience,ExpectedVersion:metadata.Version,ExpectedBindingDigest:metadata.BindingDigest});return "",err};return SecretRef(metadata.ID.String()),nil}
func(issuer *ApplicationSecretIssuer)applicationAudience(siteID SiteID,installation InstallationID,purpose string)secrets.AudienceBinding{resourceKind:="application_installation";resource:=ApplicationAudienceID(string(installation));if purpose=="administrator"{resourceKind="hosting_site";resource=ApplicationAudienceID(string(siteID))};return secrets.AudienceBinding{AdapterID:ApplicationSecretAdapterID,AdapterVersion:ApplicationSecretAdapterVersion,Account:"site-application",Origin:"local://panel-execd/applications",ResourceKind:resourceKind,ResourceID:resource,ResourceGeneration:1,Operations:[]secrets.Operation{secrets.OperationAuthenticate},ConsumerReleaseDigest:issuer.ReleaseDigest}}
func(issuer *ApplicationSecretIssuer)RevokeApplicationSecret(ctx context.Context,reference SecretRef)error{if issuer==nil||issuer.Management==nil||issuer.Store.DB==nil||ctx==nil||!validID(string(reference)){return ErrInvalid};identifier,err:=secrets.NewID(string(reference));if err!=nil{return ErrInvalid};lease,err:=issuer.Store.LoadApplicationSecretLease(ctx,identifier);if err!=nil{return err};if lease.Metadata.State==secrets.StateRevoked||lease.Metadata.State==secrets.StateDestroyed{return nil};metadata,err:=issuer.Management.Revoke(ctx,secrets.RevokeRequest{ID:lease.Metadata.ID,OwnerTenantID:lease.Metadata.OwnerTenantID,Purpose:lease.Metadata.Purpose,Audience:lease.Metadata.Audience,ExpectedVersion:lease.Metadata.Version,ExpectedBindingDigest:lease.Metadata.BindingDigest});if err!=nil{return err};lease.Metadata=metadata;lease.UpdatedAt=time.Now().UTC();return issuer.Store.SaveApplicationSecretLease(ctx,lease)}

type CryptoRandomTokenSource struct{}
func(CryptoRandomTokenSource)Token(_ context.Context,size uint16)(string,error){if size<32||size>256{return "",ErrInvalid};value:=make([]byte,size);if _,err:=rand.Read(value);err!=nil{return "",err};encoded:=base64.RawURLEncoding.EncodeToString(value);wipeLinuxApplicationBytes(value);return encoded,nil}

type ApplicationDatabaseCommandService interface{Handle(context.Context,database.Command)(database.OperationReceipt,error)}
type ApplicationDatabaseProvisioner struct{Commands ApplicationDatabaseCommandService;Repository database.Repository;Management *secrets.ManagementClient;ReleaseDigest string}

func NewApplicationDatabaseProvisioner(commands ApplicationDatabaseCommandService,repository database.Repository,management *secrets.ManagementClient,releaseDigest string)(*ApplicationDatabaseProvisioner,error){if commands==nil||repository==nil||management==nil||len(releaseDigest)!=64{return nil,ErrInvalid};if _,err:=hex.DecodeString(releaseDigest);err!=nil{return nil,ErrInvalid};return &ApplicationDatabaseProvisioner{commands,repository,management,strings.ToLower(releaseDigest)},nil}

func(provisioner *ApplicationDatabaseProvisioner)ProvisionApplicationDatabase(ctx context.Context,tenant TenantID,siteID SiteID,installation InstallationID,kind ApplicationKind)(DatabaseBinding,error){if provisioner==nil||kind!=ApplicationWordPress{return DatabaseBinding{},ErrUnsupported};tenantID,err:=site.NewTenantID(string(tenant));if err!=nil{return DatabaseBinding{},ErrInvalid};siteResourceID,err:=site.NewSiteID(string(siteID));if err!=nil{return DatabaseBinding{},ErrInvalid};token:=applicationShortToken(string(installation));databaseID,_:=database.NewResourceID("appdb-"+token);principalID,_:=database.NewResourceID("appuser-"+token);grantID,_:=database.NewResourceID("appgrant-"+token);instance,err:=database.DefaultLocalInstance();if err!=nil{return DatabaseBinding{},err};databaseName,_:=database.ParseSQLIdentifier("cp_"+token[:24]);principalName,_:=database.ParseSQLIdentifier("cp_"+token[:24]);charset,_:=database.ParseSQLIdentifier("utf8mb4");collation,_:=database.ParseSQLIdentifier("utf8mb4_unicode_ci")
	password:=make([]byte,32);if _,err=rand.Read(password);err!=nil{return DatabaseBinding{},err};encoded:=make([]byte,base64.RawURLEncoding.EncodedLen(len(password)));base64.RawURLEncoding.Encode(encoded,password);wipeLinuxApplicationBytes(password);databaseSecret:=database.DatabaseSecretRecordID("appdb-secret-"+token);databaseAudience:=database.DatabaseAudienceID(principalID.String());if _,err=provisioner.Management.Put(ctx,secrets.PutRequest{ID:databaseSecret,OwnerTenantID:database.DatabaseTenantOwnerID(string(tenant)),Purpose:secrets.PurposeDatabase,Audience:secrets.AudienceBinding{AdapterID:database.MariaDBSecretAdapterID,AdapterVersion:database.MariaDBSecretAdapterVersion,Account:"local-mariadb",Origin:"local://panel-execd/mariadb",ResourceKind:"database_principal",ResourceID:databaseAudience,ResourceGeneration:1,Operations:[]secrets.Operation{secrets.OperationAuthenticate},ConsumerReleaseDigest:provisioner.ReleaseDigest},Plaintext:append([]byte(nil),encoded...)});err!=nil{wipeLinuxApplicationBytes(encoded);return DatabaseBinding{},err};applicationSecret:=ApplicationManagedSecretID("database",installation);if _,err=provisioner.Management.Put(ctx,secrets.PutRequest{ID:applicationSecret,OwnerTenantID:ApplicationTenantOwnerID(string(tenant)),Purpose:secrets.PurposeDatabase,Audience:secrets.AudienceBinding{AdapterID:ApplicationSecretAdapterID,AdapterVersion:ApplicationSecretAdapterVersion,Account:"site-application",Origin:"local://panel-execd/applications",ResourceKind:"application_installation",ResourceID:ApplicationAudienceID(string(installation)),ResourceGeneration:1,Operations:[]secrets.Operation{secrets.OperationAuthenticate},ConsumerReleaseDigest:provisioner.ReleaseDigest},Plaintext:encoded});wipeLinuxApplicationBytes(encoded);if err!=nil{return DatabaseBinding{},err}
	header:=database.CommandHeader{Actor:database.Actor{TenantID:tenantID,Capability:database.CapabilityTenantManage},TenantID:tenantID};status:=database.ResourceStatus{Lifecycle:database.LifecycleProvisioning,Health:database.HealthUnknown,Reconciliation:database.ReconciliationPending};db:=database.Database{Metadata:database.Metadata{ID:databaseID,TenantID:tenantID,SiteID:siteResourceID,Generation:1,Status:status},InstanceID:instance.ID,Name:databaseName,Charset:charset,Collation:collation,QuotaBytes:10<<30};header.CommandID="appdb-create-"+token;if receipt,commandErr:=provisioner.Commands.Handle(ctx,database.CreateDatabase{Header:header,Database:db});commandErr!=nil||receipt.Status!=database.OperationApplied{if commandErr==nil{commandErr=database.ErrInvalidReceipt};return DatabaseBinding{},commandErr};databaseRef,_:=database.NewSecretRef(databaseSecret.String());principal:=database.DatabasePrincipal{Metadata:database.Metadata{ID:principalID,TenantID:tenantID,SiteID:siteResourceID,Generation:1,Status:status},InstanceID:instance.ID,Name:principalName,HostScope:database.HostScopeLoopback,CredentialSecretRef:databaseRef};header.CommandID="appdb-principal-"+token;if receipt,commandErr:=provisioner.Commands.Handle(ctx,database.CreatePrincipal{Header:header,Principal:principal});commandErr!=nil||receipt.Status!=database.OperationApplied{if commandErr==nil{commandErr=database.ErrInvalidReceipt};return DatabaseBinding{},commandErr};grant:=database.Grant{Scope:database.GrantScopeDatabase,Privileges:[]database.Privilege{database.PrivilegeSelect,database.PrivilegeInsert,database.PrivilegeUpdate,database.PrivilegeDelete,database.PrivilegeCreate,database.PrivilegeAlter,database.PrivilegeIndex,database.PrivilegeDrop,database.PrivilegeCreateTemporary,database.PrivilegeExecute,database.PrivilegeCreateView,database.PrivilegeShowView,database.PrivilegeTrigger,database.PrivilegeEvent}};grantSet:=database.GrantSet{Metadata:database.Metadata{ID:grantID,TenantID:tenantID,SiteID:siteResourceID,Generation:1,Status:status},InstanceID:instance.ID,DatabaseID:databaseID,PrincipalID:principalID,Grants:[]database.Grant{grant}};header.CommandID="appdb-grant-"+token;if receipt,commandErr:=provisioner.Commands.Handle(ctx,database.ReplaceGrantSet{Header:header,GrantSet:grantSet});commandErr!=nil||receipt.Status!=database.OperationApplied{if commandErr==nil{commandErr=database.ErrInvalidReceipt};return DatabaseBinding{},commandErr};return DatabaseBinding{ID:DatabaseBindingID(databaseID.String()),Engine:"mariadb",DatabaseName:databaseName.String(),PrincipalName:principalName.String(),EndpointRef:"local-mariadb",PasswordRef:SecretRef(applicationSecret.String()),TLSRequired:true},nil}

func(provisioner *ApplicationDatabaseProvisioner)RevokeApplicationDatabase(ctx context.Context,bindingID DatabaseBindingID)error{if provisioner==nil||!validID(string(bindingID)){return ErrInvalid};databaseID,err:=database.NewResourceID(string(bindingID));if err!=nil{return ErrInvalid};envelope,err:=provisioner.Repository.LoadResource(ctx,database.KindDatabase,databaseID);if err!=nil{return err};decoded,err:=database.DecodeResource(envelope);if err!=nil{return err};db,ok:=decoded.(*database.Database);if !ok{return ErrIntegrity};token:=strings.TrimPrefix(databaseID.String(),"appdb-");principalID,_:=database.NewResourceID("appuser-"+token);principalEnvelope,err:=provisioner.Repository.LoadResource(ctx,database.KindPrincipal,principalID);if err!=nil&&!errors.Is(err,database.ErrNotFound){return err};tenantID:=db.TenantID;header:=database.CommandHeader{Actor:database.Actor{TenantID:tenantID,Capability:database.CapabilityTenantManage},TenantID:tenantID};if err==nil{resource,decodeErr:=database.DecodeResource(principalEnvelope);if decodeErr!=nil{return decodeErr};principal,ok:=resource.(*database.DatabasePrincipal);if !ok{return ErrIntegrity};header.CommandID="appdb-revoke-principal-"+token;if _,deleteErr:=provisioner.Commands.Handle(ctx,database.DeletePrincipal{Header:header,PrincipalID:principal.ID,ExpectedGeneration:principal.Generation});deleteErr!=nil{return deleteErr}};approval,_:=database.NewResourceID("application-removal-"+token);header.CommandID="appdb-revoke-database-"+token;_,err=provisioner.Commands.Handle(ctx,database.DeleteDatabase{Header:header,DatabaseID:db.ID,ExpectedGeneration:db.Generation,WaiveRecovery:true,ApprovalRef:approval});return err}

func applicationShortToken(value string)string{sum:=sha256.Sum256([]byte(value));return hex.EncodeToString(sum[:])[:32]}
func LinuxApplicationExecutorDigest()(string,error){file,err:=os.Open("/usr/local/libexec/cyberpanel/panel-execd");if err!=nil{return "",err};defer file.Close();hash:=sha256.New();copied,err:=io.Copy(hash,io.LimitReader(file,1<<30));if err!=nil||copied<=0||copied>=1<<30{return "",ErrIntegrity};return hex.EncodeToString(hash.Sum(nil)),nil}

var _ LinuxApplicationSecretSource=(*LinuxApplicationMaterialSource)(nil)
var _ SecretIssuer=(*ApplicationSecretIssuer)(nil)
var _ RandomTokenSource=CryptoRandomTokenSource{}
var _ DatabaseProvisioner=(*ApplicationDatabaseProvisioner)(nil)
