//go:build linux

package apps

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

const linuxApplicationSnapshotRoot = "/var/lib/cyberpanel/application-snapshots"

type linuxApplicationSnapshotManifest struct{Snapshot Snapshot `json:"snapshot"`;ArchiveDigest string `json:"archive_digest"`;DatabaseDigest string `json:"database_digest,omitempty"`}

func(runtime *LinuxApplicationRuntime)CreateApplicationSnapshot(ctx context.Context,request SnapshotRequest)(Snapshot,error){identifier:=SnapshotID("snapshot-"+linuxApplicationDigest(mustLinuxApplicationJSON(request))[:48]);return runtime.createSnapshot(ctx,request,identifier)}
func(runtime *LinuxApplicationRuntime)createSnapshot(ctx context.Context,request SnapshotRequest,identifier SnapshotID)(Snapshot,error){if !validID(string(identifier))||request.Scope.Validate()!=nil||!validID(string(request.Installation))||!request.IncludeFiles&&!request.IncludeDatabase||request.MaximumBytes==0||request.MaximumBytes>1<<40{return Snapshot{},ErrInvalid};scope,err:=runtime.resolve(ctx,request.Scope);if err!=nil{return Snapshot{},err};if err=os.MkdirAll(linuxApplicationSnapshotRoot,0700);err!=nil{return Snapshot{},err};if err=os.Chmod(linuxApplicationSnapshotRoot,0700);err!=nil{return Snapshot{},err};directory:=filepath.Join(linuxApplicationSnapshotRoot,string(identifier));if !strings.HasPrefix(directory,linuxApplicationSnapshotRoot+string(os.PathSeparator)){return Snapshot{},ErrPolicyDenied};if info,statErr:=os.Lstat(directory);statErr==nil{if !info.IsDir()||info.Mode()&os.ModeSymlink!=0{return Snapshot{},ErrConflict};return loadLinuxApplicationSnapshot(identifier)}else if !errors.Is(statErr,os.ErrNotExist){return Snapshot{},statErr};if err=os.Mkdir(directory,0700);err!=nil{return Snapshot{},err};generationRoot:=filepath.Join(linuxApplicationSitesRoot,scope.binding.SiteKey,"roots","g"+strconv.FormatUint(scope.binding.Generation,10));temporaryRoot:=filepath.Join(generationRoot,"tmp");archiveTemporary:=filepath.Join(temporaryRoot,"."+string(identifier)+".tar.gz");databaseTemporary:=filepath.Join(temporaryRoot,"."+string(identifier)+".sql");defer os.Remove(archiveTemporary);defer os.Remove(databaseTemporary);databaseDigest:="";if request.IncludeDatabase{if _,stderr,_,exportErr:=runtime.wp(ctx,scope,nil,2<<20,"db","export",databaseTemporary,"--single-transaction");exportErr!=nil{_ = os.RemoveAll(directory);return Snapshot{},fmt.Errorf("snapshot WordPress database: %w: %s",exportErr,stderr)};databaseDigest,err=digestLinuxApplicationFile(databaseTemporary,request.MaximumBytes);if err!=nil{_ = os.RemoveAll(directory);return Snapshot{},err}}
	args:=[]string{"-czf",archiveTemporary,"--numeric-owner","-C",scope.root};if request.IncludeFiles{args=append(args,".")}else{args=append(args,"--files-from","/dev/null")};if request.IncludeDatabase{args=append(args,"-C",temporaryRoot,filepath.Base(databaseTemporary))};if _,stderr,_,archiveErr:=runtime.command(ctx,linuxApplicationScope{binding:scope.binding,root:temporaryRoot},runtime.Tar,nil,2<<20,args...);archiveErr!=nil{_ = os.RemoveAll(directory);return Snapshot{},fmt.Errorf("archive application snapshot: %w: %s",archiveErr,stderr)};info,err:=os.Lstat(archiveTemporary);if err!=nil||!info.Mode().IsRegular()||info.Size()<=0||uint64(info.Size())>request.MaximumBytes{_ = os.RemoveAll(directory);return Snapshot{},ErrIntegrity};archiveDigest,err:=digestLinuxApplicationFile(archiveTemporary,request.MaximumBytes);if err!=nil{_ = os.RemoveAll(directory);return Snapshot{},err};archivePath:=filepath.Join(directory,"snapshot.tar.gz");if err=os.Rename(archiveTemporary,archivePath);err!=nil{_ = os.RemoveAll(directory);return Snapshot{},err};snapshot:=Snapshot{ID:identifier,InstallationID:request.Installation,Purpose:request.Purpose,ManifestDigest:archiveDigest,DatabaseDigest:databaseDigest,WriteFrontier:uint64(time.Now().UTC().UnixNano()),Stable:request.StableRequired,Size:uint64(info.Size()),CreatedAt:time.Now().UTC()};manifest:=linuxApplicationSnapshotManifest{snapshot,archiveDigest,databaseDigest};encoded,_:=json.Marshal(manifest);if err=os.WriteFile(filepath.Join(directory,"manifest.json"),encoded,0600);err!=nil{_ = os.RemoveAll(directory);return Snapshot{},err};return snapshot,nil}

func(runtime *LinuxApplicationRuntime)VerifyApplicationSnapshot(_ context.Context,identifier SnapshotID)error{snapshot,err:=loadLinuxApplicationSnapshot(identifier);if err!=nil{return err};directory:=filepath.Join(linuxApplicationSnapshotRoot,string(identifier));actual,err:=digestLinuxApplicationFile(filepath.Join(directory,"snapshot.tar.gz"),snapshot.Size+1);if err!=nil{return err};if actual!=snapshot.ManifestDigest{return ErrIntegrity};return nil}
func(runtime *LinuxApplicationRuntime)ReleaseApplicationSnapshot(_ context.Context,identifier SnapshotID)error{if !validID(string(identifier)){return ErrInvalid};directory:=filepath.Join(linuxApplicationSnapshotRoot,string(identifier));if !strings.HasPrefix(directory,linuxApplicationSnapshotRoot+string(os.PathSeparator)){return ErrPolicyDenied};return os.RemoveAll(directory)}
func loadLinuxApplicationSnapshot(identifier SnapshotID)(Snapshot,error){if !validID(string(identifier)){return Snapshot{},ErrInvalid};directory:=filepath.Join(linuxApplicationSnapshotRoot,string(identifier));info,err:=os.Lstat(directory);if err!=nil{return Snapshot{},err};if !info.IsDir()||info.Mode()&os.ModeSymlink!=0{return Snapshot{},ErrIntegrity};encoded,err:=os.ReadFile(filepath.Join(directory,"manifest.json"));if err!=nil{return Snapshot{},err};var manifest linuxApplicationSnapshotManifest;if json.Unmarshal(encoded,&manifest)!=nil||manifest.Snapshot.ID!=identifier||manifest.ArchiveDigest!=manifest.Snapshot.ManifestDigest{return Snapshot{},ErrIntegrity};return manifest.Snapshot,nil}

func(runtime *LinuxApplicationRuntime)CreateRecoveryPoint(ctx context.Context,input applicationRecoveryInput)(applicationRecoveryOutput,error){request:=input.Request;installation:=input.Installation;if request.InstallationID!=installation.ID||request.TenantID!=installation.TenantID||request.SiteID!=installation.SiteID||!validID(string(request.InstallationID)){return applicationRecoveryOutput{},ErrInvalid};binding,err:=runtime.Resolver.ResolveApplicationSite(ctx,installation.SiteID);if err!=nil{return applicationRecoveryOutput{},err};scope:=SiteExecutionScope{TenantID:installation.TenantID,SiteID:installation.SiteID,SiteUID:SiteUID(binding.UID),Root:installation.Root,IsolationProfile:"application-runtime",ResourceGeneration:binding.Generation};snapshotRequest:=SnapshotRequest{Scope:scope,Installation:installation.ID,Purpose:SnapshotPurpose("recovery_"+request.Purpose),IncludeFiles:true,IncludeDatabase:true,IncludeUploads:true,StableRequired:request.Consistency=="application_consistent",MaximumBytes:256<<30};identifier:=SnapshotID("recovery-"+linuxApplicationDigest(mustLinuxApplicationJSON(input))[:48]);snapshot,err:=runtime.createSnapshot(ctx,snapshotRequest,identifier);if err!=nil{return applicationRecoveryOutput{},err};return applicationRecoveryOutput{RecoveryPointID(snapshot.ID),snapshot.WriteFrontier},nil}
func(runtime *LinuxApplicationRuntime)VerifyRecoveryPoint(ctx context.Context,identifier RecoveryPointID)error{return runtime.VerifyApplicationSnapshot(ctx,SnapshotID(identifier))}

func digestLinuxApplicationFile(path string,maximum uint64)(string,error){file,err:=os.Open(path);if err!=nil{return "",err};defer file.Close();hash:=sha256.New();copied,err:=io.Copy(hash,io.LimitReader(file,int64(maximum)+1));if err!=nil||copied<=0||uint64(copied)>maximum{return "",ErrIntegrity};return hex.EncodeToString(hash.Sum(nil)),nil}
func mustLinuxApplicationJSON(value any)[]byte{encoded,_:=json.Marshal(value);return encoded}

var _ SnapshotProvider=(*LinuxApplicationRuntime)(nil)
