// Package controller connects durable site intents to node-wide LiteSpeed
// configuration composition, rendering, activation, and confirmation.
package controller

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"
	"sync"

	"github.com/aonsyed/cyberpanel/platform/internal/hosting/service"
	"github.com/aonsyed/cyberpanel/platform/internal/webengine"
	"github.com/aonsyed/cyberpanel/platform/internal/webengine/activation"
	"github.com/aonsyed/cyberpanel/platform/internal/webengine/composer"
	"github.com/aonsyed/cyberpanel/platform/internal/webengine/native"
)

var (
	ErrInvalidIntent      = errors.New("invalid site effect intent")
	ErrUnsupportedEdition = errors.New("unsupported web engine edition")
	ErrActivationRejected = errors.New("web engine activation was rolled back")
	ErrActivationUnknown  = errors.New("web engine activation outcome is ambiguous")
)

// ChangeToken identifies one durable projection-catalog mutation. Its value is
// generated by the catalog, not accepted from an API caller.
type ChangeToken struct{ value string }

func NewChangeToken(value string) (ChangeToken, error) {
	if !safeToken(value) {
		return ChangeToken{}, errors.New("invalid catalog change token")
	}
	return ChangeToken{value: value}, nil
}

func (token ChangeToken) String() string { return token.value }

// PreparedPlan is a complete, durable node view that includes the requested
// site mutation. The catalog must return the same token and plan for a retry of
// the same effect ID until Finalize or Reject succeeds.
type PreparedPlan struct {
	Token ChangeToken
	Plan  composer.Plan
}

// PlanCatalog is the single writer for site projections and node snapshot
// generations. Prepare must durably record the accepted effect before it
// returns. Finalize and Reject are idempotent.
type PlanCatalog interface {
	Prepare(context.Context, service.SiteEffectRequest) (PreparedPlan, error)
	Finalize(context.Context, ChangeToken, string) error
	Reject(context.Context, ChangeToken, string) error
}

// Activator is implemented by activation.Activator. It deliberately accepts a
// complete generation rather than paths or native commands.
type Activator interface {
	Apply(context.Context, native.ConfigGeneration) (activation.Receipt, error)
}

// VerifiedActivator is the privileged production boundary. The unprivileged
// controller supplies the closed desired-state snapshot and the digest it
// independently rendered; the privileged implementation re-renders from the
// typed snapshot and refuses a digest mismatch before touching native files.
// Activator remains supported for isolated in-process qualification fixtures.
type VerifiedActivator interface {
	ApplyVerified(context.Context, native.RenderRequest, string) (activation.Receipt, error)
}

// CandidatePreparation owns host work surrounding node activation. It writes
// the digest-bound health attestation before probing and defers irreversible
// withdrawal cleanup until the new node generation has been confirmed.
type CandidatePreparation interface {
	BeforeActivation(context.Context, string, string) error
	AfterActivation(context.Context, string, string) error
	CompensateCandidate(context.Context, string) error
}

type Controller struct {
	catalog    PlanCatalog
	activator  Activator
	preparation CandidatePreparation
	renderers  map[webengine.Edition]native.Renderer
	activation sync.Mutex
}

func New(catalog PlanCatalog, activator Activator, preparation CandidatePreparation, renderers ...native.Renderer) (*Controller, error) {
	if nilInterface(catalog) || nilInterface(activator) || nilInterface(preparation) {
		return nil, errors.New("catalog, activator, and candidate preparation are required")
	}
	byEdition := make(map[webengine.Edition]native.Renderer, len(renderers))
	for _, renderer := range renderers {
		if nilInterface(renderer) {
			return nil, errors.New("renderer is required")
		}
		edition := renderer.Edition()
		if edition != webengine.EditionOpenLiteSpeed && edition != webengine.EditionLiteSpeedEnterprise {
			return nil, fmt.Errorf("%w: %q", ErrUnsupportedEdition, edition)
		}
		if _, exists := byEdition[edition]; exists {
			return nil, fmt.Errorf("duplicate renderer for %s", edition)
		}
		byEdition[edition] = renderer
	}
	if len(byEdition) != 2 {
		return nil, errors.New("both OpenLiteSpeed and LiteSpeed Enterprise renderers are required")
	}
	return &Controller{catalog: catalog, activator: activator, preparation: preparation, renderers: byEdition}, nil
}

// ObserveOrApply implements hosting/service.SiteEffectDriver. One controller
// serializes node-wide generations; cross-process serialization belongs to the
// durable PlanCatalog's single-writer transaction.
func (controller *Controller) ObserveOrApply(ctx context.Context, request service.SiteEffectRequest) (service.SiteEffectReceipt, error) {
	receipt := baseReceipt(request)
	if controller == nil || nilInterface(controller.catalog) || nilInterface(controller.activator) || nilInterface(controller.preparation) || nilInterface(ctx) {
		receipt.Outcome = service.EffectAmbiguous
		return receipt, ErrInvalidIntent
	}
	if !validRequest(request) {
		receipt.Outcome = service.EffectRejected
		return receipt, ErrInvalidIntent
	}

	controller.activation.Lock()
	defer controller.activation.Unlock()

	prepared, err := controller.catalog.Prepare(ctx, request)
	if err != nil {
		receipt.Outcome = service.EffectAmbiguous
		return receipt, fmt.Errorf("prepare node plan: %w", err)
	}
	if prepared.Token.String() == "" {
		receipt.Outcome = service.EffectAmbiguous
		return receipt, errors.New("projection catalog returned an empty change token")
	}

	composed, err := composer.Compose(prepared.Plan)
	if err != nil {
		return controller.reject(ctx, prepared.Token, receipt, fmt.Errorf("compose node state: %w", err))
	}
	renderer, exists := controller.renderers[composed.Desired.Engine.Edition]
	if !exists {
		return controller.reject(ctx, prepared.Token, receipt, ErrUnsupportedEdition)
	}
	generation, err := renderer.Render(ctx, native.RenderRequest{Desired: composed.Desired, Snapshot: composed.Snapshot})
	if err != nil {
		return controller.reject(ctx, prepared.Token, receipt, fmt.Errorf("render node state: %w", err))
	}
	if err := controller.preparation.BeforeActivation(ctx, request.EffectID, generation.ContentDigest); err != nil {
		return controller.reject(ctx, prepared.Token, receipt, fmt.Errorf("prepare candidate health: %w", err))
	}
	var activated activation.Receipt
	var activationErr error
	if verified, ok := controller.activator.(VerifiedActivator); ok {
		activated, activationErr = verified.ApplyVerified(ctx, native.RenderRequest{Desired: composed.Desired, Snapshot: composed.Snapshot}, generation.ContentDigest)
	} else {
		activated, activationErr = controller.activator.Apply(ctx, generation)
	}
	switch activated.Status {
	case activation.Applied:
		if activationErr != nil || !activated.Confirmed || activated.Digest != generation.ContentDigest {
			receipt.Outcome = service.EffectAmbiguous
			return receipt, errors.Join(ErrActivationUnknown, activationErr)
		}
		if err := controller.preparation.AfterActivation(ctx, request.EffectID, activated.Digest); err != nil {
			receipt.Outcome = service.EffectAmbiguous
			return receipt, fmt.Errorf("commit host preparation: %w", err)
		}
		if err := controller.catalog.Finalize(ctx, prepared.Token, activated.Digest); err != nil {
			receipt.Outcome = service.EffectAmbiguous
			return receipt, fmt.Errorf("finalize node plan: %w", err)
		}
		receipt.Outcome = service.EffectConfirmed
		receipt.ProbeDigest = activated.Digest
		return receipt, nil
	case activation.RolledBack:
		return controller.reject(ctx, prepared.Token, receipt, errors.Join(ErrActivationRejected, activationErr))
	default:
		receipt.Outcome = service.EffectAmbiguous
		return receipt, errors.Join(ErrActivationUnknown, activationErr)
	}
}

func (controller *Controller) reject(ctx context.Context, token ChangeToken, receipt service.SiteEffectReceipt, cause error) (service.SiteEffectReceipt, error) {
	receipt.Outcome = service.EffectRejected
	if err := controller.preparation.CompensateCandidate(ctx, receipt.EffectID); err != nil {
		receipt.Outcome = service.EffectAmbiguous
		return receipt, errors.Join(cause, fmt.Errorf("compensate host preparation: %w", err))
	}
	if err := controller.catalog.Reject(ctx, token, receipt.EffectID); err != nil {
		receipt.Outcome = service.EffectAmbiguous
		return receipt, errors.Join(cause, fmt.Errorf("reject node plan: %w", err))
	}
	return receipt, cause
}

func baseReceipt(request service.SiteEffectRequest) service.SiteEffectReceipt {
	return service.SiteEffectReceipt{
		EffectID:         request.EffectID,
		Scope:            request.Scope,
		ProjectionDigest: request.ProjectionDigest,
		Generation:       request.Projection.Generation,
	}
}

func validRequest(request service.SiteEffectRequest) bool {
	return safeToken(request.EffectID) &&
		request.Scope.TenantID.String() != "" && request.Scope.SiteID.String() != "" &&
		request.Projection.Generation != 0 && len(request.Projection.Bindings) != 0 &&
		len(request.ProjectionDigest) == 64 && strings.Trim(request.ProjectionDigest, "0123456789abcdef") == ""
}

func safeToken(value string) bool {
	if value == "" || len(value) > 160 {
		return false
	}
	for _, character := range value {
		if (character < 'a' || character > 'z') && (character < 'A' || character > 'Z') &&
			(character < '0' || character > '9') && character != '-' && character != '_' && character != '.' {
			return false
		}
	}
	return true
}

func nilInterface(value any) bool {
	if value == nil {
		return true
	}
	reflected := reflect.ValueOf(value)
	switch reflected.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return reflected.IsNil()
	default:
		return false
	}
}
