package mail

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strconv"
	"strings"
	"time"
)

type AutoresponderProgramMode string

const (
	AutoresponderProgramInstall AutoresponderProgramMode = "install"
	AutoresponderProgramRemove AutoresponderProgramMode = "remove"
)

type AutoresponderSieveProgram struct {
	RuleID AutoresponderID `json:"rule_id"`
	Generation uint64 `json:"generation"`
	Mode AutoresponderProgramMode `json:"mode"`
	Enabled bool `json:"enabled"`
	Script string `json:"script,omitempty"`
	Digest string `json:"digest"`
}

type AutoresponderSieveRequest struct {
	OperationID string
	TenantID string
	DomainID DomainID
	MailboxID MailboxID
	MailboxGeneration uint64
	ExpectedDigest string
	Program AutoresponderSieveProgram
	Rollback bool
}

type AutoresponderSieveReceipt struct {
	OperationID string
	TenantID string
	DomainID DomainID
	RuleID AutoresponderID
	MailboxID MailboxID
	MailboxGeneration uint64
	RuleGeneration uint64
	Mode AutoresponderProgramMode
	PriorDigest string
	AppliedDigest string
	ObservedDigest string
	Confirmed bool
	ObservedAt time.Time
}

// AutoresponderSieveRuntime accepts only compiler-produced closed programs.
// Apply is a digest CAS. It returns ErrConflict without changing runtime state
// when ExpectedDigest is stale. Rollback may confirm an already-restored target.
type AutoresponderSieveRuntime interface {
	ApplyAutoresponder(context.Context, AutoresponderSieveRequest) (AutoresponderSieveReceipt, error)
}

func CompileAutoresponderSieve(rule AutoresponderRule) (AutoresponderSieveProgram, error) {
	if err := validateAutoresponderRule(rule, false); err != nil {
		return AutoresponderSieveProgram{}, err
	}
	var script bytes.Buffer
	if !rule.Enabled {
		script.WriteString("# Generated by CyberPanel; user Sieve is not accepted.\nkeep;\n")
	} else {
		script.WriteString("require [\"date\", \"envelope\", \"relational\", \"subaddress\", \"vacation\", \"vacation-seconds\"];\n")
		script.WriteString("if allof (\n")
		conditions := autoresponderSieveConditions(rule)
		for index, condition := range conditions {
			script.WriteString("  ")
			script.WriteString(condition)
			if index+1 < len(conditions) {
				script.WriteByte(',')
			}
			script.WriteByte('\n')
		}
		script.WriteString(") {\n")
		fmt.Fprintf(&script, "  vacation :seconds %d :subject %s :from %s :addresses [%s] text:\n", int64(rule.Settings.RepeatInterval/time.Second), sieveQuoted(rule.Settings.Subject), sieveQuoted(string(rule.MailboxAddress)), sieveQuoted(string(rule.MailboxAddress)))
		script.WriteString(sieveMultiline(rule.Settings.Body))
		script.WriteString(".\n;\n}\n")
	}
	if script.Len() == 0 || script.Len() > 64<<10 {
		return AutoresponderSieveProgram{}, ErrInvalidCommand
	}
	program := AutoresponderSieveProgram{
		RuleID: rule.ID,
		Generation: rule.Generation,
		Mode: AutoresponderProgramInstall,
		Enabled: rule.Enabled,
		Script: script.String(),
	}
	program.Digest = autoresponderProgramDigest(rule.TenantID, rule.DomainID, rule.MailboxID, program)
	return program, program.Validate(rule.TenantID, rule.DomainID, rule.MailboxID)
}

func RemovedAutoresponderSieveProgram(tenant string, domainID DomainID, mailboxID MailboxID, ruleID AutoresponderID, generation uint64) (AutoresponderSieveProgram, error) {
	if !validOpaque(tenant) || !validOpaque(string(domainID)) || !validOpaque(string(mailboxID)) || !validOpaque(string(ruleID)) || generation > AutoresponderMaximumGeneration {
		return AutoresponderSieveProgram{}, ErrInvalidCommand
	}
	program := AutoresponderSieveProgram{RuleID: ruleID, Generation: generation, Mode: AutoresponderProgramRemove}
	program.Digest = autoresponderProgramDigest(tenant, domainID, mailboxID, program)
	return program, program.Validate(tenant, domainID, mailboxID)
}

func (program AutoresponderSieveProgram) Validate(tenant string, domainID DomainID, mailboxID MailboxID) error {
	if !validOpaque(tenant) || !validOpaque(string(domainID)) || !validOpaque(string(mailboxID)) || !validOpaque(string(program.RuleID)) || program.Generation > AutoresponderMaximumGeneration || !validAutoresponderDigest(program.Digest) {
		return ErrInvalidCommand
	}
	switch program.Mode {
	case AutoresponderProgramInstall:
		if program.Generation == 0 || len(program.Script) == 0 || len(program.Script) > 64<<10 || strings.ContainsRune(program.Script, '\x00') {
			return ErrInvalidCommand
		}
	case AutoresponderProgramRemove:
		if program.Enabled || program.Script != "" {
			return ErrInvalidCommand
		}
	default:
		return ErrInvalidCommand
	}
	if autoresponderProgramDigest(tenant, domainID, mailboxID, program) != program.Digest {
		return ErrInvalidCommand
	}
	return nil
}

func autoresponderSieveConditions(rule AutoresponderRule) []string {
	self := sieveQuoted(string(rule.MailboxAddress))
	addressParts := strings.SplitN(string(rule.MailboxAddress), "@", 2)
	selfUser := sieveQuoted(strings.SplitN(addressParts[0], "+", 2)[0])
	selfDomain := sieveQuoted(addressParts[1])
	conditions := []string{
		"not envelope :is \"from\" \"\"",
		"not envelope :is \"from\" " + self,
		"not address :all :is \"from\" " + self,
		"not allof (envelope :user :is \"from\" " + selfUser + ", envelope :domain :is \"from\" " + selfDomain + ")",
		"not allof (address :user :is \"from\" " + selfUser + ", address :domain :is \"from\" " + selfDomain + ")",
		"anyof (not exists \"Auto-Submitted\", header :is \"Auto-Submitted\" \"no\")",
		"not header :is \"Precedence\" [\"bulk\", \"list\", \"junk\"]",
		"not exists [\"List-Id\", \"List-Help\", \"List-Subscribe\", \"List-Unsubscribe\", \"List-Post\", \"List-Owner\", \"List-Archive\", \"Mailing-List\", \"X-Mailing-List\"]",
		"not anyof (header :contains \"Content-Type\" \"multipart/report\", header :contains \"Content-Type\" \"message/delivery-status\", exists [\"X-Failed-Recipients\", \"Original-Recipient\", \"Final-Recipient\", \"Diagnostic-Code\"])",
	}
	if rule.Settings.StartAt != nil {
		conditions = append(conditions, "currentdate :zone \"+0000\" :value \"ge\" \"iso8601\" "+sieveQuoted(autoresponderSieveTime(*rule.Settings.StartAt)))
	}
	if rule.Settings.EndAt != nil {
		conditions = append(conditions, "currentdate :zone \"+0000\" :value \"lt\" \"iso8601\" "+sieveQuoted(autoresponderSieveTime(*rule.Settings.EndAt)))
	}
	if len(rule.Settings.Senders.Allow) != 0 {
		conditions = append(conditions, "envelope :is \"from\" "+sieveStringList(rule.Settings.Senders.Allow))
	}
	if len(rule.Settings.Senders.Deny) != 0 {
		conditions = append(conditions, "not envelope :is \"from\" "+sieveStringList(rule.Settings.Senders.Deny))
	}
	if len(rule.Settings.Senders.ExcludedDomains) != 0 {
		conditions = append(conditions, "not envelope :domain :is \"from\" "+sieveRawStringList(rule.Settings.Senders.ExcludedDomains))
	}
	return conditions
}

func autoresponderProgramDigest(tenant string, domainID DomainID, mailboxID MailboxID, program AutoresponderSieveProgram) string {
	generation := strconv.FormatUint(program.Generation, 10)
	if program.Mode == AutoresponderProgramRemove {
		generation = "removed"
	}
	digest := sha256.Sum256([]byte("mail-autoresponder-sieve-v1\x00" + tenant + "\x00" + string(domainID) + "\x00" + string(mailboxID) + "\x00" + string(program.RuleID) + "\x00" + generation + "\x00" + string(program.Mode) + "\x00" + strconv.FormatBool(program.Enabled) + "\x00" + program.Script))
	return hex.EncodeToString(digest[:])
}

func validAutoresponderDigest(value string) bool {
	if len(value) != 64 || value != strings.ToLower(value) {
		return false
	}
	_, err := hex.DecodeString(value)
	return err == nil
}

func validAutoresponderSieveReceipt(receipt AutoresponderSieveReceipt, request AutoresponderSieveRequest) bool {
	priorMatches := receipt.PriorDigest == request.ExpectedDigest
	if request.Rollback {
		priorMatches = priorMatches || receipt.PriorDigest == request.Program.Digest
	}
	return validAutoresponderDigest(request.ExpectedDigest) && receipt.OperationID == request.OperationID && receipt.TenantID == request.TenantID && receipt.DomainID == request.DomainID && receipt.RuleID == request.Program.RuleID && receipt.MailboxID == request.MailboxID && receipt.MailboxGeneration == request.MailboxGeneration && receipt.RuleGeneration == request.Program.Generation && receipt.Mode == request.Program.Mode && priorMatches && receipt.AppliedDigest == request.Program.Digest && receipt.ObservedDigest == request.Program.Digest && receipt.Confirmed && !receipt.ObservedAt.IsZero()
}

func sieveQuoted(value string) string {
	value = strings.ReplaceAll(value, "\\", "\\\\")
	value = strings.ReplaceAll(value, "\"", "\\\"")
	return "\"" + value + "\""
}

func sieveStringList(values []Address) string {
	stringsList := make([]string, len(values))
	for index, value := range values {
		stringsList[index] = string(value)
	}
	return sieveRawStringList(stringsList)
}

func sieveRawStringList(values []string) string {
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = sieveQuoted(value)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func sieveMultiline(value string) string {
	var output strings.Builder
	for _, line := range strings.Split(value, "\n") {
		if strings.HasPrefix(line, ".") {
			output.WriteByte('.')
		}
		output.WriteString(line)
		output.WriteByte('\n')
	}
	return output.String()
}

func autoresponderSieveTime(value time.Time) string {
	return value.UTC().Format("2006-01-02T15:04:05-0700")
}
