package mail

import (
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"database/sql"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"
)

type ConsentReason string
const ( ConsentOptIn ConsentReason="opt_in"; ConsentResubscribe ConsentReason="resubscribe"; ConsentImport ConsentReason="verified_import" )
type SuppressionReason string
const ( SuppressionUnsubscribe SuppressionReason="unsubscribe"; SuppressionComplaint SuppressionReason="complaint"; SuppressionGlobalDNC SuppressionReason="global_do_not_contact"; SuppressionHardBounce SuppressionReason="hard_bounce"; SuppressionTransient SuppressionReason="transient"; SuppressionAdministrative SuppressionReason="administrative" )
type ConsentEvent struct { ID string `json:"id"`; TenantID string `json:"tenant_id"`; ContactID ContactID `json:"contact_id"`; Address Address `json:"address"`; State ConsentState `json:"state"`; ConsentReason ConsentReason `json:"consent_reason,omitempty"`; SuppressionReason SuppressionReason `json:"suppression_reason,omitempty"`; EvidenceRef string `json:"evidence_ref"`; At time.Time `json:"at"` }
type CampaignAttempt struct { ID AttemptID `json:"id"`; TenantID string `json:"tenant_id"`; CampaignID CampaignID `json:"campaign_id"`; ContactID ContactID `json:"contact_id"`; Address Address `json:"address"`; IdempotencyKey string `json:"idempotency_key"`; State string `json:"state"`; QueueID QueueID `json:"queue_id,omitempty"`; Detail string `json:"detail,omitempty"`; Attempts uint32 `json:"attempts"`; NextAttempt time.Time `json:"next_attempt,omitempty"`; UpdatedAt time.Time `json:"updated_at"` }
type MarketingSender interface { SubmitCampaign(context.Context,string,Campaign,CampaignRecipient,string)(QueueID,error) }
type MarketingStore struct { DB *sql.DB }
const marketingSchema=`CREATE TABLE IF NOT EXISTS marketing_subscribers_v2(id TEXT NOT NULL,tenant_id TEXT NOT NULL,address TEXT NOT NULL,generation INTEGER NOT NULL,state TEXT NOT NULL,subscriber_json BLOB NOT NULL,updated_at TIMESTAMP NOT NULL,PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,address));CREATE INDEX IF NOT EXISTS marketing_subscribers_list ON marketing_subscribers_v2(tenant_id,state,id);CREATE TABLE IF NOT EXISTS marketing_consent_events_v2(id TEXT NOT NULL,tenant_id TEXT NOT NULL,contact_id TEXT NOT NULL,address TEXT NOT NULL,state TEXT NOT NULL,event_json BLOB NOT NULL,occurred_at TIMESTAMP NOT NULL,PRIMARY KEY(tenant_id,id));CREATE INDEX IF NOT EXISTS marketing_consent_current ON marketing_consent_events_v2(tenant_id,address,occurred_at);CREATE INDEX IF NOT EXISTS marketing_consent_list ON marketing_consent_events_v2(tenant_id,state,id);CREATE TABLE IF NOT EXISTS marketing_lists_v2(id TEXT NOT NULL,tenant_id TEXT NOT NULL,list_json BLOB NOT NULL,PRIMARY KEY(tenant_id,id));CREATE INDEX IF NOT EXISTS marketing_lists_list ON marketing_lists_v2(tenant_id,id);CREATE TABLE IF NOT EXISTS marketing_templates_v2(id TEXT NOT NULL,tenant_id TEXT NOT NULL,generation INTEGER NOT NULL,state TEXT NOT NULL,template_json BLOB NOT NULL,updated_at TIMESTAMP NOT NULL,PRIMARY KEY(tenant_id,id,generation));CREATE INDEX IF NOT EXISTS marketing_templates_list ON marketing_templates_v2(tenant_id,id,generation);CREATE TABLE IF NOT EXISTS marketing_campaigns_v2(id TEXT NOT NULL,tenant_id TEXT NOT NULL,state TEXT NOT NULL,campaign_json BLOB NOT NULL,PRIMARY KEY(tenant_id,id));CREATE INDEX IF NOT EXISTS marketing_campaigns_list ON marketing_campaigns_v2(tenant_id,state,id);CREATE TABLE IF NOT EXISTS marketing_campaign_snapshots_v2(id TEXT NOT NULL,tenant_id TEXT NOT NULL,campaign_id TEXT NOT NULL,snapshot_json BLOB NOT NULL,created_at TIMESTAMP NOT NULL,PRIMARY KEY(tenant_id,campaign_id,id));CREATE TABLE IF NOT EXISTS marketing_campaign_snapshot_recipients_v2(snapshot_id TEXT NOT NULL,tenant_id TEXT NOT NULL,campaign_id TEXT NOT NULL,contact_id TEXT NOT NULL,address TEXT NOT NULL,recipient_json BLOB NOT NULL,PRIMARY KEY(tenant_id,campaign_id,snapshot_id,contact_id),UNIQUE(tenant_id,campaign_id,snapshot_id,address));CREATE INDEX IF NOT EXISTS marketing_campaign_snapshot_lookup ON marketing_campaign_snapshot_recipients_v2(tenant_id,campaign_id,snapshot_id,contact_id);CREATE TABLE IF NOT EXISTS marketing_attempts_v2(id TEXT NOT NULL,tenant_id TEXT NOT NULL,campaign_id TEXT NOT NULL,contact_id TEXT NOT NULL,idempotency_key TEXT NOT NULL,state TEXT NOT NULL,next_attempt TIMESTAMP,attempt_json BLOB NOT NULL,updated_at TIMESTAMP NOT NULL,PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,idempotency_key));CREATE INDEX IF NOT EXISTS marketing_attempts_list ON marketing_attempts_v2(tenant_id,campaign_id,state,next_attempt,id);`
func (s MarketingStore)Bootstrap(ctx context.Context)error{if s.DB==nil{return errors.New("marketing database required")};_,err:=s.DB.ExecContext(ctx,marketingSchema);return err}
func (s MarketingStore)RecordConsent(ctx context.Context,event ConsentEvent)error{if s.DB==nil{return errors.New("marketing database required")};event.Address=canonicalMarketingAddress(event.Address);if !validOpaque(event.ID)||!validOpaque(event.TenantID)||event.ContactID==""||ValidateAddress(event.Address)!=nil||event.At.IsZero()||!validOpaque(event.EvidenceRef){return ErrInvalidCommand};switch event.State{case Consented:if event.ConsentReason!=ConsentOptIn&&event.ConsentReason!=ConsentResubscribe&&event.ConsentReason!=ConsentImport{return ErrInvalidCommand};if event.SuppressionReason!=""{return ErrInvalidCommand};case Suppressed:if !validSuppression(event.SuppressionReason)||event.ConsentReason!=""{return ErrInvalidCommand};default:return ErrInvalidCommand};if err:=s.validateConsentSubscriberBinding(ctx,event);err!=nil{return err};raw,err:=json.Marshal(event);if err!=nil{return err};_,err=s.DB.ExecContext(ctx,`INSERT INTO marketing_consent_events_v2(id,tenant_id,contact_id,address,state,event_json,occurred_at) VALUES(?,?,?,?,?,?,?)`,event.ID,event.TenantID,event.ContactID,event.Address,event.State,raw,event.At.UTC());return err}
func (s MarketingStore)CurrentConsent(ctx context.Context,tenant string,address Address)(ConsentEvent,bool,error){if s.DB==nil{return ConsentEvent{},false,errors.New("marketing database required")};address=canonicalMarketingAddress(address);if !validOpaque(tenant)||ValidateAddress(address)!=nil{return ConsentEvent{},false,ErrInvalidCommand};var raw []byte;err:=s.DB.QueryRowContext(ctx,`SELECT event_json FROM marketing_consent_events_v2 WHERE tenant_id=? AND address=? ORDER BY occurred_at DESC,id DESC LIMIT 1`,tenant,address).Scan(&raw);if errors.Is(err,sql.ErrNoRows){return ConsentEvent{},false,nil};if err!=nil{return ConsentEvent{},false,err};var event ConsentEvent;if err=strictJSON(raw,&event);err!=nil||event.TenantID!=tenant||event.Address!=address{return ConsentEvent{},false,errors.Join(ErrInvalidReceipt,err)};return event,true,nil}
func (s MarketingStore)PutList(ctx context.Context,tenant string,list List)error{if s.DB==nil{return errors.New("marketing database required")};if !validOpaque(tenant)||!validOpaque(string(list.ID))||len(list.Name)<1||len(list.Name)>256||strings.ContainsAny(list.Name,"\x00\r\n")||len(list.Contacts)>100000{return ErrInvalidCommand};seen:=map[ContactID]bool{};for _,contact:=range list.Contacts{if !validOpaque(string(contact))||seen[contact]{return ErrInvalidCommand};seen[contact]=true};if err:=s.validateListSubscribers(ctx,tenant,list.Contacts);err!=nil{return err};raw,err:=json.Marshal(list);if err!=nil{return err};_,err=s.DB.ExecContext(ctx,`INSERT INTO marketing_lists_v2(id,tenant_id,list_json) VALUES(?,?,?) ON CONFLICT(tenant_id,id) DO UPDATE SET list_json=excluded.list_json`,list.ID,tenant,raw);return err}
func (s MarketingStore)ListByID(ctx context.Context,tenant string,id ListID)(List,bool,error){if s.DB==nil{return List{},false,errors.New("marketing database required")};var raw []byte;err:=s.DB.QueryRowContext(ctx,`SELECT list_json FROM marketing_lists_v2 WHERE tenant_id=? AND id=?`,tenant,id).Scan(&raw);if errors.Is(err,sql.ErrNoRows){return List{},false,nil};if err!=nil{return List{},false,err};var list List;if err=strictJSON(raw,&list);err!=nil{return List{},false,err};return list,true,nil}
func (s MarketingStore)Lists(ctx context.Context,tenant string,limit int,cursor string)([]List,string,error){if s.DB==nil{return nil,"",errors.New("marketing database required")};if limit<1||limit>500{limit=100};after,err:=decodeCursor(cursor);if err!=nil{return nil,"",err};rows,err:=s.DB.QueryContext(ctx,`SELECT id,list_json FROM marketing_lists_v2 WHERE tenant_id=? AND id>? ORDER BY id LIMIT ?`,tenant,after,limit+1);if err!=nil{return nil,"",err};defer rows.Close();items:=make([]List,0,limit+1);ids:=make([]string,0,limit+1);for rows.Next(){var id string;var raw []byte;if err=rows.Scan(&id,&raw);err!=nil{return nil,"",err};var item List;if err=strictJSON(raw,&item);err!=nil{return nil,"",err};items=append(items,item);ids=append(ids,id)};if err=rows.Err();err!=nil{return nil,"",err};next:="";if len(items)>limit{next=base64.RawURLEncoding.EncodeToString([]byte(ids[limit-1]));items=items[:limit]};return items,next,nil}
func (s MarketingStore)DeleteList(ctx context.Context,tenant string,id ListID)error{if s.DB==nil{return errors.New("marketing database required")};result,err:=s.DB.ExecContext(ctx,`DELETE FROM marketing_lists_v2 WHERE tenant_id=? AND id=?`,tenant,id);if err!=nil{return err};affected,err:=result.RowsAffected();if err!=nil{return err};if affected!=1{return ErrNotFound};return nil}
func (s MarketingStore)PutCampaign(ctx context.Context,tenant string,campaign Campaign)error{if s.DB==nil{return errors.New("marketing database required")};if validateCampaignRecord(tenant,campaign)!=nil{return ErrInvalidCommand};raw,err:=json.Marshal(campaign);if err!=nil{return err};_,err=s.DB.ExecContext(ctx,`INSERT INTO marketing_campaigns_v2(id,tenant_id,state,campaign_json) VALUES(?,?,?,?) ON CONFLICT(tenant_id,id) DO UPDATE SET state=excluded.state,campaign_json=excluded.campaign_json`,campaign.ID,tenant,campaign.State,raw);return err}
func (s MarketingStore)CreateCampaign(ctx context.Context,tenant string,campaign Campaign)error{if s.DB==nil{return errors.New("marketing database required")};if campaign.Generation!=1||validateCampaignRecord(tenant,campaign)!=nil{return ErrInvalidCommand};raw,err:=json.Marshal(campaign);if err!=nil{return err};_,err=s.DB.ExecContext(ctx,`INSERT INTO marketing_campaigns_v2(id,tenant_id,state,campaign_json) VALUES(?,?,?,?)`,campaign.ID,tenant,campaign.State,raw);return err}
func (s MarketingStore)AdvanceCampaign(ctx context.Context,tenant string,campaign Campaign,expected uint64)error{if s.DB==nil{return errors.New("marketing database required")};if expected==0||campaign.Generation!=expected+1||validateCampaignRecord(tenant,campaign)!=nil{return ErrInvalidCommand};var priorRaw []byte;if err:=s.DB.QueryRowContext(ctx,`SELECT campaign_json FROM marketing_campaigns_v2 WHERE tenant_id=? AND id=?`,tenant,campaign.ID).Scan(&priorRaw);err!=nil{if errors.Is(err,sql.ErrNoRows){return ErrNotFound};return err};var prior Campaign;if err:=strictJSON(priorRaw,&prior);err!=nil{return err};if prior.Generation!=expected{return ErrConflict};raw,err:=json.Marshal(campaign);if err!=nil{return err};result,err:=s.DB.ExecContext(ctx,`UPDATE marketing_campaigns_v2 SET state=?,campaign_json=? WHERE tenant_id=? AND id=? AND campaign_json=?`,campaign.State,raw,tenant,campaign.ID,priorRaw);if err!=nil{return err};affected,err:=result.RowsAffected();if err!=nil{return err};if affected!=1{return ErrConflict};return nil}
func (s MarketingStore)Campaign(ctx context.Context,tenant string,id CampaignID)(Campaign,bool,error){if s.DB==nil{return Campaign{},false,errors.New("marketing database required")};var raw []byte;err:=s.DB.QueryRowContext(ctx,`SELECT campaign_json FROM marketing_campaigns_v2 WHERE tenant_id=? AND id=?`,tenant,id).Scan(&raw);if errors.Is(err,sql.ErrNoRows){return Campaign{},false,nil};if err!=nil{return Campaign{},false,err};var campaign Campaign;if err=strictJSON(raw,&campaign);err!=nil{return Campaign{},false,err};return campaign,true,nil}
func (s MarketingStore)Campaigns(ctx context.Context,tenant string,limit int,cursor string)([]Campaign,string,error){if s.DB==nil{return nil,"",errors.New("marketing database required")};if limit<1||limit>500{limit=100};after,err:=decodeCursor(cursor);if err!=nil{return nil,"",err};rows,err:=s.DB.QueryContext(ctx,`SELECT id,campaign_json FROM marketing_campaigns_v2 WHERE tenant_id=? AND id>? ORDER BY id LIMIT ?`,tenant,after,limit+1);if err!=nil{return nil,"",err};defer rows.Close();items:=make([]Campaign,0,limit+1);ids:=make([]string,0,limit+1);for rows.Next(){var id string;var raw []byte;if err=rows.Scan(&id,&raw);err!=nil{return nil,"",err};var item Campaign;if err=strictJSON(raw,&item);err!=nil{return nil,"",err};items=append(items,item);ids=append(ids,id)};if err=rows.Err();err!=nil{return nil,"",err};next:="";if len(items)>limit{next=base64.RawURLEncoding.EncodeToString([]byte(ids[limit-1]));items=items[:limit]};return items,next,nil}
func (s MarketingStore)DeleteCampaign(ctx context.Context,tenant string,id CampaignID)error{if s.DB==nil{return errors.New("marketing database required")};result,err:=s.DB.ExecContext(ctx,`DELETE FROM marketing_campaigns_v2 WHERE tenant_id=? AND id=?`,tenant,id);if err!=nil{return err};affected,err:=result.RowsAffected();if err!=nil{return err};if affected!=1{return ErrNotFound};return nil}
func (s MarketingStore)DeleteCampaignGeneration(ctx context.Context,tenant string,id CampaignID,expected uint64)error{if s.DB==nil{return errors.New("marketing database required")};if expected==0{return ErrInvalidCommand};var raw []byte;if err:=s.DB.QueryRowContext(ctx,`SELECT campaign_json FROM marketing_campaigns_v2 WHERE tenant_id=? AND id=?`,tenant,id).Scan(&raw);err!=nil{if errors.Is(err,sql.ErrNoRows){return ErrNotFound};return err};var campaign Campaign;if err:=strictJSON(raw,&campaign);err!=nil{return err};if campaign.Generation!=expected||campaign.State!="draft"&&campaign.State!="cancelled"&&campaign.State!="completed"{return ErrConflict};result,err:=s.DB.ExecContext(ctx,`DELETE FROM marketing_campaigns_v2 WHERE tenant_id=? AND id=? AND campaign_json=?`,tenant,id,raw);if err!=nil{return err};affected,err:=result.RowsAffected();if err!=nil{return err};if affected!=1{return ErrConflict};return nil}
func (s MarketingStore)ReserveAttempt(ctx context.Context,attempt CampaignAttempt)(CampaignAttempt,bool,error){if s.DB==nil{return CampaignAttempt{},false,errors.New("marketing database required")};if !validOpaque(string(attempt.ID))||!validOpaque(attempt.TenantID)||!validOpaque(string(attempt.CampaignID))||!validOpaque(string(attempt.ContactID))||!validOpaque(attempt.IdempotencyKey)||ValidateAddress(attempt.Address)!=nil{return CampaignAttempt{},false,ErrInvalidCommand};now:=time.Now().UTC();var priorRaw []byte;err:=s.DB.QueryRowContext(ctx,`SELECT attempt_json FROM marketing_attempts_v2 WHERE tenant_id=? AND (id=? OR idempotency_key=?) LIMIT 1`,attempt.TenantID,attempt.ID,attempt.IdempotencyKey).Scan(&priorRaw);if err==nil{var prior CampaignAttempt;if err=strictJSON(priorRaw,&prior);err!=nil{return CampaignAttempt{},false,err};if prior.ID!=attempt.ID||prior.IdempotencyKey!=attempt.IdempotencyKey||prior.CampaignID!=attempt.CampaignID||prior.ContactID!=attempt.ContactID||prior.Address!=attempt.Address{return CampaignAttempt{},false,ErrConflict};if prior.State=="deferred"&&!prior.NextAttempt.After(now){prior.State="reserved";prior.Detail="";prior.Attempts++;prior.NextAttempt=time.Time{};prior.UpdatedAt=now;raw,marshalErr:=json.Marshal(prior);if marshalErr!=nil{return CampaignAttempt{},false,marshalErr};result,updateErr:=s.DB.ExecContext(ctx,`UPDATE marketing_attempts_v2 SET state=?,next_attempt=NULL,attempt_json=?,updated_at=? WHERE tenant_id=? AND id=? AND state='deferred' AND attempt_json=?`,prior.State,raw,prior.UpdatedAt,prior.TenantID,prior.ID,priorRaw);if updateErr!=nil{return CampaignAttempt{},false,updateErr};affected,rowsErr:=result.RowsAffected();if rowsErr!=nil{return CampaignAttempt{},false,rowsErr};if affected==1{return prior,true,nil}};return prior,false,nil};if !errors.Is(err,sql.ErrNoRows){return CampaignAttempt{},false,err};attempt.State="reserved";attempt.Attempts=1;attempt.NextAttempt=time.Time{};attempt.UpdatedAt=now;raw,err:=json.Marshal(attempt);if err!=nil{return CampaignAttempt{},false,err};result,err:=s.DB.ExecContext(ctx,`INSERT INTO marketing_attempts_v2(id,tenant_id,campaign_id,contact_id,idempotency_key,state,next_attempt,attempt_json,updated_at) VALUES(?,?,?,?,?,?,NULL,?,?) ON CONFLICT DO NOTHING`,attempt.ID,attempt.TenantID,attempt.CampaignID,attempt.ContactID,attempt.IdempotencyKey,attempt.State,raw,attempt.UpdatedAt);if err!=nil{return CampaignAttempt{},false,err};affected,err:=result.RowsAffected();if err!=nil{return CampaignAttempt{},false,err};if affected==0{return s.ReserveAttempt(ctx,attempt)};return attempt,true,nil}
func (s MarketingStore)CompleteAttempt(ctx context.Context,attempt CampaignAttempt)error{if s.DB==nil{return errors.New("marketing database required")};if !validCampaignAttemptState(attempt.State)||attempt.Attempts==0||attempt.State=="deferred"&&attempt.NextAttempt.IsZero()||attempt.State!="deferred"&&!attempt.NextAttempt.IsZero(){return ErrInvalidCommand};attempt.UpdatedAt=time.Now().UTC();raw,err:=json.Marshal(attempt);if err!=nil{return err};result,err:=s.DB.ExecContext(ctx,`UPDATE marketing_attempts_v2 SET state=?,next_attempt=?,attempt_json=?,updated_at=? WHERE id=? AND tenant_id=?`,attempt.State,nextAttemptValue(attempt.NextAttempt),raw,attempt.UpdatedAt,attempt.ID,attempt.TenantID);if err!=nil{return err};affected,err:=result.RowsAffected();if err!=nil{return err};if affected!=1{return ErrNotFound};return nil}
func (s MarketingStore)Attempt(ctx context.Context,tenant string,id AttemptID)(CampaignAttempt,bool,error){if s.DB==nil{return CampaignAttempt{},false,errors.New("marketing database required")};var raw []byte;err:=s.DB.QueryRowContext(ctx,`SELECT attempt_json FROM marketing_attempts_v2 WHERE tenant_id=? AND id=?`,tenant,id).Scan(&raw);if errors.Is(err,sql.ErrNoRows){return CampaignAttempt{},false,nil};if err!=nil{return CampaignAttempt{},false,err};var attempt CampaignAttempt;if err=strictJSON(raw,&attempt);err!=nil{return CampaignAttempt{},false,err};return attempt,true,nil}
func (s MarketingStore)Attempts(ctx context.Context,tenant string,campaign CampaignID,limit int,cursor string)([]CampaignAttempt,string,error){if s.DB==nil{return nil,"",errors.New("marketing database required")};if limit<1||limit>500{limit=100};after,err:=decodeCursor(cursor);if err!=nil{return nil,"",err};rows,err:=s.DB.QueryContext(ctx,`SELECT id,attempt_json FROM marketing_attempts_v2 WHERE tenant_id=? AND campaign_id=? AND id>? ORDER BY id LIMIT ?`,tenant,campaign,after,limit+1);if err!=nil{return nil,"",err};defer rows.Close();items:=make([]CampaignAttempt,0,limit+1);ids:=make([]string,0,limit+1);for rows.Next(){var id string;var raw []byte;if err=rows.Scan(&id,&raw);err!=nil{return nil,"",err};var item CampaignAttempt;if err=strictJSON(raw,&item);err!=nil{return nil,"",err};items=append(items,item);ids=append(ids,id)};if err=rows.Err();err!=nil{return nil,"",err};next:="";if len(items)>limit{next=base64.RawURLEncoding.EncodeToString([]byte(ids[limit-1]));items=items[:limit]};return items,next,nil}
func (s MarketingStore)ConsentEvents(ctx context.Context,tenant string,state ConsentState,limit int,cursor string)([]ConsentEvent,string,error){if s.DB==nil{return nil,"",errors.New("marketing database required")};if state!=Consented&&state!=Suppressed{return nil,"",ErrInvalidCommand};if limit<1||limit>500{limit=100};after,err:=decodeCursor(cursor);if err!=nil{return nil,"",err};rows,err:=s.DB.QueryContext(ctx,`SELECT id,event_json FROM marketing_consent_events_v2 WHERE tenant_id=? AND state=? AND id>? ORDER BY id LIMIT ?`,tenant,state,after,limit+1);if err!=nil{return nil,"",err};defer rows.Close();items:=make([]ConsentEvent,0,limit+1);ids:=make([]string,0,limit+1);for rows.Next(){var id string;var raw []byte;if err=rows.Scan(&id,&raw);err!=nil{return nil,"",err};var item ConsentEvent;if err=strictJSON(raw,&item);err!=nil{return nil,"",err};items=append(items,item);ids=append(ids,id)};if err=rows.Err();err!=nil{return nil,"",err};next:="";if len(items)>limit{next=base64.RawURLEncoding.EncodeToString([]byte(ids[limit-1]));items=items[:limit]};return items,next,nil}

type CampaignCoordinator struct { Store MarketingStore; Sender MarketingSender; Now func()time.Time }
func (c CampaignCoordinator)SendOne(ctx context.Context,tenant string,campaign Campaign,recipient CampaignRecipient,attempt CampaignAttempt)(CampaignAttempt,error){
	if c.Sender==nil{return CampaignAttempt{},errors.New("marketing sender required")}
	if campaign.State!="running"||campaign.SnapshotRef==""||attempt.TenantID!=tenant||recipient.ContactID!=attempt.ContactID||recipient.Address!=attempt.Address||validateCampaignRecipient(recipient)!=nil{return CampaignAttempt{},ErrConflict}
	reserved,claimed,err:=c.Store.ReserveAttempt(ctx,attempt)
	if err!=nil{return CampaignAttempt{},err}
	if !claimed{return reserved,nil}
	consent,found,err:=c.Store.CurrentConsent(ctx,tenant,recipient.Address)
	if err!=nil{
		reserved.State="deferred"
		reserved.Detail="consent authority temporarily unavailable"
		reserved.NextAttempt=c.now().Add(campaignRetryDelay(reserved.Attempts))
		if completeErr:=c.completeAttempt(ctx,reserved);completeErr!=nil{return reserved,errors.Join(err,completeErr)}
		return reserved,err
	}
	if !found||consent.State!=Consented||consent.ContactID!=recipient.ContactID{
		reserved.State="suppressed"
		reserved.Detail="no current affirmative consent"
		if found&&consent.State==Suppressed{reserved.Detail="suppressed: "+string(consent.SuppressionReason)}
		return reserved,c.completeAttempt(ctx,reserved)
	}
	queueID,err:=c.Sender.SubmitCampaign(ctx,tenant,campaign,recipient,reserved.IdempotencyKey)
	switch{
	case errors.Is(err,ErrCampaignPaused):
		reserved.State="deferred"
		reserved.Detail="campaign paused before queue submission"
		reserved.NextAttempt=c.now().Add(campaignRetryDelay(reserved.Attempts))
	case errors.Is(err,ErrCampaignStopped):
		reserved.State="cancelled"
		reserved.Detail="campaign stopped before queue submission"
	case errors.Is(err,ErrSuppressed):
		reserved.State="suppressed"
		reserved.Detail="suppressed before queue submission"
	case errors.Is(err,ErrRateLimited):
		reserved.State="deferred"
		reserved.Detail="campaign delivery capacity unavailable"
		reserved.NextAttempt=c.now().Add(campaignRetryDelay(reserved.Attempts))
	case errors.Is(err,ErrInvalidCommand),errors.Is(err,ErrUnauthorized),errors.Is(err,ErrConflict),errors.Is(err,ErrNotFound):
		reserved.State="failed"
		reserved.Detail=err.Error()
	case err!=nil:
		reserved.State="ambiguous"
		reserved.Detail=err.Error()
	default:
		reserved.State="queued"
		reserved.QueueID=queueID
		reserved.Detail=""
	}
	return reserved,c.completeAttempt(ctx,reserved)
}
func (c CampaignCoordinator)completeAttempt(ctx context.Context,attempt CampaignAttempt)error{if attempt.State!="deferred"{attempt.NextAttempt=time.Time{}};return c.Store.CompleteAttempt(ctx,attempt)}
func (c CampaignCoordinator)now()time.Time{if c.Now!=nil{return c.Now().UTC()};return time.Now().UTC()}
func campaignRetryDelay(attempt uint32)time.Duration{delay:=30*time.Second;for index:=uint32(1);index<attempt&&delay<30*time.Minute;index++{delay*=2};if delay>30*time.Minute{return 30*time.Minute};return delay}
func validCampaignAttemptState(state string)bool{switch state{case"reserved","deferred","queued","suppressed","cancelled","failed","ambiguous":return true};return false}
func nextAttemptValue(value time.Time)any{if value.IsZero(){return nil};return value.UTC()}

type UnsubscribeSigner struct { KeyID string; Key []byte; BaseURL string }
func (s UnsubscribeSigner)Issue(tenant string,campaign CampaignID,contact ContactID,address Address,expires time.Time)(string,error){if !validOpaque(s.KeyID)||len(s.Key)<32||!validOpaque(tenant)||campaign==""||contact==""||ValidateAddress(address)!=nil||expires.Before(time.Now()){return "",ErrInvalidCommand};claims:=fmt.Sprintf("v1\x00%s\x00%s\x00%s\x00%s\x00%s\x00%d",s.KeyID,tenant,campaign,contact,address,expires.Unix());mac:=hmac.New(sha256.New,s.Key);mac.Write([]byte(claims));return base64.RawURLEncoding.EncodeToString([]byte(claims))+"."+hex.EncodeToString(mac.Sum(nil)),nil}
func (s UnsubscribeSigner)Verify(token string)(tenant string,campaign CampaignID,contact ContactID,address Address,err error){parts:=splitToken(token);if len(parts)!=2{return "","","","",ErrUnauthorized};raw,decodeErr:=base64.RawURLEncoding.DecodeString(parts[0]);if decodeErr!=nil{return "","","","",ErrUnauthorized};claims:=string(raw);mac:=hmac.New(sha256.New,s.Key);mac.Write(raw);provided,decodeErr:=hex.DecodeString(parts[1]);if decodeErr!=nil||!hmac.Equal(mac.Sum(nil),provided){return "","","","",ErrUnauthorized};fields:=splitNUL(claims);if len(fields)!=7||fields[0]!="v1"||fields[1]!=s.KeyID{return "","","","",ErrUnauthorized};expiry,parseErr:=parseInt64(fields[6]);if parseErr!=nil||time.Now().Unix()>expiry{return "","","","",ErrUnauthorized};return fields[2],CampaignID(fields[3]),ContactID(fields[4]),Address(fields[5]),nil}
func validSuppression(reason SuppressionReason)bool{switch reason{case SuppressionUnsubscribe,SuppressionComplaint,SuppressionGlobalDNC,SuppressionHardBounce,SuppressionTransient,SuppressionAdministrative:return true};return false}
func validateCampaignRecord(tenant string,campaign Campaign)error{if !validOpaque(tenant)||!validOpaque(string(campaign.ID))||!validOpaque(string(campaign.List))||campaign.Subject==""||len(campaign.Subject)>998||strings.ContainsAny(campaign.Subject,"\x00\r\n")||!validOpaque(campaign.TemplateRef)||!validOpaque(string(campaign.FromMailbox))||campaign.ReplyTo!=""&&ValidateAddress(campaign.ReplyTo)!=nil||len(campaign.Schedule)>128||strings.ContainsAny(campaign.Schedule,"\x00\r\n")||campaign.Generation==0{return ErrInvalidCommand};normalizedSchedule,err:=NormalizeCampaignSchedule(campaign.Schedule);if err!=nil||normalizedSchedule!=campaign.Schedule{return ErrInvalidCommand};switch campaign.State{case"draft":if campaign.SnapshotRef!=""||campaign.RecipientCount!=0||campaign.ApprovedAt!=nil||campaign.ApprovedBy!=""{return ErrInvalidCommand};case"approved","running","paused","completed":if !validOpaque(campaign.SnapshotRef)||campaign.RecipientCount==0||campaign.ApprovedAt==nil||campaign.ApprovedAt.IsZero()||!validOpaque(campaign.ApprovedBy){return ErrInvalidCommand};case"scheduled":if campaign.Schedule==""||!validOpaque(campaign.SnapshotRef)||campaign.RecipientCount==0||campaign.ApprovedAt==nil||campaign.ApprovedAt.IsZero()||!validOpaque(campaign.ApprovedBy){return ErrInvalidCommand};case"cancelled":if campaign.SnapshotRef==""{if campaign.RecipientCount!=0||campaign.ApprovedAt!=nil||campaign.ApprovedBy!=""{return ErrInvalidCommand}}else if !validOpaque(campaign.SnapshotRef)||campaign.RecipientCount==0||campaign.ApprovedAt==nil||campaign.ApprovedAt.IsZero()||!validOpaque(campaign.ApprovedBy){return ErrInvalidCommand};default:return ErrInvalidCommand};return nil}
func splitToken(value string)[]string{for i,r:=range value{if r=='.'{return []string{value[:i],value[i+1:]}}};return nil}
func splitNUL(value string)[]string{parts:=[]string{};start:=0;for i,r:=range value{if r==0{parts=append(parts,value[start:i]);start=i+1}};return append(parts,value[start:])}
func parseInt64(value string)(int64,error){var result int64;if value==""{return 0,ErrInvalidCommand};for _,r:=range value{if r<'0'||r>'9'{return 0,ErrInvalidCommand};next:=result*10+int64(r-'0');if next<result{return 0,ErrInvalidCommand};result=next};return result,nil}
