//go:build linux

package mail

import (
	"bufio"
	"bytes"
	"context"
	"crypto/sha256"
	"crypto/tls"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"mime"
	"mime/multipart"
	"mime/quotedprintable"
	"net"
	stdmail "net/mail"
	"net/textproto"
	"os"
	"sort"
	"strconv"
	"strings"
	"syscall"
	"time"
)

const webmailMasterPath = "/etc/cyberpanel/secrets/mail-webmail-master"
const webmailMasterUser = "cyberpanel-webmail"

type imapReply struct{ line string; literal []byte }
type localIMAPClient struct{ connection net.Conn; reader *bufio.Reader; writer *bufio.Writer; sequence uint64; stop func()bool }

func validWebmailBrokerRequest(request MailBrokerRequest)error{if request.Webmail.Validate()!=nil{return ErrInvalidCommand};switch request.Operation{case MailBrokerWebmailFolders:return nil;case MailBrokerWebmailSearch:query:=request.MessageQuery;if !validOpaque(string(query.FolderID))||query.Limit>200||len(query.Terms)>512||len(query.Cursor)>1024||strings.ContainsAny(query.Terms+query.Cursor,"\x00\r\n")||(query.Sort!=""&&query.Sort!="newest"&&query.Sort!="oldest"){return ErrInvalidCommand};case MailBrokerWebmailRead,MailBrokerWebmailDelete:if !validOpaque(string(request.MessageID)){return ErrInvalidCommand};case MailBrokerWebmailAttachment:if !validOpaque(string(request.MessageID))||!validOpaque(string(request.AttachmentID)){return ErrInvalidCommand};case MailBrokerWebmailMove:if !validOpaque(string(request.MessageID))||!validOpaque(string(request.FolderID)){return ErrInvalidCommand};case MailBrokerWebmailFlags:if !validOpaque(string(request.MessageID))||len(request.Flags)>32{return ErrInvalidCommand};allowed:=map[string]bool{"seen":true,"answered":true,"flagged":true,"deleted":true,"draft":true};seen:=map[string]bool{};for _,flag:=range request.Flags{flag=strings.ToLower(flag);if !allowed[flag]||seen[flag]{return ErrInvalidCommand};seen[flag]=true};case MailBrokerWebmailSubmit:message:=request.Compose;if message.From!=request.Webmail.MailboxID||len(message.Subject)>998||strings.ContainsAny(message.Subject,"\x00\r\n")||len(message.Text)>8<<20||len(message.SanitizedHTML)>8<<20||len(message.AttachmentBlobRefs)>0{return ErrInvalidCommand};recipients:=append(append(append([]Address{},message.To...),message.CC...),message.BCC...);if len(recipients)==0||len(recipients)>500{return ErrInvalidCommand};if _,err:=NormalizeAddresses(recipients);err!=nil{return err};default:return ErrInvalidCommand};return nil}

func (host *LinuxMailHost) WebmailFolders(ctx context.Context,binding WebmailBinding)([]Folder,error){client,err:=openLocalIMAP(ctx,binding);if err!=nil{return nil,err};defer client.close();return client.listFolders(binding)}
func (host *LinuxMailHost) WebmailSearch(ctx context.Context,binding WebmailBinding,query MessageQuery)(MessagePage,error){client,err:=openLocalIMAP(ctx,binding);if err!=nil{return MessagePage{},err};defer client.close();folder,err:=client.resolveFolder(binding,query.FolderID);if err!=nil{return MessagePage{},err};if _,err=client.command("SELECT "+imapQuote(folder));err!=nil{return MessagePage{},err};criteria:="ALL";if query.Terms!=""{criteria="TEXT "+imapQuote(query.Terms)};replies,err:=client.command("UID SEARCH "+criteria);if err!=nil{return MessagePage{},err};uids:=searchUIDs(replies);if query.Sort!="oldest"{sort.Slice(uids,func(i,j int)bool{return uids[i]>uids[j]})};offset,err:=webmailCursor(query.Cursor);if err!=nil||offset>len(uids){return MessagePage{},ErrInvalidCommand};limit:=int(query.Limit);if limit==0{limit=50};end:=offset+limit;if end>len(uids){end=len(uids)};page:=MessagePage{Items:make([]MessageSummary,0,end-offset),TotalEstimate:uint64(len(uids))};for _,uid:=range uids[offset:end]{summary,fetchErr:=client.fetchSummary(binding,folder,uid);if fetchErr!=nil{return MessagePage{},fetchErr};page.Items=append(page.Items,summary)};if end<len(uids){page.NextCursor="c_"+strconv.Itoa(end)};return page,nil}
func (host *LinuxMailHost) WebmailRead(ctx context.Context,binding WebmailBinding,id MessageID)(MessageView,error){client,err:=openLocalIMAP(ctx,binding);if err!=nil{return MessageView{},err};defer client.close();folder,uid,err:=client.resolveMessage(binding,id);if err!=nil{return MessageView{},err};raw,metadata,err:=client.fetchRaw(folder,uid);if err!=nil{return MessageView{},err};return parseMessageView(binding,folder,uid,raw,metadata)}
func (host *LinuxMailHost) WebmailAttachment(ctx context.Context,binding WebmailBinding,message MessageID,id AttachmentID)(AttachmentInfo,[]byte,error){client,err:=openLocalIMAP(ctx,binding);if err!=nil{return AttachmentInfo{},nil,err};defer client.close();folder,uid,err:=client.resolveMessage(binding,message);if err!=nil{return AttachmentInfo{},nil,err};raw,metadata,err:=client.fetchRaw(folder,uid);if err!=nil{return AttachmentInfo{},nil,err};view,parts,err:=parseMessage(binding,folder,uid,raw,metadata,id);if err!=nil{return AttachmentInfo{},nil,err};_ = view;for _,part:=range parts{if part.info.ID==id{return part.info,part.content,nil}};return AttachmentInfo{},nil,ErrNotFound}
func (host *LinuxMailHost) WebmailMove(ctx context.Context,binding WebmailBinding,message MessageID,target FolderID)error{client,err:=openLocalIMAP(ctx,binding);if err!=nil{return err};defer client.close();source,uid,err:=client.resolveMessage(binding,message);if err!=nil{return err};destination,err:=client.resolveFolder(binding,target);if err!=nil{return err};if source==destination{return nil};if _,err=client.command("SELECT "+imapQuote(source));err!=nil{return err};_,err=client.command("UID MOVE "+strconv.FormatUint(uid,10)+" "+imapQuote(destination));return err}
func (host *LinuxMailHost) WebmailDelete(ctx context.Context,binding WebmailBinding,message MessageID)error{client,err:=openLocalIMAP(ctx,binding);if err!=nil{return err};defer client.close();folder,uid,err:=client.resolveMessage(binding,message);if err!=nil{return err};if _,err=client.command("SELECT "+imapQuote(folder));err!=nil{return err};if _,err=client.command("UID STORE "+strconv.FormatUint(uid,10)+" +FLAGS.SILENT (\\Deleted)");err!=nil{return err};_,err=client.command("UID EXPUNGE "+strconv.FormatUint(uid,10));return err}
func (host *LinuxMailHost) WebmailFlags(ctx context.Context,binding WebmailBinding,message MessageID,flags []string)error{client,err:=openLocalIMAP(ctx,binding);if err!=nil{return err};defer client.close();folder,uid,err:=client.resolveMessage(binding,message);if err!=nil{return err};imapFlags:=make([]string,0,len(flags));allowed:=map[string]string{"seen":"\\Seen","answered":"\\Answered","flagged":"\\Flagged","deleted":"\\Deleted","draft":"\\Draft"};for _,flag:=range flags{value,ok:=allowed[strings.ToLower(flag)];if !ok{return ErrInvalidCommand};imapFlags=append(imapFlags,value)};if _,err=client.command("SELECT "+imapQuote(folder));err!=nil{return err};_,err=client.command("UID STORE "+strconv.FormatUint(uid,10)+" FLAGS.SILENT ("+strings.Join(imapFlags," ")+")");return err}
func (host *LinuxMailHost) WebmailSubmit(ctx context.Context,binding WebmailBinding,message ComposeMessage)(QueueID,error){if binding.Validate()!=nil||message.From!=binding.MailboxID||len(message.AttachmentBlobRefs)!=0{return "",ErrInvalidCommand};raw,err:=renderSubmission(binding,message);if err!=nil{return "",err};defer wipeMailBytes(raw);return submitLocalSMTP(ctx,binding,raw,message)}

func (host *LinuxMailHost) CampaignSubmit(ctx context.Context, submission CampaignSubmission) (QueueID, error) {
	if host == nil || host.Store == nil || ctx == nil || submission.Validate() != nil {
		return "", ErrInvalidCommand
	}
	raw, err := renderCampaignSubmission(submission)
	if err != nil {
		return "", err
	}
	defer wipeMailBytes(raw)
	message := ComposeMessage{From:submission.Sender.MailboxID, To:[]Address{submission.Recipient}, Subject:submission.Subject, Text:submission.Text, SanitizedHTML:submission.SanitizedHTML}
	return submitLocalSMTP(ctx, submission.Sender, raw, message)
}

func openLocalIMAP(ctx context.Context,binding WebmailBinding)(*localIMAPClient,error){if ctx==nil||binding.Validate()!=nil{return nil,ErrInvalidCommand};password,err:=loadWebmailMaster();if err!=nil{return nil,err};defer wipeMailBytes(password);serverName:=webmailServerName(binding);dialer:=tls.Dialer{NetDialer:&net.Dialer{},Config:&tls.Config{MinVersion:tls.VersionTLS12,ServerName:serverName}};connection,err:=dialer.DialContext(ctx,"tcp","127.0.0.1:993");if err!=nil{return nil,err};stop:=context.AfterFunc(ctx,func(){_=connection.SetDeadline(time.Now())});client:=&localIMAPClient{connection:connection,reader:bufio.NewReaderSize(connection,64<<10),writer:bufio.NewWriterSize(connection,64<<10),stop:stop};line,err:=client.reader.ReadString('\n');if err!=nil||!strings.HasPrefix(line,"* OK"){stop();connection.Close();return nil,ErrUnauthorized};login:=string(binding.Address)+"*"+webmailMasterUser;if _,err=client.command("LOGIN "+imapQuote(login)+" "+imapQuote(string(password)));err!=nil{stop();connection.Close();return nil,ErrUnauthorized};return client,nil}
func (client *localIMAPClient)close(){if client==nil||client.connection==nil{return};if client.stop!=nil{client.stop()};_,_=client.command("LOGOUT");_=client.connection.Close()}
func (client *localIMAPClient)command(command string)([]imapReply,error){if client==nil||client.connection==nil||strings.ContainsAny(command,"\x00\r\n")||len(command)>4096{return nil,ErrInvalidCommand};client.sequence++;tag:=fmt.Sprintf("C%06d",client.sequence);if _,err:=client.writer.WriteString(tag+" "+command+"\r\n");err!=nil{return nil,err};if err:=client.writer.Flush();err!=nil{return nil,err};replies:=[]imapReply{};for{line,err:=client.reader.ReadString('\n');if err!=nil{return nil,err};line=strings.TrimSuffix(strings.TrimSuffix(line,"\n"),"\r");if strings.HasPrefix(line,tag+" "){fields:=strings.Fields(line);if len(fields)<2||strings.ToUpper(fields[1])!="OK"{return nil,ErrNotFound};return replies,nil};reply:=imapReply{line:line};if size,ok:=imapLiteralSize(line);ok{if size>16<<20{return nil,ErrInvalidReceipt};reply.literal=make([]byte,size);if _,err=io.ReadFull(client.reader,reply.literal);err!=nil{return nil,err}};replies=append(replies,reply);if len(replies)>20000{return nil,ErrInvalidReceipt}}}
func imapLiteralSize(line string)(int,bool){end:=strings.LastIndex(line,"{");if end<0||!strings.HasSuffix(line,"}"){return 0,false};size,err:=strconv.Atoi(line[end+1:len(line)-1]);return size,err==nil&&size>=0}
func imapQuote(value string)string{return "\""+strings.NewReplacer("\\","\\\\","\"","\\\"").Replace(value)+"\""}

func (client *localIMAPClient)listFolders(binding WebmailBinding)([]Folder,error){replies,err:=client.command("LIST \"\" \"*\"");if err!=nil{return nil,err};folders:=[]Folder{};for _,reply:=range replies{if !strings.HasPrefix(reply.line,"* LIST "){continue};name,ok:=lastIMAPString(reply.line);if !ok||name==""{return nil,ErrInvalidReceipt};folders=append(folders,Folder{ID:webmailFolderID(binding,name),Mailbox:binding.MailboxID,Name:name})};sort.Slice(folders,func(i,j int)bool{return strings.ToLower(folders[i].Name)<strings.ToLower(folders[j].Name)});return folders,nil}
func lastIMAPString(line string)(string,bool){line=strings.TrimSpace(line);if len(line)<2{return "",false};if line[len(line)-1]=='"'{start:=-1;escaped:=false;for index:=len(line)-2;index>=0;index--{if line[index]=='"'&&!escaped{start=index;break};escaped=line[index]=='\\'&&!escaped;if line[index]!='\\'{escaped=false}};if start<0{return "",false};value:=line[start+1:len(line)-1];value=strings.NewReplacer("\\\"","\"","\\\\","\\").Replace(value);return value,true};index:=strings.LastIndexAny(line," \t");if index<0{return "",false};return line[index+1:],true}
func webmailFolderID(binding WebmailBinding,name string)FolderID{sum:=sha256.Sum256([]byte(string(binding.Address)+"\x00"+name));return FolderID("fld_"+hex.EncodeToString(sum[:24]))}
func (client *localIMAPClient)resolveFolder(binding WebmailBinding,id FolderID)(string,error){if !strings.HasPrefix(string(id),"fld_")||len(id)!=52{return "",ErrInvalidCommand};folders,err:=client.listFolders(binding);if err!=nil{return "",err};for _,folder:=range folders{if folder.ID==id{return folder.Name,nil}};return "",ErrNotFound}
func webmailMessageID(binding WebmailBinding,folder string,uid uint64)MessageID{return MessageID("msg_"+strings.TrimPrefix(string(webmailFolderID(binding,folder)),"fld_")+"_"+strconv.FormatUint(uid,10))}
func (client *localIMAPClient)resolveMessage(binding WebmailBinding,id MessageID)(string,uint64,error){raw:=string(id);if !strings.HasPrefix(raw,"msg_"){return "",0,ErrInvalidCommand};parts:=strings.Split(raw,"_");if len(parts)!=3||len(parts[1])!=48{return "",0,ErrInvalidCommand};uid,err:=strconv.ParseUint(parts[2],10,32);if err!=nil||uid==0{return "",0,ErrInvalidCommand};folder,err:=client.resolveFolder(binding,FolderID("fld_"+parts[1]));return folder,uid,err}
func searchUIDs(replies []imapReply)[]uint64{uids:=[]uint64{};for _,reply:=range replies{if !strings.HasPrefix(reply.line,"* SEARCH"){continue};for _,field:=range strings.Fields(strings.TrimPrefix(reply.line,"* SEARCH")){uid,err:=strconv.ParseUint(field,10,32);if err==nil&&uid>0{uids=append(uids,uid)}}};return uids}
func webmailCursor(cursor string)(int,error){if cursor==""{return 0,nil};if !strings.HasPrefix(cursor,"c_"){return 0,ErrInvalidCommand};value,err:=strconv.Atoi(strings.TrimPrefix(cursor,"c_"));if err!=nil||value<0{return 0,ErrInvalidCommand};return value,nil}
func (client *localIMAPClient)fetchSummary(binding WebmailBinding,folder string,uid uint64)(MessageSummary,error){replies,err:=client.command("UID FETCH "+strconv.FormatUint(uid,10)+" (FLAGS RFC822.SIZE BODY.PEEK[HEADER])");if err!=nil{return MessageSummary{},err};raw,metadata:=fetchLiteral(replies);if len(raw)==0{return MessageSummary{},ErrNotFound};return parseMessageSummary(binding,folder,uid,raw,metadata)}
func (client *localIMAPClient)fetchRaw(folder string,uid uint64)([]byte,string,error){if _,err:=client.command("SELECT "+imapQuote(folder));err!=nil{return nil,"",err};replies,err:=client.command("UID FETCH "+strconv.FormatUint(uid,10)+" (FLAGS RFC822.SIZE BODY.PEEK[])");if err!=nil{return nil,"",err};raw,metadata:=fetchLiteral(replies);if len(raw)==0{return nil,"",ErrNotFound};return raw,metadata,nil}
func fetchLiteral(replies []imapReply)([]byte,string){metadata:="";for _,reply:=range replies{if strings.HasPrefix(reply.line,"* ")&&strings.Contains(reply.line," FETCH "){metadata=reply.line};if len(reply.literal)>0{return reply.literal,metadata}};return nil,metadata}

type parsedAttachment struct{info AttachmentInfo;content []byte}
func parseMessageSummary(binding WebmailBinding,folder string,uid uint64,raw []byte,metadata string)(MessageSummary,error){message,err:=stdmail.ReadMessage(bytes.NewReader(raw));if err!=nil{return MessageSummary{},ErrInvalidReceipt};subject,_:=new(mime.WordDecoder).DecodeHeader(message.Header.Get("Subject"));from:=firstMailAddress(message.Header.Get("From"));to:=allMailAddresses(message.Header.Get("To"));received,_:=stdmail.ParseDate(message.Header.Get("Date"));if received.IsZero(){received=time.Unix(0,0).UTC()};contentType:=strings.ToLower(message.Header.Get("Content-Type"));return MessageSummary{ID:webmailMessageID(binding,folder,uid),FolderID:webmailFolderID(binding,folder),Subject:subject,From:from,To:to,Flags:imapFlags(metadata),ReceivedAt:received.UTC(),Size:imapSize(metadata),HasAttachments:strings.Contains(contentType,"multipart/mixed")||strings.Contains(strings.ToLower(message.Header.Get("Content-Disposition")),"attachment")},nil}
func parseMessageView(binding WebmailBinding,folder string,uid uint64,raw []byte,metadata string)(MessageView,error){view,_,err:=parseMessage(binding,folder,uid,raw,metadata,"");return view,err}
func parseMessage(binding WebmailBinding,folder string,uid uint64,raw []byte,metadata string,wanted AttachmentID)(MessageView,[]parsedAttachment,error){message,err:=stdmail.ReadMessage(bytes.NewReader(raw));if err!=nil{return MessageView{},nil,ErrInvalidReceipt};headerRaw:=bytes.NewBuffer(nil);for key,values:=range message.Header{for _,value:=range values{fmt.Fprintf(headerRaw,"%s: %s\r\n",key,value)}};fmt.Fprint(headerRaw,"\r\n");summary,err:=parseMessageSummary(binding,folder,uid,headerRaw.Bytes(),metadata);if err!=nil{return MessageView{},nil,err};view:=MessageView{Summary:summary,RemoteImagesBlocked:true};attachments:=[]parsedAttachment{};if err=walkMIME(textproto.MIMEHeader(message.Header),message.Body,"1",summary.ID,&view,&attachments,wanted);err!=nil{return MessageView{},nil,err};view.Attachments=make([]AttachmentInfo,len(attachments));for index:=range attachments{view.Attachments[index]=attachments[index].info};view.Summary.HasAttachments=len(attachments)>0;return view,attachments,nil}
func walkMIME(header textproto.MIMEHeader,body io.Reader,path string,messageID MessageID,view *MessageView,attachments *[]parsedAttachment,wanted AttachmentID)error{mediaType,params,err:=mime.ParseMediaType(header.Get("Content-Type"));if err!=nil||mediaType==""{mediaType="text/plain"};if strings.HasPrefix(mediaType,"multipart/"){boundary:=params["boundary"];if boundary==""{return ErrInvalidReceipt};reader:=multipart.NewReader(body,boundary);index:=0;for{part,partErr:=reader.NextPart();if errors.Is(partErr,io.EOF){return nil};if partErr!=nil{return partErr};index++;if index>1000{return ErrInvalidReceipt};if err=walkMIME(part.Header,part,fmt.Sprintf("%s.%d",path,index),messageID,view,attachments,wanted);err!=nil{part.Close();return err};part.Close()}};decoded:=transferReader(header.Get("Content-Transfer-Encoding"),body);content,err:=io.ReadAll(io.LimitReader(decoded,8<<20+1));if err!=nil||len(content)>8<<20{return ErrInvalidReceipt};disposition,dispositionParams,_:=mime.ParseMediaType(header.Get("Content-Disposition"));filename:=dispositionParams["filename"];if filename==""{filename=params["name"]};if filename!=""||strings.EqualFold(disposition,"attachment"){sum:=sha256.Sum256(content);idSum:=sha256.Sum256([]byte(string(messageID)+"\x00"+path));info:=AttachmentInfo{ID:AttachmentID("att_"+hex.EncodeToString(idSum[:24])),Name:safeFilename(filename),ContentType:safeMIME(mediaType),Size:uint64(len(content)),SHA256:hex.EncodeToString(sum[:])};item:=parsedAttachment{info:info};if wanted!=""&&info.ID==wanted{if len(content)>4<<20{wipeMailBytes(content);return ErrInvalidReceipt};item.content=content}else{wipeMailBytes(content)};*attachments=append(*attachments,item);return nil};switch strings.ToLower(mediaType){case"text/plain":if view.Text==""{view.Text=string(content)};wipeMailBytes(content);case"text/html":if view.SanitizedHTML==""{view.SanitizedHTML=string(content)};wipeMailBytes(content);default:wipeMailBytes(content)};return nil}
func transferReader(encoding string,reader io.Reader)io.Reader{switch strings.ToLower(strings.TrimSpace(encoding)){case"base64":return base64.NewDecoder(base64.StdEncoding,reader);case"quoted-printable":return quotedprintable.NewReader(reader);default:return reader}}
func firstMailAddress(value string)Address{list:=allMailAddresses(value);if len(list)>0{return list[0]};return ""}
func allMailAddresses(value string)[]Address{parsed,err:=stdmail.ParseAddressList(value);if err!=nil{return nil};result:=make([]Address,0,len(parsed));for _,item:=range parsed{address:=Address(strings.ToLower(item.Address));if ValidateAddress(address)==nil{result=append(result,address)}};return result}
func imapFlags(metadata string)[]string{start:=strings.Index(metadata,"FLAGS (");if start<0{return nil};start+=len("FLAGS (");end:=strings.Index(metadata[start:],")");if end<0{return nil};result:=[]string{};for _,flag:=range strings.Fields(metadata[start:start+end]){result=append(result,strings.ToLower(strings.TrimPrefix(flag,"\\")))};return result}
func imapSize(metadata string)uint64{marker:="RFC822.SIZE ";start:=strings.Index(metadata,marker);if start<0{return 0};start+=len(marker);end:=start;for end<len(metadata)&&metadata[end]>='0'&&metadata[end]<='9'{end++};value,_:=strconv.ParseUint(metadata[start:end],10,64);return value}

func loadWebmailMaster()([]byte,error){info,err:=os.Lstat(webmailMasterPath);if err!=nil{return nil,err};metadata,ok:=info.Sys().(*syscall.Stat_t);if !ok||metadata.Uid!=0||!info.Mode().IsRegular()||info.Mode()&os.ModeSymlink!=0||info.Mode().Perm()!=0400||info.Size()!=91{return nil,ErrUnauthorized};raw,err:=os.ReadFile(webmailMasterPath);if err!=nil{return nil,err};defer wipeMailBytes(raw);prefix:=[]byte(webmailMasterUser+":{PLAIN}");if !bytes.HasPrefix(raw,prefix)||len(raw)!=len(prefix)+65||raw[len(raw)-1]!='\n'{return nil,ErrUnauthorized};password:=append([]byte(nil),raw[len(prefix):len(raw)-1]...);if len(password)!=64{return nil,ErrUnauthorized};return password,nil}
func webmailServerName(binding WebmailBinding)string{return binding.ServerName}

func renderSubmission(binding WebmailBinding,message ComposeMessage)([]byte,error){if len(message.Subject)>998||strings.ContainsAny(message.Subject,"\r\n\x00"){return nil,ErrInvalidCommand};var out bytes.Buffer;domain:=strings.SplitN(string(binding.Address),"@",2)[1];messageIDSum:=sha256.Sum256([]byte(string(binding.Address)+"\x00"+time.Now().UTC().Format(time.RFC3339Nano)));fmt.Fprintf(&out,"From: %s\r\n",binding.Address);fmt.Fprintf(&out,"To: %s\r\n",joinAddresses(message.To));if len(message.CC)>0{fmt.Fprintf(&out,"Cc: %s\r\n",joinAddresses(message.CC))};fmt.Fprintf(&out,"Subject: %s\r\n",mime.QEncoding.Encode("utf-8",message.Subject));fmt.Fprintf(&out,"Date: %s\r\n",time.Now().UTC().Format(time.RFC1123Z));fmt.Fprintf(&out,"Message-ID: <%s@%s>\r\n",hex.EncodeToString(messageIDSum[:16]),domain);if message.InReplyTo!=""{fmt.Fprintf(&out,"In-Reply-To: <%s@%s>\r\n",message.InReplyTo,domain)};fmt.Fprint(&out,"MIME-Version: 1.0\r\n");if message.SanitizedHTML==""{fmt.Fprint(&out,"Content-Type: text/plain; charset=utf-8\r\nContent-Transfer-Encoding: quoted-printable\r\n\r\n");writer:=quotedprintable.NewWriter(&out);_,_=writer.Write([]byte(message.Text));_=writer.Close()}else{boundary:="cp_"+hex.EncodeToString(messageIDSum[:12]);fmt.Fprintf(&out,"Content-Type: multipart/alternative; boundary=%q\r\n\r\n",boundary);fmt.Fprintf(&out,"--%s\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Transfer-Encoding: quoted-printable\r\n\r\n",boundary);writer:=quotedprintable.NewWriter(&out);_,_=writer.Write([]byte(message.Text));_=writer.Close();fmt.Fprintf(&out,"\r\n--%s\r\nContent-Type: text/html; charset=utf-8\r\nContent-Transfer-Encoding: quoted-printable\r\n\r\n",boundary);writer=quotedprintable.NewWriter(&out);_,_=writer.Write([]byte(message.SanitizedHTML));_=writer.Close();fmt.Fprintf(&out,"\r\n--%s--\r\n",boundary)};if out.Len()>16<<20{return nil,ErrInvalidCommand};return out.Bytes(),nil}

func renderCampaignSubmission(submission CampaignSubmission) ([]byte, error) {
	if submission.Validate() != nil {
		return nil, ErrInvalidCommand
	}
	var out bytes.Buffer
	domain := strings.SplitN(string(submission.Sender.Address), "@", 2)[1]
	messageIDSum := sha256.Sum256([]byte("cyberpanel-campaign-v1\x00" + submission.IdempotencyKey))
	fmt.Fprintf(&out, "From: %s\r\n", submission.Sender.Address)
	fmt.Fprintf(&out, "To: %s\r\n", submission.Recipient)
	if submission.ReplyTo != "" {
		fmt.Fprintf(&out, "Reply-To: %s\r\n", submission.ReplyTo)
	}
	fmt.Fprintf(&out, "Subject: %s\r\n", mime.QEncoding.Encode("utf-8", submission.Subject))
	fmt.Fprintf(&out, "Date: %s\r\n", time.Now().UTC().Format(time.RFC1123Z))
	fmt.Fprintf(&out, "Message-ID: <%s@%s>\r\n", hex.EncodeToString(messageIDSum[:16]), domain)
	fmt.Fprintf(&out, "List-ID: <%s.%s>\r\n", submission.CampaignID, domain)
	fmt.Fprintf(&out, "List-Unsubscribe: <%s>\r\n", submission.UnsubscribeURL)
	fmt.Fprint(&out, "List-Unsubscribe-Post: List-Unsubscribe=One-Click\r\n")
	fmt.Fprint(&out, "Precedence: bulk\r\nAuto-Submitted: auto-generated\r\nMIME-Version: 1.0\r\n")
	boundary := "cp_campaign_" + hex.EncodeToString(messageIDSum[:12])
	fmt.Fprintf(&out, "Content-Type: multipart/alternative; boundary=%q\r\n\r\n", boundary)
	fmt.Fprintf(&out, "--%s\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Transfer-Encoding: quoted-printable\r\n\r\n", boundary)
	writer := quotedprintable.NewWriter(&out)
	_, _ = writer.Write([]byte(submission.Text))
	_ = writer.Close()
	fmt.Fprintf(&out, "\r\n--%s\r\nContent-Type: text/html; charset=utf-8\r\nContent-Transfer-Encoding: quoted-printable\r\n\r\n", boundary)
	writer = quotedprintable.NewWriter(&out)
	_, _ = writer.Write([]byte(submission.SanitizedHTML))
	_ = writer.Close()
	fmt.Fprintf(&out, "\r\n--%s--\r\n", boundary)
	if out.Len() > 16<<20 {
		return nil, ErrInvalidCommand
	}
	return out.Bytes(), nil
}
func joinAddresses(values []Address)string{result:=make([]string,len(values));for index:=range values{result[index]=string(values[index])};return strings.Join(result,", ")}
func submitLocalSMTP(ctx context.Context,binding WebmailBinding,raw []byte,message ComposeMessage)(QueueID,error){password,err:=loadWebmailMaster();if err!=nil{return "",err};defer wipeMailBytes(password);serverName:=webmailServerName(binding);connection,err:=(&net.Dialer{}).DialContext(ctx,"tcp","127.0.0.1:587");if err!=nil{return "",err};defer connection.Close();stop:=context.AfterFunc(ctx,func(){_=connection.SetDeadline(time.Now())});defer stop();protocol:=textproto.NewConn(connection);if _,_,err=protocol.ReadResponse(220);err!=nil{return "",err};if err=smtpCommand(protocol,250,"EHLO localhost");err!=nil{return "",err};if err=smtpCommand(protocol,220,"STARTTLS");err!=nil{return "",err};tlsConnection:=tls.Client(connection,&tls.Config{MinVersion:tls.VersionTLS12,ServerName:serverName});if err=tlsConnection.HandshakeContext(ctx);err!=nil{return "",err};protocol=textproto.NewConn(tlsConnection);if err=smtpCommand(protocol,250,"EHLO localhost");err!=nil{return "",err};login:=string(binding.Address)+"*"+webmailMasterUser;auth:=base64.StdEncoding.EncodeToString([]byte("\x00"+login+"\x00"+string(password)));if err=smtpCommand(protocol,235,"AUTH PLAIN "+auth);err!=nil{return "",ErrUnauthorized};if err=smtpCommand(protocol,250,"MAIL FROM:<"+string(binding.Address)+">");err!=nil{return "",err};recipients:=append(append(append([]Address{},message.To...),message.CC...),message.BCC...);for _,recipient:=range recipients{if err=smtpCommand(protocol,250,"RCPT TO:<"+string(recipient)+">");err!=nil{return "",err}};if err=smtpCommand(protocol,354,"DATA");err!=nil{return "",err};writer:=protocol.DotWriter();if _,err=writer.Write(raw);err==nil{err=writer.Close()};if err!=nil{return "",err};_,reply,err:=protocol.ReadResponse(250);if err!=nil{return "",err};_,_=protocol.Cmd("QUIT");marker:="queued as ";index:=strings.LastIndex(strings.ToLower(reply),marker);if index<0{return "",ErrInvalidReceipt};queue:=strings.Fields(reply[index+len(marker):]);if len(queue)==0{return "",ErrInvalidReceipt};id:=QueueID(strings.Trim(queue[0],".[]()"));if !validPostfixQueueID(id){return "",ErrInvalidReceipt};return id,nil}
func smtpCommand(connection *textproto.Conn,code int,command string)error{id,err:=connection.Cmd("%s",command);if err!=nil{return err};connection.StartResponse(id);defer connection.EndResponse(id);_,_,err=connection.ReadResponse(code);return err}
