package ha

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
)

const SQLSchema = `
CREATE TABLE IF NOT EXISTS ha_node_groups (id TEXT PRIMARY KEY, generation INTEGER NOT NULL, group_json BLOB NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS ha_nodes (id TEXT PRIMARY KEY, group_id TEXT NOT NULL, state TEXT NOT NULL, generation INTEGER NOT NULL, node_json BLOB NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE INDEX IF NOT EXISTS ha_nodes_group ON ha_nodes(group_id, state, id);
CREATE TABLE IF NOT EXISTS ha_enrollment_tokens (token_id TEXT PRIMARY KEY, token_digest TEXT NOT NULL UNIQUE, node_id TEXT NOT NULL UNIQUE, command_id TEXT NOT NULL UNIQUE, consumed_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS ha_health (node_id TEXT NOT NULL, observer_node_id TEXT NOT NULL, sequence INTEGER NOT NULL, health_json BLOB NOT NULL, observed_at TIMESTAMP NOT NULL, PRIMARY KEY(node_id, observer_node_id));
CREATE TABLE IF NOT EXISTS ha_placement_groups (id TEXT PRIMARY KEY, node_group_id TEXT NOT NULL, generation INTEGER NOT NULL, placement_json BLOB NOT NULL);
CREATE TABLE IF NOT EXISTS ha_replica_sets (id TEXT PRIMARY KEY, placement_group_id TEXT NOT NULL, kind TEXT NOT NULL, resource_id TEXT NOT NULL, generation INTEGER NOT NULL, replica_json BLOB NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS ha_replication_channels (id TEXT PRIMARY KEY, group_id TEXT NOT NULL, kind TEXT NOT NULL, resource_id TEXT NOT NULL, source_node_id TEXT NOT NULL, target_node_id TEXT NOT NULL, state TEXT NOT NULL, generation INTEGER NOT NULL, channel_json BLOB NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE(kind, resource_id, source_node_id, target_node_id));
CREATE INDEX IF NOT EXISTS ha_channels_resource ON ha_replication_channels(kind, resource_id, state);
CREATE TABLE IF NOT EXISTS ha_checkpoints (id TEXT PRIMARY KEY, channel_id TEXT NOT NULL, source_generation INTEGER NOT NULL, write_frontier INTEGER NOT NULL, manifest_digest TEXT NOT NULL, checkpoint_json BLOB NOT NULL, verified_at TIMESTAMP NOT NULL, UNIQUE(channel_id, source_generation, write_frontier));
CREATE INDEX IF NOT EXISTS ha_checkpoints_channel ON ha_checkpoints(channel_id, write_frontier DESC);
CREATE TABLE IF NOT EXISTS ha_database_clusters (id TEXT PRIMARY KEY, group_id TEXT NOT NULL, topology TEXT NOT NULL, state TEXT NOT NULL, generation INTEGER NOT NULL, cluster_json BLOB NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS ha_writer_leases (id TEXT PRIMARY KEY, group_id TEXT NOT NULL, resource_id TEXT NOT NULL, holder_node_id TEXT NOT NULL, fencing_token INTEGER NOT NULL, authority_epoch INTEGER NOT NULL, state TEXT NOT NULL, generation INTEGER NOT NULL, lease_json BLOB NOT NULL, expires_at TIMESTAMP NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS ha_active_writer_lease ON ha_writer_leases(resource_id) WHERE state = 'active';
CREATE TABLE IF NOT EXISTS ha_fences (id TEXT PRIMARY KEY, group_id TEXT NOT NULL, target_node_id TEXT NOT NULL, class TEXT NOT NULL, fencing_token INTEGER NOT NULL, state TEXT NOT NULL, generation INTEGER NOT NULL, fence_json BLOB NOT NULL);
CREATE TABLE IF NOT EXISTS ha_traffic_policies (id TEXT PRIMARY KEY, group_id TEXT NOT NULL, provider_mode TEXT NOT NULL, generation INTEGER NOT NULL, policy_json BLOB NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS ha_promotions (id TEXT PRIMARY KEY, command_id TEXT NOT NULL UNIQUE, group_id TEXT NOT NULL, resource_id TEXT NOT NULL, state TEXT NOT NULL, generation INTEGER NOT NULL, promotion_json BLOB NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS ha_active_promotion ON ha_promotions(resource_id) WHERE state NOT IN ('committed','rolled_back','failed');
CREATE TABLE IF NOT EXISTS ha_failover_runs (id TEXT PRIMARY KEY, promotion_id TEXT NOT NULL UNIQUE, state TEXT NOT NULL, step TEXT NOT NULL, run_json BLOB NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS ha_backup_copies (id TEXT PRIMARY KEY, recovery_point_id TEXT NOT NULL, target_node_id TEXT NOT NULL, manifest_digest TEXT NOT NULL, copy_json BLOB NOT NULL, verified_at TIMESTAMP NOT NULL, UNIQUE(recovery_point_id, target_node_id));
CREATE TABLE IF NOT EXISTS ha_mail_topologies (id TEXT PRIMARY KEY, group_id TEXT NOT NULL, writer_node_id TEXT NOT NULL, generation INTEGER NOT NULL, topology_json BLOB NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS ha_dns_topologies (id TEXT PRIMARY KEY, group_id TEXT NOT NULL, primary_node_id TEXT NOT NULL, generation INTEGER NOT NULL, topology_json BLOB NOT NULL, updated_at TIMESTAMP NOT NULL);
`

type Store interface {
	CreateNodeGroup(context.Context, NodeGroup) error; LoadNodeGroup(context.Context, NodeGroupID) (NodeGroup, error); UpdateNodeGroup(context.Context, NodeGroup, uint64) error
	SaveNode(context.Context, NodeMember, uint64) error; LoadNode(context.Context, NodeID) (NodeMember, error); ListNodes(context.Context, NodeGroupID) ([]NodeMember, error); SaveHealth(context.Context, HealthObservation) error
	SavePlacementGroup(context.Context, PlacementGroup, uint64) error; LoadPlacementGroup(context.Context, PlacementGroupID) (PlacementGroup, error)
	SaveReplicaSet(context.Context, ReplicaSet, uint64) error; LoadReplicaSet(context.Context, ReplicaSetID) (ReplicaSet, error)
	CreateChannel(context.Context, ReplicationChannel) error; LoadChannel(context.Context, ChannelID) (ReplicationChannel, error); UpdateChannel(context.Context, ReplicationChannel, uint64) error
	SaveCheckpoint(context.Context, ReplicationCheckpoint) error; LoadCheckpoint(context.Context, CheckpointID) (ReplicationCheckpoint, error); LatestCheckpoint(context.Context, ChannelID) (ReplicationCheckpoint, error)
	SaveDatabaseCluster(context.Context, DatabaseCluster, uint64) error; LoadDatabaseCluster(context.Context, ID) (DatabaseCluster, error)
	CreateLease(context.Context, WriterLease) error; LoadLease(context.Context, WriterLeaseID) (WriterLease, error); UpdateLease(context.Context, WriterLease, uint64) error
	SaveFence(context.Context, Fence, uint64) error; LoadFence(context.Context, FenceID) (Fence, error)
	SaveTrafficPolicy(context.Context, TrafficPolicy, uint64) error; LoadTrafficPolicy(context.Context, TrafficPolicyID) (TrafficPolicy, error)
	CreatePromotion(context.Context, Promotion) error; LoadPromotion(context.Context, PromotionID) (Promotion, error); UpdatePromotion(context.Context, Promotion, uint64) error
	CreateFailoverRun(context.Context, FailoverRun) error; LoadFailoverRun(context.Context, FailoverRunID) (FailoverRun, error); UpdateFailoverRun(context.Context, FailoverRun) error
	SaveBackupCopy(context.Context, BackupReplicaCopy) error
	SaveMailTopology(context.Context, MailTopology, uint64) error; LoadMailTopology(context.Context, ID) (MailTopology, error)
	SaveDNSTopology(context.Context, DNSTopology, uint64) error; LoadDNSTopology(context.Context, ID) (DNSTopology, error)
}

type SQLRepository struct{ DB *sql.DB }
func (repository SQLRepository) Bootstrap(ctx context.Context) error { if repository.DB == nil { return errors.New("ha database required") }; _, err := repository.DB.ExecContext(ctx, SQLSchema); return err }
func encode(value any) ([]byte,error) { return json.Marshal(value) }
func decode(data []byte,value any) error { if len(data)==0{return ErrInvalid}; if json.Unmarshal(data,value)!=nil{return ErrInvalid}; return nil }
func one(result sql.Result) error { count,err:=result.RowsAffected();if err!=nil{return err};if count!=1{return ErrNotFound};return nil }
func cas(result sql.Result) error { count,err:=result.RowsAffected();if err!=nil{return err};if count!=1{return ErrStaleGeneration};return nil }

func (r SQLRepository) CreateNodeGroup(ctx context.Context,v NodeGroup) error { b,e:=encode(v);if e!=nil{return e};_,e=r.DB.ExecContext(ctx,`INSERT INTO ha_node_groups (id,generation,group_json,updated_at) VALUES (?,?,?,?)`,v.ID,v.Generation,b,v.UpdatedAt);return e }
func (r SQLRepository) LoadNodeGroup(ctx context.Context,id NodeGroupID)(NodeGroup,error){var b []byte;e:=r.DB.QueryRowContext(ctx,`SELECT group_json FROM ha_node_groups WHERE id=?`,id).Scan(&b);if errors.Is(e,sql.ErrNoRows){return NodeGroup{},ErrNotFound};if e!=nil{return NodeGroup{},e};var v NodeGroup;e=decode(b,&v);return v,e}
func (r SQLRepository) UpdateNodeGroup(ctx context.Context,v NodeGroup,g uint64)error{b,e:=encode(v);if e!=nil{return e};x,e:=r.DB.ExecContext(ctx,`UPDATE ha_node_groups SET generation=?,group_json=?,updated_at=? WHERE id=? AND generation=?`,v.Generation,b,v.UpdatedAt,v.ID,g);if e!=nil{return e};return cas(x)}
func (r SQLRepository) SaveNode(ctx context.Context,v NodeMember,g uint64)error{if e:=v.Validate();e!=nil{return e};b,e:=encode(v);if e!=nil{return e};if g==0{_,e=r.DB.ExecContext(ctx,`INSERT INTO ha_nodes (id,group_id,state,generation,node_json,updated_at) VALUES (?,?,?,?,?,?)`,v.ID,v.GroupID,v.State,v.Generation,b,v.UpdatedAt);return e};x,e:=r.DB.ExecContext(ctx,`UPDATE ha_nodes SET state=?,generation=?,node_json=?,updated_at=? WHERE id=? AND generation=?`,v.State,v.Generation,b,v.UpdatedAt,v.ID,g);if e!=nil{return e};return cas(x)}
func (r SQLRepository) LoadNode(ctx context.Context,id NodeID)(NodeMember,error){var b []byte;e:=r.DB.QueryRowContext(ctx,`SELECT node_json FROM ha_nodes WHERE id=?`,id).Scan(&b);if errors.Is(e,sql.ErrNoRows){return NodeMember{},ErrNotFound};if e!=nil{return NodeMember{},e};var v NodeMember;e=decode(b,&v);if e==nil{e=v.Validate()};return v,e}
func (r SQLRepository) ListNodes(ctx context.Context,id NodeGroupID)([]NodeMember,error){rows,e:=r.DB.QueryContext(ctx,`SELECT node_json FROM ha_nodes WHERE group_id=? ORDER BY id`,id);if e!=nil{return nil,e};defer rows.Close();v:=[]NodeMember{};for rows.Next(){var b []byte;if e:=rows.Scan(&b);e!=nil{return nil,e};var n NodeMember;if e:=decode(b,&n);e!=nil{return nil,e};v=append(v,n)};return v,rows.Err()}
func (r SQLRepository) ListAllNodes(ctx context.Context,cursor string,limit uint16)([]NodeMember,string,uint64,error){if r.DB==nil||ctx==nil||cursor!=""&&!validID(cursor){return nil,"",0,ErrInvalid};if limit==0{limit=100};if limit>500{return nil,"",0,ErrInvalid};var total uint64;if err:=r.DB.QueryRowContext(ctx,`SELECT COUNT(*) FROM ha_nodes`).Scan(&total);err!=nil{return nil,"",0,err};rows,err:=r.DB.QueryContext(ctx,`SELECT node_json FROM ha_nodes WHERE id>? ORDER BY id LIMIT ?`,cursor,int(limit)+1);if err!=nil{return nil,"",0,err};defer rows.Close();values:=make([]NodeMember,0,int(limit)+1);for rows.Next(){var raw []byte;if err=rows.Scan(&raw);err!=nil{return nil,"",0,err};var node NodeMember;if err=decode(raw,&node);err!=nil{return nil,"",0,err};if err=node.Validate();err!=nil{return nil,"",0,err};values=append(values,node)};if err=rows.Err();err!=nil{return nil,"",0,err};next:="";if len(values)>int(limit){next=string(values[limit-1].ID);values=values[:limit]};return values,next,total,nil}
func (r SQLRepository) AdmitEnrollment(ctx context.Context,enrollment VerifiedEnrollment,commandID string)(NodeMember,bool,error){if r.DB==nil||ctx==nil||!validID(commandID)||!validID(enrollment.TokenID)||!validDigest(enrollment.TokenDigest)||enrollment.Group.ID!=enrollment.Node.GroupID||enrollment.Group.Validate()!=nil||enrollment.Node.Validate()!=nil{return NodeMember{},false,ErrInvalid};tx,err:=r.DB.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return NodeMember{},false,err};defer tx.Rollback();var digest,nodeID,existingCommand string;err=tx.QueryRowContext(ctx,`SELECT token_digest,node_id,command_id FROM ha_enrollment_tokens WHERE token_id=? OR token_digest=? OR command_id=? LIMIT 1`,enrollment.TokenID,enrollment.TokenDigest,commandID).Scan(&digest,&nodeID,&existingCommand);if err==nil{if digest!=enrollment.TokenDigest||nodeID!=string(enrollment.Node.ID)||existingCommand!=commandID{return NodeMember{},false,ErrConflict};var raw []byte;if err=tx.QueryRowContext(ctx,`SELECT node_json FROM ha_nodes WHERE id=?`,nodeID).Scan(&raw);err!=nil{return NodeMember{},false,err};var node NodeMember;if err=decode(raw,&node);err!=nil{return NodeMember{},false,err};return node,false,tx.Commit()};if !errors.Is(err,sql.ErrNoRows){return NodeMember{},false,err};var groupRaw []byte;err=tx.QueryRowContext(ctx,`SELECT group_json FROM ha_node_groups WHERE id=?`,enrollment.Group.ID).Scan(&groupRaw);if err==nil{var existing NodeGroup;if err=decode(groupRaw,&existing);err!=nil{return NodeMember{},false,err};if !sameEnrollmentGroup(existing,enrollment.Group){return NodeMember{},false,ErrConflict}}else if errors.Is(err,sql.ErrNoRows){groupRaw,err=encode(enrollment.Group);if err==nil{_,err=tx.ExecContext(ctx,`INSERT INTO ha_node_groups (id,generation,group_json,updated_at) VALUES (?,?,?,?)`,enrollment.Group.ID,enrollment.Group.Generation,groupRaw,enrollment.Group.UpdatedAt)};if err!=nil{return NodeMember{},false,err}}else{return NodeMember{},false,err};var occupied string;err=tx.QueryRowContext(ctx,`SELECT id FROM ha_nodes WHERE id=? LIMIT 1`,enrollment.Node.ID).Scan(&occupied);if err==nil{return NodeMember{},false,ErrConflict};if !errors.Is(err,sql.ErrNoRows){return NodeMember{},false,err};nodeRaw,err:=encode(enrollment.Node);if err!=nil{return NodeMember{},false,err};if _,err=tx.ExecContext(ctx,`INSERT INTO ha_nodes (id,group_id,state,generation,node_json,updated_at) VALUES (?,?,?,?,?,?)`,enrollment.Node.ID,enrollment.Node.GroupID,enrollment.Node.State,enrollment.Node.Generation,nodeRaw,enrollment.Node.UpdatedAt);err!=nil{return NodeMember{},false,err};if _,err=tx.ExecContext(ctx,`INSERT INTO ha_enrollment_tokens (token_id,token_digest,node_id,command_id,consumed_at) VALUES (?,?,?,?,?)`,enrollment.TokenID,enrollment.TokenDigest,enrollment.Node.ID,commandID,enrollment.Node.UpdatedAt);err!=nil{return NodeMember{},false,err};if err=tx.Commit();err!=nil{return NodeMember{},false,err};return enrollment.Node,true,nil}
func (r SQLRepository) SaveHealth(ctx context.Context,v HealthObservation)error{b,e:=encode(v);if e!=nil{return e};_,e=r.DB.ExecContext(ctx,`INSERT INTO ha_health (node_id,observer_node_id,sequence,health_json,observed_at) VALUES (?,?,?,?,?) ON CONFLICT(node_id,observer_node_id) DO UPDATE SET sequence=excluded.sequence,health_json=excluded.health_json,observed_at=excluded.observed_at WHERE ha_health.sequence < excluded.sequence`,v.NodeID,v.ObserverNodeID,v.Sequence,b,v.ObservedAt);return e}
func (r SQLRepository) SavePlacementGroup(ctx context.Context,v PlacementGroup,g uint64)error{b,e:=encode(v);if e!=nil{return e};if g==0{_,e=r.DB.ExecContext(ctx,`INSERT INTO ha_placement_groups (id,node_group_id,generation,placement_json) VALUES (?,?,?,?)`,v.ID,v.NodeGroupID,v.Generation,b);return e};x,e:=r.DB.ExecContext(ctx,`UPDATE ha_placement_groups SET generation=?,placement_json=? WHERE id=? AND generation=?`,v.Generation,b,v.ID,g);if e!=nil{return e};return cas(x)}
func (r SQLRepository) LoadPlacementGroup(ctx context.Context,id PlacementGroupID)(PlacementGroup,error){var b []byte;e:=r.DB.QueryRowContext(ctx,`SELECT placement_json FROM ha_placement_groups WHERE id=?`,id).Scan(&b);if errors.Is(e,sql.ErrNoRows){return PlacementGroup{},ErrNotFound};if e!=nil{return PlacementGroup{},e};var v PlacementGroup;e=decode(b,&v);return v,e}
func (r SQLRepository) SaveReplicaSet(ctx context.Context,v ReplicaSet,g uint64)error{b,e:=encode(v);if e!=nil{return e};if g==0{_,e=r.DB.ExecContext(ctx,`INSERT INTO ha_replica_sets (id,placement_group_id,kind,resource_id,generation,replica_json,updated_at) VALUES (?,?,?,?,?,?,?)`,v.ID,v.PlacementGroupID,v.Kind,v.ResourceID,v.Generation,b,v.UpdatedAt);return e};x,e:=r.DB.ExecContext(ctx,`UPDATE ha_replica_sets SET generation=?,replica_json=?,updated_at=? WHERE id=? AND generation=?`,v.Generation,b,v.UpdatedAt,v.ID,g);if e!=nil{return e};return cas(x)}
func (r SQLRepository) LoadReplicaSet(ctx context.Context,id ReplicaSetID)(ReplicaSet,error){var b []byte;e:=r.DB.QueryRowContext(ctx,`SELECT replica_json FROM ha_replica_sets WHERE id=?`,id).Scan(&b);if errors.Is(e,sql.ErrNoRows){return ReplicaSet{},ErrNotFound};if e!=nil{return ReplicaSet{},e};var v ReplicaSet;e=decode(b,&v);return v,e}
func (r SQLRepository) CreateChannel(ctx context.Context,v ReplicationChannel)error{if e:=v.Validate();e!=nil{return e};b,e:=encode(v);if e!=nil{return e};_,e=r.DB.ExecContext(ctx,`INSERT INTO ha_replication_channels (id,group_id,kind,resource_id,source_node_id,target_node_id,state,generation,channel_json,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)`,v.ID,v.GroupID,v.Kind,v.ResourceID,v.SourceNodeID,v.TargetNodeID,v.State,v.Generation,b,v.UpdatedAt);return e}
func (r SQLRepository) LoadChannel(ctx context.Context,id ChannelID)(ReplicationChannel,error){var b []byte;e:=r.DB.QueryRowContext(ctx,`SELECT channel_json FROM ha_replication_channels WHERE id=?`,id).Scan(&b);if errors.Is(e,sql.ErrNoRows){return ReplicationChannel{},ErrNotFound};if e!=nil{return ReplicationChannel{},e};var v ReplicationChannel;e=decode(b,&v);return v,e}
func (r SQLRepository) ChannelForResourceTarget(ctx context.Context,group NodeGroupID,resource string,source,target NodeID)(ReplicationChannel,error){if r.DB==nil||ctx==nil||!validID(string(group))||resource==""||!validID(string(source))||!validID(string(target))||source==target{return ReplicationChannel{},ErrInvalid};var raw []byte;err:=r.DB.QueryRowContext(ctx,`SELECT channel_json FROM ha_replication_channels WHERE group_id=? AND resource_id=? AND source_node_id=? AND target_node_id=? AND state IN ('caught_up','lagging','syncing') ORDER BY CASE state WHEN 'caught_up' THEN 0 WHEN 'lagging' THEN 1 ELSE 2 END,updated_at DESC LIMIT 1`,group,resource,source,target).Scan(&raw);if errors.Is(err,sql.ErrNoRows){return ReplicationChannel{},ErrNotFound};if err!=nil{return ReplicationChannel{},err};var channel ReplicationChannel;if err=decode(raw,&channel);err!=nil{return ReplicationChannel{},err};if err=channel.Validate();err!=nil{return ReplicationChannel{},err};return channel,nil}
func (r SQLRepository) UpdateChannel(ctx context.Context,v ReplicationChannel,g uint64)error{if e:=v.Validate();e!=nil{return e};b,e:=encode(v);if e!=nil{return e};x,e:=r.DB.ExecContext(ctx,`UPDATE ha_replication_channels SET state=?,generation=?,channel_json=?,updated_at=? WHERE id=? AND generation=?`,v.State,v.Generation,b,v.UpdatedAt,v.ID,g);if e!=nil{return e};return cas(x)}
func (r SQLRepository) SaveCheckpoint(ctx context.Context,v ReplicationCheckpoint)error{if e:=v.Validate();e!=nil{return e};b,e:=encode(v);if e!=nil{return e};_,e=r.DB.ExecContext(ctx,`INSERT INTO ha_checkpoints (id,channel_id,source_generation,write_frontier,manifest_digest,checkpoint_json,verified_at) VALUES (?,?,?,?,?,?,?)`,v.ID,v.ChannelID,v.SourceGeneration,v.WriteFrontier,v.ManifestDigest,b,v.VerifiedAt);return e}
func (r SQLRepository) LoadCheckpoint(ctx context.Context,id CheckpointID)(ReplicationCheckpoint,error){var b []byte;e:=r.DB.QueryRowContext(ctx,`SELECT checkpoint_json FROM ha_checkpoints WHERE id=?`,id).Scan(&b);if errors.Is(e,sql.ErrNoRows){return ReplicationCheckpoint{},ErrNotFound};if e!=nil{return ReplicationCheckpoint{},e};var v ReplicationCheckpoint;e=decode(b,&v);return v,e}
func (r SQLRepository) LatestCheckpoint(ctx context.Context,id ChannelID)(ReplicationCheckpoint,error){var b []byte;e:=r.DB.QueryRowContext(ctx,`SELECT checkpoint_json FROM ha_checkpoints WHERE channel_id=? ORDER BY write_frontier DESC LIMIT 1`,id).Scan(&b);if errors.Is(e,sql.ErrNoRows){return ReplicationCheckpoint{},ErrNotFound};if e!=nil{return ReplicationCheckpoint{},e};var v ReplicationCheckpoint;e=decode(b,&v);return v,e}
func (r SQLRepository) SaveDatabaseCluster(ctx context.Context,v DatabaseCluster,g uint64)error{if e:=v.Validate();e!=nil{return e};b,e:=encode(v);if e!=nil{return e};if g==0{_,e=r.DB.ExecContext(ctx,`INSERT INTO ha_database_clusters (id,group_id,topology,state,generation,cluster_json,updated_at) VALUES (?,?,?,?,?,?,?)`,v.ID,v.GroupID,v.Topology,v.State,v.Generation,b,v.UpdatedAt);return e};x,e:=r.DB.ExecContext(ctx,`UPDATE ha_database_clusters SET state=?,generation=?,cluster_json=?,updated_at=? WHERE id=? AND generation=?`,v.State,v.Generation,b,v.UpdatedAt,v.ID,g);if e!=nil{return e};return cas(x)}
func (r SQLRepository) LoadDatabaseCluster(ctx context.Context,id ID)(DatabaseCluster,error){var b []byte;e:=r.DB.QueryRowContext(ctx,`SELECT cluster_json FROM ha_database_clusters WHERE id=?`,id).Scan(&b);if errors.Is(e,sql.ErrNoRows){return DatabaseCluster{},ErrNotFound};if e!=nil{return DatabaseCluster{},e};var v DatabaseCluster;e=decode(b,&v);return v,e}
func (r SQLRepository) CreateLease(ctx context.Context,v WriterLease)error{b,e:=encode(v);if e!=nil{return e};_,e=r.DB.ExecContext(ctx,`INSERT INTO ha_writer_leases (id,group_id,resource_id,holder_node_id,fencing_token,authority_epoch,state,generation,lease_json,expires_at) VALUES (?,?,?,?,?,?,?,?,?,?)`,v.ID,v.GroupID,v.ResourceID,v.HolderNodeID,v.FencingToken,v.AuthorityEpoch,v.State,v.Generation,b,v.ExpiresAt);return e}
func (r SQLRepository) LoadLease(ctx context.Context,id WriterLeaseID)(WriterLease,error){var b []byte;e:=r.DB.QueryRowContext(ctx,`SELECT lease_json FROM ha_writer_leases WHERE id=?`,id).Scan(&b);if errors.Is(e,sql.ErrNoRows){return WriterLease{},ErrNotFound};if e!=nil{return WriterLease{},e};var v WriterLease;e=decode(b,&v);return v,e}
func (r SQLRepository) ActiveWriterLeaseByResource(ctx context.Context,resource string)(WriterLease,error){if r.DB==nil||ctx==nil||resource==""{return WriterLease{},ErrInvalid};var raw []byte;err:=r.DB.QueryRowContext(ctx,`SELECT lease_json FROM ha_writer_leases WHERE resource_id=? AND state='active' ORDER BY authority_epoch DESC,fencing_token DESC LIMIT 1`,resource).Scan(&raw);if errors.Is(err,sql.ErrNoRows){return WriterLease{},ErrNotFound};if err!=nil{return WriterLease{},err};var lease WriterLease;if err=decode(raw,&lease);err!=nil{return WriterLease{},err};return lease,nil}
func (r SQLRepository) UpdateLease(ctx context.Context,v WriterLease,g uint64)error{b,e:=encode(v);if e!=nil{return e};x,e:=r.DB.ExecContext(ctx,`UPDATE ha_writer_leases SET holder_node_id=?,fencing_token=?,authority_epoch=?,state=?,generation=?,lease_json=?,expires_at=? WHERE id=? AND generation=?`,v.HolderNodeID,v.FencingToken,v.AuthorityEpoch,v.State,v.Generation,b,v.ExpiresAt,v.ID,g);if e!=nil{return e};return cas(x)}
func (r SQLRepository) SaveFence(ctx context.Context,v Fence,g uint64)error{b,e:=encode(v);if e!=nil{return e};if g==0{_,e=r.DB.ExecContext(ctx,`INSERT INTO ha_fences (id,group_id,target_node_id,class,fencing_token,state,generation,fence_json) VALUES (?,?,?,?,?,?,?,?)`,v.ID,v.GroupID,v.TargetNodeID,v.Class,v.FencingToken,v.State,v.Generation,b);return e};x,e:=r.DB.ExecContext(ctx,`UPDATE ha_fences SET state=?,generation=?,fence_json=? WHERE id=? AND generation=?`,v.State,v.Generation,b,v.ID,g);if e!=nil{return e};return cas(x)}
func (r SQLRepository) LoadFence(ctx context.Context,id FenceID)(Fence,error){var b []byte;e:=r.DB.QueryRowContext(ctx,`SELECT fence_json FROM ha_fences WHERE id=?`,id).Scan(&b);if errors.Is(e,sql.ErrNoRows){return Fence{},ErrNotFound};if e!=nil{return Fence{},e};var v Fence;e=decode(b,&v);return v,e}
func (r SQLRepository) SaveTrafficPolicy(ctx context.Context,v TrafficPolicy,g uint64)error{b,e:=encode(v);if e!=nil{return e};if g==0{_,e=r.DB.ExecContext(ctx,`INSERT INTO ha_traffic_policies (id,group_id,provider_mode,generation,policy_json,updated_at) VALUES (?,?,?,?,?,?)`,v.ID,v.GroupID,v.ProviderMode,v.Generation,b,v.UpdatedAt);return e};x,e:=r.DB.ExecContext(ctx,`UPDATE ha_traffic_policies SET generation=?,policy_json=?,updated_at=? WHERE id=? AND generation=?`,v.Generation,b,v.UpdatedAt,v.ID,g);if e!=nil{return e};return cas(x)}
func (r SQLRepository) LoadTrafficPolicy(ctx context.Context,id TrafficPolicyID)(TrafficPolicy,error){var b []byte;e:=r.DB.QueryRowContext(ctx,`SELECT policy_json FROM ha_traffic_policies WHERE id=?`,id).Scan(&b);if errors.Is(e,sql.ErrNoRows){return TrafficPolicy{},ErrNotFound};if e!=nil{return TrafficPolicy{},e};var v TrafficPolicy;e=decode(b,&v);return v,e}
func (r SQLRepository) TrafficPolicyByResource(ctx context.Context,group NodeGroupID,resource string)(TrafficPolicy,error){if r.DB==nil||ctx==nil||!validID(string(group))||resource==""{return TrafficPolicy{},ErrInvalid};rows,err:=r.DB.QueryContext(ctx,`SELECT policy_json FROM ha_traffic_policies WHERE group_id=? ORDER BY updated_at DESC`,group);if err!=nil{return TrafficPolicy{},err};defer rows.Close();var selected TrafficPolicy;found:=false;for rows.Next(){var raw []byte;if err=rows.Scan(&raw);err!=nil{return TrafficPolicy{},err};var policy TrafficPolicy;if err=decode(raw,&policy);err!=nil{return TrafficPolicy{},err};if policy.Resource!=resource{continue};if found{return TrafficPolicy{},ErrProviderAmbiguous};selected=policy;found=true};if err=rows.Err();err!=nil{return TrafficPolicy{},err};if !found{return TrafficPolicy{},ErrNotFound};return selected,nil}
func (r SQLRepository) CreatePromotion(ctx context.Context,v Promotion)error{b,e:=encode(v);if e!=nil{return e};_,e=r.DB.ExecContext(ctx,`INSERT INTO ha_promotions (id,command_id,group_id,resource_id,state,generation,promotion_json,updated_at) VALUES (?,?,?,?,?,?,?,?)`,v.ID,v.CommandID,v.GroupID,v.ResourceID,v.State,v.Generation,b,v.UpdatedAt);return e}
func (r SQLRepository) LoadPromotion(ctx context.Context,id PromotionID)(Promotion,error){var b []byte;e:=r.DB.QueryRowContext(ctx,`SELECT promotion_json FROM ha_promotions WHERE id=?`,id).Scan(&b);if errors.Is(e,sql.ErrNoRows){return Promotion{},ErrNotFound};if e!=nil{return Promotion{},e};var v Promotion;e=decode(b,&v);return v,e}
func (r SQLRepository) PromotionByCommand(ctx context.Context,id CommandID)(Promotion,error){if r.DB==nil||ctx==nil||!validID(string(id)){return Promotion{},ErrInvalid};var raw []byte;err:=r.DB.QueryRowContext(ctx,`SELECT promotion_json FROM ha_promotions WHERE command_id=?`,id).Scan(&raw);if errors.Is(err,sql.ErrNoRows){return Promotion{},ErrNotFound};if err!=nil{return Promotion{},err};var promotion Promotion;if err=decode(raw,&promotion);err!=nil{return Promotion{},err};return promotion,nil}
func (r SQLRepository) UpdatePromotion(ctx context.Context,v Promotion,g uint64)error{b,e:=encode(v);if e!=nil{return e};x,e:=r.DB.ExecContext(ctx,`UPDATE ha_promotions SET state=?,generation=?,promotion_json=?,updated_at=? WHERE id=? AND generation=?`,v.State,v.Generation,b,v.UpdatedAt,v.ID,g);if e!=nil{return e};return cas(x)}
func (r SQLRepository) CreateFailoverRun(ctx context.Context,v FailoverRun)error{b,e:=encode(v);if e!=nil{return e};_,e=r.DB.ExecContext(ctx,`INSERT INTO ha_failover_runs (id,promotion_id,state,step,run_json,updated_at) VALUES (?,?,?,?,?,?)`,v.ID,v.PromotionID,v.State,v.Step,b,v.UpdatedAt);return e}
func (r SQLRepository) LoadFailoverRun(ctx context.Context,id FailoverRunID)(FailoverRun,error){var b []byte;e:=r.DB.QueryRowContext(ctx,`SELECT run_json FROM ha_failover_runs WHERE id=?`,id).Scan(&b);if errors.Is(e,sql.ErrNoRows){return FailoverRun{},ErrNotFound};if e!=nil{return FailoverRun{},e};var v FailoverRun;e=decode(b,&v);return v,e}
func (r SQLRepository) UpdateFailoverRun(ctx context.Context,v FailoverRun)error{b,e:=encode(v);if e!=nil{return e};x,e:=r.DB.ExecContext(ctx,`UPDATE ha_failover_runs SET state=?,step=?,run_json=?,updated_at=? WHERE id=?`,v.State,v.Step,b,v.UpdatedAt,v.ID);if e!=nil{return e};return one(x)}
func (r SQLRepository) SaveBackupCopy(ctx context.Context,v BackupReplicaCopy)error{if !validDigest(v.ManifestDigest)||v.CommitMarker==""||v.VerifiedAt.IsZero(){return ErrInvalid};b,e:=encode(v);if e!=nil{return e};_,e=r.DB.ExecContext(ctx,`INSERT INTO ha_backup_copies (id,recovery_point_id,target_node_id,manifest_digest,copy_json,verified_at) VALUES (?,?,?,?,?,?)`,v.ID,v.RecoveryPointID,v.TargetNodeID,v.ManifestDigest,b,v.VerifiedAt);return e}
func (r SQLRepository) SaveMailTopology(ctx context.Context,v MailTopology,g uint64)error{if e:=v.Validate();e!=nil{return e};b,e:=encode(v);if e!=nil{return e};if g==0{_,e=r.DB.ExecContext(ctx,`INSERT INTO ha_mail_topologies (id,group_id,writer_node_id,generation,topology_json,updated_at) VALUES (?,?,?,?,?,?)`,v.ID,v.GroupID,v.MailboxWriterNodeID,v.Generation,b,v.UpdatedAt);return e};x,e:=r.DB.ExecContext(ctx,`UPDATE ha_mail_topologies SET writer_node_id=?,generation=?,topology_json=?,updated_at=? WHERE id=? AND generation=?`,v.MailboxWriterNodeID,v.Generation,b,v.UpdatedAt,v.ID,g);if e!=nil{return e};return cas(x)}
func (r SQLRepository) LoadMailTopology(ctx context.Context,id ID)(MailTopology,error){var b []byte;e:=r.DB.QueryRowContext(ctx,`SELECT topology_json FROM ha_mail_topologies WHERE id=?`,id).Scan(&b);if errors.Is(e,sql.ErrNoRows){return MailTopology{},ErrNotFound};if e!=nil{return MailTopology{},e};var v MailTopology;e=decode(b,&v);return v,e}
func (r SQLRepository) SaveDNSTopology(ctx context.Context,v DNSTopology,g uint64)error{b,e:=encode(v);if e!=nil{return e};if g==0{_,e=r.DB.ExecContext(ctx,`INSERT INTO ha_dns_topologies (id,group_id,primary_node_id,generation,topology_json,updated_at) VALUES (?,?,?,?,?,?)`,v.ID,v.GroupID,v.PrimaryNodeID,v.Generation,b,v.UpdatedAt);return e};x,e:=r.DB.ExecContext(ctx,`UPDATE ha_dns_topologies SET primary_node_id=?,generation=?,topology_json=?,updated_at=? WHERE id=? AND generation=?`,v.PrimaryNodeID,v.Generation,b,v.UpdatedAt,v.ID,g);if e!=nil{return e};return cas(x)}
func (r SQLRepository) LoadDNSTopology(ctx context.Context,id ID)(DNSTopology,error){var b []byte;e:=r.DB.QueryRowContext(ctx,`SELECT topology_json FROM ha_dns_topologies WHERE id=?`,id).Scan(&b);if errors.Is(e,sql.ErrNoRows){return DNSTopology{},ErrNotFound};if e!=nil{return DNSTopology{},e};var v DNSTopology;e=decode(b,&v);return v,e}

func sameEnrollmentGroup(left,right NodeGroup)bool{
	if left.ID!=right.ID||left.Name!=right.Name||left.CoordinatorID!=right.CoordinatorID||left.MinimumManagers!=right.MinimumManagers||left.AutomaticFailover!=right.AutomaticFailover{return false}
	leftFences:=sortedIDs(left.RequiredFenceClasses);rightFences:=sortedIDs(right.RequiredFenceClasses)
	if len(leftFences)!=len(rightFences){return false}
	for index:=range leftFences{if leftFences[index]!=rightFences[index]{return false}}
	return true
}
