package ha

import (
	"context"
	"fmt"
	"time"
)

type GroupService struct { Store Store; Health HealthAuthority; Now func() time.Time }
func (service GroupService) now() time.Time { if service.Now!=nil{return service.Now().UTC()};return time.Now().UTC() }
func (service GroupService) CreateGroup(ctx context.Context,group NodeGroup)error{if service.Store==nil||group.Generation!=1{return ErrInvalid};group.UpdatedAt=service.now();if err:=group.Validate();err!=nil{return err};return service.Store.CreateNodeGroup(ctx,group)}
func (service GroupService) EnrollNode(ctx context.Context,node NodeMember)error{if service.Store==nil{return ErrInvalid};if err:=node.Validate();err!=nil{return err};group,err:=service.Store.LoadNodeGroup(ctx,node.GroupID);if err!=nil{return err};if group.State!="active"&&group.State!="forming"{return ErrConflict};return service.Store.SaveNode(ctx,node,0)}
func (service GroupService) SetNodeState(ctx context.Context,id NodeID,expected uint64,state NodeState)(NodeMember,error){node,err:=service.Store.LoadNode(ctx,id);if err!=nil{return NodeMember{},err};if node.Generation!=expected{return NodeMember{},ErrStaleGeneration};switch state{case NodeDraining,NodeFenced,NodeDegraded,NodeOffline,NodeRetired,NodeReady:default:return NodeMember{},ErrInvalid};previous:=node.Generation;node.State,node.Generation,node.UpdatedAt=state,node.Generation+1,service.now();if err:=service.Store.SaveNode(ctx,node,previous);err!=nil{return NodeMember{},err};return node,nil}
func (service GroupService) BeginDrain(ctx context.Context,id NodeID,expected uint64,deadline time.Time,force bool)(NodeMember,error){if service.Store==nil||ctx==nil{return NodeMember{},ErrInvalid};node,err:=service.Store.LoadNode(ctx,id);if err!=nil{return NodeMember{},err};if node.Generation!=expected{return NodeMember{},ErrStaleGeneration};if node.State==NodeRetired||node.State==NodeFenced{return NodeMember{},ErrConflict};now:=service.now();if deadline.IsZero(){deadline=now.Add(30*time.Minute)};deadline=deadline.UTC();if !deadline.After(now)||deadline.After(now.Add(7*24*time.Hour)){return NodeMember{},ErrInvalid};previous:=node.Generation;labels:=make(map[string]string,len(node.Labels)+2);for key,value:=range node.Labels{labels[key]=value};labels["drain_deadline"]=deadline.Format(time.RFC3339Nano);if force{labels["drain_force"]="true"}else{delete(labels,"drain_force")};node.Labels=labels;node.State=NodeDraining;node.Generation++;node.UpdatedAt=now;if err=service.Store.SaveNode(ctx,node,previous);err!=nil{return NodeMember{},err};return node,nil}
func (service GroupService) ObserveHealth(ctx context.Context,nodeID NodeID)(HealthObservation,error){if service.Health==nil{return HealthObservation{},ErrInvalid};observation,err:=service.Health.ObserveNode(ctx,nodeID);if err!=nil{return HealthObservation{},err};if observation.NodeID!=nodeID||observation.Sequence==0||observation.Signature==""||observation.ObservedAt.IsZero()||!observation.ValidUntil.After(observation.ObservedAt){return HealthObservation{},ErrInvalid};if err:=service.Store.SaveHealth(ctx,observation);err!=nil{return HealthObservation{},err};return observation,nil}

type ChannelService struct { Store Store; Now func() time.Time }
func (service ChannelService) now()time.Time{if service.Now!=nil{return service.Now().UTC()};return time.Now().UTC()}
func (service ChannelService) Create(ctx context.Context,channel ReplicationChannel)error{if channel.State!=""&&channel.State!=ChannelPending{return ErrInvalid};channel.State=ChannelPending;channel.Generation=1;channel.CreatedAt=service.now();channel.UpdatedAt=service.now();if err:=channel.Validate();err!=nil{return err};source,err:=service.Store.LoadNode(ctx,channel.SourceNodeID);if err!=nil{return err};target,err:=service.Store.LoadNode(ctx,channel.TargetNodeID);if err!=nil{return err};if source.GroupID!=channel.GroupID||target.GroupID!=channel.GroupID||source.State!=NodeReady||target.State==NodeRetired{return ErrConflict};return service.Store.CreateChannel(ctx,channel)}
func (service ChannelService) SetPaused(ctx context.Context,id ChannelID,expected uint64,paused bool)(ReplicationChannel,error){channel,err:=service.Store.LoadChannel(ctx,id);if err!=nil{return ReplicationChannel{},err};if channel.Generation!=expected{return ReplicationChannel{},ErrStaleGeneration};previous:=channel.Generation;if paused{channel.State=ChannelPaused}else{channel.State=ChannelPending};channel.Generation++;channel.UpdatedAt=service.now();if err:=service.Store.UpdateChannel(ctx,channel,previous);err!=nil{return ReplicationChannel{},err};return channel,nil}

type LeaseService struct { Store Store; Authority LeaseAuthority; Health HealthAuthority; Gate WriterGate; Now func() time.Time }
func (service LeaseService) now()time.Time{if service.Now!=nil{return service.Now().UTC()};return time.Now().UTC()}
func (service LeaseService) Renew(ctx context.Context,id WriterLeaseID,expected uint64)(WriterLease,error){lease,err:=service.Store.LoadLease(ctx,id);if err!=nil{return WriterLease{},err};if lease.Generation!=expected||lease.State!=LeaseActive{return WriterLease{},ErrLeaseLost};quorum,err:=service.Health.Quorum(ctx,lease.GroupID);if err!=nil||quorum.Validate(service.now())!=nil{return WriterLease{},service.lose(ctx,lease)};renewed,err:=service.Authority.RenewWriterLease(ctx,lease,quorum);if err!=nil{return WriterLease{},service.lose(ctx,lease)};if renewed.FencingToken<lease.FencingToken||renewed.AuthorityEpoch!=lease.AuthorityEpoch||renewed.HolderNodeID!=lease.HolderNodeID{return WriterLease{},service.lose(ctx,lease)};renewed.Generation=lease.Generation+1;if err:=service.Store.UpdateLease(ctx,renewed,lease.Generation);err!=nil{return WriterLease{},err};return renewed,nil}
func (service LeaseService) Revoke(ctx context.Context,id WriterLeaseID,expected uint64)error{lease,err:=service.Store.LoadLease(ctx,id);if err!=nil{return err};if lease.Generation!=expected{return ErrStaleGeneration};if err:=service.Authority.RevokeWriterLease(ctx,id,lease.FencingToken,lease.AuthorityEpoch);err!=nil{return err};previous:=lease.Generation;lease.State,lease.Generation=LeaseRevoked,lease.Generation+1;return service.Store.UpdateLease(ctx,lease,previous)}
func (service LeaseService) lose(ctx context.Context,lease WriterLease)error{previous:=lease.Generation;lease.State,lease.Generation=LeaseLost,lease.Generation+1;_ = service.Store.UpdateLease(ctx,lease,previous);if service.Gate!=nil{_,_ = service.Gate.FreezeResourceWrites(ctx,lease.ResourceID,lease.HolderNodeID,lease.FencingToken,lease.EnforcedWritePaths)};return ErrLeaseLost}

func (service LeaseService) AuthorizeWrite(ctx context.Context,id WriterLeaseID,node NodeID,path string,fencingToken,authorityEpoch uint64)(WriterLease,error){lease,err:=service.Store.LoadLease(ctx,id);if err!=nil{return WriterLease{},err};if lease.State!=LeaseActive||lease.HolderNodeID!=node||lease.FencingToken!=fencingToken||lease.AuthorityEpoch!=authorityEpoch||!service.now().Before(lease.ExpiresAt){return WriterLease{},service.lose(ctx,lease)};covered:=false;for _,allowed:=range lease.EnforcedWritePaths{if allowed==path{covered=true}};if !covered{return WriterLease{},ErrFenceRequired};observed,err:=service.Authority.ObserveWriterLease(ctx,id);if err!=nil||observed.FencingToken!=lease.FencingToken||observed.HolderNodeID!=node||observed.State!=LeaseActive{return WriterLease{},service.lose(ctx,lease)};return lease,nil}

type ReplicaService struct { Store Store; Placement PlacementCoordinator; Now func() time.Time }
func (service ReplicaService) Reconcile(ctx context.Context,setID ReplicaSetID,group NodeGroup,authorityEpoch uint64)(ReplicaSet,error){set,err:=service.Store.LoadReplicaSet(ctx,setID);if err!=nil{return ReplicaSet{},err};placement,err:=service.Store.LoadPlacementGroup(ctx,set.PlacementGroupID);if err!=nil{return ReplicaSet{},err};nodes,err:=service.Placement.SelectNodes(ctx,placement,set.Desired);if err!=nil{return ReplicaSet{},err};existing:=map[NodeID]Replica{};for _,replica:=range set.Replicas{existing[replica.NodeID]=replica};next:=make([]Replica,0,len(nodes));for index,node:=range nodes{replica,exists:=existing[node.ID];if !exists{replica=Replica{ID:ReplicaID(fmt.Sprintf("%s:%d",set.ID,index+1)),ReplicaSetID:set.ID,NodeID:node.ID,Revision:set.Revision,State:ReplicaPending,UpdatedAt:time.Now().UTC()};intent:=ReplicaIntent{Kind:ReplicaPlace,ReplicaSetID:set.ID,ReplicaID:replica.ID,WorkloadKind:set.Kind,ResourceID:set.ResourceID,Revision:set.Revision,ImageDigest:set.ImageDigest,ResourceProfileID:set.ResourceProfileID,SecretGrantRef:set.SecretBundleRef,DesiredState:ReplicaReady};receipt,intentErr:=service.Placement.ApplyReplicaIntent(ctx,group,node,intent,1,authorityEpoch);if intentErr!=nil{replica.State=ReplicaFailed}else{replica.IntentID=receipt.IntentID;replica.ObservedReceipt=receipt.Receipt;if receipt.Terminal{replica.State=ReplicaReady}else{replica.State=ReplicaStarting}}};next=append(next,replica)};healthy:=0;for _,replica:=range next{if replica.State==ReplicaReady{healthy++}};if healthy<int(set.MinimumHealthy)&&len(existing)>0{return set,ErrConflict};previous:=set.Generation;set.Replicas,set.Generation,set.UpdatedAt=next,set.Generation+1,time.Now().UTC();if err:=service.Store.SaveReplicaSet(ctx,set,previous);err!=nil{return ReplicaSet{},err};return set,nil}

type RejoinCoordinator struct { Store Store; Replication ReplicationCoordinator; Database DatabaseReplicationExecutor; Federation Federation; Now func() time.Time }
func (coordinator RejoinCoordinator) RebuildChannelTarget(ctx context.Context,channelID ChannelID,targetGeneration,fencingToken uint64)(ReplicationCheckpoint,error){channel,err:=coordinator.Store.LoadChannel(ctx,channelID);if err!=nil{return ReplicationCheckpoint{},err};checkpoint,err:=coordinator.Store.LatestCheckpoint(ctx,channelID);if err!=nil{return ReplicationCheckpoint{},err};if channel.State!=ChannelFailed&&channel.State!=ChannelRebuilding&&channel.State!=ChannelPaused{return ReplicationCheckpoint{},ErrConflict};previous:=channel.Generation;channel.State,channel.Generation,channel.UpdatedAt=ChannelRebuilding,channel.Generation+1,time.Now().UTC();if err:=coordinator.Store.UpdateChannel(ctx,channel,previous);err!=nil{return ReplicationCheckpoint{},err};if channel.Kind==DataDatabase{return coordinator.Replication.Replicate(ctx,channelID,checkpoint.SourceGeneration,targetGeneration,fencingToken)};view:=StableView{ID:checkpoint.StableViewRef,ResourceID:channel.ResourceID,Generation:checkpoint.SourceGeneration,WriteFrontier:checkpoint.WriteFrontier,ManifestDigest:checkpoint.ManifestDigest,Consistency:checkpoint.Consistency,ExpiresAt:time.Now().Add(time.Hour)};if coordinator.Replication.Grants==nil{return ReplicationCheckpoint{},ErrInvalid};grant,err:=coordinator.Replication.Grants.IssueReplicationGrant(ctx,channel,view,view.ExpiresAt);if err!=nil{return ReplicationCheckpoint{},err};execution:=ReplicationExecution{Channel:channel,SourceView:view,PreviousCheckpoint:&checkpoint,TargetGeneration:targetGeneration,FencingToken:fencingToken,EncryptedTransferGrant:grant};receipt,err:=coordinator.Replication.Executor.RebuildTarget(ctx,execution,checkpoint);if err!=nil{return ReplicationCheckpoint{},err};if receipt.ManifestDigest!=checkpoint.ManifestDigest||receipt.WriteFrontier!=checkpoint.WriteFrontier{return ReplicationCheckpoint{},ErrCheckpointStale};previous=channel.Generation;channel.State,channel.Generation,channel.UpdatedAt=ChannelCaughtUp,channel.Generation+1,time.Now().UTC();if err:=coordinator.Store.UpdateChannel(ctx,channel,previous);err!=nil{return ReplicationCheckpoint{},err};return checkpoint,nil}
