package apiserver

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"net/http"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/identity"
	"github.com/aonsyed/cyberpanel/platform/internal/mail"
)

type MarketingListPayload struct{List mail.List `json:"list"`}
type MarketingSubscriberPayload struct{ID mail.ContactID `json:"id,omitempty"`;Address mail.Address `json:"address"`;Name string `json:"name,omitempty"`;Tags string `json:"tags,omitempty"`}
type MarketingSubscriberPagePayload struct{State mail.SubscriberState `json:"state,omitempty"`;Limit uint16 `json:"limit"`;Cursor string `json:"cursor,omitempty"`}
type MarketingVerificationPayload struct{State mail.VerificationState `json:"state"`;EvidenceRef string `json:"evidence_ref"`}
type MarketingTemplatePayload struct{Template mail.CampaignTemplate `json:"template"`;Name string `json:"name,omitempty"`;Text string `json:"text,omitempty"`}
type MarketingCampaignPayload struct{Campaign mail.Campaign `json:"campaign"`;ListID mail.ListID `json:"list_id,omitempty"`;Subject string `json:"subject,omitempty"`;TemplateRef string `json:"template_ref,omitempty"`;FromMailbox mail.MailboxID `json:"from_mailbox,omitempty"`;ReplyTo mail.Address `json:"reply_to,omitempty"`;Schedule string `json:"schedule,omitempty"`}
type MarketingConsentPayload struct{Event mail.ConsentEvent `json:"event"`}
type MarketingAddressPayload struct{Address mail.Address `json:"address"`}
type MarketingUnsubscribePayload struct{Token string `json:"token"`}
type MarketingStatePagePayload struct{Limit uint16 `json:"limit"`;Cursor string `json:"cursor,omitempty"`}
type MarketingAttemptPagePayload struct{CampaignID mail.CampaignID `json:"campaign_id"`;Limit uint16 `json:"limit"`;Cursor string `json:"cursor,omitempty"`}
type MarketingSendPayload struct{CampaignID mail.CampaignID `json:"campaign_id"`;ContactID mail.ContactID `json:"contact_id"`}
type MarketingListPage struct{Items []mail.List `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type MarketingSubscriberPage struct{Items []mail.Subscriber `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type MarketingTemplatePage struct{Items []mail.CampaignTemplate `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type MarketingCampaignPage struct{Items []mail.Campaign `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type MarketingAttemptPage struct{Items []mail.CampaignAttempt `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type MarketingConsentPage struct{Items []mail.ConsentEvent `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type MarketingConsentCurrent struct{Found bool `json:"found"`;Event mail.ConsentEvent `json:"event,omitempty"`}

func registerMarketingContracts(registry *Registry)error{
	permission:=identity.MustPermission("mail:manage")
	definitions:=[]Operation{
		{Name:"marketing.unsubscribe",Auth:AuthNone,Mutating:true,NewPayload:func()any{return &MarketingUnsubscribePayload{}},ValidatePayload:validateMarketingUnsubscribe,ResolveScope:installationScope},
		{Name:"marketing.subscriber.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingSubscriberPagePayload{}},ValidatePayload:validateMarketingSubscriberPage,ResolveScope:mailListScope},
		{Name:"marketing.subscriber.get",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"marketing.subscriber.create",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingSubscriberPayload{}},ValidatePayload:validateMarketingSubscriberCreate,ResolveScope:tenantScope},
		{Name:"marketing.subscriber.update",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingSubscriberPayload{}},ValidatePayload:validateMarketingSubscriber,ResolveScope:marketingCampaignScope},
		{Name:"marketing.subscriber.archive",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.subscriber.restore",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.subscriber.verify",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingVerificationPayload{}},ValidatePayload:validateMarketingVerification,ResolveScope:marketingCampaignScope},
		{Name:"marketing.subscriber.delete",Permission:permission,Assurance:identity.AssurancePhishingResistant,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.list.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingStatePagePayload{}},ValidatePayload:validateMarketingPage,ResolveScope:mailListScope},
		{Name:"marketing.list.get",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"marketing.list.create",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingListPayload{}},ValidatePayload:validateMarketingList,ResolveScope:mailCreateScope},
		{Name:"marketing.list.update",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingListPayload{}},ValidatePayload:validateMarketingList,ResolveScope:marketingResourceScope},
		{Name:"marketing.list.delete",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingResourceScope},
		{Name:"marketing.template.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingStatePagePayload{}},ValidatePayload:validateMarketingPage,ResolveScope:mailListScope},
		{Name:"marketing.template.get",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"marketing.template.create",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingTemplatePayload{}},ValidatePayload:validateMarketingTemplateCreate,ResolveScope:tenantScope},
		{Name:"marketing.template.update",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingTemplatePayload{}},ValidatePayload:validateMarketingTemplate,ResolveScope:marketingCampaignScope},
		{Name:"marketing.template.approve",Permission:permission,Assurance:identity.AssurancePhishingResistant,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.template.archive",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingStatePagePayload{}},ValidatePayload:validateMarketingPage,ResolveScope:mailListScope},
		{Name:"marketing.campaign.get",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"marketing.campaign.snapshot.get",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"marketing.campaign.create",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingCampaignPayload{}},ValidatePayload:validateMarketingCampaignCreate,ResolveScope:tenantScope},
		{Name:"marketing.campaign.update",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingCampaignPayload{}},ValidatePayload:validateMarketingCampaign,ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.delete",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.approve",Permission:permission,Assurance:identity.AssurancePhishingResistant,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.schedule",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.start",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.pause",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.cancel",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.attempt.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingAttemptPagePayload{}},ValidatePayload:validateMarketingAttemptPage,ResolveScope:marketingAttemptScope},
		{Name:"marketing.attempt.get",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"marketing.attempt.send",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingSendPayload{}},ValidatePayload:validateMarketingSend,ResolveScope:mailCreateScope},
		{Name:"marketing.consent.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingStatePagePayload{}},ValidatePayload:validateMarketingPage,ResolveScope:mailListScope},
		{Name:"marketing.consent.current",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingAddressPayload{}},ValidatePayload:validateMarketingAddress,ResolveScope:mailListScope},
		{Name:"marketing.consent.record",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingConsentPayload{}},ValidatePayload:validateMarketingConsent,ResolveScope:mailCreateScope},
		{Name:"marketing.suppression.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingStatePagePayload{}},ValidatePayload:validateMarketingPage,ResolveScope:mailListScope},
		{Name:"marketing.suppression.current",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingAddressPayload{}},ValidatePayload:validateMarketingAddress,ResolveScope:mailListScope},
		{Name:"marketing.suppression.record",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingConsentPayload{}},ValidatePayload:validateMarketingSuppression,ResolveScope:mailCreateScope},
	}
	for _,definition:=range definitions{if err:=register(registry,definition);err!=nil{return err}}
	return nil
}

func validateMarketingPage(value any)error{payload:=value.(*MarketingStatePagePayload);if payload.Limit>500||len(payload.Cursor)>1024{return invalid("marketing page")};return nil}
func validateMarketingUnsubscribe(value any)error{token:=value.(*MarketingUnsubscribePayload).Token;if len(token)<32||len(token)>4096||strings.ContainsAny(token,"\x00\r\n\t "){return invalid("unsubscribe token")};return nil}
func validateMarketingSubscriberCreate(value any)error{return validateMarketingSubscriberPayload(value.(*MarketingSubscriberPayload),true)}
func validateMarketingSubscriber(value any)error{return validateMarketingSubscriberPayload(value.(*MarketingSubscriberPayload),false)}
func validateMarketingSubscriberPayload(payload *MarketingSubscriberPayload,allowGeneratedID bool)error{if (!allowGeneratedID||payload.ID!="")&&!safeMailOpaque(string(payload.ID))||!safeMailAddress(payload.Address)||len(payload.Name)>256||strings.ContainsAny(payload.Name,"\x00\r\n"){return invalid("marketing subscriber")};if _,err:=marketingSubscriberTags(payload.Tags);err!=nil{return err};return nil}
func validateMarketingSubscriberPage(value any)error{payload:=value.(*MarketingSubscriberPagePayload);if payload.State!=""&&payload.State!=mail.SubscriberActive&&payload.State!=mail.SubscriberArchived||payload.Limit>500||len(payload.Cursor)>1024{return invalid("marketing subscriber page")};return nil}
func validateMarketingVerification(value any)error{payload:=value.(*MarketingVerificationPayload);switch payload.State{case mail.VerificationVerified,mail.VerificationInvalid,mail.VerificationRisky,mail.VerificationUnknown:default:return invalid("marketing verification state")};if !safeMailOpaque(payload.EvidenceRef){return invalid("marketing verification evidence")};return nil}
func validateMarketingList(value any)error{list:=value.(*MarketingListPayload).List;if !safeMailOpaque(string(list.ID))||strings.TrimSpace(list.Name)==""||len(list.Name)>256||strings.ContainsAny(list.Name,"\x00\r\n")||len(list.Contacts)>100000{return invalid("marketing list")};seen:=map[mail.ContactID]bool{};for _,contact:=range list.Contacts{if !safeMailOpaque(string(contact))||seen[contact]{return invalid("marketing list contact")};seen[contact]=true};return nil}
func validateMarketingTemplateCreate(value any)error{return validateMarketingTemplatePayload(value.(*MarketingTemplatePayload),true)}
func validateMarketingTemplate(value any)error{return validateMarketingTemplatePayload(value.(*MarketingTemplatePayload),false)}
func validateMarketingTemplatePayload(payload *MarketingTemplatePayload,allowGeneratedID bool)error{nested:=payload.Template.ID!=""||payload.Template.Name!=""||payload.Template.Text!=""||payload.Template.State!=""||payload.Template.Generation!=0||!payload.Template.UpdatedAt.IsZero();flat:=payload.Name!=""||payload.Text!="";if nested&&flat{return invalid("marketing template shape")};if flat{payload.Template=mail.CampaignTemplate{Name:payload.Name,Text:payload.Text}};template:=payload.Template;if ((!allowGeneratedID&&!flat)||template.ID!="")&&!safeMailOpaque(string(template.ID))||strings.TrimSpace(template.Name)==""||len(template.Name)>256||strings.ContainsAny(template.Name,"\x00\r\n")||template.Text==""||len(template.Text)>8<<20||strings.ContainsRune(template.Text,'\x00'){return invalid("marketing template")};return nil}
func validateMarketingCampaignCreate(value any)error{return normalizeMarketingCampaign(value.(*MarketingCampaignPayload),true)}
func validateMarketingCampaign(value any)error{return normalizeMarketingCampaign(value.(*MarketingCampaignPayload),false)}
func normalizeMarketingCampaign(payload *MarketingCampaignPayload,allowGeneratedID bool)error{nested:=payload.Campaign.ID!=""||payload.Campaign.List!=""||payload.Campaign.Subject!=""||payload.Campaign.TemplateRef!=""||payload.Campaign.FromMailbox!=""||payload.Campaign.ReplyTo!=""||payload.Campaign.Schedule!=""||payload.Campaign.SnapshotRef!=""||payload.Campaign.RecipientCount!=0||payload.Campaign.ApprovedAt!=nil||payload.Campaign.ApprovedBy!=""||payload.Campaign.State!=""||payload.Campaign.Generation!=0;flat:=payload.ListID!=""||payload.Subject!=""||payload.TemplateRef!=""||payload.FromMailbox!=""||payload.ReplyTo!=""||payload.Schedule!="";if nested&&flat{return invalid("marketing campaign shape")};if flat{payload.Campaign=mail.Campaign{List:payload.ListID,Subject:payload.Subject,TemplateRef:payload.TemplateRef,FromMailbox:payload.FromMailbox,ReplyTo:payload.ReplyTo,Schedule:payload.Schedule}};campaign:=payload.Campaign;normalizedSchedule,scheduleErr:=mail.NormalizeCampaignSchedule(campaign.Schedule);if scheduleErr!=nil{return invalid("marketing campaign schedule")};campaign.Schedule=normalizedSchedule;payload.Campaign=campaign;if ((!allowGeneratedID&&!flat)||campaign.ID!="")&&!safeMailOpaque(string(campaign.ID))||!safeMailOpaque(string(campaign.List))||strings.TrimSpace(campaign.Subject)==""||len(campaign.Subject)>998||strings.ContainsAny(campaign.Subject,"\x00\r\n")||!safeMailOpaque(campaign.TemplateRef)||!safeMailOpaque(string(campaign.FromMailbox))||campaign.ReplyTo!=""&&!safeMailAddress(campaign.ReplyTo){return invalid("marketing campaign")};return nil}
func validateMarketingConsent(value any)error{return validateMarketingEvent(value.(*MarketingConsentPayload).Event,mail.Consented)}
func validateMarketingSuppression(value any)error{return validateMarketingEvent(value.(*MarketingConsentPayload).Event,mail.Suppressed)}
func validateMarketingEvent(event mail.ConsentEvent,state mail.ConsentState)error{now:=time.Now().UTC();if !safeMailOpaque(event.ID)||!safeMailOpaque(string(event.ContactID))||!safeMailAddress(event.Address)||event.State!=state||!safeMailOpaque(event.EvidenceRef)||event.At.Before(now.Add(-10*365*24*time.Hour))||event.At.After(now.Add(5*time.Minute)){return invalid("marketing consent event")};if state==mail.Consented{switch event.ConsentReason{case mail.ConsentOptIn,mail.ConsentResubscribe,mail.ConsentImport:default:return invalid("marketing consent reason")};if event.SuppressionReason!=""{return invalid("marketing consent state")}}else{switch event.SuppressionReason{case mail.SuppressionUnsubscribe,mail.SuppressionComplaint,mail.SuppressionGlobalDNC,mail.SuppressionHardBounce,mail.SuppressionTransient,mail.SuppressionAdministrative:default:return invalid("marketing suppression reason")};if event.ConsentReason!=""{return invalid("marketing suppression state")}};return nil}
func validateMarketingAddress(value any)error{if !safeMailAddress(value.(*MarketingAddressPayload).Address){return invalid("marketing address")};return nil}
func validateMarketingAttemptPage(value any)error{payload:=value.(*MarketingAttemptPagePayload);if payload.CampaignID!=""&&!safeMailOpaque(string(payload.CampaignID))||payload.Limit>500||len(payload.Cursor)>1024{return invalid("marketing attempts")};return nil}
func validateMarketingSend(value any)error{payload:=value.(*MarketingSendPayload);if !safeMailOpaque(string(payload.CampaignID))||!safeMailOpaque(string(payload.ContactID)){return invalid("marketing attempt")};return nil}
func marketingResourceScope(request RequestEnvelope,value any)(identity.Scope,error){if !safeMailOpaque(request.ResourceID)||request.ExpectedGeneration!=0{return identity.Scope{},invalid("marketing resource scope")};return tenantScope(request,value)}
func marketingCampaignScope(request RequestEnvelope,value any)(identity.Scope,error){if !safeMailOpaque(request.ResourceID)||request.ExpectedGeneration==0{return identity.Scope{},invalid("marketing campaign generation")};return tenantScope(request,value)}
func marketingAttemptScope(request RequestEnvelope,value any)(identity.Scope,error){payload:=value.(*MarketingAttemptPagePayload);resource:=request.ResourceID;if resource==""{resource=string(payload.CampaignID)};if !safeMailOpaque(resource)||request.ExpectedGeneration!=0{return identity.Scope{},invalid("marketing campaign scope")};if payload.CampaignID!=""&&string(payload.CampaignID)!=resource{return identity.Scope{},invalid("marketing campaign identity")};return tenantScope(request,value)}

func bindMarketing(registry *Registry,services DomainServices)error{
	if services.Unsubscribe!=nil{if err:=registry.Bind("marketing.unsubscribe",func(ctx context.Context,_ Invocation,value any)(OperationResult,error){event,err:=services.Unsubscribe.Honor(ctx,value.(*MarketingUnsubscribePayload).Token);value.(*MarketingUnsubscribePayload).Token="";if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]any{"status":"unsubscribed","at":event.At}},nil});err!=nil{return err}}
	if services.Marketing!=nil{
		if err:=registry.Bind("marketing.subscriber.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MarketingSubscriberPagePayload);items,next,err:=services.Marketing.Subscribers(ctx,inv.Request.TenantID,page.State,int(page.Limit),page.Cursor);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:MarketingSubscriberPage{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.subscriber.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){item,found,err:=services.Marketing.Subscriber(ctx,inv.Request.TenantID,mail.ContactID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};return OperationResult{Status:http.StatusOK,Value:item,Generation:item.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.subscriber.create",marketingSubscriberWriter(services.Marketing,true));err!=nil{return err}
		if err:=registry.Bind("marketing.subscriber.update",marketingSubscriberWriter(services.Marketing,false));err!=nil{return err}
		for operation,target:=range map[string]mail.SubscriberState{"marketing.subscriber.archive":mail.SubscriberArchived,"marketing.subscriber.restore":mail.SubscriberActive}{operation,target:=operation,target;if err:=registry.Bind(operation,func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){updated,err:=services.Marketing.SetSubscriberState(ctx,inv.Request.TenantID,mail.ContactID(inv.Request.ResourceID),inv.Request.ExpectedGeneration,target);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:updated,Generation:updated.Generation},nil});err!=nil{return err}}
		if err:=registry.Bind("marketing.subscriber.verify",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*MarketingVerificationPayload);updated,err:=services.Marketing.RecordSubscriberVerification(ctx,inv.Request.TenantID,mail.ContactID(inv.Request.ResourceID),inv.Request.ExpectedGeneration,payload.State,payload.EvidenceRef);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:updated,Generation:updated.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.subscriber.delete",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){if err:=services.Marketing.DeleteSubscriberGeneration(ctx,inv.Request.TenantID,mail.ContactID(inv.Request.ResourceID),inv.Request.ExpectedGeneration);err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"deleted"}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.list.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MarketingStatePagePayload);items,next,err:=services.Marketing.Lists(ctx,inv.Request.TenantID,int(page.Limit),page.Cursor);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:MarketingListPage{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.list.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){item,found,err:=services.Marketing.ListByID(ctx,inv.Request.TenantID,mail.ListID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};return OperationResult{Status:http.StatusOK,Value:item},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.list.create",marketingListWriter(services.Marketing,true));err!=nil{return err}
		if err:=registry.Bind("marketing.list.update",marketingListWriter(services.Marketing,false));err!=nil{return err}
		if err:=registry.Bind("marketing.list.delete",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){if err:=services.Marketing.DeleteList(ctx,inv.Request.TenantID,mail.ListID(inv.Request.ResourceID));err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"deleted"}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.template.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MarketingStatePagePayload);items,next,err:=services.Marketing.Templates(ctx,inv.Request.TenantID,int(page.Limit),page.Cursor);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:MarketingTemplatePage{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.template.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){item,found,err:=services.Marketing.LatestTemplate(ctx,inv.Request.TenantID,mail.CampaignTemplateID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};return OperationResult{Status:http.StatusOK,Value:item,Generation:item.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.template.create",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){template:=value.(*MarketingTemplatePayload).Template;if template.ID==""{template.ID=mail.CampaignTemplateID(effectID(inv))};if inv.Request.ResourceID!=""&&string(template.ID)!=inv.Request.ResourceID{return OperationResult{},invalid("marketing template identity")};created,err:=services.Marketing.CreateTemplate(ctx,inv.Request.TenantID,template);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusCreated,Value:created,Generation:created.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.template.update",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){template:=value.(*MarketingTemplatePayload).Template;if template.ID==""{template.ID=mail.CampaignTemplateID(inv.Request.ResourceID)};if string(template.ID)!=inv.Request.ResourceID{return OperationResult{},invalid("marketing template identity")};updated,err:=services.Marketing.ReviseTemplate(ctx,inv.Request.TenantID,template,inv.Request.ExpectedGeneration);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:updated,Generation:updated.Generation},nil});err!=nil{return err}
		for operation,target:=range map[string]string{"marketing.template.approve":"approved","marketing.template.archive":"archived"}{operation,target:=operation,target;if err:=registry.Bind(operation,func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){updated,err:=services.Marketing.SetTemplateState(ctx,inv.Request.TenantID,mail.CampaignTemplateID(inv.Request.ResourceID),inv.Request.ExpectedGeneration,target);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]any{"template":updated,"reference":mail.CampaignTemplateReference(updated)},Generation:updated.Generation},nil});err!=nil{return err}}
		if err:=registry.Bind("marketing.campaign.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MarketingStatePagePayload);items,next,err:=services.Marketing.Campaigns(ctx,inv.Request.TenantID,int(page.Limit),page.Cursor);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:MarketingCampaignPage{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.campaign.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){item,found,err:=services.Marketing.Campaign(ctx,inv.Request.TenantID,mail.CampaignID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};return OperationResult{Status:http.StatusOK,Value:item},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.campaign.snapshot.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){campaign,found,err:=services.Marketing.Campaign(ctx,inv.Request.TenantID,mail.CampaignID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};snapshot,found,err:=services.Marketing.CampaignSnapshot(ctx,inv.Request.TenantID,campaign);if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};return OperationResult{Status:http.StatusOK,Value:snapshot},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.campaign.create",marketingCampaignWriter(services.Marketing,true));err!=nil{return err}
		if err:=registry.Bind("marketing.campaign.update",marketingCampaignWriter(services.Marketing,false));err!=nil{return err}
		if err:=registry.Bind("marketing.campaign.delete",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){if err:=services.Marketing.DeleteCampaignGeneration(ctx,inv.Request.TenantID,mail.CampaignID(inv.Request.ResourceID),inv.Request.ExpectedGeneration);err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"deleted"}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.campaign.approve",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){campaign,snapshot,err:=services.Marketing.ApproveCampaign(ctx,inv.Request.TenantID,mail.CampaignID(inv.Request.ResourceID),inv.Request.ExpectedGeneration,inv.Actor.PrincipalID.String());if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]any{"campaign":campaign,"snapshot":snapshot},Generation:campaign.Generation},nil});err!=nil{return err}
		for operation,target:=range map[string]string{"marketing.campaign.schedule":"scheduled","marketing.campaign.start":"running","marketing.campaign.pause":"paused","marketing.campaign.cancel":"cancelled"}{operation,target:=operation,target;if err:=registry.Bind(operation,marketingCampaignTransition(services.Marketing,target));err!=nil{return err}}
		if err:=registry.Bind("marketing.attempt.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MarketingAttemptPagePayload);campaign:=page.CampaignID;if campaign==""{campaign=mail.CampaignID(inv.Request.ResourceID)};items,next,err:=services.Marketing.Attempts(ctx,inv.Request.TenantID,campaign,int(page.Limit),page.Cursor);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:MarketingAttemptPage{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.attempt.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){attempt,found,err:=services.Marketing.Attempt(ctx,inv.Request.TenantID,mail.AttemptID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};return OperationResult{Status:http.StatusOK,Value:attempt},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.consent.list",marketingConsentList(services.Marketing,mail.Consented));err!=nil{return err}
		if err:=registry.Bind("marketing.suppression.list",marketingConsentList(services.Marketing,mail.Suppressed));err!=nil{return err}
		if err:=registry.Bind("marketing.consent.current",marketingCurrentConsent(services.Marketing,false));err!=nil{return err}
		if err:=registry.Bind("marketing.suppression.current",marketingCurrentConsent(services.Marketing,true));err!=nil{return err}
		if err:=registry.Bind("marketing.consent.record",marketingConsentWriter(services.Marketing,mail.Consented));err!=nil{return err}
		if err:=registry.Bind("marketing.suppression.record",marketingConsentWriter(services.Marketing,mail.Suppressed));err!=nil{return err}
	}
	if services.Campaigns!=nil{return registry.Bind("marketing.attempt.send",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*MarketingSendPayload);campaign,found,err:=services.Campaigns.Store.Campaign(ctx,inv.Request.TenantID,payload.CampaignID);if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};recipient,found,err:=services.Campaigns.Store.CampaignRecipient(ctx,inv.Request.TenantID,campaign,payload.ContactID);if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrForbidden};sum:=sha256.Sum256([]byte(inv.Request.TenantID+"\x00"+inv.Actor.PrincipalID.String()+"\x00"+inv.IdempotencyKey));attempt:=mail.CampaignAttempt{ID:mail.AttemptID(inv.Request.ResourceID),TenantID:inv.Request.TenantID,CampaignID:campaign.ID,ContactID:recipient.ContactID,Address:recipient.Address,IdempotencyKey:"api_"+hex.EncodeToString(sum[:])};result,err:=services.Campaigns.SendOne(ctx,inv.Request.TenantID,campaign,recipient,attempt);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusAccepted,Value:result},nil})}
	return nil
}

func marketingListWriter(store *mail.MarketingStore,create bool)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){list:=value.(*MarketingListPayload).List;if string(list.ID)!=inv.Request.ResourceID{return OperationResult{},invalid("marketing list identity")};_,found,err:=store.ListByID(ctx,inv.Request.TenantID,list.ID);if err!=nil{return OperationResult{},mapMailError(err)};if create&&found||!create&&!found{return OperationResult{},ErrConflict};if err=store.PutList(ctx,inv.Request.TenantID,list);err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:list},nil}}
func marketingSubscriberWriter(store *mail.MarketingStore,create bool)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*MarketingSubscriberPayload);id:=payload.ID;if create&&id==""{id=mail.ContactID(effectID(inv))};if !create&&id==""{id=mail.ContactID(inv.Request.ResourceID)};if inv.Request.ResourceID!=""&&string(id)!=inv.Request.ResourceID{return OperationResult{},invalid("marketing subscriber identity")};tags,err:=marketingSubscriberTags(payload.Tags);if err!=nil{return OperationResult{},err};subscriber:=mail.Subscriber{ID:id,Address:payload.Address,Name:payload.Name,Tags:tags};var updated mail.Subscriber;if create{updated,err=store.CreateSubscriber(ctx,inv.Request.TenantID,subscriber)}else{updated,err=store.ReviseSubscriber(ctx,inv.Request.TenantID,subscriber,inv.Request.ExpectedGeneration)};if err!=nil{return OperationResult{},mapMailError(err)};status:=http.StatusOK;if create{status=http.StatusCreated};return OperationResult{Status:status,Value:updated,Generation:updated.Generation},nil}}
func marketingCampaignWriter(store *mail.MarketingStore,create bool)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){campaign:=value.(*MarketingCampaignPayload).Campaign;if create{if campaign.ID==""{campaign.ID=mail.CampaignID(effectID(inv))};if inv.Request.ResourceID!=""&&string(campaign.ID)!=inv.Request.ResourceID{return OperationResult{},invalid("marketing campaign identity")};campaign.State="draft";campaign.Generation=1;campaign.SnapshotRef="";campaign.RecipientCount=0;campaign.ApprovedAt=nil;campaign.ApprovedBy=""}else{if campaign.ID==""{campaign.ID=mail.CampaignID(inv.Request.ResourceID)};if string(campaign.ID)!=inv.Request.ResourceID{return OperationResult{},invalid("marketing campaign identity")};prior,found,err:=store.Campaign(ctx,inv.Request.TenantID,campaign.ID);if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};if prior.Generation!=inv.Request.ExpectedGeneration||prior.State!="draft"{return OperationResult{},ErrConflict};campaign.State=prior.State;campaign.Generation=prior.Generation+1;campaign.SnapshotRef="";campaign.RecipientCount=0;campaign.ApprovedAt=nil;campaign.ApprovedBy=""};if _,listFound,loadErr:=store.ListByID(ctx,inv.Request.TenantID,campaign.List);loadErr!=nil{return OperationResult{},mapMailError(loadErr)}else if !listFound{return OperationResult{},ErrNotFound};if _,templateFound,templateErr:=store.ApprovedTemplateVersion(ctx,inv.Request.TenantID,campaign.TemplateRef);templateErr!=nil{return OperationResult{},mapMailError(templateErr)}else if !templateFound{return OperationResult{},ErrNotFound};var err error;if create{err=store.CreateCampaign(ctx,inv.Request.TenantID,campaign)}else{err=store.AdvanceCampaign(ctx,inv.Request.TenantID,campaign,inv.Request.ExpectedGeneration)};if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:campaign,Generation:campaign.Generation},nil}}
func marketingCampaignTransition(store *mail.MarketingStore,target string)OperationHandler{return func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){campaign,found,err:=store.Campaign(ctx,inv.Request.TenantID,mail.CampaignID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};if campaign.Generation!=inv.Request.ExpectedGeneration{return OperationResult{},ErrConflict};allowed:=false;switch target{case"scheduled":allowed=campaign.State=="approved";case"running":allowed=campaign.State=="approved"||campaign.State=="scheduled"||campaign.State=="paused";case"paused":allowed=campaign.State=="running";case"cancelled":allowed=campaign.State=="draft"||campaign.State=="approved"||campaign.State=="scheduled"||campaign.State=="running"||campaign.State=="paused"};if !allowed{return OperationResult{},ErrConflict};if target=="running"||target=="scheduled"{if _,snapshotFound,loadErr:=store.CampaignSnapshot(ctx,inv.Request.TenantID,campaign);loadErr!=nil{return OperationResult{},mapMailError(loadErr)}else if !snapshotFound{return OperationResult{},ErrNotFound};if _,templateFound,templateErr:=store.ApprovedTemplateVersion(ctx,inv.Request.TenantID,campaign.TemplateRef);templateErr!=nil{return OperationResult{},mapMailError(templateErr)}else if !templateFound{return OperationResult{},ErrNotFound}};if target=="scheduled"{when,scheduleErr:=mail.CampaignScheduleTime(campaign.Schedule);if scheduleErr!=nil||!when.After(time.Now().UTC()){return OperationResult{},ErrConflict}};campaign.State=target;campaign.Generation++;if err=store.AdvanceCampaign(ctx,inv.Request.TenantID,campaign,inv.Request.ExpectedGeneration);err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:campaign,Generation:campaign.Generation},nil}}
func marketingConsentList(store *mail.MarketingStore,state mail.ConsentState)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MarketingStatePagePayload);items,next,err:=store.ConsentEvents(ctx,inv.Request.TenantID,state,int(page.Limit),page.Cursor);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:MarketingConsentPage{Items:items,NextCursor:next}},nil}}
func marketingCurrentConsent(store *mail.MarketingStore,suppressionOnly bool)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){event,found,err:=store.CurrentConsent(ctx,inv.Request.TenantID,value.(*MarketingAddressPayload).Address);if err!=nil{return OperationResult{},mapMailError(err)};if suppressionOnly&&found&&event.State!=mail.Suppressed{found=false;event=mail.ConsentEvent{}};return OperationResult{Status:http.StatusOK,Value:MarketingConsentCurrent{Found:found,Event:event}},nil}}
func marketingConsentWriter(store *mail.MarketingStore,state mail.ConsentState)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){event:=value.(*MarketingConsentPayload).Event;if event.ID!=inv.Request.ResourceID{return OperationResult{},invalid("marketing event identity")};event.TenantID=inv.Request.TenantID;event.State=state;if err:=store.RecordConsent(ctx,event);err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusCreated,Value:event},nil}}
func marketingListContains(list mail.List,contact mail.ContactID)bool{for _,candidate:=range list.Contacts{if candidate==contact{return true}};return false}
func marketingSubscriberTags(value string)([]string,error){if strings.TrimSpace(value)==""{return nil,nil};parts:=strings.FieldsFunc(value,func(r rune)bool{return r==','||r=='\n'||r=='\r'});if len(parts)>64{return nil,invalid("marketing subscriber tags")};tags:=make([]string,0,len(parts));seen:=map[string]struct{}{};for _,part:=range parts{tag:=strings.ToLower(strings.TrimSpace(part));if !safeMailOpaque(tag){return nil,invalid("marketing subscriber tag")};if _,found:=seen[tag];found{continue};seen[tag]=struct{}{};tags=append(tags,tag)};return tags,nil}
