package apiserver

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"net/http"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/identity"
	"github.com/aonsyed/cyberpanel/platform/internal/mail"
)

type MarketingListPayload struct{List mail.List `json:"list"`}
type MarketingCampaignPayload struct{Campaign mail.Campaign `json:"campaign"`;ListID mail.ListID `json:"list_id,omitempty"`;Subject string `json:"subject,omitempty"`;TemplateRef string `json:"template_ref,omitempty"`;Schedule string `json:"schedule,omitempty"`}
type MarketingConsentPayload struct{Event mail.ConsentEvent `json:"event"`}
type MarketingAddressPayload struct{Address mail.Address `json:"address"`}
type MarketingStatePagePayload struct{Limit uint16 `json:"limit"`;Cursor string `json:"cursor,omitempty"`}
type MarketingAttemptPagePayload struct{CampaignID mail.CampaignID `json:"campaign_id"`;Limit uint16 `json:"limit"`;Cursor string `json:"cursor,omitempty"`}
type MarketingSendPayload struct{CampaignID mail.CampaignID `json:"campaign_id"`;Contact mail.MarketingContact `json:"contact"`}
type MarketingListPage struct{Items []mail.List `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type MarketingCampaignPage struct{Items []mail.Campaign `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type MarketingAttemptPage struct{Items []mail.CampaignAttempt `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type MarketingConsentPage struct{Items []mail.ConsentEvent `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type MarketingConsentCurrent struct{Found bool `json:"found"`;Event mail.ConsentEvent `json:"event,omitempty"`}

func registerMarketingContracts(registry *Registry)error{
	permission:=identity.MustPermission("mail:manage")
	definitions:=[]Operation{
		{Name:"marketing.list.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingStatePagePayload{}},ValidatePayload:validateMarketingPage,ResolveScope:mailListScope},
		{Name:"marketing.list.get",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"marketing.list.create",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingListPayload{}},ValidatePayload:validateMarketingList,ResolveScope:mailCreateScope},
		{Name:"marketing.list.update",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingListPayload{}},ValidatePayload:validateMarketingList,ResolveScope:marketingResourceScope},
		{Name:"marketing.list.delete",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingResourceScope},
		{Name:"marketing.campaign.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingStatePagePayload{}},ValidatePayload:validateMarketingPage,ResolveScope:mailListScope},
		{Name:"marketing.campaign.get",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"marketing.campaign.create",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingCampaignPayload{}},ValidatePayload:validateMarketingCampaignCreate,ResolveScope:tenantScope},
		{Name:"marketing.campaign.update",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingCampaignPayload{}},ValidatePayload:validateMarketingCampaign,ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.delete",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.start",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.pause",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.cancel",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.attempt.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingAttemptPagePayload{}},ValidatePayload:validateMarketingAttemptPage,ResolveScope:marketingAttemptScope},
		{Name:"marketing.attempt.get",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"marketing.attempt.send",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingSendPayload{}},ValidatePayload:validateMarketingSend,ResolveScope:mailCreateScope},
		{Name:"marketing.consent.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingStatePagePayload{}},ValidatePayload:validateMarketingPage,ResolveScope:mailListScope},
		{Name:"marketing.consent.current",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingAddressPayload{}},ValidatePayload:validateMarketingAddress,ResolveScope:mailListScope},
		{Name:"marketing.consent.record",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingConsentPayload{}},ValidatePayload:validateMarketingConsent,ResolveScope:mailCreateScope},
		{Name:"marketing.suppression.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingStatePagePayload{}},ValidatePayload:validateMarketingPage,ResolveScope:mailListScope},
		{Name:"marketing.suppression.current",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingAddressPayload{}},ValidatePayload:validateMarketingAddress,ResolveScope:mailListScope},
		{Name:"marketing.suppression.record",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingConsentPayload{}},ValidatePayload:validateMarketingSuppression,ResolveScope:mailCreateScope},
	}
	for _,definition:=range definitions{if err:=register(registry,definition);err!=nil{return err}}
	return nil
}

func validateMarketingPage(value any)error{payload:=value.(*MarketingStatePagePayload);if payload.Limit>500||len(payload.Cursor)>1024{return invalid("marketing page")};return nil}
func validateMarketingList(value any)error{list:=value.(*MarketingListPayload).List;if !safeMailOpaque(string(list.ID))||strings.TrimSpace(list.Name)==""||len(list.Name)>256||strings.ContainsAny(list.Name,"\x00\r\n")||len(list.Contacts)>100000{return invalid("marketing list")};seen:=map[mail.ContactID]bool{};for _,contact:=range list.Contacts{if !safeMailOpaque(string(contact))||seen[contact]{return invalid("marketing list contact")};seen[contact]=true};return nil}
func validateMarketingCampaignCreate(value any)error{return normalizeMarketingCampaign(value.(*MarketingCampaignPayload),true)}
func validateMarketingCampaign(value any)error{return normalizeMarketingCampaign(value.(*MarketingCampaignPayload),false)}
func normalizeMarketingCampaign(payload *MarketingCampaignPayload,allowGeneratedID bool)error{nested:=payload.Campaign.ID!=""||payload.Campaign.List!=""||payload.Campaign.Subject!=""||payload.Campaign.TemplateRef!=""||payload.Campaign.Schedule!=""||payload.Campaign.State!=""||payload.Campaign.Generation!=0;flat:=payload.ListID!=""||payload.Subject!=""||payload.TemplateRef!=""||payload.Schedule!="";if nested&&flat{return invalid("marketing campaign shape")};if flat{payload.Campaign=mail.Campaign{List:payload.ListID,Subject:payload.Subject,TemplateRef:payload.TemplateRef,Schedule:payload.Schedule}};campaign:=payload.Campaign;if (!allowGeneratedID||campaign.ID!="")&&!safeMailOpaque(string(campaign.ID))||!safeMailOpaque(string(campaign.List))||strings.TrimSpace(campaign.Subject)==""||len(campaign.Subject)>998||strings.ContainsAny(campaign.Subject,"\x00\r\n")||!safeMailOpaque(campaign.TemplateRef)||len(campaign.Schedule)>128||strings.ContainsAny(campaign.Schedule,"\x00\r\n"){return invalid("marketing campaign")};return nil}
func validateMarketingConsent(value any)error{return validateMarketingEvent(value.(*MarketingConsentPayload).Event,mail.Consented)}
func validateMarketingSuppression(value any)error{return validateMarketingEvent(value.(*MarketingConsentPayload).Event,mail.Suppressed)}
func validateMarketingEvent(event mail.ConsentEvent,state mail.ConsentState)error{now:=time.Now().UTC();if !safeMailOpaque(event.ID)||!safeMailOpaque(string(event.ContactID))||!safeMailAddress(event.Address)||event.State!=state||!safeMailOpaque(event.EvidenceRef)||event.At.Before(now.Add(-10*365*24*time.Hour))||event.At.After(now.Add(5*time.Minute)){return invalid("marketing consent event")};if state==mail.Consented{switch event.ConsentReason{case mail.ConsentOptIn,mail.ConsentResubscribe,mail.ConsentImport:default:return invalid("marketing consent reason")};if event.SuppressionReason!=""{return invalid("marketing consent state")}}else{switch event.SuppressionReason{case mail.SuppressionUnsubscribe,mail.SuppressionComplaint,mail.SuppressionGlobalDNC,mail.SuppressionHardBounce,mail.SuppressionTransient,mail.SuppressionAdministrative:default:return invalid("marketing suppression reason")};if event.ConsentReason!=""{return invalid("marketing suppression state")}};return nil}
func validateMarketingAddress(value any)error{if !safeMailAddress(value.(*MarketingAddressPayload).Address){return invalid("marketing address")};return nil}
func validateMarketingAttemptPage(value any)error{payload:=value.(*MarketingAttemptPagePayload);if payload.CampaignID!=""&&!safeMailOpaque(string(payload.CampaignID))||payload.Limit>500||len(payload.Cursor)>1024{return invalid("marketing attempts")};return nil}
func validateMarketingSend(value any)error{payload:=value.(*MarketingSendPayload);if !safeMailOpaque(string(payload.CampaignID))||!safeMailOpaque(string(payload.Contact.ID))||!safeMailAddress(payload.Contact.Address)||payload.Contact.At.IsZero()||payload.Contact.At.After(time.Now().Add(5*time.Minute)){return invalid("marketing attempt")};return nil}
func marketingResourceScope(request RequestEnvelope,value any)(identity.Scope,error){if !safeMailOpaque(request.ResourceID)||request.ExpectedGeneration!=0{return identity.Scope{},invalid("marketing resource scope")};return tenantScope(request,value)}
func marketingCampaignScope(request RequestEnvelope,value any)(identity.Scope,error){if !safeMailOpaque(request.ResourceID)||request.ExpectedGeneration==0{return identity.Scope{},invalid("marketing campaign generation")};return tenantScope(request,value)}
func marketingAttemptScope(request RequestEnvelope,value any)(identity.Scope,error){payload:=value.(*MarketingAttemptPagePayload);resource:=request.ResourceID;if resource==""{resource=string(payload.CampaignID)};if !safeMailOpaque(resource)||request.ExpectedGeneration!=0{return identity.Scope{},invalid("marketing campaign scope")};if payload.CampaignID!=""&&string(payload.CampaignID)!=resource{return identity.Scope{},invalid("marketing campaign identity")};return tenantScope(request,value)}

func bindMarketing(registry *Registry,services DomainServices)error{
	if services.Marketing!=nil{
		if err:=registry.Bind("marketing.list.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MarketingStatePagePayload);items,next,err:=services.Marketing.Lists(ctx,inv.Request.TenantID,int(page.Limit),page.Cursor);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:MarketingListPage{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.list.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){item,found,err:=services.Marketing.ListByID(ctx,inv.Request.TenantID,mail.ListID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};return OperationResult{Status:http.StatusOK,Value:item},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.list.create",marketingListWriter(services.Marketing,true));err!=nil{return err}
		if err:=registry.Bind("marketing.list.update",marketingListWriter(services.Marketing,false));err!=nil{return err}
		if err:=registry.Bind("marketing.list.delete",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){if err:=services.Marketing.DeleteList(ctx,inv.Request.TenantID,mail.ListID(inv.Request.ResourceID));err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"deleted"}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.campaign.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MarketingStatePagePayload);items,next,err:=services.Marketing.Campaigns(ctx,inv.Request.TenantID,int(page.Limit),page.Cursor);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:MarketingCampaignPage{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.campaign.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){item,found,err:=services.Marketing.Campaign(ctx,inv.Request.TenantID,mail.CampaignID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};return OperationResult{Status:http.StatusOK,Value:item},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.campaign.create",marketingCampaignWriter(services.Marketing,true));err!=nil{return err}
		if err:=registry.Bind("marketing.campaign.update",marketingCampaignWriter(services.Marketing,false));err!=nil{return err}
		if err:=registry.Bind("marketing.campaign.delete",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){if err:=services.Marketing.DeleteCampaignGeneration(ctx,inv.Request.TenantID,mail.CampaignID(inv.Request.ResourceID),inv.Request.ExpectedGeneration);err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"deleted"}},nil});err!=nil{return err}
		for operation,target:=range map[string]string{"marketing.campaign.start":"running","marketing.campaign.pause":"paused","marketing.campaign.cancel":"cancelled"}{operation,target:=operation,target;if err:=registry.Bind(operation,marketingCampaignTransition(services.Marketing,target));err!=nil{return err}}
		if err:=registry.Bind("marketing.attempt.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MarketingAttemptPagePayload);campaign:=page.CampaignID;if campaign==""{campaign=mail.CampaignID(inv.Request.ResourceID)};items,next,err:=services.Marketing.Attempts(ctx,inv.Request.TenantID,campaign,int(page.Limit),page.Cursor);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:MarketingAttemptPage{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.attempt.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){attempt,found,err:=services.Marketing.Attempt(ctx,inv.Request.TenantID,mail.AttemptID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};return OperationResult{Status:http.StatusOK,Value:attempt},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.consent.list",marketingConsentList(services.Marketing,mail.Consented));err!=nil{return err}
		if err:=registry.Bind("marketing.suppression.list",marketingConsentList(services.Marketing,mail.Suppressed));err!=nil{return err}
		if err:=registry.Bind("marketing.consent.current",marketingCurrentConsent(services.Marketing,false));err!=nil{return err}
		if err:=registry.Bind("marketing.suppression.current",marketingCurrentConsent(services.Marketing,true));err!=nil{return err}
		if err:=registry.Bind("marketing.consent.record",marketingConsentWriter(services.Marketing,mail.Consented));err!=nil{return err}
		if err:=registry.Bind("marketing.suppression.record",marketingConsentWriter(services.Marketing,mail.Suppressed));err!=nil{return err}
	}
	if services.Campaigns!=nil{return registry.Bind("marketing.attempt.send",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*MarketingSendPayload);campaign,found,err:=services.Campaigns.Store.Campaign(ctx,inv.Request.TenantID,payload.CampaignID);if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};list,found,err:=services.Campaigns.Store.ListByID(ctx,inv.Request.TenantID,campaign.List);if err!=nil{return OperationResult{},mapMailError(err)};if !found||!marketingListContains(list,payload.Contact.ID){return OperationResult{},ErrForbidden};sum:=sha256.Sum256([]byte(inv.Request.TenantID+"\x00"+inv.Actor.PrincipalID.String()+"\x00"+inv.IdempotencyKey));attempt:=mail.CampaignAttempt{ID:mail.AttemptID(inv.Request.ResourceID),TenantID:inv.Request.TenantID,CampaignID:campaign.ID,ContactID:payload.Contact.ID,Address:payload.Contact.Address,IdempotencyKey:"api_"+hex.EncodeToString(sum[:])};result,err:=services.Campaigns.SendOne(ctx,inv.Request.TenantID,campaign,payload.Contact,attempt);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusAccepted,Value:result},nil})}
	return nil
}

func marketingListWriter(store *mail.MarketingStore,create bool)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){list:=value.(*MarketingListPayload).List;if string(list.ID)!=inv.Request.ResourceID{return OperationResult{},invalid("marketing list identity")};_,found,err:=store.ListByID(ctx,inv.Request.TenantID,list.ID);if err!=nil{return OperationResult{},mapMailError(err)};if create&&found||!create&&!found{return OperationResult{},ErrConflict};if err=store.PutList(ctx,inv.Request.TenantID,list);err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:list},nil}}
func marketingCampaignWriter(store *mail.MarketingStore,create bool)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){campaign:=value.(*MarketingCampaignPayload).Campaign;if create{if campaign.ID==""{campaign.ID=mail.CampaignID(effectID(inv))};if inv.Request.ResourceID!=""&&string(campaign.ID)!=inv.Request.ResourceID{return OperationResult{},invalid("marketing campaign identity")};campaign.State="draft";campaign.Generation=1}else{if string(campaign.ID)!=inv.Request.ResourceID{return OperationResult{},invalid("marketing campaign identity")};prior,found,err:=store.Campaign(ctx,inv.Request.TenantID,campaign.ID);if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};if prior.Generation!=inv.Request.ExpectedGeneration{return OperationResult{},ErrConflict};campaign.State=prior.State;campaign.Generation=prior.Generation+1};if _,listFound,loadErr:=store.ListByID(ctx,inv.Request.TenantID,campaign.List);loadErr!=nil{return OperationResult{},mapMailError(loadErr)}else if !listFound{return OperationResult{},ErrNotFound};var err error;if create{err=store.CreateCampaign(ctx,inv.Request.TenantID,campaign)}else{err=store.AdvanceCampaign(ctx,inv.Request.TenantID,campaign,inv.Request.ExpectedGeneration)};if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:campaign,Generation:campaign.Generation},nil}}
func marketingCampaignTransition(store *mail.MarketingStore,target string)OperationHandler{return func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){campaign,found,err:=store.Campaign(ctx,inv.Request.TenantID,mail.CampaignID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};if campaign.Generation!=inv.Request.ExpectedGeneration{return OperationResult{},ErrConflict};allowed:=false;switch target{case"running":allowed=campaign.State=="draft"||campaign.State=="scheduled"||campaign.State=="paused";case"paused":allowed=campaign.State=="running";case"cancelled":allowed=campaign.State=="draft"||campaign.State=="scheduled"||campaign.State=="running"||campaign.State=="paused"};if !allowed{return OperationResult{},ErrConflict};campaign.State=target;campaign.Generation++;if err=store.AdvanceCampaign(ctx,inv.Request.TenantID,campaign,inv.Request.ExpectedGeneration);err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:campaign,Generation:campaign.Generation},nil}}
func marketingConsentList(store *mail.MarketingStore,state mail.ConsentState)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MarketingStatePagePayload);items,next,err:=store.ConsentEvents(ctx,inv.Request.TenantID,state,int(page.Limit),page.Cursor);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:MarketingConsentPage{Items:items,NextCursor:next}},nil}}
func marketingCurrentConsent(store *mail.MarketingStore,suppressionOnly bool)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){event,found,err:=store.CurrentConsent(ctx,inv.Request.TenantID,value.(*MarketingAddressPayload).Address);if err!=nil{return OperationResult{},mapMailError(err)};if suppressionOnly&&found&&event.State!=mail.Suppressed{found=false;event=mail.ConsentEvent{}};return OperationResult{Status:http.StatusOK,Value:MarketingConsentCurrent{Found:found,Event:event}},nil}}
func marketingConsentWriter(store *mail.MarketingStore,state mail.ConsentState)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){event:=value.(*MarketingConsentPayload).Event;if event.ID!=inv.Request.ResourceID{return OperationResult{},invalid("marketing event identity")};event.TenantID=inv.Request.TenantID;event.State=state;if err:=store.RecordConsent(ctx,event);err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusCreated,Value:event},nil}}
func marketingListContains(list mail.List,contact mail.ContactID)bool{for _,candidate:=range list.Contacts{if candidate==contact{return true}};return false}
