package apiserver

import (
	"context"
	"encoding/base64"
	"net/http"
	"net/url"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/access"
	"github.com/aonsyed/cyberpanel/platform/internal/identity"
)

type UploadBeginPayload struct{UploadID access.UploadID `json:"upload_id"`;Destination access.FileLocator `json:"destination"`;Integrity access.Integrity `json:"integrity"`;Condition access.WriteCondition `json:"condition"`;TTL time.Duration `json:"ttl"`}
type UploadChunkPayload struct{UploadID access.UploadID `json:"upload_id"`;Chunk access.UploadChunk `json:"chunk"`}
type UploadIDPayload struct{UploadID access.UploadID `json:"upload_id"`}
type DownloadIssuePayload struct{DownloadID access.DownloadID `json:"download_id"`;Source access.FileLocator `json:"source"`;TTL time.Duration `json:"ttl"`}
type DownloadIssueResult struct{ID access.DownloadID `json:"id"`;Source access.FileLocator `json:"source"`;Integrity access.Integrity `json:"integrity"`;ExpiresAt time.Time `json:"expires_at"`;DownloadURL string `json:"download_url"`}
type DownloadReadPayload struct{DownloadID access.DownloadID `json:"download_id"`;Offset int64 `json:"offset"`;Length int64 `json:"length"`}
type DownloadReadResult struct{DownloadID access.DownloadID `json:"download_id"`;Offset int64 `json:"offset"`;ContentBase64 string `json:"content_base64"`;Integrity access.Integrity `json:"integrity"`}
type DownloadIDPayload struct{DownloadID access.DownloadID `json:"download_id"`}
type TrashCreatePayload struct{EntryID access.TrashEntryID `json:"entry_id"`;Source access.FileLocator `json:"source"`;RetainFor time.Duration `json:"retain_for"`}
type TrashMovePayload struct{Source access.FileLocator `json:"source"`;RetainFor time.Duration `json:"retain_for,omitempty"`}
type TrashRestorePayload struct{EntryID access.TrashEntryID `json:"entry_id"`;Destination access.FileLocator `json:"destination"`;Condition access.WriteCondition `json:"condition"`}
type TrashPurgePayload struct{EntryID access.TrashEntryID `json:"entry_id"`;Force bool `json:"force"`}
type ArchiveCreatePayload struct{ArchiveID access.ArchiveID `json:"archive_id"`;Format access.ArchiveFormat `json:"format"`;Sources []access.FileLocator `json:"sources"`;Destination access.FileLocator `json:"destination"`}
type ArchiveExtractPayload struct{Source access.FileLocator `json:"source"`;Destination access.FileLocator `json:"destination"`;Policy access.ExtractPolicy `json:"policy"`}

func registerAccessFileContracts(registry *Registry)error{
	read:=identity.MustPermission("file:read");write:=identity.MustPermission("file:write")
	definitions:=[]Operation{
		{Name:"access.upload.begin",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &UploadBeginPayload{}},ValidatePayload:validateUploadBegin,ResolveScope:siteScope},
		{Name:"access.upload.chunk",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,MaximumBodyBytes:12<<20,NewPayload:func()any{return &UploadChunkPayload{}},ValidatePayload:validateUploadChunk,ResolveScope:siteScope},
		{Name:"access.upload.commit",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &UploadIDPayload{}},ValidatePayload:validateUploadID,ResolveScope:siteScope},
		{Name:"access.upload.abort",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &UploadIDPayload{}},ValidatePayload:validateUploadID,ResolveScope:siteScope},
		{Name:"access.download.issue",Permission:read,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &DownloadIssuePayload{}},ValidatePayload:validateDownloadIssue,ResolveScope:siteScope},
		{Name:"access.files.download.issue",Permission:read,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &DownloadIssuePayload{}},ValidatePayload:validateDownloadIssue,ResolveScope:siteScope},
		{Name:"access.download.get",Permission:read,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &DownloadIDPayload{}},ValidatePayload:validateDownloadID,ResolveScope:siteScope},
		{Name:"access.download.read",Permission:read,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &DownloadReadPayload{}},ValidatePayload:validateDownloadRead,ResolveScope:siteScope},
		{Name:"access.download.close",Permission:read,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &DownloadIDPayload{}},ValidatePayload:validateDownloadID,ResolveScope:siteScope},
		{Name:"access.trash.create",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &TrashCreatePayload{}},ValidatePayload:validateTrashCreate,ResolveScope:siteScope},
		{Name:"access.trash.move",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &TrashMovePayload{}},ValidatePayload:validateTrashMove,ResolveScope:siteScope},
		{Name:"access.file.trash",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &TrashMovePayload{}},ValidatePayload:validateTrashMove,ResolveScope:siteScope},
		{Name:"access.trash.restore",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &TrashRestorePayload{}},ValidatePayload:validateTrashRestore,ResolveScope:siteScope},
		{Name:"access.trash.purge",Permission:write,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &TrashPurgePayload{}},ValidatePayload:validateTrashPurge,ResolveScope:siteScope},
		{Name:"access.archive.create",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ArchiveCreatePayload{}},ValidatePayload:validateArchiveCreate,ResolveScope:siteScope},
		{Name:"access.archive.extract",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ArchiveExtractPayload{}},ValidatePayload:validateArchiveExtract,ResolveScope:siteScope},
	}
	for _,definition:=range definitions{if err:=register(registry,definition);err!=nil{return err}}
	return nil
}

func validateUploadBegin(value any)error{payload:=value.(*UploadBeginPayload);if !safeMailOpaque(string(payload.UploadID))||payload.Destination.Validate()!=nil||payload.Integrity.Validate()!=nil||payload.TTL<time.Minute||payload.TTL>24*time.Hour{return invalid("upload session")};return nil}
func validateUploadChunk(value any)error{payload:=value.(*UploadChunkPayload);if !safeMailOpaque(string(payload.UploadID))||payload.Chunk.Validate()!=nil{return invalid("upload chunk")};return nil}
func validateUploadID(value any)error{if !safeMailOpaque(string(value.(*UploadIDPayload).UploadID)){return invalid("upload id")};return nil}
func validateDownloadIssue(value any)error{payload:=value.(*DownloadIssuePayload);if payload.DownloadID!=""&&!safeMailOpaque(string(payload.DownloadID))||payload.Source.Validate()!=nil||payload.TTL!=0&&(payload.TTL<time.Minute||payload.TTL>time.Hour){return invalid("download lease")};return nil}
func validateDownloadRead(value any)error{payload:=value.(*DownloadReadPayload);if !safeMailOpaque(string(payload.DownloadID))||payload.Offset<0||payload.Length<=0||payload.Length>4<<20{return invalid("download range")};return nil}
func validateDownloadID(value any)error{if !safeMailOpaque(string(value.(*DownloadIDPayload).DownloadID)){return invalid("download id")};return nil}
func validateTrashCreate(value any)error{payload:=value.(*TrashCreatePayload);if !safeMailOpaque(string(payload.EntryID))||payload.Source.Validate()!=nil||payload.Source.Path.IsRoot()||payload.RetainFor<time.Hour||payload.RetainFor>365*24*time.Hour{return invalid("trash entry")};return nil}
func validateTrashMove(value any)error{payload:=value.(*TrashMovePayload);if payload.Source.Validate()!=nil||payload.Source.Path.IsRoot()||payload.RetainFor!=0&&(payload.RetainFor<time.Hour||payload.RetainFor>365*24*time.Hour){return invalid("trash entry")};return nil}
func validateTrashRestore(value any)error{payload:=value.(*TrashRestorePayload);if !safeMailOpaque(string(payload.EntryID))||payload.Destination.Validate()!=nil{return invalid("trash restore")};return nil}
func validateTrashPurge(value any)error{if !safeMailOpaque(string(value.(*TrashPurgePayload).EntryID)){return invalid("trash purge")};return nil}
func validateArchiveCreate(value any)error{payload:=value.(*ArchiveCreatePayload);if !safeMailOpaque(string(payload.ArchiveID))||payload.Destination.Validate()!=nil||len(payload.Sources)==0||len(payload.Sources)>access.MaxBatchPaths{return invalid("archive")};switch payload.Format{case access.ArchiveZIP,access.ArchiveTarGZ,access.ArchiveTarZST:default:return invalid("archive format")};for _,source:=range payload.Sources{if source.Validate()!=nil{return invalid("archive source")}};return nil}
func validateArchiveExtract(value any)error{payload:=value.(*ArchiveExtractPayload);if payload.Source.Validate()!=nil||payload.Destination.Validate()!=nil||payload.Policy.MaxFiles>1000000||payload.Policy.MaxBytes<0||payload.Policy.MaxBytes>1<<50||payload.Policy.MaxRatio>10000{return invalid("archive extraction")};return nil}

func bindAccessFiles(registry *Registry,files *access.FileService)error{
	if files==nil||files.Store==nil||files.Executor==nil{return nil}
	if err:=registry.Bind("access.upload.begin",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*UploadBeginPayload);if err:=accessSite(inv,payload.Destination.Root);err!=nil{return OperationResult{},err};session:=access.UploadSession{ID:payload.UploadID,Mutation:accessMutation(inv),Destination:payload.Destination,Integrity:payload.Integrity,Condition:payload.Condition,State:access.UploadOpen,Generation:1,ExpiresAt:time.Now().UTC().Add(payload.TTL)};created,err:=files.BeginUpload(ctx,session);if err!=nil{return OperationResult{},mapDomainError(err)};created.Handle="";return OperationResult{Status:http.StatusCreated,Value:created,Generation:created.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("access.upload.chunk",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*UploadChunkPayload);session,err:=files.Store.LoadUpload(ctx,payload.UploadID);if err!=nil{return OperationResult{},mapDomainError(err)};if err=accessOwnedUpload(inv,session);err!=nil{return OperationResult{},err};updated,err:=files.AppendUpload(ctx,payload.UploadID,payload.Chunk);clearSecret(payload.Chunk.Data);if err!=nil{return OperationResult{},mapDomainError(err)};updated.Handle="";return OperationResult{Status:http.StatusOK,Value:updated,Generation:updated.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("access.upload.commit",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){id:=value.(*UploadIDPayload).UploadID;session,err:=files.Store.LoadUpload(ctx,id);if err!=nil{return OperationResult{},mapDomainError(err)};if err=accessOwnedUpload(inv,session);err!=nil{return OperationResult{},err};receipt,err:=files.CommitUpload(ctx,id);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:receipt},nil});err!=nil{return err}
	if err:=registry.Bind("access.upload.abort",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){id:=value.(*UploadIDPayload).UploadID;session,err:=files.Store.LoadUpload(ctx,id);if err!=nil{return OperationResult{},mapDomainError(err)};if err=accessOwnedUpload(inv,session);err!=nil{return OperationResult{},err};if err=files.AbortUpload(ctx,id);err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"aborted"}},nil});err!=nil{return err}
	issueDownload:=func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*DownloadIssuePayload);if err:=accessSite(inv,payload.Source.Root);err!=nil{return OperationResult{},err};if payload.DownloadID==""{payload.DownloadID=access.DownloadID(effectID(inv))};if payload.TTL==0{payload.TTL=15*time.Minute};lease:=access.DownloadLease{ID:payload.DownloadID,Actor:accessActor(inv),Source:payload.Source,ExpiresAt:time.Now().UTC().Add(payload.TTL)};opened,err:=files.OpenDownload(ctx,lease);if err!=nil{return OperationResult{},mapDomainError(err)};query:=url.Values{"tenant_id":[]string{inv.Request.TenantID},"site_id":[]string{inv.Request.ResourceID}};result:=DownloadIssueResult{ID:opened.ID,Source:opened.Source,Integrity:opened.Integrity,ExpiresAt:opened.ExpiresAt,DownloadURL:"/api/v1/downloads/"+url.PathEscape(string(opened.ID))+"?"+query.Encode()};opened.Handle="";return OperationResult{Status:http.StatusCreated,Value:result},nil}
	if err:=registry.Bind("access.download.issue",issueDownload);err!=nil{return err}
	if err:=registry.Bind("access.files.download.issue",issueDownload);err!=nil{return err}
	if err:=registry.Bind("access.download.get",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){id:=value.(*DownloadIDPayload).DownloadID;lease,err:=files.Store.LoadDownload(ctx,id);if err!=nil{return OperationResult{},mapDomainError(err)};if err=accessOwnedDownload(inv,lease);err!=nil{return OperationResult{},err};return OperationResult{Status:http.StatusOK,Value:DownloadIssueResult{ID:lease.ID,Source:lease.Source,Integrity:lease.Integrity,ExpiresAt:lease.ExpiresAt,DownloadURL:"/api/v1/downloads/"+url.PathEscape(string(lease.ID))+"?tenant_id="+url.QueryEscape(inv.Request.TenantID)+"&site_id="+url.QueryEscape(inv.Request.ResourceID)}},nil});err!=nil{return err}
	if err:=registry.Bind("access.download.read",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*DownloadReadPayload);lease,err:=files.Store.LoadDownload(ctx,payload.DownloadID);if err!=nil{return OperationResult{},mapDomainError(err)};if err=accessOwnedDownload(inv,lease);err!=nil{return OperationResult{},err};content,err:=files.ReadDownload(ctx,lease,payload.Offset,payload.Length);if err!=nil{return OperationResult{},mapDomainError(err)};encoded:=base64.RawStdEncoding.EncodeToString(content);clearSecret(content);return OperationResult{Status:http.StatusOK,Value:DownloadReadResult{DownloadID:lease.ID,Offset:payload.Offset,ContentBase64:encoded,Integrity:lease.Integrity}},nil});err!=nil{return err}
	if err:=registry.Bind("access.download.close",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){id:=value.(*DownloadIDPayload).DownloadID;lease,err:=files.Store.LoadDownload(ctx,id);if err!=nil{return OperationResult{},mapDomainError(err)};if err=accessOwnedDownload(inv,lease);err!=nil{return OperationResult{},err};if err=files.CloseDownload(ctx,lease);err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"closed"}},nil});err!=nil{return err}
	if err:=registry.Bind("access.trash.create",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*TrashCreatePayload);if err:=accessSite(inv,payload.Source.Root);err!=nil{return OperationResult{},err};entry,err:=files.Trash(ctx,accessMutation(inv),access.FileOperationID(effectID(inv)),payload.EntryID,payload.Source,time.Now().UTC().Add(payload.RetainFor));if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusCreated,Value:entry,Generation:entry.Generation},nil});err!=nil{return err}
	moveToTrash:=func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*TrashMovePayload);if err:=accessSite(inv,payload.Source.Root);err!=nil{return OperationResult{},err};if payload.RetainFor==0{payload.RetainFor=30*24*time.Hour};entry,err:=files.Trash(ctx,accessMutation(inv),access.FileOperationID(effectID(inv)),access.TrashEntryID(effectID(inv)),payload.Source,time.Now().UTC().Add(payload.RetainFor));if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusCreated,Value:entry,Generation:entry.Generation},nil}
	if err:=registry.Bind("access.trash.move",moveToTrash);err!=nil{return err}
	if err:=registry.Bind("access.file.trash",moveToTrash);err!=nil{return err}
	if err:=registry.Bind("access.trash.restore",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*TrashRestorePayload);entry,err:=files.Store.LoadTrash(ctx,payload.EntryID);if err!=nil{return OperationResult{},mapDomainError(err)};if string(entry.SiteID)!=inv.Request.ResourceID||accessSite(inv,payload.Destination.Root)!=nil{return OperationResult{},ErrForbidden};receipt,err:=files.RestoreTrash(ctx,payload.EntryID,payload.Destination,payload.Condition);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:receipt},nil});err!=nil{return err}
	if err:=registry.Bind("access.trash.purge",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*TrashPurgePayload);entry,err:=files.Store.LoadTrash(ctx,payload.EntryID);if err!=nil{return OperationResult{},mapDomainError(err)};if string(entry.SiteID)!=inv.Request.ResourceID{return OperationResult{},ErrForbidden};receipt,err:=files.PurgeTrash(ctx,payload.EntryID,payload.Force);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:receipt},nil});err!=nil{return err}
	if err:=registry.Bind("access.archive.create",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*ArchiveCreatePayload);if err:=accessSite(inv,payload.Destination.Root);err!=nil{return OperationResult{},err};for _,source:=range payload.Sources{if err=accessSite(inv,source.Root);err!=nil{return OperationResult{},err}};archive,err:=files.CreateArchive(ctx,access.Archive{ID:payload.ArchiveID,Format:payload.Format,Sources:payload.Sources,Destination:payload.Destination});if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusCreated,Value:archive},nil});err!=nil{return err}
	return registry.Bind("access.archive.extract",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*ArchiveExtractPayload);if err:=accessSite(inv,payload.Source.Root,payload.Destination.Root);err!=nil{return OperationResult{},err};receipt,err:=files.ExtractArchive(ctx,payload.Source,payload.Destination,payload.Policy);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:receipt},nil})
}

func bindAccessFileDomains(registry *Registry,services DomainServices)error{return bindAccessFiles(registry,services.Files)}

func accessActor(inv Invocation)access.AuditActor{return access.AuditActor{TenantID:access.TenantID(inv.Request.TenantID),PrincipalID:access.PrincipalID(inv.Actor.PrincipalID.String()),SourceIP:inv.Meta.ClientIP.String()}}
func accessMutation(inv Invocation)access.Mutation{return access.Mutation{CommandID:access.CommandID(commandID(inv)),Actor:accessActor(inv),At:time.Now().UTC()}}
func accessSite(inv Invocation,roots ...access.SiteRoot)error{for _,root:=range roots{if string(root.SiteID)!=inv.Request.ResourceID{return ErrForbidden};if err:=root.Validate();err!=nil{return ErrInvalidRequest}};return nil}
func accessOwnedUpload(inv Invocation,session access.UploadSession)error{if err:=accessSite(inv,session.Destination.Root);err!=nil{return err};if session.Mutation.Actor.TenantID!=access.TenantID(inv.Request.TenantID)||session.Mutation.Actor.PrincipalID!=access.PrincipalID(inv.Actor.PrincipalID.String()){return ErrForbidden};return nil}
func accessOwnedDownload(inv Invocation,lease access.DownloadLease)error{if err:=accessSite(inv,lease.Source.Root);err!=nil{return err};if lease.Actor.TenantID!=access.TenantID(inv.Request.TenantID)||lease.Actor.PrincipalID!=access.PrincipalID(inv.Actor.PrincipalID.String()){return ErrForbidden};return nil}
