package apiserver

import (
	"context"
	"net/http"

	"github.com/aonsyed/cyberpanel/platform/internal/apps"
	"github.com/aonsyed/cyberpanel/platform/internal/identity"
)

type ApplicationInstallPayload struct{Request apps.InstallRequest `json:"request"`}
type ApplicationDiscoverPayload struct{Request apps.DiscoveryRequest `json:"request"`}
type ApplicationAdoptPayload struct{Request apps.AdoptionRequest `json:"request"`}
type ApplicationUpdatePayload struct{Request apps.UpdateRequest `json:"request"`}
type ApplicationRepairPayload struct{Request apps.RepairRequest `json:"request"`}
type ApplicationRemovePayload struct{Request apps.RemovalRequest `json:"request"`}
type WordPressComponentPayload struct{Request apps.WordPressMutationRequest `json:"request"`}
type WordPressSettingsPayload struct{Request apps.WordPressSettingsRequest `json:"request"`}
type WordPressLSCachePayload struct{Request apps.LSCacheRequest `json:"request"`}
type WordPressLSCachePurgePayload struct{Request apps.LSCachePurgeRequest `json:"request"`}
type WordPressAutologinIssuePayload struct{Request apps.LoginGrantRequest `json:"request"`}
type WordPressAutologinExchangePayload struct{Request apps.LoginGrantExchange `json:"request"`}
type WordPressAutologinBridgePayload struct{CommandID apps.CommandID `json:"command_id,omitempty"`;Request apps.AutologinBridgeRequest `json:"request"`}

func registerApplicationContracts(registry *Registry)error{
	if err:=register(registry,Operation{Name:"application.install",Permission:identity.MustPermission("application:install"),Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ApplicationInstallPayload{}},ResolveScope:siteScope});err!=nil{return err}
	operations:=[]Operation{
		{Name:"application.discover",Permission:identity.MustPermission("application:manage"),Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ApplicationDiscoverPayload{}},ValidatePayload:validateApplicationDiscoverPayload,ResolveScope:applicationSiteGenerationScope},
		{Name:"application.adopt",Permission:identity.MustPermission("application:install"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ApplicationAdoptPayload{}},ValidatePayload:validateApplicationAdoptPayload,ResolveScope:applicationSiteGenerationScope},
		{Name:"application.update",Permission:identity.MustPermission("application:update"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ApplicationUpdatePayload{}},ResolveScope:siteScope},
		{Name:"application.repair",Permission:identity.MustPermission("application:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ApplicationRepairPayload{}},ResolveScope:siteScope},
		{Name:"application.remove",Permission:identity.MustPermission("application:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ApplicationRemovePayload{}},ResolveScope:siteScope},
		{Name:"application.wordpress.component.mutate",Permission:identity.MustPermission("application:manage"),Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &WordPressComponentPayload{}},ResolveScope:siteScope},
		{Name:"application.wordpress.settings.update",Permission:identity.MustPermission("application:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &WordPressSettingsPayload{}},ResolveScope:siteScope},
		{Name:"application.wordpress.lscache.configure",Permission:identity.MustPermission("application:manage"),Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &WordPressLSCachePayload{}},ResolveScope:siteScope},
		{Name:"application.wordpress.lscache.purge",Permission:identity.MustPermission("application:manage"),Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &WordPressLSCachePurgePayload{}},ResolveScope:siteScope},
		{Name:"application.wordpress.autologin.issue",Permission:identity.MustPermission("application:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &WordPressAutologinIssuePayload{}},ResolveScope:siteScope},
		{Name:"application.wordpress.autologin.exchange",Auth:AuthNone,Mutating:true,MaximumBodyBytes:32<<10,NewPayload:func()any{return &WordPressAutologinExchangePayload{}},ValidatePayload:func(value any)error{if value.(*WordPressAutologinExchangePayload).Request.Validate()!=nil{return invalid("autologin exchange")};return nil},ResolveScope:installationScope},
		{Name:"application.wordpress.autologin.bridge.install",Permission:identity.MustPermission("application:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &WordPressAutologinBridgePayload{}},ResolveScope:siteScope},
		{Name:"application.wordpress.autologin.bridge.remove",Permission:identity.MustPermission("application:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &WordPressAutologinBridgePayload{}},ResolveScope:siteScope},
	};for _,operation:=range operations{if err:=register(registry,operation);err!=nil{return err}};return nil
}

func bindApplications(registry *Registry,services DomainServices)error{
	if services.Applications==nil{return nil}
	if err:=registry.Bind("application.install",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){p:=value.(*ApplicationInstallPayload);p.Request.CommandID=apps.CommandID(commandID(inv));p.Request.TenantID=apps.TenantID(inv.Request.TenantID);p.Request.SiteID=apps.SiteID(inv.Request.ResourceID);installation,err:=services.Applications.Install(ctx,p.Request);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusCreated,Value:installation,Generation:installation.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("application.update",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){p:=value.(*ApplicationUpdatePayload);if _,err:=loadScopedApplication(ctx,services.Applications.Store,p.Request.InstallationID,inv);err!=nil{return OperationResult{},err};p.Request.CommandID=apps.CommandID(commandID(inv));p.Request.ExpectedGeneration=inv.Request.ExpectedGeneration;deployment,err:=services.Applications.Update(ctx,p.Request);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:deployment},nil});err!=nil{return err}
	if services.ApplicationLifecycle!=nil{if err:=registry.Bind("application.discover",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){p:=value.(*ApplicationDiscoverPayload);p.Request.CommandID=apps.CommandID(commandID(inv));p.Request.TenantID=apps.TenantID(inv.Request.TenantID);p.Request.SiteID=apps.SiteID(inv.Request.ResourceID);p.Request.SiteGeneration=inv.Request.ExpectedGeneration;candidates,err:=services.ApplicationLifecycle.Discover(ctx,p.Request);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:candidates,Generation:inv.Request.ExpectedGeneration},nil});err!=nil{return err};if err:=registry.Bind("application.adopt",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){p:=value.(*ApplicationAdoptPayload);p.Request.CommandID=apps.CommandID(commandID(inv));p.Request.TenantID=apps.TenantID(inv.Request.TenantID);p.Request.SiteID=apps.SiteID(inv.Request.ResourceID);p.Request.SiteGeneration=inv.Request.ExpectedGeneration;p.Request.RuntimeID=p.Request.Candidate.RuntimeID;p.Request.InstallationID=apps.DerivedAdoptionInstallationID(p.Request.TenantID,p.Request.SiteID,p.Request.Candidate);p.Request.ReleaseID=apps.DerivedAdoptionReleaseID(p.Request.InstallationID,p.Request.Candidate);installation,err:=services.ApplicationLifecycle.Adopt(ctx,p.Request);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusCreated,Value:installation,Generation:installation.Generation},nil});err!=nil{return err};if err:=registry.Bind("application.repair",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){p:=value.(*ApplicationRepairPayload);if _,err:=loadScopedApplication(ctx,services.ApplicationLifecycle.Store,p.Request.InstallationID,inv);err!=nil{return OperationResult{},err};p.Request.CommandID=apps.CommandID(commandID(inv));p.Request.ExpectedGeneration=inv.Request.ExpectedGeneration;installation,err:=services.ApplicationLifecycle.Repair(ctx,p.Request);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:installation,Generation:installation.Generation},nil});err!=nil{return err};if err:=registry.Bind("application.remove",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){p:=value.(*ApplicationRemovePayload);if _,err:=loadScopedApplication(ctx,services.ApplicationLifecycle.Store,p.Request.InstallationID,inv);err!=nil{return OperationResult{},err};p.Request.CommandID=apps.CommandID(commandID(inv));p.Request.ExpectedGeneration=inv.Request.ExpectedGeneration;installation,err:=services.ApplicationLifecycle.Remove(ctx,p.Request);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:installation,Generation:installation.Generation},nil});err!=nil{return err}}
	if services.WordPress!=nil{if err:=registry.Bind("application.wordpress.component.mutate",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){p:=value.(*WordPressComponentPayload);if _,err:=loadScopedApplication(ctx,services.WordPress.Store,p.Request.InstallationID,inv);err!=nil{return OperationResult{},err};p.Request.CommandID=apps.CommandID(commandID(inv));p.Request.ExpectedGeneration=inv.Request.ExpectedGeneration;inventory,err:=services.WordPress.MutateComponent(ctx,p.Request);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:inventory,Generation:inventory.Generation},nil});err!=nil{return err};if err:=registry.Bind("application.wordpress.settings.update",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){p:=value.(*WordPressSettingsPayload);if _,err:=loadScopedApplication(ctx,services.WordPress.Store,p.Request.InstallationID,inv);err!=nil{return OperationResult{},err};p.Request.CommandID=apps.CommandID(commandID(inv));p.Request.ExpectedGeneration=inv.Request.ExpectedGeneration;settings,err:=services.WordPress.UpdateSettings(ctx,p.Request);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:settings,Generation:settings.Generation},nil});err!=nil{return err};if err:=registry.Bind("application.wordpress.lscache.configure",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){p:=value.(*WordPressLSCachePayload);if _,err:=loadScopedApplication(ctx,services.WordPress.Store,p.Request.InstallationID,inv);err!=nil{return OperationResult{},err};p.Request.CommandID=apps.CommandID(commandID(inv));p.Request.ExpectedGeneration=inv.Request.ExpectedGeneration;policy,err:=services.WordPress.ConfigureLSCache(ctx,p.Request);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:policy,Generation:policy.Generation},nil});err!=nil{return err};if err:=registry.Bind("application.wordpress.lscache.purge",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){p:=value.(*WordPressLSCachePurgePayload);if _,err:=loadScopedApplication(ctx,services.WordPress.Store,p.Request.InstallationID,inv);err!=nil{return OperationResult{},err};p.Request.CommandID=apps.CommandID(commandID(inv));if err:=services.WordPress.PurgeLSCache(ctx,p.Request);err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusNoContent},nil});err!=nil{return err}}
	if services.ApplicationAutologin!=nil{if err:=registry.Bind("application.wordpress.autologin.issue",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){p:=value.(*WordPressAutologinIssuePayload);installation,err:=loadScopedApplication(ctx,services.Applications.Store,p.Request.InstallationID,inv);if err!=nil{return OperationResult{},err};if installation.Kind!=apps.ApplicationWordPress{return OperationResult{},ErrConflict};p.Request.ID=apps.LoginGrantID(commandID(inv));p.Request.TenantID=installation.TenantID;p.Request.SiteID=installation.SiteID;grant,credential,err:=services.ApplicationAutologin.Issue(ctx,p.Request);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusCreated,Value:struct{Grant apps.LoginGrant `json:"grant"`;Credential apps.LoginCredential `json:"credential"`}{grant,credential},Generation:grant.Generation},nil});err!=nil{return err};if err:=registry.Bind("application.wordpress.autologin.exchange",func(ctx context.Context,_ Invocation,value any)(OperationResult,error){p:=value.(*WordPressAutologinExchangePayload);grant,err:=services.ApplicationAutologin.Exchange(ctx,p.Request);p.Request.Secret="";p.Request.CSRFBinding="";if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:struct{WordPressUserID uint64 `json:"wordpress_user_id"`}{grant.WordPressUserID},Generation:grant.Generation},nil});err!=nil{return err}};return nil
	if services.ApplicationAutologinBridge!=nil{bindBridge:=func(remove bool)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){p:=value.(*WordPressAutologinBridgePayload);installation,err:=loadScopedApplication(ctx,services.ApplicationAutologinBridge.Store,p.Request.InstallationID,inv);if err!=nil{return OperationResult{},err};if installation.Kind!=apps.ApplicationWordPress{return OperationResult{},ErrConflict};p.CommandID=apps.CommandID(commandID(inv));p.Request.Scope.TenantID=installation.TenantID;p.Request.Scope.SiteID=installation.SiteID;p.Request.Scope.SiteUID=installation.SiteUID;p.Request.Scope.Root=installation.Root;if remove{err=services.ApplicationAutologinBridge.Remove(ctx,p.CommandID,p.Request)}else{err=services.ApplicationAutologinBridge.Install(ctx,p.CommandID,p.Request)};if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusNoContent},nil}};if err:=registry.Bind("application.wordpress.autologin.bridge.install",bindBridge(false));err!=nil{return err};if err:=registry.Bind("application.wordpress.autologin.bridge.remove",bindBridge(true));err!=nil{return err}};return nil
}

func loadScopedApplication(ctx context.Context,store apps.ApplicationStore,id apps.InstallationID,inv Invocation)(apps.ApplicationInstallation,error){installation,err:=store.LoadInstallation(ctx,id);if err!=nil{return apps.ApplicationInstallation{},mapDomainError(err)};if string(installation.TenantID)!=inv.Request.TenantID||string(installation.SiteID)!=inv.Request.ResourceID{return apps.ApplicationInstallation{},ErrForbidden};return installation,nil}

func applicationSiteGenerationScope(request RequestEnvelope,value any)(identity.Scope,error){if request.ExpectedGeneration==0{return identity.Scope{},invalid("application site generation")};return siteScope(request,value)}
func validateApplicationDiscoverPayload(value any)error{request:=&value.(*ApplicationDiscoverPayload).Request;if request.MaximumDepth==0{request.MaximumDepth=4};if request.MaximumCandidates==0{request.MaximumCandidates=32};if !validEdgeID(request.RuntimeID)||request.MaximumDepth>16||request.MaximumCandidates>1000||len(request.Kinds)==0||len(request.Kinds)>4{return invalid("application discovery")};seen:=map[apps.ApplicationKind]bool{};for _,kind:=range request.Kinds{switch kind{case apps.ApplicationJoomla,apps.ApplicationPrestaShop,apps.ApplicationMautic,apps.ApplicationMagento:default:return invalid("application discovery kind")};if seen[kind]{return invalid("application discovery kind")};seen[kind]=true};return nil}
func validateApplicationAdoptPayload(value any)error{request:=value.(*ApplicationAdoptPayload).Request;if request.Candidate.Validate()!=nil||request.Database!=(apps.DatabaseBinding{})||request.CanonicalURL==""{return invalid("application adoption")};return nil}
