package apiserver

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/hosting/service"
	"github.com/aonsyed/cyberpanel/platform/internal/hosting/site"
	"github.com/aonsyed/cyberpanel/platform/internal/identity"
)

type LoginPayload struct { Username string `json:"username"`; Password string `json:"password"` }
type TOTPLoginPayload struct { ChallengeID string `json:"challenge_id"`; Code string `json:"code"` }
type LoginPublicResult struct { PrincipalID string `json:"principal_id"`; DisplayName string `json:"display_name"`; Locale string `json:"locale"`; Theme identity.Theme `json:"theme"`; Assurance identity.AssuranceLevel `json:"assurance"`; CSRFToken string `json:"csrf_token"`; ExpiresAt time.Time `json:"expires_at"`; MFARequired bool `json:"mfa_required,omitempty"`; ChallengeID string `json:"challenge_id,omitempty"`; Viewer identity.ViewerProjection `json:"viewer"` }
type WebAuthnLoginBeginPayload struct{Username string `json:"username"`}
type WebAuthnLoginFinishPayload struct{ChallengeID string `json:"challenge_id"`;Response json.RawMessage `json:"response"`}
type WebAuthnLoginBeginResult struct{ChallengeID string `json:"challenge_id"`;PublicKey json.RawMessage `json:"public_key"`;ExpiresAt time.Time `json:"expires_at"`}
type WebAuthnEnrollmentBeginPayload struct{CredentialID string `json:"credential_id"`}
type WebAuthnEnrollmentFinishPayload struct{CredentialID string `json:"credential_id"`;Response json.RawMessage `json:"response"`}
type WebAuthnEnrollmentBeginResult struct{CredentialID string `json:"credential_id"`;PublicKey json.RawMessage `json:"public_key"`;State identity.CredentialState `json:"state"`}
type WebAuthnEnrollmentFinishResult struct{CredentialID string `json:"credential_id"`;State identity.CredentialState `json:"state"`}
type SessionPolicyProjection struct{Mode identity.SessionBindingMode `json:"mode"`;IPv4PrefixBits uint8 `json:"ipv4_prefix_bits"`;IPv6PrefixBits uint8 `json:"ipv6_prefix_bits"`;Generation uint64 `json:"generation"`;UpdatedAt time.Time `json:"updated_at"`}
type SessionPolicyUpdatePayload struct{Mode identity.SessionBindingMode `json:"mode"`;IPv4PrefixBits uint8 `json:"ipv4_prefix_bits,omitempty"`;IPv6PrefixBits uint8 `json:"ipv6_prefix_bits,omitempty"`}
type SessionListPayload struct{Limit uint16 `json:"limit,omitempty"`;Cursor string `json:"cursor,omitempty"`}
type SessionProjection struct{ID string `json:"id"`;Current bool `json:"current"`;Assurance identity.AssuranceLevel `json:"assurance"`;BindingMode identity.SessionBindingMode `json:"binding_mode"`;IPv4PrefixBits uint8 `json:"ipv4_prefix_bits"`;IPv6PrefixBits uint8 `json:"ipv6_prefix_bits"`;SourcePrefix string `json:"source_prefix"`;UserAgentDigest string `json:"user_agent_digest"`;CreatedAt time.Time `json:"created_at"`;LastSeenAt time.Time `json:"last_seen_at"`;ExpiresAt time.Time `json:"expires_at"`;AbsoluteExpiresAt time.Time `json:"absolute_expires_at"`;RevokedAt *time.Time `json:"revoked_at,omitempty"`}
type SessionListResult struct{Items []SessionProjection `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`;Total uint64 `json:"total"`}

func registerIdentityContracts(registry *Registry)error{
	if err:=register(registry,Operation{Name:"identity.session.login",Auth:AuthNone,Mutating:false,NewPayload:func()any{return &LoginPayload{}},ValidatePayload:func(value any)error{payload:=value.(*LoginPayload);if len(strings.TrimSpace(payload.Username))<2||len(payload.Username)>63||len(payload.Password)<12||len(payload.Password)>4096{return invalid("login")};return nil},ResolveScope:installationScope});err!=nil{return err}
	if err:=register(registry,Operation{Name:"identity.session.mfa_totp",Auth:AuthNone,Mutating:false,NewPayload:func()any{return &TOTPLoginPayload{}},ValidatePayload:func(value any)error{payload:=value.(*TOTPLoginPayload);if _,err:=identity.NewID(payload.ChallengeID);err!=nil||len(payload.Code)<6||len(payload.Code)>12{return invalid("TOTP login")};return nil},ResolveScope:installationScope});err!=nil{return err}
	definitions:=[]Operation{
		{Name:"identity.session.current",Auth:AuthRequired,SelfService:true,Assurance:identity.AssurancePassword,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:identitySessionScope},
		{Name:"identity.session.logout",Auth:AuthRequired,SelfService:true,Assurance:identity.AssurancePassword,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:identitySessionScope},
		{Name:"identity.session.policy.current",Auth:AuthRequired,SelfService:true,Assurance:identity.AssurancePassword,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:identitySessionScope},
		{Name:"identity.session.policy.update",Auth:AuthRequired,SelfService:true,Assurance:identity.AssurancePassword,Mutating:true,NewPayload:func()any{return &SessionPolicyUpdatePayload{}},ValidatePayload:validateSessionPolicyUpdate,ResolveScope:identitySessionPolicyMutationScope},
		{Name:"identity.session.list",Auth:AuthRequired,SelfService:true,Assurance:identity.AssurancePassword,NewPayload:func()any{return &SessionListPayload{}},ValidatePayload:validateSessionList,ResolveScope:identitySessionScope},
		{Name:"identity.session.revoke",Auth:AuthRequired,SelfService:true,Assurance:identity.AssurancePassword,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:identitySessionResourceScope},
		{Name:"identity.session.revoke_others",Auth:AuthRequired,SelfService:true,Assurance:identity.AssurancePassword,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:identitySessionScope},
		{Name:"identity.session.webauthn.begin",Auth:AuthNone,NewPayload:func()any{return &WebAuthnLoginBeginPayload{}},ValidatePayload:validateWebAuthnLoginBegin,ResolveScope:identitySessionScope},
		{Name:"identity.session.webauthn.finish",Auth:AuthNone,MaximumBodyBytes:3<<20,NewPayload:func()any{return &WebAuthnLoginFinishPayload{}},ValidatePayload:validateWebAuthnLoginFinish,ResolveScope:identitySessionScope},
		{Name:"identity.credential.webauthn.begin",Auth:AuthRequired,SelfService:true,Assurance:identity.AssurancePassword,Mutating:true,NewPayload:func()any{return &WebAuthnEnrollmentBeginPayload{}},ValidatePayload:validateWebAuthnEnrollmentBegin,ResolveScope:identitySessionScope},
		{Name:"identity.credential.webauthn.finish",Auth:AuthRequired,SelfService:true,Assurance:identity.AssurancePassword,Mutating:true,MaximumBodyBytes:3<<20,NewPayload:func()any{return &WebAuthnEnrollmentFinishPayload{}},ValidatePayload:validateWebAuthnEnrollmentFinish,ResolveScope:identitySessionScope},
	}
	for _,definition:=range definitions{if err:=register(registry,definition);err!=nil{return err}}
	return nil
}

func bindIdentity(registry *Registry,services DomainServices)error{
	if services.Identity==nil{return nil}
	if err:=registry.Bind("identity.session.login",func(ctx context.Context,invocation Invocation,value any)(OperationResult,error){payload:=value.(*LoginPayload);result,err:=services.Identity.AuthenticatePassword(ctx,identity.LoginRequest{Username:payload.Username,Password:[]byte(payload.Password),Source:invocation.Meta.ClientIP,UserAgentDigest:invocation.Meta.UserAgentDigest,SessionTTL:30*time.Minute,AbsoluteTTL:12*time.Hour});payload.Password="";if errors.Is(err,identity.ErrAssuranceRequired)&&result.MFARequired{viewer:=loginViewer(result.Principal);return OperationResult{Status:http.StatusAccepted,Value:LoginPublicResult{PrincipalID:result.Principal.ID.String(),DisplayName:result.Principal.DisplayName,Locale:result.Principal.Locale,Theme:result.Principal.Theme,MFARequired:true,ChallengeID:result.ChallengeID.String(),Viewer:viewer}},nil};if err!=nil{return OperationResult{},mapIdentityError(err)};viewer,err:=services.Identity.CurrentViewer(ctx,loginActor(result));if err!=nil{return OperationResult{},mapIdentityError(err)};return loginResult(result,viewer)});err!=nil{return err}
	if err:=registry.Bind("identity.session.mfa_totp",func(ctx context.Context,invocation Invocation,value any)(OperationResult,error){payload:=value.(*TOTPLoginPayload);challenge,_:=identity.NewID(payload.ChallengeID);result,err:=services.Identity.CompleteTOTPLogin(ctx,challenge,payload.Code,invocation.Meta.ClientIP,30*time.Minute,12*time.Hour);payload.Code="";if err!=nil{return OperationResult{},mapIdentityError(err)};viewer,err:=services.Identity.CurrentViewer(ctx,loginActor(result));if err!=nil{return OperationResult{},mapIdentityError(err)};return loginResult(result,viewer)});err!=nil{return err}
	if err:=registry.Bind("identity.session.current",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){viewer,err:=services.Identity.CurrentViewer(ctx,inv.Actor.IdentityContext());if err!=nil{return OperationResult{},mapIdentityError(err)};return OperationResult{Status:http.StatusOK,Value:viewer},nil});err!=nil{return err}
	if err:=registry.Bind("identity.session.logout",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){if inv.Actor.CredentialKind!=CredentialSession{return OperationResult{},ErrInvalidRequest};if err:=services.Identity.RevokeCurrentSession(ctx,inv.Actor.IdentityContext());err!=nil{return OperationResult{},mapIdentityError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"logged_out"},ClearSession:true},nil});err!=nil{return err}
	if err:=registry.Bind("identity.session.policy.current",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){if inv.Actor.CredentialKind!=CredentialSession{return OperationResult{},ErrForbidden};policy,err:=services.Identity.CurrentSessionPolicy(ctx,inv.Actor.IdentityContext());if err!=nil{return OperationResult{},mapIdentityError(err)};return OperationResult{Status:http.StatusOK,Value:sessionPolicyProjection(policy),Generation:policy.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("identity.session.policy.update",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){if inv.Actor.CredentialKind!=CredentialSession{return OperationResult{},ErrForbidden};payload:=value.(*SessionPolicyUpdatePayload);binding:=identity.SessionBindingPolicy{Mode:payload.Mode,IPv4PrefixBits:payload.IPv4PrefixBits,IPv6PrefixBits:payload.IPv6PrefixBits};policy,err:=services.Identity.UpdateSessionPolicy(ctx,inv.Actor.IdentityContext(),inv.Request.ExpectedGeneration,binding);if err!=nil{return OperationResult{},mapIdentityError(err)};return OperationResult{Status:http.StatusOK,Value:sessionPolicyProjection(policy),Generation:policy.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("identity.session.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){if inv.Actor.CredentialKind!=CredentialSession{return OperationResult{},ErrForbidden};payload:=value.(*SessionListPayload);cursor,err:=optionalSessionID(payload.Cursor);if err!=nil{return OperationResult{},ErrInvalidRequest};sessions,next,total,err:=services.Identity.ListSessions(ctx,inv.Actor.IdentityContext(),int(payload.Limit),cursor);if err!=nil{return OperationResult{},mapIdentityError(err)};items:=make([]SessionProjection,0,len(sessions));for _,session:=range sessions{items=append(items,sessionProjection(session,inv.Actor.SessionID))};return OperationResult{Status:http.StatusOK,Value:SessionListResult{Items:items,NextCursor:next,Total:total}},nil});err!=nil{return err}
	if err:=registry.Bind("identity.session.revoke",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){if inv.Actor.CredentialKind!=CredentialSession{return OperationResult{},ErrForbidden};sessionID,err:=identity.NewID(inv.Request.ResourceID);if err!=nil{return OperationResult{},ErrInvalidRequest};session,err:=services.Identity.RevokeSession(ctx,inv.Actor.IdentityContext(),sessionID);if err!=nil{return OperationResult{},mapIdentityError(err)};current:=session.ID==inv.Actor.SessionID;return OperationResult{Status:http.StatusOK,Value:sessionProjection(session,inv.Actor.SessionID),ClearSession:current},nil});err!=nil{return err}
	if err:=registry.Bind("identity.session.revoke_others",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){if inv.Actor.CredentialKind!=CredentialSession{return OperationResult{},ErrForbidden};count,err:=services.Identity.RevokeOtherSessions(ctx,inv.Actor.IdentityContext());if err!=nil{return OperationResult{},mapIdentityError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]uint64{"revoked":count}},nil});err!=nil{return err}
	if err:=registry.Bind("identity.session.webauthn.begin",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){rpID,err:=webAuthnRP(inv.Meta);if err!=nil{return OperationResult{},err};challenge,err:=services.Identity.BeginWebAuthnLogin(ctx,value.(*WebAuthnLoginBeginPayload).Username,rpID);if err!=nil{return OperationResult{},mapIdentityError(err)};options:=append(json.RawMessage(nil),challenge.PublicKeyOptions...);clearSecret(challenge.PublicKeyOptions);return OperationResult{Status:http.StatusOK,Value:WebAuthnLoginBeginResult{ChallengeID:challenge.ChallengeID.String(),PublicKey:options,ExpiresAt:challenge.ExpiresAt}},nil});err!=nil{return err}
	if err:=registry.Bind("identity.session.webauthn.finish",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){if _,err:=webAuthnRP(inv.Meta);err!=nil{return OperationResult{},err};payload:=value.(*WebAuthnLoginFinishPayload);challenge,_:=identity.NewID(payload.ChallengeID);response:=append([]byte(nil),payload.Response...);clearSecret(payload.Response);result,err:=services.Identity.CompleteWebAuthnLogin(ctx,challenge,response,inv.Meta.ClientIP,inv.Meta.UserAgentDigest,30*time.Minute,12*time.Hour);clearSecret(response);if err!=nil{return OperationResult{},mapIdentityError(err)};viewer,err:=services.Identity.CurrentViewer(ctx,loginActor(result));if err!=nil{return OperationResult{},mapIdentityError(err)};return loginResult(result,viewer)});err!=nil{return err}
	if err:=registry.Bind("identity.credential.webauthn.begin",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){if inv.Actor.CredentialKind!=CredentialSession{return OperationResult{},ErrForbidden};rpID,err:=webAuthnRP(inv.Meta);if err!=nil{return OperationResult{},err};payload:=value.(*WebAuthnEnrollmentBeginPayload);credentialID,_:=identity.NewID(payload.CredentialID);enrollment,err:=services.Identity.BeginWebAuthn(ctx,inv.Actor.IdentityContext(),credentialID,rpID);if err!=nil{return OperationResult{},mapIdentityError(err)};options:=append(json.RawMessage(nil),enrollment.WebAuthnOptions...);clearSecret(enrollment.WebAuthnOptions);return OperationResult{Status:http.StatusCreated,Value:WebAuthnEnrollmentBeginResult{CredentialID:enrollment.Credential.ID.String(),PublicKey:options,State:enrollment.Credential.State}},nil});err!=nil{return err}
	return registry.Bind("identity.credential.webauthn.finish",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){if inv.Actor.CredentialKind!=CredentialSession{return OperationResult{},ErrForbidden};if _,err:=webAuthnRP(inv.Meta);err!=nil{return OperationResult{},err};payload:=value.(*WebAuthnEnrollmentFinishPayload);credentialID,_:=identity.NewID(payload.CredentialID);response:=append([]byte(nil),payload.Response...);clearSecret(payload.Response);credential,err:=services.Identity.FinishWebAuthn(ctx,inv.Actor.IdentityContext(),credentialID,response);clearSecret(response);if err!=nil{return OperationResult{},mapIdentityError(err)};return OperationResult{Status:http.StatusOK,Value:WebAuthnEnrollmentFinishResult{CredentialID:credential.ID.String(),State:credential.State}},nil})
}

func loginResult(result identity.LoginResult,viewer identity.ViewerProjection)(OperationResult,error){delivery:=&SessionDelivery{SessionID:result.Session.ID.String(),SessionToken:base64.RawURLEncoding.EncodeToString(result.SessionToken),CSRFToken:base64.RawURLEncoding.EncodeToString(result.CSRFToken),ExpiresAt:result.Session.ExpiresAt};public:=LoginPublicResult{PrincipalID:result.Principal.ID.String(),DisplayName:result.Principal.DisplayName,Locale:result.Principal.Locale,Theme:result.Principal.Theme,Assurance:result.Session.Assurance,CSRFToken:delivery.CSRFToken,ExpiresAt:delivery.ExpiresAt,Viewer:viewer};return OperationResult{Status:http.StatusOK,Value:public,Session:delivery},nil}
func loginActor(result identity.LoginResult)identity.ActorContext{return identity.ActorContext{PrincipalID:result.Principal.ID,CredentialID:result.Credential.ID,SessionID:result.Session.ID,AuthzEpoch:result.Principal.AuthzEpoch,Assurance:result.Session.Assurance}}
func loginViewer(principal identity.Principal)identity.ViewerProjection{return identity.ViewerProjection{PrincipalID:principal.ID,Username:principal.Username,Email:principal.Email,DisplayName:principal.DisplayName,Locale:principal.Locale,Theme:principal.Theme,AuthzEpoch:principal.AuthzEpoch,Tenants:[]identity.ViewerTenant{}}}
func identitySessionScope(request RequestEnvelope,value any)(identity.Scope,error){if request.TenantID!=""||request.ResourceID!=""||request.ExpectedGeneration!=0{return identity.Scope{},invalid("identity session scope")};return installationScope(request,value)}
func identitySessionPolicyMutationScope(request RequestEnvelope,value any)(identity.Scope,error){if request.TenantID!=""||request.ResourceID!=""||request.ExpectedGeneration==0{return identity.Scope{},invalid("identity session policy generation")};return installationScope(request,value)}
func identitySessionResourceScope(request RequestEnvelope,value any)(identity.Scope,error){if request.TenantID!=""||request.ExpectedGeneration!=0{return identity.Scope{},invalid("identity session resource scope")};if _,err:=identity.NewID(request.ResourceID);err!=nil{return identity.Scope{},invalid("identity session resource")};return installationScope(request,value)}
func validateSessionPolicyUpdate(value any)error{payload:=value.(*SessionPolicyUpdatePayload);if (identity.SessionBindingPolicy{Mode:payload.Mode,IPv4PrefixBits:payload.IPv4PrefixBits,IPv6PrefixBits:payload.IPv6PrefixBits}).Validate()!=nil{return invalid("session binding policy")};return nil}
func validateSessionList(value any)error{payload:=value.(*SessionListPayload);if payload.Limit==0{payload.Limit=50};if payload.Limit>200{return invalid("session page")};if _,err:=optionalSessionID(payload.Cursor);err!=nil{return invalid("session cursor")};return nil}
func optionalSessionID(value string)(identity.ID,error){if value==""{return "",nil};return identity.NewID(value)}
func sessionPolicyProjection(value identity.PrincipalSessionPolicy)SessionPolicyProjection{return SessionPolicyProjection{Mode:value.Binding.Mode,IPv4PrefixBits:value.Binding.IPv4PrefixBits,IPv6PrefixBits:value.Binding.IPv6PrefixBits,Generation:value.Generation,UpdatedAt:value.UpdatedAt}}
func sessionProjection(value identity.SessionMetadata,current identity.ID)SessionProjection{return SessionProjection{ID:value.ID.String(),Current:value.ID==current,Assurance:value.Assurance,BindingMode:value.BindingPolicy.Mode,IPv4PrefixBits:value.BindingPolicy.IPv4PrefixBits,IPv6PrefixBits:value.BindingPolicy.IPv6PrefixBits,SourcePrefix:value.SourcePrefix.String(),UserAgentDigest:value.UserAgentDigest,CreatedAt:value.CreatedAt,LastSeenAt:value.LastSeenAt,ExpiresAt:value.ExpiresAt,AbsoluteExpiresAt:value.AbsoluteExpiresAt,RevokedAt:value.RevokedAt}}
func validateWebAuthnLoginBegin(value any)error{username:=strings.TrimSpace(value.(*WebAuthnLoginBeginPayload).Username);if len(username)<2||len(username)>63||strings.ContainsAny(username,"\x00\r\n\t"){return invalid("WebAuthn login")};return nil}
func validateWebAuthnLoginFinish(value any)error{payload:=value.(*WebAuthnLoginFinishPayload);if _,err:=identity.NewID(payload.ChallengeID);err!=nil||!validBrowserCredentialJSON(payload.Response){return invalid("WebAuthn response")};return nil}
func validateWebAuthnEnrollmentBegin(value any)error{if _,err:=identity.NewID(value.(*WebAuthnEnrollmentBeginPayload).CredentialID);err!=nil{return invalid("WebAuthn enrollment")};return nil}
func validateWebAuthnEnrollmentFinish(value any)error{payload:=value.(*WebAuthnEnrollmentFinishPayload);if _,err:=identity.NewID(payload.CredentialID);err!=nil||!validBrowserCredentialJSON(payload.Response){return invalid("WebAuthn response")};return nil}
func validBrowserCredentialJSON(value json.RawMessage)bool{if len(value)<16||len(value)>2<<20||value[0]!='{'||value[len(value)-1]!='}'{return false};var decoded map[string]json.RawMessage;decoder:=json.NewDecoder(strings.NewReader(string(value)));decoder.DisallowUnknownFields();return decoder.Decode(&decoded)==nil&&len(decoded)>0}
func webAuthnRP(meta RequestMeta)(string,error){if !meta.TLS||meta.Origin==""{return "",ErrForbidden};host,err:=normalizeHost(meta.Host);if err!=nil{return "",ErrForbidden};origin,err:=url.Parse(meta.Origin);if err!=nil||origin.Scheme!="https"||origin.User!=nil||origin.Path!=""||origin.RawQuery!=""||origin.Fragment!=""||!strings.EqualFold(origin.Hostname(),host)||(origin.Port()!=""&&origin.Port()!="443"){return "",ErrForbidden};if !validMailHostname(host){return "",ErrForbidden};return host,nil}

type SiteCreatePayload struct{ProjectID string `json:"project_id"`;PrimaryHostname string `json:"primary_hostname"`;PHPProfile site.PHPProfile `json:"php_profile"`}
type SiteActionPayload struct{Action string `json:"action"`}

func registerHostingContracts(registry *Registry)error{
	create:=Operation{Name:"hosting.site.create",Permission:identity.MustPermission("site:create"),Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &SiteCreatePayload{}},ValidatePayload:func(value any)error{payload:=value.(*SiteCreatePayload);if _,err:=site.NewProjectID(payload.ProjectID);err!=nil{return invalid("project_id")};if _,err:=site.ParseHostname(payload.PrimaryHostname);err!=nil{return invalid("primary_hostname")};if !site.ValidPHPProfile(payload.PHPProfile){return invalid("php_profile")};return nil},ResolveScope:tenantScope}
	if err:=register(registry,create);err!=nil{return err}
	return register(registry,Operation{Name:"hosting.site.lifecycle",Permission:identity.MustPermission("site:manage"),Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &SiteActionPayload{}},ValidatePayload:func(value any)error{switch value.(*SiteActionPayload).Action{case "mark_provisioned","suspend","resume","begin_delete","mark_quarantined","restore","begin_purge","mark_deleted":return nil};return invalid("site action")},ResolveScope:siteScope})
}

func bindHosting(registry *Registry,services DomainServices)error{
	if services.Hosting==nil{return nil}
	if err:=registry.Bind("hosting.site.create",func(ctx context.Context,invocation Invocation,value any)(OperationResult,error){payload:=value.(*SiteCreatePayload);tenant,err:=site.NewTenantID(invocation.Request.TenantID);if err!=nil{return OperationResult{},ErrInvalidRequest};baseCommandID:=commandID(invocation);siteID,err:=site.NewSiteID("site-"+baseCommandID);if err!=nil{return OperationResult{},ErrInvalidRequest};project,_:=site.NewProjectID(payload.ProjectID);hostname,_:=site.ParseHostname(payload.PrimaryHostname);actor:=service.Actor{TenantID:tenant};created,err:=services.Hosting.Handle(ctx,service.CreateSite{CommandID:baseCommandID,Actor:actor,TenantID:tenant,Site:site.CreateInput{ID:siteID,TenantID:tenant,ProjectID:project,PrimaryHostname:hostname,PHPProfile:payload.PHPProfile}});if err!=nil{return OperationResult{},mapHostingError(err)};receipt,err:=services.Hosting.Handle(ctx,service.MarkProvisioned{CommandID:baseCommandID+"_active",Actor:actor,TenantID:tenant,SiteID:siteID,ExpectedGeneration:created.Request.Projection.Generation});if err!=nil{return OperationResult{},mapHostingError(err)};return OperationResult{Status:http.StatusCreated,Value:receipt,Generation:receipt.Request.Projection.Generation},nil});err!=nil{return err}
	return registry.Bind("hosting.site.lifecycle",func(ctx context.Context,invocation Invocation,value any)(OperationResult,error){payload:=value.(*SiteActionPayload);tenant,_:=site.NewTenantID(invocation.Request.TenantID);siteID,_:=site.NewSiteID(invocation.Request.ResourceID);actor:=service.Actor{TenantID:tenant};id:=commandID(invocation);expected:=invocation.Request.ExpectedGeneration;var command service.Command;switch payload.Action{case "mark_provisioned":command=service.MarkProvisioned{CommandID:id,Actor:actor,TenantID:tenant,SiteID:siteID,ExpectedGeneration:expected};case "suspend":command=service.SuspendSite{CommandID:id,Actor:actor,TenantID:tenant,SiteID:siteID,ExpectedGeneration:expected};case "resume":command=service.ResumeSite{CommandID:id,Actor:actor,TenantID:tenant,SiteID:siteID,ExpectedGeneration:expected};case "begin_delete":command=service.BeginDelete{CommandID:id,Actor:actor,TenantID:tenant,SiteID:siteID,ExpectedGeneration:expected};case "mark_quarantined":command=service.MarkQuarantined{CommandID:id,Actor:actor,TenantID:tenant,SiteID:siteID,ExpectedGeneration:expected};case "restore":command=service.RestoreSite{CommandID:id,Actor:actor,TenantID:tenant,SiteID:siteID,ExpectedGeneration:expected};case "begin_purge":command=service.BeginPurge{CommandID:id,Actor:actor,TenantID:tenant,SiteID:siteID,ExpectedGeneration:expected};case "mark_deleted":command=service.MarkDeleted{CommandID:id,Actor:actor,TenantID:tenant,SiteID:siteID,ExpectedGeneration:expected}};receipt,err:=services.Hosting.Handle(ctx,command);if err!=nil{return OperationResult{},mapHostingError(err)};return OperationResult{Status:http.StatusOK,Value:receipt,Generation:receipt.Request.Projection.Generation},nil})
}

func mapHostingError(err error)error{switch{case errors.Is(err,service.ErrUnauthorized):return ErrForbidden;case errors.Is(err,service.ErrNotFound):return ErrNotFound;case errors.Is(err,service.ErrIdempotencyConflict):return ErrIdempotencyConflict;case errors.Is(err,site.ErrStaleGeneration),errors.Is(err,site.ErrInvalidTransition),errors.Is(err,site.ErrDuplicateBinding),errors.Is(err,site.ErrSolePrimary),errors.Is(err,site.ErrRedirectCycle):return ErrConflict;case errors.Is(err,service.ErrInvalidCommand),errors.Is(err,service.ErrInvalidReceipt),errors.Is(err,service.ErrInvalidEffectReceipt),errors.Is(err,site.ErrInvalidAggregate):return ErrInvalidRequest;default:return err}}
