package apiserver

import (
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"net/http"
	"strings"
	"time"

	marketing "github.com/aonsyed/cyberpanel/platform/internal/emailmarketing"
	"github.com/aonsyed/cyberpanel/platform/internal/identity"
	"github.com/aonsyed/cyberpanel/platform/internal/mail"
)

type MarketingListPayload struct{List mail.List `json:"list"`}
type MarketingSubscriberPayload struct{ID mail.ContactID `json:"id,omitempty"`;Address mail.Address `json:"address"`;Name string `json:"name,omitempty"`;Tags string `json:"tags,omitempty"`}
type MarketingSubscriberPagePayload struct{State mail.SubscriberState `json:"state,omitempty"`;Limit uint16 `json:"limit"`;Cursor string `json:"cursor,omitempty"`}
type MarketingVerificationPayload struct{State mail.VerificationState `json:"state"`;EvidenceRef string `json:"evidence_ref"`}
type MarketingTemplatePayload struct{Template mail.CampaignTemplate `json:"template"`;Name string `json:"name,omitempty"`;Text string `json:"text,omitempty"`}
type MarketingCampaignPayload struct{Campaign mail.Campaign `json:"campaign"`;ListID mail.ListID `json:"list_id,omitempty"`;Subject string `json:"subject,omitempty"`;TemplateRef string `json:"template_ref,omitempty"`;FromMailbox mail.MailboxID `json:"from_mailbox,omitempty"`;ReplyTo mail.Address `json:"reply_to,omitempty"`;Schedule string `json:"schedule,omitempty"`}
type MarketingConsentPayload struct{Event mail.ConsentEvent `json:"event"`}
type MarketingAddressPayload struct{Address mail.Address `json:"address"`}
type MarketingUnsubscribePayload struct{Token string `json:"token"`}
type MarketingStatePagePayload struct{Limit uint16 `json:"limit"`;Cursor string `json:"cursor,omitempty"`}
type MarketingAttemptPagePayload struct{CampaignID mail.CampaignID `json:"campaign_id"`;Limit uint16 `json:"limit"`;Cursor string `json:"cursor,omitempty"`}
type MarketingSendPayload struct{CampaignID mail.CampaignID `json:"campaign_id"`;ContactID mail.ContactID `json:"contact_id"`}
type MarketingListPage struct{Items []mail.List `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type MarketingSubscriberPage struct{Items []mail.Subscriber `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type MarketingTemplatePage struct{Items []mail.CampaignTemplate `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type MarketingCampaignPage struct{Items []mail.Campaign `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type MarketingAttemptPage struct{Items []mail.CampaignAttempt `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type MarketingConsentPage struct{Items []mail.ConsentEvent `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type MarketingConsentCurrent struct{Found bool `json:"found"`;Event mail.ConsentEvent `json:"event,omitempty"`}
type MarketingDeliveryEventPayload struct{Source marketing.DeliveryEventSource `json:"source"`;ProviderRef string `json:"provider_ref"`;KeyID string `json:"key_id"`;EventID string `json:"event_id"`;Nonce string `json:"nonce"`;SignedAt time.Time `json:"signed_at"`;PayloadBase64 string `json:"payload_base64"`;SignatureBase64 string `json:"signature_base64"`}
type MarketingMetricsPayload struct{Start time.Time `json:"start,omitempty"`;End time.Time `json:"end,omitempty"`;BucketHours uint16 `json:"bucket_hours,omitempty"`;MaximumBuckets uint16 `json:"maximum_buckets,omitempty"`;MaximumProviders uint8 `json:"maximum_providers,omitempty"`;MinimumReportPopulation uint32 `json:"minimum_report_population,omitempty"`}
type MarketingPolicyPutPayload struct{ExpectedGeneration uint64 `json:"expected_generation"`;MaxRecipientsPerCampaign uint64 `json:"max_recipients_per_campaign"`;MaxRecipientsPerHour uint64 `json:"max_recipients_per_hour"`;MaxRecipientsPerDay uint64 `json:"max_recipients_per_day"`;MaxConcurrentCampaigns uint32 `json:"max_concurrent_campaigns"`;WarmupStartedAt time.Time `json:"warmup_started_at"`;WarmupInitialDailyLimit uint64 `json:"warmup_initial_daily_limit"`;WarmupDoublingHours uint16 `json:"warmup_doubling_hours"`;MinimumApprovals uint8 `json:"minimum_approvals"`;CapacityMaximumAgeSeconds uint32 `json:"capacity_maximum_age_seconds"`;Abuse marketing.AbuseDisposition `json:"abuse"`;AbuseEvidenceDigest string `json:"abuse_evidence_digest"`;LocalAuthorityReady bool `json:"local_authority_ready"`}
type MarketingSenderRefreshPayload struct{ExpectedGeneration uint64 `json:"expected_generation"`;Domain string `json:"domain"`}
type MarketingCapacityPutPayload struct{ExpectedGeneration uint64 `json:"expected_generation"`;ProfileRef string `json:"profile_ref"`;Kind marketing.DeliveryCapacityKind `json:"kind"`;Online bool `json:"online"`;MaximumConcurrency uint32 `json:"maximum_concurrency"`;MaximumRecipientsPerHour uint64 `json:"maximum_recipients_per_hour"`;ReservedTransactionalConcurrency uint32 `json:"reserved_transactional_concurrency"`;ReservedTransactionalPerHour uint64 `json:"reserved_transactional_per_hour"`;ObservedAt time.Time `json:"observed_at"`}
type MarketingAdmissionPayload struct{CampaignRevision uint64 `json:"campaign_revision"`;RecipientCount uint64 `json:"recipient_count"`;DeliveryProfileRef string `json:"delivery_profile_ref"`;VerifiedSenderDomain string `json:"verified_sender_domain"`;SenderEvidenceDigest string `json:"sender_evidence_digest"`;PolicyGeneration uint64 `json:"policy_generation"`;TenantPolicyDigest string `json:"tenant_policy_digest"`;SenderGeneration uint64 `json:"sender_generation"`;CapacityGeneration uint64 `json:"capacity_generation"`;TTLSeconds uint32 `json:"ttl_seconds"`}
type MarketingBackupStartPayload struct{RetentionDays uint32 `json:"retention_days"`;MaximumRecords uint64 `json:"maximum_records"`;MaximumBytes int64 `json:"maximum_bytes"`}
type MarketingRestoreStartPayload struct{SourceJobID string `json:"source_job_id"`;ExpectedActivationGeneration uint64 `json:"expected_activation_generation"`}
type MarketingReconcileStartPayload struct{SourceJobID string `json:"source_job_id"`}
type MarketingDeliveryEventResult struct{Accepted bool `json:"accepted"`;Duplicate bool `json:"duplicate"`;Delayed bool `json:"delayed"`;OutOfOrder bool `json:"out_of_order"`;ReceiptID string `json:"receipt_id,omitempty"`}
type MarketingMetricCounts struct{Denominator uint64 `json:"denominator"`;Queued uint64 `json:"queued"`;Sent uint64 `json:"sent"`;Delivered uint64 `json:"delivered"`;Deferred uint64 `json:"deferred"`;Bounced uint64 `json:"bounced"`;Complained uint64 `json:"complained"`;Suppressed uint64 `json:"suppressed"`;Failed uint64 `json:"failed"`}
type MarketingListMetric struct{ListID string `json:"list_id"`;Denominator uint64 `json:"denominator"`;Counts *MarketingMetricCounts `json:"counts,omitempty"`;SmallCohort bool `json:"small_cohort"`}
type MarketingProviderMetric struct{ProviderRef string `json:"provider_ref"`;Attempts uint64 `json:"attempts"`;Events uint64 `json:"events"`;Counts MarketingMetricCounts `json:"counts"`}
type MarketingMetricBucket struct{Start time.Time `json:"start"`;End time.Time `json:"end"`;Delivered uint64 `json:"delivered"`;Deferred uint64 `json:"deferred"`;Bounced uint64 `json:"bounced"`;Complained uint64 `json:"complained"`;Failed uint64 `json:"failed"`}
type MarketingMetricQuality struct{EventWatermark *time.Time `json:"event_watermark,omitempty"`;LatestReceivedAt *time.Time `json:"latest_received_at,omitempty"`;WatermarkLagSeconds uint64 `json:"watermark_lag_seconds"`;DelayedEvents uint64 `json:"delayed_events"`;OutOfOrderEvents uint64 `json:"out_of_order_events"`;AwaitingReceipts uint64 `json:"awaiting_receipts"`;MissingProviderData bool `json:"missing_provider_data"`;ProviderCardinalityTruncated bool `json:"provider_cardinality_truncated"`}
type MarketingCampaignMetricsResult struct{CampaignID string `json:"campaign_id"`;Counts MarketingMetricCounts `json:"counts"`;Lists []MarketingListMetric `json:"lists"`;Providers []MarketingProviderMetric `json:"providers"`;TimeSeries []MarketingMetricBucket `json:"time_series,omitempty"`;Quality MarketingMetricQuality `json:"quality"`;SmallCohort bool `json:"small_cohort"`;AsOf time.Time `json:"as_of"`}
type MarketingAdmissionResult struct{Admitted bool `json:"admitted"`;Waiting bool `json:"waiting"`;WaitReason string `json:"wait_reason,omitempty"`;Reservation MarketingReservationProjection `json:"reservation,omitempty"`}

func registerMarketingContracts(registry *Registry)error{
	permission:=identity.MustPermission("mail:manage")
	definitions:=[]Operation{
		{Name:"marketing.delivery_event.ingest",Auth:AuthNone,Mutating:true,MaximumBodyBytes:2<<20,NewPayload:func()any{return &MarketingDeliveryEventPayload{}},ValidatePayload:validateMarketingDeliveryEvent,ResolveScope:installationScope},
		{Name:"marketing.campaign.metrics",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingMetricsPayload{}},ValidatePayload:validateMarketingMetrics,ResolveScope:marketingResourceScope},
		{Name:"marketing.policy.status",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:tenantScope},
		{Name:"marketing.policy.put",Permission:permission,Assurance:identity.AssurancePhishingResistant,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingPolicyPutPayload{}},ValidatePayload:validateMarketingPolicyPut,ResolveScope:tenantScope},
		{Name:"marketing.sender.refresh",Permission:permission,Assurance:identity.AssurancePhishingResistant,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingSenderRefreshPayload{}},ValidatePayload:validateMarketingSenderRefresh,ResolveScope:tenantScope},
		{Name:"marketing.capacity.put",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingCapacityPutPayload{}},ValidatePayload:validateMarketingCapacityPut,ResolveScope:tenantScope},
		{Name:"marketing.admission.status",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingResourceScope},
		{Name:"marketing.admission.reserve",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingAdmissionPayload{}},ValidatePayload:validateMarketingAdmission,ResolveScope:marketingResourceScope},
		{Name:"marketing.backup.start",Permission:permission,Assurance:identity.AssurancePhishingResistant,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingBackupStartPayload{}},ValidatePayload:validateMarketingBackupStart,ResolveScope:tenantScope},
		{Name:"marketing.restore.start",Permission:permission,Assurance:identity.AssurancePhishingResistant,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingRestoreStartPayload{}},ValidatePayload:validateMarketingRestoreStart,ResolveScope:tenantScope},
		{Name:"marketing.reconcile.start",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingReconcileStartPayload{}},ValidatePayload:validateMarketingReconcileStart,ResolveScope:tenantScope},
		{Name:"marketing.archive_job.status",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingResourceScope},
		{Name:"marketing.unsubscribe",Auth:AuthNone,Mutating:true,NewPayload:func()any{return &MarketingUnsubscribePayload{}},ValidatePayload:validateMarketingUnsubscribe,ResolveScope:installationScope},
		{Name:"marketing.subscriber.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingSubscriberPagePayload{}},ValidatePayload:validateMarketingSubscriberPage,ResolveScope:mailListScope},
		{Name:"marketing.subscriber.get",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"marketing.subscriber.create",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingSubscriberPayload{}},ValidatePayload:validateMarketingSubscriberCreate,ResolveScope:tenantScope},
		{Name:"marketing.subscriber.update",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingSubscriberPayload{}},ValidatePayload:validateMarketingSubscriber,ResolveScope:marketingCampaignScope},
		{Name:"marketing.subscriber.archive",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.subscriber.restore",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.subscriber.verify",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingVerificationPayload{}},ValidatePayload:validateMarketingVerification,ResolveScope:marketingCampaignScope},
		{Name:"marketing.subscriber.delete",Permission:permission,Assurance:identity.AssurancePhishingResistant,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.list.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingStatePagePayload{}},ValidatePayload:validateMarketingPage,ResolveScope:mailListScope},
		{Name:"marketing.list.get",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"marketing.list.create",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingListPayload{}},ValidatePayload:validateMarketingList,ResolveScope:mailCreateScope},
		{Name:"marketing.list.update",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingListPayload{}},ValidatePayload:validateMarketingList,ResolveScope:marketingResourceScope},
		{Name:"marketing.list.delete",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingResourceScope},
		{Name:"marketing.template.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingStatePagePayload{}},ValidatePayload:validateMarketingPage,ResolveScope:mailListScope},
		{Name:"marketing.template.get",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"marketing.template.create",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingTemplatePayload{}},ValidatePayload:validateMarketingTemplateCreate,ResolveScope:tenantScope},
		{Name:"marketing.template.update",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingTemplatePayload{}},ValidatePayload:validateMarketingTemplate,ResolveScope:marketingCampaignScope},
		{Name:"marketing.template.approve",Permission:permission,Assurance:identity.AssurancePhishingResistant,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.template.archive",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingStatePagePayload{}},ValidatePayload:validateMarketingPage,ResolveScope:mailListScope},
		{Name:"marketing.campaign.get",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"marketing.campaign.snapshot.get",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"marketing.campaign.create",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingCampaignPayload{}},ValidatePayload:validateMarketingCampaignCreate,ResolveScope:tenantScope},
		{Name:"marketing.campaign.update",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingCampaignPayload{}},ValidatePayload:validateMarketingCampaign,ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.delete",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.approve",Permission:permission,Assurance:identity.AssurancePhishingResistant,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.schedule",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.start",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.pause",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.campaign.cancel",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:marketingCampaignScope},
		{Name:"marketing.attempt.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingAttemptPagePayload{}},ValidatePayload:validateMarketingAttemptPage,ResolveScope:marketingAttemptScope},
		{Name:"marketing.attempt.get",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"marketing.attempt.send",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingSendPayload{}},ValidatePayload:validateMarketingSend,ResolveScope:mailCreateScope},
		{Name:"marketing.consent.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingStatePagePayload{}},ValidatePayload:validateMarketingPage,ResolveScope:mailListScope},
		{Name:"marketing.consent.current",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingAddressPayload{}},ValidatePayload:validateMarketingAddress,ResolveScope:mailListScope},
		{Name:"marketing.consent.record",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingConsentPayload{}},ValidatePayload:validateMarketingConsent,ResolveScope:mailCreateScope},
		{Name:"marketing.suppression.list",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingStatePagePayload{}},ValidatePayload:validateMarketingPage,ResolveScope:mailListScope},
		{Name:"marketing.suppression.current",Permission:permission,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MarketingAddressPayload{}},ValidatePayload:validateMarketingAddress,ResolveScope:mailListScope},
		{Name:"marketing.suppression.record",Permission:permission,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MarketingConsentPayload{}},ValidatePayload:validateMarketingSuppression,ResolveScope:mailCreateScope},
	}
	for _,definition:=range definitions{if err:=register(registry,definition);err!=nil{return err}}
	return nil
}

func validateMarketingPage(value any)error{payload:=value.(*MarketingStatePagePayload);if payload.Limit>500||len(payload.Cursor)>1024{return invalid("marketing page")};return nil}
func validateMarketingDeliveryEvent(value any)error{
	payload:=value.(*MarketingDeliveryEventPayload)
	if (payload.Source!=marketing.DeliveryEventProvider&&payload.Source!=marketing.DeliveryEventLocal)||!safeMailOpaque(payload.ProviderRef)||!safeMailOpaque(payload.KeyID)||!safeMailOpaque(payload.EventID)||len(payload.Nonce)<16||len(payload.Nonce)>256||strings.ContainsAny(payload.Nonce,"\x00\r\n\t")||payload.SignedAt.IsZero()||len(payload.PayloadBase64)>2<<20||len(payload.SignatureBase64)>128{return invalid("marketing delivery event")}
	document,documentErr:=base64.RawStdEncoding.DecodeString(payload.PayloadBase64);signature,signatureErr:=base64.RawStdEncoding.DecodeString(payload.SignatureBase64)
	defer clearSecret(document);defer clearSecret(signature)
	if documentErr!=nil||signatureErr!=nil||len(document)==0||len(document)>1<<20||len(signature)!=sha256.Size{return invalid("marketing delivery event")}
	return nil
}
func validateMarketingMetrics(value any)error{
	payload:=value.(*MarketingMetricsPayload)
	if payload.Start.IsZero()!=payload.End.IsZero()||!payload.Start.IsZero()&&!payload.End.After(payload.Start)||payload.BucketHours>24||payload.MaximumBuckets>168||payload.MaximumProviders>32||payload.MinimumReportPopulation!=0&&payload.MinimumReportPopulation<10||payload.MinimumReportPopulation>100000{return invalid("marketing metrics")}
	return nil
}
func validateMarketingPolicyPut(value any)error{
	payload:=value.(*MarketingPolicyPutPayload)
	if payload.MaxRecipientsPerCampaign==0||payload.MaxRecipientsPerHour<payload.MaxRecipientsPerCampaign||payload.MaxRecipientsPerDay<payload.MaxRecipientsPerHour||payload.MaxConcurrentCampaigns==0||payload.WarmupStartedAt.IsZero()||payload.WarmupInitialDailyLimit==0||payload.WarmupInitialDailyLimit>payload.MaxRecipientsPerDay||payload.WarmupDoublingHours<24||payload.WarmupDoublingHours>720||payload.MinimumApprovals==0||payload.MinimumApprovals>8||payload.CapacityMaximumAgeSeconds<60||payload.CapacityMaximumAgeSeconds>86400||!validMarketingDigest(payload.AbuseEvidenceDigest)||(payload.Abuse!=marketing.AbuseClear&&payload.Abuse!=marketing.AbuseReview&&payload.Abuse!=marketing.AbuseBlock){return invalid("marketing policy")}
	return nil
}
func validateMarketingSenderRefresh(value any)error{payload:=value.(*MarketingSenderRefreshPayload);payload.Domain=strings.TrimSuffix(strings.ToLower(strings.TrimSpace(payload.Domain)),".");if !validMailHostname(payload.Domain){return invalid("marketing sender")};return nil}
func validateMarketingCapacityPut(value any)error{
	payload:=value.(*MarketingCapacityPutPayload)
	if !safeMailOpaque(payload.ProfileRef)||(payload.Kind!=marketing.CapacityLocal&&payload.Kind!=marketing.CapacityProvider)||payload.MaximumConcurrency==0||payload.MaximumRecipientsPerHour==0||payload.ReservedTransactionalConcurrency>=payload.MaximumConcurrency||payload.ReservedTransactionalPerHour>=payload.MaximumRecipientsPerHour||payload.ObservedAt.IsZero()||payload.ObservedAt.After(time.Now().UTC().Add(time.Minute)){return invalid("marketing capacity")}
	return nil
}
func validateMarketingAdmission(value any)error{
	payload:=value.(*MarketingAdmissionPayload)
	payload.VerifiedSenderDomain=strings.TrimSuffix(strings.ToLower(strings.TrimSpace(payload.VerifiedSenderDomain)),".")
	if payload.CampaignRevision==0||payload.RecipientCount==0||!safeMailOpaque(payload.DeliveryProfileRef)||!validMailHostname(payload.VerifiedSenderDomain)||!validMarketingDigest(payload.SenderEvidenceDigest)||payload.PolicyGeneration==0||!validMarketingDigest(payload.TenantPolicyDigest)||payload.SenderGeneration==0||payload.CapacityGeneration==0||payload.TTLSeconds<60||payload.TTLSeconds>86400{return invalid("marketing admission")}
	return nil
}
func validateMarketingBackupStart(value any)error{payload:=value.(*MarketingBackupStartPayload);if payload.RetentionDays==0||payload.RetentionDays>3650||payload.MaximumRecords==0||payload.MaximumRecords>100000000||payload.MaximumBytes<1024||payload.MaximumBytes>1<<40{return invalid("marketing backup")};return nil}
func validateMarketingRestoreStart(value any)error{payload:=value.(*MarketingRestoreStartPayload);if !safeMailOpaque(payload.SourceJobID)||payload.ExpectedActivationGeneration!=0{return invalid("marketing restore")};return nil}
func validateMarketingReconcileStart(value any)error{if !safeMailOpaque(value.(*MarketingReconcileStartPayload).SourceJobID){return invalid("marketing reconcile")};return nil}
func validMarketingDigest(value string)bool{if len(value)!=sha256.Size*2{return false};_,err:=hex.DecodeString(value);return err==nil&&value==strings.ToLower(value)}
func validateMarketingUnsubscribe(value any)error{token:=value.(*MarketingUnsubscribePayload).Token;if len(token)<32||len(token)>4096||strings.ContainsAny(token,"\x00\r\n\t "){return invalid("unsubscribe token")};return nil}
func validateMarketingSubscriberCreate(value any)error{return validateMarketingSubscriberPayload(value.(*MarketingSubscriberPayload),true)}
func validateMarketingSubscriber(value any)error{return validateMarketingSubscriberPayload(value.(*MarketingSubscriberPayload),false)}
func validateMarketingSubscriberPayload(payload *MarketingSubscriberPayload,allowGeneratedID bool)error{if (!allowGeneratedID||payload.ID!="")&&!safeMailOpaque(string(payload.ID))||!safeMailAddress(payload.Address)||len(payload.Name)>256||strings.ContainsAny(payload.Name,"\x00\r\n"){return invalid("marketing subscriber")};if _,err:=marketingSubscriberTags(payload.Tags);err!=nil{return err};return nil}
func validateMarketingSubscriberPage(value any)error{payload:=value.(*MarketingSubscriberPagePayload);if payload.State!=""&&payload.State!=mail.SubscriberActive&&payload.State!=mail.SubscriberArchived||payload.Limit>500||len(payload.Cursor)>1024{return invalid("marketing subscriber page")};return nil}
func validateMarketingVerification(value any)error{payload:=value.(*MarketingVerificationPayload);switch payload.State{case mail.VerificationVerified,mail.VerificationInvalid,mail.VerificationRisky,mail.VerificationUnknown:default:return invalid("marketing verification state")};if !safeMailOpaque(payload.EvidenceRef){return invalid("marketing verification evidence")};return nil}
func validateMarketingList(value any)error{list:=value.(*MarketingListPayload).List;if !safeMailOpaque(string(list.ID))||strings.TrimSpace(list.Name)==""||len(list.Name)>256||strings.ContainsAny(list.Name,"\x00\r\n")||len(list.Contacts)>100000{return invalid("marketing list")};seen:=map[mail.ContactID]bool{};for _,contact:=range list.Contacts{if !safeMailOpaque(string(contact))||seen[contact]{return invalid("marketing list contact")};seen[contact]=true};return nil}
func validateMarketingTemplateCreate(value any)error{return validateMarketingTemplatePayload(value.(*MarketingTemplatePayload),true)}
func validateMarketingTemplate(value any)error{return validateMarketingTemplatePayload(value.(*MarketingTemplatePayload),false)}
func validateMarketingTemplatePayload(payload *MarketingTemplatePayload,allowGeneratedID bool)error{nested:=payload.Template.ID!=""||payload.Template.Name!=""||payload.Template.Text!=""||payload.Template.State!=""||payload.Template.Generation!=0||!payload.Template.UpdatedAt.IsZero();flat:=payload.Name!=""||payload.Text!="";if nested&&flat{return invalid("marketing template shape")};if flat{payload.Template=mail.CampaignTemplate{Name:payload.Name,Text:payload.Text}};template:=payload.Template;if ((!allowGeneratedID&&!flat)||template.ID!="")&&!safeMailOpaque(string(template.ID))||strings.TrimSpace(template.Name)==""||len(template.Name)>256||strings.ContainsAny(template.Name,"\x00\r\n")||template.Text==""||len(template.Text)>8<<20||strings.ContainsRune(template.Text,'\x00'){return invalid("marketing template")};return nil}
func validateMarketingCampaignCreate(value any)error{return normalizeMarketingCampaign(value.(*MarketingCampaignPayload),true)}
func validateMarketingCampaign(value any)error{return normalizeMarketingCampaign(value.(*MarketingCampaignPayload),false)}
func normalizeMarketingCampaign(payload *MarketingCampaignPayload,allowGeneratedID bool)error{nested:=payload.Campaign.ID!=""||payload.Campaign.List!=""||payload.Campaign.Subject!=""||payload.Campaign.TemplateRef!=""||payload.Campaign.FromMailbox!=""||payload.Campaign.ReplyTo!=""||payload.Campaign.Schedule!=""||payload.Campaign.SnapshotRef!=""||payload.Campaign.RecipientCount!=0||payload.Campaign.ApprovedAt!=nil||payload.Campaign.ApprovedBy!=""||payload.Campaign.State!=""||payload.Campaign.Generation!=0;flat:=payload.ListID!=""||payload.Subject!=""||payload.TemplateRef!=""||payload.FromMailbox!=""||payload.ReplyTo!=""||payload.Schedule!="";if nested&&flat{return invalid("marketing campaign shape")};if flat{payload.Campaign=mail.Campaign{List:payload.ListID,Subject:payload.Subject,TemplateRef:payload.TemplateRef,FromMailbox:payload.FromMailbox,ReplyTo:payload.ReplyTo,Schedule:payload.Schedule}};campaign:=payload.Campaign;normalizedSchedule,scheduleErr:=mail.NormalizeCampaignSchedule(campaign.Schedule);if scheduleErr!=nil{return invalid("marketing campaign schedule")};campaign.Schedule=normalizedSchedule;payload.Campaign=campaign;if ((!allowGeneratedID&&!flat)||campaign.ID!="")&&!safeMailOpaque(string(campaign.ID))||!safeMailOpaque(string(campaign.List))||strings.TrimSpace(campaign.Subject)==""||len(campaign.Subject)>998||strings.ContainsAny(campaign.Subject,"\x00\r\n")||!safeMailOpaque(campaign.TemplateRef)||!safeMailOpaque(string(campaign.FromMailbox))||campaign.ReplyTo!=""&&!safeMailAddress(campaign.ReplyTo){return invalid("marketing campaign")};return nil}
func validateMarketingConsent(value any)error{return validateMarketingEvent(value.(*MarketingConsentPayload).Event,mail.Consented)}
func validateMarketingSuppression(value any)error{return validateMarketingEvent(value.(*MarketingConsentPayload).Event,mail.Suppressed)}
func validateMarketingEvent(event mail.ConsentEvent,state mail.ConsentState)error{now:=time.Now().UTC();if !safeMailOpaque(event.ID)||!safeMailOpaque(string(event.ContactID))||!safeMailAddress(event.Address)||event.State!=state||!safeMailOpaque(event.EvidenceRef)||event.At.Before(now.Add(-10*365*24*time.Hour))||event.At.After(now.Add(5*time.Minute)){return invalid("marketing consent event")};if state==mail.Consented{switch event.ConsentReason{case mail.ConsentOptIn,mail.ConsentResubscribe,mail.ConsentImport:default:return invalid("marketing consent reason")};if event.SuppressionReason!=""{return invalid("marketing consent state")}}else{switch event.SuppressionReason{case mail.SuppressionUnsubscribe,mail.SuppressionComplaint,mail.SuppressionGlobalDNC,mail.SuppressionHardBounce,mail.SuppressionTransient,mail.SuppressionAdministrative:default:return invalid("marketing suppression reason")};if event.ConsentReason!=""{return invalid("marketing suppression state")}};return nil}
func validateMarketingAddress(value any)error{if !safeMailAddress(value.(*MarketingAddressPayload).Address){return invalid("marketing address")};return nil}
func validateMarketingAttemptPage(value any)error{payload:=value.(*MarketingAttemptPagePayload);if payload.CampaignID!=""&&!safeMailOpaque(string(payload.CampaignID))||payload.Limit>500||len(payload.Cursor)>1024{return invalid("marketing attempts")};return nil}
func validateMarketingSend(value any)error{payload:=value.(*MarketingSendPayload);if !safeMailOpaque(string(payload.CampaignID))||!safeMailOpaque(string(payload.ContactID)){return invalid("marketing attempt")};return nil}
func marketingResourceScope(request RequestEnvelope,value any)(identity.Scope,error){if !safeMailOpaque(request.ResourceID)||request.ExpectedGeneration!=0{return identity.Scope{},invalid("marketing resource scope")};return tenantScope(request,value)}
func marketingCampaignScope(request RequestEnvelope,value any)(identity.Scope,error){if !safeMailOpaque(request.ResourceID)||request.ExpectedGeneration==0{return identity.Scope{},invalid("marketing campaign generation")};return tenantScope(request,value)}
func marketingAttemptScope(request RequestEnvelope,value any)(identity.Scope,error){payload:=value.(*MarketingAttemptPagePayload);resource:=request.ResourceID;if resource==""{resource=string(payload.CampaignID)};if !safeMailOpaque(resource)||request.ExpectedGeneration!=0{return identity.Scope{},invalid("marketing campaign scope")};if payload.CampaignID!=""&&string(payload.CampaignID)!=resource{return identity.Scope{},invalid("marketing campaign identity")};return tenantScope(request,value)}

func bindMarketing(registry *Registry,services DomainServices)error{
	if services.Unsubscribe!=nil{if err:=registry.Bind("marketing.unsubscribe",func(ctx context.Context,_ Invocation,value any)(OperationResult,error){event,err:=services.Unsubscribe.Honor(ctx,value.(*MarketingUnsubscribePayload).Token);value.(*MarketingUnsubscribePayload).Token="";if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]any{"status":"unsubscribed","at":event.At}},nil});err!=nil{return err}}
	if services.Marketing!=nil{
		if err:=registry.Bind("marketing.subscriber.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MarketingSubscriberPagePayload);items,next,err:=services.Marketing.Subscribers(ctx,inv.Request.TenantID,page.State,int(page.Limit),page.Cursor);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:MarketingSubscriberPage{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.subscriber.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){item,found,err:=services.Marketing.Subscriber(ctx,inv.Request.TenantID,mail.ContactID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};return OperationResult{Status:http.StatusOK,Value:item,Generation:item.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.subscriber.create",marketingSubscriberWriter(services.Marketing,true));err!=nil{return err}
		if err:=registry.Bind("marketing.subscriber.update",marketingSubscriberWriter(services.Marketing,false));err!=nil{return err}
		for operation,target:=range map[string]mail.SubscriberState{"marketing.subscriber.archive":mail.SubscriberArchived,"marketing.subscriber.restore":mail.SubscriberActive}{operation,target:=operation,target;if err:=registry.Bind(operation,func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){updated,err:=services.Marketing.SetSubscriberState(ctx,inv.Request.TenantID,mail.ContactID(inv.Request.ResourceID),inv.Request.ExpectedGeneration,target);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:updated,Generation:updated.Generation},nil});err!=nil{return err}}
		if err:=registry.Bind("marketing.subscriber.verify",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*MarketingVerificationPayload);updated,err:=services.Marketing.RecordSubscriberVerification(ctx,inv.Request.TenantID,mail.ContactID(inv.Request.ResourceID),inv.Request.ExpectedGeneration,payload.State,payload.EvidenceRef);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:updated,Generation:updated.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.subscriber.delete",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){if err:=services.Marketing.DeleteSubscriberGeneration(ctx,inv.Request.TenantID,mail.ContactID(inv.Request.ResourceID),inv.Request.ExpectedGeneration);err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"deleted"}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.list.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MarketingStatePagePayload);items,next,err:=services.Marketing.Lists(ctx,inv.Request.TenantID,int(page.Limit),page.Cursor);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:MarketingListPage{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.list.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){item,found,err:=services.Marketing.ListByID(ctx,inv.Request.TenantID,mail.ListID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};return OperationResult{Status:http.StatusOK,Value:item},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.list.create",marketingListWriter(services.Marketing,true));err!=nil{return err}
		if err:=registry.Bind("marketing.list.update",marketingListWriter(services.Marketing,false));err!=nil{return err}
		if err:=registry.Bind("marketing.list.delete",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){if err:=services.Marketing.DeleteList(ctx,inv.Request.TenantID,mail.ListID(inv.Request.ResourceID));err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"deleted"}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.template.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MarketingStatePagePayload);items,next,err:=services.Marketing.Templates(ctx,inv.Request.TenantID,int(page.Limit),page.Cursor);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:MarketingTemplatePage{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.template.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){item,found,err:=services.Marketing.LatestTemplate(ctx,inv.Request.TenantID,mail.CampaignTemplateID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};return OperationResult{Status:http.StatusOK,Value:item,Generation:item.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.template.create",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){template:=value.(*MarketingTemplatePayload).Template;if template.ID==""{template.ID=mail.CampaignTemplateID(effectID(inv))};if inv.Request.ResourceID!=""&&string(template.ID)!=inv.Request.ResourceID{return OperationResult{},invalid("marketing template identity")};created,err:=services.Marketing.CreateTemplate(ctx,inv.Request.TenantID,template);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusCreated,Value:created,Generation:created.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.template.update",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){template:=value.(*MarketingTemplatePayload).Template;if template.ID==""{template.ID=mail.CampaignTemplateID(inv.Request.ResourceID)};if string(template.ID)!=inv.Request.ResourceID{return OperationResult{},invalid("marketing template identity")};updated,err:=services.Marketing.ReviseTemplate(ctx,inv.Request.TenantID,template,inv.Request.ExpectedGeneration);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:updated,Generation:updated.Generation},nil});err!=nil{return err}
		for operation,target:=range map[string]string{"marketing.template.approve":"approved","marketing.template.archive":"archived"}{operation,target:=operation,target;if err:=registry.Bind(operation,func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){updated,err:=services.Marketing.SetTemplateState(ctx,inv.Request.TenantID,mail.CampaignTemplateID(inv.Request.ResourceID),inv.Request.ExpectedGeneration,target);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]any{"template":updated,"reference":mail.CampaignTemplateReference(updated)},Generation:updated.Generation},nil});err!=nil{return err}}
		if err:=registry.Bind("marketing.campaign.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MarketingStatePagePayload);items,next,err:=services.Marketing.Campaigns(ctx,inv.Request.TenantID,int(page.Limit),page.Cursor);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:MarketingCampaignPage{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.campaign.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){item,found,err:=services.Marketing.Campaign(ctx,inv.Request.TenantID,mail.CampaignID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};return OperationResult{Status:http.StatusOK,Value:item},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.campaign.snapshot.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){campaign,found,err:=services.Marketing.Campaign(ctx,inv.Request.TenantID,mail.CampaignID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};snapshot,found,err:=services.Marketing.CampaignSnapshot(ctx,inv.Request.TenantID,campaign);if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};return OperationResult{Status:http.StatusOK,Value:snapshot},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.campaign.create",marketingCampaignWriter(services.Marketing,true));err!=nil{return err}
		if err:=registry.Bind("marketing.campaign.update",marketingCampaignWriter(services.Marketing,false));err!=nil{return err}
		if err:=registry.Bind("marketing.campaign.delete",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){if err:=services.Marketing.DeleteCampaignGeneration(ctx,inv.Request.TenantID,mail.CampaignID(inv.Request.ResourceID),inv.Request.ExpectedGeneration);err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"deleted"}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.campaign.approve",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){campaign,snapshot,err:=services.Marketing.ApproveCampaign(ctx,inv.Request.TenantID,mail.CampaignID(inv.Request.ResourceID),inv.Request.ExpectedGeneration,inv.Actor.PrincipalID.String());if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]any{"campaign":campaign,"snapshot":snapshot},Generation:campaign.Generation},nil});err!=nil{return err}
		for operation,target:=range map[string]string{"marketing.campaign.schedule":"scheduled","marketing.campaign.start":"running","marketing.campaign.pause":"paused","marketing.campaign.cancel":"cancelled"}{operation,target:=operation,target;if err:=registry.Bind(operation,marketingCampaignTransition(services.Marketing,target));err!=nil{return err}}
		if err:=registry.Bind("marketing.attempt.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MarketingAttemptPagePayload);campaign:=page.CampaignID;if campaign==""{campaign=mail.CampaignID(inv.Request.ResourceID)};items,next,err:=services.Marketing.Attempts(ctx,inv.Request.TenantID,campaign,int(page.Limit),page.Cursor);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:MarketingAttemptPage{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.attempt.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){attempt,found,err:=services.Marketing.Attempt(ctx,inv.Request.TenantID,mail.AttemptID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};return OperationResult{Status:http.StatusOK,Value:attempt},nil});err!=nil{return err}
		if err:=registry.Bind("marketing.consent.list",marketingConsentList(services.Marketing,mail.Consented));err!=nil{return err}
		if err:=registry.Bind("marketing.suppression.list",marketingConsentList(services.Marketing,mail.Suppressed));err!=nil{return err}
		if err:=registry.Bind("marketing.consent.current",marketingCurrentConsent(services.Marketing,false));err!=nil{return err}
		if err:=registry.Bind("marketing.suppression.current",marketingCurrentConsent(services.Marketing,true));err!=nil{return err}
		if err:=registry.Bind("marketing.consent.record",marketingConsentWriter(services.Marketing,mail.Consented));err!=nil{return err}
		if err:=registry.Bind("marketing.suppression.record",marketingConsentWriter(services.Marketing,mail.Suppressed));err!=nil{return err}
	}
	if services.Campaigns!=nil{if err:=registry.Bind("marketing.attempt.send",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*MarketingSendPayload);campaign,found,err:=services.Campaigns.Store.Campaign(ctx,inv.Request.TenantID,payload.CampaignID);if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};recipient,found,err:=services.Campaigns.Store.CampaignRecipient(ctx,inv.Request.TenantID,campaign,payload.ContactID);if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrForbidden};sum:=sha256.Sum256([]byte(inv.Request.TenantID+"\x00"+inv.Actor.PrincipalID.String()+"\x00"+inv.IdempotencyKey));attempt:=mail.CampaignAttempt{ID:mail.AttemptID(inv.Request.ResourceID),TenantID:inv.Request.TenantID,CampaignID:campaign.ID,ContactID:recipient.ContactID,Address:recipient.Address,IdempotencyKey:"api_"+hex.EncodeToString(sum[:])};result,err:=services.Campaigns.SendOne(ctx,inv.Request.TenantID,campaign,recipient,attempt);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusAccepted,Value:result},nil});err!=nil{return err}}
	if services.EmailMarketing!=nil{return bindEmailMarketingOperations(registry,services.EmailMarketing)}
	return nil
}

func bindEmailMarketingOperations(registry *Registry,operations *EmailMarketingOperations)error{
	if err:=registry.Bind("marketing.delivery_event.ingest",func(ctx context.Context,_ Invocation,value any)(OperationResult,error){
		payload:=value.(*MarketingDeliveryEventPayload)
		document,documentErr:=base64.RawStdEncoding.DecodeString(payload.PayloadBase64);signature,signatureErr:=base64.RawStdEncoding.DecodeString(payload.SignatureBase64)
		payload.PayloadBase64="";payload.SignatureBase64=""
		defer clearSecret(document);defer clearSecret(signature)
		if documentErr!=nil||signatureErr!=nil{return OperationResult{},ErrInvalidRequest}
		result,err:=operations.IngestDeliveryEvent(ctx,marketing.SignedDeliveryEvent{Source:payload.Source,ProviderRef:payload.ProviderRef,KeyID:payload.KeyID,EventID:payload.EventID,Nonce:payload.Nonce,SignedAt:payload.SignedAt,Payload:document,Signature:signature})
		if err!=nil{return OperationResult{},mapEmailMarketingError(err)}
		status:=http.StatusAccepted;if result.Duplicate{status=http.StatusOK}
		return OperationResult{Status:status,Value:MarketingDeliveryEventResult{Accepted:result.Accepted,Duplicate:result.Duplicate,Delayed:result.Delayed,OutOfOrder:result.OutOfOrder,ReceiptID:result.ReceiptID}},nil
	});err!=nil{return err}
	if err:=registry.Bind("marketing.campaign.metrics",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){
		payload:=value.(*MarketingMetricsPayload);end:=payload.End;if end.IsZero(){end=time.Now().UTC()};start:=payload.Start;if start.IsZero(){start=end.Add(-24*time.Hour)};bucketHours:=payload.BucketHours;if bucketHours==0{bucketHours=1};maximumBuckets:=payload.MaximumBuckets;if maximumBuckets==0{maximumBuckets=168};maximumProviders:=payload.MaximumProviders;if maximumProviders==0{maximumProviders=16};minimumPopulation:=payload.MinimumReportPopulation;if minimumPopulation==0{minimumPopulation=10}
		snapshot,err:=operations.CampaignMetrics(ctx,inv,marketing.CampaignID(inv.Request.ResourceID),marketing.CampaignMetricsQuery{Start:start,End:end,BucketWidth:time.Duration(bucketHours)*time.Hour,MaximumBuckets:int(maximumBuckets),MaximumProviders:int(maximumProviders),MinimumReportPopulation:uint64(minimumPopulation)})
		if err!=nil{return OperationResult{},mapEmailMarketingError(err)}
		return OperationResult{Status:http.StatusOK,Value:projectMarketingMetrics(snapshot)},nil
	});err!=nil{return err}
	if err:=registry.Bind("marketing.policy.status",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){status,err:=operations.PolicyStatus(ctx,inv);if err!=nil{return OperationResult{},mapEmailMarketingError(err)};generation:=uint64(0);if status.Policy!=nil{generation=status.Policy.Generation};return OperationResult{Status:http.StatusOK,Value:status,Generation:generation},nil});err!=nil{return err}
	if err:=registry.Bind("marketing.policy.put",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){
		payload:=value.(*MarketingPolicyPutPayload);expected,err:=marketingExpectedGeneration(inv.Request.ExpectedGeneration,payload.ExpectedGeneration);if err!=nil{return OperationResult{},err};now:=time.Now().UTC()
		policy:=marketing.TenantCampaignPolicy{TenantID:marketing.TenantID(inv.Request.TenantID),Generation:expected+1,MaxRecipientsPerCampaign:payload.MaxRecipientsPerCampaign,MaxRecipientsPerHour:payload.MaxRecipientsPerHour,MaxRecipientsPerDay:payload.MaxRecipientsPerDay,MaxConcurrentCampaigns:payload.MaxConcurrentCampaigns,WarmupStartedAt:payload.WarmupStartedAt,WarmupInitialDailyLimit:payload.WarmupInitialDailyLimit,WarmupDoublingPeriod:time.Duration(payload.WarmupDoublingHours)*time.Hour,MinimumApprovals:payload.MinimumApprovals,CapacityMaximumAge:time.Duration(payload.CapacityMaximumAgeSeconds)*time.Second,Abuse:payload.Abuse,AbuseEvidenceDigest:payload.AbuseEvidenceDigest,LocalAuthorityReady:payload.LocalAuthorityReady,UpdatedAt:now}
		status,err:=operations.PutPolicy(ctx,inv,policy,expected);if err!=nil{return OperationResult{},mapEmailMarketingError(err)}
		return OperationResult{Status:http.StatusOK,Value:status,Generation:policy.Generation},nil
	});err!=nil{return err}
	if err:=registry.Bind("marketing.sender.refresh",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*MarketingSenderRefreshPayload);expected,err:=marketingExpectedGeneration(inv.Request.ExpectedGeneration,payload.ExpectedGeneration);if err!=nil{return OperationResult{},err};status,err:=operations.RefreshSender(ctx,inv,payload.Domain,expected);if err!=nil{return OperationResult{},mapEmailMarketingError(err)};generation:=expected+1;return OperationResult{Status:http.StatusOK,Value:status,Generation:generation},nil});err!=nil{return err}
	if err:=registry.Bind("marketing.capacity.put",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){
		payload:=value.(*MarketingCapacityPutPayload);expected,err:=marketingExpectedGeneration(inv.Request.ExpectedGeneration,payload.ExpectedGeneration);if err!=nil{return OperationResult{},err};updatedAt:=time.Now().UTC();if payload.ObservedAt.After(updatedAt){updatedAt=payload.ObservedAt}
		capacity:=marketing.CampaignDeliveryCapacity{TenantID:marketing.TenantID(inv.Request.TenantID),ProfileRef:payload.ProfileRef,Generation:expected+1,Kind:payload.Kind,Online:payload.Online,MaximumConcurrency:payload.MaximumConcurrency,MaximumRecipientsPerHour:payload.MaximumRecipientsPerHour,ReservedTransactionalConcurrency:payload.ReservedTransactionalConcurrency,ReservedTransactionalPerHour:payload.ReservedTransactionalPerHour,ObservedAt:payload.ObservedAt,UpdatedAt:updatedAt}
		status,err:=operations.PutCapacity(ctx,inv,capacity,expected);if err!=nil{return OperationResult{},mapEmailMarketingError(err)}
		return OperationResult{Status:http.StatusOK,Value:status,Generation:capacity.Generation},nil
	});err!=nil{return err}
	if err:=registry.Bind("marketing.admission.status",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){status,err:=operations.AdmissionStatus(ctx,inv,marketing.CampaignID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapEmailMarketingError(err)};return OperationResult{Status:http.StatusOK,Value:status},nil});err!=nil{return err}
	if err:=registry.Bind("marketing.admission.reserve",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){
		payload:=value.(*MarketingAdmissionPayload);now:=time.Now().UTC();result,err:=operations.ReserveAdmission(ctx,inv,marketing.CampaignAdmissionRequest{TenantID:marketing.TenantID(inv.Request.TenantID),CampaignID:marketing.CampaignID(inv.Request.ResourceID),CampaignRevision:payload.CampaignRevision,ReservationID:effectID(inv),RecipientCount:payload.RecipientCount,DeliveryProfileRef:payload.DeliveryProfileRef,VerifiedSenderDomain:strings.ToLower(payload.VerifiedSenderDomain),SenderEvidenceDigest:payload.SenderEvidenceDigest,PolicyGeneration:payload.PolicyGeneration,TenantPolicyDigest:payload.TenantPolicyDigest,SenderGeneration:payload.SenderGeneration,CapacityGeneration:payload.CapacityGeneration,AllowFallback:false,RequestedAt:now,ExpiresAt:now.Add(time.Duration(payload.TTLSeconds)*time.Second)})
		if err!=nil{return OperationResult{},mapEmailMarketingError(err)}
		projection:=MarketingAdmissionResult{Admitted:result.Admitted,Waiting:result.Waiting,WaitReason:result.WaitReason};if result.Reservation.ID!=""{projection.Reservation=projectMarketingReservation(result.Reservation)}
		return OperationResult{Status:http.StatusAccepted,Value:projection},nil
	});err!=nil{return err}
	if err:=registry.Bind("marketing.backup.start",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*MarketingBackupStartPayload);job,err:=operations.StartBackup(ctx,inv,payload.RetentionDays,payload.MaximumRecords,payload.MaximumBytes);if err!=nil{return OperationResult{},mapEmailMarketingError(err)};return OperationResult{Status:http.StatusAccepted,Value:job,Generation:job.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("marketing.restore.start",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*MarketingRestoreStartPayload);job,err:=operations.StartRestore(ctx,inv,payload.SourceJobID,payload.ExpectedActivationGeneration);if err!=nil{return OperationResult{},mapEmailMarketingError(err)};return OperationResult{Status:http.StatusAccepted,Value:job,Generation:job.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("marketing.reconcile.start",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){job,err:=operations.StartReconcile(ctx,inv,value.(*MarketingReconcileStartPayload).SourceJobID);if err!=nil{return OperationResult{},mapEmailMarketingError(err)};return OperationResult{Status:http.StatusAccepted,Value:job,Generation:job.Generation},nil});err!=nil{return err}
	return registry.Bind("marketing.archive_job.status",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){job,err:=operations.ArchiveJob(ctx,inv,inv.Request.ResourceID);if err!=nil{return OperationResult{},mapEmailMarketingError(err)};return OperationResult{Status:http.StatusOK,Value:job,Generation:job.Generation},nil})
}

func marketingExpectedGeneration(envelope,payload uint64)(uint64,error){if envelope!=0&&payload!=0&&envelope!=payload{return 0,ErrConflict};if envelope!=0{return envelope,nil};return payload,nil}

func projectMarketingMetrics(snapshot marketing.CampaignMetricsSnapshot)MarketingCampaignMetricsResult{
	result:=MarketingCampaignMetricsResult{CampaignID:string(snapshot.CampaignID),Counts:projectMarketingCounts(snapshot.Counts),Lists:make([]MarketingListMetric,0,len(snapshot.Lists)),Providers:make([]MarketingProviderMetric,0,len(snapshot.Providers)),Quality:MarketingMetricQuality{EventWatermark:snapshot.Quality.EventWatermark,LatestReceivedAt:snapshot.Quality.LatestReceivedAt,WatermarkLagSeconds:uint64(snapshot.Quality.WatermarkLag/time.Second),DelayedEvents:snapshot.Quality.DelayedEvents,OutOfOrderEvents:snapshot.Quality.OutOfOrderEvents,AwaitingReceipts:snapshot.Quality.AwaitingReceipts,MissingProviderData:snapshot.Quality.MissingProviderData,ProviderCardinalityTruncated:snapshot.Quality.ProviderCardinalityTruncated},SmallCohort:snapshot.SmallCohort,AsOf:snapshot.AsOf}
	for _,metric:=range snapshot.Lists{projected:=MarketingListMetric{ListID:string(metric.ListID),Denominator:metric.Counts.Denominator,SmallCohort:metric.SmallCohort};if !metric.SmallCohort{counts:=projectMarketingCounts(metric.Counts);projected.Counts=&counts};result.Lists=append(result.Lists,projected)}
	for _,metric:=range snapshot.Providers{result.Providers=append(result.Providers,MarketingProviderMetric{ProviderRef:metric.ProviderRef,Attempts:metric.Attempts,Events:metric.Events,Counts:MarketingMetricCounts{Denominator:metric.Attempts,Queued:metric.Queued,Sent:metric.Sent,Delivered:metric.Delivered,Deferred:metric.Deferred,Bounced:metric.Bounced,Complained:metric.Complained,Suppressed:metric.Suppressed,Failed:metric.Failed}})}
	if !snapshot.SmallCohort{result.TimeSeries=make([]MarketingMetricBucket,0,len(snapshot.TimeSeries));for _,bucket:=range snapshot.TimeSeries{result.TimeSeries=append(result.TimeSeries,MarketingMetricBucket{Start:bucket.Start,End:bucket.End,Delivered:bucket.Delivered,Deferred:bucket.Deferred,Bounced:bucket.Bounced,Complained:bucket.Complained,Failed:bucket.Failed})}}
	return result
}

func projectMarketingCounts(counts marketing.DeliveryStateCounts)MarketingMetricCounts{return MarketingMetricCounts{Denominator:counts.Denominator,Queued:counts.Queued,Sent:counts.Sent,Delivered:counts.Delivered,Deferred:counts.Deferred,Bounced:counts.Bounced,Complained:counts.Complained,Suppressed:counts.Suppressed,Failed:counts.Failed}}

func mapEmailMarketingError(err error)error{
	switch{
	case err==nil:return nil
	case errors.Is(err,marketing.ErrInvalid):return ErrInvalidRequest
	case errors.Is(err,marketing.ErrUnauthorized),errors.Is(err,marketing.ErrDeliveryEventRejected),errors.Is(err,marketing.ErrCampaignAbuseBlocked):return ErrForbidden
	case errors.Is(err,marketing.ErrNotFound):return ErrNotFound
	case errors.Is(err,marketing.ErrConflict),errors.Is(err,marketing.ErrStale),errors.Is(err,marketing.ErrIntegrity):return ErrConflict
	case errors.Is(err,marketing.ErrCampaignAdmissionWaiting):return ErrUnavailable
	default:return err
	}
}

func marketingListWriter(store *mail.MarketingStore,create bool)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){list:=value.(*MarketingListPayload).List;if string(list.ID)!=inv.Request.ResourceID{return OperationResult{},invalid("marketing list identity")};_,found,err:=store.ListByID(ctx,inv.Request.TenantID,list.ID);if err!=nil{return OperationResult{},mapMailError(err)};if create&&found||!create&&!found{return OperationResult{},ErrConflict};if err=store.PutList(ctx,inv.Request.TenantID,list);err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:list},nil}}
func marketingSubscriberWriter(store *mail.MarketingStore,create bool)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*MarketingSubscriberPayload);id:=payload.ID;if create&&id==""{id=mail.ContactID(effectID(inv))};if !create&&id==""{id=mail.ContactID(inv.Request.ResourceID)};if inv.Request.ResourceID!=""&&string(id)!=inv.Request.ResourceID{return OperationResult{},invalid("marketing subscriber identity")};tags,err:=marketingSubscriberTags(payload.Tags);if err!=nil{return OperationResult{},err};subscriber:=mail.Subscriber{ID:id,Address:payload.Address,Name:payload.Name,Tags:tags};var updated mail.Subscriber;if create{updated,err=store.CreateSubscriber(ctx,inv.Request.TenantID,subscriber)}else{updated,err=store.ReviseSubscriber(ctx,inv.Request.TenantID,subscriber,inv.Request.ExpectedGeneration)};if err!=nil{return OperationResult{},mapMailError(err)};status:=http.StatusOK;if create{status=http.StatusCreated};return OperationResult{Status:status,Value:updated,Generation:updated.Generation},nil}}
func marketingCampaignWriter(store *mail.MarketingStore,create bool)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){campaign:=value.(*MarketingCampaignPayload).Campaign;if create{if campaign.ID==""{campaign.ID=mail.CampaignID(effectID(inv))};if inv.Request.ResourceID!=""&&string(campaign.ID)!=inv.Request.ResourceID{return OperationResult{},invalid("marketing campaign identity")};campaign.State="draft";campaign.Generation=1;campaign.SnapshotRef="";campaign.RecipientCount=0;campaign.ApprovedAt=nil;campaign.ApprovedBy=""}else{if campaign.ID==""{campaign.ID=mail.CampaignID(inv.Request.ResourceID)};if string(campaign.ID)!=inv.Request.ResourceID{return OperationResult{},invalid("marketing campaign identity")};prior,found,err:=store.Campaign(ctx,inv.Request.TenantID,campaign.ID);if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};if prior.Generation!=inv.Request.ExpectedGeneration||prior.State!="draft"{return OperationResult{},ErrConflict};campaign.State=prior.State;campaign.Generation=prior.Generation+1;campaign.SnapshotRef="";campaign.RecipientCount=0;campaign.ApprovedAt=nil;campaign.ApprovedBy=""};if _,listFound,loadErr:=store.ListByID(ctx,inv.Request.TenantID,campaign.List);loadErr!=nil{return OperationResult{},mapMailError(loadErr)}else if !listFound{return OperationResult{},ErrNotFound};if _,templateFound,templateErr:=store.ApprovedTemplateVersion(ctx,inv.Request.TenantID,campaign.TemplateRef);templateErr!=nil{return OperationResult{},mapMailError(templateErr)}else if !templateFound{return OperationResult{},ErrNotFound};var err error;if create{err=store.CreateCampaign(ctx,inv.Request.TenantID,campaign)}else{err=store.AdvanceCampaign(ctx,inv.Request.TenantID,campaign,inv.Request.ExpectedGeneration)};if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:campaign,Generation:campaign.Generation},nil}}
func marketingCampaignTransition(store *mail.MarketingStore,target string)OperationHandler{return func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){campaign,found,err:=store.Campaign(ctx,inv.Request.TenantID,mail.CampaignID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};if campaign.Generation!=inv.Request.ExpectedGeneration{return OperationResult{},ErrConflict};allowed:=false;switch target{case"scheduled":allowed=campaign.State=="approved";case"running":allowed=campaign.State=="approved"||campaign.State=="scheduled"||campaign.State=="paused";case"paused":allowed=campaign.State=="running";case"cancelled":allowed=campaign.State=="draft"||campaign.State=="approved"||campaign.State=="scheduled"||campaign.State=="running"||campaign.State=="paused"};if !allowed{return OperationResult{},ErrConflict};if target=="running"||target=="scheduled"{if _,snapshotFound,loadErr:=store.CampaignSnapshot(ctx,inv.Request.TenantID,campaign);loadErr!=nil{return OperationResult{},mapMailError(loadErr)}else if !snapshotFound{return OperationResult{},ErrNotFound};if _,templateFound,templateErr:=store.ApprovedTemplateVersion(ctx,inv.Request.TenantID,campaign.TemplateRef);templateErr!=nil{return OperationResult{},mapMailError(templateErr)}else if !templateFound{return OperationResult{},ErrNotFound}};if target=="scheduled"{when,scheduleErr:=mail.CampaignScheduleTime(campaign.Schedule);if scheduleErr!=nil||!when.After(time.Now().UTC()){return OperationResult{},ErrConflict}};campaign.State=target;campaign.Generation++;if err=store.AdvanceCampaign(ctx,inv.Request.TenantID,campaign,inv.Request.ExpectedGeneration);err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:campaign,Generation:campaign.Generation},nil}}
func marketingConsentList(store *mail.MarketingStore,state mail.ConsentState)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MarketingStatePagePayload);items,next,err:=store.ConsentEvents(ctx,inv.Request.TenantID,state,int(page.Limit),page.Cursor);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:MarketingConsentPage{Items:items,NextCursor:next}},nil}}
func marketingCurrentConsent(store *mail.MarketingStore,suppressionOnly bool)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){event,found,err:=store.CurrentConsent(ctx,inv.Request.TenantID,value.(*MarketingAddressPayload).Address);if err!=nil{return OperationResult{},mapMailError(err)};if suppressionOnly&&found&&event.State!=mail.Suppressed{found=false;event=mail.ConsentEvent{}};return OperationResult{Status:http.StatusOK,Value:MarketingConsentCurrent{Found:found,Event:event}},nil}}
func marketingConsentWriter(store *mail.MarketingStore,state mail.ConsentState)OperationHandler{return func(ctx context.Context,inv Invocation,value any)(OperationResult,error){event:=value.(*MarketingConsentPayload).Event;if event.ID!=inv.Request.ResourceID{return OperationResult{},invalid("marketing event identity")};event.TenantID=inv.Request.TenantID;event.State=state;if err:=store.RecordConsent(ctx,event);err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusCreated,Value:event},nil}}
func marketingListContains(list mail.List,contact mail.ContactID)bool{for _,candidate:=range list.Contacts{if candidate==contact{return true}};return false}
func marketingSubscriberTags(value string)([]string,error){if strings.TrimSpace(value)==""{return nil,nil};parts:=strings.FieldsFunc(value,func(r rune)bool{return r==','||r=='\n'||r=='\r'});if len(parts)>64{return nil,invalid("marketing subscriber tags")};tags:=make([]string,0,len(parts));seen:=map[string]struct{}{};for _,part:=range parts{tag:=strings.ToLower(strings.TrimSpace(part));if !safeMailOpaque(tag){return nil,invalid("marketing subscriber tag")};if _,found:=seen[tag];found{continue};seen[tag]=struct{}{};tags=append(tags,tag)};return tags,nil}
