package apiserver

import (
	"context"
	"database/sql"
	"errors"
	"net/http"

	"github.com/aonsyed/cyberpanel/platform/internal/backup"
	"github.com/aonsyed/cyberpanel/platform/internal/identity"
)

type BackupPagePayload struct{Limit uint16 `json:"limit"`;Cursor string `json:"cursor,omitempty"`}
type BackupPageResult struct{Items any `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type BackupPolicySpecPayload struct{Policy backup.BackupPolicySpec `json:"policy"`}
type BackupRepositorySpecPayload struct{Repository backup.RepositorySpec `json:"repository"`}
type BackupRunPayload struct{RunID string `json:"run_id"`;PolicyID backup.PolicyID `json:"policy_id"`}
type BackupRestoreWorkflowPayload struct{Plan backup.RestorePlanSpec `json:"plan"`}
type BackupRetentionPlanPayload struct{PolicyID backup.PolicyID `json:"policy_id"`}
type BackupRetentionExecutePayload struct{PolicyID backup.PolicyID `json:"policy_id"`;Plan backup.RetentionPlan `json:"plan"`}
type RecoveryPointResult struct{Manifest backup.RecoveryPointManifest `json:"manifest"`;Copies []backup.CopyReceipt `json:"copies"`}

func registerBackupContracts(registry *Registry)error{
	manage:=identity.MustPermission("backup:manage");create:=identity.MustPermission("backup:create");restore:=identity.MustPermission("backup:restore")
	definitions:=[]Operation{
		{Name:"backup.policy.list",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &BackupPagePayload{}},ValidatePayload:validateBackupPage,ResolveScope:tenantScope},
		{Name:"backup.policy.get",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:backupResourceScope},
		{Name:"backup.policy.put",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &BackupPolicySpecPayload{}},ValidatePayload:validateBackupPolicySpec,ResolveScope:backupResourceScope},
		{Name:"backup.policy.delete",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:backupResourceScope},
		{Name:"backup.repository.list",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &BackupPagePayload{}},ValidatePayload:validateBackupPage,ResolveScope:tenantScope},
		{Name:"backup.repository.get",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:backupResourceScope},
		{Name:"backup.repository.put",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &BackupRepositorySpecPayload{}},ValidatePayload:validateBackupRepositorySpec,ResolveScope:backupResourceScope},
		{Name:"backup.run.list",Permission:create,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &BackupPagePayload{}},ValidatePayload:validateBackupPage,ResolveScope:tenantScope},
		{Name:"backup.run.get",Permission:create,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:backupResourceScope},
		{Name:"backup.run.execute",Permission:create,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &BackupRunPayload{}},ValidatePayload:validateBackupRun,ResolveScope:tenantScope},
		{Name:"backup.run.start",Permission:create,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:backupResourceScope},
		{Name:"backup.recovery_point.list",Permission:create,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &BackupPagePayload{}},ValidatePayload:validateBackupPage,ResolveScope:tenantScope},
		{Name:"backup.recovery_point.get",Permission:create,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:backupResourceScope},
		{Name:"backup.restore.prepare",Permission:restore,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &BackupRestoreWorkflowPayload{}},ValidatePayload:validateBackupRestoreWorkflow,ResolveScope:backupResourceScope},
		{Name:"backup.restore.apply",Permission:restore,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:backupResourceScope},
		{Name:"backup.restore.status",Permission:restore,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:backupResourceScope},
		{Name:"backup.restore.workflow",Permission:restore,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &BackupRestoreWorkflowPayload{}},ValidatePayload:validateBackupRestoreWorkflow,ResolveScope:tenantScope},
		{Name:"backup.retention.plan",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &BackupRetentionPlanPayload{}},ValidatePayload:validateBackupRetentionPlan,ResolveScope:tenantScope},
		{Name:"backup.retention.execute",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,MaximumBodyBytes:8<<20,NewPayload:func()any{return &BackupRetentionExecutePayload{}},ValidatePayload:validateBackupRetentionExecute,ResolveScope:tenantScope},
	}
	for _,definition:=range definitions{if err:=register(registry,definition);err!=nil{return err}}
	return nil
}

func validateBackupPage(value any)error{page:=value.(*BackupPagePayload);if page.Limit>500||(page.Cursor!=""&&!safeMailOpaque(page.Cursor)){return invalid("backup page")};return nil}
func validateBackupPolicySpec(value any)error{policy:=value.(*BackupPolicySpecPayload).Policy;if !safeMailOpaque(string(policy.ID))||!safeMailOpaque(policy.Scope)||len(policy.Components)==0||len(policy.Components)>3||len(policy.Repositories)==0||len(policy.Repositories)>64||policy.RequiredCopies==0||policy.Consistency!=backup.ConsistencyFuzzy{return invalid("backup policy")};seen:=map[backup.ComponentKind]bool{};for _,component:=range policy.Components{if component!=backup.ComponentFiles&&component!=backup.ComponentDatabase&&component!=backup.ComponentMail||seen[component]{return invalid("backup component")};seen[component]=true};for _,repository:=range policy.Repositories{if !safeMailOpaque(string(repository)){return invalid("backup repository")}};return nil}
func validateBackupRepositorySpec(value any)error{spec:=value.(*BackupRepositorySpecPayload).Repository;expectedEndpoint:="file:///var/backups/cyberpanel/repositories/"+string(spec.Repository.ID);if !safeMailOpaque(string(spec.Repository.ID))||spec.Repository.Kind!=backup.Local||spec.Repository.Endpoint!=expectedEndpoint||spec.Repository.Bucket!=""||spec.Repository.CredentialRef!="local"||!safeMailOpaque(spec.FailureDomain)||!safeMailOpaque(spec.EncryptionDomain)||spec.MaximumConcurrency==0||spec.MaximumConcurrency>64{return invalid("backup repository")};return nil}
func validateBackupRun(value any)error{payload:=value.(*BackupRunPayload);if !safeMailOpaque(payload.RunID)||!safeMailOpaque(string(payload.PolicyID)){return invalid("backup run")};return nil}
func validateBackupRestoreWorkflow(value any)error{plan:=value.(*BackupRestoreWorkflowPayload).Plan;if !safeMailOpaque(string(plan.ID))||!safeMailOpaque(string(plan.RecoveryPointID))||!safeMailOpaque(plan.SourceScope)||!safeMailOpaque(plan.TargetScope)||len(plan.ComponentMapping)==0||len(plan.ComponentMapping)>3||plan.CollisionPolicy!=backup.CollisionReplaceBlueGreen||plan.SecretPolicy!=backup.SecretResetRequired||len(plan.DomainMapping)!=0{return invalid("restore plan")};for component,target:=range plan.ComponentMapping{if component!=backup.ComponentFiles&&component!=backup.ComponentDatabase&&component!=backup.ComponentMail||target!=plan.TargetScope{return invalid("restore target")}};return nil}
func validateBackupRetentionPlan(value any)error{if !safeMailOpaque(string(value.(*BackupRetentionPlanPayload).PolicyID)){return invalid("retention policy")};return nil}
func validateBackupRetentionExecute(value any)error{payload:=value.(*BackupRetentionExecutePayload);if !safeMailOpaque(string(payload.PolicyID))||!safeMailOpaque(payload.Plan.ID)||payload.Plan.PolicyID!=payload.PolicyID||payload.Plan.Digest==""||payload.Plan.InventoryDigest==""||len(payload.Plan.Decisions)>1000000{return invalid("retention plan")};return nil}
func backupResourceScope(request RequestEnvelope,value any)(identity.Scope,error){if !safeMailOpaque(request.ResourceID){return identity.Scope{},invalid("backup resource")};return tenantScope(request,value)}

func bindBackup(registry *Registry,services DomainServices)error{
	catalog:=services.BackupCatalog;if catalog==nil&&services.BackupWorkflow!=nil{catalog=&services.BackupWorkflow.Catalog}
	if catalog!=nil&&catalog.DB!=nil{
		if err:=registry.Bind("backup.policy.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*BackupPagePayload);items,next,err:=catalog.Policies(ctx,inv.Request.TenantID,page.Cursor,int(page.Limit));if err!=nil{return OperationResult{},mapBackupError(err)};return OperationResult{Status:http.StatusOK,Value:BackupPageResult{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("backup.policy.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){policy,err:=catalog.Policy(ctx,inv.Request.TenantID,backup.PolicyID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapBackupError(err)};return OperationResult{Status:http.StatusOK,Value:policy,Generation:policy.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("backup.policy.put",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){policy:=value.(*BackupPolicySpecPayload).Policy;if string(policy.ID)!=inv.Request.ResourceID{return OperationResult{},ErrInvalidRequest};policy.TenantID=inv.Request.TenantID;policy.Generation=inv.Request.ExpectedGeneration+1;if err:=catalog.PutPolicy(ctx,policy,inv.Request.ExpectedGeneration);err!=nil{return OperationResult{},mapBackupError(err)};return OperationResult{Status:http.StatusOK,Value:policy,Generation:policy.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("backup.policy.delete",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){if err:=catalog.DeletePolicy(ctx,inv.Request.TenantID,backup.PolicyID(inv.Request.ResourceID),inv.Request.ExpectedGeneration);err!=nil{return OperationResult{},mapBackupError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"deleted"}},nil});err!=nil{return err}
		if err:=registry.Bind("backup.repository.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*BackupPagePayload);items,next,err:=catalog.Repositories(ctx,inv.Request.TenantID,page.Cursor,int(page.Limit));if err!=nil{return OperationResult{},mapBackupError(err)};for index:=range items{items[index].Repository.CredentialRef=""};return OperationResult{Status:http.StatusOK,Value:BackupPageResult{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("backup.repository.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){repository,err:=catalog.Repository(ctx,inv.Request.TenantID,backup.RepositoryID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapBackupError(err)};repository.Repository.CredentialRef="";return OperationResult{Status:http.StatusOK,Value:repository},nil});err!=nil{return err}
		if err:=registry.Bind("backup.repository.put",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){repository:=value.(*BackupRepositorySpecPayload).Repository;if string(repository.Repository.ID)!=inv.Request.ResourceID{return OperationResult{},ErrInvalidRequest};repository.TenantID=inv.Request.TenantID;if err:=catalog.PutRepository(ctx,repository);err!=nil{return OperationResult{},mapBackupError(err)};repository.Repository.CredentialRef="";return OperationResult{Status:http.StatusOK,Value:repository},nil});err!=nil{return err}
		if err:=registry.Bind("backup.run.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*BackupPagePayload);items,next,err:=catalog.Runs(ctx,inv.Request.TenantID,page.Cursor,int(page.Limit));if err!=nil{return OperationResult{},mapBackupError(err)};return OperationResult{Status:http.StatusOK,Value:BackupPageResult{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("backup.run.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){run,err:=catalog.Run(ctx,inv.Request.TenantID,inv.Request.ResourceID);if err!=nil{return OperationResult{},mapBackupError(err)};return OperationResult{Status:http.StatusOK,Value:run,Generation:run.Policy.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("backup.recovery_point.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*BackupPagePayload);items,next,err:=catalog.RecoveryPoints(ctx,inv.Request.TenantID,page.Cursor,int(page.Limit));if err!=nil{return OperationResult{},mapBackupError(err)};return OperationResult{Status:http.StatusOK,Value:BackupPageResult{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("backup.recovery_point.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){manifest,copies,err:=catalog.RecoveryPoint(ctx,inv.Request.TenantID,backup.RecoveryPointID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapBackupError(err)};return OperationResult{Status:http.StatusOK,Value:RecoveryPointResult{Manifest:manifest,Copies:copies}},nil});err!=nil{return err}
	}
	if services.BackupWorkflow!=nil&&services.BackupWorkflow.Snapshots!=nil&&services.BackupWorkflow.Capturer!=nil&&catalog!=nil{
		if err:=registry.Bind("backup.run.execute",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*BackupRunPayload);policy,err:=catalog.Policy(ctx,inv.Request.TenantID,payload.PolicyID);if err!=nil{return OperationResult{},mapBackupError(err)};repositories:=make([]backup.RepositorySpec,0,len(policy.Repositories));for _,id:=range policy.Repositories{repository,loadErr:=catalog.Repository(ctx,inv.Request.TenantID,id);if loadErr!=nil{return OperationResult{},mapBackupError(loadErr)};repositories=append(repositories,repository)};run,err:=services.BackupWorkflow.Run(ctx,payload.RunID,"api_"+inv.IdempotencyKey,policy,repositories);if err!=nil{return OperationResult{},mapBackupError(err)};return OperationResult{Status:http.StatusCreated,Value:run,Generation:policy.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("backup.run.start",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){policy,err:=catalog.Policy(ctx,inv.Request.TenantID,backup.PolicyID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapBackupError(err)};if inv.Request.ExpectedGeneration!=0&&policy.Generation!=inv.Request.ExpectedGeneration{return OperationResult{},ErrConflict};repositories:=make([]backup.RepositorySpec,0,len(policy.Repositories));for _,id:=range policy.Repositories{repository,loadErr:=catalog.Repository(ctx,inv.Request.TenantID,id);if loadErr!=nil{return OperationResult{},mapBackupError(loadErr)};repositories=append(repositories,repository)};run,err:=services.BackupWorkflow.Run(ctx,effectID(inv),"api_"+inv.IdempotencyKey,policy,repositories);if err!=nil{return OperationResult{},mapBackupError(err)};return OperationResult{Status:http.StatusCreated,Value:run,Generation:policy.Generation},nil});err!=nil{return err}
	}
	if services.RestoreWorkflow!=nil&&services.RestoreWorkflow.Store.DB!=nil{
		if err:=registry.Bind("backup.restore.status",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){plan,receipt,err:=services.RestoreWorkflow.Status(ctx,inv.Request.TenantID,backup.RestoreID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapBackupError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]any{"plan":plan,"receipt":receipt},Generation:receipt.Generation},nil});err!=nil{return err}
	}
	if services.RestoreWorkflow!=nil&&services.RestoreWorkflow.Capacity!=nil&&services.RestoreWorkflow.Source!=nil{
		if err:=registry.Bind("backup.restore.prepare",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){plan:=value.(*BackupRestoreWorkflowPayload).Plan;if string(plan.ID)!=inv.Request.ResourceID||inv.Request.ExpectedGeneration!=0{return OperationResult{},ErrInvalidRequest};plan.TenantID=inv.Request.TenantID;plan.IdempotencyKey="api_"+inv.Request.TenantID+"_"+inv.IdempotencyKey;plan.Generation=1;receipt,err:=services.RestoreWorkflow.Plan(ctx,plan);if err!=nil{return OperationResult{},mapBackupError(err)};return OperationResult{Status:http.StatusCreated,Value:receipt,Generation:receipt.Generation},nil});err!=nil{return err}
	}
	if services.RestoreWorkflow!=nil&&services.RestoreWorkflow.Capacity!=nil&&services.RestoreWorkflow.Source!=nil&&services.RestoreWorkflow.Scanner!=nil&&services.RestoreWorkflow.Target!=nil&&services.RestoreWorkflow.Safety!=nil{
		if err:=registry.Bind("backup.restore.apply",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){receipt,err:=services.RestoreWorkflow.Apply(ctx,inv.Request.TenantID,backup.RestoreID(inv.Request.ResourceID),inv.Request.ExpectedGeneration);if err!=nil{return OperationResult{},mapBackupError(err)};return OperationResult{Status:http.StatusOK,Value:receipt,Generation:receipt.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("backup.restore.workflow",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){if inv.Request.ExpectedGeneration!=0{return OperationResult{},ErrInvalidRequest};plan:=value.(*BackupRestoreWorkflowPayload).Plan;plan.TenantID=inv.Request.TenantID;plan.IdempotencyKey="api_"+inv.Request.TenantID+"_"+inv.IdempotencyKey;plan.Generation=1;receipt,err:=services.RestoreWorkflow.Execute(ctx,plan);if err!=nil{return OperationResult{},mapBackupError(err)};return OperationResult{Status:http.StatusOK,Value:receipt,Generation:receipt.Generation},nil});err!=nil{return err}
	}
	if services.Retention!=nil&&services.Retention.Catalog!=nil&&catalog!=nil{
		if err:=registry.Bind("backup.retention.plan",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){policy,err:=catalog.Policy(ctx,inv.Request.TenantID,value.(*BackupRetentionPlanPayload).PolicyID);if err!=nil{return OperationResult{},mapBackupError(err)};plan,err:=services.Retention.Plan(ctx,policy);if err!=nil{return OperationResult{},mapBackupError(err)};return OperationResult{Status:http.StatusCreated,Value:plan,Generation:policy.Generation},nil});err!=nil{return err}
		return registry.Bind("backup.retention.execute",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*BackupRetentionExecutePayload);policy,err:=catalog.Policy(ctx,inv.Request.TenantID,payload.PolicyID);if err!=nil{return OperationResult{},mapBackupError(err)};plan,err:=services.Retention.ExecuteDurable(ctx,policy,payload.Plan);if err!=nil{return OperationResult{},mapBackupError(err)};return OperationResult{Status:http.StatusOK,Value:plan,Generation:policy.Generation},nil})
	}
	return nil
}

func mapBackupError(err error)error{switch{case err==nil:return nil;case errors.Is(err,sql.ErrNoRows):return ErrNotFound;case errors.Is(err,backup.ErrInvalidBackup):return ErrInvalidRequest;case errors.Is(err,backup.ErrBackupConflict),errors.Is(err,backup.ErrRestoreWriteFrontier):return ErrConflict;case errors.Is(err,backup.ErrBackupAmbiguous):return ErrUnavailable;default:return err}}
