package apiserver

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"net/http"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/hosting/site"
	"github.com/aonsyed/cyberpanel/platform/internal/identity"
	"github.com/aonsyed/cyberpanel/platform/internal/operations"
)

type ResourceProfilePayload struct{NodeID operations.ResourceID `json:"node_id"`;Profile operations.ResourceProfile `json:"profile"`}
type FirewallPayload struct{NodeID operations.ResourceID `json:"node_id"`;ApprovalRef operations.ResourceID `json:"approval_ref"`;Policy operations.FirewallPolicy `json:"policy"`}
type SSHPolicyPayload struct{NodeID operations.ResourceID `json:"node_id"`;ApprovalRef operations.ResourceID `json:"approval_ref"`;Policy operations.SSHPolicy `json:"policy"`}
type SSHPutKeyPayload struct{NodeID operations.ResourceID `json:"node_id"`;Key operations.SSHKey `json:"key"`}
type SSHDeleteKeyPayload struct{NodeID operations.ResourceID `json:"node_id"`;SiteID string `json:"site_id,omitempty"`;KeyID operations.ResourceID `json:"key_id"`}
type WAFPayload struct{NodeID operations.ResourceID `json:"node_id"`;Policy operations.WAFPolicy `json:"policy"`}
type ServicePolicyPayload struct{NodeID operations.ResourceID `json:"node_id"`;Policy operations.ServicePolicy `json:"policy"`}
type ServiceControlPayload struct{NodeID operations.ResourceID `json:"node_id"`;Service operations.ServiceName `json:"service"`;Action operations.ServiceAction `json:"action"`}
type ServiceDiagnosePayload struct{NodeID operations.ResourceID `json:"node_id"`;Service operations.ServiceName `json:"service"`;Depth operations.DiagnosticDepth `json:"depth"`;Since time.Time `json:"since"`}
type ServiceRepairPayload struct{NodeID operations.ResourceID `json:"node_id"`;Service operations.ServiceName `json:"service"`;Strategy operations.RepairStrategy `json:"strategy"`;DiagnosticProofDigest string `json:"diagnostic_proof_digest"`}
type MetricsPayload struct{NodeID operations.ResourceID `json:"node_id"`;SiteID string `json:"site_id,omitempty"`;Names []operations.MetricName `json:"names"`;Start time.Time `json:"start"`;End time.Time `json:"end"`;Step time.Duration `json:"step"`;Limit uint32 `json:"limit"`}
type LogsPayload struct{NodeID operations.ResourceID `json:"node_id"`;SiteID string `json:"site_id,omitempty"`;Source operations.LogSource `json:"source"`;Service operations.ServiceName `json:"service,omitempty"`;Start time.Time `json:"start"`;End time.Time `json:"end"`;MinimumSeverity uint8 `json:"minimum_severity"`;Cursor string `json:"cursor,omitempty"`;Limit uint32 `json:"limit"`}
type PackagePayload struct{NodeID operations.ResourceID `json:"node_id"`;ApprovalRef operations.ResourceID `json:"approval_ref"`;Transaction operations.PackageTransaction `json:"transaction"`}
type ManagedServicePayload struct{NodeID operations.ResourceID `json:"node_id"`;Service operations.ManagedService `json:"service"`}

func registerOperationsContracts(registry *Registry)error{
	definitions:=[]Operation{
		{Name:"operations.resource_profile.apply",Permission:identity.MustPermission("operations:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ResourceProfilePayload{}},ResolveScope:tenantOrInstallationScope},
		{Name:"operations.firewall.replace",Permission:identity.MustPermission("security:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &FirewallPayload{}},ResolveScope:installationScope},
		{Name:"operations.ssh_policy.replace",Permission:identity.MustPermission("security:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &SSHPolicyPayload{}},ResolveScope:installationScope},
		{Name:"operations.ssh_key.put",Permission:identity.MustPermission("security:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &SSHPutKeyPayload{}},ResolveScope:tenantOrInstallationScope},
		{Name:"operations.ssh_key.delete",Permission:identity.MustPermission("security:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &SSHDeleteKeyPayload{}},ResolveScope:tenantOrInstallationScope},
		{Name:"operations.waf.replace",Permission:identity.MustPermission("security:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &WAFPayload{}},ResolveScope:tenantOrInstallationScope},
		{Name:"operations.service_policy.set",Permission:identity.MustPermission("operations:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ServicePolicyPayload{}},ResolveScope:installationScope},
		{Name:"operations.service.control",Permission:identity.MustPermission("operations:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ServiceControlPayload{}},ResolveScope:installationScope},
		{Name:"operations.service.diagnose",Permission:identity.MustPermission("operations:observe"),Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:false,NewPayload:func()any{return &ServiceDiagnosePayload{}},ResolveScope:installationScope},
		{Name:"operations.service.repair",Permission:identity.MustPermission("operations:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ServiceRepairPayload{}},ResolveScope:installationScope},
		{Name:"operations.metrics.query",Permission:identity.MustPermission("operations:observe"),Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:false,NewPayload:func()any{return &MetricsPayload{}},ResolveScope:tenantOrInstallationScope},
		{Name:"operations.logs.query",Permission:identity.MustPermission("operations:observe"),Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:false,NewPayload:func()any{return &LogsPayload{}},ResolveScope:tenantOrInstallationScope},
		{Name:"operations.package.apply",Permission:identity.MustPermission("package:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &PackagePayload{}},ResolveScope:installationScope},
		{Name:"operations.managed_service.reconcile",Permission:identity.MustPermission("operations:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ManagedServicePayload{}},ResolveScope:tenantOrInstallationScope},
	}
	for _,definition:=range definitions{if err:=register(registry,definition);err!=nil{return err}}
	return nil
}

func tenantOrInstallationScope(request RequestEnvelope,value any)(identity.Scope,error){if request.TenantID==""{return installationScope(request,value)};return tenantScope(request,value)}

func operationHeader(inv Invocation,node,approval operations.ResourceID,siteRaw string,capabilities ...operations.Capability)(operations.CommandHeader,error){principal,err:=operations.NewResourceID(inv.Actor.PrincipalID.String());if err!=nil{return operations.CommandHeader{},ErrInvalidRequest};var tenant site.TenantID;if inv.Request.TenantID!=""{tenant,err=site.NewTenantID(inv.Request.TenantID);if err!=nil{return operations.CommandHeader{},ErrInvalidRequest}};var siteID site.SiteID;if siteRaw!=""{if tenant.String()==""{return operations.CommandHeader{},invalid("site_id without tenant_id")};siteID,err=site.NewSiteID(siteRaw);if err!=nil{return operations.CommandHeader{},invalid("site_id")}};now:=time.Now().UTC();mfa:=operations.ResourceID{};if inv.Actor.Assurance>=identity.AssuranceMFA{sum:=sha256.Sum256([]byte(inv.Actor.SessionID.String()+"\x00"+inv.Actor.CredentialID.String()));mfa,_=operations.NewResourceID("mfa-"+hex.EncodeToString(sum[:16]))};return operations.CommandHeader{CommandID:commandID(inv),NodeID:node,TenantID:tenant,SiteID:siteID,Actor:operations.Actor{PrincipalID:principal,TenantID:tenant,Capabilities:capabilities,MFAProofRef:mfa},RequestedAt:now,Deadline:now.Add(2*time.Minute),ApprovalRef:approval},nil}
func observationCapability(inv Invocation)operations.Capability{if inv.Request.TenantID==""{return operations.CapabilityNodeOperations};return operations.CapabilityTenantObserve}
func enforcementScope(header operations.CommandHeader)operations.EnforcementScope{kind:=operations.ScopeNode;if header.TenantID.String()!=""{kind=operations.ScopeTenant};if header.SiteID.String()!=""{kind=operations.ScopeSite};return operations.EnforcementScope{Kind:kind,NodeID:header.NodeID,TenantID:header.TenantID,SiteID:header.SiteID}}
func generation(expected uint64)uint64{return expected+1}

func bindOperations(registry *Registry,services DomainServices)error{
	if services.Operations==nil{return nil}
	bind:=func(name string,builder func(Invocation,any)(operations.Command,error))error{return registry.Bind(name,func(ctx context.Context,inv Invocation,value any)(OperationResult,error){command,err:=builder(inv,value);if err!=nil{return OperationResult{},err};receipt,err:=services.Operations.Handle(ctx,command);if err!=nil{return OperationResult{},mapOperationsError(err)};return OperationResult{Status:http.StatusOK,Value:receipt},nil})}
	if err:=bind("operations.resource_profile.apply",func(inv Invocation,value any)(operations.Command,error){p:=value.(*ResourceProfilePayload);header,err:=operationHeader(inv,p.NodeID,operations.ResourceID{},p.Profile.Metadata.SiteID.String(),operations.CapabilityNodeOperations);p.Profile.Metadata.NodeID=p.NodeID;p.Profile.Metadata.TenantID=header.TenantID;p.Profile.Metadata.SiteID=header.SiteID;p.Profile.Metadata.Generation=generation(inv.Request.ExpectedGeneration);p.Profile.Scope=enforcementScope(header);return operations.ApplyResourceProfile{Header:header,Profile:p.Profile,ExpectedGeneration:inv.Request.ExpectedGeneration},err});err!=nil{return err}
	if err:=bind("operations.firewall.replace",func(inv Invocation,value any)(operations.Command,error){p:=value.(*FirewallPayload);header,err:=operationHeader(inv,p.NodeID,p.ApprovalRef,"",operations.CapabilityNodeSecurity);p.Policy.Metadata.NodeID=p.NodeID;p.Policy.Metadata.Generation=generation(inv.Request.ExpectedGeneration);return operations.ReplaceFirewallPolicy{Header:header,Policy:p.Policy,ExpectedGeneration:inv.Request.ExpectedGeneration},err});err!=nil{return err}
	if err:=bind("operations.ssh_policy.replace",func(inv Invocation,value any)(operations.Command,error){p:=value.(*SSHPolicyPayload);header,err:=operationHeader(inv,p.NodeID,p.ApprovalRef,"",operations.CapabilityNodeSecurity);p.Policy.Metadata.NodeID=p.NodeID;p.Policy.Metadata.Generation=generation(inv.Request.ExpectedGeneration);return operations.ReplaceSSHPolicy{Header:header,Policy:p.Policy,ExpectedGeneration:inv.Request.ExpectedGeneration},err});err!=nil{return err}
	if err:=bind("operations.ssh_key.put",func(inv Invocation,value any)(operations.Command,error){p:=value.(*SSHPutKeyPayload);capability:=operations.CapabilityTenantSecurity;if inv.Request.TenantID==""{capability=operations.CapabilityNodeSecurity};header,err:=operationHeader(inv,p.NodeID,operations.ResourceID{},p.Key.Metadata.SiteID.String(),capability);p.Key.Metadata.NodeID=p.NodeID;p.Key.Metadata.Generation=generation(inv.Request.ExpectedGeneration);p.Key.Metadata.TenantID=header.TenantID;p.Key.Metadata.SiteID=header.SiteID;if capability==operations.CapabilityTenantSecurity{p.Key.PrincipalID=header.Actor.PrincipalID};return operations.PutSSHKey{Header:header,Key:p.Key,ExpectedGeneration:inv.Request.ExpectedGeneration},err});err!=nil{return err}
	if err:=bind("operations.ssh_key.delete",func(inv Invocation,value any)(operations.Command,error){p:=value.(*SSHDeleteKeyPayload);capability:=operations.CapabilityTenantSecurity;if inv.Request.TenantID==""{capability=operations.CapabilityNodeSecurity};header,err:=operationHeader(inv,p.NodeID,operations.ResourceID{},p.SiteID,capability);return operations.DeleteSSHKey{Header:header,KeyID:p.KeyID,ExpectedGeneration:inv.Request.ExpectedGeneration},err});err!=nil{return err}
	if err:=bind("operations.waf.replace",func(inv Invocation,value any)(operations.Command,error){p:=value.(*WAFPayload);capability:=operations.CapabilityTenantSecurity;if inv.Request.TenantID==""{capability=operations.CapabilityNodeSecurity};header,err:=operationHeader(inv,p.NodeID,operations.ResourceID{},p.Policy.Metadata.SiteID.String(),capability);p.Policy.Metadata.NodeID=p.NodeID;p.Policy.Metadata.Generation=generation(inv.Request.ExpectedGeneration);p.Policy.Metadata.TenantID=header.TenantID;p.Policy.Metadata.SiteID=header.SiteID;return operations.ReplaceWAFPolicy{Header:header,Policy:p.Policy,ExpectedGeneration:inv.Request.ExpectedGeneration},err});err!=nil{return err}
	if err:=bind("operations.service_policy.set",func(inv Invocation,value any)(operations.Command,error){p:=value.(*ServicePolicyPayload);header,err:=operationHeader(inv,p.NodeID,operations.ResourceID{},"",operations.CapabilityNodeOperations);id,_:=operations.NewResourceID("service-"+string(p.Policy.Service));p.Policy.Metadata.ID=id;p.Policy.Metadata.NodeID=p.NodeID;p.Policy.Metadata.Generation=generation(inv.Request.ExpectedGeneration);return operations.SetServicePolicy{Header:header,Policy:p.Policy,ExpectedGeneration:inv.Request.ExpectedGeneration},err});err!=nil{return err}
	if err:=bind("operations.service.control",func(inv Invocation,value any)(operations.Command,error){p:=value.(*ServiceControlPayload);header,err:=operationHeader(inv,p.NodeID,operations.ResourceID{},"",operations.CapabilityNodeOperations);return operations.ControlService{Header:header,Service:p.Service,Action:p.Action,ExpectedPolicyGeneration:inv.Request.ExpectedGeneration},err});err!=nil{return err}
	if err:=bind("operations.service.diagnose",func(inv Invocation,value any)(operations.Command,error){p:=value.(*ServiceDiagnosePayload);header,err:=operationHeader(inv,p.NodeID,operations.ResourceID{},"",operations.CapabilityNodeOperations);return operations.DiagnoseService{Header:header,Service:p.Service,Depth:p.Depth,Since:p.Since},err});err!=nil{return err}
	if err:=bind("operations.service.repair",func(inv Invocation,value any)(operations.Command,error){p:=value.(*ServiceRepairPayload);header,err:=operationHeader(inv,p.NodeID,operations.ResourceID{},"",operations.CapabilityNodeOperations);return operations.RepairService{Header:header,Service:p.Service,Strategy:p.Strategy,DiagnosticProofDigest:p.DiagnosticProofDigest},err});err!=nil{return err}
	if err:=bind("operations.metrics.query",func(inv Invocation,value any)(operations.Command,error){p:=value.(*MetricsPayload);header,err:=operationHeader(inv,p.NodeID,operations.ResourceID{},p.SiteID,observationCapability(inv));return operations.QueryMetrics{Header:header,Scope:enforcementScope(header),Names:p.Names,Start:p.Start,End:p.End,Step:p.Step,Limit:p.Limit},err});err!=nil{return err}
	if err:=bind("operations.logs.query",func(inv Invocation,value any)(operations.Command,error){p:=value.(*LogsPayload);header,err:=operationHeader(inv,p.NodeID,operations.ResourceID{},p.SiteID,observationCapability(inv));return operations.OpenLogStream{Header:header,Source:p.Source,Service:p.Service,Start:p.Start,End:p.End,MinimumSeverity:p.MinimumSeverity,Cursor:p.Cursor,Limit:p.Limit},err});err!=nil{return err}
	if err:=bind("operations.package.apply",func(inv Invocation,value any)(operations.Command,error){p:=value.(*PackagePayload);header,err:=operationHeader(inv,p.NodeID,p.ApprovalRef,"",operations.CapabilityNodePackages);p.Transaction.Metadata.NodeID=p.NodeID;p.Transaction.Metadata.Generation=1;return operations.RequestPackageTransaction{Header:header,Transaction:p.Transaction},err});err!=nil{return err}
	return bind("operations.managed_service.reconcile",func(inv Invocation,value any)(operations.Command,error){p:=value.(*ManagedServicePayload);header,err:=operationHeader(inv,p.NodeID,operations.ResourceID{},p.Service.Metadata.SiteID.String(),operations.CapabilityNodeOperations);p.Service.Metadata.NodeID=p.NodeID;p.Service.Metadata.Generation=generation(inv.Request.ExpectedGeneration);p.Service.Metadata.TenantID=header.TenantID;p.Service.Metadata.SiteID=header.SiteID;return operations.ReconcileManagedService{Header:header,Service:p.Service,ExpectedGeneration:inv.Request.ExpectedGeneration},err})
}

func mapOperationsError(err error)error{switch{case err==nil:return nil;case errors.Is(err,operations.ErrInvalidCommand)||errors.Is(err,operations.ErrInvalidResource):return ErrInvalidRequest;case errors.Is(err,operations.ErrUnauthorized):return ErrForbidden;case errors.Is(err,operations.ErrNotFound):return ErrNotFound;case errors.Is(err,operations.ErrConflict)||errors.Is(err,operations.ErrIdempotency):return ErrConflict;default:return err}}
