package apiserver

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"net"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/certificates"
	"github.com/aonsyed/cyberpanel/platform/internal/identity"
)

type CertificatePagePayload struct{Limit uint16 `json:"limit"`;Cursor string `json:"cursor,omitempty"`}
type CertificatePageResult struct{Items any `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type CertificateAccountPayload struct{Account certificates.AccountSpec `json:"account"`}
type CertificatePolicyPayload struct{Policy certificates.CertificatePolicy `json:"policy"`}
type CertificateIssuePayload struct{PolicyID certificates.PolicyID `json:"policy_id"`;IssuanceID string `json:"issuance_id"`}
type CertificateDeployPayload struct{CertificateID certificates.CertificateID `json:"certificate_id"`;Consumer string `json:"consumer"`}
type CertificateMaterialUint64 uint64
func(value *CertificateMaterialUint64)UnmarshalJSON(content []byte)error{var number uint64;if json.Unmarshal(content,&number)==nil{*value=CertificateMaterialUint64(number);return nil};var text string;if json.Unmarshal(content,&text)!=nil{return invalid("certificate material number")};number,err:=strconv.ParseUint(text,10,64);if err!=nil{return invalid("certificate material number")};*value=CertificateMaterialUint64(number);return nil}
type CertificateMaterialInt int
func(value *CertificateMaterialInt)UnmarshalJSON(content []byte)error{var number int;if json.Unmarshal(content,&number)==nil{*value=CertificateMaterialInt(number);return nil};var text string;if json.Unmarshal(content,&text)!=nil{return invalid("certificate material number")};parsed,err:=strconv.ParseInt(text,10,32);if err!=nil{return invalid("certificate material number")};*value=CertificateMaterialInt(parsed);return nil}
type CertificateMaterialImportPayload struct{ResourceID string `json:"resource_id"`;UploadHandle string `json:"upload_handle"`;DisplayLabel string `json:"display_label"`;DNSNames EdgeStringList `json:"dns_names"`;IPAddresses EdgeStringList `json:"ip_addresses"`;ExpectedCertificateGeneration CertificateMaterialUint64 `json:"expected_certificate_generation,omitempty"`}
type CertificateMaterialSelfSignedPayload struct{ResourceID string `json:"resource_id"`;DisplayLabel string `json:"display_label"`;Mode certificates.SelfSignedMode `json:"mode"`;DNSNames EdgeStringList `json:"dns_names"`;IPAddresses EdgeStringList `json:"ip_addresses"`;LifetimeSeconds CertificateMaterialUint64 `json:"lifetime_seconds"`;KeyAlgorithm certificates.MaterialKeyAlgorithm `json:"key_algorithm"`;KeyBits CertificateMaterialInt `json:"key_bits"`;AcknowledgeNoPublicReplacement bool `json:"acknowledge_no_public_replacement"`;ExpectedCertificateGeneration CertificateMaterialUint64 `json:"expected_certificate_generation,omitempty"`}
type CertificateMaterialListPayload struct{ResourceID string `json:"resource_id"`;Limit uint16 `json:"limit"`;Cursor string `json:"cursor,omitempty"`}
type CertificateMaterialInspectPayload struct{ResourceID string `json:"resource_id"`;MaterialID string `json:"material_id"`}
type CertificateMaterialRetirePayload struct{ResourceID string `json:"resource_id"`;MaterialID string `json:"material_id"`;ExpectedRecordGeneration CertificateMaterialUint64 `json:"expected_record_generation"`}
type CertificateMaterialEligibilityPayload struct{ResourceID string `json:"resource_id"`;MaterialID string `json:"material_id"`;ConsumerKind string `json:"consumer_kind"`;ConsumerID string `json:"consumer_id"`;Purpose string `json:"purpose"`}
type CertificateMaterialDeploymentEligibility struct{MaterialID string `json:"material_id"`;CertificateFingerprint string `json:"certificate_fingerprint"`;TrustLabel certificates.MaterialTrustLabel `json:"trust_label"`;State certificates.MaterialLifecycleState `json:"state"`;NotBefore time.Time `json:"not_before"`;NotAfter time.Time `json:"not_after"`;Consumer *certificates.MaterialConsumerBinding `json:"consumer,omitempty"`;Eligible bool `json:"eligible"`;ReasonCodes []string `json:"reason_codes,omitempty"`}

func registerCertificateContracts(registry *Registry)error{
	manage:=identity.MustPermission("certificate:manage")
	definitions:=[]Operation{
		{Name:"certificate.account.list",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &CertificatePagePayload{}},ValidatePayload:validateCertificatePage,ResolveScope:tenantScope},
		{Name:"certificate.account.get",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:certificateResourceScope},
		{Name:"certificate.account.put",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &CertificateAccountPayload{}},ValidatePayload:validateCertificateAccount,ResolveScope:certificateResourceScope},
		{Name:"certificate.policy.list",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &CertificatePagePayload{}},ValidatePayload:validateCertificatePage,ResolveScope:tenantScope},
		{Name:"certificate.policy.get",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:certificateResourceScope},
		{Name:"certificate.policy.put",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &CertificatePolicyPayload{}},ValidatePayload:validateCertificatePolicy,ResolveScope:certificateResourceScope},
		{Name:"certificate.issuance.list",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &CertificatePagePayload{}},ValidatePayload:validateCertificatePage,ResolveScope:tenantScope},
		{Name:"certificate.list",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &CertificatePagePayload{}},ValidatePayload:validateCertificatePage,ResolveScope:tenantScope},
		{Name:"certificate.issuance.get",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:certificateResourceScope},
		{Name:"certificate.issuance.issue",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &CertificateIssuePayload{}},ValidatePayload:validateCertificateIssue,ResolveScope:tenantScope},
		{Name:"certificate.renew",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:certificateResourceScope},
		{Name:"certificate.revoke",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:certificateResourceScope},
		{Name:"certificate.deployment.create",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &CertificateDeployPayload{}},ValidatePayload:validateCertificateDeploy,ResolveScope:siteScope},
		{Name:"certificate.material.import",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &CertificateMaterialImportPayload{}},ValidatePayload:validateCertificateMaterialImport,ResolveScope:certificateMaterialScope},
		{Name:"certificate.material.self_signed",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &CertificateMaterialSelfSignedPayload{}},ValidatePayload:validateCertificateMaterialSelfSigned,ResolveScope:certificateMaterialScope},
		{Name:"certificate.material.list",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &CertificateMaterialListPayload{}},ValidatePayload:validateCertificateMaterialList,ResolveScope:certificateMaterialScope},
		{Name:"certificate.material.inspect",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &CertificateMaterialInspectPayload{}},ValidatePayload:validateCertificateMaterialInspect,ResolveScope:certificateMaterialScope},
		{Name:"certificate.material.retire",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &CertificateMaterialRetirePayload{}},ValidatePayload:validateCertificateMaterialRetire,ResolveScope:certificateMaterialScope},
		{Name:"certificate.material.deployment_eligibility",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &CertificateMaterialEligibilityPayload{}},ValidatePayload:validateCertificateMaterialEligibility,ResolveScope:certificateMaterialScope},
	}
	for _,definition:=range definitions{if err:=register(registry,definition);err!=nil{return err}}
	return nil
}

func validateCertificatePage(value any)error{payload:=value.(*CertificatePagePayload);if payload.Limit>500||(payload.Cursor!=""&&!safeMailOpaque(payload.Cursor)){return invalid("certificate page")};return nil}
func validateCertificateAccount(value any)error{account:=value.(*CertificateAccountPayload).Account;if !safeMailOpaque(string(account.ID))||!safeMailOpaque(account.AccountKeyRef)||len(account.Contact)==0||len(account.Contact)>10||account.AcceptedTermsAt.IsZero(){return invalid("ACME account")};production,err:=url.Parse(account.Directory.ProductionURL);if err!=nil||production.Scheme!="https"||production.User!=nil||production.Hostname()==""{return invalid("ACME directory")};staging,err:=url.Parse(account.Directory.StagingURL);if err!=nil||staging.Scheme!="https"||staging.User!=nil||staging.Hostname()==""{return invalid("ACME directory")};return nil}
func validateCertificatePolicy(value any)error{policy:=value.(*CertificatePolicyPayload).Policy;if !safeMailOpaque(string(policy.ID))||!safeMailOpaque(string(policy.AccountID))||len(policy.Names)==0||len(policy.Names)>100||policy.RenewBefore<24*time.Hour||policy.RenewBefore>90*24*time.Hour{return invalid("certificate policy")};for _,name:=range policy.Names{base:=strings.TrimPrefix(name,"*.");if !validMailHostname(base){return invalid("certificate name")}};return nil}
func validateCertificateIssue(value any)error{payload:=value.(*CertificateIssuePayload);if !safeMailOpaque(string(payload.PolicyID))||!safeMailOpaque(payload.IssuanceID){return invalid("certificate issuance")};return nil}
func validateCertificateDeploy(value any)error{payload:=value.(*CertificateDeployPayload);if !safeMailOpaque(string(payload.CertificateID))||(payload.Consumer!="webengine"&&payload.Consumer!="panel"&&payload.Consumer!="mail"){return invalid("certificate deployment")};return nil}
func certificateResourceScope(request RequestEnvelope,value any)(identity.Scope,error){if !safeMailOpaque(request.ResourceID){return identity.Scope{},invalid("certificate resource")};return tenantScope(request,value)}
func validateCertificateMaterialImport(value any)error{payload:=value.(*CertificateMaterialImportPayload);if !validEdgeID(payload.ResourceID)||!safeMailOpaque(payload.UploadHandle)||!safeCertificateMaterialLabel(payload.DisplayLabel)||!validCertificateMaterialNames(payload.DNSNames,payload.IPAddresses)||payload.ExpectedCertificateGeneration==CertificateMaterialUint64(^uint64(0)){return invalid("certificate material import")};return nil}
func validateCertificateMaterialSelfSigned(value any)error{payload:=value.(*CertificateMaterialSelfSignedPayload);if !validEdgeID(payload.ResourceID)||!safeCertificateMaterialLabel(payload.DisplayLabel)||(payload.Mode!=certificates.SelfSignedDevelopment&&payload.Mode!=certificates.SelfSignedRecovery)||payload.LifetimeSeconds<3600||payload.LifetimeSeconds>30*24*3600||!payload.AcknowledgeNoPublicReplacement||!validCertificateMaterialNames(payload.DNSNames,payload.IPAddresses)||payload.ExpectedCertificateGeneration==CertificateMaterialUint64(^uint64(0)){return invalid("self-signed certificate")};switch payload.KeyAlgorithm{case certificates.MaterialKeyECDSA:if payload.KeyBits!=256&&payload.KeyBits!=384&&payload.KeyBits!=521{return invalid("certificate key")};case certificates.MaterialKeyRSA:if payload.KeyBits<3072||payload.KeyBits>8192{return invalid("certificate key")};default:return invalid("certificate key")};return nil}
func validateCertificateMaterialList(value any)error{payload:=value.(*CertificateMaterialListPayload);if !validEdgeID(payload.ResourceID)||payload.Limit>certificates.MaximumMaterialListLimit||len(payload.Cursor)>512||strings.ContainsAny(payload.Cursor,"\x00\r\n\t "){return invalid("certificate material page")};return nil}
func validateCertificateMaterialInspect(value any)error{payload:=value.(*CertificateMaterialInspectPayload);if !validEdgeID(payload.ResourceID)||!validEdgeID(payload.MaterialID){return invalid("certificate material")};return nil}
func validateCertificateMaterialRetire(value any)error{payload:=value.(*CertificateMaterialRetirePayload);if validateCertificateMaterialInspect(&CertificateMaterialInspectPayload{ResourceID:payload.ResourceID,MaterialID:payload.MaterialID})!=nil||payload.ExpectedRecordGeneration==0{return invalid("certificate material retirement")};return nil}
func validateCertificateMaterialEligibility(value any)error{payload:=value.(*CertificateMaterialEligibilityPayload);if validateCertificateMaterialInspect(&CertificateMaterialInspectPayload{ResourceID:payload.ResourceID,MaterialID:payload.MaterialID})!=nil||!validEdgeID(payload.ConsumerID)||(payload.ConsumerKind!="webengine"&&payload.ConsumerKind!="application"&&payload.ConsumerKind!="panel"&&payload.ConsumerKind!="mail"&&payload.ConsumerKind!="ftps")||(payload.Purpose!="public"&&payload.Purpose!="development"&&payload.Purpose!="recovery"){return invalid("certificate deployment eligibility")};return nil}
func certificateMaterialScope(request RequestEnvelope,value any)(identity.Scope,error){if request.ResourceID!=""||request.ExpectedGeneration==^uint64(0){return identity.Scope{},invalid("certificate material scope")};return tenantScope(request,value)}
func safeCertificateMaterialLabel(value string)bool{return value!=""&&len(value)<=128&&strings.TrimSpace(value)==value&&!strings.ContainsAny(value,"\x00\r\n")}
func validCertificateMaterialNames(dnsNames,ipAddresses []string)bool{if len(dnsNames)+len(ipAddresses)==0||len(dnsNames)+len(ipAddresses)>certificates.MaximumMaterialNames{return false};for _,name:=range dnsNames{if !validMailHostname(strings.TrimPrefix(strings.ToLower(strings.TrimSuffix(name,".")),"*.")){return false}};for _,address:=range ipAddresses{if net.ParseIP(strings.TrimSpace(address))==nil{return false}};return true}

func bindCertificates(registry *Registry,services DomainServices)error{
	if err:=bindCertificateMaterials(registry,services);err!=nil{return err}
	store:=services.CertificateStore;if store==nil&&services.CertificateIssuance!=nil{store=&services.CertificateIssuance.Store}
	if store!=nil&&store.DB!=nil{
		if err:=registry.Bind("certificate.account.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*CertificatePagePayload);items,next,err:=store.Accounts(ctx,inv.Request.TenantID,page.Cursor,int(page.Limit));if err!=nil{return OperationResult{},mapCertificateError(err)};for index:=range items{items[index].AccountKeyRef="";items[index].EABKeyRef=""};return OperationResult{Status:http.StatusOK,Value:CertificatePageResult{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("certificate.account.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){account,err:=store.Account(ctx,inv.Request.TenantID,certificates.AccountID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapCertificateError(err)};account.AccountKeyRef="";account.EABKeyRef="";return OperationResult{Status:http.StatusOK,Value:account},nil});err!=nil{return err}
		if err:=registry.Bind("certificate.account.put",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){account:=value.(*CertificateAccountPayload).Account;if string(account.ID)!=inv.Request.ResourceID{return OperationResult{},ErrInvalidRequest};account.TenantID=inv.Request.TenantID;if err:=store.PutAccount(ctx,account);err!=nil{return OperationResult{},mapCertificateError(err)};account.AccountKeyRef="";account.EABKeyRef="";return OperationResult{Status:http.StatusOK,Value:account},nil});err!=nil{return err}
		if err:=registry.Bind("certificate.policy.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*CertificatePagePayload);items,next,err:=store.Policies(ctx,inv.Request.TenantID,page.Cursor,int(page.Limit));if err!=nil{return OperationResult{},mapCertificateError(err)};return OperationResult{Status:http.StatusOK,Value:CertificatePageResult{Items:items,NextCursor:next}},nil});err!=nil{return err}
		if err:=registry.Bind("certificate.policy.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){policy,err:=store.Policy(ctx,inv.Request.TenantID,certificates.PolicyID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapCertificateError(err)};return OperationResult{Status:http.StatusOK,Value:policy,Generation:policy.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("certificate.policy.put",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){policy:=value.(*CertificatePolicyPayload).Policy;if string(policy.ID)!=inv.Request.ResourceID{return OperationResult{},ErrInvalidRequest};policy.TenantID=inv.Request.TenantID;policy.Generation=inv.Request.ExpectedGeneration+1;if err:=store.PutPolicy(ctx,policy,inv.Request.ExpectedGeneration);err!=nil{return OperationResult{},mapCertificateError(err)};return OperationResult{Status:http.StatusOK,Value:policy,Generation:policy.Generation},nil});err!=nil{return err}
		listIssuances:=func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*CertificatePagePayload);items,next,err:=store.Issuances(ctx,inv.Request.TenantID,page.Cursor,int(page.Limit));if err!=nil{return OperationResult{},mapCertificateError(err)};for index:=range items{items[index].Certificate.PrivateKeyRef=""};return OperationResult{Status:http.StatusOK,Value:CertificatePageResult{Items:items,NextCursor:next}},nil}
		if err:=registry.Bind("certificate.issuance.list",listIssuances);err!=nil{return err};if err:=registry.Bind("certificate.list",listIssuances);err!=nil{return err}
		if err:=registry.Bind("certificate.issuance.get",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){issuance,err:=store.Issuance(ctx,inv.Request.TenantID,inv.Request.ResourceID);if err!=nil{return OperationResult{},mapCertificateError(err)};issuance.Certificate.PrivateKeyRef="";return OperationResult{Status:http.StatusOK,Value:issuance,Generation:issuance.PolicyGeneration},nil});err!=nil{return err}
	}
	if services.CertificateIssuance!=nil&&services.CertificateIssuance.Store.DB!=nil&&services.CertificateIssuance.ACME!=nil&&services.CertificateIssuance.Signer!=nil&&services.CertificateIssuance.Validator!=nil{
		if err:=registry.Bind("certificate.issuance.issue",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*CertificateIssuePayload);issuance,err:=services.CertificateIssuance.Issue(ctx,inv.Request.TenantID,payload.PolicyID,payload.IssuanceID,"api_"+inv.IdempotencyKey);if err!=nil{return OperationResult{},mapCertificateError(err)};issuance.Certificate.PrivateKeyRef="";return OperationResult{Status:http.StatusCreated,Value:issuance,Generation:issuance.PolicyGeneration},nil});err!=nil{return err}
		if err:=registry.Bind("certificate.renew",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){prior,err:=services.CertificateIssuance.Store.Issuance(ctx,inv.Request.TenantID,inv.Request.ResourceID);if err!=nil{return OperationResult{},mapCertificateError(err)};if inv.Request.ExpectedGeneration!=0&&prior.PolicyGeneration!=inv.Request.ExpectedGeneration{return OperationResult{},ErrConflict};issuance,err:=services.CertificateIssuance.Issue(ctx,inv.Request.TenantID,prior.PolicyID,effectID(inv),"api_"+inv.IdempotencyKey);if err!=nil{return OperationResult{},mapCertificateError(err)};issuance.Certificate.PrivateKeyRef="";return OperationResult{Status:http.StatusCreated,Value:issuance,Generation:issuance.PolicyGeneration},nil});err!=nil{return err}
	}
	if services.CertificateIssuance!=nil&&services.CertificateIssuance.Store.DB!=nil&&services.CertificateIssuance.ACME!=nil{if err:=registry.Bind("certificate.revoke",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){issuance,err:=services.CertificateIssuance.Revoke(ctx,inv.Request.TenantID,inv.Request.ResourceID,"api_"+inv.IdempotencyKey);if err!=nil{return OperationResult{},mapCertificateError(err)};return OperationResult{Status:http.StatusOK,Value:issuance,Generation:issuance.PolicyGeneration},nil});err!=nil{return err}}
	if services.CertificateDeployment!=nil&&services.CertificateDeployment.Target!=nil&&store!=nil&&store.DB!=nil{
		return registry.Bind("certificate.deployment.create",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*CertificateDeployPayload);material,err:=store.Material(ctx,inv.Request.TenantID,payload.CertificateID);if err!=nil{return OperationResult{},mapCertificateError(err)};consumer:=payload.Consumer+"/"+inv.Request.ResourceID;deployment,err:=services.CertificateDeployment.Deploy(ctx,consumer,material,effectID(inv));if err!=nil{return OperationResult{},mapCertificateError(err)};return OperationResult{Status:http.StatusCreated,Value:deployment},nil})
	}
	return nil
}

func bindCertificateMaterials(registry *Registry,services DomainServices)error{
	base:=services.CertificateMaterials
	if base==nil||base.Repository.DB==nil||base.Secrets==nil||base.ImportPolicies==nil||base.SelfSignedPolicy==nil||base.Audit==nil||services.CertificateMaterialUploads==nil{return nil}
	if err:=registry.Bind("certificate.material.import",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*CertificateMaterialImportPayload);expected,err:=certificateMaterialExpectedGeneration(inv,uint64(payload.ExpectedCertificateGeneration));if err!=nil{return OperationResult{},err};service,_:=certificateMaterialServiceForInvocation(base,inv,payload.ResourceID,"");upload,err:=services.CertificateMaterialUploads.OpenCertificateMaterialUpload(ctx,payload.UploadHandle,inv.Request.TenantID,payload.ResourceID,expected+1);payload.UploadHandle="";if err!=nil{return OperationResult{},mapCertificateError(err)};inspection,err:=service.Import(ctx,certificateMaterialPrincipal(inv),certificates.ImportMaterialRequest{TenantID:inv.Request.TenantID,ResourceID:payload.ResourceID,DisplayLabel:payload.DisplayLabel,DNSNames:append([]string(nil),payload.DNSNames...),IPAddresses:append([]string(nil),payload.IPAddresses...),ExpectedCertificateGeneration:expected,IdempotencyKey:inv.IdempotencyKey,Material:upload});if err!=nil{return OperationResult{},mapCertificateError(err)};return OperationResult{Status:http.StatusCreated,Value:inspection,Generation:inspection.CertificateGeneration},nil});err!=nil{return err}
	if err:=registry.Bind("certificate.material.self_signed",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*CertificateMaterialSelfSignedPayload);expected,err:=certificateMaterialExpectedGeneration(inv,uint64(payload.ExpectedCertificateGeneration));if err!=nil{return OperationResult{},err};service,proof:=certificateMaterialServiceForInvocation(base,inv,payload.ResourceID,"");inspection,err:=service.GenerateSelfSigned(ctx,certificateMaterialPrincipal(inv),certificates.GenerateSelfSignedMaterialRequest{TenantID:inv.Request.TenantID,ResourceID:payload.ResourceID,DisplayLabel:payload.DisplayLabel,Mode:payload.Mode,DNSNames:append([]string(nil),payload.DNSNames...),IPAddresses:append([]string(nil),payload.IPAddresses...),Lifetime:time.Duration(payload.LifetimeSeconds)*time.Second,Key:certificates.MaterialKeySpec{Algorithm:payload.KeyAlgorithm,Bits:int(payload.KeyBits)},ExpectedCertificateGeneration:expected,AcknowledgeNoPublicReplacement:payload.AcknowledgeNoPublicReplacement,IdempotencyKey:inv.IdempotencyKey,StepUpProof:proof});if err!=nil{return OperationResult{},mapCertificateError(err)};return OperationResult{Status:http.StatusCreated,Value:inspection,Generation:inspection.CertificateGeneration},nil});err!=nil{return err}
	if err:=registry.Bind("certificate.material.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*CertificateMaterialListPayload);limit:=int(payload.Limit);if limit==0{limit=100};service,_:=certificateMaterialServiceForInvocation(base,inv,payload.ResourceID,"");page,err:=service.List(ctx,certificateMaterialPrincipal(inv),certificates.ListMaterialRequest{TenantID:inv.Request.TenantID,ResourceID:payload.ResourceID,Cursor:payload.Cursor,Limit:limit});if err!=nil{return OperationResult{},mapCertificateError(err)};return OperationResult{Status:http.StatusOK,Value:page},nil});err!=nil{return err}
	if err:=registry.Bind("certificate.material.inspect",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*CertificateMaterialInspectPayload);service,_:=certificateMaterialServiceForInvocation(base,inv,payload.ResourceID,payload.MaterialID);inspection,err:=service.Inspect(ctx,certificateMaterialPrincipal(inv),certificates.InspectMaterialRequest{TenantID:inv.Request.TenantID,ResourceID:payload.ResourceID,MaterialID:payload.MaterialID});if err!=nil{return OperationResult{},mapCertificateError(err)};return OperationResult{Status:http.StatusOK,Value:inspection,Generation:inspection.RecordGeneration},nil});err!=nil{return err}
	if err:=registry.Bind("certificate.material.retire",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*CertificateMaterialRetirePayload);service,proof:=certificateMaterialServiceForInvocation(base,inv,payload.ResourceID,payload.MaterialID);inspection,err:=service.Retire(ctx,certificateMaterialPrincipal(inv),certificates.RetireMaterialRequest{TenantID:inv.Request.TenantID,ResourceID:payload.ResourceID,MaterialID:payload.MaterialID,ExpectedRecordGeneration:uint64(payload.ExpectedRecordGeneration),IdempotencyKey:inv.IdempotencyKey,StepUpProof:proof});if err!=nil{return OperationResult{},mapCertificateError(err)};return OperationResult{Status:http.StatusOK,Value:inspection,Generation:inspection.RecordGeneration},nil});err!=nil{return err}
	return registry.Bind("certificate.material.deployment_eligibility",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*CertificateMaterialEligibilityPayload);service,_:=certificateMaterialServiceForInvocation(base,inv,payload.ResourceID,payload.MaterialID);inspection,err:=service.Inspect(ctx,certificateMaterialPrincipal(inv),certificates.InspectMaterialRequest{TenantID:inv.Request.TenantID,ResourceID:payload.ResourceID,MaterialID:payload.MaterialID});if err!=nil{return OperationResult{},mapCertificateError(err)};return OperationResult{Status:http.StatusOK,Value:certificateMaterialEligibility(inspection,*payload,time.Now().UTC()),Generation:inspection.RecordGeneration},nil})
}

type certificateMaterialInvocationGate struct{inv Invocation;resourceID,materialID,proof string}
func(gate certificateMaterialInvocationGate)AuthorizeMaterial(_ context.Context,principal certificates.MaterialPrincipal,action certificates.MaterialAction,scope certificates.MaterialScope)error{expected:=map[certificates.MaterialAction]string{certificates.MaterialActionImport:"certificate.material.import",certificates.MaterialActionSelfSigned:"certificate.material.self_signed",certificates.MaterialActionList:"certificate.material.list",certificates.MaterialActionInspect:"certificate.material.inspect",certificates.MaterialActionRetire:"certificate.material.retire"}[action];if gate.inv.Request.Operation=="certificate.material.deployment_eligibility"&&action==certificates.MaterialActionInspect{expected=gate.inv.Request.Operation};if expected==""||gate.inv.Request.Operation!=expected||gate.inv.Actor.Assurance<identity.AssurancePassword||principal.TenantID!=gate.inv.Request.TenantID||principal.SubjectID!=gate.inv.Actor.PrincipalID.String()||principal.SessionID!=gate.inv.Actor.SessionID.String()||scope.TenantID!=gate.inv.Request.TenantID||scope.ResourceID!=gate.resourceID||(gate.materialID!=""&&scope.MaterialID!=gate.materialID){return certificates.ErrMaterialUnauthorized};return nil}
func(gate certificateMaterialInvocationGate)VerifyMaterialStepUp(_ context.Context,principal certificates.MaterialPrincipal,proof,binding string,_ time.Time)error{validBinding:=(strings.HasPrefix(binding,"self_signed:")&&len(binding)==len("self_signed:")+64)||(strings.HasPrefix(binding,"retire:")&&len(binding)==len("retire:")+64);if gate.inv.Actor.Assurance<identity.AssuranceMFA||gate.inv.Actor.SessionID==""||principal.SessionID!=gate.inv.Actor.SessionID.String()||proof!=gate.proof||!validBinding{return certificates.ErrMaterialStepUpRequired};return nil}
func certificateMaterialServiceForInvocation(base *certificates.MaterialService,inv Invocation,resourceID,materialID string)(certificates.MaterialService,string){proof:="api-step-up:"+inv.Request.RequestID;gate:=certificateMaterialInvocationGate{inv:inv,resourceID:resourceID,materialID:materialID,proof:proof};service:=*base;service.Authorizer=gate;service.StepUp=gate;return service,proof}
func certificateMaterialPrincipal(inv Invocation)certificates.MaterialPrincipal{return certificates.MaterialPrincipal{TenantID:inv.Request.TenantID,SubjectID:inv.Actor.PrincipalID.String(),SessionID:inv.Actor.SessionID.String()}}
func certificateMaterialExpectedGeneration(inv Invocation,payload uint64)(uint64,error){if inv.Request.ExpectedGeneration!=0&&payload!=0&&inv.Request.ExpectedGeneration!=payload{return 0,ErrConflict};if payload!=0{return payload,nil};return inv.Request.ExpectedGeneration,nil}

func certificateMaterialEligibility(inspection certificates.MaterialInspection,payload CertificateMaterialEligibilityPayload,now time.Time)CertificateMaterialDeploymentEligibility{result:=CertificateMaterialDeploymentEligibility{MaterialID:inspection.ID,CertificateFingerprint:inspection.LeafFingerprintSHA256,TrustLabel:inspection.TrustLabel,State:inspection.State,NotBefore:inspection.NotBefore,NotAfter:inspection.NotAfter};if inspection.State==certificates.MaterialStateRetired{result.ReasonCodes=append(result.ReasonCodes,"retired")};if now.Before(inspection.NotBefore){result.ReasonCodes=append(result.ReasonCodes,"not_yet_valid")};if !now.Before(inspection.NotAfter){result.ReasonCodes=append(result.ReasonCodes,"expired")};if inspection.LastDeployment!=nil&&(inspection.LastDeployment.State==certificates.MaterialDeploymentPending||inspection.LastDeployment.State==certificates.MaterialDeploymentAmbiguous){result.ReasonCodes=append(result.ReasonCodes,"deployment_state_uncertain")};switch payload.Purpose{case "public":if inspection.TrustLabel!=certificates.MaterialTrustPublicValidated&&inspection.TrustLabel!=certificates.MaterialTrustPrivateValidated{result.ReasonCodes=append(result.ReasonCodes,"untrusted_for_public_use")};case "development":if inspection.TrustLabel!=certificates.MaterialTrustDevelopment||payload.ConsumerKind!="webengine"&&payload.ConsumerKind!="application"{result.ReasonCodes=append(result.ReasonCodes,"development_scope_mismatch")};case "recovery":if inspection.TrustLabel!=certificates.MaterialTrustRecovery||payload.ConsumerKind!="panel"&&payload.ConsumerKind!="webengine"{result.ReasonCodes=append(result.ReasonCodes,"recovery_scope_mismatch")}};for _,consumer:=range inspection.Consumers{if consumer.ConsumerID==payload.ConsumerID&&consumer.ConsumerKind==payload.ConsumerKind{copy:=consumer;result.Consumer=&copy;break}};result.Eligible=len(result.ReasonCodes)==0;return result}

func mapCertificateError(err error)error{switch{case err==nil:return nil;case errors.Is(err,sql.ErrNoRows),errors.Is(err,certificates.ErrMaterialNotFound):return ErrNotFound;case errors.Is(err,certificates.ErrInvalidCertificate),errors.Is(err,certificates.ErrMaterialInvalid):return ErrInvalidRequest;case errors.Is(err,certificates.ErrMaterialUnauthorized):return ErrForbidden;case errors.Is(err,certificates.ErrMaterialStepUpRequired):return ErrAssuranceRequired;case errors.Is(err,certificates.ErrCertificateConflict),errors.Is(err,certificates.ErrMaterialConflict),errors.Is(err,certificates.ErrMaterialDuplicate),errors.Is(err,certificates.ErrMaterialOwnership),errors.Is(err,certificates.ErrMaterialNotRetirable):return ErrConflict;case errors.Is(err,certificates.ErrCertificateAmbiguous),errors.Is(err,certificates.ErrMaterialAmbiguous):return ErrUnavailable;default:return err}}
