package apiserver

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"net/http"
	"net/netip"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/containers"
	"github.com/aonsyed/cyberpanel/platform/internal/identity"
)

type ContainerImagePayload struct{RegistryCredentialID containers.ID `json:"registry_credential_id,omitempty"`;Registry string `json:"registry"`;Repository string `json:"repository"`;Tag string `json:"tag"`;Platform string `json:"platform"`}
type ContainerVolumePayload struct{Name string `json:"name"`;Class string `json:"class"`;QuotaBytes uint64 `json:"quota_bytes"`;InodeLimit uint64 `json:"inode_limit"`}
type ContainerNetworkPayload struct{Name string `json:"name"`;IPv4 netip.Prefix `json:"ipv4,omitempty"`;IPv6 netip.Prefix `json:"ipv6,omitempty"`;Internal bool `json:"internal"`;DNSPolicy string `json:"dns_policy"`}
type ContainerWorkloadPayload struct{ProjectID containers.ID `json:"project_id,omitempty"`;SiteID containers.ID `json:"site_id,omitempty"`;Name string `json:"name"`;Tier containers.RuntimeTier `json:"tier"`;Spec containers.WorkloadSpec `json:"spec"`}
type ContainerLifecyclePayload struct{Lifecycle containers.Lifecycle `json:"lifecycle"`;CommitAuthorizationDigest string `json:"commit_authorization_digest"`}
type ContainerExposurePayload struct{Exposure containers.Exposure `json:"exposure"`}
type ContainerApplicationDeployPayload struct{SiteID containers.ID `json:"site_id"`;RecipeID containers.ID `json:"recipe_id"`;RecipeVersion string `json:"recipe_version"`}
type ContainerApplicationUpdatePayload struct{RecipeID containers.ID `json:"recipe_id"`;RecipeVersion string `json:"recipe_version"`;BackwardCompatibleData bool `json:"backward_compatible_data"`}
type ContainerExecExchangePayload struct{GrantID containers.ID `json:"grant_id"`;Token string `json:"token"`}

func registerContainerContracts(registry *Registry)error{
	operations:=[]Operation{
		{Name:"container.image.pull",Permission:identity.MustPermission("container:manage"),Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ContainerImagePayload{}},ResolveScope:tenantScope},
		{Name:"container.volume.ensure",Permission:identity.MustPermission("container:manage"),Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ContainerVolumePayload{}},ResolveScope:tenantScope},
		{Name:"container.network.ensure",Permission:identity.MustPermission("container:manage"),Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ContainerNetworkPayload{}},ResolveScope:tenantScope},
		{Name:"container.workload.apply",Permission:identity.MustPermission("container:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ContainerWorkloadPayload{}},ResolveScope:tenantScope},
		{Name:"container.workload.lifecycle",Permission:identity.MustPermission("container:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ContainerLifecyclePayload{}},ResolveScope:tenantScope},
		{Name:"container.exposure.apply",Permission:identity.MustPermission("container:expose"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ContainerExposurePayload{}},ResolveScope:tenantScope},
		{Name:"container.application.deploy",Permission:identity.MustPermission("container:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ContainerApplicationDeployPayload{}},ResolveScope:tenantScope},
		{Name:"container.application.update",Permission:identity.MustPermission("container:manage"),Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &ContainerApplicationUpdatePayload{}},ResolveScope:tenantScope},
		{Name:"container.exec.exchange",Auth:AuthNone,Mutating:true,MaximumBodyBytes:16<<10,NewPayload:func()any{return &ContainerExecExchangePayload{}},ValidatePayload:func(value any)error{payload:=value.(*ContainerExecExchangePayload);if !payload.GrantID.Valid()||len(payload.Token)<32||len(payload.Token)>512{return invalid("container exec exchange")};return nil},ResolveScope:globalScope},
	}
	for _,operation:=range operations{if err:=register(registry,operation);err!=nil{return err}}
	return nil
}

func containerMeta(inv Invocation,operation string,resource containers.ID)containers.CommandMeta{tenant,_:=containers.NewID(inv.Request.TenantID);sum:=sha256.Sum256([]byte(inv.Actor.PrincipalID.String()+"\x00"+operation+"\x00"+resource.String()+"\x00"+inv.IdempotencyKey));grant:=containers.Grant{TenantID:tenant,ResourceID:resource,Operation:operation,AuthzEpoch:inv.Actor.AuthzEpoch,ExpiresAt:time.Now().UTC().Add(30*time.Second),Digest:hex.EncodeToString(sum[:])};fence:=inv.Request.ExpectedGeneration+1;if fence==0{fence=1};return containers.CommandMeta{CommandID:commandID(inv),Grant:grant,ExpectedGeneration:inv.Request.ExpectedGeneration,Fence:containers.FenceToken(fence)}}

func bindContainers(registry *Registry,services DomainServices)error{
	if services.Containers!=nil{
		if err:=registry.Bind("container.image.pull",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){resource,err:=containers.NewID(inv.Request.ResourceID);if err!=nil{return OperationResult{},ErrInvalidRequest};p:=value.(*ContainerImagePayload);image,result,err:=services.Containers.PullImage(ctx,containers.PullImageCommand{Meta:containerMeta(inv,"image.pull",resource),ImageID:resource,RegistryCredentialID:p.RegistryCredentialID,Registry:p.Registry,Repository:p.Repository,Tag:p.Tag,Platform:p.Platform});if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:struct{Image containers.Image `json:"image"`;Operation containers.Result `json:"operation"`}{image,result},Generation:image.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("container.volume.ensure",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){resource,err:=containers.NewID(inv.Request.ResourceID);if err!=nil{return OperationResult{},ErrInvalidRequest};p:=value.(*ContainerVolumePayload);volume,result,err:=services.Containers.EnsureVolume(ctx,containers.EnsureVolumeCommand{Meta:containerMeta(inv,"volume.ensure",resource),VolumeID:resource,Name:p.Name,Class:p.Class,QuotaBytes:p.QuotaBytes,InodeLimit:p.InodeLimit});if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:struct{Volume containers.Volume `json:"volume"`;Operation containers.Result `json:"operation"`}{volume,result},Generation:volume.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("container.network.ensure",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){resource,err:=containers.NewID(inv.Request.ResourceID);if err!=nil{return OperationResult{},ErrInvalidRequest};p:=value.(*ContainerNetworkPayload);network,result,err:=services.Containers.EnsureNetwork(ctx,containers.EnsureNetworkCommand{Meta:containerMeta(inv,"network.ensure",resource),NetworkID:resource,Name:p.Name,IPv4:p.IPv4,IPv6:p.IPv6,Internal:p.Internal,DNSPolicy:p.DNSPolicy});if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:struct{Network containers.Network `json:"network"`;Operation containers.Result `json:"operation"`}{network,result},Generation:network.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("container.workload.apply",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){resource,err:=containers.NewID(inv.Request.ResourceID);if err!=nil{return OperationResult{},ErrInvalidRequest};p:=value.(*ContainerWorkloadPayload);workload,result,err:=services.Containers.ApplyWorkload(ctx,containers.ApplyWorkloadCommand{Meta:containerMeta(inv,"workload.apply",resource),WorkloadID:resource,ProjectID:p.ProjectID,SiteID:p.SiteID,Name:p.Name,Tier:p.Tier,Spec:p.Spec});if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:struct{Workload containers.Workload `json:"workload"`;Operation containers.Result `json:"operation"`}{workload,result},Generation:workload.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("container.workload.lifecycle",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){resource,err:=containers.NewID(inv.Request.ResourceID);if err!=nil{return OperationResult{},ErrInvalidRequest};p:=value.(*ContainerLifecyclePayload);workload,result,err:=services.Containers.SetLifecycle(ctx,containers.LifecycleCommand{Meta:containerMeta(inv,"workload.lifecycle",resource),WorkloadID:resource,Lifecycle:p.Lifecycle,CommitAuthorizationDigest:p.CommitAuthorizationDigest});if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:struct{Workload containers.Workload `json:"workload"`;Operation containers.Result `json:"operation"`}{workload,result},Generation:workload.Generation},nil});err!=nil{return err}
		if err:=registry.Bind("container.exposure.apply",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){resource,err:=containers.NewID(inv.Request.ResourceID);if err!=nil{return OperationResult{},ErrInvalidRequest};p:=value.(*ContainerExposurePayload);p.Exposure.ID=resource;exposure,result,err:=services.Containers.ApplyExposure(ctx,containers.ApplyExposureCommand{Meta:containerMeta(inv,"exposure.apply",resource),Exposure:p.Exposure});if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:struct{Exposure containers.Exposure `json:"exposure"`;Operation containers.Result `json:"operation"`}{exposure,result},Generation:exposure.Generation},nil});err!=nil{return err}
	}
	if services.ContainerApplications!=nil{
		if err:=registry.Bind("container.application.deploy",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){resource,err:=containers.NewID(inv.Request.ResourceID);if err!=nil{return OperationResult{},ErrInvalidRequest};p:=value.(*ContainerApplicationDeployPayload);application,results,err:=services.ContainerApplications.Deploy(ctx,containers.DeployApplicationCommand{Meta:containerMeta(inv,"application.deploy",resource),ApplicationID:resource,SiteID:p.SiteID,RecipeID:p.RecipeID,RecipeVersion:p.RecipeVersion});if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusCreated,Value:struct{Application containers.ContainerApplication `json:"application"`;Operations []containers.Result `json:"operations"`}{application,results},Generation:application.ActiveGeneration},nil});err!=nil{return err}
		if err:=registry.Bind("container.application.update",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){resource,err:=containers.NewID(inv.Request.ResourceID);if err!=nil{return OperationResult{},ErrInvalidRequest};p:=value.(*ContainerApplicationUpdatePayload);application,results,err:=services.ContainerApplications.Update(ctx,containers.UpdateApplicationCommand{Meta:containerMeta(inv,"application.deploy",resource),ApplicationID:resource,RecipeID:p.RecipeID,RecipeVersion:p.RecipeVersion,BackwardCompatibleData:p.BackwardCompatibleData});if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:struct{Application containers.ContainerApplication `json:"application"`;Operations []containers.Result `json:"operations"`}{application,results},Generation:application.ActiveGeneration},nil});err!=nil{return err}
	}
	if services.Containers!=nil{if err:=registry.Bind("container.exec.exchange",func(ctx context.Context,_ Invocation,value any)(OperationResult,error){payload:=value.(*ContainerExecExchangePayload);receipt,err:=services.Containers.ExchangeExec(ctx,payload.GrantID,payload.Token);payload.Token="";if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:receipt},nil});err!=nil{return err}}
	return nil
}
