package apiserver

import (
	"context"
	"net/http"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/access"
	"github.com/aonsyed/cyberpanel/platform/internal/identity"
)

type FTPSCreatePayload struct{Account access.FTPSAccount `json:"account"`;Password []byte `json:"password"`}
type FTPSRotatePayload struct{AccountID access.FTPSAccountID `json:"account_id"`;Password []byte `json:"password"`}
type FTPSSetEnabledPayload struct{AccountID access.FTPSAccountID `json:"account_id"`;Enabled bool `json:"enabled"`}
type FTPSIDPayload struct{AccountID access.FTPSAccountID `json:"account_id"`}
type SSHKeyRegisterPayload struct{KeyID access.SSHKeyID `json:"key_id"`;Name string `json:"name"`;AuthorizedKey string `json:"authorized_key"`}
type SSHKeyIDPayload struct{KeyID access.SSHKeyID `json:"key_id"`}
type AccessGrantPayload struct{Grant access.AccessGrant `json:"grant"`}
type AccessGrantIDPayload struct{GrantID access.AccessGrantID `json:"grant_id"`}
type TerminalOpenPayload struct{GrantID access.AccessGrantID `json:"grant_id"`;Columns uint16 `json:"columns"`;Rows uint16 `json:"rows"`;ClientNonce string `json:"client_nonce"`}
type TerminalClosePayload struct{SessionID access.TerminalSessionID `json:"session_id"`}
type CronJobPayload struct{Job access.CronJob `json:"job"`}
type CronIDPayload struct{JobID access.CronJobID `json:"job_id"`}
type CronListPayload struct{IncludePending bool `json:"include_pending"`}
type GitRepositoryPayload struct{Repository access.GitRepository `json:"repository"`}
type GitRepositoryIDPayload struct{RepositoryID access.GitRepositoryID `json:"repository_id"`}
type GitFetchPayload struct{RepositoryID access.GitRepositoryID `json:"repository_id"`;Prune bool `json:"prune"`}
type GitLogPayload struct{RepositoryID access.GitRepositoryID `json:"repository_id"`;Page access.PageRequest `json:"page"`}
type GitCheckoutPayload struct{RepositoryID access.GitRepositoryID `json:"repository_id"`;Branch string `json:"branch"`;Force bool `json:"force"`}
type GitCommitPayload struct{RepositoryID access.GitRepositoryID `json:"repository_id"`;Changes access.GitChangeSet `json:"changes"`}
type GitPushPayload struct{RepositoryID access.GitRepositoryID `json:"repository_id"`;Ref string `json:"ref"`}
type GitIgnorePayload struct{RepositoryID access.GitRepositoryID `json:"repository_id"`;Rules []string `json:"rules"`}
type GitDetachPayload struct{RepositoryID access.GitRepositoryID `json:"repository_id"`;RetainFiles bool `json:"retain_files"`}
type DeployKeyPayload struct{Key access.DeployKey `json:"key"`}
type DeploymentPayload struct{Deployment access.Deployment `json:"deployment"`}
type DeploymentIDPayload struct{DeploymentID access.DeploymentID `json:"deployment_id"`}
type StagingPayload struct{Sync access.StagingSync `json:"sync"`}

func registerAccessDeveloperContracts(registry *Registry)error{
	read:=identity.MustPermission("file:read");write:=identity.MustPermission("file:write");manage:=identity.MustPermission("site:manage")
	definitions:=[]Operation{
		{Name:"access.ftps.create",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,MaximumBodyBytes:1<<20,NewPayload:func()any{return &FTPSCreatePayload{}},ValidatePayload:validateFTPSCreate,ResolveScope:siteScope},
		{Name:"access.ftps.rotate",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &FTPSRotatePayload{}},ValidatePayload:validateFTPSRotate,ResolveScope:siteScope},
		{Name:"access.ftps.set_enabled",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &FTPSSetEnabledPayload{}},ValidatePayload:validateFTPSSetEnabled,ResolveScope:siteScope},
		{Name:"access.ftps.delete",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &FTPSIDPayload{}},ValidatePayload:validateFTPSID,ResolveScope:siteScope},
		{Name:"access.ssh_key.register",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &SSHKeyRegisterPayload{}},ValidatePayload:validateSSHKeyRegister,ResolveScope:tenantScope},
		{Name:"access.ssh_key.revoke",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &SSHKeyIDPayload{}},ValidatePayload:validateSSHKeyID,ResolveScope:tenantScope},
		{Name:"access.grant.create",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &AccessGrantPayload{}},ValidatePayload:validateAccessGrant,ResolveScope:siteScope},
		{Name:"access.grant.revoke",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &AccessGrantIDPayload{}},ValidatePayload:validateAccessGrantID,ResolveScope:siteScope},
		{Name:"access.terminal.open",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &TerminalOpenPayload{}},ValidatePayload:validateTerminalOpen,ResolveScope:siteScope},
		{Name:"access.terminal.close",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &TerminalClosePayload{}},ValidatePayload:validateTerminalClose,ResolveScope:siteScope},
		{Name:"access.cron.list",Permission:read,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &CronListPayload{}},ResolveScope:siteScope},
		{Name:"access.cron.get",Permission:read,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &CronIDPayload{}},ValidatePayload:validateCronID,ResolveScope:siteScope},
		{Name:"access.cron.create",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &CronJobPayload{}},ValidatePayload:validateCronJob,ResolveScope:siteScope},
		{Name:"access.cron.update",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &CronJobPayload{}},ValidatePayload:validateCronJob,ResolveScope:siteScope},
		{Name:"access.cron.delete",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &CronIDPayload{}},ValidatePayload:validateCronID,ResolveScope:siteScope},
		{Name:"access.cron.run",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &CronIDPayload{}},ValidatePayload:validateCronID,ResolveScope:siteScope},
		{Name:"access.git.status",Permission:read,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &GitRepositoryIDPayload{}},ValidatePayload:validateGitID,ResolveScope:siteScope},
		{Name:"access.git.log",Permission:read,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &GitLogPayload{}},ValidatePayload:validateGitLog,ResolveScope:siteScope},
		{Name:"access.git.fetch",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &GitFetchPayload{}},ValidatePayload:validateGitFetch,ResolveScope:siteScope},
		{Name:"access.git.attach",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &GitRepositoryPayload{}},ValidatePayload:validateGitRepository,ResolveScope:siteScope},
		{Name:"access.git.initialize",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &GitRepositoryPayload{}},ValidatePayload:validateGitRepository,ResolveScope:siteScope},
		{Name:"access.git.checkout",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &GitCheckoutPayload{}},ValidatePayload:validateGitCheckout,ResolveScope:siteScope},
		{Name:"access.git.pull",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &GitRepositoryIDPayload{}},ValidatePayload:validateGitID,ResolveScope:siteScope},
		{Name:"access.git.commit",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &GitCommitPayload{}},ValidatePayload:validateGitCommit,ResolveScope:siteScope},
		{Name:"access.git.push",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &GitPushPayload{}},ValidatePayload:validateGitPush,ResolveScope:siteScope},
		{Name:"access.git.ignore",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &GitIgnorePayload{}},ValidatePayload:validateGitIgnore,ResolveScope:siteScope},
		{Name:"access.git.detach",Permission:write,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &GitDetachPayload{}},ValidatePayload:validateGitDetach,ResolveScope:siteScope},
		{Name:"access.git.deploy_key.create",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &DeployKeyPayload{}},ValidatePayload:validateDeployKey,ResolveScope:siteScope},
		{Name:"access.git.deployment.create",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &DeploymentPayload{}},ValidatePayload:validateDeployment,ResolveScope:siteScope},
		{Name:"access.git.deployment.execute",Permission:write,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &DeploymentIDPayload{}},ValidatePayload:validateDeploymentID,ResolveScope:siteScope},
		{Name:"access.staging.sync",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &StagingPayload{}},ValidatePayload:validateStaging,ResolveScope:siteScope},
	}
	for _,definition:=range definitions{if err:=register(registry,definition);err!=nil{return err}}
	return nil
}

func validAccessID(value string)bool{return safeMailOpaque(value)}
func validSecret(value []byte)bool{return len(value)>=12&&len(value)<=1024}
func validateFTPSCreate(value any)error{payload:=value.(*FTPSCreatePayload);if !validAccessID(string(payload.Account.ID))||!validSecret(payload.Password){return invalid("FTPS account")};return nil}
func validateFTPSRotate(value any)error{payload:=value.(*FTPSRotatePayload);if !validAccessID(string(payload.AccountID))||!validSecret(payload.Password){return invalid("FTPS password")};return nil}
func validateFTPSSetEnabled(value any)error{if !validAccessID(string(value.(*FTPSSetEnabledPayload).AccountID)){return invalid("FTPS account")};return nil}
func validateFTPSID(value any)error{if !validAccessID(string(value.(*FTPSIDPayload).AccountID)){return invalid("FTPS account")};return nil}
func validateSSHKeyRegister(value any)error{payload:=value.(*SSHKeyRegisterPayload);if !validAccessID(string(payload.KeyID))||strings.TrimSpace(payload.Name)==""||len(payload.Name)>128{return invalid("SSH key")};if _,err:=access.ParsePublicKey(payload.AuthorizedKey);err!=nil{return invalid("SSH key")};return nil}
func validateSSHKeyID(value any)error{if !validAccessID(string(value.(*SSHKeyIDPayload).KeyID)){return invalid("SSH key")};return nil}
func validateAccessGrant(value any)error{grant:=value.(*AccessGrantPayload).Grant;if !validAccessID(string(grant.ID))||!validAccessID(string(grant.SiteID)){return invalid("access grant")};return nil}
func validateAccessGrantID(value any)error{if !validAccessID(string(value.(*AccessGrantIDPayload).GrantID)){return invalid("access grant")};return nil}
func validateTerminalOpen(value any)error{payload:=value.(*TerminalOpenPayload);if !validAccessID(string(payload.GrantID))||payload.Columns<20||payload.Columns>500||payload.Rows<5||payload.Rows>300||len(payload.ClientNonce)<16||len(payload.ClientNonce)>256||strings.ContainsAny(payload.ClientNonce,"\x00\r\n"){return invalid("terminal request")};return nil}
func validateTerminalClose(value any)error{if !validAccessID(string(value.(*TerminalClosePayload).SessionID)){return invalid("terminal session")};return nil}
func validateCronID(value any)error{if !validAccessID(string(value.(*CronIDPayload).JobID)){return invalid("cron job")};return nil}
func validateCronJob(value any)error{job:=value.(*CronJobPayload).Job;if !validAccessID(string(job.ID))||!validAccessID(string(job.SiteID)){return invalid("cron job")};candidate:=job;candidate.Generation=1;candidate.State=access.StatePending;candidate.CreatedAt=time.Unix(1,0).UTC();candidate.UpdatedAt=candidate.CreatedAt;if candidate.Validate()!=nil{return invalid("cron job")};return nil}
func validateGitID(value any)error{if !validAccessID(string(value.(*GitRepositoryIDPayload).RepositoryID)){return invalid("Git repository")};return nil}
func validateGitFetch(value any)error{if !validAccessID(string(value.(*GitFetchPayload).RepositoryID)){return invalid("Git repository")};return nil}
func validateGitLog(value any)error{payload:=value.(*GitLogPayload);if !validAccessID(string(payload.RepositoryID))||payload.Page.Limit>1000||len(payload.Page.Cursor)>1024{return invalid("Git log")};return nil}
func validateGitRepository(value any)error{repository:=value.(*GitRepositoryPayload).Repository;if !validAccessID(string(repository.ID))||!validAccessID(string(repository.SiteID)){return invalid("Git repository")};return nil}
func validateGitCheckout(value any)error{payload:=value.(*GitCheckoutPayload);if !validAccessID(string(payload.RepositoryID))||len(payload.Branch)==0||len(payload.Branch)>255||strings.ContainsAny(payload.Branch,"\x00\r\n "){return invalid("Git checkout")};return nil}
func validateGitCommit(value any)error{payload:=value.(*GitCommitPayload);if !validAccessID(string(payload.RepositoryID))||len(payload.Changes.Paths)>access.MaxBatchPaths||strings.TrimSpace(payload.Changes.Message)==""||len(payload.Changes.Message)>4096{return invalid("Git commit")};return nil}
func validateGitPush(value any)error{payload:=value.(*GitPushPayload);if !validAccessID(string(payload.RepositoryID))||len(payload.Ref)==0||len(payload.Ref)>255||strings.ContainsAny(payload.Ref,"\x00\r\n "){return invalid("Git push")};return nil}
func validateGitIgnore(value any)error{payload:=value.(*GitIgnorePayload);if !validAccessID(string(payload.RepositoryID))||len(payload.Rules)>4096{return invalid("gitignore")};for _,rule:=range payload.Rules{if len(rule)>4096||strings.ContainsAny(rule,"\x00\r"){return invalid("gitignore")}};return nil}
func validateGitDetach(value any)error{if !validAccessID(string(value.(*GitDetachPayload).RepositoryID)){return invalid("Git repository")};return nil}
func validateDeployKey(value any)error{key:=value.(*DeployKeyPayload).Key;if !validAccessID(string(key.ID))||!validAccessID(string(key.RepositoryID))||!validAccessID(string(key.SiteID))||strings.TrimSpace(key.Name)==""||len(key.Name)>128{return invalid("deploy key")};return nil}
func validateDeployment(value any)error{deployment:=value.(*DeploymentPayload).Deployment;if !validAccessID(string(deployment.ID))||!validAccessID(string(deployment.RepositoryID))||!validAccessID(string(deployment.SiteID)){return invalid("deployment")};return nil}
func validateDeploymentID(value any)error{if !validAccessID(string(value.(*DeploymentIDPayload).DeploymentID)){return invalid("deployment")};return nil}
func validateStaging(value any)error{sync:=value.(*StagingPayload).Sync;if !validAccessID(string(sync.ID))||!validAccessID(string(sync.LiveSiteID))||!validAccessID(string(sync.StagingSiteID)){return invalid("staging sync")};return nil}

func bindAccessDeveloper(registry *Registry,services DomainServices)error{
	if err:=bindAccessCredentials(registry,services.Credentials);err!=nil{return err}
	if err:=bindAccessCron(registry,services.Cron);err!=nil{return err}
	if err:=bindAccessGit(registry,services.Git);err!=nil{return err}
	if services.Staging!=nil&&services.Staging.Executor!=nil&&services.Staging.Store!=nil{return registry.Bind("access.staging.sync",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){sync:=value.(*StagingPayload).Sync;if string(sync.LiveSiteID)!=inv.Request.ResourceID&&string(sync.StagingSiteID)!=inv.Request.ResourceID{return OperationResult{},ErrForbidden};result,err:=services.Staging.Execute(ctx,sync);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:result,Generation:result.Generation},nil})}
	return nil
}

func bindAccessCredentials(registry *Registry,service *access.CredentialService)error{
	if service==nil||service.Store==nil||service.Executor==nil{return nil}
	if err:=registry.Bind("access.ftps.create",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*FTPSCreatePayload);account:=payload.Account;account.SiteID=access.SiteID(inv.Request.ResourceID);account.Root.SiteID=account.SiteID;secret,err:=access.NewSecretMaterial(payload.Password);clearSecret(payload.Password);if err!=nil{return OperationResult{},ErrInvalidRequest};created,err:=service.CreateFTPS(ctx,account,&secret);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusCreated,Value:created,Generation:created.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("access.ftps.rotate",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*FTPSRotatePayload);account,err:=service.Store.LoadFTPS(ctx,payload.AccountID);if err!=nil{return OperationResult{},mapDomainError(err)};if string(account.SiteID)!=inv.Request.ResourceID||account.Generation!=inv.Request.ExpectedGeneration{return OperationResult{},ErrConflict};secret,err:=access.NewSecretMaterial(payload.Password);clearSecret(payload.Password);if err!=nil{return OperationResult{},ErrInvalidRequest};updated,err:=service.RotateFTPSPassword(ctx,payload.AccountID,&secret);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:updated,Generation:updated.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("access.ftps.set_enabled",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*FTPSSetEnabledPayload);account,err:=service.Store.LoadFTPS(ctx,payload.AccountID);if err!=nil{return OperationResult{},mapDomainError(err)};if string(account.SiteID)!=inv.Request.ResourceID||account.Generation!=inv.Request.ExpectedGeneration{return OperationResult{},ErrConflict};updated,err:=service.SetFTPSEnabled(ctx,payload.AccountID,payload.Enabled);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:updated,Generation:updated.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("access.ftps.delete",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){id:=value.(*FTPSIDPayload).AccountID;account,err:=service.Store.LoadFTPS(ctx,id);if err!=nil{return OperationResult{},mapDomainError(err)};if string(account.SiteID)!=inv.Request.ResourceID||account.Generation!=inv.Request.ExpectedGeneration{return OperationResult{},ErrConflict};if err=service.DeleteFTPS(ctx,id);err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"deleted"}},nil});err!=nil{return err}
	if err:=registry.Bind("access.ssh_key.register",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*SSHKeyRegisterPayload);public,err:=access.ParsePublicKey(payload.AuthorizedKey);payload.AuthorizedKey="";if err!=nil{return OperationResult{},ErrInvalidRequest};key,err:=service.RegisterSSHKey(ctx,access.SSHKey{ID:payload.KeyID,TenantID:access.TenantID(inv.Request.TenantID),PrincipalID:access.PrincipalID(inv.Actor.PrincipalID.String()),Name:payload.Name,PublicKey:public});if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusCreated,Value:key,Generation:key.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("access.ssh_key.revoke",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){id:=value.(*SSHKeyIDPayload).KeyID;key,err:=service.Store.LoadSSHKey(ctx,id);if err!=nil{return OperationResult{},mapDomainError(err)};if key.TenantID!=access.TenantID(inv.Request.TenantID)||key.PrincipalID!=access.PrincipalID(inv.Actor.PrincipalID.String())||key.Generation!=inv.Request.ExpectedGeneration{return OperationResult{},ErrForbidden};if err=service.RevokeSSHKey(ctx,id);err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"revoked"}},nil});err!=nil{return err}
	if err:=registry.Bind("access.grant.create",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){grant:=value.(*AccessGrantPayload).Grant;grant.SiteID=access.SiteID(inv.Request.ResourceID);grant.Root.SiteID=grant.SiteID;grant.TenantID=access.TenantID(inv.Request.TenantID);grant.PrincipalID=access.PrincipalID(inv.Actor.PrincipalID.String());created,err:=service.Grant(ctx,grant);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusCreated,Value:created,Generation:created.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("access.grant.revoke",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){id:=value.(*AccessGrantIDPayload).GrantID;grant,err:=service.Store.LoadAccessGrant(ctx,id);if err!=nil{return OperationResult{},mapDomainError(err)};if string(grant.SiteID)!=inv.Request.ResourceID||grant.TenantID!=access.TenantID(inv.Request.TenantID)||grant.PrincipalID!=access.PrincipalID(inv.Actor.PrincipalID.String())||grant.Generation!=inv.Request.ExpectedGeneration{return OperationResult{},ErrForbidden};if err=service.RevokeGrant(ctx,id);err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"revoked"}},nil});err!=nil{return err}
	if err:=registry.Bind("access.terminal.open",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*TerminalOpenPayload);grant,err:=service.Store.LoadAccessGrant(ctx,payload.GrantID);if err!=nil{return OperationResult{},mapDomainError(err)};if string(grant.SiteID)!=inv.Request.ResourceID||grant.TenantID!=access.TenantID(inv.Request.TenantID)||grant.PrincipalID!=access.PrincipalID(inv.Actor.PrincipalID.String()){return OperationResult{},ErrForbidden};session,err:=service.OpenTerminal(ctx,access.TerminalRequest{GrantID:payload.GrantID,SourceIP:inv.Meta.ClientIP.String(),Columns:payload.Columns,Rows:payload.Rows,ClientNonce:payload.ClientNonce});payload.ClientNonce="";if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusCreated,Value:session},nil});err!=nil{return err}
	return registry.Bind("access.terminal.close",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){id:=value.(*TerminalClosePayload).SessionID;session,err:=service.Store.LoadTerminalSession(ctx,id);if err!=nil{return OperationResult{},mapDomainError(err)};grant,err:=service.Store.LoadAccessGrant(ctx,session.GrantID);if err!=nil{return OperationResult{},mapDomainError(err)};if string(grant.SiteID)!=inv.Request.ResourceID||grant.TenantID!=access.TenantID(inv.Request.TenantID)||grant.PrincipalID!=access.PrincipalID(inv.Actor.PrincipalID.String()){return OperationResult{},ErrForbidden};if err=service.CloseTerminal(ctx,id);err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"closed"}},nil})
}

func bindAccessCron(registry *Registry,service *access.CronService)error{
	if service==nil||service.Store==nil||service.Executor==nil{return nil}
	if err:=registry.Bind("access.cron.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){jobs,err:=service.Store.ListCrons(ctx,access.SiteID(inv.Request.ResourceID),value.(*CronListPayload).IncludePending);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:jobs},nil});err!=nil{return err}
	if err:=registry.Bind("access.cron.get",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){job,err:=service.Store.LoadCron(ctx,value.(*CronIDPayload).JobID);if err!=nil{return OperationResult{},mapDomainError(err)};if string(job.SiteID)!=inv.Request.ResourceID{return OperationResult{},ErrForbidden};return OperationResult{Status:http.StatusOK,Value:job,Generation:job.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("access.cron.create",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){job:=value.(*CronJobPayload).Job;job.SiteID=access.SiteID(inv.Request.ResourceID);created,err:=service.Create(ctx,job);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusCreated,Value:created,Generation:created.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("access.cron.update",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){job:=value.(*CronJobPayload).Job;job.SiteID=access.SiteID(inv.Request.ResourceID);updated,err:=service.Update(ctx,job,inv.Request.ExpectedGeneration);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:updated,Generation:updated.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("access.cron.delete",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){id:=value.(*CronIDPayload).JobID;job,err:=service.Store.LoadCron(ctx,id);if err!=nil{return OperationResult{},mapDomainError(err)};if string(job.SiteID)!=inv.Request.ResourceID{return OperationResult{},ErrForbidden};if err=service.Delete(ctx,id,inv.Request.ExpectedGeneration);err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"deleted"}},nil});err!=nil{return err}
	return registry.Bind("access.cron.run",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){id:=value.(*CronIDPayload).JobID;job,err:=service.Store.LoadCron(ctx,id);if err!=nil{return OperationResult{},mapDomainError(err)};if string(job.SiteID)!=inv.Request.ResourceID{return OperationResult{},ErrForbidden};run,err:=service.RunNow(ctx,id);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusAccepted,Value:run},nil})
}

func bindAccessGit(registry *Registry,service *access.GitService)error{
	if service==nil||service.Store==nil||service.Executor==nil{return nil}
	owned:=func(ctx context.Context,inv Invocation,id access.GitRepositoryID)(access.GitRepository,error){repository,err:=service.Store.LoadRepository(ctx,id);if err!=nil{return repository,mapDomainError(err)};if string(repository.SiteID)!=inv.Request.ResourceID{return repository,ErrForbidden};return repository,nil}
	if err:=registry.Bind("access.git.status",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){id:=value.(*GitRepositoryIDPayload).RepositoryID;if _,err:=owned(ctx,inv,id);err!=nil{return OperationResult{},err};status,err:=service.Status(ctx,id);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:status},nil});err!=nil{return err}
	if err:=registry.Bind("access.git.log",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*GitLogPayload);if _,err:=owned(ctx,inv,payload.RepositoryID);err!=nil{return OperationResult{},err};page,err:=service.Log(ctx,payload.RepositoryID,payload.Page);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:page},nil});err!=nil{return err}
	if err:=registry.Bind("access.git.fetch",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*GitFetchPayload);if _,err:=owned(ctx,inv,payload.RepositoryID);err!=nil{return OperationResult{},err};status,err:=service.Fetch(ctx,payload.RepositoryID,payload.Prune);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:status},nil});err!=nil{return err}
	if err:=registry.Bind("access.git.attach",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){repository:=value.(*GitRepositoryPayload).Repository;repository.SiteID=access.SiteID(inv.Request.ResourceID);repository.Worktree.Root.SiteID=repository.SiteID;created,err:=service.Attach(ctx,repository);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusCreated,Value:created,Generation:created.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("access.git.initialize",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){repository:=value.(*GitRepositoryPayload).Repository;repository.SiteID=access.SiteID(inv.Request.ResourceID);repository.Worktree.Root.SiteID=repository.SiteID;created,err:=service.Initialize(ctx,repository);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusCreated,Value:created,Generation:created.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("access.git.checkout",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*GitCheckoutPayload);repository,err:=owned(ctx,inv,payload.RepositoryID);if err!=nil{return OperationResult{},err};if repository.Generation!=inv.Request.ExpectedGeneration{return OperationResult{},ErrConflict};updated,status,err:=service.ChangeBranch(ctx,payload.RepositoryID,payload.Branch,payload.Force);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]any{"repository":updated,"status":status},Generation:updated.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("access.git.pull",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){id:=value.(*GitRepositoryIDPayload).RepositoryID;repository,err:=owned(ctx,inv,id);if err!=nil{return OperationResult{},err};if repository.Generation!=inv.Request.ExpectedGeneration{return OperationResult{},ErrConflict};updated,status,err:=service.Pull(ctx,id);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]any{"repository":updated,"status":status},Generation:updated.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("access.git.commit",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*GitCommitPayload);repository,err:=owned(ctx,inv,payload.RepositoryID);if err!=nil{return OperationResult{},err};if repository.Generation!=inv.Request.ExpectedGeneration{return OperationResult{},ErrConflict};commit,err:=service.Commit(ctx,payload.RepositoryID,payload.Changes);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusCreated,Value:commit},nil});err!=nil{return err}
	if err:=registry.Bind("access.git.push",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*GitPushPayload);if _,err:=owned(ctx,inv,payload.RepositoryID);err!=nil{return OperationResult{},err};status,err:=service.Push(ctx,payload.RepositoryID,payload.Ref);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:status},nil});err!=nil{return err}
	if err:=registry.Bind("access.git.ignore",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*GitIgnorePayload);if _,err:=owned(ctx,inv,payload.RepositoryID);err!=nil{return OperationResult{},err};receipt,err:=service.WriteIgnore(ctx,payload.RepositoryID,payload.Rules);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"receipt":receipt}},nil});err!=nil{return err}
	if err:=registry.Bind("access.git.detach",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*GitDetachPayload);repository,err:=owned(ctx,inv,payload.RepositoryID);if err!=nil{return OperationResult{},err};if repository.Generation!=inv.Request.ExpectedGeneration{return OperationResult{},ErrConflict};if err=service.Detach(ctx,payload.RepositoryID,payload.RetainFiles);err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"detached"}},nil});err!=nil{return err}
	if err:=registry.Bind("access.git.deploy_key.create",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){key:=value.(*DeployKeyPayload).Key;if string(key.SiteID)!=inv.Request.ResourceID{return OperationResult{},ErrForbidden};created,err:=service.GenerateDeployKey(ctx,key);if err!=nil{return OperationResult{},mapDomainError(err)};created.PrivateKeyRef="";return OperationResult{Status:http.StatusCreated,Value:created,Generation:created.Generation},nil});err!=nil{return err}
	if err:=registry.Bind("access.git.deployment.create",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){deployment:=value.(*DeploymentPayload).Deployment;deployment.SiteID=access.SiteID(inv.Request.ResourceID);deployment.Trigger=access.TriggerManual;created,err:=service.RequestDeployment(ctx,deployment);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusAccepted,Value:created,Generation:created.Generation},nil});err!=nil{return err}
	return registry.Bind("access.git.deployment.execute",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){id:=value.(*DeploymentIDPayload).DeploymentID;deployment,err:=service.Store.LoadDeployment(ctx,id);if err!=nil{return OperationResult{},mapDomainError(err)};if string(deployment.SiteID)!=inv.Request.ResourceID{return OperationResult{},ErrForbidden};updated,err:=service.ExecuteDeployment(ctx,id);if err!=nil{return OperationResult{},mapDomainError(err)};return OperationResult{Status:http.StatusOK,Value:updated,Generation:updated.Generation},nil})
}
