package apiserver

import (
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"io"
	"math"
	"net/http"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/identity"
	"github.com/aonsyed/cyberpanel/platform/internal/mail"
)

type MailPagePayload struct{Limit uint16 `json:"limit"`;Cursor string `json:"cursor,omitempty"`}
type MailPageResult struct{Items []mail.ResourceEnvelope `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type MailDomainPayload struct{Domain mail.Domain `json:"domain"`}
type MailMailboxPayload struct{Mailbox mail.Mailbox `json:"mailbox"`}
type MailAliasPayload struct{Alias mail.Alias `json:"alias"`}
type MailPolicyPayload struct{Policy mail.Policy `json:"policy"`}
type MailDKIMPreparePayload struct{OverlapSeconds uint32 `json:"overlap_seconds,omitempty"`;CurrentSecretVersion uint64 `json:"current_secret_version,omitempty"`;CurrentSecretBindingDigest string `json:"current_secret_binding_digest,omitempty"`;CurrentSecretResourceGeneration uint64 `json:"current_secret_resource_generation,omitempty"`}
type MailDKIMActivatePayload struct{ConfirmPrevious bool `json:"confirm_previous,omitempty"`}
type MailQueueFlushPayload struct{Limit uint16 `json:"limit,omitempty"`;Cursor string `json:"cursor,omitempty"`}
type MailQueueFlushResult struct{Items []mail.OperationReceipt `json:"items"`;NextCursor string `json:"next_cursor,omitempty"`}
type EmptyPayload struct{}

type WebmailSessionIssuePayload struct{TTLSeconds uint32 `json:"ttl_seconds"`}
type WebmailFoldersPayload struct{Session mail.MailSession `json:"session"`;MailboxID mail.MailboxID `json:"mailbox_id,omitempty"`}
type WebmailSearchPayload struct{Session mail.MailSession `json:"session"`;MailboxID mail.MailboxID `json:"mailbox_id,omitempty"`;Query mail.MessageQuery `json:"query"`;FolderID mail.FolderID `json:"folder_id,omitempty"`;Terms string `json:"terms,omitempty"`;Cursor string `json:"cursor,omitempty"`;Limit uint16 `json:"limit,omitempty"`;Sort string `json:"sort,omitempty"`}
type WebmailReadPayload struct{Session mail.MailSession `json:"session"`;MailboxID mail.MailboxID `json:"mailbox_id,omitempty"`;MessageID mail.MessageID `json:"message_id"`}
type WebmailAttachmentPayload struct{Session mail.MailSession `json:"session"`;MailboxID mail.MailboxID `json:"mailbox_id,omitempty"`;MessageID mail.MessageID `json:"message_id"`;AttachmentID mail.AttachmentID `json:"attachment_id"`;MaximumBytes uint64 `json:"maximum_bytes"`}
type WebmailAttachmentResult struct{Info mail.AttachmentInfo `json:"info"`;ContentBase64 string `json:"content_base64"`}
type WebmailMovePayload struct{Session mail.MailSession `json:"session"`;MailboxID mail.MailboxID `json:"mailbox_id,omitempty"`;MessageID mail.MessageID `json:"message_id"`;FolderID mail.FolderID `json:"folder_id,omitempty"`;FolderRole string `json:"folder_role,omitempty"`}
type WebmailDeletePayload struct{Session mail.MailSession `json:"session"`;MailboxID mail.MailboxID `json:"mailbox_id,omitempty"`;MessageID mail.MessageID `json:"message_id"`}
type WebmailFlagsPayload struct{Session mail.MailSession `json:"session"`;MailboxID mail.MailboxID `json:"mailbox_id,omitempty"`;MessageID mail.MessageID `json:"message_id"`;Flags []string `json:"flags"`}
type WebmailDraftPayload struct{Session mail.MailSession `json:"session"`;Draft mail.DraftRecord `json:"draft"`}
type WebmailSendPayload struct{Session mail.MailSession `json:"session"`;MailboxID mail.MailboxID `json:"mailbox_id,omitempty"`;Message mail.ComposeMessage `json:"message"`;To []mail.Address `json:"to,omitempty"`;CC []mail.Address `json:"cc,omitempty"`;BCC []mail.Address `json:"bcc,omitempty"`;Subject string `json:"subject,omitempty"`;Text string `json:"text,omitempty"`;SanitizedHTML string `json:"sanitized_html,omitempty"`;AttachmentBlobRefs []string `json:"attachment_blob_refs,omitempty"`;InReplyTo mail.MessageID `json:"in_reply_to,omitempty"`}

func registerMailContracts(registry *Registry)error{
	manage:=identity.MustPermission("mail:manage")
	definitions:=[]Operation{
		{Name:"mail.domain.list",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MailPagePayload{}},ValidatePayload:validateMailPage,ResolveScope:mailListScope},
		{Name:"mail.domain.get",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"mail.domain.create",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MailDomainPayload{}},ValidatePayload:validateMailDomain,ResolveScope:mailCreateScope},
		{Name:"mail.domain.update",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MailDomainPayload{}},ValidatePayload:validateMailDomain,ResolveScope:mailExistingScope},
		{Name:"mail.domain.delete",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailExistingScope},
		{Name:"mail.domain.dkim.prepare",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MailDKIMPreparePayload{}},ValidatePayload:validateMailDKIMPrepare,ResolveScope:mailExistingScope},
		{Name:"mail.domain.dkim.status",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"mail.domain.dkim.activate",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MailDKIMActivatePayload{}},ResolveScope:mailExistingScope},
		{Name:"mail.mailbox.list",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MailPagePayload{}},ValidatePayload:validateMailPage,ResolveScope:mailListScope},
		{Name:"mail.mailbox.get",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"mail.mailbox.create",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MailMailboxPayload{}},ValidatePayload:validateMailMailbox,ResolveScope:mailCreateScope},
		{Name:"mail.mailbox.update",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MailMailboxPayload{}},ValidatePayload:validateMailMailbox,ResolveScope:mailExistingScope},
		{Name:"mail.mailbox.delete",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailExistingScope},
		{Name:"mail.alias.list",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MailPagePayload{}},ValidatePayload:validateMailPage,ResolveScope:mailListScope},
		{Name:"mail.alias.get",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"mail.alias.create",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MailAliasPayload{}},ValidatePayload:validateMailAlias,ResolveScope:mailCreateScope},
		{Name:"mail.alias.update",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MailAliasPayload{}},ValidatePayload:validateMailAlias,ResolveScope:mailExistingScope},
		{Name:"mail.alias.delete",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailExistingScope},
		{Name:"mail.policy.list",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MailPagePayload{}},ValidatePayload:validateMailPage,ResolveScope:mailListScope},
		{Name:"mail.policy.get",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"mail.policy.create",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MailPolicyPayload{}},ValidatePayload:validateMailPolicy,ResolveScope:mailCreateScope},
		{Name:"mail.policy.update",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MailPolicyPayload{}},ValidatePayload:validateMailPolicy,ResolveScope:mailExistingScope},
		{Name:"mail.policy.delete",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailExistingScope},
		{Name:"mail.queue.list",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MailPagePayload{}},ValidatePayload:validateMailPage,ResolveScope:mailListScope},
		{Name:"mail.queue.get",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"mail.queue.inspect",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailGetScope},
		{Name:"mail.queue.retry",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailExistingScope},
		{Name:"mail.queue.flush",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &MailQueueFlushPayload{}},ValidatePayload:validateMailQueueFlush,ResolveScope:mailListScope},
		{Name:"mail.queue.cancel",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailExistingScope},
		{Name:"mail.queue.delete",Permission:manage,Assurance:identity.AssuranceMFA,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &EmptyPayload{}},ResolveScope:mailExistingScope},
		{Name:"webmail.mailbox.list",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &MailPagePayload{}},ValidatePayload:validateMailPage,ResolveScope:mailListScope},
		{Name:"webmail.session.issue",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &WebmailSessionIssuePayload{}},ValidatePayload:func(value any)error{ttl:=value.(*WebmailSessionIssuePayload).TTLSeconds;if ttl<60||ttl>1800{return invalid("webmail session lifetime")};return nil},ResolveScope:mailGetScope},
		{Name:"webmail.folder.list",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &WebmailFoldersPayload{}},ValidatePayload:validateWebmailSessionPayload,ResolveScope:webmailScope},
		{Name:"webmail.message.search",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &WebmailSearchPayload{}},ValidatePayload:validateWebmailSearch,ResolveScope:webmailScope},
		{Name:"webmail.message.list",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,NewPayload:func()any{return &WebmailSearchPayload{}},ValidatePayload:validateWebmailSearch,ResolveScope:webmailScope},
		{Name:"webmail.message.read",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,MaximumResponseBytes:8<<20,NewPayload:func()any{return &WebmailReadPayload{}},ValidatePayload:validateWebmailRead,ResolveScope:webmailScope},
		{Name:"webmail.message.get",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,MaximumResponseBytes:8<<20,NewPayload:func()any{return &WebmailReadPayload{}},ValidatePayload:validateWebmailRead,ResolveScope:webmailScope},
		{Name:"webmail.attachment.read",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,MaximumResponseBytes:8<<20,NewPayload:func()any{return &WebmailAttachmentPayload{}},ValidatePayload:validateWebmailAttachment,ResolveScope:webmailScope},
		{Name:"webmail.message.move",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &WebmailMovePayload{}},ValidatePayload:validateWebmailMove,ResolveScope:webmailScope},
		{Name:"webmail.message.delete",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &WebmailDeletePayload{}},ValidatePayload:validateWebmailDelete,ResolveScope:webmailScope},
		{Name:"webmail.message.flags",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &WebmailFlagsPayload{}},ValidatePayload:validateWebmailFlags,ResolveScope:webmailScope},
		{Name:"webmail.draft.save",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &WebmailDraftPayload{}},ValidatePayload:validateWebmailDraft,ResolveScope:webmailScope},
		{Name:"webmail.message.send",Permission:manage,Assurance:identity.AssurancePassword,Auth:AuthRequired,Mutating:true,NewPayload:func()any{return &WebmailSendPayload{}},ValidatePayload:validateWebmailSend,ResolveScope:webmailScope},
	}
	for _,definition:=range definitions{if err:=register(registry,definition);err!=nil{return err}}
	return nil
}

func validateMailPage(value any)error{payload:=value.(*MailPagePayload);if payload.Limit>500||len(payload.Cursor)>1024{return invalid("mail page")};return nil}
func validateMailQueueFlush(value any)error{payload:=value.(*MailQueueFlushPayload);if payload.Limit==0{payload.Limit=500};if payload.Limit>1000||len(payload.Cursor)>1024{return invalid("mail queue page")};return nil}
func validateMailDomain(value any)error{domain:=value.(*MailDomainPayload).Domain;if !safeMailOpaque(string(domain.ID))||!validMailHostname(domain.Name)||!safeMailOpaque(string(domain.Policy))||len(domain.DKIM.PublicKey)>16<<10{return invalid("mail domain")};if domain.DKIM.Enabled&&(!safeMailLabel(domain.DKIM.Selector,63)||!safeMailOpaque(domain.DKIM.PrivateKeyRef)){return invalid("mail DKIM")};if domain.Relay.Host!=""&&(!validMailHostname(domain.Relay.Host)||domain.Relay.Port==0||!safeMailOpaque(domain.Relay.CredentialRef)){return invalid("mail relay")};return nil}
func validateMailDKIMPrepare(value any)error{payload:=value.(*MailDKIMPreparePayload);if payload.OverlapSeconds==0{payload.OverlapSeconds=uint32(mail.DKIMDefaultOverlap/time.Second)};overlap:=time.Duration(payload.OverlapSeconds)*time.Second;if overlap<mail.DKIMMinimumOverlap||overlap>mail.DKIMMaximumOverlap{return invalid("mail DKIM overlap")};payload.CurrentSecretBindingDigest=strings.ToLower(strings.TrimSpace(payload.CurrentSecretBindingDigest));present:=payload.CurrentSecretVersion!=0||payload.CurrentSecretBindingDigest!=""||payload.CurrentSecretResourceGeneration!=0;if present&&(payload.CurrentSecretVersion==0||payload.CurrentSecretResourceGeneration==0||!validDigestReference(payload.CurrentSecretBindingDigest)){return invalid("mail DKIM current secret")};return nil}
func validateMailMailbox(value any)error{mailbox:=value.(*MailMailboxPayload).Mailbox;if !safeMailOpaque(string(mailbox.ID))||!safeMailOpaque(string(mailbox.Domain))||!safeMailboxLocal(mailbox.Local)||mailbox.QuotaBytes==0||mailbox.QuotaBytes>1<<50{return invalid("mail mailbox")};return nil}
func validateMailAlias(value any)error{alias:=value.(*MailAliasPayload).Alias;if !safeMailOpaque(string(alias.ID))||!safeMailOpaque(string(alias.Domain))||!safeMailAddress(alias.Source)||len(alias.Targets)==0||len(alias.Targets)>1000{return invalid("mail alias")};for _,target:=range alias.Targets{if !safeMailAddress(target){return invalid("mail alias targets")}};switch alias.Capability{case "",mail.CapabilityPlus,mail.CapabilityPattern:if alias.PipeRef!=""{return invalid("mail alias pipe")};case mail.CapabilityPipe:if !safeMailOpaque(alias.PipeRef){return invalid("mail alias pipe")};default:return invalid("mail alias capability")};return nil}
func validateMailPolicy(value any)error{policy:=value.(*MailPolicyPayload).Policy;if !safeMailOpaque(string(policy.ID))||policy.MaxMailboxBytes==0||policy.MaxMailboxBytes>1<<50||policy.MaxRecipients==0||policy.MaxRecipients>10000||math.IsNaN(policy.SpamThreshold)||math.IsInf(policy.SpamThreshold,0)||policy.SpamThreshold < -100||policy.SpamThreshold>100||policy.RetainDays>3650||policy.Log.RetainDays>3650{return invalid("mail policy")};return nil}
func validateWebmailSession(session mail.MailSession)error{if !safeMailOpaque(session.ID)||len(session.Token)<64||len(session.Token)>4096||!safeMailToken(session.Token)||session.ExpiresAt.IsZero()||session.ExpiresAt.Before(time.Now().Add(-time.Minute))||session.ExpiresAt.After(time.Now().Add(31*time.Minute)){return invalid("mail session")};return nil}
func validOptionalMailbox(value mail.MailboxID)bool{return value==""||safeMailOpaque(string(value))}
func validateWebmailSessionPayload(value any)error{payload:=value.(*WebmailFoldersPayload);if validateWebmailSession(payload.Session)!=nil||!validOptionalMailbox(payload.MailboxID){return invalid("webmail session")};return nil}
func validateWebmailSearch(value any)error{payload:=value.(*WebmailSearchPayload);nested:=payload.Query!=(mail.MessageQuery{});flat:=payload.FolderID!=""||payload.Terms!=""||payload.Cursor!=""||payload.Limit!=0||payload.Sort!="";if nested&&flat{return invalid("webmail search shape")};if flat{payload.Query=mail.MessageQuery{FolderID:payload.FolderID,Terms:payload.Terms,Cursor:payload.Cursor,Limit:payload.Limit,Sort:payload.Sort}};if validateWebmailSession(payload.Session)!=nil||!validOptionalMailbox(payload.MailboxID)||!safeMailOpaque(string(payload.Query.FolderID))||payload.Query.Limit>200||len(payload.Query.Terms)>512||len(payload.Query.Cursor)>1024||strings.ContainsAny(payload.Query.Terms+payload.Query.Cursor,"\x00\r\n")||(payload.Query.Sort!=""&&payload.Query.Sort!="newest"&&payload.Query.Sort!="oldest"){return invalid("webmail search")};return nil}
func validateWebmailRead(value any)error{payload:=value.(*WebmailReadPayload);if validateWebmailSession(payload.Session)!=nil||!validOptionalMailbox(payload.MailboxID)||!safeMailOpaque(string(payload.MessageID)){return invalid("webmail message")};return nil}
func validateWebmailAttachment(value any)error{payload:=value.(*WebmailAttachmentPayload);if validateWebmailSession(payload.Session)!=nil||!validOptionalMailbox(payload.MailboxID)||!safeMailOpaque(string(payload.MessageID))||!safeMailOpaque(string(payload.AttachmentID))||payload.MaximumBytes==0||payload.MaximumBytes>4<<20{return invalid("webmail attachment")};return nil}
func validateWebmailMove(value any)error{payload:=value.(*WebmailMovePayload);role:=strings.ToLower(strings.TrimSpace(payload.FolderRole));payload.FolderRole=role;if validateWebmailSession(payload.Session)!=nil||!validOptionalMailbox(payload.MailboxID)||!safeMailOpaque(string(payload.MessageID))||(payload.FolderID=="")== (role==""){return invalid("webmail move")};if payload.FolderID!=""&&!safeMailOpaque(string(payload.FolderID)){return invalid("webmail move")};switch role{case"","archive","trash","junk","sent","drafts":default:return invalid("webmail folder role")};return nil}
func validateWebmailDelete(value any)error{payload:=value.(*WebmailDeletePayload);if validateWebmailSession(payload.Session)!=nil||!validOptionalMailbox(payload.MailboxID)||!safeMailOpaque(string(payload.MessageID)){return invalid("webmail delete")};return nil}
func validateWebmailFlags(value any)error{payload:=value.(*WebmailFlagsPayload);if validateWebmailSession(payload.Session)!=nil||!validOptionalMailbox(payload.MailboxID)||!safeMailOpaque(string(payload.MessageID))||len(payload.Flags)>32{return invalid("webmail flags")};return nil}
func validateWebmailDraft(value any)error{payload:=value.(*WebmailDraftPayload);if validateWebmailSession(payload.Session)!=nil||!safeMailOpaque(string(payload.Draft.ID))||!safeCompose(payload.Draft.Message){return invalid("webmail draft")};return nil}
func validateWebmailSend(value any)error{payload:=value.(*WebmailSendPayload);nested:=payload.Message.From!=""||len(payload.Message.To)>0||len(payload.Message.CC)>0||len(payload.Message.BCC)>0||payload.Message.Subject!=""||payload.Message.Text!=""||payload.Message.SanitizedHTML!=""||len(payload.Message.AttachmentBlobRefs)>0||payload.Message.InReplyTo!="";flat:=len(payload.To)>0||len(payload.CC)>0||len(payload.BCC)>0||payload.Subject!=""||payload.Text!=""||payload.SanitizedHTML!=""||len(payload.AttachmentBlobRefs)>0||payload.InReplyTo!="";if nested&&flat{return invalid("webmail message shape")};if flat{payload.Message=mail.ComposeMessage{To:payload.To,CC:payload.CC,BCC:payload.BCC,Subject:payload.Subject,Text:payload.Text,SanitizedHTML:payload.SanitizedHTML,AttachmentBlobRefs:payload.AttachmentBlobRefs,InReplyTo:payload.InReplyTo}};if validateWebmailSession(payload.Session)!=nil||!validOptionalMailbox(payload.MailboxID)||!safeCompose(payload.Message){return invalid("webmail send")};return nil}

func mailListScope(request RequestEnvelope,value any)(identity.Scope,error){if request.ResourceID!=""||request.ExpectedGeneration!=0{return identity.Scope{},invalid("mail list scope")};return tenantScope(request,value)}
func mailGetScope(request RequestEnvelope,value any)(identity.Scope,error){if !safeMailOpaque(request.ResourceID)||request.ExpectedGeneration!=0{return identity.Scope{},invalid("mail resource scope")};return tenantScope(request,value)}
func mailCreateScope(request RequestEnvelope,value any)(identity.Scope,error){if !safeMailOpaque(request.ResourceID)||request.ExpectedGeneration!=0{return identity.Scope{},invalid("mail create scope")};return tenantScope(request,value)}
func mailExistingScope(request RequestEnvelope,value any)(identity.Scope,error){if !safeMailOpaque(request.ResourceID)||request.ExpectedGeneration==0{return identity.Scope{},invalid("mail resource generation")};return tenantScope(request,value)}
func webmailScope(request RequestEnvelope,value any)(identity.Scope,error){if !safeMailOpaque(request.ResourceID){return identity.Scope{},invalid("webmail mailbox scope")};return tenantScope(request,value)}

func safeMailOpaque(value string)bool{if value==""||len(value)>160{return false};for index:=range value{character:=value[index];if !(character>='a'&&character<='z'||character>='A'&&character<='Z'||character>='0'&&character<='9'||character=='-'||character=='_'||character=='.'){return false}};return true}
func safeMailToken(value string)bool{for index:=range value{character:=value[index];if !(character>='a'&&character<='z'||character>='A'&&character<='Z'||character>='0'&&character<='9'||character=='-'||character=='_'){return false}};return true}
func safeMailLabel(value string,maximum int)bool{if value==""||len(value)>maximum{return false};for index:=range value{character:=value[index];if !(character>='a'&&character<='z'||character>='A'&&character<='Z'||character>='0'&&character<='9'||character=='-'){return false}};return true}
func validMailHostname(value string)bool{value=strings.TrimSuffix(strings.ToLower(strings.TrimSpace(value)),".");if len(value)<3||len(value)>253||!strings.Contains(value,"."){return false};for _,label:=range strings.Split(value,"."){if !safeMailLabel(label,63)||label[0]=='-'||label[len(label)-1]=='-'{return false}};return true}
func safeMailboxLocal(value string)bool{if value==""||len(value)>64||value[0]=='.'||value[len(value)-1]=='.'||strings.Contains(value,".."){return false};for index:=range value{character:=value[index];if !(character>='a'&&character<='z'||character>='A'&&character<='Z'||character>='0'&&character<='9'||strings.ContainsRune(".!#$%&'*+-=?^_`{|}~",rune(character))){return false}};return true}
func safeMailAddress(value mail.Address)bool{raw:=strings.ToLower(strings.TrimSpace(string(value)));if len(raw)>254||strings.Count(raw,"@")!=1{return false};parts:=strings.SplitN(raw,"@",2);return safeMailboxLocal(parts[0])&&validMailHostname(parts[1])}
func safeCompose(message mail.ComposeMessage)bool{if len(message.Subject)>998||strings.ContainsAny(message.Subject,"\x00\r\n")||len(message.Text)>1<<20||len(message.SanitizedHTML)>1<<20||strings.Contains(message.Text,"\x00")||strings.Contains(message.SanitizedHTML,"\x00")||len(message.AttachmentBlobRefs)>100{return false};total:=len(message.To)+len(message.CC)+len(message.BCC);if total==0||total>500{return false};for _,address:=range append(append(append([]mail.Address{},message.To...),message.CC...),message.BCC...){if !safeMailAddress(address){return false}};for _,reference:=range message.AttachmentBlobRefs{if !safeMailOpaque(reference){return false}};return message.InReplyTo==""||safeMailOpaque(string(message.InReplyTo))}

func bindMail(registry *Registry,services DomainServices)error{
	if services.MailControl!=nil&&services.MailControl.Store!=nil{
		for name,kind:=range map[string]mail.ResourceKind{"mail.domain.list":mail.ResourceDomain,"mail.mailbox.list":mail.ResourceMailbox,"webmail.mailbox.list":mail.ResourceMailbox,"mail.alias.list":mail.ResourceAlias,"mail.policy.list":mail.ResourcePolicy}{name,kind:=name,kind;if err:=registry.Bind(name,func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MailPagePayload);items,next,err:=services.MailControl.Store.List(ctx,inv.Request.TenantID,kind,int(page.Limit),page.Cursor);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:MailPageResult{Items:items,NextCursor:next}},nil});err!=nil{return err}}
		for name,kind:=range map[string]mail.ResourceKind{"mail.domain.get":mail.ResourceDomain,"mail.mailbox.get":mail.ResourceMailbox,"mail.alias.get":mail.ResourceAlias,"mail.policy.get":mail.ResourcePolicy}{name,kind:=name,kind;if err:=registry.Bind(name,func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){resource,found,err:=services.MailControl.Store.Load(ctx,inv.Request.TenantID,kind,inv.Request.ResourceID);if err!=nil{return OperationResult{},mapMailError(err)};if !found{return OperationResult{},ErrNotFound};return OperationResult{Status:http.StatusOK,Value:resource,Generation:resource.Generation},nil});err!=nil{return err}}
		bindings:=[]struct{name string;kind mail.ResourceKind;action mail.Action;payload func(any)(any,string)}{
			{"mail.domain.create",mail.ResourceDomain,mail.ActionCreate,domainMailResource},{"mail.domain.update",mail.ResourceDomain,mail.ActionUpdate,domainMailResource},{"mail.domain.delete",mail.ResourceDomain,mail.ActionDelete,nil},
			{"mail.mailbox.create",mail.ResourceMailbox,mail.ActionCreate,mailboxMailResource},{"mail.mailbox.update",mail.ResourceMailbox,mail.ActionUpdate,mailboxMailResource},{"mail.mailbox.delete",mail.ResourceMailbox,mail.ActionDelete,nil},
			{"mail.alias.create",mail.ResourceAlias,mail.ActionCreate,aliasMailResource},{"mail.alias.update",mail.ResourceAlias,mail.ActionUpdate,aliasMailResource},{"mail.alias.delete",mail.ResourceAlias,mail.ActionDelete,nil},
			{"mail.policy.create",mail.ResourcePolicy,mail.ActionCreate,policyMailResource},{"mail.policy.update",mail.ResourcePolicy,mail.ActionUpdate,policyMailResource},{"mail.policy.delete",mail.ResourcePolicy,mail.ActionDelete,nil},
		}
		for _,binding:=range bindings{binding:=binding;if err:=registry.Bind(binding.name,func(ctx context.Context,inv Invocation,value any)(OperationResult,error){command:=newMailCommand(inv,binding.kind,binding.action);if binding.payload!=nil{resource,id:=binding.payload(value);if id!=inv.Request.ResourceID{return OperationResult{},invalid("mail resource identity")};switch typed:=resource.(type){case mail.Domain:typed.Tenant=inv.Request.TenantID;command.Domain=&typed;case mail.Mailbox:command.Mailbox=&typed;case mail.Alias:command.Alias=&typed;case mail.Policy:command.Policy=&typed}};receipt,err:=services.MailControl.Handle(ctx,command);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:receipt,Generation:receipt.Request.Generation},nil});err!=nil{return err}}
		if rotation:=services.MailControl.DKIMRotation;rotation!=nil{
			if err:=registry.Bind("mail.domain.dkim.prepare",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*MailDKIMPreparePayload);var proof *mail.DKIMSecretProof;if payload.CurrentSecretVersion!=0{proof=&mail.DKIMSecretProof{Version:payload.CurrentSecretVersion,BindingDigest:payload.CurrentSecretBindingDigest,ResourceGeneration:payload.CurrentSecretResourceGeneration}};status,err:=rotation.Prepare(ctx,mail.DKIMPrepareRequest{TenantID:inv.Request.TenantID,DomainID:mail.DomainID(inv.Request.ResourceID),ExpectedGeneration:inv.Request.ExpectedGeneration,OperationID:commandID(inv),Overlap:time.Duration(payload.OverlapSeconds)*time.Second,CurrentSecret:proof});if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusCreated,Value:status,Generation:status.CurrentGeneration},nil});err!=nil{return err}
			if err:=registry.Bind("mail.domain.dkim.status",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){status,err:=rotation.Status(ctx,inv.Request.TenantID,mail.DomainID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:status,Generation:status.CurrentGeneration},nil});err!=nil{return err}
			if err:=registry.Bind("mail.domain.dkim.activate",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){status,err:=rotation.Activate(ctx,mail.DKIMActivateRequest{TenantID:inv.Request.TenantID,DomainID:mail.DomainID(inv.Request.ResourceID),ExpectedGeneration:inv.Request.ExpectedGeneration,ConfirmPrevious:value.(*MailDKIMActivatePayload).ConfirmPrevious});if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:status,Generation:status.CurrentGeneration},nil});err!=nil{return err}
		}
	}
	if services.MailQueue!=nil{
		if err:=registry.Bind("mail.queue.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){page:=value.(*MailPagePayload);if page.Cursor!=""{return OperationResult{},ErrInvalidRequest};items,evidence,err:=services.MailQueue.ListQueue(ctx,uint32(page.Limit));if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]any{"items":items,"evidence_digest":evidence}},nil});err!=nil{return err}
		for _,name:=range []string{"mail.queue.get","mail.queue.inspect"}{name:=name;if err:=registry.Bind(name,func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){items,evidence,err:=services.MailQueue.ListQueue(ctx,10000);if err!=nil{return OperationResult{},mapMailError(err)};for _,item:=range items{if string(item.ID)==inv.Request.ResourceID{return OperationResult{Status:http.StatusOK,Value:map[string]any{"item":item,"evidence_digest":evidence}},nil}};return OperationResult{},ErrNotFound});err!=nil{return err}}
		for name,action:=range map[string]mail.MailQueueAction{"mail.queue.retry":mail.QueueRetry,"mail.queue.cancel":mail.QueueDelete,"mail.queue.delete":mail.QueueDelete}{name,action:=name,action;if err:=registry.Bind(name,func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){receipt,err:=services.MailQueue.Queue(ctx,action,mail.QueueID(inv.Request.ResourceID));if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:receipt},nil});err!=nil{return err}}
		if err:=registry.Bind("mail.queue.flush",func(ctx context.Context,inv Invocation,_ any)(OperationResult,error){receipt,err:=services.MailQueue.Queue(ctx,mail.QueueFlush,"");if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:receipt},nil});err!=nil{return err}
	}
	authority:=services.MailSessions
	if authority==nil&&services.Webmail!=nil{authority,_=services.Webmail.Sessions.(*mail.MailSessionAuthority)}
	if authority!=nil&&services.MailControl!=nil&&services.MailControl.Store!=nil{
		if err:=registry.Bind("webmail.session.issue",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){
			resource,found,err:=services.MailControl.Store.Load(ctx,inv.Request.TenantID,mail.ResourceMailbox,inv.Request.ResourceID);if err!=nil{return OperationResult{},mapMailError(err)};if !found||resource.State!=mail.StateActive{return OperationResult{},ErrNotFound}
			_,decoded,err:=canonicalPayload(resource.Spec,func()any{return &mail.Mailbox{}},func(value any)error{return validateMailMailbox(&MailMailboxPayload{Mailbox:*value.(*mail.Mailbox)})});if err!=nil{return OperationResult{},ErrUnavailable};mailbox:=decoded.(*mail.Mailbox);if string(mailbox.ID)!=resource.ID{return OperationResult{},ErrUnavailable}
			issued,err:=authority.IssueMailSession(ctx,mail.MailSession{TenantID:inv.Request.TenantID,MailboxID:mailbox.ID,PrincipalID:inv.Actor.PrincipalID.String(),AuthzEpoch:inv.Actor.AuthzEpoch},time.Duration(value.(*WebmailSessionIssuePayload).TTLSeconds)*time.Second);if err!=nil{return OperationResult{},mapMailError(err)}
			return OperationResult{Status:http.StatusCreated,Value:issued},nil
		});err!=nil{return err}
	}
	if services.Webmail!=nil{return bindWebmail(registry,services.Webmail)}
	return nil
}

func newMailCommand(inv Invocation,kind mail.ResourceKind,action mail.Action)mail.Command{sum:=sha256.Sum256([]byte(inv.IdempotencyKey));commandSum:=sha256.Sum256([]byte(inv.Request.TenantID+"\x00"+inv.Actor.PrincipalID.String()+"\x00"+inv.Request.Operation+"\x00"+inv.IdempotencyKey));return mail.Command{ID:"mailcmd_"+hex.EncodeToString(commandSum[:])[:48],IdempotencyKey:"api_"+hex.EncodeToString(sum[:]),ActorID:inv.Actor.PrincipalID.String(),TenantID:inv.Request.TenantID,Kind:kind,ResourceID:inv.Request.ResourceID,ExpectedGeneration:inv.Request.ExpectedGeneration,Action:action}}
func newMailCommandForResource(inv Invocation,kind mail.ResourceKind,action mail.Action,resource string,generation uint64)mail.Command{sum:=sha256.Sum256([]byte(inv.IdempotencyKey+"\x00"+resource));commandSum:=sha256.Sum256([]byte(inv.Request.TenantID+"\x00"+inv.Actor.PrincipalID.String()+"\x00"+inv.Request.Operation+"\x00"+inv.IdempotencyKey+"\x00"+resource));return mail.Command{ID:"mailcmd_"+hex.EncodeToString(commandSum[:])[:48],IdempotencyKey:"api_"+hex.EncodeToString(sum[:]),ActorID:inv.Actor.PrincipalID.String(),TenantID:inv.Request.TenantID,Kind:kind,ResourceID:resource,ExpectedGeneration:generation,Action:action}}
func domainMailResource(value any)(any,string){resource:=value.(*MailDomainPayload).Domain;return resource,string(resource.ID)}
func mailboxMailResource(value any)(any,string){resource:=value.(*MailMailboxPayload).Mailbox;return resource,string(resource.ID)}
func aliasMailResource(value any)(any,string){resource:=value.(*MailAliasPayload).Alias;return resource,string(resource.ID)}
func policyMailResource(value any)(any,string){resource:=value.(*MailPolicyPayload).Policy;return resource,string(resource.ID)}

func bindWebmail(registry *Registry,service *mail.WebmailService)error{
	if err:=registry.Bind("webmail.folder.list",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*WebmailFoldersPayload);session,err:=boundWebmailSession(ctx,service,inv,payload.Session,payload.MailboxID);if err!=nil{return OperationResult{},err};folders,err:=service.Folders(ctx,session);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:folders},nil});err!=nil{return err}
	search:=func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*WebmailSearchPayload);session,err:=boundWebmailSession(ctx,service,inv,payload.Session,payload.MailboxID);if err!=nil{return OperationResult{},err};page,err:=service.Search(ctx,session,payload.Query);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:page},nil}
	if err:=registry.Bind("webmail.message.search",search);err!=nil{return err};if err:=registry.Bind("webmail.message.list",search);err!=nil{return err}
	read:=func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*WebmailReadPayload);session,err:=boundWebmailSession(ctx,service,inv,payload.Session,payload.MailboxID);if err!=nil{return OperationResult{},err};message,err:=service.Read(ctx,session,payload.MessageID);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:message},nil}
	if err:=registry.Bind("webmail.message.read",read);err!=nil{return err};if err:=registry.Bind("webmail.message.get",read);err!=nil{return err}
	if err:=registry.Bind("webmail.attachment.read",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*WebmailAttachmentPayload);session,err:=boundWebmailSession(ctx,service,inv,payload.Session,payload.MailboxID);if err!=nil{return OperationResult{},err};stream,err:=service.Attachment(ctx,session,payload.MessageID,payload.AttachmentID);if err!=nil{return OperationResult{},mapMailError(err)};defer stream.Reader.Close();if stream.Info.Size>payload.MaximumBytes{return OperationResult{},ErrResponseTooLarge};content,err:=io.ReadAll(io.LimitReader(stream.Reader,int64(payload.MaximumBytes)+1));if err!=nil||uint64(len(content))>payload.MaximumBytes{return OperationResult{},ErrResponseTooLarge};encoded:=base64.RawStdEncoding.EncodeToString(content);clearSecret(content);return OperationResult{Status:http.StatusOK,Value:WebmailAttachmentResult{Info:stream.Info,ContentBase64:encoded}},nil});err!=nil{return err}
	if err:=registry.Bind("webmail.message.move",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*WebmailMovePayload);session,err:=boundWebmailSession(ctx,service,inv,payload.Session,payload.MailboxID);if err!=nil{return OperationResult{},err};folder:=payload.FolderID;if folder==""{folders,listErr:=service.Folders(ctx,session);if listErr!=nil{return OperationResult{},mapMailError(listErr)};folder,err=webmailFolderForRole(folders,payload.FolderRole);if err!=nil{return OperationResult{},err}};if err=service.Move(ctx,session,payload.MessageID,folder);err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"moved"}},nil});err!=nil{return err}
	if err:=registry.Bind("webmail.message.delete",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*WebmailDeletePayload);session,err:=boundWebmailSession(ctx,service,inv,payload.Session,payload.MailboxID);if err!=nil{return OperationResult{},err};if err=service.Delete(ctx,session,payload.MessageID);err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"deleted"}},nil});err!=nil{return err}
	if err:=registry.Bind("webmail.message.flags",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*WebmailFlagsPayload);session,err:=boundWebmailSession(ctx,service,inv,payload.Session,payload.MailboxID);if err!=nil{return OperationResult{},err};if err=service.Flags(ctx,session,payload.MessageID,payload.Flags);err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:map[string]string{"status":"updated"}},nil});err!=nil{return err}
	if err:=registry.Bind("webmail.draft.save",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*WebmailDraftPayload);session,err:=boundWebmailSession(ctx,service,inv,payload.Session,payload.Draft.MailboxID);if err!=nil{return OperationResult{},err};payload.Draft.TenantID=inv.Request.TenantID;draft,err:=service.SaveDraft(ctx,session,payload.Draft,inv.Request.ExpectedGeneration);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusOK,Value:draft,Generation:draft.Generation},nil});err!=nil{return err}
	return registry.Bind("webmail.message.send",func(ctx context.Context,inv Invocation,value any)(OperationResult,error){payload:=value.(*WebmailSendPayload);session,err:=boundWebmailSession(ctx,service,inv,payload.Session,payload.MailboxID);if err!=nil{return OperationResult{},err};queue,err:=service.Send(ctx,session,payload.Message);if err!=nil{return OperationResult{},mapMailError(err)};return OperationResult{Status:http.StatusAccepted,Value:map[string]mail.QueueID{"queue_id":queue}},nil})
}

func mailSession(inv Invocation,session mail.MailSession)mail.MailSession{session.TenantID=inv.Request.TenantID;session.PrincipalID=inv.Actor.PrincipalID.String();session.AuthzEpoch=inv.Actor.AuthzEpoch;return session}
func boundWebmailSession(ctx context.Context,service *mail.WebmailService,inv Invocation,session mail.MailSession,selected mail.MailboxID)(mail.MailSession,error){bound:=mailSession(inv,session);verified,err:=service.ResolveSession(ctx,bound);if err!=nil{return mail.MailSession{},mapMailError(err)};if string(verified.MailboxID)!=inv.Request.ResourceID||selected!=""&&selected!=verified.MailboxID{return mail.MailSession{},ErrForbidden};return bound,nil}
func webmailFolderForRole(folders []mail.Folder,role string)(mail.FolderID,error){names:=map[string]map[string]bool{"archive":{"archive":true,"archives":true},"trash":{"trash":true,"deleted items":true},"junk":{"junk":true,"spam":true},"sent":{"sent":true,"sent items":true},"drafts":{"drafts":true}}[role];if names==nil{return "",ErrInvalidRequest};var selected mail.FolderID;for _,folder:=range folders{if names[strings.ToLower(strings.TrimSpace(folder.Name))]{if selected!=""&&selected!=folder.ID{return "",ErrUnavailable};selected=folder.ID}};if selected==""{return "",ErrNotFound};return selected,nil}
func mapMailError(err error)error{switch{case err==nil:return nil;case errors.Is(err,mail.ErrInvalidCommand):return ErrInvalidRequest;case errors.Is(err,mail.ErrUnauthorized):return ErrForbidden;case errors.Is(err,mail.ErrNotFound):return ErrNotFound;case errors.Is(err,mail.ErrConflict):return ErrConflict;case errors.Is(err,mail.ErrRateLimited):return ErrRateLimited;case errors.Is(err,mail.ErrAmbiguous),errors.Is(err,mail.ErrInvalidReceipt):return ErrUnavailable;default:return err}}
