package apiserver

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base32"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"net/http"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/access"
	"github.com/aonsyed/cyberpanel/platform/internal/apps"
)

type Gateway struct{Registry *Registry;Transport CoreTransport;Signer RequestSigner;policy compiledPolicy;limiter *RateLimiter;clock func()time.Time;ui http.Handler;capabilityMutex sync.RWMutex;capabilities map[string]operationDescription;capabilityExpires time.Time}

func NewGateway(registry *Registry,transport CoreTransport,signer RequestSigner,policy GatewayPolicy)(*Gateway,error){if registry==nil||transport==nil||signer==nil{return nil,invalid("gateway dependencies")};compiled,err:=policy.compile();if err!=nil{return nil,err};return &Gateway{Registry:registry,Transport:transport,Signer:signer,policy:compiled,limiter:NewRateLimiter(policy.RatePerSecond,policy.RateBurst),clock:time.Now,capabilities:map[string]operationDescription{}},nil}

func(gateway *Gateway)WithUI(handler http.Handler)*Gateway{if gateway!=nil{gateway.ui=handler};return gateway}
func(gateway *Gateway)Handler()http.Handler{mux:=http.NewServeMux();mux.HandleFunc("GET /health/live",gateway.live);mux.HandleFunc("GET /health/ready",gateway.ready);mux.HandleFunc("GET /api/v1/catalog",gateway.catalog);mux.HandleFunc("POST /api/v1/operations",gateway.invoke);mux.HandleFunc("POST /api/v1/applications/wordpress/autologin/exchange",gateway.exchangeWordPressAutologin);mux.HandleFunc("POST /api/v1/containers/exec/exchange",gateway.exchangeContainerExec);mux.HandleFunc("GET /api/v1/downloads/{download_id}",gateway.download);mux.HandleFunc("/",gateway.serveUI);return http.HandlerFunc(func(writer http.ResponseWriter,request *http.Request){setSecurityHeaders(writer);mux.ServeHTTP(writer,request)})}

func(gateway *Gateway)exchangeContainerExec(writer http.ResponseWriter,httpRequest *http.Request){meta,err:=gateway.policy.metadata(httpRequest);if err!=nil{writeProblem(writer,classifyError(err,httpRequest.Header.Get("X-Request-ID")),1<<20);return};if !gateway.limiter.Allow(meta.ClientIP,5){problem:=classifyError(ErrRateLimited,httpRequest.Header.Get("X-Request-ID"));problem.RetryAfterSeconds=1;writeProblem(writer,problem,1<<20);return};if available,availabilityErr:=gateway.operationAvailable(httpRequest.Context(),"container.exec.exchange");availabilityErr!=nil||!available{writeProblem(writer,classifyError(ErrOperationUnavailable,httpRequest.Header.Get("X-Request-ID")),1<<20);return};var exchange ContainerExecExchangePayload;if err=readJSON(httpRequest,16<<10,&exchange);err!=nil{writeProblem(writer,classifyError(err,httpRequest.Header.Get("X-Request-ID")),1<<20);return};requestID,err:=opaqueID("request",18);if err!=nil{writeProblem(writer,classifyError(ErrUnavailable,""),1<<20);return};idempotency,err:=opaqueID("idempotency",18);if err!=nil{writeProblem(writer,classifyError(ErrUnavailable,requestID),1<<20);return};payload,err:=json.Marshal(exchange);exchange.Token="";if err!=nil{writeProblem(writer,classifyError(ErrUnavailable,requestID),1<<20);return};defer clearSecret(payload);ctx,cancel:=context.WithTimeout(httpRequest.Context(),gateway.policy.timeout);defer cancel();response,err:=gateway.invokeCore(ctx,RequestEnvelope{APIVersion:APIVersion,RequestID:requestID,Operation:"container.exec.exchange",Payload:payload},nil,idempotency,meta);if err!=nil{writeProblem(writer,classifyError(err,requestID),1<<20);return};if response.Problem!=nil{writeProblem(writer,*response.Problem,1<<20);return};if response.Envelope==nil{writeProblem(writer,classifyError(ErrUnavailable,requestID),1<<20);return};writer.Header().Set("Cache-Control","no-store");_ = writeJSON(writer,http.StatusOK,*response.Envelope,1<<20)}
func(gateway *Gateway)live(writer http.ResponseWriter,request *http.Request){if !gateway.allowPublic(writer,request,.25){return};_ = writeJSON(writer,http.StatusOK,map[string]string{"status":"alive"},1<<20)}
func(gateway *Gateway)ready(writer http.ResponseWriter,request *http.Request){if !gateway.allowPublic(writer,request,.25){return};ctx,cancel:=context.WithTimeout(request.Context(),3*time.Second);defer cancel();if err:=gateway.Transport.Health(ctx);err!=nil{writeProblem(writer,classifyError(ErrUnavailable,request.Header.Get("X-Request-ID")),1<<20);return};_ = writeJSON(writer,http.StatusOK,map[string]string{"status":"ready"},1<<20)}
func(gateway *Gateway)serveUI(writer http.ResponseWriter,request *http.Request){if !gateway.allowPublic(writer,request,.1){return};if gateway.ui==nil{writeProblem(writer,classifyError(ErrNotFound,request.Header.Get("X-Request-ID")),1<<20);return};gateway.ui.ServeHTTP(writer,request)}
func(gateway *Gateway)allowPublic(writer http.ResponseWriter,request *http.Request,cost float64)bool{meta,err:=gateway.policy.metadata(request);if err!=nil{writeProblem(writer,classifyError(err,request.Header.Get("X-Request-ID")),1<<20);return false};if !gateway.limiter.Allow(meta.ClientIP,cost){problem:=classifyError(ErrRateLimited,request.Header.Get("X-Request-ID"));problem.RetryAfterSeconds=1;writeProblem(writer,problem,1<<20);return false};return true}
func(gateway *Gateway)exchangeWordPressAutologin(writer http.ResponseWriter,httpRequest *http.Request){meta,err:=gateway.policy.metadata(httpRequest);if err!=nil{writeProblem(writer,classifyError(err,httpRequest.Header.Get("X-Request-ID")),1<<20);return};if !gateway.limiter.Allow(meta.ClientIP,5){problem:=classifyError(ErrRateLimited,httpRequest.Header.Get("X-Request-ID"));problem.RetryAfterSeconds=1;writeProblem(writer,problem,1<<20);return};if available,availabilityErr:=gateway.operationAvailable(httpRequest.Context(),"application.wordpress.autologin.exchange");availabilityErr!=nil||!available{writeProblem(writer,classifyError(ErrOperationUnavailable,httpRequest.Header.Get("X-Request-ID")),1<<20);return};var exchange apps.LoginGrantExchange;if err=readJSON(httpRequest,32<<10,&exchange);err!=nil{writeProblem(writer,classifyError(err,httpRequest.Header.Get("X-Request-ID")),1<<20);return};requestID:=strings.TrimSpace(httpRequest.Header.Get("X-Request-ID"));if requestID==""{requestID,err=opaqueID("request",18)}else if !requestIDPattern.MatchString(requestID){err=invalid("request_id")};if err!=nil{writeProblem(writer,classifyError(err,requestID),1<<20);return};idempotency,err:=opaqueID("idempotency",18);if err!=nil{writeProblem(writer,classifyError(ErrUnavailable,requestID),1<<20);return};payload,err:=json.Marshal(WordPressAutologinExchangePayload{Request:exchange});exchange.Secret="";exchange.CSRFBinding="";if err!=nil{writeProblem(writer,classifyError(ErrUnavailable,requestID),1<<20);return};ctx,cancel:=context.WithTimeout(httpRequest.Context(),gateway.policy.timeout);defer cancel();response,err:=gateway.invokeCore(ctx,RequestEnvelope{APIVersion:APIVersion,RequestID:requestID,Operation:"application.wordpress.autologin.exchange",Payload:payload},nil,idempotency,meta);if err!=nil{writeProblem(writer,classifyError(err,requestID),1<<20);return};if response.Problem!=nil{writeProblem(writer,*response.Problem,1<<20);return};if response.Envelope==nil{writeProblem(writer,classifyError(ErrUnavailable,requestID),1<<20);return};var result struct{WordPressUserID uint64 `json:"wordpress_user_id"`};if err=decodeStrict(response.Envelope.Result,&result);err!=nil||result.WordPressUserID==0{writeProblem(writer,classifyError(ErrUnavailable,requestID),1<<20);return};_ = writeJSON(writer,http.StatusOK,result,1<<20)}
func(gateway *Gateway)catalog(writer http.ResponseWriter,request *http.Request){meta,err:=gateway.policy.metadata(request);if err!=nil{writeProblem(writer,classifyError(err,request.Header.Get("X-Request-ID")),1<<20);return};if !gateway.limiter.Allow(meta.ClientIP,1){problem:=classifyError(ErrRateLimited,request.Header.Get("X-Request-ID"));problem.RetryAfterSeconds=1;writeProblem(writer,problem,1<<20);return};ctx,cancel:=context.WithTimeout(request.Context(),3*time.Second);defer cancel();catalog,err:=gateway.loadCapabilities(ctx,true);if err!=nil{writeProblem(writer,classifyError(ErrUnavailable,request.Header.Get("X-Request-ID")),1<<20);return};_ = writeJSON(writer,http.StatusOK,map[string]any{"api_version":catalog.APIVersion,"operations":catalog.Operations},DefaultMaximumResponseBytes)}

func(gateway *Gateway)loadCapabilities(ctx context.Context,force bool)(CoreCatalog,error){now:=gateway.now();if !force{gateway.capabilityMutex.RLock();if now.Before(gateway.capabilityExpires)&&len(gateway.capabilities)>0{operations:=make([]operationDescription,0,len(gateway.capabilities));for _,name:=range gateway.Registry.Names(){if description,ok:=gateway.capabilities[name];ok{operations=append(operations,description)}};gateway.capabilityMutex.RUnlock();return CoreCatalog{ProtocolVersion:InternalProtocolVersion,APIVersion:APIVersion,Operations:operations},nil};gateway.capabilityMutex.RUnlock()};transport,ok:=gateway.Transport.(CoreCatalogTransport);if !ok{return CoreCatalog{},ErrUnavailable};catalog,err:=transport.Catalog(ctx);if err!=nil{return CoreCatalog{},err};available:=make(map[string]operationDescription,len(catalog.Operations));for _,description:=range catalog.Operations{operation,exists:=gateway.Registry.Lookup(description.Name);if !exists||description.Permission!=operation.Permission||description.Assurance!=operation.Assurance||description.Auth!=operation.Auth||description.SelfService!=operation.SelfService||description.Mutating!=operation.Mutating||description.MaximumBodyBytes!=effectiveBodyLimit(operation)||description.MaximumResponseBytes!=effectiveResponseLimit(operation){return CoreCatalog{},ErrUnavailable};if _,duplicate:=available[description.Name];duplicate{return CoreCatalog{},ErrUnavailable};available[description.Name]=description};gateway.capabilityMutex.Lock();gateway.capabilities=available;gateway.capabilityExpires=now.Add(10*time.Second);gateway.capabilityMutex.Unlock();return catalog,nil}

func(gateway *Gateway)operationAvailable(ctx context.Context,name string)(bool,error){catalog,err:=gateway.loadCapabilities(ctx,false);if err!=nil{return false,err};for _,description:=range catalog.Operations{if description.Name==name{return true,nil}};return false,nil}

func(gateway *Gateway)download(writer http.ResponseWriter,httpRequest *http.Request){
	meta,err:=gateway.policy.metadata(httpRequest);if err!=nil{writeProblem(writer,classifyError(err,httpRequest.Header.Get("X-Request-ID")),1<<20);return}
	if !gateway.limiter.Allow(meta.ClientIP,2){problem:=classifyError(ErrRateLimited,httpRequest.Header.Get("X-Request-ID"));problem.RetryAfterSeconds=1;writeProblem(writer,problem,1<<20);return}
	operation,ok:=gateway.Registry.Lookup("access.download.get");if !ok{writeProblem(writer,classifyError(ErrOperationUnavailable,httpRequest.Header.Get("X-Request-ID")),1<<20);return}
	auth,err:=gateway.readAuth(httpRequest,operation);if err!=nil{writeProblem(writer,classifyError(err,httpRequest.Header.Get("X-Request-ID")),1<<20);return}
	query:=httpRequest.URL.Query();if len(query)!=2||len(query["tenant_id"])!=1||len(query["site_id"])!=1{writeProblem(writer,classifyError(invalid("download URL"),httpRequest.Header.Get("X-Request-ID")),1<<20);return}
	downloadID:=httpRequest.PathValue("download_id");tenantID:=query.Get("tenant_id");siteID:=query.Get("site_id")
	requestID:=strings.TrimSpace(httpRequest.Header.Get("X-Request-ID"));if requestID==""{requestID,err=opaqueID("request",18)}else if !requestIDPattern.MatchString(requestID){err=invalid("request_id")};if err!=nil{writeProblem(writer,classifyError(err,requestID),1<<20);return}
	payload,err:=json.Marshal(DownloadIDPayload{DownloadID:access.DownloadID(downloadID)});if err!=nil{writeProblem(writer,classifyError(ErrUnavailable,requestID),1<<20);return}
	envelope:=RequestEnvelope{APIVersion:APIVersion,RequestID:requestID,Operation:"access.download.get",TenantID:tenantID,ResourceID:siteID,Payload:payload}
	ctx,cancel:=context.WithTimeout(httpRequest.Context(),gateway.policy.timeout);defer cancel();response,err:=gateway.invokeCore(ctx,envelope,auth,"",meta);if err!=nil{writeProblem(writer,classifyError(err,requestID),1<<20);return};if response.Problem!=nil{writeProblem(writer,*response.Problem,1<<20);return};if response.Envelope==nil{writeProblem(writer,classifyError(ErrUnavailable,requestID),1<<20);return}
	var lease DownloadIssueResult;if err=decodeStrict(response.Envelope.Result,&lease);err!=nil||lease.ID!=access.DownloadID(downloadID)||lease.Integrity.Validate()!=nil||lease.Integrity.Size>1<<40||!lease.ExpiresAt.After(gateway.now()){writeProblem(writer,classifyError(ErrUnavailable,requestID),1<<20);return}
	var first []byte;if lease.Integrity.Size>0{length:=lease.Integrity.Size;if length>access.MaxUploadChunk{length=access.MaxUploadChunk};first,err=gateway.downloadChunk(ctx,auth,meta,tenantID,siteID,lease.ID,lease.Integrity,0,length);if err!=nil{writeProblem(writer,classifyError(err,requestID),1<<20);return}}
	digestBytes,err:=hex.DecodeString(lease.Integrity.Digest);if err!=nil{writeProblem(writer,classifyError(ErrUnavailable,requestID),1<<20);return}
	writer.Header().Set("Content-Type","application/octet-stream");writer.Header().Set("Content-Disposition","attachment");writer.Header().Set("Content-Length",strconv.FormatInt(lease.Integrity.Size,10));writer.Header().Set("Accept-Ranges","none");writer.Header().Set("Content-Digest","sha-256=:"+base64.StdEncoding.EncodeToString(digestBytes)+":");writer.WriteHeader(http.StatusOK)
	hasher:=sha256.New();offset:=int64(0);if len(first)>0{firstLength:=len(first);_,_=hasher.Write(first);written,writeErr:=writer.Write(first);clearSecret(first);if writeErr!=nil||written!=firstLength{return};offset=int64(firstLength)}
	for offset<lease.Integrity.Size{length:=lease.Integrity.Size-offset;if length>access.MaxUploadChunk{length=access.MaxUploadChunk};content,readErr:=gateway.downloadChunk(ctx,auth,meta,tenantID,siteID,lease.ID,lease.Integrity,offset,length);if readErr!=nil{return};if _,err=hasher.Write(content);err!=nil{clearSecret(content);return};written,writeErr:=writer.Write(content);clearSecret(content);if writeErr!=nil||int64(written)!=length{return};offset+=length}
	actual:=hex.EncodeToString(hasher.Sum(nil));if actual!=lease.Integrity.Digest{return};closeCtx,closeCancel:=context.WithTimeout(context.WithoutCancel(httpRequest.Context()),3*time.Second);defer closeCancel();gateway.closeDownload(closeCtx,auth,meta,tenantID,siteID,lease.ID)
}

func(gateway *Gateway)downloadChunk(ctx context.Context,auth *AuthMaterial,meta RequestMeta,tenantID,siteID string,downloadID access.DownloadID,integrity access.Integrity,offset,length int64)([]byte,error){requestID,err:=opaqueID("request",18);if err!=nil{return nil,err};payload,err:=json.Marshal(DownloadReadPayload{DownloadID:downloadID,Offset:offset,Length:length});if err!=nil{return nil,err};response,err:=gateway.invokeCore(ctx,RequestEnvelope{APIVersion:APIVersion,RequestID:requestID,Operation:"access.download.read",TenantID:tenantID,ResourceID:siteID,Payload:payload},auth,"",meta);if err!=nil{return nil,err};if response.Problem!=nil{return nil,problemError(*response.Problem)};if response.Envelope==nil{return nil,ErrUnavailable};var chunk DownloadReadResult;if err=decodeStrict(response.Envelope.Result,&chunk);err!=nil||chunk.DownloadID!=downloadID||chunk.Offset!=offset||chunk.Integrity!=integrity{return nil,ErrUnavailable};content,err:=base64.RawStdEncoding.DecodeString(chunk.ContentBase64);if err!=nil||int64(len(content))!=length{clearSecret(content);return nil,ErrUnavailable};return content,nil}

func(gateway *Gateway)closeDownload(ctx context.Context,auth *AuthMaterial,meta RequestMeta,tenantID,siteID string,downloadID access.DownloadID){requestID,err:=opaqueID("request",18);if err!=nil{return};idempotency,err:=opaqueID("idempotency",18);if err!=nil{return};payload,err:=json.Marshal(DownloadIDPayload{DownloadID:downloadID});if err!=nil{return};_,_=gateway.invokeCore(ctx,RequestEnvelope{APIVersion:APIVersion,RequestID:requestID,Operation:"access.download.close",TenantID:tenantID,ResourceID:siteID,Payload:payload},auth,idempotency,meta)}

func(gateway *Gateway)invokeCore(ctx context.Context,request RequestEnvelope,auth *AuthMaterial,idempotency string,meta RequestMeta)(CoreResponse,error){nonce,err:=opaqueID("nonce",24);if err!=nil{return CoreResponse{},err};coreRequest:=CoreRequest{ProtocolVersion:InternalProtocolVersion,Request:request,Auth:auth,IdempotencyKey:idempotency,Meta:meta,SentAt:gateway.now(),Nonce:nonce};if err=gateway.Signer.Sign(&coreRequest);err!=nil{return CoreResponse{},err};return gateway.Transport.Invoke(ctx,coreRequest)}

type problemError Problem
func(errorValue problemError)Error()string{if errorValue.Detail!=""{return errorValue.Detail};return errorValue.Title}
func(errorValue problemError)Unwrap()error{switch errorValue.Code{case"invalid_request":return ErrInvalidRequest;case"unauthenticated":return ErrUnauthenticated;case"forbidden":return ErrForbidden;case"assurance_required":return ErrAssuranceRequired;case"not_found":return ErrNotFound;case"idempotency_conflict":return ErrIdempotencyConflict;case"conflict":return ErrConflict;case"rate_limited":return ErrRateLimited;case"operation_unavailable":return ErrOperationUnavailable;case"response_too_large":return ErrResponseTooLarge;default:return ErrUnavailable}}

func(gateway *Gateway)invoke(writer http.ResponseWriter,httpRequest *http.Request){
	meta,err:=gateway.policy.metadata(httpRequest);if err!=nil{writeProblem(writer,classifyError(err,httpRequest.Header.Get("X-Request-ID")),DefaultMaximumResponseBytes);return}
	var request RequestEnvelope;if err=readJSON(httpRequest,AbsoluteMaximumBodyBytes,&request);err!=nil{writeProblem(writer,classifyError(err,request.RequestID),DefaultMaximumResponseBytes);return}
	if err=request.Validate();err!=nil{writeProblem(writer,classifyError(err,request.RequestID),DefaultMaximumResponseBytes);return};if _,exists:=gateway.Registry.Lookup(request.Operation);!exists{writeProblem(writer,classifyError(ErrOperationUnavailable,request.RequestID),DefaultMaximumResponseBytes);return};catalogCtx,catalogCancel:=context.WithTimeout(httpRequest.Context(),3*time.Second);available,catalogErr:=gateway.operationAvailable(catalogCtx,request.Operation);catalogCancel();if catalogErr!=nil{writeProblem(writer,classifyError(ErrUnavailable,request.RequestID),DefaultMaximumResponseBytes);return};if !available{writeProblem(writer,classifyError(ErrOperationUnavailable,request.RequestID),DefaultMaximumResponseBytes);return}
	operation,_,canonical,err:=gateway.Registry.Canonicalize(request);if err!=nil{writeProblem(writer,classifyError(err,request.RequestID),DefaultMaximumResponseBytes);return};request=canonical
	if int64(len(request.Payload))>effectiveBodyLimit(operation){writeProblem(writer,classifyError(invalid("operation payload is too large"),request.RequestID),DefaultMaximumResponseBytes);return}
	cost:=1.0;if operation.Name=="identity.session.login"||operation.Name=="identity.session.mfa_totp"{cost=5};if !gateway.limiter.Allow(meta.ClientIP,cost){problem:=classifyError(ErrRateLimited,request.RequestID);problem.RetryAfterSeconds=1;writeProblem(writer,problem,DefaultMaximumResponseBytes);return}
	auth,err:=gateway.readAuth(httpRequest,operation);if err!=nil{writeProblem(writer,classifyError(err,request.RequestID),DefaultMaximumResponseBytes);return}
	idempotency:=strings.TrimSpace(httpRequest.Header.Get("Idempotency-Key"));if operation.Mutating{if !idempotencyPattern.MatchString(idempotency){writeProblem(writer,classifyError(invalid("idempotency_key"),request.RequestID),DefaultMaximumResponseBytes);return}}else if idempotency!=""{writeProblem(writer,classifyError(invalid("idempotency_key on read operation"),request.RequestID),DefaultMaximumResponseBytes);return}
	if operation.Mutating&&auth!=nil&&auth.Kind==CredentialSession{if meta.Origin==""||auth.CSRFToken==""{writeProblem(writer,classifyError(ErrForbidden,request.RequestID),DefaultMaximumResponseBytes);return}}
	nonce,err:=opaqueID("nonce",24);if err!=nil{writeProblem(writer,classifyError(ErrUnavailable,request.RequestID),DefaultMaximumResponseBytes);return}
	coreRequest:=CoreRequest{ProtocolVersion:InternalProtocolVersion,Request:request,Auth:auth,IdempotencyKey:idempotency,Meta:meta,SentAt:gateway.now(),Nonce:nonce}
	if err=gateway.Signer.Sign(&coreRequest);err!=nil{writeProblem(writer,classifyError(ErrUnavailable,request.RequestID),DefaultMaximumResponseBytes);return}
	ctx,cancel:=context.WithTimeout(httpRequest.Context(),gateway.policy.timeout);defer cancel();response,err:=gateway.Transport.Invoke(ctx,coreRequest);if err!=nil{writeProblem(writer,classifyError(err,request.RequestID),DefaultMaximumResponseBytes);return}
	for key,value:=range safeResponseHeaders(response.Headers){writer.Header().Set(key,value)}
	if response.Problem!=nil{writeProblem(writer,*response.Problem,effectiveResponseLimit(operation));return}
	if response.Session!=nil{now:=gateway.now();if response.Session.Validate()!=nil||!response.Session.ExpiresAt.After(now)||response.Session.ExpiresAt.After(now.Add(31*24*time.Hour)){writeProblem(writer,classifyError(ErrUnavailable,request.RequestID),DefaultMaximumResponseBytes);return};writer.Header().Set("X-CSRF-Token",response.Session.CSRFToken);writer.Header().Set("Access-Control-Expose-Headers","X-CSRF-Token");maximumAge:=int(response.Session.ExpiresAt.Sub(now).Seconds());http.SetCookie(writer,&http.Cookie{Name:gateway.policy.cookieName,Value:response.Session.SessionID+"."+response.Session.SessionToken,Path:"/api/",Expires:response.Session.ExpiresAt,MaxAge:maximumAge,HttpOnly:true,Secure:true,SameSite:http.SameSiteStrictMode});http.SetCookie(writer,&http.Cookie{Name:gateway.policy.cookieName+"_csrf",Value:response.Session.CSRFToken,Path:"/",Expires:response.Session.ExpiresAt,MaxAge:maximumAge,HttpOnly:false,Secure:true,SameSite:http.SameSiteStrictMode})}else if response.ClearSession{expired:=time.Unix(1,0).UTC();http.SetCookie(writer,&http.Cookie{Name:gateway.policy.cookieName,Value:"",Path:"/api/",Expires:expired,MaxAge:-1,HttpOnly:true,Secure:true,SameSite:http.SameSiteStrictMode});http.SetCookie(writer,&http.Cookie{Name:gateway.policy.cookieName+"_csrf",Value:"",Path:"/",Expires:expired,MaxAge:-1,HttpOnly:false,Secure:true,SameSite:http.SameSiteStrictMode})}else if auth!=nil&&auth.Kind==CredentialSession&&auth.CSRFToken!=""{writer.Header().Set("X-CSRF-Token",auth.CSRFToken);writer.Header().Set("Access-Control-Expose-Headers","X-CSRF-Token")}
	if response.Envelope==nil{writeProblem(writer,classifyError(ErrUnavailable,request.RequestID),DefaultMaximumResponseBytes);return};_ = writeJSON(writer,response.Status,*response.Envelope,effectiveResponseLimit(operation))
}

func(gateway *Gateway)readAuth(request *http.Request,operation Operation)(*AuthMaterial,error){authorization:=strings.TrimSpace(request.Header.Get("Authorization"));cookie,err:=request.Cookie(gateway.policy.cookieName);hasCookie:=err==nil&&cookie.Value!="";if authorization!=""&&hasCookie{return nil,ErrInvalidRequest};if operation.Auth==AuthNone{if authorization!=""||hasCookie{return nil,ErrInvalidRequest};return nil,nil};if authorization!=""{parts:=strings.SplitN(authorization," ",2);if len(parts)!=2||parts[0]!="Bearer"||len(parts[1])<24||len(parts[1])>4096||strings.ContainsAny(parts[1],"\r\n\t "){return nil,ErrUnauthenticated};material:=&AuthMaterial{Kind:CredentialAPIKey,APIKey:parts[1]};return material,material.Validate()};if !hasCookie{return nil,ErrUnauthenticated};parts:=strings.Split(cookie.Value,".");if len(parts)!=2{return nil,ErrUnauthenticated};csrf:=strings.TrimSpace(request.Header.Get("X-CSRF-Token"));if csrf==""&&!operation.Mutating{if csrfCookie,cookieErr:=request.Cookie(gateway.policy.cookieName+"_csrf");cookieErr==nil{csrf=strings.TrimSpace(csrfCookie.Value)}};material:=&AuthMaterial{Kind:CredentialSession,SessionID:parts[0],SessionToken:parts[1],CSRFToken:csrf};return material,material.Validate()}

func opaqueID(prefix string,size int)(string,error){value:=make([]byte,size);if _,err:=rand.Read(value);err!=nil{return "",err};encoded:=strings.ToLower(base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString(value));return prefix+"_"+encoded,nil}
func(gateway *Gateway)now()time.Time{if gateway.clock==nil{return time.Now().UTC()};return gateway.clock().UTC()}
func setSecurityHeaders(writer http.ResponseWriter){writer.Header().Set("Cache-Control","no-store");writer.Header().Set("Content-Security-Policy","default-src 'none'; frame-ancestors 'none'; base-uri 'none'");writer.Header().Set("Referrer-Policy","no-referrer");writer.Header().Set("Permissions-Policy","camera=(), microphone=(), geolocation=(), payment=()");writer.Header().Set("X-Content-Type-Options","nosniff");writer.Header().Set("X-Frame-Options","DENY");writer.Header().Set("Cross-Origin-Resource-Policy","same-origin");writer.Header().Set("Strict-Transport-Security","max-age=31536000; includeSubDomains")}
