//go:build linux

package install

import (
	"archive/tar"
	"compress/gzip"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"syscall"
	"time"
)

const(installerRoot="/var/lib/cyberpanel/installer";stagingRoot=installerRoot+"/staging";slotRoot="/opt/cyberpanel/slots";activeLink="/opt/cyberpanel/current";exportRoot="/var/backups/cyberpanel/exports")
type LinuxHost struct{Client *http.Client;Now func()time.Time}
func NewLinuxHost()*LinuxHost{transport:=http.DefaultTransport.(*http.Transport).Clone();transport.Proxy=nil;transport.MaxIdleConns=4;transport.ResponseHeaderTimeout=30*time.Second;transport.DialContext=dialPublicHTTPS;return &LinuxHost{Client:&http.Client{Transport:transport,Timeout:30*time.Minute}}}
func (host *LinuxHost)now()time.Time{if host.Now!=nil{return host.Now().UTC()};return time.Now().UTC()}

func (host *LinuxHost)Probe(ctx context.Context,edition WebEdition)(SystemFacts,error){if os.Geteuid()!=0{return SystemFacts{},ErrPreflight};release,err:=parseOSRelease();if err!=nil{return SystemFacts{},err};arch,err:=RuntimeArchitecture();if err!=nil{return SystemFacts{},err};tuple:=PlatformTuple{Architecture:arch,Edition:edition};switch release["ID"]{case "ubuntu":tuple.Distribution,tuple.Release,tuple.Codename=DistributionUbuntu,release["VERSION_ID"],release["VERSION_CODENAME"];case "almalinux":tuple.Distribution,tuple.Release,tuple.Codename=DistributionAlma,majorRelease(release["VERSION_ID"]),"el9";default:return SystemFacts{},ErrUnsupported};if err:=tuple.Validate();err!=nil{return SystemFacts{},err};hostname,_:=os.Hostname();machineID,_:=readTrimmed("/etc/machine-id");bootID,_:=readTrimmed("/proc/sys/kernel/random/boot_id");memory:=readMemory();disk,filesystem,err:=diskFacts("/");if err!=nil{return SystemFacts{},err};pid1,_:=readTrimmed("/proc/1/comm");ports,_:=occupiedTCPPorts();_,linkErr:=os.Lstat(activeLink);return SystemFacts{Tuple:tuple,Hostname:hostname,MachineID:machineID,BootID:bootID,MemoryBytes:memory,DiskFreeBytes:disk,CPUCores:uint16(runtimeCPUCount()),PID1:pid1,RootFilesystem:filesystem,ExistingPanel:linkErr==nil,OccupiedPorts:ports,ObservedAt:host.now()},nil}
func (host *LinuxHost)Preflight(ctx context.Context,request PreflightRequest)(PreflightReceipt,error){if !safeID.MatchString(request.TransactionID)||request.Expected.Validate()!=nil{return PreflightReceipt{},ErrInvalid};facts,err:=host.Probe(ctx,request.Expected.Edition);if err!=nil{return PreflightReceipt{},err};checks:=map[string]string{};if facts.Tuple.Key()!=request.Expected.Key(){return PreflightReceipt{},ErrUnsupported};checks["platform"]="supported";if facts.PID1!="systemd"{return PreflightReceipt{},fmt.Errorf("%w: systemd required",ErrPreflight)};checks["init"]="systemd";if facts.MemoryBytes<request.MinimumMemoryBytes{return PreflightReceipt{},fmt.Errorf("%w: memory",ErrPreflight)};checks["memory"]="sufficient";if facts.DiskFreeBytes<request.MinimumDiskBytes{return PreflightReceipt{},fmt.Errorf("%w: disk",ErrPreflight)};checks["disk"]="sufficient";if facts.ExistingPanel&&!request.AllowExisting{return PreflightReceipt{},fmt.Errorf("%w: panel already installed",ErrConflict)};occupied:=map[uint16]bool{};for _,port:=range facts.OccupiedPorts{occupied[port]=true};if !request.AllowExisting{for _,port:=range request.RequiredPorts{if occupied[port]{return PreflightReceipt{},fmt.Errorf("%w: port %d occupied",ErrPreflight,port)}}};checks["ports"]="available_or_managed";checks["root_filesystem"]=facts.RootFilesystem;receipt:=PreflightReceipt{Facts:facts,Checks:checks,CompletedAt:host.now()};receipt.Digest,_=canonicalDigest(struct{Facts SystemFacts;Checks map[string]string}{facts,checks});return receipt,nil}
func (host *LinuxHost)PrepareTransaction(ctx context.Context,plan TransactionPlan)(MutationReceipt,error){if !safeID.MatchString(plan.ID){return MutationReceipt{},ErrInvalid};for _,path:=range []string{installerRoot,stagingRoot,filepath.Join(stagingRoot,plan.ID)}{if err:=secureMkdir(path,0700);err!=nil{return MutationReceipt{},err}};if err:=secureMkdir(slotRoot,0755);err!=nil{return MutationReceipt{},err};return mutation("prepare",plan.ID,plan.CatalogDigest,host.now()),nil}

func (host *LinuxHost)EnsureIdentity(ctx context.Context,identity IdentityID)(MutationReceipt,error){if identity==IdentityRoot{return mutation("identity",string(identity),digestText("root:0"),host.now()),nil};name,home,shell:=identityRecord(identity);if name==""{return MutationReceipt{},ErrInvalid};account,err:=user.Lookup(name);if err==nil{uid,parseErr:=strconv.ParseUint(account.Uid,10,32);if parseErr!=nil||uid==0{return MutationReceipt{},ErrIntegrity};if identity==IdentityContainers{if err=ensureContainerSubordinateIDs(ctx,name);err!=nil{return MutationReceipt{},err}};return mutation("identity",name,digestText(account.Uid+":"+account.Gid),host.now()),nil};if _,ok:=err.(user.UnknownUserError);!ok{return MutationReceipt{},err};arguments:=[]string{"--system","--user-group","--home-dir",home,"--create-home","--shell",shell,name};if _,err:=runFixed(ctx,"/usr/sbin/useradd",arguments...);err!=nil{return MutationReceipt{},err};account,err=user.Lookup(name);if err!=nil{return MutationReceipt{},err};if identity==IdentityContainers{if err=ensureContainerSubordinateIDs(ctx,name);err!=nil{return MutationReceipt{},err}};return mutation("identity",name,digestText(account.Uid+":"+account.Gid),host.now()),nil}

func (host *LinuxHost)InstallPackages(ctx context.Context,tuple PlatformTuple,component ComponentID,selections []PackageSelection)(PackageReceipt,error){if tuple.Validate()!=nil||!closedComponents[component]||len(selections)==0{return PackageReceipt{},ErrInvalid};installed:=map[PackageID]string{};repositoryReceipts:=map[string]string{};arguments:=[]string{};for _,selection:=range selections{if err:=selection.Validate();err!=nil{return PackageReceipt{},err};name,err:=nativePackage(tuple.Distribution,selection.ID);if err!=nil{return PackageReceipt{},err};receipt,err:=verifyRepositorySnapshot(selection);if err!=nil{return PackageReceipt{},err};repositoryReceipts[selection.RepositoryID]=receipt;if tuple.Distribution==DistributionUbuntu{arguments=append(arguments,name+"="+selection.Version)}else{arguments=append(arguments,name+"-"+selection.Version)};installed[selection.ID]=selection.Version};sort.Strings(arguments);if tuple.Distribution==DistributionUbuntu{args:=append([]string{"-o","Dpkg::Use-Pty=0","-y","--no-install-recommends","install","--"},arguments...);if _,err:=runFixed(ctx,"/usr/bin/apt-get",args...);err!=nil{return PackageReceipt{},err}}else{args:=append([]string{"-y","--setopt=install_weak_deps=False","--setopt=keepcache=True","install"},arguments...);if _,err:=runFixed(ctx,"/usr/bin/dnf",args...);err!=nil{return PackageReceipt{},err}};digest,_:=canonicalDigest(struct{Component ComponentID;Installed map[PackageID]string;Repositories map[string]string}{component,installed,repositoryReceipts});return PackageReceipt{ComponentID:component,Installed:installed,RepositoryReceipts:repositoryReceipts,Digest:digest,CompletedAt:host.now()},nil}

func (host *LinuxHost)StageArtifact(ctx context.Context,transactionID string,component ComponentID,artifact Artifact)(ArtifactReceipt,error){if !safeID.MatchString(transactionID)||!closedComponents[component]||artifact.Validate()!=nil{return ArtifactReceipt{},ErrInvalid};directory:=filepath.Join(stagingRoot,transactionID,"downloads");if err:=secureMkdir(directory,0700);err!=nil{return ArtifactReceipt{},err};path:=filepath.Join(directory,artifact.ID+".artifact");if info,err:=os.Stat(path);err==nil&&info.Mode().IsRegular(){sum,size,hashErr:=hashFile(path);if hashErr==nil&&sum==artifact.SHA256&&size==artifact.Size{return ArtifactReceipt{ArtifactID:artifact.ID,StagedPath:path,SHA256:sum,Size:size,Format:artifact.Format,TreeDigest:artifact.TreeDigest,Members:artifact.Members,CompletedAt:host.now()},nil};return ArtifactReceipt{},ErrIntegrity};request,err:=http.NewRequestWithContext(ctx,http.MethodGet,artifact.URL,nil);if err!=nil{return ArtifactReceipt{},err};client:=*host.Client;client.CheckRedirect=func(next *http.Request,prior []*http.Request)error{if len(prior)>=2{return ErrIntegrity};for _,allowed:=range artifact.AllowedHosts{if next.URL.Scheme=="https"&&next.URL.Hostname()==allowed{return nil}};return ErrIntegrity};response,err:=client.Do(request);if err!=nil{return ArtifactReceipt{},err};defer response.Body.Close();if response.StatusCode!=http.StatusOK||response.ContentLength>artifact.Size&&response.ContentLength>=0{return ArtifactReceipt{},ErrIntegrity};file,err:=os.OpenFile(path,os.O_CREATE|os.O_EXCL|os.O_WRONLY|syscall.O_NOFOLLOW,0600);if err!=nil{return ArtifactReceipt{},err};hasher:=sha256.New();written,copyErr:=io.Copy(io.MultiWriter(file,hasher),io.LimitReader(response.Body,artifact.Size+1));syncErr:=file.Sync();closeErr:=file.Close();if copyErr!=nil||syncErr!=nil||closeErr!=nil||written!=artifact.Size||hex.EncodeToString(hasher.Sum(nil))!=artifact.SHA256{_ = os.Remove(path);return ArtifactReceipt{},errors.Join(ErrIntegrity,copyErr,syncErr,closeErr)};return ArtifactReceipt{ArtifactID:artifact.ID,StagedPath:path,SHA256:artifact.SHA256,Size:written,Format:artifact.Format,TreeDigest:artifact.TreeDigest,Members:artifact.Members,CompletedAt:host.now()},nil}

func (host *LinuxHost)DeployArtifact(ctx context.Context,transactionID string,slot SlotID,component ComponentID,staged ArtifactReceipt)(MutationReceipt,error){if !safeID.MatchString(transactionID)||(slot!=SlotA&&slot!=SlotB)||!closedComponents[component]||(staged.Format!=ArtifactTarGzip&&staged.Format!=ArtifactRaw){return MutationReceipt{},ErrInvalid};expectedPrefix:=filepath.Join(stagingRoot,transactionID,"downloads")+string(os.PathSeparator);if !strings.HasPrefix(staged.StagedPath,expectedPrefix)||filepath.Clean(staged.StagedPath)!=staged.StagedPath{return MutationReceipt{},ErrIntegrity};sum,size,err:=hashFile(staged.StagedPath);if err!=nil||sum!=staged.SHA256||size!=staged.Size{return MutationReceipt{},ErrIntegrity};destination:=filepath.Join(slotRoot,string(slot),"components",string(component));temporary:=filepath.Join(stagingRoot,transactionID,"trees",string(component));if err:=secureMkdir(filepath.Dir(temporary),0700);err!=nil{return MutationReceipt{},err};if err:=os.RemoveAll(temporary);err!=nil{return MutationReceipt{},err};if err:=secureMkdir(temporary,0755);err!=nil{return MutationReceipt{},err};if staged.Format==ArtifactTarGzip{if err:=extractTarGzip(staged.StagedPath,temporary);err!=nil{return MutationReceipt{},err}}else{target:=filepath.Join(temporary,componentBinary(component));if err:=copyRegular(staged.StagedPath,target,0755);err!=nil{return MutationReceipt{},err}};if err:=verifyArtifactMembers(component,temporary,staged.Members);err!=nil{return MutationReceipt{},err};treeDigest,err:=digestTree(temporary);if err!=nil{return MutationReceipt{},err};if staged.TreeDigest!=""&&treeDigest!=staged.TreeDigest{return MutationReceipt{},ErrIntegrity};if err:=secureMkdir(filepath.Dir(destination),0755);err!=nil{return MutationReceipt{},err};previous:=destination+".previous";_ = os.RemoveAll(previous);if _,err:=os.Stat(destination);err==nil{if err:=os.Rename(destination,previous);err!=nil{return MutationReceipt{},err}};if err:=os.Rename(temporary,destination);err!=nil{_ = os.Rename(previous,destination);return MutationReceipt{},err};return mutation("deploy",string(component),treeDigest,host.now()),nil}

func (host *LinuxHost)InstallEnterpriseLicense(ctx context.Context,license EnterpriseLicenseRef)(MutationReceipt,error){if err:=license.Validate();err!=nil{return MutationReceipt{},err};info,err:=os.Stat(license.SourcePath);if err!=nil{return MutationReceipt{},err};if err:=requireRootOwned(info,0600);err!=nil{return MutationReceipt{},err};digest,size,err:=hashFile(license.SourcePath);if err!=nil||digest!=license.Digest||size<=0||size>64<<10{return MutationReceipt{},ErrIntegrity};destination:="/etc/cyberpanel/secrets/litespeed/license.key";if license.Kind=="serial"{destination="/etc/cyberpanel/secrets/litespeed/serial.no"};payload,err:=os.ReadFile(license.SourcePath);if err!=nil{return MutationReceipt{},err};if err:=atomicWriteManaged(destination,payload,0600,0,0);err!=nil{return MutationReceipt{},err};return mutation("install_enterprise_license",license.Kind,digest,host.now()),nil}

func (host *LinuxHost)WriteManagedFiles(ctx context.Context,slot SlotID,component ComponentID,files []ManagedFile)(MutationReceipt,error){if !closedComponents[component]||(slot!=SlotA&&slot!=SlotB){return MutationReceipt{},ErrInvalid};digests:=[]string{};for _,managed:=range files{if err:=managed.Validate();err!=nil{return MutationReceipt{},err};if managedPath(managed.PathID)==""{return MutationReceipt{},ErrInvalid};path:=managedSlotPath(slot,managed.PathID);uid,gid,err:=identityIDs(managed.Owner,managed.Group);if err!=nil{return MutationReceipt{},err};if err:=atomicWriteManaged(path,[]byte(managed.Content),os.FileMode(managed.Mode),uid,gid);err!=nil{return MutationReceipt{},err};digests=append(digests,string(managed.PathID)+":"+managed.ContentDigest)};sort.Strings(digests);return mutation("write_managed_files",string(component),digestText(strings.Join(digests,"\n")),host.now()),nil}

func (host *LinuxHost)EnableServices(ctx context.Context,tuple PlatformTuple,services []ServiceSpec)([]MutationReceipt,error){receipts:=[]MutationReceipt{};for _,service:=range services{if err:=service.Validate();err!=nil{return nil,err};unit,err:=nativeService(tuple.Distribution,service.ID);if err!=nil{return nil,err};if service.ID==ServicePanel||service.ID==ServiceGateway||service.ID==ServiceAuthn||service.ID==ServiceSecrets||service.ID==ServiceExecutor||service.ID==ServiceUpdater||service.ID==ServiceUpdateFetcher||service.ID==ServiceProvider||service.ID==ServiceWebEngine{receipts=append(receipts,mutation("defer_service_enable",string(service.ID),digestText(unit),host.now()));continue};output,err:=runFixed(ctx,"/usr/bin/systemctl","enable","--now",unit);if err!=nil&&service.Required{return nil,err};receipts=append(receipts,mutation("enable_service",string(service.ID),digestText(output),host.now()))};return receipts,nil}
func (host *LinuxHost)ProbeServices(ctx context.Context,tuple PlatformTuple,services []ServiceSpec)([]HealthReceipt,error){receipts:=[]HealthReceipt{};seen:=map[ServiceID]bool{};for _,service:=range services{if seen[service.ID]{continue};seen[service.ID]=true;if err:=service.Validate();err!=nil{return nil,err};deadline:=host.now().Add(service.StartupTimeout);var evidence string;var err error;for{evidence,err=probeService(ctx,tuple.Distribution,service);if err==nil||!host.now().Before(deadline){break};select{case <-ctx.Done():return nil,ctx.Err();case <-time.After(500*time.Millisecond):}};healthy:=err==nil;receipts=append(receipts,HealthReceipt{Service:service.ID,Check:service.Health,Healthy:healthy,EvidenceDigest:digestText(evidence),ObservedAt:host.now()});if !healthy&&service.Required{return receipts,fmt.Errorf("%w: %s: %v",ErrUnhealthy,service.ID,err)}};return receipts,nil}

func (host *LinuxHost)ActivateSlot(ctx context.Context,slot SlotID,releaseID string)(MutationReceipt,error){
	if (slot!=SlotA&&slot!=SlotB)||!safeID.MatchString(releaseID){return MutationReceipt{},ErrInvalid}
	target:=filepath.Join(slotRoot,string(slot));info,err:=os.Stat(target);if err!=nil||!info.IsDir(){return MutationReceipt{},ErrNotFound}
	if err:=atomicWriteManaged(filepath.Join(target,"RELEASE"),[]byte(releaseID+"\n"),0644,0,0);err!=nil{return MutationReceipt{},err}
	pathIDs:=make([]ManagedPathID,0,len(closedPaths));for id:=range closedPaths{pathIDs=append(pathIDs,id)};sort.Slice(pathIDs,func(i,j int)bool{return pathIDs[i]<pathIDs[j]})
	for _,id:=range pathIDs{
		source:=managedSlotPath(slot,id);sourceInfo,sourceErr:=os.Lstat(source)
		if os.IsNotExist(sourceErr){if id==PathCPanelArchiveMigratorService{if err:=removeReleaseLink(managedPath(id));err!=nil{return MutationReceipt{},err}};continue}
		if sourceErr!=nil||sourceInfo.Mode()&os.ModeSymlink!=0||!sourceInfo.Mode().IsRegular(){return MutationReceipt{},ErrIntegrity}
		destination:=managedPath(id);if id==PathProductUpdateTrust{if err:=installProductUpdateTrust(source,destination);err!=nil{return MutationReceipt{},err};continue};if err:=secureMkdir(filepath.Dir(destination),0755);err!=nil{return MutationReceipt{},err}
		temporaryPath:=destination+".new";_ = os.Remove(temporaryPath);if err:=os.Symlink(source,temporaryPath);err!=nil{return MutationReceipt{},err};if err:=os.Rename(temporaryPath,destination);err!=nil{return MutationReceipt{},err}
	}
	if _,err:=runFixed(ctx,"/usr/bin/systemd-tmpfiles","--create","/etc/tmpfiles.d/cyberpanel.conf");err!=nil{return MutationReceipt{},err};if err:=validateCPanelMigrationPackaging();err!=nil{return MutationReceipt{},err};if err:=validateProductUpdatePackaging();err!=nil{return MutationReceipt{},err}
	executableIDs:=make([]ExecutablePathID,0,len(closedExecutablePaths));for id:=range closedExecutablePaths{executableIDs=append(executableIDs,id)};sort.Slice(executableIDs,func(i,j int)bool{return executableIDs[i]<executableIDs[j]})
	bootstrapUpdater:=false
	for _,id:=range executableIDs{
		source:=executableSlotPath(slot,id);sourceInfo,sourceErr:=os.Lstat(source)
		if os.IsNotExist(sourceErr)&&id==ExecutableCPanelArchiveMigrator{if err:=removeReleaseLink(executablePath(id));err!=nil{return MutationReceipt{},err};continue}
		if sourceErr!=nil||sourceInfo.Mode()&os.ModeSymlink!=0||!sourceInfo.Mode().IsRegular(){return MutationReceipt{},ErrIntegrity};if err:=verifyRootExecutable(source);err!=nil{return MutationReceipt{},err}
		destination:=executablePath(id);if err:=secureMkdir(filepath.Dir(destination),0755);err!=nil{return MutationReceipt{},err}
		if id==ExecutablePanelUpdater{destinationInfo,destinationErr:=os.Lstat(destination);if destinationErr==nil{resolved,resolveErr:=filepath.EvalSymlinks(destination);if destinationInfo.Mode()&os.ModeSymlink==0||resolveErr!=nil||!strings.HasPrefix(resolved,slotRoot+string(os.PathSeparator))||verifyRootExecutable(resolved)!=nil{return MutationReceipt{},ErrIntegrity};continue};if !os.IsNotExist(destinationErr){return MutationReceipt{},destinationErr};bootstrapUpdater=true}
		temporaryPath:=destination+".new";_ = os.Remove(temporaryPath);if err:=os.Symlink(source,temporaryPath);err!=nil{return MutationReceipt{},err};if err:=os.Rename(temporaryPath,destination);err!=nil{return MutationReceipt{},err}
	}
	temporary:=activeLink+".new";_ = os.Remove(temporary);if err:=os.Symlink(target,temporary);err!=nil{return MutationReceipt{},err};if err:=os.Rename(temporary,activeLink);err!=nil{return MutationReceipt{},err}
	if _,err:=runFixed(ctx,"/usr/bin/systemctl","daemon-reload");err!=nil{return MutationReceipt{},err}
	if bootstrapUpdater{if _,err:=runFixed(ctx,"/usr/bin/systemctl","enable","panel-updated.service");err!=nil{return MutationReceipt{},err};if _,err=runFixed(ctx,"/usr/bin/systemctl","restart","panel-updated.service");err!=nil{return MutationReceipt{},err}}
	units:=[]string{"panel-authd.service","panel-secretd.service","panel-execd.service","panel-providerd.service","lsws.service","panel-core.service","panel-gateway.service","panel-update-fetchd.service"};for _,unit:=range units{if _,err:=runFixed(ctx,"/usr/bin/systemctl","enable",unit);err!=nil{return MutationReceipt{},err};if _,err=runFixed(ctx,"/usr/bin/systemctl","restart",unit);err!=nil{return MutationReceipt{},err};if unit=="panel-secretd.service"{binary:=filepath.Join(target,"components",string(ComponentPanel),"cyberpanel");if err:=trustedExecutable(binary);err!=nil{return MutationReceipt{},err};if _,err:=runPanelHook(ctx,binary,"reconcile-services","--release",releaseID,"--component",string(ComponentPanel));err!=nil{return MutationReceipt{},err}}}
	for _,unit:=range []string{"mariadb.service","pdns.service","pure-ftpd.service","postfix.service","dovecot.service","rspamd.service","clamav-daemon.service","clamd@scan.service","redis.service","memcached.service","nftables.service","cron.service","crond.service"}{_,_ = runFixed(ctx,"/usr/bin/systemctl","try-restart",unit)}
	return mutation("activate_slot",string(slot),digestText(releaseID+":"+string(slot)),host.now()),nil
}

func removeReleaseLink(path string)error{
	info,err:=os.Lstat(path);if os.IsNotExist(err){return nil};if err!=nil{return err};if info.Mode()&os.ModeSymlink==0{return ErrIntegrity}
	target,err:=os.Readlink(path);if err!=nil{return err};if !filepath.IsAbs(target){target=filepath.Join(filepath.Dir(path),target)};target=filepath.Clean(target)
	if !strings.HasPrefix(target,slotRoot+string(os.PathSeparator)){return ErrIntegrity};return os.Remove(path)
}

func validateCPanelMigrationPackaging()error{
	uid,gid,err:=identityIDs(IdentityPanel,IdentityPanel);if err!=nil{return err}
	var filesystem uint64
	for index,path:=range []string{"/var/lib/cyberpanel/migration/cpanel-intake","/var/lib/cyberpanel/migration/cpanel-quarantine"}{
		info,statErr:=os.Lstat(path);if statErr!=nil{return statErr};metadata,ok:=info.Sys().(*syscall.Stat_t)
		if !ok||!info.IsDir()||info.Mode()&os.ModeSymlink!=0||info.Mode().Perm()!=0700||int(metadata.Uid)!=uid||int(metadata.Gid)!=gid{return ErrIntegrity}
		if index==0{filesystem=uint64(metadata.Dev)}else if uint64(metadata.Dev)!=filesystem{return ErrIntegrity}
	}
	for _,path:=range []string{"/etc/cyberpanel/migration","/etc/cyberpanel/migration/cpanel-archive"}{
		info,statErr:=os.Lstat(path);if statErr!=nil{return statErr};metadata,ok:=info.Sys().(*syscall.Stat_t)
		if !ok||!info.IsDir()||info.Mode()&os.ModeSymlink!=0||info.Mode().Perm()!=0750||metadata.Uid!=0||int(metadata.Gid)!=gid{return ErrIntegrity}
	}
	trust,err:=os.Lstat("/etc/cyberpanel/migration/trust.json");if err!=nil{return err};metadata,ok:=trust.Sys().(*syscall.Stat_t)
	if !ok||!trust.Mode().IsRegular()||trust.Mode()&os.ModeSymlink!=0||trust.Mode().Perm()!=0640||metadata.Uid!=0||int(metadata.Gid)!=gid||metadata.Nlink!=1{return ErrIntegrity}
	return nil
}
func validateProductUpdatePackaging()error{
	panelUID,panelGID,err:=identityIDs(IdentityPanel,IdentityPanel);if err!=nil{return err}
	type directoryPolicy struct{path string;mode os.FileMode;uid,gid int}
	policies:=[]directoryPolicy{
		{"/run/cyberpanel-product-updater",0711,0,0},
		{"/var/lib/cyberpanel/product-updater",0700,0,0},
		{"/var/lib/cyberpanel/product-updater/journal",0700,0,0},
		{"/var/lib/cyberpanel/product-updater/baselines",0700,0,0},
		{"/var/lib/cyberpanel/control/product-update-staging",0700,panelUID,panelGID},
		{"/var/lib/cyberpanel/product-update-spool",0700,panelUID,panelGID},
		{"/var/lib/cyberpanel/product-update-spool/ready",0700,panelUID,panelGID},
		{"/var/lib/cyberpanel/product-updater/inbox",0700,0,0},
		{"/var/lib/cyberpanel/product-updater/inbox/ready",0700,0,0},
		{"/var/lib/cyberpanel/product-updater/inbox/accepted",0700,0,0},
		{"/var/lib/cyberpanel/product-updates",0750,0,panelGID},
		{"/var/lib/cyberpanel/product-updates/manifests",0750,0,panelGID},
		{"/var/lib/cyberpanel/product-updates/artifacts",0750,0,panelGID},
		{"/var/lib/cyberpanel/product-updates/channels",0750,0,panelGID},
		{"/var/backups/cyberpanel/product-updates",0700,0,0},
		{"/etc/cyberpanel/product-update",0750,0,panelGID},
	}
	for _,policy:=range policies{info,statErr:=os.Lstat(policy.path);if statErr!=nil{return statErr};metadata,ok:=info.Sys().(*syscall.Stat_t);if !ok||!info.IsDir()||info.Mode()&os.ModeSymlink!=0||info.Mode().Perm()!=policy.mode||int(metadata.Uid)!=policy.uid||int(metadata.Gid)!=policy.gid{return ErrIntegrity}}
	trust,err:=os.Lstat("/etc/cyberpanel/product-update/trust.json");if err!=nil{return err};metadata,ok:=trust.Sys().(*syscall.Stat_t)
	if !ok||!trust.Mode().IsRegular()||trust.Mode()&os.ModeSymlink!=0||trust.Mode().Perm()!=0640||metadata.Uid!=0||int(metadata.Gid)!=panelGID||metadata.Nlink!=1{return ErrIntegrity}
	return nil
}
func (host *LinuxHost)CurrentSlot(ctx context.Context)(SlotID,string,error){target,err:=filepath.EvalSymlinks(activeLink);if err!=nil{return "","",err};clean:=filepath.Clean(target);for _,slot:=range []SlotID{SlotA,SlotB}{if clean==filepath.Join(slotRoot,string(slot)){release,err:=readTrimmed(filepath.Join(clean,"RELEASE"));if err!=nil||!safeID.MatchString(release){return "","",ErrIntegrity};return slot,release,nil}};return "","",ErrIntegrity}

func (host *LinuxHost)Deactivate(ctx context.Context,state InstalledState,purge bool)(MutationReceipt,error){
	if err:=state.Validate();err!=nil{return MutationReceipt{},err}
	services:=[]ServiceID{ServiceUpdateFetcher,ServiceGateway,ServicePanel,ServiceProvider,ServiceExecutor,ServiceSecrets,ServiceAuthn,ServiceWebEngine,ServiceScheduler,ServiceFirewall,ServiceMemcached,ServiceRedis,ServiceClamAV,ServiceRspamd,ServiceDovecot,ServicePostfix,ServiceFTP,ServiceDNS,ServiceDatabase,ServiceUpdater}
	for _,service:=range services{unit,err:=nativeService(state.Tuple.Distribution,service);if err!=nil{continue};_,_ = runFixed(ctx,"/usr/bin/systemctl","disable","--now",unit)}
	_ = os.Remove(activeLink)
	for pathID:=range closedExecutablePaths{destination:=executablePath(pathID);target,err:=filepath.EvalSymlinks(destination);if err==nil&&strings.HasPrefix(filepath.Clean(target),slotRoot+string(os.PathSeparator)){_ = os.Remove(destination)}}
	retained:=map[ManagedPathID]bool{PathAuthnConfig:true,PathProductUpdateTrust:true,PathDatabaseConfig:true,PathDNSConfig:true,PathFTPConfig:true,PathPostfixConfig:true,PathDovecotConfig:true}
	retainedRoot:=filepath.Join(installerRoot,"retained",state.ReleaseID);if purge{if err:=secureMkdir(retainedRoot,0700);err!=nil{return MutationReceipt{},err}}
	for pathID:=range closedPaths{
		destination:=managedPath(pathID)
		if retained[pathID]&&purge{
			source:=managedSlotPath(state.ActiveSlot,pathID);info,statErr:=os.Stat(source)
			if statErr!=nil&&pathID==PathProductUpdateTrust{return MutationReceipt{},statErr}
			if statErr==nil&&info.Mode().IsRegular(){payload,readErr:=os.ReadFile(source);if readErr!=nil{return MutationReceipt{},readErr};owner,group,_:=managedFilePolicy(pathID);uid,gid,identityErr:=identityIDs(owner,group);if identityErr!=nil{return MutationReceipt{},identityErr};retainedPath:=filepath.Join(retainedRoot,string(pathID));if err:=atomicWriteManaged(retainedPath,payload,info.Mode().Perm()&0770,uid,gid);err!=nil{return MutationReceipt{},err};if pathID==PathProductUpdateTrust{if err:=installProductUpdateTrust(retainedPath,destination);err!=nil{return MutationReceipt{},err};continue};temporary:=destination+".new";_ = os.Remove(temporary);if err:=os.Symlink(retainedPath,temporary);err!=nil{return MutationReceipt{},err};if err:=os.Rename(temporary,destination);err!=nil{return MutationReceipt{},err};continue}
		}
		_ = os.Remove(destination)
	}
	_,_ = runFixed(ctx,"/usr/bin/systemctl","daemon-reload")
	if purge{for _,slot:=range []SlotID{SlotA,SlotB}{target:=filepath.Join(slotRoot,string(slot));if strings.HasPrefix(target,slotRoot+string(os.PathSeparator)){_ = os.RemoveAll(target)}}}
	return mutation("deactivate",state.ReleaseID,digestText(strconv.FormatBool(purge)),host.now()),nil
}
func (host *LinuxHost)Export(ctx context.Context,state InstalledState,path string)(ExportReceipt,error){if err:=state.Validate();err!=nil{return ExportReceipt{},err};clean:=filepath.Clean(path);if !filepath.IsAbs(clean)||!strings.HasPrefix(clean,exportRoot+string(os.PathSeparator))||filepath.Ext(clean)!=".gz"{return ExportReceipt{},ErrInvalid};if existing,err:=inspectExport(clean);err==nil{return existing,nil}else if !os.IsNotExist(err){return ExportReceipt{},err};if err:=secureMkdir(exportRoot,0700);err!=nil{return ExportReceipt{},err};file,err:=os.OpenFile(clean,os.O_CREATE|os.O_EXCL|os.O_WRONLY|syscall.O_NOFOLLOW,0600);if err!=nil{return ExportReceipt{},err};hasher:=sha256.New();counting:=&countWriter{writer:io.MultiWriter(file,hasher)};gzipWriter:=gzip.NewWriter(counting);archive:=tar.NewWriter(gzipWriter);manifest:=[]string{};roots:=[]string{"/etc/cyberpanel",installerRoot,"/var/lib/cyberpanel",filepath.Join(slotRoot,string(state.ActiveSlot),"managed")};for _,root:=range roots{if err:=appendExportTree(ctx,archive,root,&manifest);err!=nil{archive.Close();gzipWriter.Close();file.Close();_ = os.Remove(clean);return ExportReceipt{},err}};sort.Strings(manifest);manifestPayload:=[]byte(strings.Join(manifest,"\n")+"\n");header:=&tar.Header{Name:"MANIFEST.sha256",Mode:0600,Size:int64(len(manifestPayload)),ModTime:host.now()};if err:=archive.WriteHeader(header);err==nil{_,err=archive.Write(manifestPayload)};closeErr:=errors.Join(archive.Close(),gzipWriter.Close(),file.Sync(),file.Close());if err!=nil||closeErr!=nil{_ = os.Remove(clean);return ExportReceipt{},errors.Join(err,closeErr)};manifestDigest:=digestText(string(manifestPayload));return ExportReceipt{Path:clean,Digest:hex.EncodeToString(hasher.Sum(nil)),ManifestDigest:manifestDigest,Bytes:counting.count,CompletedAt:host.now()},nil}
func (host *LinuxHost)CleanupTransaction(ctx context.Context,plan TransactionPlan,success bool)error{if !safeID.MatchString(plan.ID){return ErrInvalid};path:=filepath.Join(stagingRoot,plan.ID);if !strings.HasPrefix(path,stagingRoot+string(os.PathSeparator)){return ErrIntegrity};cleanupErr:=os.RemoveAll(path);if !success&&(plan.TargetSlot==SlotA||plan.TargetSlot==SlotB){active,_,activeErr:=host.CurrentSlot(ctx);if activeErr!=nil||active!=plan.TargetSlot{target:=filepath.Join(slotRoot,string(plan.TargetSlot));if strings.HasPrefix(target,slotRoot+string(os.PathSeparator)){cleanupErr=errors.Join(cleanupErr,os.RemoveAll(target))}}else if plan.Kind==TransactionInstall{_ = os.Remove(activeLink);for id:=range closedPaths{destination:=managedPath(id);if id==PathProductUpdateTrust{_ = os.Remove(destination);continue};source:=managedSlotPath(plan.TargetSlot,id);if target,err:=filepath.EvalSymlinks(destination);err==nil&&target==source{_ = os.Remove(destination)}};for _,unit:=range []string{"panel-update-fetchd.service","panel-gateway.service","panel-core.service","panel-providerd.service","panel-authd.service","panel-secretd.service","panel-execd.service","lsws.service","panel-updated.service"}{_,_ = runFixed(ctx,"/usr/bin/systemctl","disable","--now",unit)};target:=filepath.Join(slotRoot,string(plan.TargetSlot));cleanupErr=errors.Join(cleanupErr,os.RemoveAll(target))}};return cleanupErr}

func parseOSRelease()(map[string]string,error){payload,err:=os.ReadFile("/etc/os-release");if err!=nil{return nil,err};result:=map[string]string{};for _,line:=range strings.Split(string(payload),"\n"){key,value,ok:=strings.Cut(line,"=");if !ok||key==""{continue};result[key]=strings.Trim(strings.TrimSpace(value),"\"")};return result,nil}
func dialPublicHTTPS(ctx context.Context,network,address string)(net.Conn,error){host,port,err:=net.SplitHostPort(address);if err!=nil{return nil,err};addresses,err:=net.DefaultResolver.LookupIPAddr(ctx,host);if err!=nil{return nil,err};dialer:=net.Dialer{Timeout:30*time.Second,KeepAlive:30*time.Second};for _,candidate:=range addresses{ip:=candidate.IP;if !ip.IsGlobalUnicast()||ip.IsPrivate()||ip.IsLoopback()||ip.IsLinkLocalUnicast()||ip.IsLinkLocalMulticast(){continue};connection,err:=dialer.DialContext(ctx,network,net.JoinHostPort(ip.String(),port));if err==nil{return connection,nil}};return nil,ErrIntegrity}
func majorRelease(value string)string{if before,_,ok:=strings.Cut(value,".");ok{return before};return value}
func readTrimmed(path string)(string,error){payload,err:=os.ReadFile(path);if err!=nil{return "",err};return strings.TrimSpace(string(payload)),nil}
func readMemory()uint64{payload,_:=os.ReadFile("/proc/meminfo");for _,line:=range strings.Split(string(payload),"\n"){fields:=strings.Fields(line);if len(fields)>=2&&fields[0]=="MemTotal:"{value,_:=strconv.ParseUint(fields[1],10,64);return value*1024}};return 0}
func diskFacts(path string)(uint64,string,error){var stat syscall.Statfs_t;if err:=syscall.Statfs(path,&stat);err!=nil{return 0,"",err};return stat.Bavail*uint64(stat.Bsize),fmt.Sprintf("0x%x",stat.Type),nil}
func runtimeCPUCount()int{payload,_:=os.ReadFile("/proc/cpuinfo");count:=strings.Count(string(payload),"\nprocessor");if strings.HasPrefix(string(payload),"processor"){count++};if count<1{return 1};return count}
func occupiedTCPPorts()([]uint16,error){seen:=map[uint16]bool{};for _,path:=range []string{"/proc/net/tcp","/proc/net/tcp6"}{payload,err:=os.ReadFile(path);if err!=nil{continue};for _,line:=range strings.Split(string(payload),"\n")[1:]{fields:=strings.Fields(line);if len(fields)<4||fields[3]!="0A"{continue};_,portText,ok:=strings.Cut(fields[1],":");if !ok{continue};port,err:=strconv.ParseUint(portText,16,16);if err==nil{seen[uint16(port)]=true}}};ports:=make([]uint16,0,len(seen));for port:=range seen{ports=append(ports,port)};sort.Slice(ports,func(i,j int)bool{return ports[i]<ports[j]});return ports,nil}

func secureMkdir(path string,mode os.FileMode)error{clean:=filepath.Clean(path);if !filepath.IsAbs(clean){return ErrInvalid};current:=string(os.PathSeparator);for _,part:=range strings.Split(strings.TrimPrefix(clean,string(os.PathSeparator)),string(os.PathSeparator)){current=filepath.Join(current,part);info,err:=os.Lstat(current);if os.IsNotExist(err){if err:=os.Mkdir(current,mode);err!=nil{return err};continue};if err!=nil{return err};if info.Mode()&os.ModeSymlink!=0||!info.IsDir(){return ErrIntegrity}};return os.Chmod(clean,mode)}
func runFixed(ctx context.Context,executable string,arguments ...string)(string,error){allowed:=map[string]bool{"/usr/sbin/useradd":true,"/usr/sbin/usermod":true,"/usr/bin/apt-get":true,"/usr/bin/dnf":true,"/usr/bin/systemctl":true,"/usr/bin/systemd-tmpfiles":true};if !allowed[executable]{return "",ErrUnsupported};command:=exec.CommandContext(ctx,executable,arguments...);command.Env=[]string{"PATH=/usr/sbin:/usr/bin:/sbin:/bin","LANG=C.UTF-8","LC_ALL=C.UTF-8","DEBIAN_FRONTEND=noninteractive"};output,err:=command.CombinedOutput();if len(output)>1<<20{output=output[:1<<20]};if err!=nil{return string(output),fmt.Errorf("%s: %w",filepath.Base(executable),err)};return string(output),nil}

func ensureContainerSubordinateIDs(ctx context.Context,name string)error{const count uint64=65536;uidRanges,uidPresent,err:=readSubordinateRanges("/etc/subuid",name);if err!=nil{return err};gidRanges,gidPresent,err:=readSubordinateRanges("/etc/subgid",name);if err!=nil{return err};if uidPresent&&gidPresent{return nil};occupied:=append(uidRanges,gidRanges...);start:=uint64(524288);for{end:=start+count-1;conflict:=false;for _,entry:=range occupied{if start<=entry[1]&&entry[0]<=end{conflict=true;break}};if !conflict{span:=strconv.FormatUint(start,10)+"-"+strconv.FormatUint(end,10);arguments:=[]string{};if !uidPresent{arguments=append(arguments,"--add-subuids",span)};if !gidPresent{arguments=append(arguments,"--add-subgids",span)};arguments=append(arguments,name);_,err=runFixed(ctx,"/usr/sbin/usermod",arguments...);return err};start+=count;if start>1<<31{return ErrIntegrity}}}
func readSubordinateRanges(path,name string)([][2]uint64,bool,error){content,err:=os.ReadFile(path);if errors.Is(err,os.ErrNotExist){return nil,false,nil};if err!=nil{return nil,false,err};ranges:=make([][2]uint64,0);present:=false;for _,line:=range strings.Split(string(content),"\n"){fields:=strings.Split(line,":");if len(fields)!=3{continue};start,startErr:=strconv.ParseUint(fields[1],10,64);count,countErr:=strconv.ParseUint(fields[2],10,64);if startErr!=nil||countErr!=nil||count==0||start+count<start{return nil,false,ErrIntegrity};ranges=append(ranges,[2]uint64{start,start+count-1});if fields[0]==name&&count>=65536{present=true}};return ranges,present,nil}

func identityRecord(identity IdentityID)(string,string,string){switch identity{case IdentityPanel:return "cyberpanel","/var/lib/cyberpanel/control","/usr/sbin/nologin";case IdentityGateway:return "cyberpanel-gateway","/var/lib/cyberpanel-gateway","/usr/sbin/nologin";case IdentityAuthn:return "cyberpanel-auth","/var/lib/cyberpanel-auth","/usr/sbin/nologin";case IdentitySecrets:return "cyberpanel-secrets","/var/lib/cyberpanel-secrets","/usr/sbin/nologin";case IdentityContainers:return "cyberpanel-containers","/var/lib/cyberpanel-containers","/usr/sbin/nologin";case IdentityWebAdmin:return "lsadm","/var/lib/lsadm","/usr/sbin/nologin"};return "","",""}
func identityIDs(owner,group IdentityID)(int,int,error){uid:=0;gid:=0;if owner!=IdentityRoot{account,err:=user.Lookup(identityName(owner));if err!=nil{return 0,0,err};parsed,err:=strconv.Atoi(account.Uid);if err!=nil||parsed==0{return 0,0,ErrIntegrity};uid=parsed};if group!=IdentityRoot{account,err:=user.Lookup(identityName(group));if err!=nil{return 0,0,err};parsed,err:=strconv.Atoi(account.Gid);if err!=nil||parsed==0{return 0,0,ErrIntegrity};gid=parsed};return uid,gid,nil}
func identityName(identity IdentityID)string{if identity==IdentityRoot{return "root"};name,_,_:=identityRecord(identity);return name}
func nativePackage(distribution Distribution,id PackageID)(string,error){ubuntu:=map[PackageID]string{PackageCACertificates:"ca-certificates",PackageOpenSSL:"openssl",PackageTar:"tar",PackageGzip:"gzip",PackageXZ:"xz-utils",PackageZstd:"zstd",PackageSQLite:"sqlite3",PackageNftables:"nftables",PackageCron:"cron",PackagePodman:"podman",PackageSkopeo:"skopeo",PackageShadowUtils:"passwd",PackageMariaDBServer:"mariadb-server",PackageMariaDBClient:"mariadb-client",PackageMariaDBBackup:"mariadb-backup",PackagePowerDNS:"pdns-server",PackagePowerDNSMySQL:"pdns-backend-mysql",PackagePowerDNSSQLite:"pdns-backend-sqlite3",PackageDNSUtils:"dnsutils",PackagePureFTP:"pure-ftpd",PackagePostfix:"postfix",PackagePostfixMySQL:"postfix-mysql",PackageDovecotCore:"dovecot-core",PackageDovecotIMAP:"dovecot-imapd",PackageDovecotLMTP:"dovecot-lmtpd",PackageDovecotMySQL:"dovecot-mysql",PackageDovecotSieve:"dovecot-sieve",PackageRspamd:"rspamd",PackageClamAV:"clamav",PackageClamAVDaemon:"clamav-daemon",PackageRedis:"redis-server",PackageMemcached:"memcached",PackageLibcap:"libcap2-bin",PackageUnzip:"unzip",PackageZip:"zip",PackageGit:"git",PackageRsync:"rsync",PackageCurl:"curl",PackageOpenSSHClient:"openssh-client",PackageOpenSSHServer:"openssh-server",PackageFindutils:"findutils",PackageCoreutils:"coreutils",PackageNodeJS:"nodejs",PackagePython3:"python3"};alma:=map[PackageID]string{PackageCACertificates:"ca-certificates",PackageOpenSSL:"openssl",PackageTar:"tar",PackageGzip:"gzip",PackageXZ:"xz",PackageZstd:"zstd",PackageSQLite:"sqlite",PackageNftables:"nftables",PackageCron:"cronie",PackagePodman:"podman",PackageSkopeo:"skopeo",PackageShadowUtils:"shadow-utils",PackageMariaDBServer:"MariaDB-server",PackageMariaDBClient:"MariaDB-client",PackageMariaDBBackup:"MariaDB-backup",PackagePowerDNS:"pdns",PackagePowerDNSMySQL:"pdns-backend-mysql",PackagePowerDNSSQLite:"pdns-backend-sqlite",PackageDNSUtils:"bind-utils",PackagePureFTP:"pure-ftpd",PackagePostfix:"postfix",PackagePostfixMySQL:"postfix-mysql",PackageDovecotCore:"dovecot",PackageDovecotIMAP:"dovecot",PackageDovecotLMTP:"dovecot",PackageDovecotMySQL:"dovecot-mysql",PackageDovecotSieve:"dovecot-pigeonhole",PackageRspamd:"rspamd",PackageClamAV:"clamav",PackageClamAVDaemon:"clamd",PackageRedis:"redis",PackageMemcached:"memcached",PackageLibcap:"libcap",PackageUnzip:"unzip",PackageZip:"zip",PackageGit:"git",PackageRsync:"rsync",PackageCurl:"curl",PackageOpenSSHClient:"openssh-clients",PackageOpenSSHServer:"openssh-server",PackageFindutils:"findutils",PackageCoreutils:"coreutils",PackageNodeJS:"nodejs",PackagePython3:"python3"};name:=ubuntu[id];if distribution==DistributionAlma{name=alma[id]};if name==""{return "",ErrUnsupported};return name,nil}
func verifyRepositorySnapshot(selection PackageSelection)(string,error){path:=filepath.Join("/etc/cyberpanel/installer/repositories",selection.RepositoryID+".json");info,err:=os.Stat(path);if err!=nil{return "",err};if err:=requireRootOwned(info,0644);err!=nil{return "",err};payload,err:=os.ReadFile(path);if err!=nil{return "",err};var record struct{ID string `json:"id"`;SnapshotDigest string `json:"snapshot_digest"`;Receipt string `json:"receipt"`};if json.Unmarshal(payload,&record)!=nil||record.ID!=selection.RepositoryID||record.SnapshotDigest!=selection.RepositorySnapshotDigest||record.Receipt==""{return "",ErrIntegrity};return record.Receipt,nil}
func nativeService(distribution Distribution,id ServiceID)(string,error){common:=map[ServiceID]string{ServicePanel:"panel-core.service",ServiceGateway:"panel-gateway.service",ServiceAuthn:"panel-authd.service",ServiceSecrets:"panel-secretd.service",ServiceExecutor:"panel-execd.service",ServiceUpdater:"panel-updated.service",ServiceUpdateFetcher:"panel-update-fetchd.service",ServiceProvider:"panel-providerd.service",ServiceWebEngine:"lsws.service",ServiceDatabase:"mariadb.service",ServiceDNS:"pdns.service",ServiceFTP:"pure-ftpd.service",ServicePostfix:"postfix.service",ServiceDovecot:"dovecot.service",ServiceRspamd:"rspamd.service",ServiceRedis:"redis.service",ServiceMemcached:"memcached.service",ServiceFirewall:"nftables.service",ServiceScheduler:"cron.service",ServiceClamAV:"clamav-daemon.service"};if distribution==DistributionAlma{common[ServiceScheduler]="crond.service";common[ServiceClamAV]="clamd@scan.service"};unit:=common[id];if unit==""{return "",ErrUnsupported};return unit,nil}
func managedPath(id ManagedPathID)string{paths:=map[ManagedPathID]string{PathPanelEnvironment:"/etc/cyberpanel/panel.env",PathPanelService:"/etc/systemd/system/panel-core.service",PathPanelConfig:"/etc/cyberpanel/panel-core.json",PathGatewayService:"/etc/systemd/system/panel-gateway.service",PathGatewayConfig:"/etc/cyberpanel/panel-gateway.json",PathAuthnService:"/etc/systemd/system/panel-authd.service",PathAuthnConfig:"/etc/cyberpanel/authn.json",PathSecretsService:"/etc/systemd/system/panel-secretd.service",PathExecutorService:"/etc/systemd/system/panel-execd.service",PathUpdaterService:"/etc/systemd/system/panel-updated.service",PathUpdateFetcherService:"/etc/systemd/system/panel-update-fetchd.service",PathProductUpdateTrust:"/etc/cyberpanel/product-update/trust.json",PathProductUpdateFeed:"/etc/cyberpanel/product-update/feed.json",PathProviderService:"/etc/systemd/system/panel-providerd.service",PathCPanelArchiveMigratorService:"/etc/systemd/system/cpanel-archive-migrator@.service",PathWebEngineService:"/etc/systemd/system/lsws.service",PathWebEngineEdition:"/etc/cyberpanel/webengine-edition",PathWebEngineConfig:"/etc/cyberpanel/webengine/httpd_config.conf",PathDatabaseConfig:"/etc/cyberpanel/database/server.cnf",PathDNSConfig:"/etc/cyberpanel/dns/pdns.conf",PathFTPConfig:"/etc/cyberpanel/ftp/pure-ftpd.conf",PathPostfixConfig:"/etc/cyberpanel/mail/postfix/main.cf",PathDovecotConfig:"/etc/cyberpanel/mail/dovecot/dovecot.conf",PathRspamdConfig:"/etc/cyberpanel/mail/rspamd/local.d/worker-controller.inc",PathClamAVConfig:"/etc/cyberpanel/mail/clamav/clamd.conf",PathFirewallConfig:"/etc/nftables.d/cyberpanel.nft",PathTmpfilesConfig:"/etc/tmpfiles.d/cyberpanel.conf",PathRedisTemplate:"/etc/systemd/system/redis-server@.service",PathElasticsearchTemplate:"/etc/systemd/system/elasticsearch@.service"};return paths[id]}
func installProductUpdateTrust(source,destination string)error{if destination!="/etc/cyberpanel/product-update/trust.json"{return ErrInvalid};payload,err:=os.ReadFile(source);if err!=nil{return err};uid,gid,err:=identityIDs(IdentityRoot,IdentityPanel);if err!=nil{return err};if err=atomicWriteManaged(destination,payload,0640,uid,gid);err!=nil{return err};directory:=filepath.Dir(destination);if err=os.Chown(directory,uid,gid);err!=nil{return err};return os.Chmod(directory,0750)}
func managedSlotPath(slot SlotID,id ManagedPathID)string{return filepath.Join(slotRoot,string(slot),"managed",string(id))}
func atomicWriteManaged(path string,payload []byte,mode os.FileMode,uid,gid int)error{if !filepath.IsAbs(path)||mode&0002!=0{return ErrInvalid};directoryMode:=os.FileMode(0755);for _,privateRoot:=range []string{installerRoot,"/etc/cyberpanel/secrets","/etc/cyberpanel/installer/input",exportRoot}{if path==privateRoot||strings.HasPrefix(path,privateRoot+string(os.PathSeparator)){directoryMode=0700}};if err:=secureMkdir(filepath.Dir(path),directoryMode);err!=nil{return err};temporary:=path+".new";file,err:=os.OpenFile(temporary,os.O_CREATE|os.O_EXCL|os.O_WRONLY|syscall.O_NOFOLLOW,mode);if os.IsExist(err){_ = os.Remove(temporary);file,err=os.OpenFile(temporary,os.O_CREATE|os.O_EXCL|os.O_WRONLY|syscall.O_NOFOLLOW,mode)};if err!=nil{return err};_,writeErr:=file.Write(payload);syncErr:=file.Sync();chownErr:=file.Chown(uid,gid);chmodErr:=file.Chmod(mode);closeErr:=file.Close();if joined:=errors.Join(writeErr,syncErr,chownErr,chmodErr,closeErr);joined!=nil{_ = os.Remove(temporary);return joined};return os.Rename(temporary,path)}
func mutation(operation,resource,digest string,now time.Time)MutationReceipt{return MutationReceipt{Operation:operation,Resource:resource,OutputDigest:digest,Receipt:operation+":"+resource,CompletedAt:now}}
func digestText(value string)string{sum:=sha256.Sum256([]byte(value));return hex.EncodeToString(sum[:])}
func hashFile(path string)(string,int64,error){file,err:=os.Open(path);if err!=nil{return "",0,err};defer file.Close();hasher:=sha256.New();size,err:=io.Copy(hasher,file);return hex.EncodeToString(hasher.Sum(nil)),size,err}
func detectArtifactFormat(path string)(ArtifactFormat,error){file,err:=os.Open(path);if err!=nil{return "",err};defer file.Close();header:=make([]byte,2);if _,err:=io.ReadFull(file,header);err!=nil{return "",err};if header[0]==0x1f&&header[1]==0x8b{return ArtifactTarGzip,nil};return ArtifactRaw,nil}
func componentBinary(component ComponentID)string{switch component{case ComponentPanel:return "cyberpanel";case ComponentAuthn:return "panel-authd";case ComponentSecrets:return "panel-secretd";case ComponentExecutor:return "panel-execd";case ComponentWebOpenLiteSpeed,ComponentWebEnterprise:return "lsws";default:return string(component)}}
func executableSlotPath(slot SlotID,id ExecutablePathID)string{return filepath.Join(slotRoot,string(slot),"components",string(ComponentExecutor),closedExecutablePaths[id])}
func executablePath(id ExecutablePathID)string{if closedExecutablePaths[id]==""{return ""};return filepath.Join("/usr/local/libexec/cyberpanel",closedExecutablePaths[id])}
func verifyRootExecutable(path string)error{info,err:=os.Lstat(path);if err!=nil{return err};metadata,ok:=info.Sys().(*syscall.Stat_t);if !ok||metadata.Uid!=0||info.Mode()&os.ModeSymlink!=0||!info.Mode().IsRegular()||info.Mode().Perm()&0022!=0||info.Mode().Perm()&0111==0{return ErrIntegrity};return nil}
func verifyArtifactMembers(component ComponentID,root string,members []ArtifactMember)error{if component!=ComponentExecutor{if len(members)>0{return ErrInvalid};return nil};seen:=map[ExecutablePathID]bool{};for _,member:=range members{if member.Validate()!=nil||seen[member.PathID]{return ErrInvalid};seen[member.PathID]=true;path:=filepath.Join(root,closedExecutablePaths[member.PathID]);if err:=verifyRootExecutable(path);err!=nil{return err};digest,_,err:=hashFile(path);if err!=nil||digest!=member.SHA256{return ErrIntegrity}};for pathID:=range closedExecutablePaths{if !seen[pathID]{return ErrIntegrity}};if len(seen)!=len(closedExecutablePaths){return ErrIntegrity};return nil}

func extractTarGzip(source,destination string)error{file,err:=os.Open(source);if err!=nil{return err};defer file.Close();gzipReader,err:=gzip.NewReader(file);if err!=nil{return err};defer gzipReader.Close();archive:=tar.NewReader(gzipReader);var total int64;for{header,err:=archive.Next();if errors.Is(err,io.EOF){break};if err!=nil{return err};clean:=filepath.Clean(header.Name);if clean=="."||filepath.IsAbs(clean)||strings.HasPrefix(clean,".."+string(os.PathSeparator))||strings.Contains(clean,"\\"){return ErrIntegrity};target:=filepath.Join(destination,clean);if !strings.HasPrefix(target,destination+string(os.PathSeparator)){return ErrIntegrity};switch header.Typeflag{case tar.TypeDir:if err:=secureMkdir(target,0755);err!=nil{return err};case tar.TypeReg,tar.TypeRegA:if header.Size<0||header.Size>4<<30{return ErrIntegrity};total+=header.Size;if total>16<<30{return ErrIntegrity};if err:=secureMkdir(filepath.Dir(target),0755);err!=nil{return err};mode:=os.FileMode(header.Mode)&0755;if mode&0111==0{mode=0644};output,err:=os.OpenFile(target,os.O_CREATE|os.O_EXCL|os.O_WRONLY|syscall.O_NOFOLLOW,mode);if err!=nil{return err};written,copyErr:=io.Copy(output,io.LimitReader(archive,header.Size+1));closeErr:=output.Close();if copyErr!=nil||closeErr!=nil||written!=header.Size{return errors.Join(ErrIntegrity,copyErr,closeErr)};default:return ErrIntegrity}};return nil}
func copyRegular(source,target string,mode os.FileMode)error{input,err:=os.Open(source);if err!=nil{return err};defer input.Close();output,err:=os.OpenFile(target,os.O_CREATE|os.O_EXCL|os.O_WRONLY|syscall.O_NOFOLLOW,mode);if err!=nil{return err};_,copyErr:=io.Copy(output,input);closeErr:=output.Close();return errors.Join(copyErr,closeErr)}
func digestTree(root string)(string,error){paths:=[]string{};if err:=filepath.Walk(root,func(path string,info os.FileInfo,err error)error{if err!=nil{return err};if path==root{return nil};if info.Mode()&os.ModeSymlink!=0||!info.Mode().IsRegular()&&!info.IsDir(){return ErrIntegrity};relative,err:=filepath.Rel(root,path);if err!=nil{return err};paths=append(paths,relative);return nil});err!=nil{return "",err};sort.Strings(paths);hasher:=sha256.New();for _,relative:=range paths{path:=filepath.Join(root,relative);info,err:=os.Stat(path);if err!=nil{return "",err};io.WriteString(hasher,relative+"\x00"+info.Mode().String()+"\x00");if info.Mode().IsRegular(){file,err:=os.Open(path);if err!=nil{return "",err};_,copyErr:=io.Copy(hasher,file);closeErr:=file.Close();if copyErr!=nil||closeErr!=nil{return "",errors.Join(copyErr,closeErr)}}};return hex.EncodeToString(hasher.Sum(nil)),nil}

func probeService(ctx context.Context,distribution Distribution,spec ServiceSpec)(string,error){unit,err:=nativeService(distribution,spec.ID);if err!=nil{return "",err};output,err:=runFixed(ctx,"/usr/bin/systemctl","is-active",unit);if err!=nil{return output,err};if spec.Health==HealthServiceActive{return strings.TrimSpace(output),nil};network,address:=healthAddress(spec.Health);if network=="unix"{connection,err:=net.DialTimeout(network,address,time.Second);if err!=nil{return output,err};connection.Close();return strings.TrimSpace(output)+":socket",nil};connection,err:=net.DialTimeout(network,address,time.Second);if err!=nil{return output,err};connection.Close();return strings.TrimSpace(output)+":"+address,nil}
func healthAddress(check HealthCheckID)(string,string){switch check{case HealthAuthnSocket:return "unix","/run/cyberpanel-auth/auth-verifier.sock";case HealthSecretsSocket:return "unix","/run/cyberpanel-secrets/material.sock";case HealthExecutorSocket:return "unix","/run/cyberpanel/panel-execd.sock";case HealthPanelAPI:return "tcp","127.0.0.1:8090";case HealthWebHTTP:return "tcp","127.0.0.1:80";case HealthDatabaseLocal:return "tcp","127.0.0.1:3306";case HealthDNSLocal:return "tcp","127.0.0.1:53";case HealthFTP:return "tcp","127.0.0.1:21";case HealthSMTP:return "tcp","127.0.0.1:25";case HealthIMAP:return "tcp","127.0.0.1:143";case HealthRspamd:return "tcp","127.0.0.1:11334";case HealthClamAV:return "tcp","127.0.0.1:3310";case HealthRedis:return "tcp","127.0.0.1:6379";case HealthMemcached:return "tcp","127.0.0.1:11211"};return "tcp","127.0.0.1:9"}
type countWriter struct{writer io.Writer;count uint64}
func (writer *countWriter)Write(payload []byte)(int,error){count,err:=writer.writer.Write(payload);writer.count+=uint64(count);return count,err}
func inspectExport(path string)(ExportReceipt,error){info,err:=os.Stat(path);if err!=nil{return ExportReceipt{},err};if err:=requireRootOwned(info,0600);err!=nil{return ExportReceipt{},err};digest,size,err:=hashFile(path);if err!=nil{return ExportReceipt{},err};file,err:=os.Open(path);if err!=nil{return ExportReceipt{},err};defer file.Close();compressed,err:=gzip.NewReader(file);if err!=nil{return ExportReceipt{},ErrIntegrity};defer compressed.Close();archive:=tar.NewReader(compressed);manifest:=[]byte(nil);for{header,nextErr:=archive.Next();if errors.Is(nextErr,io.EOF){break};if nextErr!=nil{return ExportReceipt{},ErrIntegrity};if header.Name=="MANIFEST.sha256"{if header.Size<1||header.Size>16<<20{return ExportReceipt{},ErrIntegrity};manifest,err=io.ReadAll(io.LimitReader(archive,header.Size+1));if err!=nil||int64(len(manifest))!=header.Size{return ExportReceipt{},ErrIntegrity}}};if len(manifest)==0{return ExportReceipt{},ErrIntegrity};return ExportReceipt{Path:path,Digest:digest,ManifestDigest:digestText(string(manifest)),Bytes:uint64(size),CompletedAt:info.ModTime().UTC()},nil}
func appendExportTree(ctx context.Context,archive *tar.Writer,root string,manifest *[]string)error{info,err:=os.Lstat(root);if os.IsNotExist(err){return nil};if err!=nil{return err};_ = info;base:=strings.TrimPrefix(filepath.Clean(root),"/");return filepath.Walk(root,func(path string,entry os.FileInfo,walkErr error)error{if walkErr!=nil{return walkErr};select{case <-ctx.Done():return ctx.Err();default:};if entry.Mode()&os.ModeSymlink!=0{return nil};relative,err:=filepath.Rel(root,path);if err!=nil{return err};name:=filepath.Join(base,relative);if relative=="."{name=base};header,err:=tar.FileInfoHeader(entry,"");if err!=nil{return err};header.Name=name;header.Uid=0;header.Gid=0;header.Uname="root";header.Gname="root";header.Mode&=0770;if err:=archive.WriteHeader(header);err!=nil{return err};if entry.Mode().IsRegular(){file,err:=os.Open(path);if err!=nil{return err};hasher:=sha256.New();_,copyErr:=io.Copy(io.MultiWriter(archive,hasher),file);closeErr:=file.Close();if copyErr!=nil||closeErr!=nil{return errors.Join(copyErr,closeErr)};*manifest=append(*manifest,hex.EncodeToString(hasher.Sum(nil))+"  "+name)};return nil})}
