package install

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"
)

type Request struct{TransactionID string `json:"transaction_id"`;CommandID string `json:"command_id"`;Kind TransactionKind `json:"kind"`;Tuple PlatformTuple `json:"tuple"`;TargetReleaseID string `json:"target_release_id,omitempty"`;EnterpriseLicense *EnterpriseLicenseRef `json:"enterprise_license,omitempty"`;ExportPath string `json:"export_path,omitempty"`;PurgeAfter time.Time `json:"purge_after,omitempty"`}
type Orchestrator struct{Store Store;Host Host;State StateInitializer;Watchdog Watchdog;Now func()time.Time;WatchdogTimeout time.Duration}
func (orchestrator Orchestrator)now()time.Time{if orchestrator.Now!=nil{return orchestrator.Now().UTC()};return time.Now().UTC()}
func (orchestrator Orchestrator)watchdogTimeout()time.Duration{if orchestrator.WatchdogTimeout>=30*time.Second&&orchestrator.WatchdogTimeout<=30*time.Minute{return orchestrator.WatchdogTimeout};return 5*time.Minute}

func (orchestrator Orchestrator)Execute(ctx context.Context,request Request,catalog Catalog)(TransactionPlan,error){if orchestrator.Store==nil||orchestrator.Host==nil||orchestrator.State==nil||orchestrator.Watchdog==nil{return TransactionPlan{},ErrInvalid};if !safeID.MatchString(request.TransactionID)||!safeID.MatchString(request.CommandID)||request.Tuple.Validate()!=nil{return TransactionPlan{},ErrInvalid};requestDigest,digestErr:=canonicalDigest(request);if digestErr!=nil{return TransactionPlan{},digestErr};var installed *InstalledState;state,loadErr:=orchestrator.Store.LoadInstalled(ctx);if loadErr==nil{installed=&state}else if !errors.Is(loadErr,ErrNotFound){return TransactionPlan{},loadErr};if request.Kind==TransactionUninstall{if request.ExportPath==""||!request.PurgeAfter.After(orchestrator.now().Add(24*time.Hour)){return TransactionPlan{},ErrInvalid}};plan,tupleCatalog,created,err:=orchestrator.admitPlan(ctx,request,catalog,installed,requestDigest);if err!=nil{return TransactionPlan{},err};if !created{switch plan.State{case TxCommitted,TxRolledBack:return plan,nil;case TxFailed,TxRecoveryRequired:return plan,ErrRollback}};if _,err:=orchestrator.Host.PrepareTransaction(ctx,plan);err!=nil{return orchestrator.fail(ctx,plan,"prepare transaction",err)};components:=ComponentMap(tupleCatalog);for plan.CurrentStep<uint32(len(plan.Steps)){index:=plan.CurrentStep;step:=plan.Steps[index];if step.State=="committed"{plan.CurrentStep++;continue};previous:=plan.Generation;plan.State=stateForStep(step.Kind);plan.Steps[index].State="executing";plan.Steps[index].StartedAt=orchestrator.now();plan.Generation++;plan.UpdatedAt=orchestrator.now();if err:=orchestrator.Store.UpdatePlan(ctx,plan,previous);err!=nil{return plan,err};receipt,stepErr:=orchestrator.executeStep(ctx,request,plan,tupleCatalog,components,step,installed);if stepErr!=nil{plan.Steps[index].State="failed";plan.Steps[index].Failure=stepErr.Error();plan.Steps[index].CompletedAt=orchestrator.now();if plan.Kind==TransactionUpgrade||plan.Kind==TransactionRollback{return orchestrator.rollbackActivation(ctx,plan,stepErr)};return orchestrator.fail(ctx,plan,step.ID,stepErr)};previous=plan.Generation;plan.Steps[index].State="committed";plan.Steps[index].Receipt=receipt;plan.Steps[index].CompletedAt=orchestrator.now();plan.CurrentStep++;plan.Generation++;plan.UpdatedAt=orchestrator.now();if err:=orchestrator.Store.UpdatePlan(ctx,plan,previous);err!=nil{return plan,err}}
	if err:=orchestrator.commitInstalled(ctx,request,&plan,tupleCatalog,installed);err!=nil{if plan.Kind==TransactionUpgrade||plan.Kind==TransactionRollback{return orchestrator.rollbackActivation(ctx,plan,err)};return orchestrator.fail(ctx,plan,"commit state",err)};_ = orchestrator.Host.CleanupTransaction(ctx,plan,true);return plan,nil}

func (orchestrator Orchestrator)admitPlan(ctx context.Context,request Request,catalog Catalog,installed *InstalledState,requestDigest string)(TransactionPlan,TupleCatalog,bool,error){catalogDigest,err:=canonicalDigest(catalog);if err!=nil{return TransactionPlan{},TupleCatalog{},false,err};if existing,loadErr:=orchestrator.Store.LoadPlan(ctx,request.TransactionID);loadErr==nil{if existing.CommandID!=request.CommandID||existing.Kind!=request.Kind||existing.Tuple.Key()!=request.Tuple.Key()||existing.RequestDigest!=requestDigest||existing.CatalogID!=catalog.CatalogID||existing.CatalogSequence!=catalog.Sequence||existing.CatalogDigest!=catalogDigest{return TransactionPlan{},TupleCatalog{},false,ErrConflict};tupleCatalog,err:=catalog.For(request.Tuple);return existing,tupleCatalog,false,err}else if !errors.Is(loadErr,ErrNotFound){return TransactionPlan{},TupleCatalog{},false,loadErr};compiled,tupleCatalog,err:=CompilePlan(CompileRequest{ID:request.TransactionID,CommandID:request.CommandID,Kind:request.Kind,Tuple:request.Tuple,RequestDigest:requestDigest,Catalog:catalog,Installed:installed,TargetReleaseID:request.TargetReleaseID,EnterpriseLicense:request.EnterpriseLicense,Now:orchestrator.now()});if err!=nil{return TransactionPlan{},TupleCatalog{},false,err};plan,created,err:=orchestrator.Store.Admit(ctx,compiled);if err!=nil{return TransactionPlan{},TupleCatalog{},false,err};return plan,tupleCatalog,created,nil}

func stateForStep(kind StepKind)TransactionState{switch kind{case StepPreflight:return TxPreflighting;case StepStageArtifact,StepInstallPackages,StepEnsureIdentity:return TxStaging;case StepActivateSlot:return TxActivating;case StepArmWatchdog,StepProbeServices:return TxWatching;default:return TxApplying}}

func (orchestrator Orchestrator)executeStep(ctx context.Context,request Request,plan TransactionPlan,catalog TupleCatalog,components map[ComponentID]ComponentDefinition,step PlanStep,installed *InstalledState)(string,error){component:=components[step.ComponentID];encode:=func(value any)(string,error){payload,err:=json.Marshal(value);return string(payload),err};switch step.Kind{
	case StepPreflight:receipt,err:=orchestrator.Host.Preflight(ctx,PreflightRequest{TransactionID:plan.ID,Kind:plan.Kind,Expected:plan.Tuple,MinimumMemoryBytes:catalog.MinimumMemoryBytes,MinimumDiskBytes:catalog.MinimumDiskBytes,RequiredPorts:catalog.RequiredPorts,AllowExisting:plan.Kind!=TransactionInstall});if err!=nil{return "",err};if receipt.Facts.Tuple.Key()!=plan.Tuple.Key()||!validDigest(receipt.Digest){return "",ErrPreflight};return encode(receipt)
	case StepEnsureIdentity:receipts:=[]MutationReceipt{};for _,identity:=range []IdentityID{IdentityPanel,IdentityGateway,IdentityAuthn,IdentitySecrets,IdentityContainers,IdentityWebAdmin}{receipt,err:=orchestrator.Host.EnsureIdentity(ctx,identity);if err!=nil{return "",err};receipts=append(receipts,receipt)};return encode(receipts)
	case StepInstallPackages:receipt,err:=orchestrator.Host.InstallPackages(ctx,plan.Tuple,component.ID,component.Packages);if err!=nil{return "",err};if receipt.ComponentID!=component.ID||!validDigest(receipt.Digest){return "",ErrIntegrity};return encode(receipt)
	case StepStageArtifact:if component.Artifact==nil{return "",ErrInvalid};receipt,err:=orchestrator.Host.StageArtifact(ctx,plan.ID,component.ID,*component.Artifact);if err!=nil{return "",err};if receipt.ArtifactID!=component.Artifact.ID||receipt.SHA256!=component.Artifact.SHA256||receipt.Format!=component.Artifact.Format||receipt.TreeDigest!=component.Artifact.TreeDigest{return "",ErrIntegrity};return encode(receipt)
	case StepDeployArtifact:if component.Artifact==nil{return "",ErrInvalid};var staged ArtifactReceipt;found:=false;for _,prior:=range plan.Steps{if prior.ComponentID==component.ID&&prior.Kind==StepStageArtifact&&prior.State=="committed"{if json.Unmarshal([]byte(prior.Receipt),&staged)==nil{found=true};break}};if !found{return "",ErrConflict};receipt,err:=orchestrator.Host.DeployArtifact(ctx,plan.ID,plan.TargetSlot,component.ID,staged);if err!=nil{return "",err};return encode(receipt)
	case StepInstallEnterpriseLicense:if request.EnterpriseLicense==nil{return "",ErrInvalid};receipt,err:=orchestrator.Host.InstallEnterpriseLicense(ctx,*request.EnterpriseLicense);if err!=nil{return "",err};return encode(receipt)
	case StepWriteFiles:receipt,err:=orchestrator.Host.WriteManagedFiles(ctx,plan.TargetSlot,component.ID,component.Files);if err!=nil{return "",err};return encode(receipt)
	case StepInitializeState:receipts:=[]MutationReceipt{};for _,hook:=range component.StateHooks{if !stateHookApplies(plan.Kind,hook){continue};receipt,err:=orchestrator.State.ApplyStateHook(ctx,hook,plan.TargetSlot,plan.TargetReleaseID,component);if err!=nil{return "",err};receipts=append(receipts,receipt)};return encode(receipts)
	case StepEnableServices:receipts,err:=orchestrator.Host.EnableServices(ctx,plan.Tuple,component.Services);if err!=nil{return "",err};return encode(receipts)
	case StepProbeServices:services:=[]ServiceSpec{};for _,definition:=range catalog.Components{services=append(services,definition.Services...)};receipts,err:=orchestrator.Host.ProbeServices(ctx,plan.Tuple,services);if err!=nil{return "",err};for _,receipt:=range receipts{if !receipt.Healthy{return "",fmt.Errorf("%w: %s",ErrUnhealthy,receipt.Service)}};return encode(receipts)
	case StepArmWatchdog:if installed==nil{return "",ErrConflict};facts,err:=orchestrator.Host.Probe(ctx,plan.Tuple.Edition);if err!=nil{return "",err};ticket:=WatchdogTicket{ID:plan.ID+":watchdog",TransactionID:plan.ID,PreviousSlot:installed.ActiveSlot,PreviousReleaseID:installed.ReleaseID,CandidateSlot:plan.TargetSlot,Deadline:orchestrator.now().Add(orchestrator.watchdogTimeout()),BootID:facts.BootID};ticket,err=orchestrator.Watchdog.Arm(ctx,ticket);if err!=nil{return "",err};if ticket.Signature==""||ticket.PreviousSlot!=installed.ActiveSlot||ticket.PreviousReleaseID!=installed.ReleaseID{return "",ErrIntegrity};return encode(ticket)
	case StepActivateSlot:receipt,err:=orchestrator.Host.ActivateSlot(ctx,plan.TargetSlot,plan.TargetReleaseID);if err!=nil{return "",err};return encode(receipt)
	case StepDisarmWatchdog:ticket,err:=orchestrator.watchdogTicket(plan);if err!=nil{return "",err};slot,release,err:=orchestrator.Host.CurrentSlot(ctx);if err!=nil{return "",err};if slot!=plan.TargetSlot||release!=plan.TargetReleaseID{return "",ErrUnhealthy};if err:=orchestrator.Watchdog.Disarm(ctx,ticket,plan.TargetReleaseID);err!=nil{return "",err};return encode(MutationReceipt{Operation:"disarm_watchdog",Resource:ticket.ID,OutputDigest:step.InputDigest,Receipt:"disarmed",CompletedAt:orchestrator.now()})
	case StepExportState:if installed==nil{return "",ErrNotFound};receipt,err:=orchestrator.Host.Export(ctx,*installed,request.ExportPath);if err!=nil{return "",err};if !validDigest(receipt.Digest)||!validDigest(receipt.ManifestDigest){return "",ErrIntegrity};return encode(receipt)
	case StepDeactivate:if installed==nil{return "",ErrNotFound};receipt,err:=orchestrator.Host.Deactivate(ctx,*installed,true);if err!=nil{return "",err};return encode(receipt)
	case StepTombstone:if installed==nil{return "",ErrNotFound};export,err:=orchestrator.exportReceipt(plan);if err!=nil{return "",err};tombstone:=UninstallTombstone{ID:plan.ID+":tombstone",TransactionID:plan.ID,LastReleaseID:installed.ReleaseID,ExportPath:export.Path,ExportDigest:export.Digest,RetainedPaths:[]ManagedPathID{PathDatabaseConfig,PathDNSConfig,PathFTPConfig,PathPostfixConfig,PathDovecotConfig},PurgeAfter:request.PurgeAfter,CreatedAt:orchestrator.now(),Generation:1};if err:=orchestrator.Store.SaveTombstone(ctx,tombstone);err!=nil{return "",err};return encode(tombstone)
	default:return "",ErrUnsupported}}

func (orchestrator Orchestrator)watchdogTicket(plan TransactionPlan)(WatchdogTicket,error){for _,step:=range plan.Steps{if step.Kind==StepArmWatchdog&&step.State=="committed"{var ticket WatchdogTicket;if json.Unmarshal([]byte(step.Receipt),&ticket)!=nil{return WatchdogTicket{},ErrIntegrity};return ticket,nil}};return WatchdogTicket{},ErrNotFound}
func (orchestrator Orchestrator)exportReceipt(plan TransactionPlan)(ExportReceipt,error){for _,step:=range plan.Steps{if step.Kind==StepExportState&&step.State=="committed"{var receipt ExportReceipt;if json.Unmarshal([]byte(step.Receipt),&receipt)!=nil{return ExportReceipt{},ErrIntegrity};return receipt,nil}};return ExportReceipt{},ErrNotFound}

func (orchestrator Orchestrator)commitInstalled(ctx context.Context,request Request,plan *TransactionPlan,catalog TupleCatalog,installed *InstalledState)error{now:=orchestrator.now();current,currentErr:=orchestrator.Store.LoadInstalled(ctx);switch plan.Kind{case TransactionInstall:if currentErr==nil{if current.ReleaseID!=plan.TargetReleaseID||current.ActiveSlot!=plan.TargetSlot{return ErrConflict}}else if errors.Is(currentErr,ErrNotFound){state:=InstalledState{Tuple:plan.Tuple,CatalogID:plan.CatalogID,CatalogSequence:plan.CatalogSequence,ReleaseID:plan.TargetReleaseID,Version:ReleaseVersion(catalog),ActiveSlot:plan.TargetSlot,ComponentVersions:CatalogComponentVersions(catalog),Generation:1,InstalledAt:now,UpdatedAt:now};if err:=orchestrator.Store.SaveInstalled(ctx,state,0);err!=nil{return err}}else{return currentErr};case TransactionUpgrade:if currentErr!=nil{return currentErr};if current.ReleaseID!=plan.TargetReleaseID||current.ActiveSlot!=plan.TargetSlot{if current.ReleaseID!=plan.FromReleaseID||current.ActiveSlot!=plan.ActiveSlot{return ErrConflict};next:=current;next.CatalogID,next.CatalogSequence,next.PreviousReleaseID,next.PreviousSlot,next.ReleaseID,next.ActiveSlot,next.Version,next.ComponentVersions,next.Generation,next.UpdatedAt=plan.CatalogID,plan.CatalogSequence,current.ReleaseID,current.ActiveSlot,plan.TargetReleaseID,plan.TargetSlot,ReleaseVersion(catalog),CatalogComponentVersions(catalog),current.Generation+1,now;if err:=orchestrator.Store.SaveInstalled(ctx,next,current.Generation);err!=nil{return err}};case TransactionRollback:if currentErr!=nil{return currentErr};if current.ReleaseID!=plan.TargetReleaseID||current.ActiveSlot!=plan.TargetSlot{if current.ReleaseID!=plan.FromReleaseID||current.ActiveSlot!=plan.ActiveSlot{return ErrConflict};next:=current;next.ReleaseID,next.ActiveSlot,next.PreviousReleaseID,next.PreviousSlot,next.Generation,next.UpdatedAt=plan.TargetReleaseID,plan.TargetSlot,current.ReleaseID,current.ActiveSlot,current.Generation+1,now;if err:=orchestrator.Store.SaveInstalled(ctx,next,current.Generation);err!=nil{return err}};case TransactionUninstall:if currentErr==nil{if err:=orchestrator.Store.DeleteInstalled(ctx,current.Generation);err!=nil{return err}}else if !errors.Is(currentErr,ErrNotFound){return currentErr};default:return ErrInvalid};previous:=plan.Generation;plan.State=TxCommitted;plan.Generation++;plan.CompletedAt=now;plan.UpdatedAt=now;return orchestrator.Store.UpdatePlan(ctx,*plan,previous)}

func (orchestrator Orchestrator)rollbackActivation(ctx context.Context,plan TransactionPlan,cause error)(TransactionPlan,error){previous:=plan.Generation;plan.State=TxRollingBack;plan.Failure=cause.Error();plan.Generation++;plan.UpdatedAt=orchestrator.now();_ = orchestrator.Store.UpdatePlan(ctx,plan,previous);rollbackErr:=orchestrator.rollbackStateHooks(ctx,plan);target:=plan.ActiveSlot;release:=plan.FromReleaseID;if plan.Kind==TransactionRollback{installed,err:=orchestrator.Store.LoadInstalled(ctx);if err==nil{target=installed.ActiveSlot;release=installed.ReleaseID}};_,activationErr:=orchestrator.Host.ActivateSlot(ctx,target,release);rollbackErr=errors.Join(rollbackErr,activationErr);if ticket,ticketErr:=orchestrator.watchdogTicket(plan);ticketErr==nil{disarmErr:=orchestrator.Watchdog.Disarm(ctx,ticket,release);if !errors.Is(disarmErr,ErrNotFound){rollbackErr=errors.Join(rollbackErr,disarmErr)}};previous=plan.Generation;plan.Generation++;plan.UpdatedAt=orchestrator.now();if rollbackErr!=nil{plan.State=TxRecoveryRequired;plan.Failure=errors.Join(cause,rollbackErr).Error()}else{plan.State=TxRolledBack;plan.CompletedAt=orchestrator.now()};_ = orchestrator.Store.UpdatePlan(ctx,plan,previous);_ = orchestrator.Host.CleanupTransaction(ctx,plan,false);if rollbackErr!=nil{return plan,errors.Join(ErrRollback,cause,rollbackErr)};return plan,cause}
func (orchestrator Orchestrator)fail(ctx context.Context,plan TransactionPlan,stage string,cause error)(TransactionPlan,error){compensationErr:=orchestrator.rollbackStateHooks(ctx,plan);previous:=plan.Generation;plan.State=TxFailed;plan.Failure=stage+": "+cause.Error();if compensationErr!=nil{plan.State=TxRecoveryRequired;plan.Failure=errors.Join(cause,compensationErr).Error()};plan.Generation++;plan.UpdatedAt=orchestrator.now();plan.CompletedAt=orchestrator.now();_ = orchestrator.Store.UpdatePlan(ctx,plan,previous);_ = orchestrator.Host.CleanupTransaction(ctx,plan,false);return plan,errors.Join(cause,compensationErr)}
func (orchestrator Orchestrator)rollbackStateHooks(ctx context.Context,plan TransactionPlan)error{var result error;for stepIndex:=len(plan.Steps)-1;stepIndex>=0;stepIndex--{step:=plan.Steps[stepIndex];if step.Kind!=StepInitializeState||step.State!="committed"{continue};var receipts []MutationReceipt;if json.Unmarshal([]byte(step.Receipt),&receipts)!=nil{result=errors.Join(result,ErrIntegrity);continue};for receiptIndex:=len(receipts)-1;receiptIndex>=0;receiptIndex--{receipt:=receipts[receiptIndex];hook:=StateHookID(receipt.Resource);if !closedHooks[hook]{result=errors.Join(result,ErrIntegrity);continue};result=errors.Join(result,orchestrator.State.RollbackStateHook(ctx,hook,plan.TargetSlot,plan.TargetReleaseID,receipt))}};return result}
func stateHookApplies(kind TransactionKind,hook StateHookID)bool{if kind==TransactionInstall{return hook!=HookMigrateAuthority};if kind==TransactionUpgrade{return hook!=HookInitializeAuthority};return false}
