//go:build linux

package install

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"syscall"
	"time"
)

type LocalStateInitializer struct{Now func()time.Time}
func (initializer LocalStateInitializer)now()time.Time{if initializer.Now!=nil{return initializer.Now().UTC()};return time.Now().UTC()}
func (initializer LocalStateInitializer)ApplyStateHook(ctx context.Context,hook StateHookID,slot SlotID,releaseID string,component ComponentDefinition)(MutationReceipt,error){verb:=hookVerb(hook);if verb==""||(slot!=SlotA&&slot!=SlotB)||!safeID.MatchString(releaseID)||!closedComponents[component.ID]{return MutationReceipt{},ErrInvalid};binary:=filepath.Join(slotRoot,string(slot),"components",string(ComponentPanel),"cyberpanel");if err:=trustedExecutable(binary);err!=nil{return MutationReceipt{},err};output,err:=runPanelHook(ctx,binary,verb,"--release",releaseID,"--component",string(component.ID));if err!=nil{return MutationReceipt{},err};return mutation("state_hook",string(hook),digestText(output),initializer.now()),nil}
func (initializer LocalStateInitializer)RollbackStateHook(ctx context.Context,hook StateHookID,slot SlotID,releaseID string,receipt MutationReceipt)error{if hookVerb(hook)==""||!validDigest(receipt.OutputDigest){return ErrInvalid};binary:=filepath.Join(slotRoot,string(slot),"components",string(ComponentPanel),"cyberpanel");if err:=trustedExecutable(binary);err!=nil{return err};_,err:=runPanelHook(ctx,binary,"rollback","--hook",string(hook),"--release",releaseID,"--receipt-digest",receipt.OutputDigest);return err}
func hookVerb(hook StateHookID)string{switch hook{case HookInitializeAuthority:return "initialize-authority";case HookMigrateAuthority:return "migrate-authority";case HookBootstrapSecrets:return "bootstrap-secrets";case HookBootstrapAuthn:return "bootstrap-authn";case HookBootstrapDatabase:return "bootstrap-database";case HookBootstrapDNS:return "bootstrap-dns";case HookBootstrapMail:return "bootstrap-mail";case HookReconcileServices:return "reconcile-services"};return ""}
func trustedExecutable(path string)error{info,err:=os.Stat(path);if err!=nil{return err};stat,ok:=info.Sys().(*syscall.Stat_t);if !ok||stat.Uid!=0||!info.Mode().IsRegular()||info.Mode().Perm()&0111==0||info.Mode().Perm()&0022!=0{return ErrIntegrity};return nil}
func runPanelHook(ctx context.Context,binary,verb string,arguments ...string)(string,error){allowed:=map[string]bool{"initialize-authority":true,"migrate-authority":true,"bootstrap-secrets":true,"bootstrap-authn":true,"bootstrap-database":true,"bootstrap-dns":true,"bootstrap-mail":true,"reconcile-services":true,"rollback":true};if !allowed[verb]{return "",ErrUnsupported};args:=append([]string{"installer-hook",verb},arguments...);command:=exec.CommandContext(ctx,binary,args...);command.Env=[]string{"PATH=/usr/sbin:/usr/bin:/sbin:/bin","LANG=C.UTF-8","LC_ALL=C.UTF-8","CYBERPANEL_INSTALLER=1"};output,err:=command.CombinedOutput();if len(output)>1<<20{output=output[:1<<20]};if err!=nil{return string(output),fmt.Errorf("installer hook %s: %w",verb,err)};return string(output),nil}

const(watchdogKeyPath="/etc/cyberpanel/secrets/installer-watchdog.key";watchdogTicketPath=installerRoot+"/watchdog.json";watchdogServicePath="/etc/systemd/system/cyberpanel-install-watchdog.service";watchdogTimerPath="/etc/systemd/system/cyberpanel-install-watchdog.timer")
type SystemdWatchdog struct{Now func()time.Time}
func (watchdog SystemdWatchdog)now()time.Time{if watchdog.Now!=nil{return watchdog.Now().UTC()};return time.Now().UTC()}
func (watchdog SystemdWatchdog)Arm(ctx context.Context,ticket WatchdogTicket)(WatchdogTicket,error){if !safeID.MatchString(ticket.ID)||!safeID.MatchString(ticket.TransactionID)||!safeID.MatchString(ticket.PreviousReleaseID)||(ticket.PreviousSlot!=SlotA&&ticket.PreviousSlot!=SlotB)||(ticket.CandidateSlot!=SlotA&&ticket.CandidateSlot!=SlotB)||ticket.PreviousSlot==ticket.CandidateSlot||ticket.BootID==""||!ticket.Deadline.After(watchdog.now().Add(10*time.Second)){return WatchdogTicket{},ErrInvalid};if err:=trustedExecutable("/usr/local/sbin/panel-install");err!=nil{return WatchdogTicket{},err};key,err:=watchdogKey();if err!=nil{return WatchdogTicket{},err};ticket.Signature="";payload,err:=json.Marshal(ticket);if err!=nil{return WatchdogTicket{},err};mac:=hmac.New(sha256.New,key);mac.Write(payload);ticket.Signature=hex.EncodeToString(mac.Sum(nil));signed,err:=json.Marshal(ticket);if err!=nil{return WatchdogTicket{},err};if err:=atomicWriteManaged(watchdogTicketPath,signed,0600,0,0);err!=nil{return WatchdogTicket{},err};seconds:=int64(time.Until(ticket.Deadline).Seconds());if watchdog.Now!=nil{seconds=int64(ticket.Deadline.Sub(watchdog.now()).Seconds())};if seconds<10{seconds=10};service:="[Unit]\nDescription=CyberPanel installer activation watchdog\nAfter=local-fs.target\n\n[Service]\nType=oneshot\nExecStart=/usr/local/sbin/panel-install watchdog\nNoNewPrivileges=yes\nPrivateTmp=yes\nProtectSystem=strict\nReadWritePaths=/opt/cyberpanel /var/lib/cyberpanel/installer\nProtectHome=yes\nCapabilityBoundingSet=\n";timer:="[Unit]\nDescription=CyberPanel installer activation watchdog timer\n\n[Timer]\nOnActiveSec="+strconv.FormatInt(seconds,10)+"s\nAccuracySec=1s\nUnit=cyberpanel-install-watchdog.service\n\n[Install]\nWantedBy=timers.target\n";if err:=atomicWriteManaged(watchdogServicePath,[]byte(service),0644,0,0);err!=nil{return WatchdogTicket{},err};if err:=atomicWriteManaged(watchdogTimerPath,[]byte(timer),0644,0,0);err!=nil{return WatchdogTicket{},err};if _,err:=runFixed(ctx,"/usr/bin/systemctl","daemon-reload");err!=nil{return WatchdogTicket{},err};if _,err:=runFixed(ctx,"/usr/bin/systemctl","enable","--now","cyberpanel-install-watchdog.timer");err!=nil{return WatchdogTicket{},err};return ticket,nil}
func (watchdog SystemdWatchdog)Disarm(ctx context.Context,ticket WatchdogTicket,releaseID string)error{observed,err:=watchdog.Observe(ctx,ticket.ID);if err!=nil{return err};if observed.TransactionID!=ticket.TransactionID||observed.CandidateSlot!=ticket.CandidateSlot||releaseID==""{return ErrIntegrity};_,_ = runFixed(ctx,"/usr/bin/systemctl","disable","--now","cyberpanel-install-watchdog.timer");return os.Remove(watchdogTicketPath)}
func (watchdog SystemdWatchdog)Observe(ctx context.Context,id string)(WatchdogTicket,error){payload,err:=os.ReadFile(watchdogTicketPath);if os.IsNotExist(err){return WatchdogTicket{},ErrNotFound};if err!=nil{return WatchdogTicket{},err};var ticket WatchdogTicket;if json.Unmarshal(payload,&ticket)!=nil||ticket.ID!=id{return WatchdogTicket{},ErrIntegrity};signature:=ticket.Signature;ticket.Signature="";unsigned,err:=json.Marshal(ticket);if err!=nil{return WatchdogTicket{},err};key,err:=watchdogKey();if err!=nil{return WatchdogTicket{},err};expected,err:=hex.DecodeString(signature);if err!=nil{return WatchdogTicket{},ErrIntegrity};mac:=hmac.New(sha256.New,key);mac.Write(unsigned);if !hmac.Equal(expected,mac.Sum(nil)){return WatchdogTicket{},ErrIntegrity};ticket.Signature=signature;return ticket,nil}
func (watchdog SystemdWatchdog)RunExpired(ctx context.Context,host Host)(bool,error){payload,err:=os.ReadFile(watchdogTicketPath);if os.IsNotExist(err){return false,nil};if err!=nil{return false,err};var reference WatchdogTicket;if json.Unmarshal(payload,&reference)!=nil{return false,ErrIntegrity};ticket,err:=watchdog.Observe(ctx,reference.ID);if err!=nil{return false,err};if watchdog.now().Before(ticket.Deadline){return false,nil};slot,_,err:=host.CurrentSlot(ctx);if err!=nil{return false,err};if slot==ticket.CandidateSlot{if _,err:=host.ActivateSlot(ctx,ticket.PreviousSlot,ticket.PreviousReleaseID);err!=nil{return false,err}};_,_ = runFixed(ctx,"/usr/bin/systemctl","disable","--now","cyberpanel-install-watchdog.timer");if err:=os.Remove(watchdogTicketPath);err!=nil&&!os.IsNotExist(err){return false,err};return true,nil}
func watchdogKey()([]byte,error){if payload,err:=os.ReadFile(watchdogKeyPath);err==nil{info,statErr:=os.Stat(watchdogKeyPath);if statErr!=nil||requireRootOwned(info,0600)!=nil||len(payload)!=32{return nil,ErrIntegrity};return payload,nil}else if !os.IsNotExist(err){return nil,err};if err:=secureMkdir(filepath.Dir(watchdogKeyPath),0700);err!=nil{return nil,err};key:=make([]byte,32);if _,err:=rand.Read(key);err!=nil{return nil,err};file,err:=os.OpenFile(watchdogKeyPath,os.O_CREATE|os.O_EXCL|os.O_WRONLY|syscall.O_NOFOLLOW,0600);if err!=nil{return nil,err};_,writeErr:=file.Write(key);syncErr:=file.Sync();closeErr:=file.Close();if joined:=errors.Join(writeErr,syncErr,closeErr);joined!=nil{return nil,joined};return key,nil}

type FileStore struct{Root string}
func NewFileStore()(FileStore,error){store:=FileStore{Root:installerRoot+"/authority"};for _,path:=range []string{store.Root,filepath.Join(store.Root,"transactions"),filepath.Join(store.Root,"tombstones")}{if err:=secureMkdir(path,0700);err!=nil{return FileStore{},err}};return store,nil}
func (store FileStore)withLock(action func()error)error{lockPath:=filepath.Join(store.Root,"lock");file,err:=os.OpenFile(lockPath,os.O_CREATE|os.O_RDWR|syscall.O_NOFOLLOW,0600);if err!=nil{return err};defer file.Close();if err:=syscall.Flock(int(file.Fd()),syscall.LOCK_EX);err!=nil{return err};defer syscall.Flock(int(file.Fd()),syscall.LOCK_UN);return action()}
func (store FileStore)planPath(id string)string{return filepath.Join(store.Root,"transactions",id+".json")}
func (store FileStore)Admit(ctx context.Context,plan TransactionPlan)(result TransactionPlan,created bool,err error){if err=plan.Validate();err!=nil{return};err=store.withLock(func()error{if payload,readErr:=os.ReadFile(store.planPath(plan.ID));readErr==nil{var existing TransactionPlan;if json.Unmarshal(payload,&existing)!=nil{return ErrIntegrity};if existing.CommandID!=plan.CommandID||existing.RequestDigest!=plan.RequestDigest||existing.CatalogDigest!=plan.CatalogDigest{return ErrConflict};result,created=existing,false;return nil};entries,readErr:=os.ReadDir(filepath.Join(store.Root,"transactions"));if readErr!=nil{return readErr};highestSequence:=uint64(0);for _,entry:=range entries{payload,readErr:=os.ReadFile(filepath.Join(store.Root,"transactions",entry.Name()));if readErr!=nil{return readErr};var existing TransactionPlan;if json.Unmarshal(payload,&existing)!=nil{return ErrIntegrity};if existing.CatalogSequence>highestSequence{highestSequence=existing.CatalogSequence};if existing.CommandID==plan.CommandID{return ErrConflict};switch existing.State{case TxCommitted,TxRolledBack,TxFailed:default:return ErrConflict}};if plan.CatalogSequence<highestSequence{return ErrIntegrity};payload,_:=json.Marshal(plan);if err:=atomicWriteManaged(store.planPath(plan.ID),payload,0600,0,0);err!=nil{return err};result,created=plan,true;return nil});return}
func (store FileStore)LoadPlan(ctx context.Context,id string)(TransactionPlan,error){if !safeID.MatchString(id){return TransactionPlan{},ErrInvalid};payload,err:=os.ReadFile(store.planPath(id));if os.IsNotExist(err){return TransactionPlan{},ErrNotFound};if err!=nil{return TransactionPlan{},err};var plan TransactionPlan;if json.Unmarshal(payload,&plan)!=nil{return TransactionPlan{},ErrIntegrity};return plan,plan.Validate()}
func (store FileStore)UpdatePlan(ctx context.Context,plan TransactionPlan,expected uint64)error{if plan.Generation!=expected+1{return ErrStaleGeneration};return store.withLock(func()error{existing,err:=store.LoadPlan(ctx,plan.ID);if err!=nil{return err};if existing.Generation!=expected{return ErrStaleGeneration};payload,_:=json.Marshal(plan);return atomicWriteManaged(store.planPath(plan.ID),payload,0600,0,0)})}
func (store FileStore)SaveInstalled(ctx context.Context,state InstalledState,expected uint64)error{if state.Generation!=expected+1{return ErrStaleGeneration};if err:=state.Validate();err!=nil{return err};return store.withLock(func()error{path:=filepath.Join(store.Root,"installed.json");if expected==0{if _,err:=os.Stat(path);err==nil{return ErrConflict}}else{payload,err:=os.ReadFile(path);if err!=nil{return err};var existing InstalledState;if json.Unmarshal(payload,&existing)!=nil{return ErrIntegrity};if existing.Generation!=expected{return ErrStaleGeneration}};payload,_:=json.Marshal(state);return atomicWriteManaged(path,payload,0600,0,0)})}
func (store FileStore)LoadInstalled(ctx context.Context)(InstalledState,error){payload,err:=os.ReadFile(filepath.Join(store.Root,"installed.json"));if os.IsNotExist(err){return InstalledState{},ErrNotFound};if err!=nil{return InstalledState{},err};var state InstalledState;if json.Unmarshal(payload,&state)!=nil{return InstalledState{},ErrIntegrity};return state,state.Validate()}
func (store FileStore)DeleteInstalled(ctx context.Context,expected uint64)error{return store.withLock(func()error{state,err:=store.LoadInstalled(ctx);if err!=nil{return err};if state.Generation!=expected{return ErrStaleGeneration};return os.Remove(filepath.Join(store.Root,"installed.json"))})}
func (store FileStore)SaveTombstone(ctx context.Context,tombstone UninstallTombstone)error{if !safeID.MatchString(tombstone.ID)||!validDigest(tombstone.ExportDigest){return ErrInvalid};return store.withLock(func()error{path:=filepath.Join(store.Root,"tombstones",tombstone.ID+".json");if payload,err:=os.ReadFile(path);err==nil{var existing UninstallTombstone;if json.Unmarshal(payload,&existing)!=nil{return ErrIntegrity};if existing.TransactionID==tombstone.TransactionID&&existing.ExportDigest==tombstone.ExportDigest&&existing.PurgeAfter.Equal(tombstone.PurgeAfter){return nil};return ErrConflict};payload,_:=json.Marshal(tombstone);return atomicWriteManaged(path,payload,0600,0,0)})}
func (store FileStore)LoadTombstone(ctx context.Context,id string)(UninstallTombstone,error){if !safeID.MatchString(id){return UninstallTombstone{},ErrInvalid};payload,err:=os.ReadFile(filepath.Join(store.Root,"tombstones",id+".json"));if os.IsNotExist(err){return UninstallTombstone{},ErrNotFound};if err!=nil{return UninstallTombstone{},err};var tombstone UninstallTombstone;if json.Unmarshal(payload,&tombstone)!=nil{return UninstallTombstone{},ErrIntegrity};return tombstone,nil}
