//go:build linux

package certificates

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"net"
	"os"
	"sync"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/secrets"
)

const CertificateBrokerSocketPath="/run/cyberpanel/certificate-runtime.sock"
const certificateBrokerFrameLimit=20<<20
type CertificateBrokerOperation string
const(CertificateBrokerHTTPPresent CertificateBrokerOperation="http01_present";CertificateBrokerHTTPRemove CertificateBrokerOperation="http01_remove";CertificateBrokerStage CertificateBrokerOperation="stage";CertificateBrokerActivate CertificateBrokerOperation="activate";CertificateBrokerProbe CertificateBrokerOperation="probe";CertificateBrokerRestore CertificateBrokerOperation="restore";CertificateBrokerDiscard CertificateBrokerOperation="discard_staged")
// CertificateBrokerRequest deliberately has no private-key field. Stage sends
// the key in a separate bounded binary frame after peer authorization so key
// bytes never enter JSON, command arguments, logs, or the broker journal.
type CertificateBrokerRequest struct{Version uint8 `json:"version"`;RequestID string `json:"request_id"`;Operation CertificateBrokerOperation `json:"operation"`;Deadline time.Time `json:"deadline"`;Challenge *Challenge `json:"challenge,omitempty"`;Consumer string `json:"consumer,omitempty"`;Material *CertificateMaterial `json:"material,omitempty"`;EffectID string `json:"effect_id,omitempty"`;Candidate string `json:"candidate,omitempty"`;Previous string `json:"previous,omitempty"`}
type CertificateBrokerResponse struct{Version uint8 `json:"version"`;RequestID string `json:"request_id"`;Operation CertificateBrokerOperation `json:"operation"`;Success bool `json:"success"`;Failure string `json:"failure,omitempty"`;Previous string `json:"previous,omitempty"`;Candidate string `json:"candidate,omitempty"`;Activation string `json:"activation,omitempty"`;Probe string `json:"probe,omitempty"`;ObservedAt time.Time `json:"observed_at"`}

func(request CertificateBrokerRequest)Validate(now time.Time)error{if request.Version!=1||len(request.RequestID)!=36||request.RequestID[:4]!="crt-"||request.Deadline.Before(now.Add(-time.Second))||request.Deadline.After(now.Add(3*time.Minute)){return ErrInvalidCertificate};if _,err:=hex.DecodeString(request.RequestID[4:]);err!=nil{return ErrInvalidCertificate};switch request.Operation{case CertificateBrokerHTTPPresent,CertificateBrokerHTTPRemove:if request.Challenge==nil||request.Challenge.Kind!=HTTP01||request.Consumer!=""||request.Material!=nil||request.EffectID!=""||request.Candidate!=""||request.Previous!=""{return ErrInvalidCertificate};_,_,err:=validatedHTTP01Challenge(*request.Challenge);return err;case CertificateBrokerStage:if request.Challenge!=nil||request.Consumer==""||request.Material==nil||request.EffectID==""||request.Candidate!=""||request.Previous!=""{return ErrInvalidCertificate};case CertificateBrokerActivate:if request.Challenge!=nil||request.Consumer==""||request.Material!=nil||request.EffectID==""||request.Candidate==""||request.Previous!=""{return ErrInvalidCertificate};case CertificateBrokerProbe:if request.Challenge!=nil||request.Consumer==""||request.Material==nil||request.EffectID!=""||request.Candidate!=""||request.Previous!=""{return ErrInvalidCertificate};case CertificateBrokerRestore:if request.Challenge!=nil||request.Consumer==""||request.Material!=nil||request.EffectID==""||request.Candidate!=""{return ErrInvalidCertificate};case CertificateBrokerDiscard:if request.Challenge!=nil||request.Consumer==""||request.Material==nil||request.EffectID==""||request.Candidate==""||request.Previous!=""{return ErrInvalidCertificate};default:return ErrInvalidCertificate};return nil}
func(response CertificateBrokerResponse)Validate(request CertificateBrokerRequest,now time.Time)error{if response.Version!=1||response.RequestID!=request.RequestID||response.Operation!=request.Operation||response.ObservedAt.IsZero()||response.ObservedAt.After(now.Add(time.Minute))||response.Success==(response.Failure!=""){return ErrInvalidCertificate};if !response.Success{return nil};switch request.Operation{case CertificateBrokerStage:if response.Candidate==""{return ErrInvalidCertificate};case CertificateBrokerActivate:if response.Activation==""{return ErrInvalidCertificate};case CertificateBrokerProbe:if len(response.Probe)!=64{return ErrInvalidCertificate}};return nil}

type TLSPrivateKeyPEMSource interface{TLSPrivateKeyPEM(context.Context,string)([]byte,error)}
type CertificateBrokerTransport interface{RoundTrip(context.Context,CertificateBrokerRequest)(CertificateBrokerResponse,error)}
type protectedCertificateBrokerTransport interface{RoundTripProtected(context.Context,CertificateBrokerRequest,[]byte)(CertificateBrokerResponse,error)}
type CertificateBrokerClient struct{Transport CertificateBrokerTransport;Keys TLSPrivateKeyPEMSource;Now func()time.Time}
func NewLocalCertificateBrokerClient(keys TLSPrivateKeyPEMSource)(*CertificateBrokerClient,error){if keys==nil{return nil,ErrInvalidCertificate};info,err:=os.Lstat(CertificateBrokerSocketPath);if err!=nil||info.Mode()&os.ModeSocket==0||info.Mode().Perm()&0002!=0{return nil,ErrInvalidCertificate};return &CertificateBrokerClient{Transport:CertificateBrokerFramedTransport{Dialer:CertificateBrokerUnixDialer{}},Keys:keys},nil}
func(client *CertificateBrokerClient)now()time.Time{if client.Now!=nil{return client.Now().UTC()};return time.Now().UTC()}
func(client *CertificateBrokerClient)request(ctx context.Context,request CertificateBrokerRequest)(CertificateBrokerResponse,error){return client.requestProtected(ctx,request,nil)}
func(client *CertificateBrokerClient)requestProtected(ctx context.Context,request CertificateBrokerRequest,secret []byte)(CertificateBrokerResponse,error){if client==nil||client.Transport==nil||ctx==nil||(request.Operation==CertificateBrokerStage)!=(len(secret)>0)||len(secret)>1<<20{return CertificateBrokerResponse{},ErrInvalidCertificate};identifier:=make([]byte,16);if _,err:=io.ReadFull(rand.Reader,identifier);err!=nil{return CertificateBrokerResponse{},err};request.Version=1;request.RequestID="crt-"+hex.EncodeToString(identifier);request.Deadline=client.now().Add(90*time.Second);if deadline,ok:=ctx.Deadline();ok&&deadline.Before(request.Deadline){request.Deadline=deadline};if err:=request.Validate(client.now());err!=nil{return CertificateBrokerResponse{},err};var response CertificateBrokerResponse;var err error;if len(secret)>0{transport,ok:=client.Transport.(protectedCertificateBrokerTransport);if !ok{return CertificateBrokerResponse{},ErrInvalidCertificate};response,err=transport.RoundTripProtected(ctx,request,secret)}else{response,err=client.Transport.RoundTrip(ctx,request)};if err!=nil{return CertificateBrokerResponse{},err};if err=response.Validate(request,client.now());err!=nil{return CertificateBrokerResponse{},err};if !response.Success{return response,errors.New("certificate broker: "+response.Failure)};return response,nil}
func(client *CertificateBrokerClient)PresentHTTP01(ctx context.Context,challenge Challenge)error{_,err:=client.request(ctx,CertificateBrokerRequest{Operation:CertificateBrokerHTTPPresent,Challenge:&challenge});return err}
func(client *CertificateBrokerClient)RemoveHTTP01(ctx context.Context,challenge Challenge)error{_,err:=client.request(ctx,CertificateBrokerRequest{Operation:CertificateBrokerHTTPRemove,Challenge:&challenge});return err}
func(client *CertificateBrokerClient)StageCertificate(ctx context.Context,consumer string,material CertificateMaterial,effectID string)(string,string,error){if client.Keys==nil{return "","",ErrInvalidCertificate};key,err:=client.Keys.TLSPrivateKeyPEM(ctx,material.PrivateKeyRef);if err!=nil{return "","",err};defer wipeCertificateBytes(key);response,err:=client.requestProtected(ctx,CertificateBrokerRequest{Operation:CertificateBrokerStage,Consumer:consumer,Material:&material,EffectID:effectID},key);return response.Previous,response.Candidate,err}
func(client *CertificateBrokerClient)ActivateCertificate(ctx context.Context,consumer,candidate,effectID string)(string,error){response,err:=client.request(ctx,CertificateBrokerRequest{Operation:CertificateBrokerActivate,Consumer:consumer,Candidate:candidate,EffectID:effectID});return response.Activation,err}
func(client *CertificateBrokerClient)ProbeCertificate(ctx context.Context,consumer string,material CertificateMaterial)(string,error){response,err:=client.request(ctx,CertificateBrokerRequest{Operation:CertificateBrokerProbe,Consumer:consumer,Material:&material});return response.Probe,err}
func(client *CertificateBrokerClient)RestoreCertificate(ctx context.Context,consumer,previous,effectID string)error{_,err:=client.request(ctx,CertificateBrokerRequest{Operation:CertificateBrokerRestore,Consumer:consumer,Previous:previous,EffectID:effectID});return err}
func(client *CertificateBrokerClient)DiscardStagedCertificate(ctx context.Context,consumer,candidate string,material CertificateMaterial,effectID string)error{_,err:=client.request(ctx,CertificateBrokerRequest{Operation:CertificateBrokerDiscard,Consumer:consumer,Candidate:candidate,Material:&material,EffectID:effectID});return err}

type CertificateBrokerDialer interface{DialContext(context.Context)(net.Conn,error)}
type CertificateBrokerUnixDialer struct{}
func(CertificateBrokerUnixDialer)DialContext(ctx context.Context)(net.Conn,error){return (&net.Dialer{}).DialContext(ctx,"unix",CertificateBrokerSocketPath)}
type CertificateBrokerFramedTransport struct{Dialer CertificateBrokerDialer}
func(transport CertificateBrokerFramedTransport)RoundTrip(ctx context.Context,request CertificateBrokerRequest)(CertificateBrokerResponse,error){return transport.roundTrip(ctx,request,nil)}
func(transport CertificateBrokerFramedTransport)RoundTripProtected(ctx context.Context,request CertificateBrokerRequest,secret []byte)(CertificateBrokerResponse,error){if request.Operation!=CertificateBrokerStage||len(secret)==0||len(secret)>1<<20{return CertificateBrokerResponse{},ErrInvalidCertificate};return transport.roundTrip(ctx,request,secret)}
func(transport CertificateBrokerFramedTransport)roundTrip(ctx context.Context,request CertificateBrokerRequest,secret []byte)(CertificateBrokerResponse,error){connection,err:=transport.Dialer.DialContext(ctx);if err!=nil{return CertificateBrokerResponse{},err};defer connection.Close();stop:=context.AfterFunc(ctx,func(){_=connection.SetDeadline(time.Now())});defer stop();_ = connection.SetDeadline(request.Deadline);if err=writeCertificateBrokerFrame(connection,request);err!=nil{return CertificateBrokerResponse{},err};if len(secret)>0{if err=writeCertificateBrokerSecretFrame(connection,secret);err!=nil{return CertificateBrokerResponse{},err}};var response CertificateBrokerResponse;if err=readCertificateBrokerFrame(connection,&response);err!=nil{return CertificateBrokerResponse{},err};return response,nil}

type CertificateBrokerHost interface{PresentHTTP01(context.Context,Challenge)error;RemoveHTTP01(context.Context,Challenge)error;StageCertificate(context.Context,string,CertificateMaterial,[]byte,string)(string,string,error);ActivateCertificate(context.Context,string,string,string)(string,error);ProbeCertificate(context.Context,string,CertificateMaterial)(string,error);RestoreCertificate(context.Context,string,string,string)error;DiscardStagedCertificate(context.Context,string,string,CertificateMaterial,string)error}
type CertificateBrokerServer struct{Authorizer secrets.MaterialPeerAuthorizer;Host CertificateBrokerHost;MaximumConcurrent uint32;once sync.Once;semaphore chan struct{}}
func(server *CertificateBrokerServer)Serve(listener net.Listener)error{if server==nil||listener==nil||server.Authorizer==nil||server.Host==nil{return ErrInvalidCertificate};server.once.Do(func(){maximum:=server.MaximumConcurrent;if maximum==0{maximum=16};server.semaphore=make(chan struct{},maximum)});for{connection,err:=listener.Accept();if err!=nil{return err};select{case server.semaphore<-struct{}{}:go func(){defer func(){<-server.semaphore;connection.Close()}();server.serve(connection)}();default:connection.Close()}}}
func(server *CertificateBrokerServer)serve(connection net.Conn){if _,err:=server.Authorizer.Authorize(connection);err!=nil{return};now:=time.Now().UTC();_ = connection.SetReadDeadline(now.Add(15*time.Second));var request CertificateBrokerRequest;if readCertificateBrokerFrame(connection,&request)!=nil||request.Validate(now)!=nil{return};_ = connection.SetDeadline(request.Deadline);var privateKey []byte;if request.Operation==CertificateBrokerStage{var err error;privateKey,err=readCertificateBrokerSecretFrame(connection);if err!=nil{return};defer wipeCertificateBytes(privateKey)};ctx,cancel:=context.WithDeadline(context.Background(),request.Deadline);defer cancel();response:=CertificateBrokerResponse{Version:1,RequestID:request.RequestID,Operation:request.Operation,ObservedAt:time.Now().UTC()};var err error;switch request.Operation{case CertificateBrokerHTTPPresent:err=server.Host.PresentHTTP01(ctx,*request.Challenge);case CertificateBrokerHTTPRemove:err=server.Host.RemoveHTTP01(ctx,*request.Challenge);case CertificateBrokerStage:response.Previous,response.Candidate,err=server.Host.StageCertificate(ctx,request.Consumer,*request.Material,privateKey,request.EffectID);case CertificateBrokerActivate:response.Activation,err=server.Host.ActivateCertificate(ctx,request.Consumer,request.Candidate,request.EffectID);case CertificateBrokerProbe:response.Probe,err=server.Host.ProbeCertificate(ctx,request.Consumer,*request.Material);case CertificateBrokerRestore:err=server.Host.RestoreCertificate(ctx,request.Consumer,request.Previous,request.EffectID);case CertificateBrokerDiscard:err=server.Host.DiscardStagedCertificate(ctx,request.Consumer,request.Candidate,*request.Material,request.EffectID)};response.Success=err==nil;if err!=nil{response.Failure=classifyCertificateBrokerError(err)};response.ObservedAt=time.Now().UTC();_ = writeCertificateBrokerFrame(connection,response)}
func classifyCertificateBrokerError(err error)string{switch{case errors.Is(err,ErrInvalidCertificate):return "invalid";case errors.Is(err,os.ErrPermission):return "forbidden";case errors.Is(err,os.ErrNotExist):return "not_found";default:return "failed"}}

func ListenCertificateBroker(ownerUID,groupGID int)(*net.UnixListener,error){if ownerUID<0||groupGID<=0{return nil,ErrInvalidCertificate};directory:="/run/cyberpanel";if err:=os.Mkdir(directory,0750);err!=nil&&!errors.Is(err,os.ErrExist){return nil,err};info,err:=os.Lstat(directory);if err!=nil||!info.IsDir()||info.Mode()&os.ModeSymlink!=0||info.Mode().Perm()&0002!=0{return nil,ErrInvalidCertificate};if info,err=os.Lstat(CertificateBrokerSocketPath);err==nil{if info.Mode()&os.ModeSocket==0{return nil,ErrInvalidCertificate};if err=os.Remove(CertificateBrokerSocketPath);err!=nil{return nil,err}}else if !errors.Is(err,os.ErrNotExist){return nil,err};listener,err:=net.ListenUnix("unix",&net.UnixAddr{Name:CertificateBrokerSocketPath,Net:"unix"});if err!=nil{return nil,err};if err=os.Chown(CertificateBrokerSocketPath,ownerUID,groupGID);err==nil{err=os.Chmod(CertificateBrokerSocketPath,0660)};if err!=nil{listener.Close();return nil,err};return listener,nil}
func writeCertificateBrokerFrame(writer io.Writer,value any)error{content,err:=json.Marshal(value);if err!=nil||len(content)==0||len(content)>certificateBrokerFrameLimit{return ErrInvalidCertificate};var header[4]byte;binary.BigEndian.PutUint32(header[:],uint32(len(content)));if err=writeCertificateBrokerBytes(writer,header[:]);err!=nil{return err};return writeCertificateBrokerBytes(writer,content)}
func writeCertificateBrokerBytes(writer io.Writer,content []byte)error{for len(content)>0{written,err:=writer.Write(content);if err!=nil{return err};if written<=0||written>len(content){return io.ErrShortWrite};content=content[written:]};return nil}
func readCertificateBrokerFrame(reader io.Reader,target any)error{var header[4]byte;if _,err:=io.ReadFull(reader,header[:]);err!=nil{return err};size:=binary.BigEndian.Uint32(header[:]);if size==0||size>certificateBrokerFrameLimit{return ErrInvalidCertificate};content:=make([]byte,size);defer wipeCertificateBytes(content);if _,err:=io.ReadFull(reader,content);err!=nil{return err};decoder:=json.NewDecoder(bytes.NewReader(content));decoder.DisallowUnknownFields();if decoder.Decode(target)!=nil||decoder.Decode(&struct{}{})!=io.EOF{return ErrInvalidCertificate};return nil}
func writeCertificateBrokerSecretFrame(writer io.Writer,content []byte)error{if len(content)==0||len(content)>1<<20{return ErrInvalidCertificate};var header[4]byte;binary.BigEndian.PutUint32(header[:],uint32(len(content)));if err:=writeCertificateBrokerBytes(writer,header[:]);err!=nil{return err};return writeCertificateBrokerBytes(writer,content)}
func readCertificateBrokerSecretFrame(reader io.Reader)([]byte,error){var header[4]byte;if _,err:=io.ReadFull(reader,header[:]);err!=nil{return nil,err};size:=binary.BigEndian.Uint32(header[:]);if size==0||size>1<<20{return nil,ErrInvalidCertificate};content:=make([]byte,size);if _,err:=io.ReadFull(reader,content);err!=nil{wipeCertificateBytes(content);return nil,err};return content,nil}

var _ HTTP01Presenter=(*CertificateBrokerClient)(nil)
var _ DeploymentTarget=(*CertificateBrokerClient)(nil)
