//go:build linux

package certificates

import (
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"crypto/tls"
	"encoding/hex"
	"errors"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
)

const defaultHTTP01Root="/var/lib/cyberpanel/acme/http-01"
const defaultCertificateRoot="/var/lib/cyberpanel/certificates"

type CertificateCommandRunner interface{Run(context.Context,string,...string)error}
type FixedCertificateCommandRunner struct{}
func(FixedCertificateCommandRunner)Run(ctx context.Context,program string,arguments ...string)error{allowed:=false;switch program{case "/usr/local/lsws/bin/lswsctrl":allowed=len(arguments)==1&&(arguments[0]=="reload"||arguments[0]=="status");case "/usr/bin/systemctl":if len(arguments)==2{verb,unit:=arguments[0],arguments[1];allowed=(verb=="reload"||verb=="restart"||verb=="is-active")&&(unit=="panel-gateway.service"||unit=="postfix.service"||unit=="dovecot.service")}};if !allowed{return ErrInvalidCertificate};return exec.CommandContext(ctx,program,arguments...).Run()}

type LinuxCertificateHost struct{HTTPRoot string;CertificateRoot string;Runner CertificateCommandRunner;PanelGID int}
func NewLinuxCertificateHost()(*LinuxCertificateHost,error){if os.Geteuid()!=0{return nil,ErrInvalidCertificate};group,err:=user.LookupGroup("cyberpanel");if err!=nil{return nil,err};gid,err:=strconv.Atoi(group.Gid);if err!=nil||gid<=0{return nil,ErrInvalidCertificate};return &LinuxCertificateHost{HTTPRoot:defaultHTTP01Root,CertificateRoot:defaultCertificateRoot,Runner:FixedCertificateCommandRunner{},PanelGID:gid},nil}
func(host *LinuxCertificateHost)roots()(string,string,error){if host==nil||host.Runner==nil{return "","",ErrInvalidCertificate};httpRoot:=host.HTTPRoot;if httpRoot==""{httpRoot=defaultHTTP01Root};certificateRoot:=host.CertificateRoot;if certificateRoot==""{certificateRoot=defaultCertificateRoot};if !filepath.IsAbs(httpRoot)||!filepath.IsAbs(certificateRoot)||filepath.Clean(httpRoot)!=httpRoot||filepath.Clean(certificateRoot)!=certificateRoot{return "","",ErrInvalidCertificate};return httpRoot,certificateRoot,nil}

func(host *LinuxCertificateHost)PresentHTTP01(ctx context.Context,challenge Challenge)error{root,_,err:=host.roots();if err!=nil{return err};token,authorization,err:=validatedHTTP01Challenge(challenge);if err!=nil{return err};if err=secureRootDirectory(root,0755);err!=nil{return err};select{case<-ctx.Done():return ctx.Err();default:};return atomicRootFile(filepath.Join(root,token),[]byte(authorization),0644,true)}
func(host *LinuxCertificateHost)RemoveHTTP01(ctx context.Context,challenge Challenge)error{root,_,err:=host.roots();if err!=nil{return err};token,authorization,err:=validatedHTTP01Challenge(challenge);if err!=nil{return err};path:=filepath.Join(root,token);info,err:=os.Lstat(path);if errors.Is(err,os.ErrNotExist){return nil};if err!=nil||!safeRootFile(info,0644){return ErrInvalidCertificate};content,err:=os.ReadFile(path);if err!=nil{return err};if !bytes.Equal(content,[]byte(authorization)){return ErrCertificateConflict};select{case<-ctx.Done():return ctx.Err();default:};return os.Remove(path)}

func(host *LinuxCertificateHost)StageCertificate(ctx context.Context,consumer string,material CertificateMaterial,privateKeyPEM []byte,effectID string)(string,string,error){
	_,root,err:=host.roots();if err!=nil{return "","",err};kind,identifier,err:=validCertificateConsumer(consumer);if err!=nil||!validCertificateEffect(effectID){return "","",ErrInvalidCertificate};if len(privateKeyPEM)==0||len(privateKeyPEM)>1<<20{return "","",ErrInvalidCertificate};if _,err=tls.X509KeyPair(material.FullChainPEM,privateKeyPEM);err!=nil{return "","",ErrInvalidCertificate};parsed,err:=certificateMaterialFromPEM(material.FullChainPEM);if err!=nil||parsed.ID!=material.ID||parsed.FingerprintSHA256!=material.FingerprintSHA256||!bytes.Equal(parsed.LeafPEM,material.LeafPEM)||!bytes.Equal(parsed.ChainPEM,material.ChainPEM){return "","",ErrInvalidCertificate}
	generations:=filepath.Join(root,"generations");consumers:=filepath.Join(root,"consumers",kind,identifier);if err=secureRootDirectory(generations,0711);err!=nil{return "","",err};if err=secureRootDirectory(consumers,0750);err!=nil{return "","",err};candidateParent:=filepath.Join(generations,kind,identifier);if err=secureRootDirectory(candidateParent,0711);err!=nil{return "","",err};candidate:=filepath.Join(candidateParent,string(material.ID)+"-"+material.FingerprintSHA256);if err=os.Mkdir(candidate,0750);err!=nil&&!errors.Is(err,os.ErrExist){return "","",err};info,err:=os.Lstat(candidate);if err!=nil||!safeRootDirectory(info,0750){return "","",ErrInvalidCertificate};gid:=0;if kind=="panel"{gid=host.PanelGID;if gid<=0{return "","",ErrInvalidCertificate}};if err=os.Chown(candidate,0,gid);err!=nil{return "","",err};for _,file:=range []struct{name string;content []byte}{{"certificate.pem",material.LeafPEM},{"chain.pem",material.ChainPEM},{"fullchain.pem",material.FullChainPEM},{"private.key",privateKeyPEM}}{path:=filepath.Join(candidate,file.name);if err=atomicRootFile(path,file.content,0440,true);err!=nil{return "","",err};if err=os.Chown(path,0,gid);err!=nil{return "","",err}};if err=syncDirectory(candidate);err!=nil{return "","",err};previous:="";current:=filepath.Join(consumers,"current");if target,readErr:=os.Readlink(current);readErr==nil{absolute:=target;if !filepath.IsAbs(absolute){absolute=filepath.Join(consumers,target)};absolute=filepath.Clean(absolute);if !pathWithin(generations,absolute){return "","",ErrInvalidCertificate};previous=absolute}else if !errors.Is(readErr,os.ErrNotExist){return "","",readErr};select{case<-ctx.Done():return "","",ctx.Err();default:};return previous,candidate,nil
}

func(host *LinuxCertificateHost)ActivateCertificate(ctx context.Context,consumer,candidate,effectID string)(string,error){_,root,err:=host.roots();if err!=nil{return "",err};kind,identifier,err:=validCertificateConsumer(consumer);if err!=nil||!validCertificateEffect(effectID){return "",ErrInvalidCertificate};generations:=filepath.Join(root,"generations");candidate=filepath.Clean(candidate);if !pathWithin(filepath.Join(generations,kind,identifier),candidate){return "",ErrInvalidCertificate};info,err:=os.Lstat(candidate);if err!=nil||!safeRootDirectory(info,0750){return "",ErrInvalidCertificate};consumerRoot:=filepath.Join(root,"consumers",kind,identifier);if err=secureRootDirectory(consumerRoot,0750);err!=nil{return "",err};if err=atomicRootSymlink(filepath.Join(consumerRoot,"current"),candidate,effectID);err!=nil{return "",err};if err=host.reload(ctx,kind);err!=nil{return "",err};return filepath.Join(consumerRoot,"current"),nil}
func(host *LinuxCertificateHost)ProbeCertificate(ctx context.Context,consumer string,material CertificateMaterial)(string,error){_,root,err:=host.roots();if err!=nil{return "",err};kind,identifier,err:=validCertificateConsumer(consumer);if err!=nil{return "",err};current:=filepath.Join(root,"consumers",kind,identifier,"current");target,err:=os.Readlink(current);if err!=nil{return "",err};if !filepath.IsAbs(target){target=filepath.Join(filepath.Dir(current),target)};target=filepath.Clean(target);if !pathWithin(filepath.Join(root,"generations",kind,identifier),target){return "",ErrInvalidCertificate};content,err:=os.ReadFile(filepath.Join(target,"certificate.pem"));if err!=nil{return "",err};parsed,err:=certificateMaterialFromPEM(content);if err!=nil||parsed.FingerprintSHA256!=material.FingerprintSHA256{return "",ErrInvalidCertificate};if err=host.probe(ctx,kind);err!=nil{return "",err};return parsed.FingerprintSHA256,nil}
func(host *LinuxCertificateHost)RestoreCertificate(ctx context.Context,consumer,previous,effectID string)error{_,root,err:=host.roots();if err!=nil{return err};kind,identifier,err:=validCertificateConsumer(consumer);if err!=nil||!validCertificateEffect(effectID){return ErrInvalidCertificate};consumerRoot:=filepath.Join(root,"consumers",kind,identifier);current:=filepath.Join(consumerRoot,"current");if previous==""{info,lstatErr:=os.Lstat(current);if errors.Is(lstatErr,os.ErrNotExist){return nil};if lstatErr!=nil||info.Mode()&os.ModeSymlink==0{return ErrInvalidCertificate};if err=os.Remove(current);err!=nil{return err};if err=syncDirectory(consumerRoot);err!=nil{return err};return host.reload(ctx,kind)};previous=filepath.Clean(previous);if !pathWithin(filepath.Join(root,"generations",kind,identifier),previous){return ErrInvalidCertificate};if info,statErr:=os.Lstat(previous);statErr!=nil||!safeRootDirectory(info,0750){return ErrInvalidCertificate};if err=atomicRootSymlink(current,previous,effectID+"-restore");err!=nil{return err};return host.reload(ctx,kind)}

func(host *LinuxCertificateHost)reload(ctx context.Context,kind string)error{switch kind{case "webengine":return host.Runner.Run(ctx,"/usr/local/lsws/bin/lswsctrl","reload");case "panel":return host.Runner.Run(ctx,"/usr/bin/systemctl","restart","panel-gateway.service");case "mail":if err:=host.Runner.Run(ctx,"/usr/bin/systemctl","reload","postfix.service");err!=nil{return err};return host.Runner.Run(ctx,"/usr/bin/systemctl","reload","dovecot.service")};return ErrInvalidCertificate}
func(host *LinuxCertificateHost)probe(ctx context.Context,kind string)error{switch kind{case "webengine":return host.Runner.Run(ctx,"/usr/local/lsws/bin/lswsctrl","status");case "panel":return host.Runner.Run(ctx,"/usr/bin/systemctl","is-active","panel-gateway.service");case "mail":if err:=host.Runner.Run(ctx,"/usr/bin/systemctl","is-active","postfix.service");err!=nil{return err};return host.Runner.Run(ctx,"/usr/bin/systemctl","is-active","dovecot.service")};return ErrInvalidCertificate}

func validatedHTTP01Challenge(challenge Challenge)(string,string,error){if challenge.Kind!=HTTP01||challenge.ID==""||challenge.Token==""||len(challenge.Token)>128||challenge.KeyAuthorization==""||len(challenge.KeyAuthorization)>512||!strings.HasPrefix(challenge.KeyAuthorization,challenge.Token+"."){return "","",ErrInvalidCertificate};for _,value:=range []string{challenge.Token,challenge.KeyAuthorization}{if strings.ContainsAny(value,"/\\\x00\r\n") {return "","",ErrInvalidCertificate};for index:=range value{character:=value[index];if !(character>='a'&&character<='z'||character>='A'&&character<='Z'||character>='0'&&character<='9'||character=='-'||character=='_'||character=='.'){return "","",ErrInvalidCertificate}}};return challenge.Token,challenge.KeyAuthorization,nil}
func validCertificateConsumer(value string)(string,string,error){parts:=strings.Split(value,"/");if len(parts)!=2||(parts[0]!="webengine"&&parts[0]!="panel"&&parts[0]!="mail")||!validCertificatePathComponent(parts[1]){return "","",ErrInvalidCertificate};return parts[0],parts[1],nil}
func validCertificatePathComponent(value string)bool{if len(value)<1||len(value)>96||value=="."||value==".."{return false};for index:=range value{character:=value[index];if !(character>='a'&&character<='z'||character>='A'&&character<='Z'||character>='0'&&character<='9'||character=='-'||character=='_'){return false}};return true}
func validCertificateEffect(value string)bool{return validCertificatePathComponent(value)&&len(value)>=8}
func pathWithin(root,target string)bool{relative,err:=filepath.Rel(filepath.Clean(root),filepath.Clean(target));return err==nil&&relative!="."&&!strings.HasPrefix(relative,".."+string(os.PathSeparator))&&relative!=".."&&!filepath.IsAbs(relative)}

func secureRootDirectory(path string,mode os.FileMode)error{path=filepath.Clean(path);if !filepath.IsAbs(path)||path=="/"{return ErrInvalidCertificate};current:=string(os.PathSeparator);for _,component:=range strings.Split(strings.TrimPrefix(path,string(os.PathSeparator)),string(os.PathSeparator)){current=filepath.Join(current,component);info,err:=os.Lstat(current);if errors.Is(err,os.ErrNotExist){if err=os.Mkdir(current,mode);err!=nil{return err};info,err=os.Lstat(current)};if err!=nil||!safeRootOwnedDirectory(info){return ErrInvalidCertificate}};if err:=os.Chmod(path,mode);err!=nil{return err};return nil}
func safeRootOwnedDirectory(info os.FileInfo)bool{if info==nil||!info.IsDir()||info.Mode()&os.ModeSymlink!=0||info.Mode().Perm()&0022!=0{return false};stat,ok:=info.Sys().(*syscall.Stat_t);return ok&&stat.Uid==0}
func safeRootDirectory(info os.FileInfo,mode os.FileMode)bool{return safeRootOwnedDirectory(info)&&info.Mode().Perm()==mode.Perm()}
func safeRootFile(info os.FileInfo,mode os.FileMode)bool{if info==nil||!info.Mode().IsRegular()||info.Mode()&os.ModeSymlink!=0||info.Mode().Perm()!=mode.Perm(){return false};stat,ok:=info.Sys().(*syscall.Stat_t);return ok&&stat.Uid==0&&stat.Nlink==1}
func atomicRootFile(path string,content []byte,mode os.FileMode,immutable bool)error{directory:=filepath.Dir(path);if info,err:=os.Lstat(path);err==nil{if !safeRootFile(info,mode){return ErrInvalidCertificate};existing,readErr:=os.ReadFile(path);if readErr!=nil{return readErr};if bytes.Equal(existing,content){return nil};if immutable{return ErrCertificateConflict}}else if !errors.Is(err,os.ErrNotExist){return err};random:=make([]byte,12);if _,err:=rand.Read(random);err!=nil{return err};temporary:=filepath.Join(directory,".certificate-"+hex.EncodeToString(random));file,err:=os.OpenFile(temporary,os.O_WRONLY|os.O_CREATE|os.O_EXCL|syscall.O_NOFOLLOW,mode);if err!=nil{return err};cleanup:=true;defer func(){file.Close();if cleanup{os.Remove(temporary)}}();if _,err=file.Write(content);err!=nil{return err};if err=file.Sync();err!=nil{return err};if err=file.Close();err!=nil{return err};if err=os.Rename(temporary,path);err!=nil{return err};cleanup=false;return syncDirectory(directory)}
func atomicRootSymlink(path,target,effectID string)error{directory:=filepath.Dir(path);sum:=sha256.Sum256([]byte(effectID+"\x00"+target));temporary:=filepath.Join(directory,".current-"+hex.EncodeToString(sum[:])[:24]);_ = os.Remove(temporary);if err:=os.Symlink(target,temporary);err!=nil{return err};if err:=os.Rename(temporary,path);err!=nil{os.Remove(temporary);return err};return syncDirectory(directory)}
func syncDirectory(path string)error{directory,err:=os.Open(path);if err!=nil{return err};defer directory.Close();return directory.Sync()}

var _ CertificateBrokerHost=(*LinuxCertificateHost)(nil)
