package federation

import(
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"regexp"
	"sort"
	"strings"
	"time"
)
var(ErrInvalid=errors.New("federation: invalid value");ErrForbidden=errors.New("federation: forbidden");ErrExpired=errors.New("federation: expired");ErrStale=errors.New("federation: stale authority or generation");ErrReplay=errors.New("federation: replay");ErrConflict=errors.New("federation: conflict");ErrOffline=errors.New("federation: offline");ErrAmbiguous=errors.New("federation: ambiguous outcome"))
var idPattern=regexp.MustCompile(`^[a-z][a-z0-9_-]{2,95}$`)
type ID string
func NewID(v string)(ID,error){v=strings.TrimSpace(v);if !idPattern.MatchString(v){return "",ErrInvalid};return ID(v),nil}
func(id ID)Valid()bool{return idPattern.MatchString(string(id))}
func(id ID)String()string{return string(id)}
type Risk string
const(RiskLow Risk="low";RiskModerate Risk="moderate";RiskHigh Risk="high";RiskCritical Risk="critical")
type Origin string
const(OriginLocalUI Origin="local_ui";OriginLocalAPI Origin="local_api";OriginLocalCLI Origin="local_cli";OriginScheduler Origin="scheduler";OriginFederation Origin="federation")
type Capability struct{CommandType,SchemaHash string;Version uint32;RemoteEligible bool;MinimumRisk Risk;Resources []string}
type CapabilitySet struct{NodeID ID;ProtocolVersion uint32;ProductVersion,BuildDigest,OS,Architecture,WebEngineEdition,WebEngineVersion string;AuthorityEpoch uint64;Capabilities []Capability;GeneratedAt time.Time;Digest string}
func(c CapabilitySet)CanonicalDigest()string{copy:=c;copy.Digest="";copy.Capabilities=append([]Capability(nil),c.Capabilities...);sort.Slice(copy.Capabilities,func(i,j int)bool{return copy.Capabilities[i].CommandType<copy.Capabilities[j].CommandType});raw,_:=json.Marshal(copy);sum:=sha256.Sum256(raw);return hex.EncodeToString(sum[:])}
type ResourceSelector struct{Kind,TenantID,ResourceID,LabelSelector string;Operations []string}
func validateResourceSelector(selector ResourceSelector)error{if selector.Kind==""||len(selector.Kind)>128||selector.TenantID==""||len(selector.TenantID)>256||selector.ResourceID==""||len(selector.ResourceID)>256||selector.LabelSelector!=""||len(selector.Operations)==0||len(selector.Operations)>128||strings.ContainsAny(selector.Kind+selector.TenantID+selector.ResourceID,"\x00\r\n"){return ErrInvalid};seen:=make(map[string]struct{},len(selector.Operations));for _,operation:=range selector.Operations{if operation==""||len(operation)>256||strings.ContainsAny(operation,"\x00\r\n") {return ErrInvalid};if _,duplicate:=seen[operation];duplicate{return ErrInvalid};seen[operation]=struct{}{}};return nil}
const(SigningAlgorithmEd25519="ed25519";CentralOperatorIssuer="cyberpanel-central-operator-mtls-v1")
type SigningKeyTrust struct{ID,Algorithm string;Epoch uint64;PublicKey []byte;ValidFrom,ValidUntil,OverlapUntil time.Time;RevocationEpoch uint64;RevokedAt *time.Time}
func(k SigningKeyTrust)Validate()error{if !ID(k.ID).Valid()||k.Algorithm!=SigningAlgorithmEd25519||k.Epoch==0||len(k.PublicKey)!=ed25519.PublicKeySize||k.ValidFrom.IsZero()||!k.ValidUntil.After(k.ValidFrom)||k.OverlapUntil.Before(k.ValidFrom)||k.OverlapUntil.After(k.ValidUntil){return ErrInvalid};return nil}
func(k SigningKeyTrust)Allows(intent Intent,now time.Time,currentEpoch uint64)bool{if k.Validate()!=nil||k.ID!=intent.SigningKeyID||k.Algorithm!=intent.SigningAlgorithm||k.Epoch!=intent.SigningKeyEpoch||intent.SigningKeyEpoch>currentEpoch||now.Before(k.ValidFrom)||!now.Before(k.ValidUntil)||intent.IssuedAt.Before(k.ValidFrom)||!intent.IssuedAt.Before(k.ValidUntil)||k.RevokedAt!=nil||k.RevocationEpoch!=0&&intent.AuthorityEpoch>=k.RevocationEpoch{return false};return k.Epoch==currentEpoch||now.Before(k.OverlapUntil)}
type MutationGrant struct{ID,PeerID,NodeID ID;AuthorityEpoch uint64;Selectors []ResourceSelector;MaximumRisk Risk;SigningKeys []SigningKeyTrust;PrincipalBindings []FederatedPrincipalBinding;IssuedAt,ExpiresAt time.Time;RevokedAt *time.Time;Digest,SignatureKeyID,SignatureAlgorithm string;SignatureKeyEpoch uint64;Signature []byte}
func(g MutationGrant)Validate(now time.Time)error{if !g.ID.Valid()||!g.PeerID.Valid()||!g.NodeID.Valid()||g.AuthorityEpoch==0||len(g.Selectors)==0||len(g.Selectors)>256||len(g.SigningKeys)==0||len(g.SigningKeys)>16||len(g.PrincipalBindings)==0||len(g.PrincipalBindings)>256||g.IssuedAt.IsZero()||!g.ExpiresAt.After(g.IssuedAt)||!now.Before(g.ExpiresAt)||len(g.Digest)!=64||g.SignatureKeyID==""||g.SignatureAlgorithm!=SigningAlgorithmEd25519||g.SignatureKeyEpoch==0||len(g.Signature)!=ed25519.SignatureSize{return ErrInvalid};if g.RevokedAt!=nil{return ErrForbidden};for _,selector:=range g.Selectors{if validateResourceSelector(selector)!=nil{return ErrInvalid}};keys:=make(map[string]struct{},len(g.SigningKeys));for _,key:=range g.SigningKeys{if key.Validate()!=nil{return ErrInvalid};if _,duplicate:=keys[key.ID];duplicate{return ErrInvalid};keys[key.ID]=struct{}{}};bindings:=make(map[string]struct{},len(g.PrincipalBindings));for _,binding:=range g.PrincipalBindings{if binding.Validate()!=nil||binding.PeerID!=g.PeerID{return ErrInvalid};identity:=binding.PeerID.String()+"\x00"+binding.Issuer+"\x00"+binding.Subject;if _,duplicate:=bindings[identity];duplicate{return ErrInvalid};bindings[identity]=struct{}{}};return nil}
type Actor struct{PrincipalID,TenantID,CredentialID,SessionID string;AuthzEpoch uint64;Assurance,Display string}
type CentralActorAssertion struct{Issuer,Subject,Audience string;AuthenticatedAt time.Time;AuthenticationMethods []string;Nonce string;ExpiresAt time.Time;AuthorizationEpoch uint64}
func(a CentralActorAssertion)Validate(now time.Time)error{if a.Issuer==""||a.Subject==""||a.Audience==""||a.AuthenticatedAt.IsZero()||a.AuthenticatedAt.After(now.Add(time.Minute))||len(a.AuthenticationMethods)==0||a.Nonce==""||!a.ExpiresAt.After(a.AuthenticatedAt)||!now.Before(a.ExpiresAt)||a.AuthorizationEpoch==0{return ErrInvalid};return nil}
type FederatedPrincipalBinding struct{ID,PeerID ID;Issuer,Subject,LocalPrincipalID,LocalTenantID,RoleCeiling string;Selectors []ResourceSelector;RequiredAuthenticationMethods []string;MaximumAuthenticationAge time.Duration;MaximumRisk Risk;ValidFrom,ExpiresAt time.Time;AuthorizationEpoch uint64;RevocationEpoch uint64;RevokedAt *time.Time}
func(b FederatedPrincipalBinding)Validate()error{role:=strings.ToLower(strings.ReplaceAll(b.RoleCeiling,"-","_"));if !b.ID.Valid()||!b.PeerID.Valid()||b.Issuer==""||len(b.Issuer)>256||b.Subject==""||len(b.Subject)>256||b.LocalPrincipalID==""||len(b.LocalPrincipalID)>256||b.LocalTenantID==""||len(b.LocalTenantID)>256||role==""||len(role)>128||role=="owner"||role=="instance_owner"||len(b.Selectors)==0||len(b.Selectors)>256||len(b.RequiredAuthenticationMethods)==0||len(b.RequiredAuthenticationMethods)>16||b.MaximumAuthenticationAge<=0||!riskAllows(RiskCritical,b.MaximumRisk)||b.ValidFrom.IsZero()||!b.ExpiresAt.After(b.ValidFrom)||b.AuthorizationEpoch==0||strings.ContainsAny(b.Issuer+b.Subject+b.LocalPrincipalID+b.LocalTenantID+role,"\x00\r\n"){return ErrInvalid};for _,selector:=range b.Selectors{if validateResourceSelector(selector)!=nil{return ErrInvalid}};methods:=make(map[string]struct{},len(b.RequiredAuthenticationMethods));for _,method:=range b.RequiredAuthenticationMethods{if method==""||len(method)>128||strings.ContainsAny(method,"\x00\r\n"){return ErrInvalid};if _,duplicate:=methods[method];duplicate{return ErrInvalid};methods[method]=struct{}{}};return nil}
func(b FederatedPrincipalBinding)Allows(assertion CentralActorAssertion,intent Intent,now time.Time)bool{if b.Validate()!=nil||b.PeerID!=intent.PeerID||b.Issuer!=assertion.Issuer||b.Subject!=assertion.Subject||assertion.Audience!=intent.NodeID.String()||assertion.AuthorizationEpoch!=b.AuthorizationEpoch||now.Before(b.ValidFrom)||!now.Before(b.ExpiresAt)||b.RevokedAt!=nil||b.RevocationEpoch!=0&&assertion.AuthorizationEpoch>=b.RevocationEpoch||assertion.AuthenticatedAt.Before(b.ValidFrom)||now.Sub(assertion.AuthenticatedAt)>b.MaximumAuthenticationAge||!riskAllows(b.MaximumRisk,intent.Risk){return false};required:=make(map[string]struct{},len(b.RequiredAuthenticationMethods));for _,method:=range b.RequiredAuthenticationMethods{required[method]=struct{}{}};for _,method:=range assertion.AuthenticationMethods{delete(required,method)};if len(required)!=0{return false};for _,selector:=range b.Selectors{if selectorAllows(selector,intent){return true}};return false}
type Approval struct{AuthorizationID,PlanDigest,DisplayDigest,PolicyVersion,SigningKeyID,SigningAlgorithm string;SigningKeyEpoch,AuthorizationEpoch uint64;IssuedAt,ExpiresAt time.Time;Signature []byte}
func(a Approval)Validate(now time.Time)error{if a.AuthorizationID==""||len(a.PlanDigest)!=64||len(a.DisplayDigest)!=64||a.PolicyVersion==""||a.SigningKeyID==""||a.SigningAlgorithm!=SigningAlgorithmEd25519||a.SigningKeyEpoch==0||a.AuthorizationEpoch==0||a.IssuedAt.IsZero()||!a.ExpiresAt.After(a.IssuedAt)||!now.Before(a.ExpiresAt)||len(a.Signature)!=ed25519.SignatureSize{return ErrInvalid};return nil}
type Intent struct{ID,PeerID,NodeID,GrantID ID;AuthorityEpoch,CapabilityEpoch uint64;ProtocolVersion uint32;CommandType,SchemaHash,PayloadTypeURL string;Payload json.RawMessage;PayloadDigest string;TenantID,ResourceKind,ResourceID,TargetScope string;ExpectedGeneration uint64;IdempotencyKey,EffectID string;Risk Risk;ActorAssertion CentralActorAssertion;Approvals []Approval;ActorChain []Actor;Approval *Approval;IssuedAt,ExpiresAt time.Time;SigningKeyID,SigningAlgorithm string;SigningKeyEpoch uint64;Signature []byte}
func(i Intent)Validate(now time.Time)error{if !i.ID.Valid()||!i.PeerID.Valid()||!i.NodeID.Valid()||!i.GrantID.Valid()||i.AuthorityEpoch==0||i.CapabilityEpoch==0||i.ProtocolVersion==0||i.CommandType==""||len(i.SchemaHash)!=64||i.PayloadTypeURL==""||len(i.Payload)==0||len(i.Payload)>4<<20||len(i.PayloadDigest)!=64||i.TenantID==""||i.ResourceKind==""||i.ResourceID==""||i.TargetScope==""||i.IdempotencyKey==""||i.EffectID==""||len(i.ActorChain)!=0||i.Approval!=nil||len(i.Approvals)>16||i.IssuedAt.IsZero()||!i.ExpiresAt.After(i.IssuedAt)||!now.Before(i.ExpiresAt)||i.SigningKeyID==""||i.SigningAlgorithm!=SigningAlgorithmEd25519||i.SigningKeyEpoch==0||len(i.Signature)!=ed25519.SignatureSize||i.ActorAssertion.Validate(now)!=nil{return ErrInvalid};seen:=make(map[string]struct{},len(i.Approvals));for _,approval:=range i.Approvals{if approval.Validate(now)!=nil{return ErrInvalid};if _,duplicate:=seen[approval.AuthorizationID];duplicate{return ErrInvalid};seen[approval.AuthorizationID]=struct{}{}};canonical,err:=canonicalJSON(i.Payload);if err!=nil||digest(canonical)!=i.PayloadDigest{return ErrInvalid};return nil}
func(i Intent)SigStructure()[]byte{envelope:=struct{Domain string `json:"domain"`;ID,PeerID,NodeID,GrantID ID;AuthorityEpoch,CapabilityEpoch uint64;ProtocolVersion uint32;CommandType,SchemaHash,PayloadTypeURL,PayloadDigest,TenantID,ResourceKind,ResourceID,TargetScope string;ExpectedGeneration uint64;IdempotencyKey,EffectID string;Risk Risk;ActorAssertionDigest,ApprovalSetDigest string;IssuedAt,ExpiresAt time.Time;SigningKeyID,SigningAlgorithm string;SigningKeyEpoch uint64}{Domain:"cyberpanel-federated-intent-sig-v2",ID:i.ID,PeerID:i.PeerID,NodeID:i.NodeID,GrantID:i.GrantID,AuthorityEpoch:i.AuthorityEpoch,CapabilityEpoch:i.CapabilityEpoch,ProtocolVersion:i.ProtocolVersion,CommandType:i.CommandType,SchemaHash:i.SchemaHash,PayloadTypeURL:i.PayloadTypeURL,PayloadDigest:i.PayloadDigest,TenantID:i.TenantID,ResourceKind:i.ResourceKind,ResourceID:i.ResourceID,TargetScope:i.TargetScope,ExpectedGeneration:i.ExpectedGeneration,IdempotencyKey:i.IdempotencyKey,EffectID:i.EffectID,Risk:i.Risk,ActorAssertionDigest:digestJSON(i.ActorAssertion),ApprovalSetDigest:digestJSON(i.Approvals),IssuedAt:i.IssuedAt.UTC(),ExpiresAt:i.ExpiresAt.UTC(),SigningKeyID:i.SigningKeyID,SigningAlgorithm:i.SigningAlgorithm,SigningKeyEpoch:i.SigningKeyEpoch};raw,_:=json.Marshal(envelope);return raw}
type IntentStatus string
const(IntentQueued IntentStatus="queued";IntentAccepted IntentStatus="accepted";IntentRunning IntentStatus="running";IntentApplied IntentStatus="applied";IntentRejected IntentStatus="rejected";IntentAmbiguous IntentStatus="ambiguous";IntentExpired IntentStatus="expired")
type Receipt struct{IntentID ID;NodeID ID;EffectID,IdempotencyKey string;Status IntentStatus;OperationID,ResultDigest,ErrorCode,ErrorMessage string;LocalGeneration uint64;AcceptedAt,UpdatedAt time.Time;Terminal bool;SignatureKeyID string;Signature []byte}
func(r Receipt)SigStructure()[]byte{copy:=r;copy.Signature=nil;raw,_:=json.Marshal(struct{Domain string `json:"domain"`;Value Receipt `json:"value"`}{"cyberpanel-federation-receipt-v1",copy});return raw}
type EventPriority uint8
const(PriorityTelemetry EventPriority=1;PriorityState EventPriority=2;PrioritySecurity EventPriority=3;PriorityReceipt EventPriority=4;PriorityRevocation EventPriority=5)
type NodeEvent struct{ID,NodeID ID;Sequence uint64;Priority EventPriority;Kind,TenantID,ResourceID,ResourceKind string;Generation uint64;Payload json.RawMessage;PayloadDigest string;OccurredAt time.Time;SignatureKeyID string;Signature []byte}
func(e NodeEvent)SigStructure()[]byte{copy:=e;copy.Signature=nil;raw,_:=json.Marshal(struct{Domain string `json:"domain"`;Value NodeEvent `json:"value"`}{"cyberpanel-federation-event-v1",copy});return raw}
type ProjectionCursor struct{PeerID,NodeID ID;EventSequence,SnapshotGeneration uint64;LastReceiptAt,UpdatedAt time.Time}
type Revocation struct{PeerID,NodeID ID;NewAuthorityEpoch uint64;GrantIDs []ID;Reason string;IssuedAt time.Time;SigningKeyID string;Signature []byte}
func canonicalJSON(raw []byte)([]byte,error){var value any;decoder:=json.NewDecoder(strings.NewReader(string(raw)));decoder.UseNumber();if err:=decoder.Decode(&value);err!=nil{return nil,err};var extra any;if err:=decoder.Decode(&extra);!errors.Is(err,io.EOF){return nil,ErrInvalid};return json.Marshal(value)}
func digest(raw []byte)string{sum:=sha256.Sum256(raw);return hex.EncodeToString(sum[:])}
func digestJSON(v any)string{if v==nil{return strings.Repeat("0",64)};raw,_:=json.Marshal(v);return digest(raw)}
func riskAllows(maximum,requested Risk)bool{rank:=map[Risk]int{RiskLow:1,RiskModerate:2,RiskHigh:3,RiskCritical:4};return rank[requested]>0&&rank[requested]<=rank[maximum]}
func selectorAllows(selector ResourceSelector,intent Intent)bool{if validateResourceSelector(selector)!=nil{return false};if selector.Kind!="*"&&selector.Kind!=intent.ResourceKind{return false};if selector.TenantID!="*"&&selector.TenantID!=intent.TenantID{return false};if selector.ResourceID!="*"&&selector.ResourceID!=intent.ResourceID{return false};for _,operation:=range selector.Operations{if operation=="*"||operation==intent.CommandType{return true}};return false}
var _=fmt.Sprintf
