package federation

import(
	"bytes"
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"time"
)
const Schema=`
CREATE TABLE IF NOT EXISTS federation_state(singleton_id INTEGER PRIMARY KEY,node_id TEXT NOT NULL,authority_epoch BIGINT NOT NULL,active_peer_id TEXT NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS federation_peers(id TEXT PRIMARY KEY,state TEXT NOT NULL,ca_fingerprint TEXT NOT NULL,signing_keys_json TEXT NOT NULL,node_certificate_ref TEXT NOT NULL,hpke_key_ref TEXT NOT NULL,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS federation_grants(id TEXT PRIMARY KEY,peer_id TEXT NOT NULL,authority_epoch BIGINT NOT NULL,state TEXT NOT NULL,grant_json TEXT NOT NULL,expires_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS federation_intents(id TEXT PRIMARY KEY,peer_id TEXT NOT NULL,authority_epoch BIGINT NOT NULL,effect_id TEXT NOT NULL UNIQUE,idempotency_key TEXT NOT NULL,status TEXT NOT NULL,intent_json TEXT NOT NULL,receipt_json TEXT NOT NULL,accepted_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS federation_events(sequence INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT NOT NULL UNIQUE,priority INTEGER NOT NULL,kind TEXT NOT NULL,payload_json TEXT NOT NULL,payload_bytes BIGINT NOT NULL,occurred_at TIMESTAMP NOT NULL,acked_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS federation_cursors(peer_id TEXT PRIMARY KEY,cursor_json TEXT NOT NULL,updated_at TIMESTAMP NOT NULL);
`
type Peer struct{ID ID;State,CAFingerprint string;SigningKeys map[string][]byte;NodeCertificateRef,HPKEKeyRef string;CreatedAt,UpdatedAt time.Time}
type Store struct{db *sql.DB;clock func()time.Time}
func NewStore(db *sql.DB)(*Store,error){if db==nil{return nil,ErrInvalid};return &Store{db:db,clock:time.Now},nil}
func(s *Store)Bootstrap(ctx context.Context,node ID)error{if !node.Valid(){return ErrInvalid};if _,err:=s.db.ExecContext(ctx,Schema);err!=nil{return err};_,err:=s.db.ExecContext(ctx,`INSERT INTO federation_state VALUES(1,?,1,'',?) ON CONFLICT(singleton_id) DO NOTHING`,node,s.clock().UTC());return err}
func(s *Store)State(ctx context.Context)(ID,uint64,ID,error){var node,peer ID;var epoch uint64;err:=s.db.QueryRowContext(ctx,`SELECT node_id,authority_epoch,active_peer_id FROM federation_state WHERE singleton_id=1`).Scan(&node,&epoch,&peer);return node,epoch,peer,err}
func(s *Store)AdvanceAuthority(ctx context.Context,expected,next uint64,activePeer ID)error{if next<=expected{return ErrInvalid};result,err:=s.db.ExecContext(ctx,`UPDATE federation_state SET authority_epoch=?,active_peer_id=?,updated_at=? WHERE singleton_id=1 AND authority_epoch=?`,next,activePeer,s.clock().UTC(),expected);if err!=nil{return err};count,_:=result.RowsAffected();if count!=1{return ErrStale};_,err=s.db.ExecContext(ctx,`UPDATE federation_grants SET state='revoked',updated_at=? WHERE authority_epoch<?`,s.clock().UTC(),next);return err}
func(s *Store)PutPeer(ctx context.Context,peer Peer)error{raw,_:=json.Marshal(peer.SigningKeys);_,err:=s.db.ExecContext(ctx,`INSERT INTO federation_peers VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET state=excluded.state,ca_fingerprint=excluded.ca_fingerprint,signing_keys_json=excluded.signing_keys_json,node_certificate_ref=excluded.node_certificate_ref,hpke_key_ref=excluded.hpke_key_ref,updated_at=excluded.updated_at`,peer.ID,peer.State,peer.CAFingerprint,raw,peer.NodeCertificateRef,peer.HPKEKeyRef,peer.CreatedAt,peer.UpdatedAt);return err}
func(s *Store)Peer(ctx context.Context,id ID)(Peer,error){var peer Peer;var raw []byte;err:=s.db.QueryRowContext(ctx,`SELECT id,state,ca_fingerprint,signing_keys_json,node_certificate_ref,hpke_key_ref,created_at,updated_at FROM federation_peers WHERE id=?`,id).Scan(&peer.ID,&peer.State,&peer.CAFingerprint,&raw,&peer.NodeCertificateRef,&peer.HPKEKeyRef,&peer.CreatedAt,&peer.UpdatedAt);if errors.Is(err,sql.ErrNoRows){return peer,ErrNotFound};if err!=nil{return peer,err};err=json.Unmarshal(raw,&peer.SigningKeys);return peer,err}
func(s *Store)PutGrant(ctx context.Context,grant MutationGrant)error{raw,_:=json.Marshal(grant);_,err:=s.db.ExecContext(ctx,`INSERT INTO federation_grants VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET state=excluded.state,grant_json=excluded.grant_json,expires_at=excluded.expires_at,updated_at=excluded.updated_at WHERE federation_grants.authority_epoch=excluded.authority_epoch`,grant.ID,grant.PeerID,grant.AuthorityEpoch,"active",raw,grant.ExpiresAt,s.clock().UTC());return err}
func(s *Store)Grant(ctx context.Context,id ID)(MutationGrant,error){var grant MutationGrant;var raw []byte;var state string;err:=s.db.QueryRowContext(ctx,`SELECT state,grant_json FROM federation_grants WHERE id=?`,id).Scan(&state,&raw);if errors.Is(err,sql.ErrNoRows){return grant,ErrNotFound};if err!=nil{return grant,err};if state!="active"{return grant,ErrForbidden};err=json.Unmarshal(raw,&grant);return grant,err}
func(s *Store)AcceptIntent(ctx context.Context,intent Intent)(Receipt,bool,error){tx,err:=s.db.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return Receipt{},false,err};defer tx.Rollback();var raw []byte;var status string;err=tx.QueryRowContext(ctx,`SELECT status,receipt_json FROM federation_intents WHERE id=?`,intent.ID).Scan(&status,&raw);if err==nil{var receipt Receipt;if decodeErr:=json.Unmarshal(raw,&receipt);decodeErr!=nil{return Receipt{},false,decodeErr};return receipt,false,tx.Commit()};if !errors.Is(err,sql.ErrNoRows){return Receipt{},false,err};var effectID string;err=tx.QueryRowContext(ctx,`SELECT effect_id FROM federation_intents WHERE effect_id=? OR idempotency_key=? LIMIT 1`,intent.EffectID,intent.IdempotencyKey).Scan(&effectID);if err==nil{return Receipt{},false,ErrReplay};if !errors.Is(err,sql.ErrNoRows){return Receipt{},false,err};receipt:=Receipt{IntentID:intent.ID,NodeID:intent.NodeID,EffectID:intent.EffectID,IdempotencyKey:intent.IdempotencyKey,Status:IntentAccepted,LocalGeneration:intent.ExpectedGeneration,AcceptedAt:s.clock().UTC(),UpdatedAt:s.clock().UTC()};intentRaw,_:=json.Marshal(intent);receiptRaw,_:=json.Marshal(receipt);_,err=tx.ExecContext(ctx,`INSERT INTO federation_intents VALUES(?,?,?,?,?,?,?,?,?,?)`,intent.ID,intent.PeerID,intent.AuthorityEpoch,intent.EffectID,intent.IdempotencyKey,receipt.Status,intentRaw,receiptRaw,receipt.AcceptedAt,receipt.UpdatedAt);if err!=nil{return Receipt{},false,err};return receipt,true,tx.Commit()}
func(s *Store)CompleteIntent(ctx context.Context,receipt Receipt)error{raw,_:=json.Marshal(receipt);result,err:=s.db.ExecContext(ctx,`UPDATE federation_intents SET status=?,receipt_json=?,updated_at=? WHERE id=? AND status IN ('accepted','running','ambiguous')`,receipt.Status,raw,s.clock().UTC(),receipt.IntentID);if err!=nil{return err};count,_:=result.RowsAffected();if count!=1{return ErrConflict};return nil}
func(s *Store)PendingIntents(ctx context.Context,limit uint32)([]Intent,error){if limit==0||limit>1000{limit=100};rows,err:=s.db.QueryContext(ctx,`SELECT intent_json FROM federation_intents WHERE status IN ('accepted','running','ambiguous') ORDER BY accepted_at LIMIT ?`,limit);if err!=nil{return nil,err};defer rows.Close();var out []Intent;for rows.Next(){var raw []byte;if err=rows.Scan(&raw);err!=nil{return nil,err};var intent Intent;if err=json.Unmarshal(raw,&intent);err!=nil{return nil,err};out=append(out,intent)};return out,rows.Err()}
func(s *Store)EnqueueEvent(ctx context.Context,event NodeEvent)error{if s==nil||s.db==nil||ctx==nil||!event.ID.Valid()||!event.NodeID.Valid()||event.Sequence!=0||event.Priority<PriorityTelemetry||event.Priority>PriorityRevocation||event.Kind==""||len(event.Kind)>128||len(event.Payload)==0||len(event.Payload)>4<<20||event.PayloadDigest!=digest(event.Payload)||event.OccurredAt.IsZero(){return ErrInvalid};raw,err:=json.Marshal(event);if err!=nil{return err};tx,err:=s.db.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return err};defer tx.Rollback();result,err:=tx.ExecContext(ctx,`INSERT INTO federation_events(id,priority,kind,payload_json,payload_bytes,occurred_at) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING`,event.ID,event.Priority,event.Kind,raw,len(raw),event.OccurredAt);if err!=nil{return err};inserted,err:=result.RowsAffected();if err!=nil{return err};if inserted==0{var existing []byte;if err=tx.QueryRowContext(ctx,`SELECT payload_json FROM federation_events WHERE id=?`,event.ID).Scan(&existing);err!=nil{return err};if !bytes.Equal(existing,raw){return ErrConflict}};return tx.Commit()}
func(s *Store)Events(ctx context.Context,after uint64,maxEvents,maxBytes uint32)([]NodeEvent,error){if maxEvents==0||maxEvents>1000{maxEvents=100};if maxBytes==0||maxBytes>16<<20{maxBytes=1<<20};rows,err:=s.db.QueryContext(ctx,`SELECT sequence,payload_json FROM federation_events WHERE sequence>? AND acked_at IS NULL ORDER BY priority DESC,sequence LIMIT ?`,after,maxEvents);if err!=nil{return nil,err};defer rows.Close();var out []NodeEvent;var used uint32;for rows.Next(){var sequence uint64;var raw []byte;if err=rows.Scan(&sequence,&raw);err!=nil{return nil,err};if used+uint32(len(raw))>maxBytes{break};var event NodeEvent;if err=json.Unmarshal(raw,&event);err!=nil{return nil,err};event.Sequence=sequence;out=append(out,event);used+=uint32(len(raw))};return out,rows.Err()}
func(s *Store)ContiguousEvents(ctx context.Context,maxEvents,maxBytes uint32)([]NodeEvent,error){if maxEvents==0||maxEvents>1000{maxEvents=100};if maxBytes==0||maxBytes>MaxFrameBytes{maxBytes=1<<20};rows,err:=s.db.QueryContext(ctx,`SELECT sequence,payload_json FROM federation_events WHERE acked_at IS NULL ORDER BY sequence LIMIT ?`,maxEvents);if err!=nil{return nil,err};defer rows.Close();var out []NodeEvent;var used uint32;for rows.Next(){var sequence uint64;var raw []byte;if err=rows.Scan(&sequence,&raw);err!=nil{return nil,err};if used+uint32(len(raw))>maxBytes{break};var event NodeEvent;if err=json.Unmarshal(raw,&event);err!=nil{return nil,err};event.Sequence=sequence;out=append(out,event);used+=uint32(len(raw))};return out,rows.Err()}
func(s *Store)AckEvents(ctx context.Context,through uint64)error{_,err:=s.db.ExecContext(ctx,`UPDATE federation_events SET acked_at=? WHERE sequence<=? AND acked_at IS NULL`,s.clock().UTC(),through);return err}
func(s *Store)Cursor(ctx context.Context,peer ID)(ProjectionCursor,error){var cursor ProjectionCursor;var raw []byte;err:=s.db.QueryRowContext(ctx,`SELECT cursor_json FROM federation_cursors WHERE peer_id=?`,peer).Scan(&raw);if errors.Is(err,sql.ErrNoRows){return ProjectionCursor{PeerID:peer},nil};if err!=nil{return cursor,err};err=json.Unmarshal(raw,&cursor);return cursor,err}
func(s *Store)PutCursor(ctx context.Context,cursor ProjectionCursor)error{cursor.UpdatedAt=s.clock().UTC();raw,_:=json.Marshal(cursor);_,err:=s.db.ExecContext(ctx,`INSERT INTO federation_cursors VALUES(?,?,?) ON CONFLICT(peer_id) DO UPDATE SET cursor_json=excluded.cursor_json,updated_at=excluded.updated_at`,cursor.PeerID,raw,cursor.UpdatedAt);return err}

// ActivateEnrollment keeps the exact epoch bound into the enrollment request.
// A concurrent local revoke or another peer activation invalidates the commit.
func (s *Store) ActivateEnrollment(ctx context.Context, node ID, expectedEpoch uint64, peer Peer) error {
	if s == nil || s.db == nil || ctx == nil || !node.Valid() || expectedEpoch == 0 || !peer.ID.Valid() || peer.State != "active" || peer.NodeCertificateRef == "" || peer.HPKEKeyRef == "" {
		return ErrInvalid
	}
	keys, err := json.Marshal(peer.SigningKeys)
	if err != nil { return err }
	tx, err := s.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil { return err }
	defer tx.Rollback()
	now := s.clock().UTC()
	update, err := tx.ExecContext(ctx, `UPDATE federation_state SET active_peer_id=?,updated_at=? WHERE singleton_id=1 AND node_id=? AND authority_epoch=? AND active_peer_id=''`, peer.ID, now, node, expectedEpoch)
	if err != nil { return err }
	if affected, rowsErr := update.RowsAffected(); rowsErr != nil || affected != 1 { return ErrStale }
	_, err = tx.ExecContext(ctx, `INSERT INTO federation_peers(id,state,ca_fingerprint,signing_keys_json,node_certificate_ref,hpke_key_ref,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET state=excluded.state,ca_fingerprint=excluded.ca_fingerprint,signing_keys_json=excluded.signing_keys_json,node_certificate_ref=excluded.node_certificate_ref,hpke_key_ref=excluded.hpke_key_ref,updated_at=excluded.updated_at`, peer.ID, peer.State, peer.CAFingerprint, keys, peer.NodeCertificateRef, peer.HPKEKeyRef, peer.CreatedAt, now)
	if err != nil { return err }
	if _, err = tx.ExecContext(ctx, `UPDATE federation_grants SET state='revoked',updated_at=? WHERE authority_epoch<?`, now, expectedEpoch); err != nil { return err }
	return tx.Commit()
}
