package providers

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"io"
	"net/url"
	"strconv"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/backup"
)

// GoogleDriveProvider uses deterministic names inside a pre-authorized folder.
// The adapter is capability-limited: it cannot enumerate or mutate outside the
// configured folder and drive, and receives an in-memory credential per call.
type GoogleDriveProvider struct{Targets map[backup.RepositoryID]DriveTarget;Secrets SecretResolver;Connector DriveConnector;Source ObjectSource;Now func()time.Time}
func (provider GoogleDriveProvider)now()time.Time{if provider.Now!=nil{return provider.Now().UTC()};return time.Now().UTC()}
func (provider GoogleDriveProvider)connect(ctx context.Context,spec backup.RepositorySpec)(DriveTarget,DriveClient,error){if err:=validateSpec(spec,backup.GoogleDrive);err!=nil{return DriveTarget{},nil,err};target,ok:=provider.Targets[spec.Repository.ID];if !ok||provider.Secrets==nil||provider.Connector==nil{return DriveTarget{},nil,ErrNotFound};if err:=target.Validate();err!=nil{return DriveTarget{},nil,err};if target.RepositoryID!=spec.Repository.ID||target.CredentialRef!=spec.Repository.CredentialRef{return DriveTarget{},nil,ErrInvalid};parsed,err:=url.Parse(spec.Repository.Endpoint);if err!=nil||parsed.Scheme!="gdrive"||parsed.Host!="folder"||strings.TrimPrefix(parsed.Path,"/")!=target.FolderID||parsed.RawQuery!=""||parsed.Fragment!=""{return DriveTarget{},nil,ErrInvalid};credential,err:=provider.Secrets.ResolveBackupCredential(ctx,target.CredentialRef,"gdrive:"+string(target.RepositoryID));if err!=nil{return DriveTarget{},nil,errors.Join(ErrCredential,err)};defer clearBytes(credential);client,err:=provider.Connector.Connect(ctx,target,credential);if err!=nil{return DriveTarget{},nil,err};return target,client,nil}
func (provider GoogleDriveProvider)StageManifest(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,effect string)(string,error){if err:=validateManifest(manifest);err!=nil{return "",err};target,client,err:=provider.connect(ctx,spec);if err!=nil{return "",err};defer client.Close();token:=stageToken(spec.Repository.ID,manifest.RecoveryPointID,effect);payload,err:=manifestBytes(manifest);if err!=nil{return "",err};if _,err=provider.writeBytes(ctx,client,target,driveStageName(token),payload);err!=nil{return "",err};return token,nil}
func (provider GoogleDriveProvider)StageObject(ctx context.Context,spec backup.RepositorySpec,staging string,object backup.ObjectDescriptor,effect string)(string,error){if provider.Source==nil||!safeID(staging)||validateObject(object)!=nil{return "",ErrInvalid};target,client,err:=provider.connect(ctx,spec);if err!=nil{return "",err};defer client.Close();name:=driveObjectName(object);existing,err:=client.Find(ctx,target,name);if err==nil&&existing!=nil{return objectPath(object),verifyDriveFile(*existing,object)}else if err!=nil&&!errors.Is(err,ErrNotFound){return "",err};session,err:=client.BeginUpload(ctx,target,name,object.Size,object.Digest,effect);if err!=nil{return "",err};if session.ID==""||session.FileName!=name||session.Offset>object.Size{return "",ErrIntegrity};for session.Offset<object.Size{chunkSize:=minUint64(target.ChunkBytes,object.Size-session.Offset);source,openErr:=provider.Source.OpenObject(ctx,object,effect,session.Offset);if openErr!=nil{return "",openErr};chunk,readErr:=io.ReadAll(io.LimitReader(source,int64(chunkSize)+1));closeErr:=source.Close();if readErr!=nil||closeErr!=nil||uint64(len(chunk))!=chunkSize{return "",errors.Join(ErrIntegrity,readErr,closeErr)};prior:=session.Offset;session,err=client.ResumeUpload(ctx,target,session,prior,chunk,hashBytes(chunk));clearBytes(chunk);if err!=nil{return "",err};if session.Offset!=prior+chunkSize{return "",ErrIntegrity}};file,err:=client.CommitUpload(ctx,target,session);if err!=nil{found,findErr:=client.Find(ctx,target,name);if findErr!=nil||found==nil{return "",errors.Join(ErrAmbiguous,err,findErr)};file=*found};if err=verifyDriveFile(file,object);err!=nil{return "",err};return objectPath(object),nil}
func (provider GoogleDriveProvider)Commit(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,staging,effect string)(backup.CopyReceipt,error){if validateManifest(manifest)!=nil||staging!=stageToken(spec.Repository.ID,manifest.RecoveryPointID,effect){return backup.CopyReceipt{},ErrInvalid};target,client,err:=provider.connect(ctx,spec);if err!=nil{return backup.CopyReceipt{},err};defer client.Close();for _,artifact:=range manifest.Artifacts{for _,object:=range artifact.Objects{file,findErr:=client.Find(ctx,target,driveObjectName(object));if findErr!=nil{return backup.CopyReceipt{},findErr};if file==nil{return backup.CopyReceipt{},ErrNotFound};if err=verifyDriveFile(*file,object);err!=nil{return backup.CopyReceipt{},err}}};payload,err:=manifestBytes(manifest);if err!=nil{return backup.CopyReceipt{},err};if _,err=provider.writeBytes(ctx,client,target,drivePointName(manifest.RecoveryPointID,"manifest"),payload);err!=nil{return backup.CopyReceipt{},err};marker,markerDigest,err:=commitBytes(manifest,spec.Repository.ID,effect,provider.now());if err!=nil{return backup.CopyReceipt{},err};if _,err=provider.writeBytes(ctx,client,target,drivePointName(manifest.RecoveryPointID,"committed"),marker);err!=nil{return backup.CopyReceipt{},err};objects,bytes:=manifestTotals(manifest);return backup.CopyReceipt{ID:copyID(spec.Repository.ID,manifest.RecoveryPointID),RecoveryPointID:manifest.RecoveryPointID,RepositoryID:spec.Repository.ID,FailureDomain:spec.FailureDomain,Status:backup.CopyCommitted,CommitMarker:markerDigest,ManifestDigest:manifest.ManifestDigest,Objects:objects,Bytes:bytes},nil}
func (provider GoogleDriveProvider)Verify(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,receipt backup.CopyReceipt)(backup.CopyReceipt,error){if receipt.RecoveryPointID!=manifest.RecoveryPointID||receipt.RepositoryID!=spec.Repository.ID||receipt.ManifestDigest!=manifest.ManifestDigest{return receipt,ErrIntegrity};target,client,err:=provider.connect(ctx,spec);if err!=nil{return receipt,err};defer client.Close();markerFile,err:=client.Find(ctx,target,drivePointName(manifest.RecoveryPointID,"committed"));if err!=nil{return receipt,err};if markerFile==nil{return receipt,ErrNotFound};marker,err:=client.Read(ctx,target,markerFile.ID,0,1<<20);if err!=nil{return receipt,err};manifestFile,err:=client.Find(ctx,target,drivePointName(manifest.RecoveryPointID,"manifest"));if err!=nil{return receipt,err};if manifestFile==nil{return receipt,ErrNotFound};stored,err:=client.Read(ctx,target,manifestFile.ID,0,64<<20);if err!=nil{return receipt,err};expected,err:=manifestBytes(manifest);if err!=nil||!equalBytes(stored,expected)||hashBytes(marker)!=receipt.CommitMarker{return receipt,ErrIntegrity};for _,artifact:=range manifest.Artifacts{for _,object:=range artifact.Objects{file,findErr:=client.Find(ctx,target,driveObjectName(object));if findErr!=nil{return receipt,findErr};if file==nil{return receipt,ErrNotFound};if err=verifyDriveFile(*file,object);err!=nil{return receipt,err};if err=provider.verifyDriveObject(ctx,client,target,*file,object);err!=nil{return receipt,err}}};receipt.Status=backup.CopyVerified;receipt.VerifiedAt=provider.now();return receipt,nil}
func (provider GoogleDriveProvider)DeleteRecoveryPoint(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,effect string)error{target,client,err:=provider.connect(ctx,spec);if err!=nil{return err};defer client.Close();for _,kind:=range []string{"committed","manifest"}{name:=drivePointName(manifest.RecoveryPointID,kind);file,findErr:=client.Find(ctx,target,name);if errors.Is(findErr,ErrNotFound)||file==nil{continue};if findErr!=nil{return findErr};if err=client.Delete(ctx,target,file.ID,file.Revision);err!=nil&&!errors.Is(err,ErrNotFound){return err}};return nil}
func (provider GoogleDriveProvider)OpenCommittedObject(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,receipt backup.CopyReceipt,object backup.ObjectDescriptor)(backup.ReadCloser,error){if !receiptMatches(spec,manifest,receipt)||!objectInManifest(manifest,object){return nil,ErrInvalid};target,client,err:=provider.connect(ctx,spec);if err!=nil{return nil,err};markerFile,err:=client.Find(ctx,target,drivePointName(manifest.RecoveryPointID,"committed"));if err!=nil||markerFile==nil{client.Close();return nil,ErrNotFound};marker,err:=client.Read(ctx,target,markerFile.ID,0,1<<20);if err!=nil||hashBytes(marker)!=receipt.CommitMarker{client.Close();return nil,ErrIntegrity};file,err:=client.Find(ctx,target,driveObjectName(object));if err!=nil||file==nil{client.Close();return nil,ErrNotFound};if err=verifyDriveFile(*file,object);err!=nil{client.Close();return nil,err};raw:=&driveRawReader{ctx:ctx,client:client,target:target,file:*file,maximumChunk:target.ChunkBytes};return newIntegrityReadCloser(raw,object.Digest,object.Size),nil}
type driveRawReader struct{ctx context.Context;client DriveClient;target DriveTarget;file DriveFile;offset uint64;maximumChunk uint64;pending []byte}
func (reader *driveRawReader)Read(buffer []byte)(int,error){if len(buffer)==0{return 0,nil};if len(reader.pending)>0{count:=copy(buffer,reader.pending);reader.pending=reader.pending[count:];reader.offset+=uint64(count);return count,nil};if reader.offset>=reader.file.Size{return 0,io.EOF};amount:=minUint64(reader.maximumChunk,reader.file.Size-reader.offset);payload,err:=reader.client.Read(reader.ctx,reader.target,reader.file.ID,reader.offset,amount);if err!=nil{return 0,err};if uint64(len(payload))!=amount{return 0,ErrIntegrity};count:=copy(buffer,payload);reader.pending=payload[count:];reader.offset+=uint64(count);return count,nil}
func (reader *driveRawReader)Close()error{clearBytes(reader.pending);reader.pending=nil;return reader.client.Close()}
func (provider GoogleDriveProvider)ProbeRepository(ctx context.Context,spec backup.RepositorySpec,effect string)(RepositoryProbe,error){started:=provider.now();probe:=RepositoryProbe{RepositoryID:spec.Repository.ID,Kind:backup.GoogleDrive,Health:RepositoryUnavailable,Capabilities:[]string{"content_addressed","commit_marker","resumable","sha256","stream_restore"},ObservedAt:provider.now()};target,client,err:=provider.connect(ctx,spec);if err!=nil{probe.DetailDigest=hashText(err.Error());return probe,err};defer client.Close();name:="cp-probe-"+hashText(effect)[:32];payload:=[]byte(hashText(effect));file,err:=provider.writeBytes(ctx,client,target,name,payload);if err==nil{stored,readErr:=client.Read(ctx,target,file.ID,0,uint64(len(payload))+1);if readErr!=nil||!equalBytes(stored,payload){err=errors.Join(ErrIntegrity,readErr)}};if file.ID!=""{_ = client.Delete(ctx,target,file.ID,file.Revision)};probe.Latency=provider.now().Sub(started);if err!=nil{probe.DetailDigest=hashText(err.Error());return probe,err};probe.Health=RepositoryHealthy;probe.DetailDigest=hashText(effect+"\x00gdrive-probe-ok");return probe,nil}
func (provider GoogleDriveProvider)writeBytes(ctx context.Context,client DriveClient,target DriveTarget,name string,payload []byte)(DriveFile,error){digestValue:=hashBytes(payload);existing,err:=client.Find(ctx,target,name);if err==nil&&existing!=nil{if existing.Size==uint64(len(payload))&&existing.Digest==digestValue&&existing.Committed{return *existing,nil};return DriveFile{},ErrConflict};if err!=nil&&!errors.Is(err,ErrNotFound){return DriveFile{},err};file,err:=client.WriteSmallExclusive(ctx,target,name,payload,digestValue);if err!=nil{return DriveFile{},err};if file.Name!=name||file.Size!=uint64(len(payload))||file.Digest!=digestValue||!file.Committed{return DriveFile{},ErrIntegrity};return file,nil}
func (provider GoogleDriveProvider)verifyDriveObject(ctx context.Context,client DriveClient,target DriveTarget,file DriveFile,object backup.ObjectDescriptor)error{hasher:=sha256.New();for offset:=uint64(0);offset<object.Size;{amount:=minUint64(target.ChunkBytes,object.Size-offset);chunk,err:=client.Read(ctx,target,file.ID,offset,amount);if err!=nil{return err};if uint64(len(chunk))!=amount{return ErrIntegrity};_,_=hasher.Write(chunk);offset+=amount};if hex.EncodeToString(hasher.Sum(nil))!=object.Digest{return ErrIntegrity};return nil}
func verifyDriveFile(file DriveFile,object backup.ObjectDescriptor)error{if file.Name!=driveObjectName(object)||file.Size!=object.Size||file.Digest!=object.Digest||!file.Committed{return ErrIntegrity};return nil}
func driveObjectName(object backup.ObjectDescriptor)string{return "cp-blob-"+object.Digest+"-"+strconv.FormatUint(object.Size,10)}
func driveStageName(token string)string{return "cp-stage-"+token+"-manifest.json"}
func drivePointName(point backup.RecoveryPointID,kind string)string{return "cp-point-"+string(point)+"-"+kind+".json"}
