//go:build linux

package providers

import (
	"context"
	"encoding/json"
	"errors"
	"io"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"syscall"
	"time"
	"unsafe"

	"github.com/aonsyed/cyberpanel/platform/internal/backup"
)

type LocalRepository struct{ID backup.RepositoryID;Root string;rootFD int}
func OpenLocalRepository(id backup.RepositoryID,root string)(*LocalRepository,error){base:="/var/backups/cyberpanel/repositories";if id==""||!filepath.IsAbs(root)||filepath.Clean(root)!=root||root==base||!strings.HasPrefix(root,base+"/"){return nil,ErrInvalid};fd,err:=openLocalRepositoryTree(root);if err!=nil{return nil,err};repository:=&LocalRepository{ID:id,Root:root,rootFD:fd};for _,directory:=range []string{".staging","blobs","points"}{opened,openErr:=repository.openDir(directory,false);if openErr==nil{openErr=validateRepositoryDataDirectory(opened)};if openErr!=nil{if opened>=0{syscall.Close(opened)};repository.Close();return nil,openErr};syscall.Close(opened)};return repository,nil}
func (repository *LocalRepository)Close()error{if repository.rootFD<0{return nil};err:=syscall.Close(repository.rootFD);repository.rootFD=-1;return err}

// LocalRepositoryRegistry opens local repositories lazily from their catalog
// identity. The fixed root prevents a catalog record from turning panel-core
// into an arbitrary filesystem writer, while the cache keeps descriptor-safe
// repository roots open for the lifetime of the process.
type LocalRepositoryRegistry struct{Root string;mu sync.Mutex;repositories map[backup.RepositoryID]*LocalRepository}
func NewLocalRepositoryRegistry(root string)(*LocalRepositoryRegistry,error){const fixedRoot="/var/backups/cyberpanel/repositories";if root!=fixedRoot{return nil,ErrInvalid};return &LocalRepositoryRegistry{Root:root,repositories:map[backup.RepositoryID]*LocalRepository{}},nil}
func (registry *LocalRepositoryRegistry)Resolve(id backup.RepositoryID)(*LocalRepository,error){if registry==nil||registry.Root==""||!safeID(string(id)){return nil,ErrInvalid};registry.mu.Lock();defer registry.mu.Unlock();if repository:=registry.repositories[id];repository!=nil&&repository.rootFD>=0{return repository,nil};root:=filepath.Join(registry.Root,string(id));if filepath.Dir(root)!=registry.Root{return nil,ErrInvalid};repository,err:=OpenLocalRepository(id,root);if err!=nil{return nil,err};registry.repositories[id]=repository;return repository,nil}
func (registry *LocalRepositoryRegistry)Close()error{if registry==nil{return nil};registry.mu.Lock();defer registry.mu.Unlock();var result error;for id,repository:=range registry.repositories{result=errors.Join(result,repository.Close());delete(registry.repositories,id)};return result}

type LocalProvider struct{Keys RepositoryKeySource;Repositories map[backup.RepositoryID]*LocalRepository;Registry *LocalRepositoryRegistry;Source ObjectSource;Now func()time.Time}
type localStageMetadata struct{RecoveryPointID backup.RecoveryPointID `json:"recovery_point_id"`;TenantID string `json:"tenant_id"`;ManifestDigest string `json:"manifest_digest"`;EffectID string `json:"effect_id"`}
func NewLocalProvider(root string,source ObjectSource,now func()time.Time)(*LocalProvider,error){if source==nil{return nil,ErrInvalid};registry,err:=NewLocalRepositoryRegistry(root);if err!=nil{return nil,err};return &LocalProvider{Registry:registry,Source:source,Now:now},nil}
func (provider LocalProvider)Close()error{if provider.Registry==nil{return nil};return provider.Registry.Close()}
func (provider LocalProvider)now()time.Time{if provider.Now!=nil{return provider.Now().UTC()};return time.Now().UTC()}
func (provider LocalProvider)repository(spec backup.RepositorySpec)(*LocalRepository,error){if err:=validateSpec(spec,backup.Local);err!=nil{return nil,err};parsed,err:=url.Parse(spec.Repository.Endpoint);if err!=nil||parsed.Scheme!="file"||parsed.Host!=""||parsed.RawQuery!=""||parsed.Fragment!=""{return nil,ErrInvalid};expectedRoot:="";if provider.Registry!=nil{expectedRoot=filepath.Join(provider.Registry.Root,string(spec.Repository.ID));if parsed.Path!=expectedRoot{return nil,ErrInvalid}};repository:=provider.Repositories[spec.Repository.ID];if repository==nil&&provider.Registry!=nil{repository,err=provider.Registry.Resolve(spec.Repository.ID);if err!=nil{return nil,err}};if repository==nil||repository.rootFD<0{return nil,ErrNotFound};if parsed.Path!=repository.Root||(expectedRoot!=""&&repository.Root!=expectedRoot){return nil,ErrInvalid};return repository,nil}

func (provider LocalProvider)plainStageManifest(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,effect string)(string,error){repository,err:=provider.repository(spec);if err!=nil{return "",err};if effect==""||len(effect)>1024||manifest.TenantID!=spec.TenantID{return "",ErrInvalid};if err:=validateManifest(manifest);err!=nil{return "",err};token:=stageToken(spec.Repository.ID,manifest.RecoveryPointID,effect);directory,err:=repository.openDir(".staging/"+token,true);if err!=nil{return "",err};defer syscall.Close(directory);payload,err:=manifestBytes(manifest);if err!=nil{return "",err};if err:=writeExclusiveOrEqual(directory,"manifest.json",payload,0600);err!=nil{return "",err};metadata,err:=json.Marshal(localStageMetadata{RecoveryPointID:manifest.RecoveryPointID,TenantID:manifest.TenantID,ManifestDigest:manifest.ManifestDigest,EffectID:effect});if err!=nil{return "",err};if err=writeExclusiveOrEqual(directory,"metadata.json",metadata,0600);err!=nil{return "",err};return token,nil}

func (provider LocalProvider)plainStageObject(ctx context.Context,spec backup.RepositorySpec,staging string,object backup.ObjectDescriptor,effect string)(string,error){repository,err:=provider.repository(spec);if err!=nil{return "",err};if provider.Source==nil||!safeID(staging)||effect==""||len(effect)>1024||validateObject(object)!=nil{return "",ErrInvalid};stagedManifest,metadata,err:=loadLocalStage(repository,staging);if err!=nil||metadata.EffectID!=effect||metadata.TenantID!=spec.TenantID||!objectInManifest(stagedManifest,object){return "",errors.Join(ErrInvalid,err)};if staging!=stageToken(spec.Repository.ID,metadata.RecoveryPointID,effect){return "",ErrInvalid};relative:=objectPath(object);directoryPath,leaf:=filepath.ToSlash(filepath.Dir(relative)),filepath.Base(relative);directory,err:=repository.openDir(directoryPath,true);if err!=nil{return "",err};defer syscall.Close(directory);if valid,verifyErr:=verifyRegularAt(directory,leaf,object.Digest,object.Size);verifyErr==nil&&valid{return relative,nil}else if verifyErr!=nil&&!errors.Is(verifyErr,ErrNotFound){return "",verifyErr};partial:=leaf+".partial."+hashText(effect)[:20];offset,err:=regularSizeAt(directory,partial);if errors.Is(err,ErrNotFound){offset=0}else if err!=nil{return "",err};if offset>object.Size{_ = unlinkAt(directory,partial,false);return "",ErrIntegrity};reader,err:=provider.Source.OpenObject(ctx,object,effect,offset);if err!=nil{return "",err};defer reader.Close();fd,err:=syscall.Openat(directory,partial,syscall.O_WRONLY|syscall.O_CREAT|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0600);if err!=nil{return "",err};file:=os.NewFile(uintptr(fd),partial);if _,err=file.Seek(int64(offset),io.SeekStart);err!=nil{file.Close();return "",err};written,copyErr:=io.Copy(file,io.LimitReader(reader,int64(object.Size-offset)+1));syncErr:=file.Sync();closeErr:=file.Close();if copyErr!=nil||syncErr!=nil||closeErr!=nil||uint64(written)!=object.Size-offset{_ = unlinkAt(directory,partial,false);return "",errors.Join(ErrIntegrity,copyErr,syncErr,closeErr)};valid,err:=verifyRegularAt(directory,partial,object.Digest,object.Size);if err!=nil||!valid{_ = unlinkAt(directory,partial,false);return "",errors.Join(ErrIntegrity,err)};if err:=renameNoReplace(directory,partial,directory,leaf);err!=nil{if valid,verifyErr:=verifyRegularAt(directory,leaf,object.Digest,object.Size);verifyErr==nil&&valid{_ = unlinkAt(directory,partial,false);return relative,nil};return "",err};_ = syscall.Fsync(directory);return relative,nil}

func (provider LocalProvider)plainCommit(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,staging,effect string)(backup.CopyReceipt,error){repository,err:=provider.repository(spec);if err!=nil{return backup.CopyReceipt{},err};expected:=stageToken(spec.Repository.ID,manifest.RecoveryPointID,effect);if staging!=expected||effect==""||manifest.TenantID!=spec.TenantID||validateManifest(manifest)!=nil{return backup.CopyReceipt{},ErrInvalid};staged,metadata,err:=loadLocalStage(repository,staging);if err!=nil||metadata.EffectID!=effect||metadata.TenantID!=manifest.TenantID||metadata.RecoveryPointID!=manifest.RecoveryPointID||metadata.ManifestDigest!=manifest.ManifestDigest{return backup.CopyReceipt{},errors.Join(ErrIntegrity,err)};manifestPayload,err:=manifestBytes(manifest);if err!=nil{return backup.CopyReceipt{},err};stagedPayload,err:=manifestBytes(staged);if err!=nil||!equalBytes(stagedPayload,manifestPayload){return backup.CopyReceipt{},errors.Join(ErrIntegrity,err)};for _,artifact:=range manifest.Artifacts{for _,object:=range artifact.Objects{relative:=objectPath(object);directory,openErr:=repository.openDir(filepath.ToSlash(filepath.Dir(relative)),false);if openErr!=nil{return backup.CopyReceipt{},openErr};valid,verifyErr:=verifyRegularAt(directory,filepath.Base(relative),object.Digest,object.Size);syscall.Close(directory);if verifyErr!=nil||!valid{return backup.CopyReceipt{},errors.Join(ErrIntegrity,verifyErr)}}};point,err:=repository.openDir("points/"+string(manifest.RecoveryPointID),true);if err!=nil{return backup.CopyReceipt{},err};defer syscall.Close(point);if err=writeExclusiveOrEqual(point,"manifest.json",manifestPayload,0600);err!=nil{return backup.CopyReceipt{},err};markerPayload,markerDigest,err:=commitBytes(manifest,spec.Repository.ID,effect,provider.now());if err!=nil{return backup.CopyReceipt{},err};if err=writeExclusiveOrEqual(point,"COMMITTED",markerPayload,0600);err!=nil{return backup.CopyReceipt{},err};if err=syscall.Fsync(point);err!=nil{return backup.CopyReceipt{},err};objects,bytes:=manifestTotals(manifest);return backup.CopyReceipt{ID:copyID(spec.Repository.ID,manifest.RecoveryPointID),RecoveryPointID:manifest.RecoveryPointID,RepositoryID:spec.Repository.ID,FailureDomain:spec.FailureDomain,Status:backup.CopyCommitted,CommitMarker:markerDigest,ManifestDigest:manifest.ManifestDigest,Objects:objects,Bytes:bytes},nil}

func (provider LocalProvider)plainVerify(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,receipt backup.CopyReceipt)(backup.CopyReceipt,error){repository,err:=provider.repository(spec);if err!=nil{return receipt,err};if receipt.RecoveryPointID!=manifest.RecoveryPointID||receipt.RepositoryID!=spec.Repository.ID||receipt.ManifestDigest!=manifest.ManifestDigest||manifest.TenantID!=spec.TenantID||validateManifest(manifest)!=nil{return receipt,ErrIntegrity};point,err:=repository.openDir("points/"+string(manifest.RecoveryPointID),false);if err!=nil{return receipt,err};err=verifyLocalCommit(point,spec,manifest,receipt);syscall.Close(point);if err!=nil{return receipt,err};for _,artifact:=range manifest.Artifacts{for _,object:=range artifact.Objects{relative:=objectPath(object);directory,openErr:=repository.openDir(filepath.ToSlash(filepath.Dir(relative)),false);if openErr!=nil{return receipt,openErr};valid,verifyErr:=verifyRegularAt(directory,filepath.Base(relative),object.Digest,object.Size);syscall.Close(directory);if verifyErr!=nil||!valid{return receipt,errors.Join(ErrIntegrity,verifyErr)}}};receipt.Status=backup.CopyVerified;receipt.VerifiedAt=provider.now();return receipt,nil}

func (provider LocalProvider)DeleteRecoveryPoint(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,effect string)error{repository,err:=provider.repository(spec);if err!=nil{return err};point,err:=repository.openDir("points/"+string(manifest.RecoveryPointID),false);if errors.Is(err,ErrNotFound){return nil};if err!=nil{return err};for _,leaf:=range []string{"COMMITTED","manifest.json"}{if unlinkErr:=unlinkAt(point,leaf,false);unlinkErr!=nil&&!errors.Is(unlinkErr,ErrNotFound){syscall.Close(point);return unlinkErr}};syscall.Close(point);points,err:=repository.openDir("points",false);if err!=nil{return err};err=unlinkAt(points,string(manifest.RecoveryPointID),true);syscall.Close(points);return err}
func (provider LocalProvider)plainOpenCommittedObject(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,receipt backup.CopyReceipt,object backup.ObjectDescriptor)(backup.ReadCloser,error){repository,err:=provider.repository(spec);if err!=nil{return nil,err};if manifest.TenantID!=spec.TenantID||validateManifest(manifest)!=nil||!receiptMatches(spec,manifest,receipt)||!objectInManifest(manifest,object){return nil,ErrInvalid};point,err:=repository.openDir("points/"+string(manifest.RecoveryPointID),false);if err!=nil{return nil,err};err=verifyLocalCommit(point,spec,manifest,receipt);syscall.Close(point);if err!=nil{return nil,err};relative:=objectPath(object);directory,err:=repository.openDir(filepath.ToSlash(filepath.Dir(relative)),false);if err!=nil{return nil,err};valid,err:=verifyRegularAt(directory,filepath.Base(relative),object.Digest,object.Size);if err!=nil||!valid{syscall.Close(directory);return nil,errors.Join(ErrIntegrity,err)};fd,err:=syscall.Openat(directory,filepath.Base(relative),syscall.O_RDONLY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);syscall.Close(directory);if err!=nil{return nil,err};return newIntegrityReadCloser(os.NewFile(uintptr(fd),object.Digest),object.Digest,object.Size),nil}
func (provider LocalProvider)plainProbeRepository(ctx context.Context,spec backup.RepositorySpec,effect string)(RepositoryProbe,error){started:=provider.now();repository,err:=provider.repository(spec);probe:=RepositoryProbe{RepositoryID:spec.Repository.ID,Kind:backup.Local,Health:RepositoryUnavailable,Capabilities:[]string{"content_addressed","immutable_manifest","manifest_digest_verified","commit_marker","descriptor_safe","staging_before_activation","resume","stream_restore"},ObservedAt:provider.now()};if err!=nil{probe.DetailDigest=hashText(err.Error());return probe,err};directory,err:=repository.openDir(".staging",false);if err==nil{err=syscall.Fsync(directory);syscall.Close(directory)};probe.Latency=provider.now().Sub(started);if err!=nil{probe.DetailDigest=hashText(err.Error());return probe,err};probe.Health=RepositoryHealthy;probe.DetailDigest=hashText(effect+"\x00local-probe-ok");return probe,nil}

func loadLocalStage(repository *LocalRepository,staging string)(backup.RecoveryPointManifest,localStageMetadata,error){if repository==nil||!safeID(staging){return backup.RecoveryPointManifest{},localStageMetadata{},ErrInvalid};directory,err:=repository.openDir(".staging/"+staging,false);if err!=nil{return backup.RecoveryPointManifest{},localStageMetadata{},err};defer syscall.Close(directory);manifestRaw,err:=readRegularAt(directory,"manifest.json",64<<20);if err!=nil{return backup.RecoveryPointManifest{},localStageMetadata{},err};metadataRaw,err:=readRegularAt(directory,"metadata.json",1<<20);if err!=nil{return backup.RecoveryPointManifest{},localStageMetadata{},err};var manifest backup.RecoveryPointManifest;var metadata localStageMetadata;if json.Unmarshal(manifestRaw,&manifest)!=nil||json.Unmarshal(metadataRaw,&metadata)!=nil||validateManifest(manifest)!=nil||metadata.RecoveryPointID!=manifest.RecoveryPointID||metadata.TenantID!=manifest.TenantID||metadata.ManifestDigest!=manifest.ManifestDigest{return backup.RecoveryPointManifest{},localStageMetadata{},ErrIntegrity};return manifest,metadata,nil}
func verifyLocalCommit(point int,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,receipt backup.CopyReceipt)error{marker,err:=readRegularAt(point,"COMMITTED",1<<20);if err!=nil{return err};storedManifest,err:=readRegularAt(point,"manifest.json",64<<20);if err!=nil{return err};expectedManifest,err:=manifestBytes(manifest);if err!=nil||!equalBytes(storedManifest,expectedManifest){return errors.Join(ErrIntegrity,err)};if _,err=validateCommitBytes(marker,spec,manifest,receipt);err!=nil{return err};return nil}

func (repository *LocalRepository)openDir(relative string,create bool)(int,error){if repository.rootFD<0||!safePrefix(relative){return -1,ErrInvalid};current,err:=syscall.Dup(repository.rootFD);if err!=nil{return -1,err};if relative==""||relative=="."{return current,nil};for _,segment:=range strings.Split(relative,"/"){if segment==""||segment=="."||segment==".."{syscall.Close(current);return -1,ErrInvalid};next,openErr:=syscall.Openat(current,segment,syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if openErr!=nil&&create&&errors.Is(openErr,syscall.ENOENT){if mkdirErr:=syscall.Mkdirat(current,segment,0700);mkdirErr!=nil&&!errors.Is(mkdirErr,syscall.EEXIST){syscall.Close(current);return -1,mkdirErr};next,openErr=syscall.Openat(current,segment,syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0)};syscall.Close(current);if openErr!=nil{if errors.Is(openErr,syscall.ENOENT){return -1,ErrNotFound};return -1,openErr};current=next};return current,nil}
func writeExclusiveOrEqual(directory int,leaf string,payload []byte,mode uint32)error{if !safeLeaf(leaf){return ErrInvalid};fd,err:=syscall.Openat(directory,leaf,syscall.O_WRONLY|syscall.O_CREAT|syscall.O_EXCL|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,mode);if errors.Is(err,syscall.EEXIST){existing,readErr:=readRegularAt(directory,leaf,uint64(len(payload))+1);if readErr==nil&&equalBytes(existing,payload){return nil};return ErrConflict};if err!=nil{return err};file:=os.NewFile(uintptr(fd),leaf);written,writeErr:=file.Write(payload);syncErr:=file.Sync();closeErr:=file.Close();if writeErr!=nil||syncErr!=nil||closeErr!=nil||written!=len(payload){return errors.Join(ErrIntegrity,writeErr,syncErr,closeErr)};return syscall.Fsync(directory)}
func readRegularAt(directory int,leaf string,maximum uint64)([]byte,error){if !safeLeaf(leaf){return nil,ErrInvalid};fd,err:=syscall.Openat(directory,leaf,syscall.O_RDONLY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if errors.Is(err,syscall.ENOENT){return nil,ErrNotFound};if err!=nil{return nil,err};file:=os.NewFile(uintptr(fd),leaf);defer file.Close();info,err:=file.Stat();if err!=nil||!info.Mode().IsRegular()||uint64(info.Size())>maximum{return nil,ErrIntegrity};payload,err:=io.ReadAll(io.LimitReader(file,int64(maximum)+1));if err!=nil||uint64(len(payload))>maximum{return nil,ErrIntegrity};return payload,nil}
func regularSizeAt(directory int,leaf string)(uint64,error){fd,err:=syscall.Openat(directory,leaf,syscall.O_RDONLY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if errors.Is(err,syscall.ENOENT){return 0,ErrNotFound};if err!=nil{return 0,err};file:=os.NewFile(uintptr(fd),leaf);defer file.Close();info,err:=file.Stat();if err!=nil||!info.Mode().IsRegular()||info.Size()<0{return 0,ErrIntegrity};return uint64(info.Size()),nil}
func verifyRegularAt(directory int,leaf,digestValue string,size uint64)(bool,error){fd,err:=syscall.Openat(directory,leaf,syscall.O_RDONLY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if errors.Is(err,syscall.ENOENT){return false,ErrNotFound};if err!=nil{return false,err};file:=os.NewFile(uintptr(fd),leaf);defer file.Close();info,err:=file.Stat();if err!=nil||!info.Mode().IsRegular()||uint64(info.Size())!=size{return false,ErrIntegrity};_,err=verifyReader(file,digestValue,size);return err==nil,err}
func renameNoReplace(sourceDirectory int,source string,targetDirectory int,target string)error{if !safeLeaf(source)||!safeLeaf(target){return ErrInvalid};if _,err:=regularSizeAt(targetDirectory,target);err==nil{return ErrConflict}else if !errors.Is(err,ErrNotFound){return err};if err:=syscall.Renameat(sourceDirectory,source,targetDirectory,target);err!=nil{return err};return nil}
func unlinkAt(directory int,leaf string,directoryEntry bool)error{if !safeLeaf(leaf){return ErrInvalid};name,err:=syscall.BytePtrFromString(leaf);if err!=nil{return err};flags:=uintptr(0);if directoryEntry{flags=0x200};_,_,errno:=syscall.Syscall(syscall.SYS_UNLINKAT,uintptr(directory),uintptr(unsafe.Pointer(name)),flags);if errno==syscall.ENOENT{return ErrNotFound};if errno!=0{return errno};return nil}
func validateRepositoryDataDirectory(directory int)error{var stat syscall.Stat_t;if directory<0||syscall.Fstat(directory,&stat)!=nil||stat.Mode&syscall.S_IFMT!=syscall.S_IFDIR||stat.Uid!=uint32(os.Geteuid())||stat.Gid!=uint32(os.Getegid())||stat.Mode&07777!=0700{return ErrInvalid};return nil}
func openRootOwnedTree(absolute string)(int,error){if !filepath.IsAbs(absolute)||filepath.Clean(absolute)!=absolute{return -1,ErrInvalid};current,err:=syscall.Open("/",syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if err!=nil{return -1,err};trustedUID:=uint32(os.Geteuid());segments:=strings.Split(strings.TrimPrefix(absolute,"/"),"/");for index,segment:=range segments{if !safeLeaf(segment){syscall.Close(current);return -1,ErrInvalid};next,openErr:=syscall.Openat(current,segment,syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if errors.Is(openErr,syscall.ENOENT){if mkdirErr:=syscall.Mkdirat(current,segment,0700);mkdirErr!=nil&&!errors.Is(mkdirErr,syscall.EEXIST){syscall.Close(current);return -1,mkdirErr};next,openErr=syscall.Openat(current,segment,syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0)};syscall.Close(current);if openErr!=nil{return -1,openErr};var stat syscall.Stat_t;if err=syscall.Fstat(next,&stat);err!=nil||(stat.Uid!=0&&stat.Uid!=trustedUID)||stat.Mode&syscall.S_IFMT!=syscall.S_IFDIR||stat.Mode&0022!=0||(index==len(segments)-1&&stat.Mode&0077!=0){syscall.Close(next);return -1,ErrInvalid};current=next};return current,nil}
func safeLeaf(value string)bool{return value!=""&&value!="."&&value!=".."&&!strings.Contains(value,"/")&&len(value)<=255}
