package providers

import (
	"context"
	"crypto/sha256"
	"crypto/tls"
	"encoding/base64"
	"encoding/hex"
	"encoding/xml"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strconv"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/backup"
)

type S3ClientFactory interface{Client(context.Context,S3Target)(*http.Client,error)}
type S3Provider struct{Targets map[backup.RepositoryID]S3Target;Credentials S3CredentialResolver;Source ObjectSource;Journal UploadJournal;Clients S3ClientFactory;Now func()time.Time}
type s3ObjectInfo struct{Size uint64;Digest string;ETag string;ChecksumSHA256 string}
type s3Binding struct{target S3Target;credentials S3Credentials;client *http.Client}
func (provider S3Provider)now()time.Time{if provider.Now!=nil{return provider.Now().UTC()};return time.Now().UTC()}
func (provider S3Provider)binding(ctx context.Context,spec backup.RepositorySpec)(s3Binding,error){kind:=spec.Repository.Kind;if kind!=backup.S3&&kind!=backup.AWS&&kind!=backup.Wasabi&&kind!=backup.Backblaze&&kind!=backup.DigitalOceanSpaces&&kind!=backup.MinIO{return s3Binding{},ErrInvalid};if err:=validateSpec(spec,kind);err!=nil{return s3Binding{},err};target,ok:=provider.Targets[spec.Repository.ID];if !ok||provider.Credentials==nil{return s3Binding{},ErrNotFound};if err:=target.Validate();err!=nil{return s3Binding{},err};if target.Provider!=kind||target.RepositoryID!=spec.Repository.ID||target.CredentialRef!=spec.Repository.CredentialRef||target.Endpoint!=strings.TrimSuffix(spec.Repository.Endpoint,"/")||target.Bucket!=spec.Repository.Bucket||target.PartSize<spec.MinimumPartBytes||target.PartSize>spec.MaximumPartBytes||target.MaximumConcurrency>spec.MaximumConcurrency{return s3Binding{},ErrInvalid};credentials,err:=provider.Credentials.ResolveS3(ctx,target.CredentialRef,target.RepositoryID);if err!=nil{return s3Binding{},errors.Join(ErrCredential,err)};if err=credentials.Validate(provider.now());err!=nil{return s3Binding{},err};var client *http.Client;if provider.Clients!=nil{client,err=provider.Clients.Client(ctx,target)}else{if target.PinnedCARef!=""{return s3Binding{},ErrCredential};base,ok:=http.DefaultTransport.(*http.Transport);if !ok{return s3Binding{},ErrInvalid};transport:=base.Clone();transport.TLSClientConfig=&tls.Config{MinVersion:tls.VersionTLS12};transport.DisableCompression=true;transport.MaxIdleConnsPerHost=int(target.MaximumConcurrency);client=&http.Client{Transport:transport,Timeout:6*time.Hour,CheckRedirect:func(*http.Request,[]*http.Request)error{return http.ErrUseLastResponse}}};if err!=nil||client==nil{return s3Binding{},err};return s3Binding{target:target,credentials:credentials,client:client},nil}

func (provider S3Provider)StageManifest(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,effect string)(string,error){if err:=validateManifest(manifest);err!=nil{return "",err};binding,err:=provider.binding(ctx,spec);if err!=nil{return "",err};token:=stageToken(spec.Repository.ID,manifest.RecoveryPointID,effect);payload,err:=manifestBytes(manifest);if err!=nil{return "",err};if err=provider.putBytes(ctx,binding,".staging/"+token+"/manifest.json",payload,"application/json");err!=nil{return "",err};return token,nil}

func (provider S3Provider)StageObject(ctx context.Context,spec backup.RepositorySpec,staging string,object backup.ObjectDescriptor,effect string)(string,error){if provider.Source==nil||!safeID(staging)||validateObject(object)!=nil{return "",ErrInvalid};binding,err:=provider.binding(ctx,spec);if err!=nil{return "",err};key:=objectPath(object);if info,headErr:=provider.head(ctx,binding,key);headErr==nil{return key,verifyS3Info(info,object)}else if !errors.Is(headErr,ErrNotFound){return "",headErr};if object.Size<binding.target.PartSize{return key,provider.putObject(ctx,binding,key,object,effect)};if provider.Journal==nil{return "",ErrInvalid};return key,provider.putMultipart(ctx,binding,key,object,effect)}

func (provider S3Provider)Commit(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,staging,effect string)(backup.CopyReceipt,error){if validateManifest(manifest)!=nil||staging!=stageToken(spec.Repository.ID,manifest.RecoveryPointID,effect){return backup.CopyReceipt{},ErrInvalid};binding,err:=provider.binding(ctx,spec);if err!=nil{return backup.CopyReceipt{},err};for _,artifact:=range manifest.Artifacts{for _,object:=range artifact.Objects{info,headErr:=provider.head(ctx,binding,objectPath(object));if headErr!=nil{return backup.CopyReceipt{},headErr};if err=verifyS3Info(info,object);err!=nil{return backup.CopyReceipt{},err}}};point:="points/"+string(manifest.RecoveryPointID);payload,err:=manifestBytes(manifest);if err!=nil{return backup.CopyReceipt{},err};if err=provider.putBytes(ctx,binding,point+"/manifest.json",payload,"application/json");err!=nil{return backup.CopyReceipt{},err};marker,markerDigest,err:=commitBytes(manifest,spec.Repository.ID,effect,provider.now());if err!=nil{return backup.CopyReceipt{},err};if err=provider.putBytes(ctx,binding,point+"/COMMITTED",marker,"application/json");err!=nil{return backup.CopyReceipt{},err};objects,bytes:=manifestTotals(manifest);return backup.CopyReceipt{ID:copyID(spec.Repository.ID,manifest.RecoveryPointID),RecoveryPointID:manifest.RecoveryPointID,RepositoryID:spec.Repository.ID,FailureDomain:spec.FailureDomain,Status:backup.CopyCommitted,CommitMarker:markerDigest,ManifestDigest:manifest.ManifestDigest,Objects:objects,Bytes:bytes},nil}

func (provider S3Provider)Verify(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,receipt backup.CopyReceipt)(backup.CopyReceipt,error){if receipt.RecoveryPointID!=manifest.RecoveryPointID||receipt.RepositoryID!=spec.Repository.ID||receipt.ManifestDigest!=manifest.ManifestDigest{return receipt,ErrIntegrity};binding,err:=provider.binding(ctx,spec);if err!=nil{return receipt,err};point:="points/"+string(manifest.RecoveryPointID);marker,err:=provider.getBytes(ctx,binding,point+"/COMMITTED",1<<20);if err!=nil{return receipt,err};stored,err:=provider.getBytes(ctx,binding,point+"/manifest.json",64<<20);if err!=nil{return receipt,err};expected,err:=manifestBytes(manifest);if err!=nil||!equalBytes(stored,expected)||hashBytes(marker)!=receipt.CommitMarker{return receipt,ErrIntegrity};for _,artifact:=range manifest.Artifacts{for _,object:=range artifact.Objects{if err=provider.verifyObject(ctx,binding,objectPath(object),object);err!=nil{return receipt,err}}};receipt.Status=backup.CopyVerified;receipt.VerifiedAt=provider.now();return receipt,nil}

func (provider S3Provider)DeleteRecoveryPoint(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,effect string)error{binding,err:=provider.binding(ctx,spec);if err!=nil{return err};point:="points/"+string(manifest.RecoveryPointID);for _,leaf:=range []string{"COMMITTED","manifest.json"}{if err=provider.delete(ctx,binding,point+"/"+leaf);err!=nil&&!errors.Is(err,ErrNotFound){return err}};return nil}
func (provider S3Provider)OpenCommittedObject(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,receipt backup.CopyReceipt,object backup.ObjectDescriptor)(backup.ReadCloser,error){if !receiptMatches(spec,manifest,receipt)||!objectInManifest(manifest,object){return nil,ErrInvalid};binding,err:=provider.binding(ctx,spec);if err!=nil{return nil,err};marker,err:=provider.getBytes(ctx,binding,"points/"+string(manifest.RecoveryPointID)+"/COMMITTED",1<<20);if err!=nil||hashBytes(marker)!=receipt.CommitMarker{return nil,ErrIntegrity};info,err:=provider.head(ctx,binding,objectPath(object));if err!=nil{return nil,err};if err=verifyS3Info(info,object);err!=nil{return nil,err};response,err:=provider.request(ctx,binding,http.MethodGet,objectPath(object),nil,nil,0,hashBytes(nil),nil);if err!=nil{return nil,err};if response.StatusCode<200||response.StatusCode>=300{defer response.Body.Close();return nil,s3ResponseError(response)};return newIntegrityReadCloser(response.Body,object.Digest,object.Size),nil}
func (provider S3Provider)ProbeRepository(ctx context.Context,spec backup.RepositorySpec,effect string)(RepositoryProbe,error){started:=provider.now();probe:=RepositoryProbe{RepositoryID:spec.Repository.ID,Kind:spec.Repository.Kind,Health:RepositoryUnavailable,Capabilities:[]string{"content_addressed","commit_marker","multipart","resume","sha256","sigv4","stream_restore"},ObservedAt:provider.now()};binding,err:=provider.binding(ctx,spec);if err!=nil{probe.DetailDigest=hashText(err.Error());return probe,err};key:=".staging/probe-"+hashText(effect)[:32];payload:=[]byte(hashText(effect));if err=provider.putBytes(ctx,binding,key,payload,"application/octet-stream");err==nil{stored,readErr:=provider.getBytes(ctx,binding,key,uint64(len(payload))+1);if readErr!=nil||!equalBytes(stored,payload){err=errors.Join(ErrIntegrity,readErr)}};_ = provider.delete(ctx,binding,key);probe.Latency=provider.now().Sub(started);if err!=nil{probe.DetailDigest=hashText(err.Error());return probe,err};probe.Health=RepositoryHealthy;probe.DetailDigest=hashText(effect+"\x00s3-probe-ok");return probe,nil}

func (provider S3Provider)putObject(ctx context.Context,binding s3Binding,key string,object backup.ObjectDescriptor,effect string)error{source,err:=provider.Source.OpenObject(ctx,object,effect,0);if err!=nil{return err};defer source.Close();headers:=http.Header{"Content-Type":[]string{"application/octet-stream"},"If-None-Match":[]string{"*"},"X-Amz-Meta-Sha256":[]string{object.Digest},"X-Amz-Meta-Size":[]string{strconv.FormatUint(object.Size,10)}};response,err:=provider.request(ctx,binding,http.MethodPut,key,nil,source,int64(object.Size),object.Digest,headers);if err!=nil{return err};defer response.Body.Close();if response.StatusCode>=200&&response.StatusCode<300{_,_=io.Copy(io.Discard,io.LimitReader(response.Body,64<<10));return nil};if response.StatusCode==http.StatusPreconditionFailed||response.StatusCode==http.StatusConflict{info,headErr:=provider.head(ctx,binding,key);if headErr==nil{return verifyS3Info(info,object)}};return s3ResponseError(response)}
func (provider S3Provider)putBytes(ctx context.Context,binding s3Binding,key string,payload []byte,contentType string)error{digestValue:=hashBytes(payload);info,err:=provider.head(ctx,binding,key);if err==nil{if info.Size==uint64(len(payload))&&info.Digest==digestValue{return nil};return ErrConflict};if !errors.Is(err,ErrNotFound){return err};headers:=http.Header{"Content-Type":[]string{contentType},"If-None-Match":[]string{"*"},"X-Amz-Meta-Sha256":[]string{digestValue},"X-Amz-Meta-Size":[]string{strconv.Itoa(len(payload))}};response,err:=provider.request(ctx,binding,http.MethodPut,key,nil,strings.NewReader(string(payload)),int64(len(payload)),digestValue,headers);if err!=nil{return err};defer response.Body.Close();if response.StatusCode>=200&&response.StatusCode<300{_,_=io.Copy(io.Discard,io.LimitReader(response.Body,64<<10));return nil};if response.StatusCode==http.StatusPreconditionFailed||response.StatusCode==http.StatusConflict{existing,headErr:=provider.head(ctx,binding,key);if headErr==nil&&existing.Size==uint64(len(payload))&&existing.Digest==digestValue{return nil}};return s3ResponseError(response)}

func (provider S3Provider)putMultipart(ctx context.Context,binding s3Binding,key string,object backup.ObjectDescriptor,effect string)error{sessionID:="mpu_"+hashText(string(binding.target.RepositoryID)+"\x00"+effect+"\x00"+key)[:48];session,err:=provider.Journal.LoadUpload(ctx,sessionID);if errors.Is(err,ErrNotFound){uploadID,beginErr:=provider.beginMultipart(ctx,binding,key,object);if beginErr!=nil{return beginErr};now:=provider.now();session=UploadSession{ID:sessionID,RepositoryID:binding.target.RepositoryID,EffectID:effect,ObjectKey:key,ObjectDigest:object.Digest,ObjectSize:object.Size,ProviderUploadID:uploadID,PartSize:binding.target.PartSize,State:"uploading",Generation:1,CreatedAt:now,UpdatedAt:now};if err=provider.Journal.CreateUpload(ctx,session);err!=nil{return errors.Join(ErrAmbiguous,err)}}else if err!=nil{return err};if session.RepositoryID!=binding.target.RepositoryID||session.EffectID!=effect||session.ObjectKey!=key||session.ObjectDigest!=object.Digest||session.ObjectSize!=object.Size||session.PartSize!=binding.target.PartSize{return ErrConflict};completed:=map[uint32]UploadPart{};for _,part:=range session.Parts{completed[part.Number]=part};for offset,number:=uint64(0),uint32(1);offset<object.Size;offset,number=offset+minUint64(session.PartSize,object.Size-offset),number+1{size:=minUint64(session.PartSize,object.Size-offset);if part,ok:=completed[number];ok{if part.Offset!=offset||part.Size!=size{return ErrIntegrity};continue};partDigest,checksum,hashErr:=provider.sourcePartDigest(ctx,object,effect,offset,size);if hashErr!=nil{return hashErr};etag,uploadErr:=provider.uploadPart(ctx,binding,session,object,effect,number,offset,size,partDigest,checksum);if uploadErr!=nil{return uploadErr};previous:=session.Generation;session.Parts=append(session.Parts,UploadPart{Number:number,Offset:offset,Size:size,Digest:partDigest,ETag:etag,CompletedAt:provider.now()});session.Generation++;session.UpdatedAt=provider.now();if err=provider.Journal.SaveUpload(ctx,session,previous);err!=nil{return errors.Join(ErrAmbiguous,err)}};if err=provider.completeMultipart(ctx,binding,session);err!=nil{info,headErr:=provider.head(ctx,binding,key);if headErr!=nil||verifyS3Info(info,object)!=nil{return err}};info,err:=provider.head(ctx,binding,key);if err!=nil{return errors.Join(ErrAmbiguous,err)};if err=verifyS3Info(info,object);err!=nil{return err};if err=provider.Journal.DeleteUpload(ctx,session.ID,session.Generation);err!=nil&&!errors.Is(err,ErrConflict){return errors.Join(ErrAmbiguous,err)};return nil}

func (provider S3Provider)beginMultipart(ctx context.Context,binding s3Binding,key string,object backup.ObjectDescriptor)(string,error){query:=url.Values{"uploads":[]string{""}};headers:=http.Header{"Content-Type":[]string{"application/octet-stream"},"X-Amz-Checksum-Algorithm":[]string{"SHA256"},"X-Amz-Meta-Sha256":[]string{object.Digest},"X-Amz-Meta-Size":[]string{strconv.FormatUint(object.Size,10)}};empty:=hashBytes(nil);response,err:=provider.request(ctx,binding,http.MethodPost,key,query,nil,0,empty,headers);if err!=nil{return "",err};defer response.Body.Close();if response.StatusCode<200||response.StatusCode>=300{return "",s3ResponseError(response)};var result struct{UploadID string `xml:"UploadId"`};if err=xml.NewDecoder(io.LimitReader(response.Body,1<<20)).Decode(&result);err!=nil||result.UploadID==""{return "",errors.Join(ErrIntegrity,err)};return result.UploadID,nil}
func (provider S3Provider)sourcePartDigest(ctx context.Context,object backup.ObjectDescriptor,effect string,offset,size uint64)(string,string,error){reader,err:=provider.Source.OpenObject(ctx,object,effect,offset);if err!=nil{return "","",err};defer reader.Close();hasher:=sha256.New();written,err:=io.Copy(hasher,io.LimitReader(reader,int64(size)+1));if err!=nil||uint64(written)!=size{return "","",errors.Join(ErrIntegrity,err)};sum:=hasher.Sum(nil);return hex.EncodeToString(sum),base64.StdEncoding.EncodeToString(sum),nil}
func (provider S3Provider)uploadPart(ctx context.Context,binding s3Binding,session UploadSession,object backup.ObjectDescriptor,effect string,number uint32,offset,size uint64,partDigest,checksum string)(string,error){reader,err:=provider.Source.OpenObject(ctx,object,effect,offset);if err!=nil{return "",err};defer reader.Close();query:=url.Values{"partNumber":[]string{strconv.FormatUint(uint64(number),10)},"uploadId":[]string{session.ProviderUploadID}};headers:=http.Header{"Content-Type":[]string{"application/octet-stream"},"X-Amz-Checksum-Sha256":[]string{checksum}};response,err:=provider.request(ctx,binding,http.MethodPut,session.ObjectKey,query,reader,int64(size),partDigest,headers);if err!=nil{return "",err};defer response.Body.Close();if response.StatusCode<200||response.StatusCode>=300{return "",s3ResponseError(response)};etag:=strings.Trim(response.Header.Get("ETag"),"\"");if etag==""{return "",ErrIntegrity};if remote:=response.Header.Get("X-Amz-Checksum-Sha256");remote!=""&&remote!=checksum{return "",ErrIntegrity};_,_=io.Copy(io.Discard,io.LimitReader(response.Body,64<<10));return etag,nil}
func (provider S3Provider)completeMultipart(ctx context.Context,binding s3Binding,session UploadSession)error{type completedPart struct{Number uint32 `xml:"PartNumber"`;ETag string `xml:"ETag"`;Checksum string `xml:"ChecksumSHA256"`};document:=struct{XMLName xml.Name `xml:"CompleteMultipartUpload"`;Parts []completedPart `xml:"Part"` }{};for _,part:=range sortedParts(session.Parts){decoded,err:=hex.DecodeString(part.Digest);if err!=nil{return ErrIntegrity};document.Parts=append(document.Parts,completedPart{part.Number,"\""+strings.Trim(part.ETag,"\"")+"\"",base64.StdEncoding.EncodeToString(decoded)})};payload,err:=xml.Marshal(document);if err!=nil{return err};query:=url.Values{"uploadId":[]string{session.ProviderUploadID}};response,err:=provider.request(ctx,binding,http.MethodPost,session.ObjectKey,query,strings.NewReader(string(payload)),int64(len(payload)),hashBytes(payload),http.Header{"Content-Type":[]string{"application/xml"}});if err!=nil{return err};defer response.Body.Close();body,readErr:=io.ReadAll(io.LimitReader(response.Body,1<<20));if readErr!=nil{return readErr};if response.StatusCode<200||response.StatusCode>=300||strings.Contains(string(body),"<Error>"){return fmt.Errorf("s3 multipart completion failed: status=%d body_digest=%s",response.StatusCode,hashBytes(body))};return nil}

func (provider S3Provider)head(ctx context.Context,binding s3Binding,key string)(s3ObjectInfo,error){response,err:=provider.request(ctx,binding,http.MethodHead,key,nil,nil,0,hashBytes(nil),nil);if err!=nil{return s3ObjectInfo{},err};defer response.Body.Close();if response.StatusCode==http.StatusNotFound{return s3ObjectInfo{},ErrNotFound};if response.StatusCode<200||response.StatusCode>=300{return s3ObjectInfo{},s3ResponseError(response)};size,err:=strconv.ParseUint(response.Header.Get("Content-Length"),10,64);if err!=nil{return s3ObjectInfo{},ErrIntegrity};return s3ObjectInfo{Size:size,Digest:strings.ToLower(response.Header.Get("X-Amz-Meta-Sha256")),ETag:strings.Trim(response.Header.Get("ETag"),"\""),ChecksumSHA256:response.Header.Get("X-Amz-Checksum-Sha256")},nil}
func (provider S3Provider)getBytes(ctx context.Context,binding s3Binding,key string,maximum uint64)([]byte,error){response,err:=provider.request(ctx,binding,http.MethodGet,key,nil,nil,0,hashBytes(nil),nil);if err!=nil{return nil,err};defer response.Body.Close();if response.StatusCode==http.StatusNotFound{return nil,ErrNotFound};if response.StatusCode<200||response.StatusCode>=300{return nil,s3ResponseError(response)};payload,err:=io.ReadAll(io.LimitReader(response.Body,int64(maximum)+1));if err!=nil||uint64(len(payload))>maximum{return nil,ErrIntegrity};return payload,nil}
func (provider S3Provider)verifyObject(ctx context.Context,binding s3Binding,key string,object backup.ObjectDescriptor)error{info,err:=provider.head(ctx,binding,key);if err!=nil{return err};if err=verifyS3Info(info,object);err!=nil{return err};response,err:=provider.request(ctx,binding,http.MethodGet,key,nil,nil,0,hashBytes(nil),nil);if err!=nil{return err};defer response.Body.Close();if response.StatusCode<200||response.StatusCode>=300{return s3ResponseError(response)};_,err=verifyReader(response.Body,object.Digest,object.Size);return err}
func (provider S3Provider)delete(ctx context.Context,binding s3Binding,key string)error{response,err:=provider.request(ctx,binding,http.MethodDelete,key,nil,nil,0,hashBytes(nil),nil);if err!=nil{return err};defer response.Body.Close();if response.StatusCode==http.StatusNotFound{return ErrNotFound};if response.StatusCode<200||response.StatusCode>=300{return s3ResponseError(response)};_,_=io.Copy(io.Discard,io.LimitReader(response.Body,64<<10));return nil}
func verifyS3Info(info s3ObjectInfo,object backup.ObjectDescriptor)error{if info.Size!=object.Size||info.Digest!=object.Digest{return ErrIntegrity};return nil}

func (provider S3Provider)request(ctx context.Context,binding s3Binding,method,key string,query url.Values,body io.Reader,length int64,payloadDigest string,headers http.Header)(*http.Response,error){targetURL,err:=s3ObjectURL(binding.target,key,query);if err!=nil{return nil,err};request,err:=http.NewRequestWithContext(ctx,method,targetURL.String(),body);if err!=nil{return nil,err};request.ContentLength=length;for name,values:=range headers{for _,value:=range values{request.Header.Add(name,value)}};if err=signS3Request(request,binding.target,binding.credentials,payloadDigest,provider.now());err!=nil{return nil,err};response,err:=binding.client.Do(request);if err!=nil{return nil,err};return response,nil}
func s3ObjectURL(target S3Target,key string,query url.Values)(*url.URL,error){if err:=target.Validate();err!=nil{return nil,err};if !safePrefix(key){return nil,ErrInvalid};endpoint,err:=url.Parse(target.Endpoint);if err!=nil{return nil,err};segments:=[]string{};if target.Addressing==AddressingVirtual{endpoint.Host=target.Bucket+"."+endpoint.Host}else{segments=append(segments,target.Bucket)};if target.Prefix!=""{segments=append(segments,target.Prefix)};segments=append(segments,key);cleaned:=path.Join(segments...);endpoint.Path="/"+cleaned;escaped:=make([]string,0,len(strings.Split(cleaned,"/")));for _,segment:=range strings.Split(cleaned,"/"){escaped=append(escaped,url.PathEscape(segment))};endpoint.RawPath="/"+strings.Join(escaped,"/");endpoint.RawQuery=canonicalS3Query(query);return endpoint,nil}
func s3ResponseError(response *http.Response)error{if response==nil{return ErrAmbiguous};body,_:=io.ReadAll(io.LimitReader(response.Body,64<<10));return fmt.Errorf("s3 request failed: status=%d response_digest=%s",response.StatusCode,hashBytes(body))}
func minUint64(left,right uint64)uint64{if left<right{return left};return right}
