package providers

import (
	"context"
	"errors"
	"io"
	"net"
	"net/url"
	"path"
	"strconv"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/backup"
)

// SFTPProvider stores immutable content-addressed objects over an SFTP client
// that is required to pin the configured host key. The connector deliberately
// exposes no remote command or shell facility.
type SFTPProvider struct{Endpoints map[backup.RepositoryID]SFTPEndpoint;Secrets SecretResolver;Connector SFTPConnector;Source ObjectSource;Now func()time.Time}
func (provider SFTPProvider)now()time.Time{if provider.Now!=nil{return provider.Now().UTC()};return time.Now().UTC()}
func (provider SFTPProvider)connect(ctx context.Context,spec backup.RepositorySpec)(SFTPEndpoint,SFTPClient,error){if err:=validateSpec(spec,backup.SFTP);err!=nil{return SFTPEndpoint{},nil,err};endpoint,ok:=provider.Endpoints[spec.Repository.ID];if !ok||provider.Secrets==nil||provider.Connector==nil{return SFTPEndpoint{},nil,ErrNotFound};if err:=endpoint.Validate();err!=nil{return SFTPEndpoint{},nil,err};if endpoint.CredentialRef!=spec.Repository.CredentialRef{return SFTPEndpoint{},nil,ErrInvalid};parsed,err:=url.Parse(spec.Repository.Endpoint);if err!=nil||parsed.Scheme!="sftp"||parsed.User!=nil||parsed.RawQuery!=""||parsed.Fragment!=""||parsed.Path!=endpoint.Root{return SFTPEndpoint{},nil,ErrInvalid};host,portText,err:=net.SplitHostPort(parsed.Host);if err!=nil||!strings.EqualFold(strings.Trim(host,"[]"),strings.Trim(endpoint.Host,"[]")){return SFTPEndpoint{},nil,ErrInvalid};port,err:=strconv.ParseUint(portText,10,16);if err!=nil||uint16(port)!=endpoint.Port{return SFTPEndpoint{},nil,ErrInvalid};credential,err:=provider.Secrets.ResolveBackupCredential(ctx,endpoint.CredentialRef,"sftp:"+string(endpoint.RepositoryID));if err!=nil{return SFTPEndpoint{},nil,errors.Join(ErrCredential,err)};defer clearBytes(credential);client,err:=provider.Connector.Connect(ctx,endpoint,credential);if err!=nil{return SFTPEndpoint{},nil,err};return endpoint,client,nil}

func (provider SFTPProvider)StageManifest(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,effect string)(string,error){if err:=validateManifest(manifest);err!=nil{return "",err};endpoint,client,err:=provider.connect(ctx,spec);if err!=nil{return "",err};defer client.Close();token:=stageToken(spec.Repository.ID,manifest.RecoveryPointID,effect);directory,err:=joinRemote(endpoint.Root,".staging/"+token);if err!=nil{return "",err};if err=ensureRemoteTree(ctx,client,endpoint.Root,".staging/"+token);err!=nil{return "",err};payload,err:=manifestBytes(manifest);if err!=nil{return "",err};if err=writeRemoteExclusiveOrEqual(ctx,client,path.Join(directory,"manifest.json"),payload,0600);err!=nil{return "",err};return token,nil}

func (provider SFTPProvider)StageObject(ctx context.Context,spec backup.RepositorySpec,staging string,object backup.ObjectDescriptor,effect string)(string,error){if provider.Source==nil||!safeID(staging)||validateObject(object)!=nil{return "",ErrInvalid};endpoint,client,err:=provider.connect(ctx,spec);if err!=nil{return "",err};defer client.Close();relative:=objectPath(object);finalPath,err:=joinRemote(endpoint.Root,relative);if err!=nil{return "",err};if err=ensureRemoteTree(ctx,client,endpoint.Root,path.Dir(relative));err!=nil{return "",err};if valid,verifyErr:=verifyRemoteObject(ctx,client,finalPath,object);verifyErr==nil&&valid{return relative,nil}else if verifyErr!=nil&&!errors.Is(verifyErr,ErrNotFound){return "",verifyErr};partial:=finalPath+".partial."+hashText(effect)[:20];offset:=uint64(0);info,statErr:=client.Stat(ctx,partial);if statErr==nil{if !info.Regular||info.Size>object.Size{_ = client.RemoveFile(ctx,partial);return "",ErrIntegrity};offset=info.Size}else if !errors.Is(statErr,ErrNotFound){return "",statErr};source,err:=provider.Source.OpenObject(ctx,object,effect,offset);if err!=nil{return "",err};defer source.Close();writer,err:=client.OpenWriter(ctx,partial,offset,0600);if err!=nil{return "",err};written,copyErr:=io.Copy(writer,io.LimitReader(source,int64(object.Size-offset)+1));syncErr:=writer.Sync();closeErr:=writer.Close();if copyErr!=nil||syncErr!=nil||closeErr!=nil||uint64(written)!=object.Size-offset{_ = client.RemoveFile(ctx,partial);return "",errors.Join(ErrIntegrity,copyErr,syncErr,closeErr)};valid,err:=verifyRemoteObject(ctx,client,partial,object);if err!=nil||!valid{_ = client.RemoveFile(ctx,partial);return "",errors.Join(ErrIntegrity,err)};if err=client.RenameNoReplace(ctx,partial,finalPath);err!=nil{if valid,verifyErr:=verifyRemoteObject(ctx,client,finalPath,object);verifyErr==nil&&valid{_ = client.RemoveFile(ctx,partial);return relative,nil};return "",err};return relative,nil}

func (provider SFTPProvider)Commit(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,staging,effect string)(backup.CopyReceipt,error){if validateManifest(manifest)!=nil||staging!=stageToken(spec.Repository.ID,manifest.RecoveryPointID,effect){return backup.CopyReceipt{},ErrInvalid};endpoint,client,err:=provider.connect(ctx,spec);if err!=nil{return backup.CopyReceipt{},err};defer client.Close();for _,artifact:=range manifest.Artifacts{for _,object:=range artifact.Objects{remote,joinErr:=joinRemote(endpoint.Root,objectPath(object));if joinErr!=nil{return backup.CopyReceipt{},joinErr};valid,verifyErr:=verifyRemoteObject(ctx,client,remote,object);if verifyErr!=nil||!valid{return backup.CopyReceipt{},errors.Join(ErrIntegrity,verifyErr)}}};pointRelative:="points/"+string(manifest.RecoveryPointID);if err=ensureRemoteTree(ctx,client,endpoint.Root,pointRelative);err!=nil{return backup.CopyReceipt{},err};point,err:=joinRemote(endpoint.Root,pointRelative);if err!=nil{return backup.CopyReceipt{},err};payload,err:=manifestBytes(manifest);if err!=nil{return backup.CopyReceipt{},err};if err=writeRemoteExclusiveOrEqual(ctx,client,path.Join(point,"manifest.json"),payload,0600);err!=nil{return backup.CopyReceipt{},err};marker,markerDigest,err:=commitBytes(manifest,spec.Repository.ID,effect,provider.now());if err!=nil{return backup.CopyReceipt{},err};if err=writeRemoteExclusiveOrEqual(ctx,client,path.Join(point,"COMMITTED"),marker,0600);err!=nil{return backup.CopyReceipt{},err};objects,bytes:=manifestTotals(manifest);return backup.CopyReceipt{ID:copyID(spec.Repository.ID,manifest.RecoveryPointID),RecoveryPointID:manifest.RecoveryPointID,RepositoryID:spec.Repository.ID,FailureDomain:spec.FailureDomain,Status:backup.CopyCommitted,CommitMarker:markerDigest,ManifestDigest:manifest.ManifestDigest,Objects:objects,Bytes:bytes},nil}

func (provider SFTPProvider)Verify(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,receipt backup.CopyReceipt)(backup.CopyReceipt,error){if receipt.RecoveryPointID!=manifest.RecoveryPointID||receipt.RepositoryID!=spec.Repository.ID||receipt.ManifestDigest!=manifest.ManifestDigest{return receipt,ErrIntegrity};endpoint,client,err:=provider.connect(ctx,spec);if err!=nil{return receipt,err};defer client.Close();point,err:=joinRemote(endpoint.Root,"points/"+string(manifest.RecoveryPointID));if err!=nil{return receipt,err};marker,err:=client.ReadFile(ctx,path.Join(point,"COMMITTED"),1<<20);if err!=nil{return receipt,err};stored,err:=client.ReadFile(ctx,path.Join(point,"manifest.json"),64<<20);if err!=nil{return receipt,err};expected,err:=manifestBytes(manifest);if err!=nil||!equalBytes(stored,expected)||hashBytes(marker)!=receipt.CommitMarker{return receipt,ErrIntegrity};for _,artifact:=range manifest.Artifacts{for _,object:=range artifact.Objects{remote,_:=joinRemote(endpoint.Root,objectPath(object));valid,verifyErr:=verifyRemoteObject(ctx,client,remote,object);if verifyErr!=nil||!valid{return receipt,errors.Join(ErrIntegrity,verifyErr)}}};receipt.Status=backup.CopyVerified;receipt.VerifiedAt=provider.now();return receipt,nil}

func (provider SFTPProvider)DeleteRecoveryPoint(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,effect string)error{endpoint,client,err:=provider.connect(ctx,spec);if err!=nil{return err};defer client.Close();point,err:=joinRemote(endpoint.Root,"points/"+string(manifest.RecoveryPointID));if err!=nil{return err};for _,leaf:=range []string{"COMMITTED","manifest.json"}{removeErr:=client.RemoveFile(ctx,path.Join(point,leaf));if removeErr!=nil&&!errors.Is(removeErr,ErrNotFound){return removeErr}};removeErr:=client.RemoveEmptyDirectory(ctx,point);if errors.Is(removeErr,ErrNotFound){return nil};return removeErr}
func (provider SFTPProvider)OpenCommittedObject(ctx context.Context,spec backup.RepositorySpec,manifest backup.RecoveryPointManifest,receipt backup.CopyReceipt,object backup.ObjectDescriptor)(backup.ReadCloser,error){endpoint,client,err:=provider.connect(ctx,spec);if err!=nil{return nil,err};if !receiptMatches(spec,manifest,receipt)||!objectInManifest(manifest,object){client.Close();return nil,ErrInvalid};point,err:=joinRemote(endpoint.Root,"points/"+string(manifest.RecoveryPointID));if err!=nil{client.Close();return nil,err};marker,err:=client.ReadFile(ctx,path.Join(point,"COMMITTED"),1<<20);if err!=nil||hashBytes(marker)!=receipt.CommitMarker{client.Close();return nil,ErrIntegrity};remote,err:=joinRemote(endpoint.Root,objectPath(object));if err!=nil{client.Close();return nil,err};info,err:=client.Stat(ctx,remote);if err!=nil||!info.Regular||info.Size!=object.Size{client.Close();return nil,errors.Join(ErrIntegrity,err)};reader,err:=client.OpenReader(ctx,remote,0);if err!=nil{client.Close();return nil,err};return newIntegrityReadCloser(&sftpClientReader{reader:reader,client:client},object.Digest,object.Size),nil}
type sftpClientReader struct{reader SFTPReader;client SFTPClient}
func (reader *sftpClientReader)Read(buffer []byte)(int,error){return reader.reader.Read(buffer)}
func (reader *sftpClientReader)Close()error{return errors.Join(reader.reader.Close(),reader.client.Close())}
func (provider SFTPProvider)ProbeRepository(ctx context.Context,spec backup.RepositorySpec,effect string)(RepositoryProbe,error){started:=provider.now();probe:=RepositoryProbe{RepositoryID:spec.Repository.ID,Kind:backup.SFTP,Health:RepositoryUnavailable,Capabilities:[]string{"content_addressed","commit_marker","host_key_pinned","resume","stream_restore"},ObservedAt:provider.now()};endpoint,client,err:=provider.connect(ctx,spec);if err!=nil{probe.DetailDigest=hashText(err.Error());return probe,err};defer client.Close();probePath,err:=joinRemote(endpoint.Root,".staging/probe-"+hashText(effect)[:32]);if err==nil{err=ensureRemoteTree(ctx,client,endpoint.Root,".staging")};if err==nil{payload:=[]byte(hashText(effect));err=writeRemoteExclusiveOrEqual(ctx,client,probePath,payload,0600);if err==nil{stored,readErr:=client.ReadFile(ctx,probePath,uint64(len(payload))+1);if readErr!=nil||!equalBytes(stored,payload){err=errors.Join(ErrIntegrity,readErr)}};_ = client.RemoveFile(ctx,probePath)};probe.Latency=provider.now().Sub(started);if err!=nil{probe.DetailDigest=hashText(err.Error());return probe,err};probe.Health=RepositoryHealthy;probe.DetailDigest=hashText(effect+"\x00sftp-probe-ok");return probe,nil}

func verifyRemoteObject(ctx context.Context,client SFTPClient,remote string,object backup.ObjectDescriptor)(bool,error){info,err:=client.Stat(ctx,remote);if err!=nil{return false,err};if !info.Regular||info.Size!=object.Size{return false,ErrIntegrity};reader,err:=client.OpenReader(ctx,remote,0);if err!=nil{return false,err};defer reader.Close();_,err=verifyReader(reader,object.Digest,object.Size);return err==nil,err}
func writeRemoteExclusiveOrEqual(ctx context.Context,client SFTPClient,remote string,payload []byte,mode uint32)error{err:=client.WriteFileExclusive(ctx,remote,payload,mode);if err==nil{return nil};existing,readErr:=client.ReadFile(ctx,remote,uint64(len(payload))+1);if readErr==nil&&equalBytes(existing,payload){return nil};if readErr!=nil&&!errors.Is(readErr,ErrNotFound){return errors.Join(err,readErr)};return ErrConflict}
func ensureRemoteTree(ctx context.Context,client SFTPClient,root,relative string)error{if !absoluteRemoteRoot(root)||!safePrefix(relative){return ErrInvalid};current:=root;for _,segment:=range strings.Split(relative,"/"){if segment==""||segment=="."||segment==".."{return ErrInvalid};current=path.Join(current,segment);if err:=client.EnsureDirectory(ctx,current,0700);err!=nil{return err}};return nil}
func clearBytes(value []byte){for index:=range value{value[index]=0}}
