package cyberpanel

import (
	"bufio"
	"context"
	"crypto/sha256"
	"crypto/tls"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"net"
	"strings"
	"sync"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/migration"
)

const ExtractorProtocolVersion uint32=1
const defaultMaximumRequestBytes=uint32(64<<10)
const defaultMaximumResponseBytes=uint32(48<<20)

type ExtractorOperation string
const(OperationDiscover ExtractorOperation="discover";OperationOpenChunk ExtractorOperation="open_chunk";OperationGeneration ExtractorOperation="generation";OperationQuiesce ExtractorOperation="quiesce";OperationUnquiesce ExtractorOperation="unquiesce";OperationFinalDelta ExtractorOperation="final_delta";OperationCommitSource ExtractorOperation="commit_source";OperationRollbackSource ExtractorOperation="rollback_source")

type ExtractorRequest struct { Version uint32 `json:"version"`; RequestID string `json:"request_id"`; Operation ExtractorOperation `json:"operation"`; MigrationID migration.ID `json:"migration_id"`; Digest string `json:"digest,omitempty"`; Offset uint64 `json:"offset,omitempty"`; Length uint64 `json:"length,omitempty"`; TargetPlanDigest string `json:"target_plan_digest,omitempty"`; TargetPlanApprovedAt *time.Time `json:"target_plan_approved_at,omitempty"`; ExpectedFence uint64 `json:"expected_fence,omitempty"`; Fence *migration.SourceFence `json:"fence,omitempty"`; BaseSource migration.SourceKind `json:"base_source,omitempty"` }
type ExtractorResponse struct { Version uint32 `json:"version"`; RequestID string `json:"request_id"`; Manifest *migration.Manifest `json:"manifest,omitempty"`; Generation uint64 `json:"generation,omitempty"`; Chunk []byte `json:"chunk,omitempty"`; Fence *migration.SourceFence `json:"fence,omitempty"`; ErrorCode string `json:"error_code,omitempty"`; ErrorMessage string `json:"error_message,omitempty"` }

type PeerAuthorizer interface { Authorize(context.Context,net.Conn)error }
type SessionGrantBinder interface { AuthorizeSession(context.Context,net.Conn,migration.ID)error }
type ScopedChunkSource interface { OpenChunkForMigration(context.Context,migration.ID,string,uint64,uint64)([]byte,error) }

type PinnedTLSAuthorizer struct { allowedSPKI map[string]struct{} }
func NewPinnedTLSAuthorizer(allowedSPKI []string)(*PinnedTLSAuthorizer,error){if len(allowedSPKI)==0{return nil,ErrInvalid};values:=make(map[string]struct{},len(allowedSPKI));for _,digest:=range allowedSPKI{if !isDigest(digest){return nil,ErrInvalid};values[digest]=struct{}{}};return &PinnedTLSAuthorizer{allowedSPKI:values},nil}
func(a *PinnedTLSAuthorizer)Authorize(ctx context.Context,connection net.Conn)error{if a==nil||ctx==nil||connection==nil{return ErrInvalid};tlsConnection,ok:=connection.(*tls.Conn);if !ok{return ErrDenied};if err:=tlsConnection.HandshakeContext(ctx);err!=nil{return ErrDenied};digest,err:=peerSPKIDigest(connection);if err!=nil{return ErrDenied};if _,allowed:=a.allowedSPKI[digest];!allowed{return ErrDenied};return nil}
func peerSPKIDigest(connection net.Conn)(string,error){tlsConnection,ok:=connection.(*tls.Conn);if !ok{return "",ErrDenied};state:=tlsConnection.ConnectionState();if !state.HandshakeComplete||len(state.VerifiedChains)==0||len(state.PeerCertificates)==0{return "",ErrDenied};sum:=sha256.Sum256(state.PeerCertificates[0].RawSubjectPublicKeyInfo);return hex.EncodeToString(sum[:]),nil}

type ServerConfig struct { Listener net.Listener; Source migration.SourceReader; Cutover migration.CutoverSource; Authorizer PeerAuthorizer; SessionGrants SessionGrantBinder; MaximumRequestBytes,MaximumResponseBytes uint32; MaximumConnections int; ReadTimeout,WriteTimeout time.Duration }
type Server struct { listener net.Listener; source migration.SourceReader; scopedSource ScopedChunkSource; cutover migration.CutoverSource; authorizer PeerAuthorizer; sessionGrants SessionGrantBinder; maximumRequestBytes,maximumResponseBytes uint32; semaphore chan struct{}; readTimeout,writeTimeout time.Duration; closeOnce sync.Once; closed chan struct{}; connectionMu sync.Mutex; connections map[net.Conn]struct{}; workers sync.WaitGroup }

func NewServer(config ServerConfig)(*Server,error){if config.Listener==nil||config.Source==nil||config.Authorizer==nil||config.SessionGrants==nil{return nil,ErrInvalid};scopedSource,ok:=config.Source.(ScopedChunkSource);if !ok{return nil,ErrInvalid};if config.MaximumRequestBytes==0{config.MaximumRequestBytes=defaultMaximumRequestBytes};if config.MaximumResponseBytes==0{config.MaximumResponseBytes=defaultMaximumResponseBytes};if config.MaximumRequestBytes<1024||config.MaximumResponseBytes<1<<20{return nil,ErrInvalid};if config.MaximumConnections==0{config.MaximumConnections=32};if config.MaximumConnections<1||config.MaximumConnections>4096{return nil,ErrInvalid};if config.ReadTimeout==0{config.ReadTimeout=30*time.Second};if config.WriteTimeout==0{config.WriteTimeout=2*time.Minute};return &Server{listener:config.Listener,source:config.Source,scopedSource:scopedSource,cutover:config.Cutover,authorizer:config.Authorizer,sessionGrants:config.SessionGrants,maximumRequestBytes:config.MaximumRequestBytes,maximumResponseBytes:config.MaximumResponseBytes,semaphore:make(chan struct{},config.MaximumConnections),readTimeout:config.ReadTimeout,writeTimeout:config.WriteTimeout,closed:make(chan struct{}),connections:map[net.Conn]struct{}{}},nil}

func(s *Server)Serve(ctx context.Context)error{if s==nil||ctx==nil{return ErrInvalid};go func(){select{case<-ctx.Done():s.Close();case<-s.closed:}}();for{connection,err:=s.listener.Accept();if err!=nil{select{case<-s.closed:return nil;default:return err}};select{case s.semaphore<-struct{}{}:if !s.register(connection){<-s.semaphore;_ = connection.Close();continue};go func(){defer func(){s.unregister(connection);<-s.semaphore}();s.serveConnection(ctx,connection)}();default:_=connection.Close()}}}
func(s *Server)Close()error{if s==nil{return nil};var err error;s.closeOnce.Do(func(){s.connectionMu.Lock();close(s.closed);err=s.listener.Close();for connection:=range s.connections{err=errors.Join(err,connection.Close())};s.connectionMu.Unlock();s.workers.Wait()});return err}
func(s *Server)register(connection net.Conn)bool{s.connectionMu.Lock();defer s.connectionMu.Unlock();select{case<-s.closed:return false;default:};s.connections[connection]=struct{}{};s.workers.Add(1);return true}
func(s *Server)unregister(connection net.Conn){s.connectionMu.Lock();delete(s.connections,connection);s.connectionMu.Unlock();s.workers.Done()}

func(s *Server)serveConnection(ctx context.Context,connection net.Conn){defer connection.Close();authCtx,cancel:=context.WithTimeout(ctx,10*time.Second);err:=s.authorizer.Authorize(authCtx,connection);cancel();if err!=nil{return};reader:=bufio.NewReaderSize(connection,int(s.maximumRequestBytes));writer:=bufio.NewWriterSize(connection,128<<10);var boundMigration migration.ID;for{_ = connection.SetReadDeadline(time.Now().Add(s.readTimeout));raw,err:=readFrame(reader,s.maximumRequestBytes);if errors.Is(err,io.EOF){return};if err!=nil{return};var request ExtractorRequest;if err:=decodeStrict(raw,&request);err!=nil{return};if request.Version!=ExtractorProtocolVersion||!validRequestID(request.RequestID)||!request.MigrationID.Valid(){return};if boundMigration!=""&&request.MigrationID!=boundMigration{return};grantCtx,grantCancel:=context.WithTimeout(ctx,10*time.Second);err=s.sessionGrants.AuthorizeSession(grantCtx,connection,request.MigrationID);grantCancel();if err!=nil{return};if boundMigration==""{boundMigration=request.MigrationID};requestCtx,requestCancel:=context.WithTimeout(ctx,s.writeTimeout);response:=s.execute(requestCtx,request);requestCancel();encoded,err:=json.Marshal(response);if err!=nil||uint32(len(encoded))>s.maximumResponseBytes{return};_ = connection.SetWriteDeadline(time.Now().Add(s.writeTimeout));if err:=writeFrame(writer,encoded);err!=nil{return};if err:=writer.Flush();err!=nil{return}}}

func(s *Server)execute(ctx context.Context,request ExtractorRequest)ExtractorResponse{response:=ExtractorResponse{Version:ExtractorProtocolVersion,RequestID:request.RequestID};if request.Version!=ExtractorProtocolVersion||!validRequestID(request.RequestID)||!request.MigrationID.Valid(){response.ErrorCode="INVALID_REQUEST";response.ErrorMessage="request rejected";return response};var err error;switch request.Operation{case OperationDiscover:if !request.sourceReadFieldsOnly(){err=ErrInvalid;break};var manifest migration.Manifest;manifest,err=s.source.Discover(ctx,request.MigrationID);if err==nil{response.Manifest=&manifest};case OperationOpenChunk:if !request.chunkFieldsOnly()||!isDigest(request.Digest)||request.Length==0||request.Length>16<<20{err=ErrInvalid;break};response.Chunk,err=s.scopedSource.OpenChunkForMigration(ctx,request.MigrationID,request.Digest,request.Offset,request.Length);case OperationGeneration:if !request.sourceReadFieldsOnly(){err=ErrInvalid;break};response.Generation,err=s.source.Generation(ctx,request.MigrationID);case OperationQuiesce:if s.cutover==nil{err=ErrDenied;break};if request.Digest!=""||request.Offset!=0||request.Length!=0||!isDigest(request.TargetPlanDigest)||request.TargetPlanApprovedAt==nil||request.TargetPlanApprovedAt.IsZero()||request.ExpectedFence==0||request.Fence!=nil||request.BaseSource!=""{err=ErrInvalid;break};plan:=migration.Plan{MigrationID:request.MigrationID,DryRunDigest:request.TargetPlanDigest,ApprovedAt:request.TargetPlanApprovedAt};var fence migration.SourceFence;fence,err=s.cutover.Quiesce(ctx,request.MigrationID,plan,request.ExpectedFence);if err==nil{response.Fence=&fence};case OperationUnquiesce,OperationCommitSource,OperationRollbackSource:if s.cutover==nil{err=ErrDenied;break};if !request.fenceFieldsOnly(){err=ErrInvalid;break};switch request.Operation{case OperationUnquiesce:err=s.cutover.Unquiesce(ctx,*request.Fence);case OperationCommitSource:err=s.cutover.CommitSource(ctx,*request.Fence);case OperationRollbackSource:err=s.cutover.RollbackSource(ctx,*request.Fence)};case OperationFinalDelta:if s.cutover==nil{err=ErrDenied;break};if !request.finalDeltaFieldsOnly(){err=ErrInvalid;break};base:=migration.Manifest{MigrationID:request.MigrationID,Source:request.BaseSource};var manifest migration.Manifest;manifest,err=s.cutover.FinalDelta(ctx,*request.Fence,base);if err==nil{response.Manifest=&manifest};default:err=ErrInvalid};if err!=nil{response.ErrorCode=wireErrorCode(err);response.ErrorMessage="extractor operation failed"};return response}

func(r ExtractorRequest)sourceReadFieldsOnly()bool{return r.Digest==""&&r.Offset==0&&r.Length==0&&r.TargetPlanDigest==""&&r.TargetPlanApprovedAt==nil&&r.ExpectedFence==0&&r.Fence==nil&&r.BaseSource==""}
func(r ExtractorRequest)chunkFieldsOnly()bool{return r.TargetPlanDigest==""&&r.TargetPlanApprovedAt==nil&&r.ExpectedFence==0&&r.Fence==nil&&r.BaseSource==""}
func(r ExtractorRequest)fenceFieldsOnly()bool{return r.Digest==""&&r.Offset==0&&r.Length==0&&r.TargetPlanDigest==""&&r.TargetPlanApprovedAt==nil&&r.ExpectedFence==0&&r.Fence!=nil&&r.Fence.MigrationID==r.MigrationID&&r.BaseSource==""}
func(r ExtractorRequest)finalDeltaFieldsOnly()bool{return r.Digest==""&&r.Offset==0&&r.Length==0&&r.TargetPlanDigest==""&&r.TargetPlanApprovedAt==nil&&r.ExpectedFence==0&&r.Fence!=nil&&r.Fence.MigrationID==r.MigrationID&&(r.BaseSource==migration.SourceCyberPanel||r.BaseSource==migration.SourceCPanel)}

type DialContext func(context.Context)(net.Conn,error)
type Client struct { dial DialContext; maximumResponseBytes uint32; timeout time.Duration; mu sync.RWMutex; chunkMigrations map[string][]migration.ID }
func NewClient(dial DialContext,maximumResponseBytes uint32,timeout time.Duration)(*Client,error){if dial==nil{return nil,ErrInvalid};if maximumResponseBytes==0{maximumResponseBytes=defaultMaximumResponseBytes};if maximumResponseBytes<1<<20{return nil,ErrInvalid};if timeout==0{timeout=2*time.Minute};return &Client{dial:dial,maximumResponseBytes:maximumResponseBytes,timeout:timeout,chunkMigrations:map[string][]migration.ID{}},nil}
func(c *Client)Discover(ctx context.Context,id migration.ID)(migration.Manifest,error){if c==nil||ctx==nil||!id.Valid(){return migration.Manifest{},ErrInvalid};response,err:=c.call(ctx,ExtractorRequest{Version:ExtractorProtocolVersion,RequestID:newRequestID(id,"discover"),Operation:OperationDiscover,MigrationID:id});if err!=nil{return migration.Manifest{},err};if response.Manifest==nil||response.Generation!=0||len(response.Chunk)!=0||response.Fence!=nil{return migration.Manifest{},ErrInvalid};c.mu.Lock();for _,chunk:=range response.Manifest.Chunks{values:=c.chunkMigrations[chunk.Digest];filtered:=make([]migration.ID,0,len(values)+1);filtered=append(filtered,id);for _,existing:=range values{if existing!=id{filtered=append(filtered,existing)}};if len(filtered)>64{filtered=filtered[:64]};c.chunkMigrations[chunk.Digest]=filtered};c.mu.Unlock();return *response.Manifest,nil}
func(c *Client)OpenChunk(ctx context.Context,digest string,offset,length uint64)([]byte,error){if c==nil||ctx==nil||!isDigest(digest)||length==0||length>16<<20{return nil,ErrInvalid};c.mu.RLock();migrationIDs:=append([]migration.ID(nil),c.chunkMigrations[digest]...);c.mu.RUnlock();if len(migrationIDs)==0{return nil,ErrDenied};var last error;for _,migrationID:=range migrationIDs{response,err:=c.call(ctx,ExtractorRequest{Version:ExtractorProtocolVersion,RequestID:newRequestID(migrationID,digest),Operation:OperationOpenChunk,MigrationID:migrationID,Digest:digest,Offset:offset,Length:length});if err==nil{if response.Manifest!=nil||response.Generation!=0||response.Fence!=nil||uint64(len(response.Chunk))!=length{return nil,ErrInvalid};return response.Chunk,nil};last=err;if !errors.Is(err,ErrDenied)&&!errors.Is(err,migration.ErrNotFound){return nil,err}};return nil,last}
func(c *Client)Generation(ctx context.Context,id migration.ID)(uint64,error){if c==nil||ctx==nil||!id.Valid(){return 0,ErrInvalid};response,err:=c.call(ctx,ExtractorRequest{Version:ExtractorProtocolVersion,RequestID:newRequestID(id,"generation"),Operation:OperationGeneration,MigrationID:id});if err!=nil{return 0,err};if response.Generation==0||response.Manifest!=nil||len(response.Chunk)!=0||response.Fence!=nil{return 0,ErrInvalid};return response.Generation,nil}
func(c *Client)Quiesce(ctx context.Context,id migration.ID,plan migration.Plan,expectedFence uint64)(migration.SourceFence,error){if c==nil||ctx==nil||!id.Valid()||plan.MigrationID!=id||!isDigest(plan.DryRunDigest)||plan.ApprovedAt==nil||plan.ApprovedAt.IsZero()||expectedFence==0{return migration.SourceFence{},ErrInvalid};approvedAt:=plan.ApprovedAt.UTC();response,err:=c.call(ctx,ExtractorRequest{Version:ExtractorProtocolVersion,RequestID:newRequestID(id,"quiesce"),Operation:OperationQuiesce,MigrationID:id,TargetPlanDigest:plan.DryRunDigest,TargetPlanApprovedAt:&approvedAt,ExpectedFence:expectedFence});if err!=nil{return migration.SourceFence{},err};if response.Fence==nil||response.Fence.MigrationID!=id||response.Manifest!=nil||response.Generation!=0||len(response.Chunk)!=0{return migration.SourceFence{},ErrInvalid};return *response.Fence,nil}
func(c *Client)Unquiesce(ctx context.Context,fence migration.SourceFence)error{return c.callFence(ctx,OperationUnquiesce,fence)}
func(c *Client)CommitSource(ctx context.Context,fence migration.SourceFence)error{return c.callFence(ctx,OperationCommitSource,fence)}
func(c *Client)RollbackSource(ctx context.Context,fence migration.SourceFence)error{return c.callFence(ctx,OperationRollbackSource,fence)}
func(c *Client)FinalDelta(ctx context.Context,fence migration.SourceFence,base migration.Manifest)(migration.Manifest,error){if c==nil||ctx==nil||base.MigrationID!=fence.MigrationID||(base.Source!=migration.SourceCyberPanel&&base.Source!=migration.SourceCPanel){return migration.Manifest{},ErrInvalid};response,err:=c.call(ctx,ExtractorRequest{Version:ExtractorProtocolVersion,RequestID:newRequestID(fence.MigrationID,"final-delta"),Operation:OperationFinalDelta,MigrationID:fence.MigrationID,Fence:&fence,BaseSource:base.Source});if err!=nil{return migration.Manifest{},err};if response.Manifest==nil||response.Generation!=0||len(response.Chunk)!=0||response.Fence!=nil{return migration.Manifest{},ErrInvalid};return *response.Manifest,nil}
func(c *Client)callFence(ctx context.Context,operation ExtractorOperation,fence migration.SourceFence)error{if c==nil||ctx==nil||!fence.MigrationID.Valid(){return ErrInvalid};if operation!=OperationUnquiesce&&operation!=OperationCommitSource&&operation!=OperationRollbackSource{return ErrInvalid};response,err:=c.call(ctx,ExtractorRequest{Version:ExtractorProtocolVersion,RequestID:newRequestID(fence.MigrationID,string(operation)),Operation:operation,MigrationID:fence.MigrationID,Fence:&fence});if err!=nil{return err};if response.Manifest!=nil||response.Generation!=0||len(response.Chunk)!=0||response.Fence!=nil{return ErrInvalid};return nil}
func(c *Client)call(ctx context.Context,request ExtractorRequest)(ExtractorResponse,error){if c==nil||ctx==nil{return ExtractorResponse{},ErrInvalid};callCtx,cancel:=context.WithTimeout(ctx,c.timeout);defer cancel();connection,err:=c.dial(callCtx);if err!=nil{return ExtractorResponse{},err};defer connection.Close();deadline,_:=callCtx.Deadline();_ = connection.SetDeadline(deadline);raw,err:=json.Marshal(request);if err!=nil||len(raw)>int(defaultMaximumRequestBytes){return ExtractorResponse{},ErrInvalid};writer:=bufio.NewWriterSize(connection,128<<10);if err:=writeFrame(writer,raw);err!=nil{return ExtractorResponse{},err};if err:=writer.Flush();err!=nil{return ExtractorResponse{},err};reader:=bufio.NewReaderSize(connection,int(c.maximumResponseBytes));encoded,err:=readFrame(reader,c.maximumResponseBytes);if err!=nil{return ExtractorResponse{},err};var response ExtractorResponse;if err:=decodeStrict(encoded,&response);err!=nil{return ExtractorResponse{},err};if response.Version!=ExtractorProtocolVersion||response.RequestID!=request.RequestID{return ExtractorResponse{},ErrInvalid};if response.ErrorCode!=""{return ExtractorResponse{},wireError(response.ErrorCode)};return response,nil}

func readFrame(reader io.Reader,maximum uint32)([]byte,error){var header [4]byte;if _,err:=io.ReadFull(reader,header[:]);err!=nil{return nil,err};length:=binary.BigEndian.Uint32(header[:]);if length==0||length>maximum{return nil,ErrInvalid};value:=make([]byte,length);_,err:=io.ReadFull(reader,value);return value,err}
func writeFrame(writer io.Writer,value []byte)error{if len(value)==0||uint64(len(value))>1<<32-1{return ErrInvalid};var header [4]byte;binary.BigEndian.PutUint32(header[:],uint32(len(value)));if _,err:=writer.Write(header[:]);err!=nil{return err};count,err:=writer.Write(value);if err!=nil{return err};if count!=len(value){return io.ErrShortWrite};return nil}
func decodeStrict(raw []byte,target any)error{decoder:=json.NewDecoder(strings.NewReader(string(raw)));decoder.DisallowUnknownFields();if err:=decoder.Decode(target);err!=nil{return ErrInvalid};var trailing any;if err:=decoder.Decode(&trailing);!errors.Is(err,io.EOF){return ErrInvalid};return nil}
func validRequestID(value string)bool{return validSourceID(value)&&len(value)<=96}
func newRequestID(id migration.ID,purpose string)string{sum:=sha256Text(id.String()+"\x00"+purpose+"\x00"+time.Now().UTC().Format(time.RFC3339Nano));return"req_"+sum[:32]}
func sha256Text(value string)string{return digestText(value)}
func wireErrorCode(err error)string{switch{case errors.Is(err,migration.ErrNotFound):return"NOT_FOUND";case errors.Is(err,migration.ErrCapacity):return"CAPACITY";case errors.Is(err,ErrDenied),errors.Is(err,migration.ErrBlocked):return"DENIED";case errors.Is(err,ErrChanged),errors.Is(err,migration.ErrConflict):return"CHANGED";default:return"FAILED"}}
func wireError(code string)error{switch code{case"NOT_FOUND":return migration.ErrNotFound;case"CAPACITY":return migration.ErrCapacity;case"DENIED":return ErrDenied;case"CHANGED":return ErrChanged;default:return errors.New("extractor: remote operation failed")}}

var _ migration.SourceReader=(*Client)(nil)
var _ migration.CutoverSource=(*Client)(nil)
