package containers

import (
	"context"
	"crypto/subtle"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"net/netip"
	"reflect"
	"sort"
	"strings"
	"time"
)

type PolicyEngine interface{EvaluateImage(context.Context,ID,ImageReference)(ImagePolicyReceipt,error);AuthorizeTier(context.Context,Grant,RuntimeTier,string)error;ValidateWorkload(context.Context,ID,RuntimeTier,WorkloadSpec)error;ValidateExposure(context.Context,ID,Exposure)error}
type RouteCoordinator interface{Prepare(context.Context,Exposure)(uint64,error);Commit(context.Context,Exposure,uint64)(uint64,error);Rollback(context.Context,Exposure,uint64)error}
type BackupCoordinator interface{SnapshotVolumes(context.Context,ID,[]ID)(string,error);RestoreVolumes(context.Context,string,[]ID)error}
type Service struct{repository Repository;broker Broker;policy PolicyEngine;routes RouteCoordinator;backups BackupCoordinator;clock func()time.Time}
func NewService(repository Repository,broker Broker,policy PolicyEngine,routes RouteCoordinator,backups BackupCoordinator)(*Service,error){if nilValue(repository)||nilValue(broker)||nilValue(policy)||nilValue(routes)||nilValue(backups){return nil,ErrInvalid};return &Service{repository:repository,broker:broker,policy:policy,routes:routes,backups:backups,clock:time.Now},nil}

type CommandMeta struct{CommandID string;Grant Grant;ExpectedGeneration uint64;Fence FenceToken}
func(m CommandMeta)Validate(operation string,resource ID,now time.Time)error{if m.CommandID==""||len(m.CommandID)>160||m.Fence==0||!m.Grant.TenantID.Valid()||m.Grant.ResourceID!=resource||m.Grant.Operation!=operation||m.Grant.AuthzEpoch==0||!now.Before(m.Grant.ExpiresAt)||len(m.Grant.Digest)!=64{return ErrForbidden};return nil}
type Result struct{EffectID EffectID;Status string;ResourceID ID;Generation uint64;Receipt any}

type PullImageCommand struct{Meta CommandMeta;ImageID ID;RegistryCredentialID ID;Registry,Repository,Tag,Platform string}
func(s *Service)PullImage(ctx context.Context,command PullImageCommand)(Image,Result,error){now:=s.clock().UTC();if err:=command.Meta.Validate("image.pull",command.ImageID,now);err!=nil{return Image{},Result{},err};effect,digest,operation,existing,err:=s.operation(ctx,command.Meta,command.ImageID,command);if err!=nil||existing{return imageFromOperation(operation),resultFromOperation(operation),err};reference,err:=s.broker.ResolveImage(ctx,ResolveImageRequest{EffectID:effect,Grant:command.Meta.Grant,RegistryCredentialID:command.RegistryCredentialID,Registry:command.Registry,Repository:command.Repository,Tag:command.Tag,Platform:command.Platform});if err!=nil{return Image{},s.ambiguous(ctx,operation,nil,err)};policy,err:=s.policy.EvaluateImage(ctx,command.Meta.Grant.TenantID,reference);if err!=nil||policy.Verdict==PolicyDenied{return Image{},s.reject(ctx,operation,nil,errors.Join(ErrPolicy,err))};image:=Image{ID:command.ImageID,TenantID:command.Meta.Grant.TenantID,Reference:reference,ManifestDigest:reference.Digest,PolicyVerdict:policy.Verdict,State:ImageResolving,Generation:1,PulledAt:now};operation.CommandDigest=digest;admitted,err:=s.repository.Admit(ctx,operation,image,0);if err!=nil{return Image{},Result{},err};if !admitted{return imageFromOperation(operation),resultFromOperation(operation),nil};receipt,err:=s.broker.PullImage(ctx,PullImageRequest{EffectID:effect,Grant:command.Meta.Grant,Image:reference,RegistryCredentialID:command.RegistryCredentialID,Policy:policy,Fence:command.Meta.Fence});if err!=nil||receipt.Outcome!="confirmed"{return image,s.ambiguous(ctx,operation,image,err)};image.State=ImageReady;image.SizeBytes=receipt.Bytes;image.SBOMDigest=policy.SBOMDigest;image.SignatureDigest=policy.SignatureDigest;image.VulnerabilityDigest=policy.VulnerabilityDigest;image.VerifiedAt=s.clock().UTC();if err=s.repository.Complete(ctx,effect,"applied",image,receipt);err!=nil{return image,Result{EffectID:effect,Status:"ambiguous",ResourceID:image.ID,Generation:image.Generation,Receipt:receipt},err};return image,Result{EffectID:effect,Status:"applied",ResourceID:image.ID,Generation:image.Generation,Receipt:receipt},nil}

type EnsureVolumeCommand struct{Meta CommandMeta;VolumeID ID;Name,Class string;Tier RuntimeTier;QuotaBytes,InodeLimit uint64}
func(s *Service)EnsureVolume(ctx context.Context,command EnsureVolumeCommand)(Volume,Result,error){now:=s.clock().UTC();if err:=command.Meta.Validate("volume.ensure",command.VolumeID,now);err!=nil{return Volume{},Result{},err};if command.QuotaBytes==0||command.InodeLimit==0||strings.TrimSpace(command.Name)==""{return Volume{},Result{},ErrInvalid};effect,digest,operation,existing,err:=s.operation(ctx,command.Meta,command.VolumeID,command);if err!=nil||existing{return Volume{},resultFromOperation(operation),err};volume:=Volume{ID:command.VolumeID,TenantID:command.Meta.Grant.TenantID,Name:command.Name,Class:command.Class,QuotaBytes:command.QuotaBytes,InodeLimit:command.InodeLimit,State:"creating",Generation:command.Meta.ExpectedGeneration+1,CreatedAt:now,UpdatedAt:now};operation.CommandDigest=digest;admitted,err:=s.repository.Admit(ctx,operation,volume,command.Meta.ExpectedGeneration);if err!=nil{return Volume{},Result{},err};if !admitted{return volume,resultFromOperation(operation),nil};receipt,err:=s.broker.EnsureVolume(ctx,VolumeMutationRequest{EffectID:effect,Grant:command.Meta.Grant,VolumeID:volume.ID,ExpectedGeneration:command.Meta.ExpectedGeneration,QuotaBytes:volume.QuotaBytes,InodeLimit:volume.InodeLimit,Class:volume.Class,Fence:command.Meta.Fence});if err!=nil||receipt.Outcome!="confirmed"{return volume,s.ambiguous(ctx,operation,volume,err)};volume.State="ready";volume.UpdatedAt=s.clock().UTC();if err=s.repository.Complete(ctx,effect,"applied",volume,receipt);err!=nil{return volume,Result{EffectID:effect,Status:"ambiguous",ResourceID:volume.ID,Generation:volume.Generation,Receipt:receipt},err};return volume,Result{EffectID:effect,Status:"applied",ResourceID:volume.ID,Generation:volume.Generation,Receipt:receipt},nil}

type EnsureNetworkCommand struct{Meta CommandMeta;NetworkID ID;Name string;Tier RuntimeTier;IPv4,IPv6 netip.Prefix;Internal bool;DNSPolicy string}
func(s *Service)EnsureNetwork(ctx context.Context,command EnsureNetworkCommand)(Network,Result,error){now:=s.clock().UTC();if err:=command.Meta.Validate("network.ensure",command.NetworkID,now);err!=nil{return Network{},Result{},err};if strings.TrimSpace(command.Name)==""||(!command.IPv4.IsValid()&&!command.IPv6.IsValid()){return Network{},Result{},ErrInvalid};effect,digest,operation,existing,err:=s.operation(ctx,command.Meta,command.NetworkID,command);if err!=nil||existing{return Network{},resultFromOperation(operation),err};network:=Network{ID:command.NetworkID,TenantID:command.Meta.Grant.TenantID,Name:command.Name,IPv4:command.IPv4,IPv6:command.IPv6,Internal:command.Internal,DNSPolicy:command.DNSPolicy,State:"creating",Generation:command.Meta.ExpectedGeneration+1};operation.CommandDigest=digest;admitted,err:=s.repository.Admit(ctx,operation,network,command.Meta.ExpectedGeneration);if err!=nil{return Network{},Result{},err};if !admitted{return network,resultFromOperation(operation),nil};receipt,err:=s.broker.EnsureNetwork(ctx,NetworkMutationRequest{EffectID:effect,Grant:command.Meta.Grant,NetworkID:network.ID,ExpectedGeneration:command.Meta.ExpectedGeneration,IPv4:network.IPv4,IPv6:network.IPv6,Internal:network.Internal,DNSPolicy:network.DNSPolicy,Fence:command.Meta.Fence});if err!=nil||receipt.Outcome!="confirmed"{return network,s.ambiguous(ctx,operation,network,err)};network.State="ready";if err=s.repository.Complete(ctx,effect,"applied",network,receipt);err!=nil{return network,Result{EffectID:effect,Status:"ambiguous",ResourceID:network.ID,Generation:network.Generation,Receipt:receipt},err};return network,Result{EffectID:effect,Status:"applied",ResourceID:network.ID,Generation:network.Generation,Receipt:receipt},nil}

type ApplyWorkloadCommand struct{Meta CommandMeta;WorkloadID,ProjectID,SiteID ID;Name string;Tier RuntimeTier;Spec WorkloadSpec}
func(s *Service)ApplyWorkload(ctx context.Context,command ApplyWorkloadCommand)(Workload,Result,error){now:=s.clock().UTC();if err:=command.Meta.Validate("workload.apply",command.WorkloadID,now);err!=nil{return Workload{},Result{},err};if err:=s.policy.AuthorizeTier(ctx,command.Meta.Grant,command.Tier,"apply");err!=nil{return Workload{},Result{},err};if err:=command.Spec.Validate(command.Tier);err!=nil{return Workload{},Result{},err};if err:=s.policy.ValidateWorkload(ctx,command.Meta.Grant.TenantID,command.Tier,command.Spec);err!=nil{return Workload{},Result{},err};effect,digest,operation,existing,err:=s.operation(ctx,command.Meta,command.WorkloadID,command);if err!=nil||existing{return Workload{},resultFromOperation(operation),err};specDigest:=digestValue(command.Spec);workload:=Workload{ID:command.WorkloadID,TenantID:command.Meta.Grant.TenantID,ProjectID:command.ProjectID,SiteID:command.SiteID,Name:strings.TrimSpace(command.Name),Tier:command.Tier,Spec:command.Spec,DesiredLifecycle:LifecycleRunning,ObservedLifecycle:LifecyclePending,SpecDigest:specDigest,Generation:command.Meta.ExpectedGeneration+1,CreatedAt:now,UpdatedAt:now};if previous,loadErr:=s.repository.Workload(ctx,workload.TenantID,workload.ID);loadErr==nil{workload.CreatedAt=previous.CreatedAt;workload.ObservedLifecycle=previous.ObservedLifecycle;workload.ObservedGeneration=previous.ObservedGeneration;workload.RuntimeObjectID=previous.RuntimeObjectID;workload.RestartCount=previous.RestartCount};if err=workload.Validate();err!=nil{return Workload{},Result{},err};operation.CommandDigest=digest;admitted,err:=s.repository.Admit(ctx,operation,workload,command.Meta.ExpectedGeneration);if err!=nil{return Workload{},Result{},err};if !admitted{return workload,resultFromOperation(operation),nil};request:=WorkloadMutationRequest{EffectID:effect,Grant:command.Meta.Grant,WorkloadID:workload.ID,ExpectedGeneration:command.Meta.ExpectedGeneration,Tier:workload.Tier,Spec:workload.Spec,SpecDigest:workload.SpecDigest,Fence:command.Meta.Fence};receipt,err:=s.broker.ApplyWorkload(ctx,request);if err!=nil||receipt.Outcome!="confirmed"||receipt.ResourceID!=workload.ID||receipt.SpecDigest!=workload.SpecDigest{return workload,s.ambiguous(ctx,operation,workload,err)};workload.RuntimeObjectID=receipt.RuntimeObjectID;workload.ObservedDigest=receipt.ObservedDigest;workload.ObservedLifecycle=receipt.Lifecycle;workload.ObservedGeneration=workload.Generation;workload.UpdatedAt=s.clock().UTC();if err=s.repository.Complete(ctx,effect,"applied",workload,receipt);err!=nil{return workload,Result{EffectID:effect,Status:"ambiguous",ResourceID:workload.ID,Generation:workload.Generation,Receipt:receipt},err};return workload,Result{EffectID:effect,Status:"applied",ResourceID:workload.ID,Generation:workload.Generation,Receipt:receipt},nil}

type LifecycleCommand struct{Meta CommandMeta;WorkloadID ID;Lifecycle Lifecycle;CommitAuthorizationDigest string}
func(s *Service)SetLifecycle(ctx context.Context,command LifecycleCommand)(Workload,Result,error){now:=s.clock().UTC();if err:=command.Meta.Validate("workload.lifecycle",command.WorkloadID,now);err!=nil{return Workload{},Result{},err};if command.Lifecycle!=LifecycleRunning&&command.Lifecycle!=LifecycleStopped&&command.Lifecycle!=LifecyclePaused&&command.Lifecycle!=LifecycleDeleting{return Workload{},Result{},ErrInvalid};workload,err:=s.repository.Workload(ctx,command.Meta.Grant.TenantID,command.WorkloadID);if err!=nil{return Workload{},Result{},err};if workload.Generation!=command.Meta.ExpectedGeneration{return Workload{},Result{},ErrStale};effect,digest,operation,existing,err:=s.operation(ctx,command.Meta,command.WorkloadID,command);if err!=nil||existing{return workload,resultFromOperation(operation),err};workload.DesiredLifecycle=command.Lifecycle;workload.Generation++;workload.UpdatedAt=now;operation.CommandDigest=digest;admitted,err:=s.repository.Admit(ctx,operation,workload,command.Meta.ExpectedGeneration);if err!=nil{return workload,Result{},err};if !admitted{return workload,resultFromOperation(operation),nil};receipt,err:=s.broker.SetLifecycle(ctx,WorkloadLifecycleRequest{EffectID:effect,Grant:command.Meta.Grant,WorkloadID:workload.ID,ExpectedGeneration:command.Meta.ExpectedGeneration,Lifecycle:command.Lifecycle,Fence:command.Meta.Fence,CommitAuthorizationDigest:command.CommitAuthorizationDigest});if err!=nil||receipt.Outcome!="confirmed"{return workload,s.ambiguous(ctx,operation,workload,err)};workload.ObservedLifecycle=receipt.Lifecycle;workload.ObservedGeneration=workload.Generation;workload.ObservedDigest=receipt.ObservedDigest;if command.Lifecycle==LifecycleDeleting{workload.DesiredLifecycle=LifecycleDeleted;workload.ObservedLifecycle=LifecycleDeleted;deleted:=s.clock().UTC();workload.DeletedAt=&deleted};if err=s.repository.Complete(ctx,effect,"applied",workload,receipt);err!=nil{return workload,Result{EffectID:effect,Status:"ambiguous",ResourceID:workload.ID,Generation:workload.Generation,Receipt:receipt},err};return workload,Result{EffectID:effect,Status:"applied",ResourceID:workload.ID,Generation:workload.Generation,Receipt:receipt},nil}

type ApplyExposureCommand struct{Meta CommandMeta;Exposure Exposure}
func(s *Service)ApplyExposure(ctx context.Context,command ApplyExposureCommand)(Exposure,Result,error){now:=s.clock().UTC();command.Exposure.TenantID=command.Meta.Grant.TenantID;if err:=command.Meta.Validate("exposure.apply",command.Exposure.ID,now);err!=nil{return Exposure{},Result{},err};command.Exposure.Generation=command.Meta.ExpectedGeneration+1;command.Exposure.State="preparing";if err:=s.policy.ValidateExposure(ctx,command.Meta.Grant.TenantID,command.Exposure);err!=nil{return Exposure{},Result{},err};workload,err:=s.repository.Workload(ctx,command.Exposure.TenantID,command.Exposure.WorkloadID);if err!=nil{return Exposure{},Result{},err};if workload.ObservedLifecycle!=LifecycleRunning{return Exposure{},Result{},ErrConflict};effect,digest,operation,existing,err:=s.operation(ctx,command.Meta,command.Exposure.ID,command);if err!=nil||existing{return command.Exposure,resultFromOperation(operation),err};operation.CommandDigest=digest;admitted,err:=s.repository.Admit(ctx,operation,command.Exposure,command.Meta.ExpectedGeneration);if err!=nil{return command.Exposure,Result{},err};if !admitted{return command.Exposure,resultFromOperation(operation),nil};routeGeneration,err:=s.routes.Prepare(ctx,command.Exposure);if err!=nil{return command.Exposure,s.reject(ctx,operation,command.Exposure,err)};request:=ExposureMutationRequest{EffectID:effect,Grant:command.Meta.Grant,Exposure:command.Exposure,ExpectedGeneration:command.Meta.ExpectedGeneration,Fence:command.Meta.Fence};receipt,err:=s.broker.ApplyExposure(ctx,request);if err!=nil||receipt.Outcome!="confirmed"{_ = s.routes.Rollback(ctx,command.Exposure,routeGeneration);return command.Exposure,s.ambiguous(ctx,operation,command.Exposure,err)};committed,err:=s.routes.Commit(ctx,command.Exposure,routeGeneration);if err!=nil{_ = s.routes.Rollback(ctx,command.Exposure,routeGeneration);compensation:=request;compensation.EffectID=EffectID(string(effect)+"-compensate");compensation.Grant.Operation="exposure.delete";_,compensationErr:=s.broker.DeleteExposure(ctx,compensation);return command.Exposure,s.ambiguous(ctx,operation,command.Exposure,errors.Join(err,compensationErr))};receipt.RouteGeneration=committed;command.Exposure.State="active";if err=s.repository.Complete(ctx,effect,"applied",command.Exposure,receipt);err!=nil{return command.Exposure,Result{EffectID:effect,Status:"ambiguous",ResourceID:command.Exposure.ID,Generation:command.Exposure.Generation,Receipt:receipt},err};return command.Exposure,Result{EffectID:effect,Status:"applied",ResourceID:command.Exposure.ID,Generation:command.Exposure.Generation,Receipt:receipt},nil}

func(s *Service)IssueExecGrant(ctx context.Context,grant Grant,id,workloadID,commandID ID,user RuntimeUser,args []string,ttl time.Duration,assuranceDigest string)(ExecGrant,error){if err:=grantValid(grant,"workload.exec",workloadID,s.clock().UTC());err!=nil{return ExecGrant{},err};workload,err:=s.repository.Workload(ctx,grant.TenantID,workloadID);if err!=nil{return ExecGrant{},err};if err=s.policy.AuthorizeTier(ctx,grant,workload.Tier,"exec");err!=nil{return ExecGrant{},err};if err=user.Validate(workload.Tier);err!=nil{return ExecGrant{},err};if ttl<=0||ttl>15*time.Minute{ttl=5*time.Minute};value:=ExecGrant{ID:id,TenantID:grant.TenantID,WorkloadID:workloadID,Tier:workload.Tier,RuntimeUser:user,CommandID:commandID,Arguments:append([]string(nil),args...),AssuranceDigest:assuranceDigest,ExpiresAt:s.clock().UTC().Add(ttl)};if err=s.repository.IssueExecGrant(ctx,value);err!=nil{return ExecGrant{},err};return value,nil}
func(s *Service)Exec(ctx context.Context,meta CommandMeta,grantID ID)(ExecReceipt,error){now:=s.clock().UTC();grant,err:=s.repository.ConsumeExecGrant(ctx,grantID,now);if err!=nil{return ExecReceipt{},err};if err=meta.Validate("workload.exec",grant.WorkloadID,now);err!=nil{return ExecReceipt{},err};effect,_,_,_,err:=s.operation(ctx,meta,grant.WorkloadID,grant);if err!=nil{return ExecReceipt{},err};return s.broker.Exec(ctx,ExecRequest{EffectID:effect,Grant:meta.Grant,ExecGrant:grant,Fence:meta.Fence})}
func(s *Service)ExchangeExec(ctx context.Context,grantID ID,token string)(ExecReceipt,error){if s==nil||ctx==nil||!grantID.Valid()||len(token)<32||len(token)>512||strings.ContainsAny(token,"\x00\r\n\t "){return ExecReceipt{},ErrForbidden};stored,err:=s.repository.ExecGrant(ctx,grantID);if err!=nil{return ExecReceipt{},err};now:=s.clock().UTC();if stored.ConsumedAt!=nil||!now.Before(stored.ExpiresAt)||len(stored.AssuranceDigest)!=64{return ExecReceipt{},ErrForbidden};sum:=sha256.Sum256([]byte(token));actual:=hex.EncodeToString(sum[:]);if subtle.ConstantTimeCompare([]byte(actual),[]byte(stored.AssuranceDigest))!=1{return ExecReceipt{},ErrForbidden};workload,err:=s.repository.Workload(ctx,stored.TenantID,stored.WorkloadID);if err!=nil{return ExecReceipt{},err};grant:=Grant{TenantID:stored.TenantID,ResourceID:stored.WorkloadID,Operation:"workload.exec",AuthzEpoch:1,ExpiresAt:stored.ExpiresAt,Digest:stored.AssuranceDigest};meta:=CommandMeta{CommandID:"exec-exchange-"+stored.ID.String(),Grant:grant,ExpectedGeneration:workload.Generation,Fence:FenceToken(workload.Generation+1)};return s.Exec(ctx,meta,stored.ID)}

func(s *Service)Reconcile(ctx context.Context,tenant,workloadID ID,grant Grant)(Workload,error){workload,err:=s.repository.Workload(ctx,tenant,workloadID);if err!=nil{return Workload{},err};if err=grantValid(grant,"workload.reconcile",workloadID,s.clock().UTC());err!=nil{return Workload{},err};receipt,err:=s.broker.ObserveWorkload(ctx,WorkloadObservationRequest{Grant:grant,WorkloadID:workload.ID,ExpectedGeneration:workload.Generation});if err!=nil{return workload,err};workload.ObservedLifecycle=receipt.Lifecycle;workload.ObservedDigest=receipt.ObservedDigest;workload.RuntimeObjectID=receipt.RuntimeObjectID;workload.ObservedGeneration=workload.Generation;workload.UpdatedAt=s.clock().UTC();effect:=EffectID("reconcile-"+digestValue(struct{ID ID;Generation uint64;Observed string}{workload.ID,workload.Generation,receipt.ObservedDigest}));operation:=Operation{EffectID:effect,TenantID:tenant,ResourceID:workload.ID,CommandDigest:string(effect),Status:"accepted",CreatedAt:s.clock().UTC()};_,_ = s.repository.Admit(ctx,operation,workload,workload.Generation-1);_ = s.repository.Complete(ctx,effect,"applied",workload,receipt);return workload,nil}

func(s *Service)operation(ctx context.Context,meta CommandMeta,resource ID,payload any)(EffectID,string,Operation,bool,error){digest:=digestValue(struct{Version int;CommandID string;Tenant ID;Resource ID;Payload any}{1,meta.CommandID,meta.Grant.TenantID,resource,payload});effect:=EffectID("ctr-"+digest);existing,found,err:=s.repository.Operation(ctx,effect);if err!=nil{return effect,digest,Operation{},false,err};if found{if existing.CommandDigest!=digest||existing.TenantID!=meta.Grant.TenantID||existing.ResourceID!=resource{return effect,digest,existing,true,ErrConflict};return effect,digest,existing,true,nil};raw,_:=json.Marshal(payload);return effect,digest,Operation{EffectID:effect,TenantID:meta.Grant.TenantID,ResourceID:resource,CommandDigest:digest,Status:"accepted",Request:raw,CreatedAt:s.clock().UTC()},false,nil}
func(s *Service)ambiguous(ctx context.Context,operation Operation,resource any,cause error)(Result,error){_ = s.repository.Complete(ctx,operation.EffectID,"ambiguous",resource,map[string]string{"code":"BROKER_EFFECT_AMBIGUOUS"});return Result{EffectID:operation.EffectID,Status:"ambiguous",ResourceID:operation.ResourceID,Generation:resourceGeneration(resource)},errors.Join(ErrAmbiguous,cause)}
func(s *Service)reject(ctx context.Context,operation Operation,resource any,cause error)(Result,error){_ = s.repository.Complete(ctx,operation.EffectID,"rejected",resource,map[string]string{"code":"EFFECT_REJECTED"});return Result{EffectID:operation.EffectID,Status:"rejected",ResourceID:operation.ResourceID,Generation:resourceGeneration(resource)},cause}
func resultFromOperation(operation Operation)Result{return Result{EffectID:operation.EffectID,Status:operation.Status,ResourceID:operation.ResourceID,Receipt:operation.Receipt}}
func imageFromOperation(operation Operation)Image{var value Image;_ = json.Unmarshal(operation.Receipt,&value);return value}
func digestValue(value any)string{raw,_:=json.Marshal(value);sum:=sha256.Sum256(raw);return hex.EncodeToString(sum[:])}
func grantValid(grant Grant,operation string,resource ID,now time.Time)error{if !grant.TenantID.Valid()||grant.ResourceID!=resource||grant.Operation!=operation||grant.AuthzEpoch==0||!now.Before(grant.ExpiresAt)||len(grant.Digest)!=64{return ErrForbidden};return nil}
func nilValue(value any)bool{if value==nil{return true};ref:=reflect.ValueOf(value);switch ref.Kind(){case reflect.Pointer,reflect.Interface,reflect.Map,reflect.Slice,reflect.Func,reflect.Chan:return ref.IsNil()};return false}
var _=fmt.Sprintf
var _=sort.Strings
