package containers

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"time"
)

const Schema=`
CREATE TABLE IF NOT EXISTS container_registry_credentials(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,generation BIGINT NOT NULL,value_json TEXT NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS container_images(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,image_digest TEXT NOT NULL,generation BIGINT NOT NULL,state TEXT NOT NULL,value_json TEXT NOT NULL,updated_at TIMESTAMP NOT NULL,UNIQUE(tenant_id,image_digest));
CREATE TABLE IF NOT EXISTS container_volumes(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,generation BIGINT NOT NULL,state TEXT NOT NULL,value_json TEXT NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS container_networks(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,generation BIGINT NOT NULL,state TEXT NOT NULL,value_json TEXT NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS container_workloads(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,generation BIGINT NOT NULL,observed_generation BIGINT NOT NULL,state TEXT NOT NULL,spec_digest TEXT NOT NULL,value_json TEXT NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE INDEX IF NOT EXISTS container_workloads_tenant ON container_workloads(tenant_id,state);
CREATE TABLE IF NOT EXISTS container_exposures(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,workload_id TEXT NOT NULL,generation BIGINT NOT NULL,state TEXT NOT NULL,value_json TEXT NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS container_applications(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,generation BIGINT NOT NULL,state TEXT NOT NULL,value_json TEXT NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS container_recipes(id TEXT PRIMARY KEY,version TEXT NOT NULL,digest TEXT NOT NULL,value_json TEXT NOT NULL,UNIQUE(id,version));
CREATE TABLE IF NOT EXISTS container_exec_grants(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,workload_id TEXT NOT NULL,expires_at TIMESTAMP NOT NULL,consumed_at TIMESTAMP,value_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS container_operations(effect_id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,resource_id TEXT NOT NULL,command_digest TEXT NOT NULL,status TEXT NOT NULL,request_json TEXT NOT NULL,receipt_json TEXT NOT NULL,created_at TIMESTAMP NOT NULL,completed_at TIMESTAMP);
`

type Operation struct{EffectID EffectID;TenantID,ResourceID ID;CommandDigest,Status string;Request json.RawMessage;Receipt json.RawMessage;CreatedAt time.Time;CompletedAt *time.Time}
type Repository interface{Workload(context.Context,ID,ID)(Workload,error);ListWorkloads(context.Context,ID)([]Workload,error);Volume(context.Context,ID,ID)(Volume,error);VolumeByID(context.Context,ID)(Volume,error);Network(context.Context,ID,ID)(Network,error);Exposure(context.Context,ID,ID)(Exposure,error);ImageByDigest(context.Context,ID,string)(Image,error);Application(context.Context,ID,ID)(ContainerApplication,error);Recipe(context.Context,ID,string)(ApplicationRecipe,error);Operation(context.Context,EffectID)(Operation,bool,error);Admit(context.Context,Operation,any,uint64)(bool,error);Complete(context.Context,EffectID,string,any,any)error;PutRecipe(context.Context,ApplicationRecipe)error;IssueExecGrant(context.Context,ExecGrant)error;ExecGrant(context.Context,ID)(ExecGrant,error);ConsumeExecGrant(context.Context,ID,time.Time)(ExecGrant,error)}

type SQLStore struct{db *sql.DB;clock func()time.Time}
func NewSQLStore(db *sql.DB)(*SQLStore,error){if db==nil{return nil,ErrInvalid};return &SQLStore{db:db,clock:time.Now},nil}
func(s *SQLStore)Bootstrap(ctx context.Context)error{_,err:=s.db.ExecContext(ctx,Schema);return err}

func(s *SQLStore)Workload(ctx context.Context,tenant,id ID)(Workload,error){var raw []byte;err:=s.db.QueryRowContext(ctx,`SELECT value_json FROM container_workloads WHERE id=? AND tenant_id=?`,id,tenant).Scan(&raw);var value Workload;return value,decodeResource(raw,err,&value)}
func(s *SQLStore)ListWorkloads(ctx context.Context,tenant ID)([]Workload,error){rows,err:=s.db.QueryContext(ctx,`SELECT value_json FROM container_workloads WHERE tenant_id=? AND state<>'deleted' ORDER BY id`,tenant);if err!=nil{return nil,err};defer rows.Close();var out []Workload;for rows.Next(){var raw []byte;if err=rows.Scan(&raw);err!=nil{return nil,err};var value Workload;if err=json.Unmarshal(raw,&value);err!=nil{return nil,err};out=append(out,value)};return out,rows.Err()}
func(s *SQLStore)Volume(ctx context.Context,tenant,id ID)(Volume,error){var raw []byte;err:=s.db.QueryRowContext(ctx,`SELECT value_json FROM container_volumes WHERE id=? AND tenant_id=?`,id,tenant).Scan(&raw);var value Volume;return value,decodeResource(raw,err,&value)}
func(s *SQLStore)VolumeByID(ctx context.Context,id ID)(Volume,error){var raw []byte;err:=s.db.QueryRowContext(ctx,`SELECT value_json FROM container_volumes WHERE id=?`,id).Scan(&raw);var value Volume;return value,decodeResource(raw,err,&value)}
func(s *SQLStore)Network(ctx context.Context,tenant,id ID)(Network,error){var raw []byte;err:=s.db.QueryRowContext(ctx,`SELECT value_json FROM container_networks WHERE id=? AND tenant_id=?`,id,tenant).Scan(&raw);var value Network;return value,decodeResource(raw,err,&value)}
func(s *SQLStore)Exposure(ctx context.Context,tenant,id ID)(Exposure,error){var raw []byte;err:=s.db.QueryRowContext(ctx,`SELECT value_json FROM container_exposures WHERE id=? AND tenant_id=?`,id,tenant).Scan(&raw);var value Exposure;return value,decodeResource(raw,err,&value)}
func(s *SQLStore)ImageByDigest(ctx context.Context,tenant ID,digest string)(Image,error){var raw []byte;err:=s.db.QueryRowContext(ctx,`SELECT value_json FROM container_images WHERE tenant_id=? AND image_digest=?`,tenant,digest).Scan(&raw);var value Image;return value,decodeResource(raw,err,&value)}
func(s *SQLStore)Application(ctx context.Context,tenant,id ID)(ContainerApplication,error){var raw []byte;err:=s.db.QueryRowContext(ctx,`SELECT value_json FROM container_applications WHERE id=? AND tenant_id=?`,id,tenant).Scan(&raw);var value ContainerApplication;return value,decodeResource(raw,err,&value)}
func(s *SQLStore)Recipe(ctx context.Context,id ID,version string)(ApplicationRecipe,error){var raw []byte;err:=s.db.QueryRowContext(ctx,`SELECT value_json FROM container_recipes WHERE id=? AND version=?`,id,version).Scan(&raw);var value ApplicationRecipe;return value,decodeResource(raw,err,&value)}
func decodeResource(raw []byte,err error,target any)error{if errors.Is(err,sql.ErrNoRows){return ErrNotFound};if err!=nil{return err};return json.Unmarshal(raw,target)}

func(s *SQLStore)Operation(ctx context.Context,effect EffectID)(Operation,bool,error){var value Operation;var request,receipt []byte;var completed sql.NullTime;err:=s.db.QueryRowContext(ctx,`SELECT effect_id,tenant_id,resource_id,command_digest,status,request_json,receipt_json,created_at,completed_at FROM container_operations WHERE effect_id=?`,effect).Scan(&value.EffectID,&value.TenantID,&value.ResourceID,&value.CommandDigest,&value.Status,&request,&receipt,&value.CreatedAt,&completed);if errors.Is(err,sql.ErrNoRows){return Operation{},false,nil};if err!=nil{return Operation{},false,err};value.Request=request;value.Receipt=receipt;if completed.Valid{value.CompletedAt=&completed.Time};return value,true,nil}

// Admit writes the accepted operation and proposed desired resource in one
// serializable transaction. expectedGeneration is zero for creation.
func(s *SQLStore)Admit(ctx context.Context,operation Operation,proposal any,expectedGeneration uint64)(bool,error){tx,err:=s.db.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return false,err};defer tx.Rollback();var digest string;err=tx.QueryRowContext(ctx,`SELECT command_digest FROM container_operations WHERE effect_id=?`,operation.EffectID).Scan(&digest);if err==nil{if digest!=operation.CommandDigest{return false,ErrConflict};return false,tx.Commit()};if !errors.Is(err,sql.ErrNoRows){return false,err};request,_:=json.Marshal(operation.Request);_,err=tx.ExecContext(ctx,`INSERT INTO container_operations VALUES(?,?,?,?,? ,?,?,?,NULL)`,operation.EffectID,operation.TenantID,operation.ResourceID,operation.CommandDigest,"accepted",request,[]byte(`{}`),s.clock().UTC());if err!=nil{return false,err};if err=putProposal(ctx,tx,proposal,expectedGeneration,s.clock().UTC());err!=nil{return false,err};if err=tx.Commit();err!=nil{return false,err};return true,nil}

func(s *SQLStore)Complete(ctx context.Context,effect EffectID,status string,resource any,receipt any)error{if status!="applied"&&status!="rejected"&&status!="ambiguous"{return ErrInvalid};tx,err:=s.db.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return err};defer tx.Rollback();var current string;err=tx.QueryRowContext(ctx,`SELECT status FROM container_operations WHERE effect_id=?`,effect).Scan(&current);if err!=nil{return err};if current!="accepted"&&current!="ambiguous"{if current==status{return tx.Commit()};return ErrConflict};if resource!=nil{if err=completeProposal(ctx,tx,resource,s.clock().UTC());err!=nil{return err}};raw,_:=json.Marshal(receipt);_,err=tx.ExecContext(ctx,`UPDATE container_operations SET status=?,receipt_json=?,completed_at=? WHERE effect_id=?`,status,raw,s.clock().UTC(),effect);if err!=nil{return err};return tx.Commit()}

// Admission already persisted this generation. Completion updates that exact
// row, never inserts it again or overwrites a newer admitted generation.
func completeProposal(ctx context.Context, tx *sql.Tx, value any, now time.Time) error {
	var table string
	var id, tenant ID
	switch v := value.(type) {
	case Workload: table, id, tenant = "container_workloads", v.ID, v.TenantID
	case Volume: table, id, tenant = "container_volumes", v.ID, v.TenantID
	case Network: table, id, tenant = "container_networks", v.ID, v.TenantID
	case Exposure: table, id, tenant = "container_exposures", v.ID, v.TenantID
	case Image: table, id, tenant = "container_images", v.ID, v.TenantID
	case ContainerApplication: table, id, tenant = "container_applications", v.ID, v.TenantID
	default: return ErrInvalid
	}
	var generation uint64
	if err := tx.QueryRowContext(ctx, `SELECT generation FROM `+table+` WHERE id=? AND tenant_id=?`, id, tenant).Scan(&generation); err != nil { return err }
	if generation != resourceGeneration(value) { return ErrStale }
	return putProposal(ctx, tx, value, generation, now)
}

func putProposal(ctx context.Context,tx *sql.Tx,value any,expected uint64,now time.Time)error{var table,id,tenant,state,digest,workloadID string;var generation,observed uint64;switch v:=value.(type){case Workload:table="container_workloads";id=v.ID.String();tenant=v.TenantID.String();state=string(v.DesiredLifecycle);digest=v.SpecDigest;generation=v.Generation;observed=v.ObservedGeneration;case Volume:table="container_volumes";id=v.ID.String();tenant=v.TenantID.String();state=v.State;generation=v.Generation;case Network:table="container_networks";id=v.ID.String();tenant=v.TenantID.String();state=v.State;generation=v.Generation;case Exposure:table="container_exposures";id=v.ID.String();tenant=v.TenantID.String();workloadID=v.WorkloadID.String();state=v.State;generation=v.Generation;case Image:table="container_images";id=v.ID.String();tenant=v.TenantID.String();state=string(v.State);digest=v.Reference.Digest;generation=v.Generation;case ContainerApplication:table="container_applications";id=v.ID.String();tenant=v.TenantID.String();state=v.State;generation=v.ActiveGeneration;default:return fmt.Errorf("%w: proposal type",ErrInvalid)};raw,err:=json.Marshal(value);if err!=nil{return err};if expected==0{switch table{case"container_workloads":_,err=tx.ExecContext(ctx,`INSERT INTO container_workloads VALUES(?,?,?,?,?,?,?,?)`,id,tenant,generation,observed,state,digest,raw,now);case"container_images":_,err=tx.ExecContext(ctx,`INSERT INTO container_images VALUES(?,?,?,?,?,?,?)`,id,tenant,digest,generation,state,raw,now);case"container_exposures":_,err=tx.ExecContext(ctx,`INSERT INTO container_exposures VALUES(?,?,?,?,?,?,?)`,id,tenant,workloadID,generation,state,raw,now);default:_,err=tx.ExecContext(ctx,`INSERT INTO `+table+`(id,tenant_id,generation,state,value_json,updated_at) VALUES(?,?,?,?,?,?)`,id,tenant,generation,state,raw,now)};return err};var result sql.Result;switch table{case"container_workloads":result,err=tx.ExecContext(ctx,`UPDATE container_workloads SET generation=?,observed_generation=?,state=?,spec_digest=?,value_json=?,updated_at=? WHERE id=? AND tenant_id=? AND generation=?`,generation,observed,state,digest,raw,now,id,tenant,expected);case"container_images":result,err=tx.ExecContext(ctx,`UPDATE container_images SET generation=?,state=?,value_json=?,updated_at=? WHERE id=? AND tenant_id=? AND generation=?`,generation,state,raw,now,id,tenant,expected);case"container_exposures":result,err=tx.ExecContext(ctx,`UPDATE container_exposures SET workload_id=?,generation=?,state=?,value_json=?,updated_at=? WHERE id=? AND tenant_id=? AND generation=?`,workloadID,generation,state,raw,now,id,tenant,expected);default:result,err=tx.ExecContext(ctx,`UPDATE `+table+` SET generation=?,state=?,value_json=?,updated_at=? WHERE id=? AND tenant_id=? AND generation=?`,generation,state,raw,now,id,tenant,expected)};if err!=nil{return err};count,err:=result.RowsAffected();if err!=nil{return err};if count!=1{return ErrStale};return nil}
func resourceGeneration(value any)uint64{switch v:=value.(type){case Workload:return v.Generation;case Volume:return v.Generation;case Network:return v.Generation;case Exposure:return v.Generation;case Image:return v.Generation;case ContainerApplication:return v.ActiveGeneration};return 0}
func(s *SQLStore)PutRecipe(ctx context.Context,recipe ApplicationRecipe)error{raw,_:=json.Marshal(recipe);_,err:=s.db.ExecContext(ctx,`INSERT INTO container_recipes VALUES(?,?,?,?) ON CONFLICT(id,version) DO UPDATE SET digest=excluded.digest,value_json=excluded.value_json WHERE container_recipes.digest=excluded.digest`,recipe.ID,recipe.Version,recipe.Digest,raw);return err}
func(s *SQLStore)IssueExecGrant(ctx context.Context,grant ExecGrant)error{raw,_:=json.Marshal(grant);_,err:=s.db.ExecContext(ctx,`INSERT INTO container_exec_grants VALUES(?,?,?,?,?,?)`,grant.ID,grant.TenantID,grant.WorkloadID,grant.ExpiresAt,grant.ConsumedAt,raw);return err}
func(s *SQLStore)ExecGrant(ctx context.Context,id ID)(ExecGrant,error){var raw []byte;err:=s.db.QueryRowContext(ctx,`SELECT value_json FROM container_exec_grants WHERE id=?`,id).Scan(&raw);if errors.Is(err,sql.ErrNoRows){return ExecGrant{},ErrNotFound};if err!=nil{return ExecGrant{},err};var grant ExecGrant;if json.Unmarshal(raw,&grant)!=nil||grant.ID!=id{return ExecGrant{},ErrInvalid};return grant,nil}
func(s *SQLStore)ConsumeExecGrant(ctx context.Context,id ID,now time.Time)(ExecGrant,error){tx,err:=s.db.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return ExecGrant{},err};defer tx.Rollback();var raw []byte;var expiry time.Time;var consumed sql.NullTime;err=tx.QueryRowContext(ctx,`SELECT expires_at,consumed_at,value_json FROM container_exec_grants WHERE id=?`,id).Scan(&expiry,&consumed,&raw);if errors.Is(err,sql.ErrNoRows){return ExecGrant{},ErrNotFound};if err!=nil{return ExecGrant{},err};if consumed.Valid||!now.Before(expiry){return ExecGrant{},ErrForbidden};result,err:=tx.ExecContext(ctx,`UPDATE container_exec_grants SET consumed_at=? WHERE id=? AND consumed_at IS NULL`,now,id);if err!=nil{return ExecGrant{},err};count,_:=result.RowsAffected();if count!=1{return ExecGrant{},ErrConflict};var grant ExecGrant;if err=json.Unmarshal(raw,&grant);err!=nil{return grant,err};grant.ConsumedAt=&now;return grant,tx.Commit()}
