package management

import(
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/webengine"
	"github.com/aonsyed/cyberpanel/platform/internal/webengine/native"
)

var(ErrInvalid=errors.New("webengine management: invalid value");ErrNotFound=errors.New("webengine management: not found");ErrConflict=errors.New("webengine management: conflict");ErrAmbiguous=errors.New("webengine management: ambiguous effect");ErrLicense=errors.New("webengine management: license rejected");ErrUnsupported=errors.New("webengine management: unsupported tuple"))
type State string
const(StateAbsent State="absent";StateInstalling State="installing";StateStaged State="staged";StateActive State="active";StateDegraded State="degraded";StateRemoving State="removing")
type Channel string
const(ChannelStable Channel="stable";ChannelLTS Channel="lts";ChannelPinned Channel="pinned")
type Installation struct{ID string;Edition webengine.Edition;Version,ArtifactDigest,RepositorySnapshotDigest string;Channel Channel;State State;License LicenseStatus;Generation uint64;ActiveConfigDigest,PreviousConfigDigest string;InstalledAt,UpdatedAt time.Time}
type LicenseStatus struct{Mode string;SecretRef string;SerialFingerprint string;State webengine.LicenseState;Limits LicenseLimits;CheckedAt,ExpiresAt time.Time;ReceiptDigest string}
type LicenseLimits struct{Workers,Domains uint32;MemoryBytes uint64;Features []string}
type ArtifactRequest struct{Edition webengine.Edition;Channel Channel;Version,OS,OSVersion,Architecture string}
type ArtifactPlan struct{Edition webengine.Edition;Version,ArtifactDigest,RepositorySnapshotDigest string;Packages []PackageArtifact;ServiceProfileID string;NativeConfigFormat string}
type PackageArtifact struct{Name,Version,Digest,RepositoryID string}
type ArtifactCatalog interface{Resolve(context.Context,ArtifactRequest)(ArtifactPlan,error)}
type TargetRenderer interface{BuildTarget(context.Context,webengine.Edition,uint64)(native.ConfigGeneration,error)}
type Executor interface{Inspect(context.Context,webengine.Edition)(Installation,error);Install(context.Context,EffectRequest,ArtifactPlan)(EffectReceipt,error);ApplyLicense(context.Context,EffectRequest,LicenseRequest)(LicenseStatus,error);RefreshLicense(context.Context,EffectRequest)(LicenseStatus,error);StageGeneration(context.Context,EffectRequest,native.ConfigGeneration)(EffectReceipt,error);ValidateGeneration(context.Context,EffectRequest,native.ConfigGeneration)(ValidationReceipt,error);ShadowProbe(context.Context,EffectRequest,native.ConfigGeneration)(ProbeReceipt,error);SwitchService(context.Context,SwitchRequest)(SwitchReceipt,error);ConfirmService(context.Context,SwitchReceipt)(ProbeReceipt,error);RestoreService(context.Context,SwitchReceipt)(ProbeReceipt,error);Remove(context.Context,EffectRequest,webengine.Edition)(EffectReceipt,error);InstallPHP(context.Context,EffectRequest,PHPArtifactPlan)(EffectReceipt,error);ApplyPHPProfile(context.Context,EffectRequest,PHPProfile)(EffectReceipt,error);RestartPHPPool(context.Context,EffectRequest,string)(EffectReceipt,error);ApplyGlobalTuning(context.Context,EffectRequest,GlobalTuning)(EffectReceipt,error)}
type EffectRequest struct{EffectID string;ExpectedGeneration uint64;Fence uint64;PlanDigest,CommitAuthorizationDigest string}
type EffectReceipt struct{EffectID,PlanDigest,EvidenceDigest string;Generation,Fence uint64;Outcome string;ObservedAt time.Time}
type ValidationReceipt struct{EffectID,ConfigDigest,ParserDigest,SemanticDigest string;Valid bool;Findings []string;ObservedAt time.Time}
type ProbeReceipt struct{EffectID,ConfigDigest string;HTTP,HTTPS,PHP,Cache,TLS,HTTP3 bool;EvidenceDigest string;ObservedAt time.Time}
type SwitchRequest struct{EffectRequest EffectRequest;Previous,Target webengine.Edition;PreviousConfigDigest,TargetConfigDigest string;RollbackDeadline time.Time}
type SwitchReceipt struct{EffectID string;Previous,Target webengine.Edition;PreviousConfigDigest,TargetConfigDigest,LeaseID,ConfirmNonce,EvidenceDigest string;Fence uint64;SwitchedAt,RollbackDeadline time.Time;Confirmed bool}
type LicenseRequest struct{Mode,SecretRef string;Trial bool}

type PHPProfile struct{ID,Version,BinaryArtifactDigest,ConfigDigest string;Extensions []string;MemoryLimitBytes,UploadLimitBytes,BodyLimitBytes uint64;RequestTimeout time.Duration;MaxConnections,MaxChildren uint32;Detached bool;Generation uint64}
type PHPArtifactPlan struct{Version,RepositorySnapshotDigest string;Packages []PackageArtifact;BinaryPathID string}
type GlobalTuning struct{WorkerProcesses,MaxConnections,MaxTLSConnections uint32;ConnectionTimeout,KeepAliveTimeout time.Duration;KeepAliveRequests uint32;MemoryCacheBytes uint64;Compression bool;CompressionLevel uint8;Brotli bool;Generation uint64}

type Operation struct{ID,Kind,Status,RequestDigest string;ExpectedGeneration uint64;Installation Installation;Receipt any;CreatedAt,UpdatedAt time.Time}
type Repository interface{Installation(context.Context)(Installation,error);Admit(context.Context,Operation)(Operation,bool,error);Complete(context.Context,string,string,Installation,any)error;PHPProfile(context.Context,string)(PHPProfile,error);PutPHPProfile(context.Context,PHPProfile,uint64)error;GlobalTuning(context.Context)(GlobalTuning,error);PutGlobalTuning(context.Context,GlobalTuning,uint64)error}
type Service struct{repository Repository;catalog ArtifactCatalog;renderer TargetRenderer;executor Executor;clock func()time.Time}
func New(repository Repository,catalog ArtifactCatalog,renderer TargetRenderer,executor Executor)(*Service,error){if repository==nil||catalog==nil||renderer==nil||executor==nil{return nil,ErrInvalid};return &Service{repository:repository,catalog:catalog,renderer:renderer,executor:executor,clock:time.Now},nil}

type InstallCommand struct{CommandID,OS,OSVersion,Architecture,Version string;Edition webengine.Edition;Channel Channel;License LicenseRequest;ExpectedGeneration,Fence uint64;CommitAuthorizationDigest string}
func(s *Service)Install(ctx context.Context,command InstallCommand)(Installation,error){if command.Edition!=webengine.EditionOpenLiteSpeed&&command.Edition!=webengine.EditionLiteSpeedEnterprise{return Installation{},ErrInvalid};plan,err:=s.catalog.Resolve(ctx,ArtifactRequest{Edition:command.Edition,Channel:command.Channel,Version:command.Version,OS:command.OS,OSVersion:command.OSVersion,Architecture:command.Architecture});if err!=nil{return Installation{},err};planDigest:=digestJSON(plan);effect:=effectID(command.CommandID,planDigest);current,loadErr:=s.repository.Installation(ctx);if loadErr!=nil&&!errors.Is(loadErr,ErrNotFound){return Installation{},loadErr};next:=Installation{ID:"node-webengine",Edition:command.Edition,Version:plan.Version,ArtifactDigest:plan.ArtifactDigest,RepositorySnapshotDigest:plan.RepositorySnapshotDigest,Channel:command.Channel,State:StateInstalling,Generation:command.ExpectedGeneration+1,UpdatedAt:s.clock().UTC()};if current.Generation>0{next.InstalledAt=current.InstalledAt;next.PreviousConfigDigest=current.ActiveConfigDigest}else{next.InstalledAt=s.clock().UTC()};operation:=Operation{ID:effect,Kind:"install",Status:"accepted",RequestDigest:planDigest,ExpectedGeneration:command.ExpectedGeneration,Installation:next,CreatedAt:s.clock().UTC(),UpdatedAt:s.clock().UTC()};admitted,isNew,err:=s.repository.Admit(ctx,operation);if err!=nil{return Installation{},err};if !isNew{return admitted.Installation,nil};request:=EffectRequest{EffectID:effect,ExpectedGeneration:command.ExpectedGeneration,Fence:command.Fence,PlanDigest:planDigest,CommitAuthorizationDigest:command.CommitAuthorizationDigest};receipt,err:=s.executor.Install(ctx,request,plan);if err!=nil||receipt.Outcome!="confirmed"{_ = s.repository.Complete(ctx,effect,"ambiguous",next,receipt);return next,errors.Join(ErrAmbiguous,err)};if command.Edition==webengine.EditionLiteSpeedEnterprise{license,licenseErr:=s.executor.ApplyLicense(ctx,request,command.License);if licenseErr!=nil||license.State!=webengine.LicenseActive&&license.State!=webengine.LicenseTrial{_ = s.repository.Complete(ctx,effect,"rejected",next,license);return next,errors.Join(ErrLicense,licenseErr)};next.License=license};next.State=StateStaged;if err=s.repository.Complete(ctx,effect,"applied",next,receipt);err!=nil{return next,err};return next,nil}

type ConvertCommand struct{CommandID,OS,OSVersion,Architecture,Version string;Target webengine.Edition;Channel Channel;License LicenseRequest;ExpectedGeneration,SnapshotGeneration,Fence uint64;CommitAuthorizationDigest string;RollbackWindow time.Duration}
func(s *Service)Convert(ctx context.Context,command ConvertCommand)(Installation,error){current,err:=s.repository.Installation(ctx);if err!=nil{return Installation{},err};if current.Generation!=command.ExpectedGeneration||current.Edition==command.Target{return current,ErrConflict};installed,err:=s.Install(ctx,InstallCommand{CommandID:command.CommandID+".install",OS:command.OS,OSVersion:command.OSVersion,Architecture:command.Architecture,Version:command.Version,Edition:command.Target,Channel:command.Channel,License:command.License,ExpectedGeneration:current.Generation,Fence:command.Fence,CommitAuthorizationDigest:command.CommitAuthorizationDigest});if err!=nil{return installed,err};generation,err:=s.renderer.BuildTarget(ctx,command.Target,command.SnapshotGeneration);if err!=nil{return installed,err};request:=EffectRequest{EffectID:effectID(command.CommandID,generation.ContentDigest),ExpectedGeneration:installed.Generation,Fence:command.Fence+1,PlanDigest:generation.ContentDigest,CommitAuthorizationDigest:command.CommitAuthorizationDigest};stage,err:=s.executor.StageGeneration(ctx,request,generation);if err!=nil||stage.Outcome!="confirmed"{return installed,errors.Join(ErrAmbiguous,err)};validation,err:=s.executor.ValidateGeneration(ctx,request,generation);if err!=nil||!validation.Valid{return installed,errors.Join(ErrInvalid,err)};shadow,err:=s.executor.ShadowProbe(ctx,request,generation);if err!=nil||!probeHealthy(shadow){return installed,errors.Join(ErrInvalid,err)};window:=command.RollbackWindow;if window<time.Minute{window=5*time.Minute};switched,err:=s.executor.SwitchService(ctx,SwitchRequest{EffectRequest:request,Previous:current.Edition,Target:command.Target,PreviousConfigDigest:current.ActiveConfigDigest,TargetConfigDigest:generation.ContentDigest,RollbackDeadline:s.clock().UTC().Add(window)});if err!=nil{return installed,errors.Join(ErrAmbiguous,err)};confirmed,err:=s.executor.ConfirmService(ctx,switched);if err!=nil||!probeHealthy(confirmed){restored,restoreErr:=s.executor.RestoreService(ctx,switched);if restoreErr!=nil||!probeHealthy(restored){installed.State=StateDegraded;_ = s.repository.Complete(ctx,request.EffectID,"ambiguous",installed,switched);return installed,errors.Join(ErrAmbiguous,err,restoreErr)};return current,errors.Join(ErrInvalid,err)};installed.State=StateActive;installed.ActiveConfigDigest=generation.ContentDigest;installed.PreviousConfigDigest=current.ActiveConfigDigest;installed.UpdatedAt=s.clock().UTC();if err=s.repository.Complete(ctx,request.EffectID,"applied",installed,switched);err!=nil{return installed,err};return installed,nil}

func(s *Service)RefreshLicense(ctx context.Context,effect string,expected,fence uint64)(LicenseStatus,error){installation,err:=s.repository.Installation(ctx);if err!=nil{return LicenseStatus{},err};if installation.Edition!=webengine.EditionLiteSpeedEnterprise||installation.Generation!=expected{return LicenseStatus{},ErrConflict};status,err:=s.executor.RefreshLicense(ctx,EffectRequest{EffectID:effect,ExpectedGeneration:expected,Fence:fence,PlanDigest:installation.ArtifactDigest});if err!=nil{return status,err};installation.License=status;installation.Generation++;installation.UpdatedAt=s.clock().UTC();if err=s.repository.Complete(ctx,effect,"applied",installation,status);err!=nil{return status,err};return status,nil}
func(s *Service)InstallPHP(ctx context.Context,effect string,profile PHPProfile,plan PHPArtifactPlan,expected,fence uint64,authorization string)(PHPProfile,error){if profile.ID==""||profile.Version==""||profile.Generation!=expected+1||profile.MaxConnections==0||profile.MaxChildren==0||profile.MaxChildren<profile.MaxConnections{return PHPProfile{},ErrInvalid};request:=EffectRequest{EffectID:effect,ExpectedGeneration:expected,Fence:fence,PlanDigest:digestJSON(plan),CommitAuthorizationDigest:authorization};receipt,err:=s.executor.InstallPHP(ctx,request,plan);if err!=nil||receipt.Outcome!="confirmed"{return profile,errors.Join(ErrAmbiguous,err)};receipt,err=s.executor.ApplyPHPProfile(ctx,request,profile);if err!=nil||receipt.Outcome!="confirmed"{return profile,errors.Join(ErrAmbiguous,err)};if err=s.repository.PutPHPProfile(ctx,profile,expected);err!=nil{return profile,err};return profile,nil}
func(s *Service)Tune(ctx context.Context,effect string,tuning GlobalTuning,expected,fence uint64,authorization string)(GlobalTuning,error){if tuning.Generation!=expected+1||tuning.WorkerProcesses==0||tuning.MaxConnections==0||tuning.MaxTLSConnections>tuning.MaxConnections||tuning.KeepAliveRequests==0||tuning.CompressionLevel>9{return GlobalTuning{},ErrInvalid};request:=EffectRequest{EffectID:effect,ExpectedGeneration:expected,Fence:fence,PlanDigest:digestJSON(tuning),CommitAuthorizationDigest:authorization};receipt,err:=s.executor.ApplyGlobalTuning(ctx,request,tuning);if err!=nil||receipt.Outcome!="confirmed"{return tuning,errors.Join(ErrAmbiguous,err)};if err=s.repository.PutGlobalTuning(ctx,tuning,expected);err!=nil{return tuning,err};return tuning,nil}
func probeHealthy(value ProbeReceipt)bool{return value.HTTP&&value.HTTPS&&value.PHP&&value.TLS&&value.EvidenceDigest!=""}
func effectID(command,digest string)string{sum:=sha256.Sum256([]byte(command+"\x00"+digest));return "web-"+hex.EncodeToString(sum[:])}
func digestJSON(value any)string{raw,_:=json.Marshal(value);sum:=sha256.Sum256(raw);return hex.EncodeToString(sum[:])}
var _=fmt.Sprintf
var _=strings.TrimSpace

const SQLSchema=`
CREATE TABLE IF NOT EXISTS webengine_installation(singleton_id INTEGER PRIMARY KEY,generation BIGINT NOT NULL,state TEXT NOT NULL,value_json TEXT NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS webengine_management_operations(id TEXT PRIMARY KEY,kind TEXT NOT NULL,status TEXT NOT NULL,request_digest TEXT NOT NULL,expected_generation BIGINT NOT NULL,installation_json TEXT NOT NULL,receipt_json TEXT NOT NULL,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS webengine_php_profiles(id TEXT PRIMARY KEY,generation BIGINT NOT NULL,value_json TEXT NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS webengine_global_tuning(singleton_id INTEGER PRIMARY KEY,generation BIGINT NOT NULL,value_json TEXT NOT NULL,updated_at TIMESTAMP NOT NULL);
`
type SQLRepository struct{db *sql.DB;clock func()time.Time}
func NewSQLRepository(db *sql.DB)(*SQLRepository,error){if db==nil{return nil,ErrInvalid};return &SQLRepository{db:db,clock:time.Now},nil}
func(r *SQLRepository)Bootstrap(ctx context.Context)error{_,err:=r.db.ExecContext(ctx,SQLSchema);return err}
func(r *SQLRepository)Installation(ctx context.Context)(Installation,error){var value Installation;var raw []byte;err:=r.db.QueryRowContext(ctx,`SELECT value_json FROM webengine_installation WHERE singleton_id=1`).Scan(&raw);if errors.Is(err,sql.ErrNoRows){return value,ErrNotFound};if err!=nil{return value,err};err=json.Unmarshal(raw,&value);return value,err}
func(r *SQLRepository)Admit(ctx context.Context,operation Operation)(Operation,bool,error){tx,err:=r.db.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return operation,false,err};defer tx.Rollback();var raw []byte;var digest string;err=tx.QueryRowContext(ctx,`SELECT request_digest,installation_json FROM webengine_management_operations WHERE id=?`,operation.ID).Scan(&digest,&raw);if err==nil{if digest!=operation.RequestDigest{return operation,false,ErrConflict};_ = json.Unmarshal(raw,&operation.Installation);return operation,false,tx.Commit()};if !errors.Is(err,sql.ErrNoRows){return operation,false,err};current:=uint64(0);_ = tx.QueryRowContext(ctx,`SELECT generation FROM webengine_installation WHERE singleton_id=1`).Scan(&current);if current!=operation.ExpectedGeneration{return operation,false,ErrConflict};installation,_:=json.Marshal(operation.Installation);_,err=tx.ExecContext(ctx,`INSERT INTO webengine_management_operations VALUES(?,?,?,?,?,?,?,?,?)`,operation.ID,operation.Kind,"accepted",operation.RequestDigest,operation.ExpectedGeneration,installation,[]byte(`{}`),operation.CreatedAt,operation.UpdatedAt);if err!=nil{return operation,false,err};_,err=tx.ExecContext(ctx,`INSERT INTO webengine_installation VALUES(1,?,?,?,?) ON CONFLICT(singleton_id) DO UPDATE SET generation=excluded.generation,state=excluded.state,value_json=excluded.value_json,updated_at=excluded.updated_at WHERE webengine_installation.generation=?`,operation.Installation.Generation,operation.Installation.State,installation,r.clock().UTC(),operation.ExpectedGeneration);if err!=nil{return operation,false,err};return operation,true,tx.Commit()}
func(r *SQLRepository)Complete(ctx context.Context,id,status string,installation Installation,receipt any)error{tx,err:=r.db.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return err};defer tx.Rollback();raw,_:=json.Marshal(installation);receiptRaw,_:=json.Marshal(receipt);_,err=tx.ExecContext(ctx,`UPDATE webengine_installation SET generation=?,state=?,value_json=?,updated_at=? WHERE singleton_id=1`,installation.Generation,installation.State,raw,r.clock().UTC());if err!=nil{return err};_,err=tx.ExecContext(ctx,`UPDATE webengine_management_operations SET status=?,installation_json=?,receipt_json=?,updated_at=? WHERE id=?`,status,raw,receiptRaw,r.clock().UTC(),id);if err!=nil{return err};return tx.Commit()}
func(r *SQLRepository)PHPProfile(ctx context.Context,id string)(PHPProfile,error){var value PHPProfile;var raw []byte;err:=r.db.QueryRowContext(ctx,`SELECT value_json FROM webengine_php_profiles WHERE id=?`,id).Scan(&raw);if errors.Is(err,sql.ErrNoRows){return value,ErrNotFound};if err!=nil{return value,err};err=json.Unmarshal(raw,&value);return value,err}
func(r *SQLRepository)PutPHPProfile(ctx context.Context,value PHPProfile,expected uint64)error{raw,_:=json.Marshal(value);result,err:=r.db.ExecContext(ctx,`INSERT INTO webengine_php_profiles VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET generation=excluded.generation,value_json=excluded.value_json,updated_at=excluded.updated_at WHERE webengine_php_profiles.generation=?`,value.ID,value.Generation,raw,r.clock().UTC(),expected);if err!=nil{return err};count,_:=result.RowsAffected();if count!=1{return ErrConflict};return nil}
func(r *SQLRepository)GlobalTuning(ctx context.Context)(GlobalTuning,error){var value GlobalTuning;var raw []byte;err:=r.db.QueryRowContext(ctx,`SELECT value_json FROM webengine_global_tuning WHERE singleton_id=1`).Scan(&raw);if errors.Is(err,sql.ErrNoRows){return value,ErrNotFound};if err!=nil{return value,err};err=json.Unmarshal(raw,&value);return value,err}
func(r *SQLRepository)PutGlobalTuning(ctx context.Context,value GlobalTuning,expected uint64)error{raw,_:=json.Marshal(value);result,err:=r.db.ExecContext(ctx,`INSERT INTO webengine_global_tuning VALUES(1,?,?,?) ON CONFLICT(singleton_id) DO UPDATE SET generation=excluded.generation,value_json=excluded.value_json,updated_at=excluded.updated_at WHERE webengine_global_tuning.generation=?`,value.Generation,raw,r.clock().UTC(),expected);if err!=nil{return err};count,_:=result.RowsAffected();if count!=1{return ErrConflict};return nil}
