package secrets

import(
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"time"
)

const Schema=`
CREATE TABLE IF NOT EXISTS secret_password_pairs(primary_id TEXT PRIMARY KEY,replica_id TEXT NOT NULL UNIQUE,intent_digest TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS secret_records(secret_id TEXT NOT NULL,version BIGINT NOT NULL,owner_tenant_id TEXT NOT NULL,state TEXT NOT NULL,key_epoch BIGINT NOT NULL,metadata_json TEXT NOT NULL,nonce BLOB NOT NULL,wrapped_dek BLOB NOT NULL,ciphertext BLOB NOT NULL,aad BLOB NOT NULL,created_at TIMESTAMP NOT NULL,PRIMARY KEY(secret_id,version));
CREATE TABLE IF NOT EXISTS secret_heads(secret_id TEXT PRIMARY KEY,owner_tenant_id TEXT NOT NULL,current_version BIGINT NOT NULL,key_epoch BIGINT NOT NULL,state TEXT NOT NULL,binding_digest TEXT NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS secret_delivery_grants(id TEXT PRIMARY KEY,secret_id TEXT NOT NULL,secret_version BIGINT NOT NULL,tenant_id TEXT NOT NULL,operation TEXT NOT NULL,grant_json TEXT NOT NULL,expires_at TIMESTAMP NOT NULL,consumed_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS secret_deliveries(id INTEGER PRIMARY KEY AUTOINCREMENT,grant_id TEXT NOT NULL,secret_id TEXT NOT NULL,secret_version BIGINT NOT NULL,consumer_id TEXT NOT NULL,operation TEXT NOT NULL,outcome TEXT NOT NULL,delivered_at TIMESTAMP NOT NULL);
`
type Store struct{db *sql.DB;clock func()time.Time}
func NewStore(db *sql.DB)(*Store,error){if db==nil{return nil,ErrInvalid};return &Store{db:db,clock:time.Now},nil}
func(s *Store)Bootstrap(ctx context.Context)error{_,err:=s.db.ExecContext(ctx,Schema);return err}
func(s *Store)Head(ctx context.Context,id ID)(Metadata,error){var version uint64;err:=s.db.QueryRowContext(ctx,`SELECT current_version FROM secret_heads WHERE secret_id=?`,id).Scan(&version);if errors.Is(err,sql.ErrNoRows){return Metadata{},ErrNotFound};if err!=nil{return Metadata{},err};record,err:=s.Record(ctx,id,version);return record.Metadata,err}
func(s *Store)Record(ctx context.Context,id ID,version uint64)(SecretRecord,error){var record SecretRecord;var raw []byte;err:=s.db.QueryRowContext(ctx,`SELECT metadata_json,nonce,wrapped_dek,ciphertext,aad FROM secret_records WHERE secret_id=? AND version=?`,id,version).Scan(&raw,&record.Nonce,&record.WrappedDEK,&record.Ciphertext,&record.AAD);if errors.Is(err,sql.ErrNoRows){return record,ErrNotFound};if err!=nil{return record,err};if err=json.Unmarshal(raw,&record.Metadata);err!=nil{return record,err};return record,record.Metadata.Validate()}
func(s *Store)Put(ctx context.Context,record SecretRecord,expectedVersion uint64)error{if err:=record.Metadata.Validate();err!=nil{return err};tx,err:=s.db.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return err};defer tx.Rollback();var current uint64;err=tx.QueryRowContext(ctx,`SELECT current_version FROM secret_heads WHERE secret_id=?`,record.Metadata.ID).Scan(&current);if errors.Is(err,sql.ErrNoRows){current=0}else if err!=nil{return err};if current!=expectedVersion||record.Metadata.Version!=expectedVersion+1{return ErrRollback};raw,_:=json.Marshal(record.Metadata);_,err=tx.ExecContext(ctx,`INSERT INTO secret_records VALUES(?,?,?,?,?,?,?,?,?,?,?)`,record.Metadata.ID,record.Metadata.Version,record.Metadata.OwnerTenantID,record.Metadata.State,record.Metadata.KeyEpoch,raw,record.Nonce,record.WrappedDEK,record.Ciphertext,record.AAD,record.Metadata.CreatedAt);if err!=nil{return err};_,err=tx.ExecContext(ctx,`INSERT INTO secret_heads VALUES(?,?,?,?,?,?,?) ON CONFLICT(secret_id) DO UPDATE SET current_version=excluded.current_version,key_epoch=excluded.key_epoch,state=excluded.state,binding_digest=excluded.binding_digest,updated_at=excluded.updated_at WHERE secret_heads.current_version=?`,record.Metadata.ID,record.Metadata.OwnerTenantID,record.Metadata.Version,record.Metadata.KeyEpoch,record.Metadata.State,record.Metadata.BindingDigest,s.clock().UTC(),expectedVersion);if err!=nil{return err};return tx.Commit()}
func(s *Store)UpdateState(ctx context.Context,id ID,version uint64,state State,at time.Time)error{if state!=StateRetiring&&state!=StateRevoked&&state!=StateDestroyed{return ErrInvalid};tx,err:=s.db.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return err};defer tx.Rollback();record,err:=loadRecordTx(ctx,tx,id,version);if err!=nil{return err};record.Metadata.State=state;if state==StateRevoked{record.Metadata.RevokedAt=&at};if state==StateDestroyed{record.Metadata.DestroyedAt=&at;record.Ciphertext=[]byte{};record.WrappedDEK=[]byte{}};raw,_:=json.Marshal(record.Metadata);_,err=tx.ExecContext(ctx,`UPDATE secret_records SET state=?,metadata_json=?,wrapped_dek=?,ciphertext=? WHERE secret_id=? AND version=?`,state,raw,record.WrappedDEK,record.Ciphertext,id,version);if err!=nil{return err};_,err=tx.ExecContext(ctx,`UPDATE secret_heads SET state=?,updated_at=? WHERE secret_id=? AND current_version=?`,state,at,id,version);if err!=nil{return err};return tx.Commit()}
func loadRecordTx(ctx context.Context,tx *sql.Tx,id ID,version uint64)(SecretRecord,error){var record SecretRecord;var raw []byte;err:=tx.QueryRowContext(ctx,`SELECT metadata_json,nonce,wrapped_dek,ciphertext,aad FROM secret_records WHERE secret_id=? AND version=?`,id,version).Scan(&raw,&record.Nonce,&record.WrappedDEK,&record.Ciphertext,&record.AAD);if errors.Is(err,sql.ErrNoRows){return record,ErrNotFound};if err!=nil{return record,err};err=json.Unmarshal(raw,&record.Metadata);return record,err}
func(s *Store)IssueGrant(ctx context.Context,grant DeliveryGrant)error{if err:=grant.Validate();err!=nil{return err};raw,_:=json.Marshal(grant);_,err:=s.db.ExecContext(ctx,`INSERT INTO secret_delivery_grants VALUES(?,?,?,?,?,?,?,NULL)`,grant.ID,grant.SecretID,grant.SecretVersion,grant.TenantID,grant.Operation,raw,grant.ExpiresAt);return err}
func(s *Store)ConsumeGrant(ctx context.Context,id ID,now time.Time)(DeliveryGrant,error){tx,err:=s.db.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return DeliveryGrant{},err};defer tx.Rollback();var raw []byte;var expiry time.Time;var consumed sql.NullTime;err=tx.QueryRowContext(ctx,`SELECT grant_json,expires_at,consumed_at FROM secret_delivery_grants WHERE id=?`,id).Scan(&raw,&expiry,&consumed);if errors.Is(err,sql.ErrNoRows){return DeliveryGrant{},ErrNotFound};if err!=nil{return DeliveryGrant{},err};if consumed.Valid||!now.Before(expiry){return DeliveryGrant{},ErrExpired};result,err:=tx.ExecContext(ctx,`UPDATE secret_delivery_grants SET consumed_at=? WHERE id=? AND consumed_at IS NULL`,now,id);if err!=nil{return DeliveryGrant{},err};count,_:=result.RowsAffected();if count!=1{return DeliveryGrant{},ErrConflict};var grant DeliveryGrant;if err=json.Unmarshal(raw,&grant);err!=nil{return grant,err};grant.ConsumedAt=&now;return grant,tx.Commit()}
func(s *Store)RecordDelivery(ctx context.Context,grant DeliveryGrant,outcome string)error{_,err:=s.db.ExecContext(ctx,`INSERT INTO secret_deliveries(grant_id,secret_id,secret_version,consumer_id,operation,outcome,delivered_at) VALUES(?,?,?,?,?,?,?)`,grant.ID,grant.SecretID,grant.SecretVersion,grant.Consumer.ID,grant.Operation,outcome,s.clock().UTC());return err}
