package controlplane

import(
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/federation"
)

type Authorizer interface{Authorize(context.Context,Operator,string,federation.ID,string,string)error}
type IntentSigner interface{IntentKeyID(context.Context)(string,error);SignIntent(context.Context,string,[]byte)([]byte,error);RevocationKeyID(context.Context)(string,error);SignRevocation(context.Context,string,[]byte)([]byte,error)}
type ReceiptVerifier interface{VerifyNodeReceipt(context.Context,federation.ID,string,[]byte,[]byte)error}
type IDGenerator interface{New(context.Context,string)(federation.ID,error)}
type Audit interface{Record(context.Context,string,Operator,federation.ID,string,string,string)error}
type Service struct{store *Store;authorizer Authorizer;signer IntentSigner;receiptVerifier ReceiptVerifier;ids IDGenerator;audit Audit;peerID federation.ID;clock func()time.Time}
func NewService(store *Store,authorizer Authorizer,signer IntentSigner,ids IDGenerator,audit Audit,peerID federation.ID)(*Service,error){if store==nil||authorizer==nil||signer==nil||ids==nil||audit==nil||!peerID.Valid(){return nil,ErrInvalid};return &Service{store:store,authorizer:authorizer,signer:signer,ids:ids,audit:audit,peerID:peerID,clock:time.Now},nil}
func(s *Service)WithReceiptVerifier(verifier ReceiptVerifier)*Service{if s!=nil{s.receiptVerifier=verifier};return s}

func(s *Service)CreateIntent(ctx context.Context,operator Operator,request IntentRequest)(federation.Intent,error){node,err:=s.store.Node(ctx,request.NodeID);if err!=nil{return federation.Intent{},err};if node.State==NodeRevoked||node.State==NodeRevoking{return federation.Intent{},ErrForbidden};if err=s.authorizer.Authorize(ctx,operator,"node.intent.create",node.ID,request.ResourceKind,request.ResourceID);err!=nil{return federation.Intent{},err};capability,ok:=findCapability(node.Capabilities,request.CommandType);if !ok||!capability.RemoteEligible||capability.SchemaHash!=request.SchemaHash{return federation.Intent{},ErrForbidden};if !riskAtLeast(request.Risk,capability.MinimumRisk){request.Risk=capability.MinimumRisk};if (request.Risk==federation.RiskHigh||request.Risk==federation.RiskCritical)&&request.Approval==nil{return federation.Intent{},ErrForbidden};canonical,err:=canonicalPayload(request.Payload);if err!=nil{return federation.Intent{},err};id,err:=s.ids.New(ctx,"intent");if err!=nil{return federation.Intent{},err};effectID:="fed-"+digest([]byte(id.String()+"\x00"+request.IdempotencyKey+"\x00"+request.NodeID.String()));now:=s.clock().UTC();intent:=federation.Intent{ID:id,PeerID:s.peerID,NodeID:node.ID,GrantID:request.GrantID,AuthorityEpoch:node.AuthorityEpoch,ProtocolVersion:capability.Version,CommandType:request.CommandType,SchemaHash:request.SchemaHash,Payload:canonical,PayloadDigest:digest(canonical),TenantID:request.TenantID,ResourceKind:request.ResourceKind,ResourceID:request.ResourceID,ExpectedGeneration:request.ExpectedGeneration,IdempotencyKey:request.IdempotencyKey,EffectID:effectID,Risk:request.Risk,ActorChain:[]federation.Actor{{PrincipalID:operator.PrincipalID,TenantID:operator.TenantID,SessionID:operator.SessionID,AuthzEpoch:operator.AuthzEpoch,Assurance:operator.Assurance}},Approval:request.Approval,IssuedAt:now,ExpiresAt:now.Add(15*time.Minute)};key,err:=s.signer.IntentKeyID(ctx);if err!=nil{return federation.Intent{},err};intent.SigningKeyID=key;signature,err:=s.signer.SignIntent(ctx,key,intent.SigStructure());if err!=nil{return federation.Intent{},err};intent.Signature=signature;if err=intent.Validate(now);err!=nil{return federation.Intent{},err};priority:=uint8(2);if intent.Risk==federation.RiskHigh{priority=3};if intent.Risk==federation.RiskCritical{priority=4};if err=s.store.QueueIntent(ctx,node.OwnerTenantID,intent,priority);err!=nil{return federation.Intent{},err};_ = s.audit.Record(ctx,"federation.intent.queued",operator,node.ID,request.ResourceKind,request.ResourceID,intent.EffectID);return intent,nil}

func(s *Service)HandleReceipt(ctx context.Context,nodeID federation.ID,receipt federation.Receipt)error{if s.receiptVerifier==nil||receipt.NodeID!=nodeID||!receipt.IntentID.Valid()||receipt.EffectID==""||receipt.IdempotencyKey==""||receipt.SignatureKeyID==""||len(receipt.Signature)==0||receipt.UpdatedAt.IsZero(){return ErrInvalid};if err:=s.receiptVerifier.VerifyNodeReceipt(ctx,nodeID,receipt.SignatureKeyID,receiptStructure(receipt),receipt.Signature);err!=nil{return ErrForbidden};if err:=s.store.Receipt(ctx,receipt);err!=nil{return err};return nil}
func(s *Service)HandleEvents(ctx context.Context,nodeID federation.ID,events []federation.NodeEvent)error{if len(events)==0||len(events)>1000{return ErrInvalid};sort.Slice(events,func(i,j int)bool{return events[i].Sequence<events[j].Sequence});for index,event:=range events{if event.NodeID!=nodeID||event.Sequence==0||index>0&&event.Sequence<=events[index-1].Sequence||len(event.Payload)>4<<20||digest(event.Payload)!=event.PayloadDigest{return ErrInvalid}};return s.store.ApplyEvents(ctx,nodeID,events)}
func(s *Service)Disconnect(ctx context.Context,nodeID federation.ID)error{return s.store.MarkNodeStale(ctx,nodeID)}

func(s *Service)RevokeNode(ctx context.Context,operator Operator,nodeID federation.ID,reason string)(federation.Revocation,error){node,err:=s.store.Node(ctx,nodeID);if err!=nil{return federation.Revocation{},err};if err=s.authorizer.Authorize(ctx,operator,"node.revoke",node.ID,"node",node.ID.String());err!=nil{return federation.Revocation{},err};revocation:=federation.Revocation{PeerID:s.peerID,NodeID:node.ID,NewAuthorityEpoch:node.AuthorityEpoch+1,Reason:reason,IssuedAt:s.clock().UTC()};key,err:=s.signer.RevocationKeyID(ctx);if err!=nil{return federation.Revocation{},err};revocation.SigningKeyID=key;signature,err:=s.signer.SignRevocation(ctx,key,revocationStructure(revocation));if err!=nil{return federation.Revocation{},err};revocation.Signature=signature;if err=s.store.PutRevocation(ctx,revocation);err!=nil{return federation.Revocation{},err};node.AuthorityEpoch=revocation.NewAuthorityEpoch;node.State=NodeRevoking;node.UpdatedAt=s.clock().UTC();if err=s.store.PutNode(ctx,node);err!=nil{return federation.Revocation{},err};_ = s.audit.Record(ctx,"federation.node.revocation_queued",operator,node.ID,"node",node.ID.String(),reason);return revocation,nil}

func(s *Service)CreateSaga(ctx context.Context,operator Operator,saga Saga)(Saga,error){if !saga.ID.Valid()||!saga.OwnerTenantID.Valid()||saga.Kind==""||len(saga.Steps)==0{return Saga{},ErrInvalid};if err:=s.authorizer.Authorize(ctx,operator,"saga.create",saga.ID,"saga",saga.ID.String());err!=nil{return Saga{},err};ids:=map[string]bool{};for _,step:=range saga.Steps{if step.ID==""||!step.NodeID.Valid()||ids[step.ID]{return Saga{},ErrInvalid};ids[step.ID]=true};for _,step:=range saga.Steps{for _,dependency:=range step.Dependencies{if !ids[dependency]{return Saga{},ErrInvalid}}};saga.State=SagaPending;saga.Current=0;saga.CreatedAt=s.clock().UTC();saga.UpdatedAt=saga.CreatedAt;if err:=s.store.PutSaga(ctx,saga);err!=nil{return Saga{},err};return saga,nil}
func(s *Service)AdvanceSaga(ctx context.Context,id federation.ID,operator Operator)(Saga,error){saga,err:=s.store.Saga(ctx,id);if err!=nil{return Saga{},err};if err=s.authorizer.Authorize(ctx,operator,"saga.advance",saga.ID,"saga",saga.ID.String());err!=nil{return Saga{},err};if saga.State==SagaApplied||saga.State==SagaFailed{return saga,nil};saga.State=SagaRunning;for index:=range saga.Steps{step:=&saga.Steps[index];if step.Status==federation.IntentApplied{continue};if !dependenciesApplied(saga.Steps,*step){continue};if step.IntentID==""{saga.State=SagaPaused;saga.ErrorCode="SAGA_STEP_INTENT_REQUIRED";break};saga.Current=uint32(index);saga.UpdatedAt=s.clock().UTC();return saga,s.store.PutSaga(ctx,saga)};all:=true;for _,step:=range saga.Steps{if step.Status!=federation.IntentApplied{all=false;break}};if all{saga.State=SagaApplied};saga.UpdatedAt=s.clock().UTC();return saga,s.store.PutSaga(ctx,saga)}
func(s *Service)ApplySagaReceipt(ctx context.Context,sagaID federation.ID,receipt federation.Receipt)(Saga,error){saga,err:=s.store.Saga(ctx,sagaID);if err!=nil{return Saga{},err};found:=false;for index:=range saga.Steps{if saga.Steps[index].IntentID==receipt.IntentID{saga.Steps[index].Status=receipt.Status;saga.Steps[index].Receipt=&receipt;found=true;break}};if !found{return saga,ErrNotFound};if receipt.Status==federation.IntentRejected{saga.State=SagaCompensating;saga.ErrorCode=receipt.ErrorCode}else if receipt.Status==federation.IntentAmbiguous{saga.State=SagaPaused;saga.ErrorCode="SAGA_STEP_AMBIGUOUS"};saga.UpdatedAt=s.clock().UTC();return saga,s.store.PutSaga(ctx,saga)}

type NodeSession struct{service *Service;store *Store;session federation.Session;nodeID federation.ID;sendEvery time.Duration}
func(s *Service)NewNodeSession(nodeID federation.ID,session federation.Session)(*NodeSession,error){if !nodeID.Valid()||session==nil{return nil,ErrInvalid};return &NodeSession{service:s,store:s.store,session:session,nodeID:nodeID,sendEvery:500*time.Millisecond},nil}
func(n *NodeSession)Run(ctx context.Context)error{ticker:=time.NewTicker(n.sendEvery);defer ticker.Stop();incoming:=make(chan federation.Frame,1);fail:=make(chan error,1);go func(){for{frame,err:=n.session.Receive(ctx);if err!=nil{fail<-err;return};select{case incoming<-frame:case<-ctx.Done():return}}}();for{select{case<-ctx.Done():return ctx.Err();case err:=<-fail:_=n.service.Disconnect(context.Background(),n.nodeID);return err;case frame:=<-incoming:if err:=n.handle(ctx,frame);err!=nil{return err};case<-ticker.C:if err:=n.flush(ctx);err!=nil{return err}}}}
func(n *NodeSession)flush(ctx context.Context)error{revocations,err:=n.store.QueuedRevocations(ctx,n.nodeID,20);if err!=nil{return err};for _,value:=range revocations{raw,_:=json.Marshal(value);if err=n.session.Send(ctx,federation.Frame{Version:1,Type:federation.FrameRevocation,Payload:raw});err!=nil{return err};if err=n.store.MarkRevocationSent(ctx,n.nodeID,value.NewAuthorityEpoch);err!=nil{return err}};if len(revocations)>0{return nil};node,err:=n.store.Node(ctx,n.nodeID);if err!=nil{return err};if node.State==NodeRevoking||node.State==NodeRevoked{return nil};intents,err:=n.store.QueuedIntents(ctx,n.nodeID,50);if err!=nil{return err};for _,intent:=range intents{raw,_:=json.Marshal(intent);if err=n.session.Send(ctx,federation.Frame{Version:1,Type:federation.FrameIntent,Payload:raw});err!=nil{return err};if err=n.store.MarkIntentSent(ctx,intent.ID);err!=nil{return err}};return nil}
func(n *NodeSession)handle(ctx context.Context,frame federation.Frame)error{switch frame.Type{case federation.FrameHello:var capabilities federation.CapabilitySet;if err:=json.Unmarshal(frame.Payload,&capabilities);err!=nil{return err};node,err:=n.store.Node(ctx,n.nodeID);if err!=nil{return err};epochValid:=capabilities.AuthorityEpoch==node.AuthorityEpoch||node.State==NodeRevoking&&capabilities.AuthorityEpoch<node.AuthorityEpoch;if node.State==NodeRevoked||capabilities.NodeID!=n.nodeID||!epochValid||capabilities.Digest!=capabilities.CanonicalDigest(){return ErrForbidden};node.Capabilities=capabilities;if node.State!=NodeRevoking{node.State=NodeOnline};node.LastSeenAt=time.Now().UTC();node.UpdatedAt=node.LastSeenAt;if err=n.store.PutNode(ctx,node);err!=nil{return err};return sendFrame(ctx,n.session,federation.FrameHelloAck,map[string]any{"accepted":true,"revocationPending":node.State==NodeRevoking});case federation.FrameReceipt:var receipt federation.Receipt;if err:=json.Unmarshal(frame.Payload,&receipt);err!=nil{return err};return n.service.HandleReceipt(ctx,n.nodeID,receipt);case federation.FrameRevocationAck:var ack struct{NodeID federation.ID `json:"nodeId"`;AuthorityEpoch uint64 `json:"authorityEpoch"`;AppliedAt time.Time `json:"appliedAt"`};if err:=json.Unmarshal(frame.Payload,&ack);err!=nil{return err};if ack.NodeID!=n.nodeID||ack.AuthorityEpoch==0||ack.AppliedAt.IsZero(){return ErrInvalid};return n.store.AckRevocation(ctx,n.nodeID,ack.AuthorityEpoch);case federation.FrameEventBatch:var events []federation.NodeEvent;if err:=json.Unmarshal(frame.Payload,&events);err!=nil{return err};if err:=n.service.HandleEvents(ctx,n.nodeID,events);err!=nil{return err};return sendFrame(ctx,n.session,federation.FrameEventAck,map[string]any{"through":events[len(events)-1].Sequence});case federation.FrameHeartbeat:node,err:=n.store.Node(ctx,n.nodeID);if err!=nil{return err};if node.State==NodeRevoked{return ErrForbidden};if node.State!=NodeRevoking{node.State=NodeOnline};node.LastSeenAt=time.Now().UTC();node.UpdatedAt=node.LastSeenAt;return n.store.PutNode(ctx,node);default:return ErrInvalid}}
func sendFrame(ctx context.Context,session federation.Session,kind federation.FrameType,value any)error{raw,_:=json.Marshal(value);return session.Send(ctx,federation.Frame{Version:1,Type:kind,Payload:raw})}
func findCapability(set federation.CapabilitySet,kind string)(federation.Capability,bool){for _,value:=range set.Capabilities{if value.CommandType==kind{return value,true}};return federation.Capability{},false}
func riskAtLeast(value,minimum federation.Risk)bool{rank:=map[federation.Risk]int{federation.RiskLow:1,federation.RiskModerate:2,federation.RiskHigh:3,federation.RiskCritical:4};return rank[value]>=rank[minimum]}
func canonicalPayload(raw []byte)([]byte,error){var value any;decoder:=json.NewDecoder(strings.NewReader(string(raw)));decoder.UseNumber();if err:=decoder.Decode(&value);err!=nil{return nil,err};return json.Marshal(value)}
func digest(raw []byte)string{sum:=sha256.Sum256(raw);return hex.EncodeToString(sum[:])}
func dependenciesApplied(steps []SagaStep,step SagaStep)bool{for _,dependency:=range step.Dependencies{found:=false;for _,candidate:=range steps{if candidate.ID==dependency{found=candidate.Status==federation.IntentApplied;break}};if !found{return false}};return true}
func revocationStructure(value federation.Revocation)[]byte{copy:=value;copy.Signature=nil;raw,_:=json.Marshal(struct{Domain string `json:"domain"`;Value federation.Revocation `json:"value"`}{"cyberpanel-federation-revocation-v1",copy});return raw}
func receiptStructure(value federation.Receipt)[]byte{return value.SigStructure()}
var _=errors.Is
var _=fmt.Sprintf
