package controlplane

import(
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/federation"
)
const Schema=`
CREATE TABLE IF NOT EXISTS fleet_nodes(id TEXT PRIMARY KEY,owner_tenant_id TEXT NOT NULL,name TEXT NOT NULL,state TEXT NOT NULL,authority_epoch BIGINT NOT NULL,capabilities_json TEXT NOT NULL,projection_sequence BIGINT NOT NULL,snapshot_generation BIGINT NOT NULL,last_seen_at TIMESTAMP NOT NULL,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL,certificate_fingerprint TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS fleet_intents(id TEXT PRIMARY KEY,node_id TEXT NOT NULL,owner_tenant_id TEXT NOT NULL,status TEXT NOT NULL,priority INTEGER NOT NULL,intent_json TEXT NOT NULL,receipt_json TEXT NOT NULL,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL,expires_at TIMESTAMP NOT NULL);
CREATE INDEX IF NOT EXISTS fleet_intents_node_queue ON fleet_intents(node_id,status,priority,created_at);
CREATE TABLE IF NOT EXISTS fleet_projections(node_id TEXT NOT NULL,tenant_id TEXT NOT NULL,resource_kind TEXT NOT NULL,resource_id TEXT NOT NULL,generation BIGINT NOT NULL,status_json TEXT NOT NULL,digest TEXT NOT NULL,observed_at TIMESTAMP NOT NULL,event_sequence BIGINT NOT NULL,stale INTEGER NOT NULL,PRIMARY KEY(node_id,resource_kind,resource_id));
CREATE TABLE IF NOT EXISTS fleet_events(node_id TEXT NOT NULL,sequence BIGINT NOT NULL,event_id TEXT NOT NULL,event_json TEXT NOT NULL,occurred_at TIMESTAMP NOT NULL,PRIMARY KEY(node_id,sequence),UNIQUE(node_id,event_id));
CREATE TABLE IF NOT EXISTS fleet_sagas(id TEXT PRIMARY KEY,owner_tenant_id TEXT NOT NULL,kind TEXT NOT NULL,state TEXT NOT NULL,current_step INTEGER NOT NULL,saga_json TEXT NOT NULL,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL,error_code TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS fleet_encrypted_secrets(target_node_id TEXT NOT NULL,secret_id TEXT NOT NULL,version BIGINT NOT NULL,envelope_json TEXT NOT NULL,expires_at TIMESTAMP NOT NULL,consumed_at TIMESTAMP,PRIMARY KEY(target_node_id,secret_id,version));
CREATE TABLE IF NOT EXISTS fleet_revocations(node_id TEXT NOT NULL,authority_epoch BIGINT NOT NULL,status TEXT NOT NULL,revocation_json TEXT NOT NULL,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL,PRIMARY KEY(node_id,authority_epoch));
`
type Store struct{db *sql.DB;clock func()time.Time}
func NewStore(db *sql.DB)(*Store,error){if db==nil{return nil,ErrInvalid};return &Store{db:db,clock:time.Now},nil}
func(s *Store)Bootstrap(ctx context.Context)error{_,err:=s.db.ExecContext(ctx,Schema);return err}
func(s *Store)PutNode(ctx context.Context,node Node)error{raw,_:=json.Marshal(node.Capabilities);_,err:=s.db.ExecContext(ctx,`INSERT INTO fleet_nodes VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,state=excluded.state,authority_epoch=excluded.authority_epoch,capabilities_json=excluded.capabilities_json,projection_sequence=excluded.projection_sequence,snapshot_generation=excluded.snapshot_generation,last_seen_at=excluded.last_seen_at,updated_at=excluded.updated_at,certificate_fingerprint=excluded.certificate_fingerprint`,node.ID,node.OwnerTenantID,node.Name,node.State,node.AuthorityEpoch,raw,node.ProjectionSequence,node.SnapshotGeneration,node.LastSeenAt,node.CreatedAt,node.UpdatedAt,node.CertificateFingerprint);return err}
func(s *Store)Node(ctx context.Context,id federation.ID)(Node,error){var node Node;var raw []byte;err:=s.db.QueryRowContext(ctx,`SELECT id,owner_tenant_id,name,state,authority_epoch,capabilities_json,projection_sequence,snapshot_generation,last_seen_at,created_at,updated_at,certificate_fingerprint FROM fleet_nodes WHERE id=?`,id).Scan(&node.ID,&node.OwnerTenantID,&node.Name,&node.State,&node.AuthorityEpoch,&raw,&node.ProjectionSequence,&node.SnapshotGeneration,&node.LastSeenAt,&node.CreatedAt,&node.UpdatedAt,&node.CertificateFingerprint);if errors.Is(err,sql.ErrNoRows){return node,ErrNotFound};if err!=nil{return node,err};err=json.Unmarshal(raw,&node.Capabilities);return node,err}
func(s *Store)QueueIntent(ctx context.Context,owner federation.ID,intent federation.Intent,priority uint8)error{raw,_:=json.Marshal(intent);_,err:=s.db.ExecContext(ctx,`INSERT INTO fleet_intents VALUES(?,?,?,?,?,?,?,?,?,?)`,intent.ID,intent.NodeID,owner,"queued",priority,raw,[]byte(`{}`),s.clock().UTC(),s.clock().UTC(),intent.ExpiresAt);return err}
func(s *Store)QueuedIntents(ctx context.Context,node federation.ID,limit uint32)([]federation.Intent,error){if limit==0||limit>500{limit=100};rows,err:=s.db.QueryContext(ctx,`SELECT intent_json FROM fleet_intents WHERE node_id=? AND status IN ('queued','sent') AND expires_at>? ORDER BY priority DESC,created_at LIMIT ?`,node,s.clock().UTC(),limit);if err!=nil{return nil,err};defer rows.Close();var out []federation.Intent;for rows.Next(){var raw []byte;if err=rows.Scan(&raw);err!=nil{return nil,err};var intent federation.Intent;if err=json.Unmarshal(raw,&intent);err!=nil{return nil,err};out=append(out,intent)};return out,rows.Err()}
func(s *Store)MarkIntentSent(ctx context.Context,id federation.ID)error{result,err:=s.db.ExecContext(ctx,`UPDATE fleet_intents SET status='sent',updated_at=? WHERE id=? AND status IN ('queued','sent')`,s.clock().UTC(),id);if err!=nil{return err};rows,err:=result.RowsAffected();if err!=nil||rows!=1{return ErrConflict};return nil}
func(s *Store)Receipt(ctx context.Context,receipt federation.Receipt)error{tx,err:=s.db.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return err};defer tx.Rollback();var rawIntent []byte;var current string;if err=tx.QueryRowContext(ctx,`SELECT intent_json,status FROM fleet_intents WHERE id=?`,receipt.IntentID).Scan(&rawIntent,&current);errors.Is(err,sql.ErrNoRows){return ErrNotFound};if err!=nil{return err};var intent federation.Intent;if err=json.Unmarshal(rawIntent,&intent);err!=nil{return err};if receipt.NodeID!=intent.NodeID||receipt.EffectID!=intent.EffectID||receipt.IdempotencyKey!=intent.IdempotencyKey{return ErrConflict};if current==string(federation.IntentApplied)||current==string(federation.IntentRejected)||current==string(federation.IntentExpired){return tx.Commit()};raw,_:=json.Marshal(receipt);result,err:=tx.ExecContext(ctx,`UPDATE fleet_intents SET status=?,receipt_json=?,updated_at=? WHERE id=? AND status IN ('queued','sent','accepted','running','ambiguous')`,receipt.Status,raw,s.clock().UTC(),receipt.IntentID);if err!=nil{return err};rows,err:=result.RowsAffected();if err!=nil||rows!=1{return ErrConflict};return tx.Commit()}
func(s *Store)PutRevocation(ctx context.Context,value federation.Revocation)error{raw,_:=json.Marshal(value);_,err:=s.db.ExecContext(ctx,`INSERT INTO fleet_revocations(node_id,authority_epoch,status,revocation_json,created_at,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(node_id,authority_epoch) DO UPDATE SET revocation_json=excluded.revocation_json,updated_at=excluded.updated_at WHERE fleet_revocations.status IN ('queued','sent')`,value.NodeID,value.NewAuthorityEpoch,"queued",raw,s.clock().UTC(),s.clock().UTC());return err}
func(s *Store)QueuedRevocations(ctx context.Context,node federation.ID,limit uint32)([]federation.Revocation,error){if limit==0||limit>100{limit=20};rows,err:=s.db.QueryContext(ctx,`SELECT revocation_json FROM fleet_revocations WHERE node_id=? AND status IN ('queued','sent') ORDER BY authority_epoch LIMIT ?`,node,limit);if err!=nil{return nil,err};defer rows.Close();var out []federation.Revocation;for rows.Next(){var raw []byte;if err=rows.Scan(&raw);err!=nil{return nil,err};var value federation.Revocation;if err=json.Unmarshal(raw,&value);err!=nil{return nil,err};out=append(out,value)};return out,rows.Err()}
func(s *Store)MarkRevocationSent(ctx context.Context,node federation.ID,epoch uint64)error{result,err:=s.db.ExecContext(ctx,`UPDATE fleet_revocations SET status='sent',updated_at=? WHERE node_id=? AND authority_epoch=? AND status IN ('queued','sent')`,s.clock().UTC(),node,epoch);if err!=nil{return err};rows,err:=result.RowsAffected();if err!=nil||rows!=1{return ErrConflict};return nil}
func(s *Store)AckRevocation(ctx context.Context,node federation.ID,epoch uint64)error{tx,err:=s.db.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return err};defer tx.Rollback();result,err:=tx.ExecContext(ctx,`UPDATE fleet_revocations SET status='applied',updated_at=? WHERE node_id=? AND authority_epoch=? AND status IN ('queued','sent')`,s.clock().UTC(),node,epoch);if err!=nil{return err};rows,err:=result.RowsAffected();if err!=nil||rows!=1{return ErrConflict};result,err=tx.ExecContext(ctx,`UPDATE fleet_nodes SET state='revoked',updated_at=? WHERE id=? AND authority_epoch=? AND state='revoking'`,s.clock().UTC(),node,epoch);if err!=nil{return err};rows,err=result.RowsAffected();if err!=nil||rows!=1{return ErrConflict};return tx.Commit()}
func(s *Store)ApplyEvents(ctx context.Context,nodeID federation.ID,events []federation.NodeEvent)error{tx,err:=s.db.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return err};defer tx.Rollback();node,err:=loadNodeTx(ctx,tx,nodeID);if err!=nil{return err};for _,event:=range events{if event.NodeID!=nodeID||event.Sequence<=node.ProjectionSequence{return ErrConflict};raw,_:=json.Marshal(event);_,err=tx.ExecContext(ctx,`INSERT INTO fleet_events VALUES(?,?,?,?,?) ON CONFLICT(node_id,sequence) DO NOTHING`,nodeID,event.Sequence,event.ID,raw,event.OccurredAt);if err!=nil{return err};if event.ResourceKind!=""&&event.ResourceID!=""{_,err=tx.ExecContext(ctx,`INSERT INTO fleet_projections VALUES(?,?,?,?,?,?,?,?,?,0) ON CONFLICT(node_id,resource_kind,resource_id) DO UPDATE SET tenant_id=excluded.tenant_id,generation=excluded.generation,status_json=excluded.status_json,digest=excluded.digest,observed_at=excluded.observed_at,event_sequence=excluded.event_sequence,stale=0 WHERE fleet_projections.generation<=excluded.generation`,nodeID,event.TenantID,event.ResourceKind,event.ResourceID,event.Generation,event.Payload,event.PayloadDigest,event.OccurredAt,event.Sequence);if err!=nil{return err}};node.ProjectionSequence=event.Sequence};node.LastSeenAt=s.clock().UTC();node.UpdatedAt=node.LastSeenAt;rawCapabilities,_:=json.Marshal(node.Capabilities);_,err=tx.ExecContext(ctx,`UPDATE fleet_nodes SET projection_sequence=?,last_seen_at=?,updated_at=?,capabilities_json=? WHERE id=?`,node.ProjectionSequence,node.LastSeenAt,node.UpdatedAt,rawCapabilities,nodeID);if err!=nil{return err};return tx.Commit()}
func loadNodeTx(ctx context.Context,tx *sql.Tx,id federation.ID)(Node,error){var node Node;var raw []byte;err:=tx.QueryRowContext(ctx,`SELECT id,owner_tenant_id,name,state,authority_epoch,capabilities_json,projection_sequence,snapshot_generation,last_seen_at,created_at,updated_at,certificate_fingerprint FROM fleet_nodes WHERE id=?`,id).Scan(&node.ID,&node.OwnerTenantID,&node.Name,&node.State,&node.AuthorityEpoch,&raw,&node.ProjectionSequence,&node.SnapshotGeneration,&node.LastSeenAt,&node.CreatedAt,&node.UpdatedAt,&node.CertificateFingerprint);if errors.Is(err,sql.ErrNoRows){return node,ErrNotFound};if err!=nil{return node,err};err=json.Unmarshal(raw,&node.Capabilities);return node,err}
func(s *Store)MarkNodeStale(ctx context.Context,node federation.ID)error{_,err:=s.db.ExecContext(ctx,`UPDATE fleet_projections SET stale=1 WHERE node_id=?`,node);if err==nil{_,err=s.db.ExecContext(ctx,`UPDATE fleet_nodes SET state='offline',updated_at=? WHERE id=?`,s.clock().UTC(),node)};return err}
func(s *Store)PutSaga(ctx context.Context,saga Saga)error{raw,_:=json.Marshal(saga);_,err:=s.db.ExecContext(ctx,`INSERT INTO fleet_sagas VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET state=excluded.state,current_step=excluded.current_step,saga_json=excluded.saga_json,updated_at=excluded.updated_at,error_code=excluded.error_code`,saga.ID,saga.OwnerTenantID,saga.Kind,saga.State,saga.Current,raw,saga.CreatedAt,saga.UpdatedAt,saga.ErrorCode);return err}
func(s *Store)Saga(ctx context.Context,id federation.ID)(Saga,error){var saga Saga;var raw []byte;err:=s.db.QueryRowContext(ctx,`SELECT saga_json FROM fleet_sagas WHERE id=?`,id).Scan(&raw);if errors.Is(err,sql.ErrNoRows){return saga,ErrNotFound};if err!=nil{return saga,err};err=json.Unmarshal(raw,&saga);return saga,err}
func(s *Store)PutEncryptedSecret(ctx context.Context,value EncryptedSecret)error{raw,_:=json.Marshal(value);_,err:=s.db.ExecContext(ctx,`INSERT INTO fleet_encrypted_secrets VALUES(?,?,?,?,?,NULL)`,value.TargetNodeID,value.SecretID,value.Version,raw,value.ExpiresAt);return err}
func(s *Store)TakeEncryptedSecrets(ctx context.Context,node federation.ID,limit uint32)([]EncryptedSecret,error){if limit==0||limit>100{limit=20};rows,err:=s.db.QueryContext(ctx,`SELECT envelope_json FROM fleet_encrypted_secrets WHERE target_node_id=? AND consumed_at IS NULL AND expires_at>? ORDER BY secret_id,version LIMIT ?`,node,s.clock().UTC(),limit);if err!=nil{return nil,err};defer rows.Close();var out []EncryptedSecret;for rows.Next(){var raw []byte;if err=rows.Scan(&raw);err!=nil{return nil,err};var value EncryptedSecret;if err=json.Unmarshal(raw,&value);err!=nil{return nil,err};out=append(out,value)};return out,rows.Err()}
