//go:build linux

package main

import (
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/access"
	"github.com/aonsyed/cyberpanel/platform/internal/apiserver"
	"github.com/aonsyed/cyberpanel/platform/internal/hosting/site"
)

type accessCredentialStore interface{
	ListCredentials(context.Context,access.TenantID,[]access.SiteID,string,uint16)([]access.CredentialRecord,string,uint64,error)
	LoadFTPS(context.Context,access.FTPSAccountID)(access.FTPSAccount,error)
	LoadSSHKey(context.Context,access.SSHKeyID)(access.SSHKey,error)
	LoadAccessGrant(context.Context,access.AccessGrantID)(access.AccessGrant,error)
}

type accessEdge struct{credentials *access.CredentialService;files *access.FileService;store accessCredentialStore;sites apiserver.HostingQueryService;hostFilesystem *access.HostFilesystemService;now func()time.Time}

func newAccessEdge(credentials *access.CredentialService,files *access.FileService,store accessCredentialStore,sites apiserver.HostingQueryService)(apiserver.AccessEdgeService,error){if credentials==nil||files==nil||store==nil||sites==nil{return nil,errors.New("access edge dependencies are required")};broker,err:=access.NewLinuxHostFilesystemBroker(access.DefaultLinuxHostFilesystemRoots());if err!=nil{return nil,errors.New("initialize host filesystem broker: "+err.Error())};reauthorizer:=access.HostFilesystemReauthorizerFunc(func(ctx context.Context,request access.HostFilesystemAuthorizationRequest)error{if ctx==nil||request.SessionID.Validate()!=nil{return access.ErrUnauthorized};switch request.Operation{case"issue","list","stat","read":return nil;default:return access.ErrUnauthorized}});hostFilesystem,err:=access.NewHostFilesystemService(broker,reauthorizer,access.DefaultHostFilesystemAccessPolicy());if err!=nil{_=broker.Close();return nil,errors.New("initialize host filesystem service: "+err.Error())};edge:=&accessEdge{credentials:credentials,files:files,store:store,sites:sites,hostFilesystem:hostFilesystem,now:time.Now};hostFilesystem.Now=edge.now;return edge,nil}

func(edge *accessEdge)tenantSites(ctx context.Context,raw string)(site.TenantID,[]access.SiteID,error){tenant,err:=site.NewTenantID(raw);if err!=nil{return tenant,nil,access.ErrInvalidID};values:=[]access.SiteID{};cursor:="";for{page,next,_,listErr:=edge.sites.List(ctx,tenant,cursor,500);if listErr!=nil{return tenant,nil,listErr};for _,value:=range page{values=append(values,access.SiteID(value.ID().String()))};if next==""{break};cursor=next};return tenant,values,nil}
func(edge *accessEdge)authorizeSite(ctx context.Context,call apiserver.EdgeCall,raw string)(site.TenantID,error){tenant,err:=site.NewTenantID(call.TenantID);if err!=nil{return tenant,access.ErrInvalidID};siteID,err:=site.NewSiteID(raw);if err!=nil{return tenant,access.ErrInvalidID};if _,err=edge.sites.Load(ctx,tenant,siteID);err!=nil{return tenant,access.ErrUnauthorized};return tenant,nil}

func(edge *accessEdge)ListCredentials(ctx context.Context,call apiserver.EdgeCall,page apiserver.EdgePagePayload)(apiserver.EdgePage[apiserver.AccessCredentialProjection],error){tenant,sites,err:=edge.tenantSites(ctx,call.TenantID);if err!=nil{return apiserver.EdgePage[apiserver.AccessCredentialProjection]{},err};records,next,total,err:=edge.store.ListCredentials(ctx,access.TenantID(tenant.String()),sites,page.Cursor,page.Limit);if err!=nil{return apiserver.EdgePage[apiserver.AccessCredentialProjection]{},err};items:=make([]apiserver.AccessCredentialProjection,0,len(records));for _,record:=range records{if record.FTPS!=nil{value:=record.FTPS;items=append(items,apiserver.AccessCredentialProjection{ID:string(value.ID),SiteID:string(value.SiteID),Label:value.Username,Kind:"ftps",State:string(value.State),ExpiresAt:value.ExpiresAt,Generation:value.Generation})}else if record.Grant!=nil{value:=record.Grant;kind:="ssh_key";if value.Protocol==access.ProtocolTerminal{kind="terminal"};items=append(items,apiserver.AccessCredentialProjection{ID:string(value.ID),SiteID:string(value.SiteID),Label:string(value.Protocol),Kind:kind,State:string(value.State),ExpiresAt:value.ExpiresAt,Generation:value.Generation})}};return apiserver.EdgePage[apiserver.AccessCredentialProjection]{Items:items,NextCursor:next,Total:total},nil}

func accessEdgeID(prefix string,values ...string)string{sum:=sha256.Sum256([]byte(strings.Join(values,"\x00")));return prefix+hex.EncodeToString(sum[:20])}
func accessExpiry(now time.Time,seconds uint32)time.Time{if seconds==0{return time.Time{}};return now.Add(time.Duration(seconds)*time.Second)}
func accessPermission(raw string)access.AccessPermission{switch raw{case"read_only":return access.AccessReadOnly;case"terminal":return access.AccessTerminal;default:return access.AccessReadWrite}}

func(edge *accessEdge)CreateCredential(ctx context.Context,call apiserver.EdgeCall,payload apiserver.AccessCredentialCreatePayload,secret []byte)(apiserver.EdgeMutation[apiserver.AccessCredentialProjection],error){tenant,err:=edge.authorizeSite(ctx,call,payload.SiteID);if err!=nil{return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},err};now:=edge.now().UTC();principal:=access.PrincipalID(call.PrincipalID);siteID:=access.SiteID(payload.SiteID);expires:=accessExpiry(now,payload.ExpiresInSec)
	switch payload.Kind{
	case"ftps":material,materialErr:=access.NewSecretMaterial(secret);if materialErr!=nil{return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},materialErr};id:=access.FTPSAccountID(accessEdgeID("ftps-",call.TenantID,call.CommandID,payload.SiteID));username:="cp_"+accessEdgeID("",call.TenantID,payload.SiteID,payload.Label)[:24];permission:=access.FTPSReadWrite;if payload.Permission=="read_only"{permission=access.FTPSReadOnly};value,createErr:=edge.credentials.CreateFTPS(ctx,access.FTPSAccount{ID:id,SiteID:siteID,Username:username,Root:access.SiteRoot{SiteID:siteID,Kind:access.RootSite},Permission:permission,QuotaBytes:10<<30,TLSRequired:true,ExpiresAt:expires},&material);if createErr!=nil{return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},createErr};projection:=apiserver.AccessCredentialProjection{ID:string(value.ID),SiteID:string(value.SiteID),Label:payload.Label,Kind:"ftps",State:string(value.State),ExpiresAt:value.ExpiresAt,Generation:value.Generation};return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{OperationID:call.CommandID,State:string(value.State),Generation:value.Generation,Resource:projection},nil
	case"ssh_key":keyValue,parseErr:=access.ParsePublicKey(payload.PublicKey);if parseErr!=nil{return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},parseErr};keyID:=access.SSHKeyID(accessEdgeID("ssh-",call.TenantID,call.CommandID));key,registerErr:=edge.credentials.RegisterSSHKey(ctx,access.SSHKey{ID:keyID,TenantID:access.TenantID(tenant.String()),PrincipalID:principal,Name:payload.Label,PublicKey:keyValue});if registerErr!=nil{return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},registerErr};grantID:=access.AccessGrantID(accessEdgeID("grant-",call.TenantID,call.CommandID));grant,grantErr:=edge.credentials.Grant(ctx,access.AccessGrant{ID:grantID,SiteID:siteID,TenantID:access.TenantID(tenant.String()),PrincipalID:principal,SSHKeyID:key.ID,Protocol:access.ProtocolSFTP,Permission:accessPermission(payload.Permission),Root:access.SiteRoot{SiteID:siteID,Kind:access.RootSite},ExpiresAt:expires});if grantErr!=nil{_ = edge.credentials.RevokeSSHKey(ctx,key.ID);return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},grantErr};projection:=apiserver.AccessCredentialProjection{ID:string(grant.ID),SiteID:string(grant.SiteID),Label:payload.Label,Kind:"ssh_key",State:string(grant.State),ExpiresAt:grant.ExpiresAt,Generation:grant.Generation};return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{OperationID:call.CommandID,State:string(grant.State),Generation:grant.Generation,Resource:projection},nil
	case"terminal":grantID:=access.AccessGrantID(accessEdgeID("term-",call.TenantID,call.CommandID));grant,grantErr:=edge.credentials.Grant(ctx,access.AccessGrant{ID:grantID,SiteID:siteID,TenantID:access.TenantID(tenant.String()),PrincipalID:principal,Protocol:access.ProtocolTerminal,Permission:access.AccessTerminal,Root:access.SiteRoot{SiteID:siteID,Kind:access.RootSite},ExpiresAt:expires});if grantErr!=nil{return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},grantErr};projection:=apiserver.AccessCredentialProjection{ID:string(grant.ID),SiteID:string(grant.SiteID),Label:payload.Label,Kind:"terminal",State:string(grant.State),ExpiresAt:grant.ExpiresAt,Generation:grant.Generation};return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{OperationID:call.CommandID,State:string(grant.State),Generation:grant.Generation,Resource:projection},nil
	default:return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},access.ErrInvalidState}
}

func(edge *accessEdge)RotateCredential(ctx context.Context,call apiserver.EdgeCall,_ apiserver.AccessCredentialRotatePayload,secret []byte)(apiserver.EdgeMutation[apiserver.AccessCredentialProjection],error){account,err:=edge.store.LoadFTPS(ctx,access.FTPSAccountID(call.ResourceID));if err!=nil{return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},err};if _,err=edge.authorizeSite(ctx,call,string(account.SiteID));err!=nil{return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},err};if call.ExpectedGeneration!=0&&call.ExpectedGeneration!=account.Generation{return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},access.ErrStaleGeneration};material,err:=access.NewSecretMaterial(secret);if err!=nil{return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},err};account,err=edge.credentials.RotateFTPSPassword(ctx,account.ID,&material);if err!=nil{return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},err};projection:=apiserver.AccessCredentialProjection{ID:string(account.ID),SiteID:string(account.SiteID),Label:account.Username,Kind:"ftps",State:string(account.State),ExpiresAt:account.ExpiresAt,Generation:account.Generation};return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{OperationID:call.CommandID,State:string(account.State),Generation:account.Generation,Resource:projection},nil}

func(edge *accessEdge)RevokeCredential(ctx context.Context,call apiserver.EdgeCall)(apiserver.EdgeMutation[apiserver.AccessCredentialProjection],error){if account,err:=edge.store.LoadFTPS(ctx,access.FTPSAccountID(call.ResourceID));err==nil{if _,err=edge.authorizeSite(ctx,call,string(account.SiteID));err!=nil{return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},err};if call.ExpectedGeneration!=0&&call.ExpectedGeneration!=account.Generation{return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},access.ErrStaleGeneration};if err=edge.credentials.DeleteFTPS(ctx,account.ID);err!=nil{return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},err};account.Generation+=2;account.State=access.StateDeleted;projection:=apiserver.AccessCredentialProjection{ID:string(account.ID),SiteID:string(account.SiteID),Label:account.Username,Kind:"ftps",State:string(account.State),Generation:account.Generation};return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{OperationID:call.CommandID,State:string(account.State),Generation:account.Generation,Resource:projection},nil};grant,err:=edge.store.LoadAccessGrant(ctx,access.AccessGrantID(call.ResourceID));if err!=nil{return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},err};if grant.TenantID!=access.TenantID(call.TenantID)||grant.PrincipalID!=access.PrincipalID(call.PrincipalID){return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},access.ErrUnauthorized};if call.ExpectedGeneration!=0&&call.ExpectedGeneration!=grant.Generation{return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},access.ErrStaleGeneration};if err=edge.credentials.RevokeGrant(ctx,grant.ID);err!=nil{return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{},err};if grant.SSHKeyID!=""{_ = edge.credentials.RevokeSSHKey(ctx,grant.SSHKeyID)};grant.Generation++;grant.State=access.StateDeleted;kind:="ssh_key";if grant.Protocol==access.ProtocolTerminal{kind="terminal"};projection:=apiserver.AccessCredentialProjection{ID:string(grant.ID),SiteID:string(grant.SiteID),Label:string(grant.Protocol),Kind:kind,State:string(grant.State),Generation:grant.Generation};return apiserver.EdgeMutation[apiserver.AccessCredentialProjection]{OperationID:call.CommandID,State:string(grant.State),Generation:grant.Generation,Resource:projection},nil}

func(edge *accessEdge)IssueTerminal(ctx context.Context,call apiserver.EdgeCall,payload apiserver.AccessTerminalPayload)(apiserver.AccessTerminalGrant,error){grant,err:=edge.store.LoadAccessGrant(ctx,access.AccessGrantID(call.ResourceID));if err!=nil{return apiserver.AccessTerminalGrant{},err};if grant.TenantID!=access.TenantID(call.TenantID)||grant.PrincipalID!=access.PrincipalID(call.PrincipalID){return apiserver.AccessTerminalGrant{},access.ErrUnauthorized};session,err:=edge.credentials.OpenTerminal(ctx,access.TerminalRequest{GrantID:grant.ID,Columns:payload.Columns,Rows:payload.Rows,ClientNonce:payload.ClientNonce});if err!=nil{return apiserver.AccessTerminalGrant{},err};return apiserver.AccessTerminalGrant{ID:string(session.ID),Endpoint:session.Endpoint,OneTimeToken:session.OneTimeToken,HostKeyFingerprint:session.HostKeyFingerprint,ExpiresAt:session.ExpiresAt},nil}

func(edge *accessEdge)WriteFile(ctx context.Context,call apiserver.EdgeCall,payload apiserver.AccessFileWritePayload)(apiserver.EdgeMutation[struct{}],error){siteRaw:=payload.SiteID;if siteRaw==""{siteRaw=call.ResourceID};if payload.SiteID!=""&&call.ResourceID!=""&&payload.SiteID!=call.ResourceID{return apiserver.EdgeMutation[struct{}]{},access.ErrUnauthorized};tenant,err:=edge.authorizeSite(ctx,call,siteRaw);if err!=nil{return apiserver.EdgeMutation[struct{}]{},err};relative,err:=access.ParseRelativePath(payload.RelativePath);if err!=nil{return apiserver.EdgeMutation[struct{}]{},err};content,err:=base64.StdEncoding.Strict().DecodeString(payload.ContentBase64);if err!=nil{return apiserver.EdgeMutation[struct{}]{},access.ErrIntegrity};defer func(){for index:=range content{content[index]=0}}();root:=access.SiteRoot{SiteID:access.SiteID(siteRaw),Kind:access.RootSite};locator:=access.FileLocator{Root:root,Path:relative};kind:=access.FileWrite;if _,_,readErr:=edge.files.ReadEditor(ctx,locator,access.WriteCondition{});errors.Is(readErr,access.ErrNotFound){kind=access.FileCreate}else if readErr!=nil{return apiserver.EdgeMutation[struct{}]{},readErr};operationID:=access.FileOperationID(accessEdgeID("file-",call.CommandID,siteRaw,payload.RelativePath));receipt,err:=edge.files.Mutate(ctx,access.FileMutationCall{Operation:access.FileOperation{ID:operationID,Mutation:access.Mutation{CommandID:access.CommandID(call.CommandID),Actor:access.AuditActor{TenantID:access.TenantID(tenant.String()),PrincipalID:access.PrincipalID(call.PrincipalID)},At:edge.now().UTC()},Kind:kind,Destination:locator,State:access.OperationAdmitted},Metadata:access.FileMetadata{Mode:0640,Ownership:access.OwnershipSiteUser},Content:content,Condition:access.WriteCondition{IfMatch:payload.IfMatch,IfNoneMatch:kind==access.FileCreate}});if err!=nil{return apiserver.EdgeMutation[struct{}]{},err};return apiserver.EdgeMutation[struct{}]{OperationID:string(receipt.OperationID),State:string(access.OperationCommitted),Resource:struct{}{}},nil}

func(edge *accessEdge)IssueHostFilesystemSession(ctx context.Context,authorization access.HostFilesystemAuthorization,request access.HostFilesystemIssueRequest)(access.HostFilesystemSession,error){if edge==nil||edge.hostFilesystem==nil{return access.HostFilesystemSession{},access.ErrInvalidState};return edge.hostFilesystem.Issue(ctx,authorization,request)}
func(edge *accessEdge)ListHostFilesystem(ctx context.Context,authorization access.HostFilesystemAuthorization,session access.HostFilesystemSessionID,root access.HostFilesystemRootID,path access.HostFilesystemPath,page access.HostFilesystemPageRequest)(access.HostFilesystemPage,error){if edge==nil||edge.hostFilesystem==nil{return access.HostFilesystemPage{},access.ErrInvalidState};return edge.hostFilesystem.List(ctx,authorization,session,root,path,page)}
func(edge *accessEdge)StatHostFilesystem(ctx context.Context,authorization access.HostFilesystemAuthorization,session access.HostFilesystemSessionID,root access.HostFilesystemRootID,path access.HostFilesystemPath)(access.HostFilesystemEntry,error){if edge==nil||edge.hostFilesystem==nil{return access.HostFilesystemEntry{},access.ErrInvalidState};return edge.hostFilesystem.Stat(ctx,authorization,session,root,path)}
func(edge *accessEdge)ReadHostFilesystem(ctx context.Context,authorization access.HostFilesystemAuthorization,session access.HostFilesystemSessionID,root access.HostFilesystemRootID,path access.HostFilesystemPath,offset,length int64)(access.HostFilesystemRead,error){if edge==nil||edge.hostFilesystem==nil{return access.HostFilesystemRead{},access.ErrInvalidState};return edge.hostFilesystem.Read(ctx,authorization,session,root,path,offset,length)}

var _ apiserver.AccessEdgeService=(*accessEdge)(nil)
var _ apiserver.HostFilesystemEdgeService=(*accessEdge)(nil)
