//go:build linux

package main

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"net/url"
	"os"
	"runtime"
	"strconv"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/apiserver"
	"github.com/aonsyed/cyberpanel/platform/internal/apps"
	"github.com/aonsyed/cyberpanel/platform/internal/executor/siteops"
	"github.com/aonsyed/cyberpanel/platform/internal/hosting/provisioning"
	hostingservice "github.com/aonsyed/cyberpanel/platform/internal/hosting/service"
	"github.com/aonsyed/cyberpanel/platform/internal/hosting/site"
	"github.com/aonsyed/cyberpanel/platform/internal/hosting/sqlrepo"
	webcatalog "github.com/aonsyed/cyberpanel/platform/internal/webengine/catalog"
)

type applicationEdge struct {
	service   *apps.ApplicationService
	lifecycle *apps.LifecycleCoordinator
	wordpress *apps.WordPressManager
	autologin *apps.AutologinService
	bridge    *apps.AutologinBridgeManager
	store     apps.SQLRepository
	hosting   *sqlrepo.Repository
	client    *apps.LinuxApplicationClient
	catalog   *apps.PinnedCatalog
	authority *apps.LinuxRecipeCatalogAuthority
	secrets   *apps.ApplicationSecretIssuer
	target    apps.CatalogTarget
	scanner   apps.ScanCoordinator
	routes    *webcatalog.SQLCatalog
	now       func() time.Time
}

func newApplicationEdge(service *apps.ApplicationService,lifecycle *apps.LifecycleCoordinator,wordpress *apps.WordPressManager,autologin *apps.AutologinService,bridge *apps.AutologinBridgeManager,store apps.SQLRepository,hosting *sqlrepo.Repository,client *apps.LinuxApplicationClient,catalog *apps.PinnedCatalog,authority *apps.LinuxRecipeCatalogAuthority,secrets *apps.ApplicationSecretIssuer,edition siteops.EngineEdition,routes *webcatalog.SQLCatalog,now func()time.Time)(*applicationEdge,error){
	if service==nil||lifecycle==nil||wordpress==nil||autologin==nil||bridge==nil||store.DB==nil||hosting==nil||client==nil||catalog==nil||authority==nil||secrets==nil||routes==nil{return nil,apps.ErrInvalid};if now==nil{now=time.Now};target,err:=applicationCatalogTarget(edition);if err!=nil{return nil,err};scanner:=apps.ScanCoordinator{Store:store,Snapshots:client,Providers:map[string]apps.ScannerProvider{client.ID():client},Now:now};return &applicationEdge{service,lifecycle,wordpress,autologin,bridge,store,hosting,client,catalog,authority,secrets,target,scanner,routes,now},nil
}

func(edge *applicationEdge)ApplicationCapabilities()apiserver.ApplicationEdgeCapabilities{return apiserver.ApplicationEdgeCapabilities{List:true,Discover:true,Adopt:true,Install:true,Update:true,Remove:true,Scan:true,Autologin:edge!=nil&&edge.autologin!=nil&&edge.bridge!=nil,CachePurge:true}}

func(edge *applicationEdge)ListApplications(ctx context.Context,call apiserver.EdgeCall,page apiserver.EdgePagePayload)(apiserver.EdgePage[apiserver.ApplicationProjection],error){if call.TenantID==""{return apiserver.EdgePage[apiserver.ApplicationProjection]{},apps.ErrPolicyDenied};items,next,err:=edge.store.ListInstallations(ctx,apps.TenantID(call.TenantID),"",page.Limit,page.Cursor);if err!=nil{return apiserver.EdgePage[apiserver.ApplicationProjection]{},err};result:=make([]apiserver.ApplicationProjection,0,len(items));for _,item:=range items{projection,projectErr:=edge.projection(ctx,item);if projectErr!=nil{return apiserver.EdgePage[apiserver.ApplicationProjection]{},projectErr};result=append(result,projection)};return apiserver.EdgePage[apiserver.ApplicationProjection]{Items:result,NextCursor:next},nil}

func(edge *applicationEdge)DiscoverApplications(ctx context.Context,call apiserver.EdgeCall,payload apiserver.ApplicationDiscoveryEdgePayload)(apiserver.ApplicationDiscoveryEdgeResult,error){tenantID,siteID,aggregate,_,err:=edge.site(ctx,call.TenantID,call.ResourceID);if err!=nil{return apiserver.ApplicationDiscoveryEdgeResult{},err};if call.ExpectedGeneration==0||aggregate.Generation()!=call.ExpectedGeneration{return apiserver.ApplicationDiscoveryEdgeResult{},apps.ErrStaleGeneration};scope,err:=edge.client.ResolveSiteBinding(ctx,tenantID,siteID);if err!=nil{return apiserver.ApplicationDiscoveryEdgeResult{},err};root,err:=apps.ParseRelativePath(payload.Root);if err!=nil{return apiserver.ApplicationDiscoveryEdgeResult{},apps.ErrInvalid};kinds:=make([]apps.ApplicationKind,0,len(payload.Applications));seen:=map[apps.ApplicationKind]bool{};for _,value:=range payload.Applications{kind,kindErr:=applicationKind(value);if kindErr!=nil||kind==apps.ApplicationWordPress||seen[kind]{return apiserver.ApplicationDiscoveryEdgeResult{},apps.ErrInvalid};seen[kind]=true;kinds=append(kinds,kind)};candidates,err:=edge.lifecycle.Discover(ctx,apps.DiscoveryRequest{CommandID:apps.CommandID(call.CommandID),TenantID:tenantID,SiteID:siteID,SiteUID:scope.SiteUID,SiteGeneration:scope.ResourceGeneration,IsolationProfile:scope.IsolationProfile,Root:root,Kinds:kinds,RuntimeID:string(aggregate.PHPProfile()),MaximumDepth:payload.MaximumDepth,MaximumCandidates:payload.MaximumCandidates});if err!=nil{return apiserver.ApplicationDiscoveryEdgeResult{},err};return apiserver.ApplicationDiscoveryEdgeResult{Candidates:candidates,Generation:aggregate.Generation()},nil}

func(edge *applicationEdge)AdoptApplication(ctx context.Context,call apiserver.EdgeCall,payload apiserver.ApplicationAdoptEdgePayload)(apiserver.EdgeMutation[apiserver.ApplicationProjection],error){tenantID,siteID,aggregate,hostname,err:=edge.site(ctx,call.TenantID,call.ResourceID);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};if call.ExpectedGeneration==0||aggregate.Generation()!=call.ExpectedGeneration{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},apps.ErrStaleGeneration};if payload.Candidate.Validate()!=nil||payload.Candidate.RuntimeID!=string(aggregate.PHPProfile()){return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},apps.ErrPolicyDenied};target,err:=edge.targetForSite(aggregate);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};reference,_,err:=edge.resolveRecipe(ctx,payload.RecipeID,payload.Candidate.Kind,payload.Candidate.Version,target);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};scope,err:=edge.client.ResolveSiteBinding(ctx,tenantID,siteID);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};installationID:=apps.DerivedAdoptionInstallationID(tenantID,siteID,payload.Candidate);releaseID:=apps.DerivedAdoptionReleaseID(installationID,payload.Candidate);installation,err:=edge.lifecycle.Adopt(ctx,apps.AdoptionRequest{CommandID:apps.CommandID(call.CommandID),TenantID:tenantID,ProjectID:apps.ProjectID(aggregate.ProjectID().String()),SiteID:siteID,SiteUID:scope.SiteUID,SiteGeneration:scope.ResourceGeneration,IsolationProfile:scope.IsolationProfile,InstallationID:installationID,ReleaseID:releaseID,Recipe:reference,CatalogTarget:target,Candidate:payload.Candidate,RuntimeID:payload.Candidate.RuntimeID,CanonicalURL:"https://"+hostname+"/"});if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};projection,err:=edge.projection(ctx,installation);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};return apiserver.EdgeMutation[apiserver.ApplicationProjection]{OperationID:call.CommandID,State:string(installation.State),Generation:installation.Generation,Resource:projection},nil}

func(edge *applicationEdge)InstallApplication(ctx context.Context,call apiserver.EdgeCall,payload apiserver.ApplicationInstallEdgePayload,material apiserver.ApplicationInstallMaterial)(apiserver.EdgeMutation[apiserver.ApplicationProjection],error){
	tenantID,siteID,aggregate,hostname,err:=edge.site(ctx,call.TenantID,payload.SiteID)
	if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err}
	target,err:=edge.targetForSite(aggregate)
	if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err}
	kind,err:=applicationKind(payload.Application)
	if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err}
	if (len(material.DatabaseClientCertificate)==0)!=(len(material.DatabaseClientKey)==0) || len(material.DatabaseClientCertificate)>0 && kind!=apps.ApplicationWordPress { return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},apps.ErrInvalid }
	if len(material.DatabaseClientCertificate)>0 { if err:=apps.ValidateApplicationDatabaseClientIdentity(material.DatabaseClientCertificate,material.DatabaseClientKey,edge.now());err!=nil { return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err } }
	reference,_,err:=edge.resolveRecipe(ctx,payload.RecipeID,kind,payload.Version,target)
	if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err}
	scope,err:=edge.client.ResolveSiteBinding(ctx,tenantID,siteID)
	if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err}
	installationID:=apps.InstallationID(applicationEdgeID("app",call.CommandID,payload.SiteID,string(reference.ID)))
	releaseID:=apps.ReleaseID(applicationEdgeID("release",string(installationID),reference.RecipeDigest))
	locale:=strings.TrimSpace(payload.Locale);if locale==""{locale="en_US"}
	timezone:=strings.TrimSpace(payload.Timezone);if timezone==""{timezone="UTC"}
	title:=strings.TrimSpace(payload.Title);if title==""{title=hostname}
	spec:=provisioning.RuntimeSpec{}
	root,err:=applicationServedRoot(spec.ApplicationRoot(),spec.DocumentRoot());if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err}
	scheme,err:=edge.routes.SiteScheme(ctx,hostingservice.CommandScope{TenantID:aggregate.TenantID(),SiteID:aggregate.ID()},hostname,aggregate.Generation());if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err}
	request:=apps.InstallRequest{CommandID:apps.CommandID(call.CommandID),TenantID:tenantID,ProjectID:apps.ProjectID(aggregate.ProjectID().String()),SiteID:siteID,SiteUID:scope.SiteUID,SiteGeneration:scope.ResourceGeneration,IsolationProfile:scope.IsolationProfile,InstallationID:installationID,DatabaseInstanceID:apps.DatabaseInstanceID(payload.DatabaseInstanceID),Recipe:reference,CatalogTarget:target,Root:root,RuntimeID:string(aggregate.PHPProfile()),CanonicalURL:scheme+"://"+hostname+"/",Administrator:apps.AdministratorBootstrap{Username:payload.AdministratorUsername,Email:payload.AdministratorEmail,DisplayName:payload.AdministratorDisplayName,PasswordRef:apps.SecretRef(apps.ApplicationManagedSecretID("administrator",installationID).String())},Title:title,Locale:locale,Timezone:timezone,ReleaseID:releaseID}
	if len(material.DatabaseClientCertificate)>0 { request.DatabaseClientIdentityRef=apps.SecretRef(apps.ApplicationManagedSecretID("database_tls",installationID).String()) }
	if err:=request.Validate(edge.now());err!=nil { return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err }
	administratorSecret,err:=edge.secrets.EnrollAdministratorSecret(ctx,tenantID,siteID,installationID,material.AdministratorPassword)
	if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err}
	request.Administrator.PasswordRef=administratorSecret
	defer func(){cleanup,cancel:=context.WithTimeout(context.WithoutCancel(ctx),30*time.Second);defer cancel();_=edge.secrets.RevokeApplicationSecret(cleanup,administratorSecret)}()
	if request.DatabaseClientIdentityRef!="" {
		ref,err:=edge.secrets.EnrollDatabaseClientIdentity(ctx,tenantID,siteID,installationID,material.DatabaseClientCertificate,material.DatabaseClientKey)
		if err!=nil { return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err }
		request.DatabaseClientIdentityRef=ref
	}
	installation,err:=edge.service.Install(ctx,request)
	if err!=nil {
		// Never revoke a replay's identity while the original install is still
		// running or needs recovery. Only a durable terminal failure permits it.
		if request.DatabaseClientIdentityRef!="" {
			cleanup,cancel:=context.WithTimeout(context.WithoutCancel(ctx),30*time.Second);defer cancel()
			operation,loadErr:=edge.store.LoadOperation(cleanup,request.CommandID)
			if loadErr==nil && (operation.State==apps.OperationFailed || operation.State==apps.OperationCompensated) { err=errors.Join(err,edge.secrets.RevokeApplicationSecret(cleanup,request.DatabaseClientIdentityRef)) }
		}
		return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err
	}
	projection,err:=edge.projection(ctx,installation)
	if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err}
	return apiserver.EdgeMutation[apiserver.ApplicationProjection]{OperationID:call.CommandID,State:string(installation.State),Generation:installation.Generation,Resource:projection},nil
}

func(edge *applicationEdge)UpdateApplication(ctx context.Context,call apiserver.EdgeCall,payload apiserver.ApplicationUpdateEdgePayload)(apiserver.EdgeMutation[apiserver.ApplicationProjection],error){installation,err:=edge.installation(ctx,call);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};tenant,err:=site.NewTenantID(string(installation.TenantID));if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},apps.ErrIntegrity};siteID,err:=site.NewSiteID(string(installation.SiteID));if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},apps.ErrIntegrity};aggregate,err:=edge.hosting.Load(ctx,tenant,siteID);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};target,err:=edge.targetForSite(aggregate);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};reference,definition,err:=edge.resolveRecipe(ctx,payload.RecipeID,installation.Kind,payload.Version,target);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};scope,err:=edge.client.ResolveSiteBinding(ctx,installation.TenantID,installation.SiteID);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};identity:=applicationEdgeID("update",call.CommandID,string(installation.ID),reference.RecipeDigest);deployment,err:=edge.service.Update(ctx,apps.UpdateRequest{CommandID:apps.CommandID(call.CommandID),DeploymentID:apps.DeploymentID(identity),InstallationID:installation.ID,ExpectedGeneration:call.ExpectedGeneration,TargetRecipe:reference,CatalogTarget:target,TargetReleaseID:apps.ReleaseID(applicationEdgeID("release",identity,reference.RecipeDigest)),TargetContentDigest:definition.Artifact.Digest,SiteGeneration:scope.ResourceGeneration,IsolationProfile:scope.IsolationProfile});if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};installation,err=edge.store.LoadInstallation(ctx,installation.ID);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};projection,err:=edge.projection(ctx,installation);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};return apiserver.EdgeMutation[apiserver.ApplicationProjection]{OperationID:string(deployment.ID),State:string(deployment.State),Generation:installation.Generation,Resource:projection},nil}

func(edge *applicationEdge)RemoveApplication(ctx context.Context,call apiserver.EdgeCall)(apiserver.EdgeMutation[apiserver.ApplicationProjection],error){installation,err:=edge.installation(ctx,call);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};scope,err:=edge.client.ResolveSiteBinding(ctx,installation.TenantID,installation.SiteID);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};installation,err=edge.lifecycle.Remove(ctx,apps.RemovalRequest{CommandID:apps.CommandID(call.CommandID),InstallationID:installation.ID,ExpectedGeneration:call.ExpectedGeneration,Disposition:apps.RemovalPurge,SiteGeneration:scope.ResourceGeneration,IsolationProfile:scope.IsolationProfile});if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};projection,err:=edge.projection(ctx,installation);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};return apiserver.EdgeMutation[apiserver.ApplicationProjection]{OperationID:call.CommandID,State:string(installation.State),Generation:installation.Generation,Resource:projection},nil}

func(edge *applicationEdge)ScanApplication(ctx context.Context,call apiserver.EdgeCall,payload apiserver.ApplicationScanPayload)(apiserver.EdgeMutation[apiserver.ApplicationProjection],error){installation,err:=edge.installation(ctx,call);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};provider:=payload.ProviderID;if provider==""{provider=edge.client.ID()};if provider!=edge.client.ID(){return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},apps.ErrUnsupported};mode:=apps.ScanQuick;duration:=15*time.Minute;files:=uint64(200000);bytes:=uint64(64<<30);switch payload.Mode{case "","quick":case "full","deep":mode=apps.ScanFull;duration=time.Hour;files=1000000;bytes=256<<30;case "integrity","integrity_comparison":mode=apps.ScanIntegrity;duration=time.Hour;files=1000000;bytes=256<<30;default:return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},apps.ErrInvalid};scope,err:=edge.client.ResolveExecutionScope(ctx,installation);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};now:=edge.now().UTC();identity:=applicationEdgeID("scan",call.CommandID,string(installation.ID));run:=apps.ScanRun{ID:apps.ScanRunID(identity),CommandID:apps.CommandID(call.CommandID),TenantID:installation.TenantID,SiteID:installation.SiteID,InstallationID:installation.ID,Mode:mode,ProviderID:provider,ProviderKind:edge.client.Kind(),RulesVersion:"cyberpanel-local-2026.08.1",EngineVersion:"archive-stream-v1",Budget:apps.ScanBudget{MaximumDuration:duration,MaximumFiles:files,MaximumBytes:bytes,MaximumExpandedBytes:bytes*2,MaximumArchiveDepth:8,MaximumMemoryBytes:256<<20,MaximumCPUPercent:50,MaximumIOBytesPerSecond:128<<20},State:apps.ScanAdmitted,CreatedAt:now,UpdatedAt:now};scanContext,cancel:=context.WithTimeout(ctx,duration);result,err:=edge.scanner.Run(scanContext,run,scope,nil);cancel();if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};projection,err:=edge.projection(ctx,installation);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};return apiserver.EdgeMutation[apiserver.ApplicationProjection]{OperationID:string(result.RunID),State:string(apps.ScanCompleted),Generation:installation.Generation,Resource:projection},nil}

func(edge *applicationEdge)IssueWordPressAutologin(ctx context.Context,call apiserver.EdgeCall,payload apiserver.ApplicationAutologinPayload)(apiserver.ApplicationGrant,error){
	installation,err:=edge.installation(ctx,call);if err!=nil{return apiserver.ApplicationGrant{},err}
	if installation.Kind!=apps.ApplicationWordPress||call.ExpectedGeneration==0||call.ExpectedGeneration!=installation.Generation||call.SessionID==""||!strings.HasPrefix(call.Origin,"https://")||len(call.CSRFBinding)!=sha256.Size*2||payload.WordPressUserID==0||payload.TTLSeconds<30||payload.TTLSeconds>120{return apiserver.ApplicationGrant{},apps.ErrPolicyDenied}
	projection,err:=edge.projection(ctx,installation);if err!=nil{return apiserver.ApplicationGrant{},err};if projection.Hostname==""{return apiserver.ApplicationGrant{},apps.ErrConflict}
	scope,err:=edge.client.ResolveExecutionScope(ctx,installation);if err!=nil{return apiserver.ApplicationGrant{},err}
	bridgeRequest:=apps.AutologinBridgeRequest{Scope:scope,InstallationID:installation.ID,BridgeDigest:payload.BridgeDigest,BridgeSignature:payload.BridgeSignature,SigningKeyID:payload.SigningKeyID,Endpoint:edge.autologin.Endpoint}
	bridgeCommand:=apps.CommandID(applicationEdgeID("autologin-bridge",call.CommandID,string(installation.ID),payload.BridgeDigest));if err=edge.bridge.Install(ctx,bridgeCommand,bridgeRequest);err!=nil{return apiserver.ApplicationGrant{},err}
	audience:="https://"+projection.Hostname
	grant,credential,err:=edge.autologin.Issue(ctx,apps.LoginGrantRequest{ID:apps.LoginGrantID(applicationEdgeID("login-grant",call.CommandID,string(installation.ID))),TenantID:installation.TenantID,SiteID:installation.SiteID,InstallationID:installation.ID,WordPressUserID:payload.WordPressUserID,Audience:audience,Origin:call.Origin,CSRFBinding:call.CSRFBinding,TTL:time.Duration(payload.TTLSeconds)*time.Second});if err!=nil{return apiserver.ApplicationGrant{},err}
	values:=url.Values{"grant_id":[]string{string(credential.GrantID)},"secret":[]string{credential.Secret},"audience":[]string{grant.Audience},"origin":[]string{grant.Origin},"csrf_binding":[]string{call.CSRFBinding},"site_id":[]string{string(grant.SiteID)},"installation_id":[]string{string(grant.InstallationID)},"wordpress_user_id":[]string{strconv.FormatUint(grant.WordPressUserID,10)}}
	target:=url.URL{Scheme:"https",Host:projection.Hostname,Path:"/wp-json/cyberpanel/v1/autologin",Fragment:values.Encode()};credential.Secret=""
	return apiserver.ApplicationGrant{URL:target.String(),ExpiresAt:grant.ExpiresAt},nil
}

func(edge *applicationEdge)PurgeWordPressCache(ctx context.Context,call apiserver.EdgeCall,payload apiserver.ApplicationCachePurgePayload)(apiserver.EdgeMutation[apiserver.ApplicationProjection],error){installation,err:=edge.installation(ctx,call);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};scope,err:=edge.client.ResolveSiteBinding(ctx,installation.TenantID,installation.SiteID);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};purge:=apps.CachePurgeScope(payload.Scope);if purge==""{purge=apps.PurgeAll};if err=edge.wordpress.PurgeLSCache(ctx,apps.LSCachePurgeRequest{CommandID:apps.CommandID(call.CommandID),InstallationID:installation.ID,PurgeScope:purge,Values:append([]string(nil),payload.Values...),SiteGeneration:scope.ResourceGeneration,IsolationProfile:scope.IsolationProfile});err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};projection,err:=edge.projection(ctx,installation);if err!=nil{return apiserver.EdgeMutation[apiserver.ApplicationProjection]{},err};return apiserver.EdgeMutation[apiserver.ApplicationProjection]{OperationID:call.CommandID,State:"completed",Generation:installation.Generation,Resource:projection},nil}

func(edge *applicationEdge)installation(ctx context.Context,call apiserver.EdgeCall)(apps.ApplicationInstallation,error){if call.TenantID==""{return apps.ApplicationInstallation{},apps.ErrPolicyDenied};installation,err:=edge.store.LoadInstallation(ctx,apps.InstallationID(call.ResourceID));if err!=nil{return apps.ApplicationInstallation{},err};if string(installation.TenantID)!=call.TenantID{return apps.ApplicationInstallation{},apps.ErrNotFound};return installation,nil}
func(edge *applicationEdge)site(ctx context.Context,tenantRaw,siteRaw string)(apps.TenantID,apps.SiteID,site.Site,string,error){tenant,err:=site.NewTenantID(tenantRaw);if err!=nil{return "","",site.Site{},"",apps.ErrInvalid};siteID,err:=site.NewSiteID(siteRaw);if err!=nil{return "","",site.Site{},"",apps.ErrInvalid};aggregate,err:=edge.hosting.Load(ctx,tenant,siteID);if err!=nil{return "","",site.Site{},"",err};hostname:="";for _,binding:=range aggregate.Bindings(){if binding.Kind==site.BindingPrimary{hostname=binding.Hostname.String();break}};if hostname==""||aggregate.Lifecycle()!=site.LifecycleActive{return "","",site.Site{},"",apps.ErrConflict};return apps.TenantID(tenant.String()),apps.SiteID(siteID.String()),aggregate,hostname,nil}
func(edge *applicationEdge)projection(ctx context.Context,installation apps.ApplicationInstallation)(apiserver.ApplicationProjection,error){tenant,err:=site.NewTenantID(string(installation.TenantID));if err!=nil{return apiserver.ApplicationProjection{},apps.ErrIntegrity};siteID,err:=site.NewSiteID(string(installation.SiteID));if err!=nil{return apiserver.ApplicationProjection{},apps.ErrIntegrity};aggregate,err:=edge.hosting.Load(ctx,tenant,siteID);if err!=nil{return apiserver.ApplicationProjection{},err};hostname:="";for _,binding:=range aggregate.Bindings(){if binding.Kind==site.BindingPrimary{hostname=binding.Hostname.String();break}};updates:=uint64(0);inventory,inventoryErr:=edge.store.LoadInventory(ctx,installation.ID);if inventoryErr==nil{for _,component:=range inventory.Components{if component.UpdateVersion!=""{updates++}}}else if !errors.Is(inventoryErr,apps.ErrNotFound){return apiserver.ApplicationProjection{},inventoryErr};health:=string(installation.Health.State);if health==""{health=string(installation.State)};return apiserver.ApplicationProjection{ID:string(installation.ID),SiteID:string(installation.SiteID),Hostname:hostname,Type:string(installation.Kind),Version:installation.Recipe.ProductVersion,Health:health,Updates:updates,Generation:installation.Generation,UpdatedAt:installation.UpdatedAt},nil}
func(edge *applicationEdge)targetForSite(aggregate site.Site)(apps.CatalogTarget,error){target:=edge.target;version,err:=applicationPHPVersion(aggregate.PHPProfile());if err!=nil{return target,err};target.PHPVersion=version;return target,nil}
func(edge *applicationEdge)resolveRecipe(ctx context.Context,recipeID string,kind apps.ApplicationKind,version string,target apps.CatalogTarget)(apps.RecipeReference,apps.ApplicationDefinition,error){if recipeID!=""{reference,err:=edge.authority.ReferenceByID(ctx,apps.RecipeID(recipeID));if err!=nil{return apps.RecipeReference{},apps.ApplicationDefinition{},err};definition,err:=edge.catalog.Resolve(ctx,reference,target);if err!=nil{return apps.RecipeReference{},apps.ApplicationDefinition{},err};if definition.Kind!=kind||version!=""&&reference.ProductVersion!=version{return apps.RecipeReference{},apps.ApplicationDefinition{},apps.ErrConflict};return reference,definition,nil};if version==""{return apps.RecipeReference{},apps.ApplicationDefinition{},apps.ErrInvalid};references,err:=edge.authority.References(ctx);if err!=nil{return apps.RecipeReference{},apps.ApplicationDefinition{},err};var selected apps.RecipeReference;var definition apps.ApplicationDefinition;for _,reference:=range references{if reference.ProductVersion!=version{continue};candidate,resolveErr:=edge.catalog.Resolve(ctx,reference,target);if errors.Is(resolveErr,apps.ErrUnsupported){continue};if resolveErr!=nil{return apps.RecipeReference{},apps.ApplicationDefinition{},resolveErr};if candidate.Kind!=kind{continue};if selected.ID!=""{return apps.RecipeReference{},apps.ApplicationDefinition{},apps.ErrConflict};selected,definition=reference,candidate};if selected.ID==""{return apps.RecipeReference{},apps.ApplicationDefinition{},apps.ErrRecipeUnavailable};return selected,definition,nil}

func applicationKind(value string)(apps.ApplicationKind,error){switch value{case "wordpress":return apps.ApplicationWordPress,nil;case "joomla":return apps.ApplicationJoomla,nil;case "prestashop":return apps.ApplicationPrestaShop,nil;case "magento","magento_open_source":return apps.ApplicationMagento,nil;case "mautic":return apps.ApplicationMautic,nil;default:return "",apps.ErrInvalid}}
func applicationCatalogTarget(edition siteops.EngineEdition)(apps.CatalogTarget,error){target:=apps.CatalogTarget{};switch edition{case siteops.EditionOpenLiteSpeed:target.WebEngine=apps.EngineOpenLiteSpeed;case siteops.EditionLiteSpeedEnterprise:target.WebEngine=apps.EngineLiteSpeedEnterprise;default:return target,apps.ErrUnsupported};switch runtime.GOARCH{case "amd64":target.Architecture=apps.ArchitectureAMD64;case "arm64":target.Architecture=apps.ArchitectureARM64;default:return target,apps.ErrUnsupported};raw,err:=os.ReadFile("/etc/os-release");if err!=nil||len(raw)>64<<10{return target,apps.ErrUnsupported};values:=map[string]string{};for _,line:=range strings.Split(string(raw),"\n"){key,value,found:=strings.Cut(line,"=");if found{values[key]=strings.Trim(strings.TrimSpace(value),"\"")}};switch values["ID"]{case "ubuntu":if values["VERSION_ID"]!="24.04"{return target,apps.ErrUnsupported};target.OperatingSystem=apps.OSUbuntuNoble;case "almalinux":if !strings.HasPrefix(values["VERSION_ID"],"9"){return target,apps.ErrUnsupported};target.OperatingSystem=apps.OSAlmaLinux9;default:return target,apps.ErrUnsupported};return target,nil}
func applicationPHPVersion(profile site.PHPProfile)(string,error){switch profile{case site.PHPProfile82:return "8.2",nil;case site.PHPProfile83:return "8.3",nil;case site.PHPProfile84:return "8.4",nil;default:return "",apps.ErrUnsupported}}
func applicationEdgeID(prefix string,values ...string)string{hash:=sha256.New();for _,value:=range values{_,_=hash.Write([]byte(value));_,_=hash.Write([]byte{0})};return prefix+"-"+hex.EncodeToString(hash.Sum(nil))[:48]}

var _ apiserver.ApplicationEdgeService=(*applicationEdge)(nil)
var _ apiserver.ApplicationEdgeCapabilityProvider=(*applicationEdge)(nil)
