//go:build linux

package main

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"runtime"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/apiserver"
	"github.com/aonsyed/cyberpanel/platform/internal/containers"
)

type containerEdgeRepository interface{ListWorkloads(context.Context,containers.ID)([]containers.Workload,error);Workload(context.Context,containers.ID,containers.ID)(containers.Workload,error)}
type containerEdge struct{service *containers.Service;repository containerEdgeRepository;broker containers.Broker;now func()time.Time}

func newContainerEdge(service *containers.Service,repository containerEdgeRepository,broker containers.Broker)(apiserver.ContainerEdgeService,error){if service==nil||repository==nil||broker==nil{return nil,errors.New("container edge dependencies are required")};return &containerEdge{service:service,repository:repository,broker:broker,now:time.Now},nil}

func containerEdgeGrant(tenant,resource containers.ID,operation,command string,generation uint64,now time.Time)containers.CommandMeta{sum:=sha256.Sum256([]byte(tenant.String()+"\x00"+resource.String()+"\x00"+operation+"\x00"+command));fence:=generation+1;if fence==0{fence=1};return containers.CommandMeta{CommandID:command,Grant:containers.Grant{TenantID:tenant,ResourceID:resource,Operation:operation,AuthzEpoch:1,ExpiresAt:now.Add(2*time.Minute),Digest:hex.EncodeToString(sum[:])},ExpectedGeneration:generation,Fence:containers.FenceToken(fence)}}
func containerProjection(value containers.Workload)apiserver.ContainerProjection{return apiserver.ContainerProjection{ID:value.ID.String(),SiteID:value.SiteID.String(),Name:value.Name,Image:value.Spec.Image.Registry+"/"+value.Spec.Image.Repository+"@"+value.Spec.Image.Digest,Lifecycle:string(value.ObservedLifecycle),Health:string(value.ObservedHealth),RestartCount:value.RestartCount,Generation:value.Generation,UpdatedAt:value.UpdatedAt}}
func containerTenant(raw string)(containers.ID,error){return containers.NewID(strings.ToLower(raw))}

func(edge *containerEdge)ListWorkloads(ctx context.Context,call apiserver.EdgeCall,page apiserver.EdgePagePayload)(apiserver.EdgePage[apiserver.ContainerProjection],error){tenant,err:=containerTenant(call.TenantID);if err!=nil{return apiserver.EdgePage[apiserver.ContainerProjection]{},err};values,err:=edge.repository.ListWorkloads(ctx,tenant);if err!=nil{return apiserver.EdgePage[apiserver.ContainerProjection]{},err};start:=0;if page.Cursor!=""{for start<len(values)&&values[start].ID.String()<=page.Cursor{start++}};limit:=int(page.Limit);if limit==0{limit=100};end:=start+limit;if end>len(values){end=len(values)};items:=make([]apiserver.ContainerProjection,0,end-start);for _,value:=range values[start:end]{grant:=containerEdgeGrant(tenant,value.ID,"workload.reconcile",call.CommandID+"-"+value.ID.String(),value.Generation,edge.now().UTC()).Grant;observed,observeErr:=edge.service.Reconcile(ctx,tenant,value.ID,grant);if observeErr!=nil{return apiserver.EdgePage[apiserver.ContainerProjection]{},observeErr};items=append(items,containerProjection(observed))};next:="";if end<len(values)&&end>start{next=values[end-1].ID.String()};return apiserver.EdgePage[apiserver.ContainerProjection]{Items:items,NextCursor:next,Total:uint64(len(values))},nil}

func parseContainerEdgeImage(value,platform string)(containers.ImageReference,error){if value==""||strings.ContainsAny(value," \t\r\n")||strings.Count(value,"@")!=1{return containers.ImageReference{},fmt.Errorf("%w: digest-pinned local image required",containers.ErrPolicy)};separator:=strings.LastIndex(value,"@sha256:");if separator<1||len(value[separator+8:])!=64{return containers.ImageReference{},fmt.Errorf("%w: tag-only images are not accepted",containers.ErrPolicy)};name:=value[:separator];if colon:=strings.LastIndex(name,":");colon>strings.LastIndex(name,"/"){return containers.ImageReference{},fmt.Errorf("%w: tagged image references are not accepted",containers.ErrPolicy)};parts:=strings.Split(name,"/");registryName:="docker.io";repository:=name;if len(parts)==1{repository="library/"+name}else if strings.Contains(parts[0],".")||strings.Contains(parts[0],":")||parts[0]=="localhost"{registryName=parts[0];repository=strings.Join(parts[1:],"/")};reference:=containers.ImageReference{Registry:registryName,Repository:repository,Digest:value[separator+1:],Platform:platform};if reference.Validate()!=nil{return containers.ImageReference{},containers.ErrInvalid};return reference,nil}
func containerEdgeID(prefix string,values ...string)(containers.ID,error){sum:=sha256.Sum256([]byte(strings.Join(values,"\x00")));return containers.NewID(prefix+hex.EncodeToString(sum[:24]))}

func(edge *containerEdge)CreateWorkload(ctx context.Context,call apiserver.EdgeCall,payload apiserver.ContainerCreateEdgePayload)(apiserver.EdgeMutation[apiserver.ContainerProjection],error){tenant,err:=containerTenant(call.TenantID);if err!=nil{return apiserver.EdgeMutation[apiserver.ContainerProjection]{},err};siteID,err:=containers.NewID(strings.ToLower(payload.SiteID));if err!=nil{return apiserver.EdgeMutation[apiserver.ContainerProjection]{},err};platform:="linux/amd64";if runtime.GOARCH=="arm64"{platform="linux/arm64"};image,err:=parseContainerEdgeImage(payload.Image,platform);if err!=nil{return apiserver.EdgeMutation[apiserver.ContainerProjection]{},err};workloadID,err:=containerEdgeID("work_",call.TenantID,call.CommandID,payload.SiteID);if err!=nil{return apiserver.EdgeMutation[apiserver.ContainerProjection]{},err};now:=edge.now().UTC();memoryHigh:=payload.MemoryBytes*9/10;spec:=containers.WorkloadSpec{Image:image,CommandID:"cmd_default",WorkingDirectory:"/app",User:containers.RuntimeUser{UID:1000,GID:1000},Restart:containers.RestartUnlessStopped,Update:containers.UpdateManual,Health:containers.HealthCheck{Kind:"exec",CommandID:"health_default",Interval:30*time.Second,Timeout:5*time.Second,Successes:1,Failures:3},Limits:containers.ResourceLimits{CPUQuotaMicros:100000,CPUPeriodMicros:100000,MemoryHighBytes:memoryHigh,MemoryMaxBytes:payload.MemoryBytes,SwapMaxBytes:payload.MemoryBytes,PIDsMax:512,StorageBytes:10<<30,Inodes:1000000},Security:containers.CapabilityPolicy{NoNewPrivileges:true,ReadOnlyRoot:true,DropAllCapabilities:true,SeccompProfile:"runtime/default",MACProfile:"panel/tenant",AllowPublicEgress:true}};value,result,err:=edge.service.ApplyWorkload(ctx,containers.ApplyWorkloadCommand{Meta:containerEdgeGrant(tenant,workloadID,"workload.apply",call.CommandID,0,now),WorkloadID:workloadID,ProjectID:siteID,SiteID:siteID,Name:"workload-"+workloadID.String()[5:17],Tier:containers.TierTenantRootless,Spec:spec});if err!=nil{return apiserver.EdgeMutation[apiserver.ContainerProjection]{},err};projection:=containerProjection(value);return apiserver.EdgeMutation[apiserver.ContainerProjection]{OperationID:string(result.EffectID),State:result.Status,Generation:value.Generation,Resource:projection},nil}

func(edge *containerEdge)load(ctx context.Context,call apiserver.EdgeCall)(containers.ID,containers.ID,containers.Workload,error){tenant,err:=containerTenant(call.TenantID);if err!=nil{return "","",containers.Workload{},err};id,err:=containers.NewID(strings.ToLower(call.ResourceID));if err!=nil{return "","",containers.Workload{},err};value,err:=edge.repository.Workload(ctx,tenant,id);return tenant,id,value,err}
func(edge *containerEdge)RestartWorkload(ctx context.Context,call apiserver.EdgeCall)(apiserver.EdgeMutation[apiserver.ContainerProjection],error){tenant,id,value,err:=edge.load(ctx,call);if err!=nil{return apiserver.EdgeMutation[apiserver.ContainerProjection]{},err};if call.ExpectedGeneration==0||value.Generation!=call.ExpectedGeneration{return apiserver.EdgeMutation[apiserver.ContainerProjection]{},containers.ErrStale};restarted,result,err:=edge.service.RestartWorkload(ctx,containers.RestartWorkloadCommand{Meta:containerEdgeGrant(tenant,id,"workload.restart",call.CommandID,value.Generation,edge.now().UTC()),WorkloadID:id});if err!=nil{return apiserver.EdgeMutation[apiserver.ContainerProjection]{},err};projection:=containerProjection(restarted);return apiserver.EdgeMutation[apiserver.ContainerProjection]{OperationID:string(result.EffectID),State:result.Status,Generation:restarted.Generation,Resource:projection},nil}
func(edge *containerEdge)DeleteWorkload(ctx context.Context,call apiserver.EdgeCall)(apiserver.EdgeMutation[apiserver.ContainerProjection],error){tenant,id,value,err:=edge.load(ctx,call);if err!=nil{return apiserver.EdgeMutation[apiserver.ContainerProjection]{},err};if call.ExpectedGeneration==0||value.Generation!=call.ExpectedGeneration{return apiserver.EdgeMutation[apiserver.ContainerProjection]{},containers.ErrStale};deleted,result,err:=edge.service.SetLifecycle(ctx,containers.LifecycleCommand{Meta:containerEdgeGrant(tenant,id,"workload.lifecycle",call.CommandID,value.Generation,edge.now().UTC()),WorkloadID:id,Lifecycle:containers.LifecycleDeleting});if err!=nil{return apiserver.EdgeMutation[apiserver.ContainerProjection]{},err};projection:=containerProjection(deleted);return apiserver.EdgeMutation[apiserver.ContainerProjection]{OperationID:string(result.EffectID),State:result.Status,Generation:deleted.Generation,Resource:projection},nil}

func(edge *containerEdge)IssueExec(ctx context.Context,call apiserver.EdgeCall,payload apiserver.ContainerExecPayload)(apiserver.ContainerExecGrant,error){tenant,id,value,err:=edge.load(ctx,call);if err!=nil{return apiserver.ContainerExecGrant{},err};if call.ExpectedGeneration==0||call.ExpectedGeneration!=value.Generation{return apiserver.ContainerExecGrant{},containers.ErrStale};commandID,err:=containers.NewID(payload.CommandID);if err!=nil{return apiserver.ContainerExecGrant{},err};sum:=sha256.Sum256([]byte(payload.Token));grantID,err:=containers.NewID("exec_"+hex.EncodeToString(sum[:20]));if err!=nil{return apiserver.ContainerExecGrant{},err};now:=edge.now().UTC();authority:=containerEdgeGrant(tenant,id,"workload.exec",call.CommandID,value.Generation,now).Grant;ttl:=time.Duration(payload.TTLSeconds)*time.Second;issued,err:=edge.service.IssueExecGrant(ctx,authority,grantID,id,commandID,containers.RuntimeUser{UID:1000,GID:1000},payload.Arguments,ttl,hex.EncodeToString(sum[:]));payload.Token="";if err!=nil{return apiserver.ContainerExecGrant{},err};return apiserver.ContainerExecGrant{ID:issued.ID.String(),Endpoint:"/api/v1/containers/exec/exchange",ExpiresAt:issued.ExpiresAt},nil}

func(edge *containerEdge)QueryLogs(ctx context.Context,call apiserver.EdgeCall,payload apiserver.ContainerLogPayload)(apiserver.ContainerLogPage,error){tenant,id,value,err:=edge.load(ctx,call);if err!=nil{return apiserver.ContainerLogPage{},err};grant:=containerEdgeGrant(tenant,id,"workload.logs",call.CommandID,value.Generation,edge.now().UTC()).Grant;cursor:=containers.LogCursor{WorkloadID:id,Stream:"combined",Opaque:payload.Cursor,At:payload.Start};deadline:=edge.now().UTC().Add(30*time.Second);stream,err:=edge.broker.OpenLogs(ctx,containers.LogRequest{Grant:grant,WorkloadID:id,Cursor:cursor,Since:payload.Start,TailLines:uint64(payload.Limit),MaxBytes:containers.ContainerBrokerMaximumLogBytes,Deadline:deadline});if err!=nil{return apiserver.ContainerLogPage{},err};defer stream.Close();chunk,err:=stream.Next(ctx);if err!=nil&&!errors.Is(err,io.EOF){return apiserver.ContainerLogPage{},err};content:=strings.TrimSuffix(string(chunk.Data),"\n");lines:=[]string{};if content!=""{lines=strings.Split(content,"\n")};next:="";if chunk.Truncated||!chunk.EOF{next=chunk.Cursor.Opaque};return apiserver.ContainerLogPage{Lines:lines,NextCursor:next},nil}

var _ apiserver.ContainerEdgeService=(*containerEdge)(nil)
