//go:build linux

package main

import (
	"context"
	"errors"
	"sort"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/apiserver"
	hostingservice "github.com/aonsyed/cyberpanel/platform/internal/hosting/service"
	"github.com/aonsyed/cyberpanel/platform/internal/hosting/site"
	"github.com/aonsyed/cyberpanel/platform/internal/hosting/sqlrepo"
	"github.com/aonsyed/cyberpanel/platform/internal/webengine"
	"github.com/aonsyed/cyberpanel/platform/internal/webengine/accesspolicy"
)

type hostingEdge struct{commands hostingservice.Service;store *sqlrepo.Repository;policies *accesspolicy.Authority;now func()time.Time}

func newHostingEdge(commands hostingservice.Service,store *sqlrepo.Repository,policies *accesspolicy.Authority,now func()time.Time)(*hostingEdge,error){if store==nil||policies==nil{return nil,hostingservice.ErrInvalidCommand};if now==nil{now=time.Now};return &hostingEdge{commands:commands,store:store,policies:policies,now:now},nil}

func(edge *hostingEdge)ListSites(ctx context.Context,call apiserver.EdgeCall,page apiserver.EdgePagePayload)(apiserver.EdgePage[apiserver.HostingSiteProjection],error){tenant,err:=site.NewTenantID(call.TenantID);if err!=nil{return apiserver.EdgePage[apiserver.HostingSiteProjection]{},err};items,next,total,err:=edge.store.List(ctx,tenant,page.Cursor,int(page.Limit));if err!=nil{return apiserver.EdgePage[apiserver.HostingSiteProjection]{},err};result:=make([]apiserver.HostingSiteProjection,0,len(items));for _,item:=range items{result=append(result,hostingEdgeSiteProjection(item))};return apiserver.EdgePage[apiserver.HostingSiteProjection]{Items:result,NextCursor:next,Total:total},nil}

func(edge *hostingEdge)GetSite(ctx context.Context,call apiserver.EdgeCall)(apiserver.HostingSiteProjection,error){tenant,err:=site.NewTenantID(call.TenantID);if err!=nil{return apiserver.HostingSiteProjection{},err};identifier,err:=site.NewSiteID(call.ResourceID);if err!=nil{return apiserver.HostingSiteProjection{},err};item,err:=edge.store.Load(ctx,tenant,identifier);if err!=nil{return apiserver.HostingSiteProjection{},err};return hostingEdgeSiteProjection(item),nil}

func(edge *hostingEdge)ListBindings(ctx context.Context,call apiserver.EdgeCall,page apiserver.EdgePagePayload)(apiserver.EdgePage[apiserver.HostingBindingProjection],error){tenant,err:=site.NewTenantID(call.TenantID);if err!=nil{return apiserver.EdgePage[apiserver.HostingBindingProjection]{},err};all:=[]apiserver.HostingBindingProjection{};siteCursor:="";for{sites,next,_,listErr:=edge.store.List(ctx,tenant,siteCursor,500);if listErr!=nil{return apiserver.EdgePage[apiserver.HostingBindingProjection]{},listErr};for _,aggregate:=range sites{for _,binding:=range aggregate.Bindings(){if binding.Kind==site.BindingPrimary{continue};projection:=hostingEdgeBindingProjection(aggregate,binding);if policyErr:=edge.attachAccessPolicy(ctx,aggregate,binding,&projection);policyErr!=nil{return apiserver.EdgePage[apiserver.HostingBindingProjection]{},policyErr};all=append(all,projection)}};if next==""{break};siteCursor=next};sort.Slice(all,func(left,right int)bool{return all[left].ID<all[right].ID});start:=0;for start<len(all)&&all[start].ID<=page.Cursor{start++};end:=start+int(page.Limit);if end>len(all){end=len(all)};next:="";if end<len(all)&&end>start{next=all[end-1].ID};return apiserver.EdgePage[apiserver.HostingBindingProjection]{Items:append([]apiserver.HostingBindingProjection(nil),all[start:end]...),NextCursor:next,Total:uint64(len(all))},nil}

func(edge *hostingEdge)CreateBinding(ctx context.Context,call apiserver.EdgeCall,payload apiserver.HostingBindingPayload)(apiserver.EdgeMutation[apiserver.HostingBindingProjection],error){tenant,err:=site.NewTenantID(call.TenantID);if err!=nil{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},err};siteID,err:=site.NewSiteID(payload.SiteID);if err!=nil{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},err};aggregate,err:=edge.store.Load(ctx,tenant,siteID);if err!=nil{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},err};binding,err:=hostingEdgeBinding(payload);if err!=nil{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},err};receipt,err:=edge.commands.Handle(ctx,hostingservice.AttachDomainBinding{CommandID:call.CommandID,Actor:hostingservice.Actor{TenantID:tenant},TenantID:tenant,SiteID:siteID,ExpectedGeneration:aggregate.Generation(),Binding:binding});if err!=nil{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},err};projection:=hostingEdgeBindingProjectionFromReceipt(receipt,binding);return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{OperationID:receipt.CommandID,State:string(receipt.Status),Generation:projection.Generation,Resource:projection},nil}

func(edge *hostingEdge)DeleteBinding(ctx context.Context,call apiserver.EdgeCall)(apiserver.EdgeMutation[apiserver.HostingBindingProjection],error){siteRaw,hostnameRaw,found:=strings.Cut(call.ResourceID,":");if !found{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},hostingservice.ErrInvalidCommand};tenant,err:=site.NewTenantID(call.TenantID);if err!=nil{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},err};siteID,err:=site.NewSiteID(siteRaw);if err!=nil{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},err};hostname,err:=site.ParseHostname(hostnameRaw);if err!=nil{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},err};aggregate,err:=edge.store.Load(ctx,tenant,siteID);if err!=nil{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},err};var selected site.DomainBinding;exists:=false;for _,binding:=range aggregate.Bindings(){if binding.Hostname==hostname{selected=binding;exists=true;break}};if !exists||selected.Kind==site.BindingPrimary{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},hostingservice.ErrNotFound};if call.ExpectedGeneration!=aggregate.Generation(){return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},site.ErrStaleGeneration};receipt,err:=edge.commands.Handle(ctx,hostingservice.DetachDomainBinding{CommandID:call.CommandID,Actor:hostingservice.Actor{TenantID:tenant},TenantID:tenant,SiteID:siteID,ExpectedGeneration:call.ExpectedGeneration,Hostname:hostname});if err!=nil{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},err};projection:=hostingEdgeBindingProjection(aggregate,selected);projection.Routing="withdrawn";projection.Generation=receipt.Request.Projection.Generation;projection.UpdatedAt=edge.now().UTC();return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{OperationID:receipt.CommandID,State:string(receipt.Status),Generation:projection.Generation,Resource:projection},nil}

func(edge *hostingEdge)ConfigureAccessPolicy(ctx context.Context,call apiserver.EdgeCall,payload apiserver.HostingAccessPolicyPayload)(apiserver.EdgeMutation[apiserver.HostingBindingProjection],error){siteRaw,hostnameRaw,found:=strings.Cut(call.ResourceID,":");if !found{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},hostingservice.ErrInvalidCommand};tenant,err:=site.NewTenantID(call.TenantID);if err!=nil{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},err};siteID,err:=site.NewSiteID(siteRaw);if err!=nil{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},err};hostname,err:=site.ParseHostname(hostnameRaw);if err!=nil{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},err};aggregate,err:=edge.store.Load(ctx,tenant,siteID);if err!=nil{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},err};if call.ExpectedGeneration!=aggregate.Generation(){return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},site.ErrStaleGeneration};var selected site.DomainBinding;exists:=false;for _,binding:=range aggregate.Bindings(){if binding.Hostname==hostname{selected=binding;exists=true;break}};if !exists||selected.Kind==site.BindingRedirect{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},hostingservice.ErrNotFound};engineHostname,err:=webengine.ParseHostname(hostname.String());if err!=nil{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},err};scope:=hostingservice.CommandScope{TenantID:tenant,SiteID:siteID};policy,err:=edge.policies.ConfigureBinding(ctx,accesspolicy.ConfigureBindingRequest{EffectID:call.CommandID,Scope:scope,Hostname:engineHostname,ResourceID:call.ResourceID,Enabled:payload.Enabled,CredentialRef:payload.CredentialRef,Realm:"Protected site",Route:"/"});if err!=nil{return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{},err};projection:=hostingEdgeBindingProjection(aggregate,selected);projection.AccessPolicyRef=string(policy.PolicyRef);projection.AccessPolicyState=string(policy.State);projection.AccessPolicyGeneration=policy.Generation;projection.UpdatedAt=edge.now().UTC();return apiserver.EdgeMutation[apiserver.HostingBindingProjection]{OperationID:call.CommandID,State:"confirmed",Generation:projection.Generation,Resource:projection},nil}

func(edge *hostingEdge)attachAccessPolicy(ctx context.Context,aggregate site.Site,binding site.DomainBinding,projection *apiserver.HostingBindingProjection)error{hostname,err:=webengine.ParseHostname(binding.Hostname.String());if err!=nil{return err};scope:=hostingservice.CommandScope{TenantID:aggregate.TenantID(),SiteID:aggregate.ID()};ref:=accesspolicy.PolicyRef(scope,hostname,"/");policy,err:=edge.policies.Policy(ctx,string(ref));if errors.Is(err,accesspolicy.ErrNotFound){return nil};if err!=nil{return err};projection.AccessPolicyRef=string(policy.PolicyRef);projection.AccessPolicyState=string(policy.State);projection.AccessPolicyGeneration=policy.Generation;return nil}

func hostingEdgeSiteProjection(aggregate site.Site)apiserver.HostingSiteProjection{primary:="";for _,binding:=range aggregate.Bindings(){if binding.Kind==site.BindingPrimary{primary=binding.Hostname.String();break}};return apiserver.HostingSiteProjection{ID:aggregate.ID().String(),TenantID:aggregate.TenantID().String(),ProjectID:aggregate.ProjectID().String(),PrimaryHostname:primary,PHPProfile:string(aggregate.PHPProfile()),Lifecycle:string(aggregate.Lifecycle()),Generation:aggregate.Generation()}}

func hostingEdgeBindingProjection(aggregate site.Site,binding site.DomainBinding)apiserver.HostingBindingProjection{routing:="maintenance";if aggregate.Lifecycle()==site.LifecycleActive{routing="serving"};if aggregate.Lifecycle()==site.LifecyclePurging||aggregate.Lifecycle()==site.LifecycleDeleted{routing="withdrawn"};return apiserver.HostingBindingProjection{ID:aggregate.ID().String()+":"+binding.Hostname.String(),SiteID:aggregate.ID().String(),Hostname:binding.Hostname.String(),Relationship:string(binding.Kind),RedirectTarget:binding.RedirectTarget.String(),TLS:"unmanaged",Routing:routing,Generation:aggregate.Generation()}}

func hostingEdgeBindingProjectionFromReceipt(receipt hostingservice.OperationReceipt,binding site.DomainBinding)apiserver.HostingBindingProjection{return apiserver.HostingBindingProjection{ID:receipt.Scope.SiteID.String()+":"+binding.Hostname.String(),SiteID:receipt.Scope.SiteID.String(),Hostname:binding.Hostname.String(),Relationship:string(binding.Kind),RedirectTarget:binding.RedirectTarget.String(),TLS:"unmanaged",Routing:hostingEdgeRouting(receipt.Request.Projection.Lifecycle),Generation:receipt.Request.Projection.Generation}}
func hostingEdgeRouting(lifecycle site.Lifecycle)string{if lifecycle==site.LifecycleActive{return "serving"};if lifecycle==site.LifecyclePurging||lifecycle==site.LifecycleDeleted{return "withdrawn"};return "maintenance"}
func hostingEdgeBinding(payload apiserver.HostingBindingPayload)(site.DomainBinding,error){hostname,err:=site.ParseHostname(payload.Hostname);if err!=nil{return site.DomainBinding{},err};binding:=site.DomainBinding{Hostname:hostname};switch payload.Relationship{case "alias":binding.Kind=site.BindingAlias;case "child":binding.Kind=site.BindingChild;case "redirect":binding.Kind=site.BindingRedirect;binding.RedirectStatus=site.RedirectStatusPermanent301;binding.RedirectTarget,err=site.ParseHostname(payload.RedirectTarget);if err!=nil{return site.DomainBinding{},err};default:return site.DomainBinding{},hostingservice.ErrInvalidCommand};return binding,nil}

var _ apiserver.HostingEdgeService=(*hostingEdge)(nil)
var _ apiserver.HostingAccessPolicyEdgeService=(*hostingEdge)(nil)
