//go:build linux

package main

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"sort"
	"strings"

	"github.com/aonsyed/cyberpanel/platform/internal/apiserver"
	"github.com/aonsyed/cyberpanel/platform/internal/identity"
)

type identityEdge struct{ service *identity.Service; store *identity.Store }

func newIdentityEdge(service *identity.Service,store *identity.Store)(*identityEdge,error){if service==nil||store==nil{return nil,identity.ErrInvalid};return &identityEdge{service:service,store:store},nil}

func(edge *identityEdge)ListTenants(ctx context.Context,call apiserver.EdgeCall,payload apiserver.EdgePagePayload)(apiserver.EdgePage[apiserver.IdentityTenantProjection],error){actor,tenantID,err:=edge.authorize(ctx,call,identity.AssurancePassword);if err!=nil{return apiserver.EdgePage[apiserver.IdentityTenantProjection]{},err};if _,err=edge.service.AuthorizeActor(ctx,actor,"identity:manage",identity.Scope{Kind:identity.ScopeTenant,TenantID:tenantID},identity.AssurancePassword);err!=nil{return apiserver.EdgePage[apiserver.IdentityTenantProjection]{},err};limit:=int(payload.Limit);if limit==0{limit=50};cursor,err:=optionalIdentityID(payload.Cursor);if err!=nil{return apiserver.EdgePage[apiserver.IdentityTenantProjection]{},err};values,next,total,err:=edge.store.ListTenants(ctx,tenantID,limit,cursor);if err!=nil{return apiserver.EdgePage[apiserver.IdentityTenantProjection]{},err};items:=make([]apiserver.IdentityTenantProjection,0,len(values));for _,value:=range values{items=append(items,tenantProjection(value))};return apiserver.EdgePage[apiserver.IdentityTenantProjection]{Items:items,NextCursor:next,Total:total},nil}

func(edge *identityEdge)CreateTenant(ctx context.Context,call apiserver.EdgeCall,payload apiserver.IdentityTenantCreatePayload)(apiserver.EdgeMutation[apiserver.IdentityTenantProjection],error){actor,parentID,err:=edge.authorize(ctx,call,identity.AssuranceMFA);if err!=nil{return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{},err};if payload.ParentTenantID!=""{provided,parseErr:=identity.NewID(payload.ParentTenantID);if parseErr!=nil||provided!=parentID{return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{},identity.ErrForbidden}};planID,err:=identity.NewID(payload.PlanID);if err!=nil{return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{},err};parent,err:=edge.store.Tenant(ctx,parentID);if err!=nil{return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{},err};parentPlan,err:=edge.store.Plan(ctx,parent.PlanID);if err!=nil{return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{},err};tenantID:=derivedIdentityID("tenant",call.CommandID+"\x00"+parentID.String());delegationID:=derivedIdentityID("delegation",tenantID.String());command:=identity.CreateTenantCommand{Actor:actor,TenantID:tenantID,ParentTenantID:parentID,SponsorID:parentID,PlanID:planID,DelegationID:delegationID,Kind:identity.TenantCustomer,Name:payload.Name,Permissions:[]identity.Permission{"identity:manage"},Quota:minimumChildQuota(parentPlan.Quota)};tenant,err:=edge.service.CreateTenant(ctx,command);if err!=nil{return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{},err};projection:=tenantProjection(tenant);return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{OperationID:call.CommandID,State:string(tenant.State),Generation:tenant.Generation,Resource:projection},nil}

func(edge *identityEdge)SuspendTenant(ctx context.Context,call apiserver.EdgeCall)(apiserver.EdgeMutation[apiserver.IdentityTenantProjection],error){actor,_,err:=edge.authorize(ctx,call,identity.AssuranceMFA);if err!=nil{return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{},err};tenantID,err:=identity.NewID(call.ResourceID);if err!=nil{return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{},err};tenant,err:=edge.service.SuspendTenant(ctx,actor,tenantID,call.ExpectedGeneration);if err!=nil{return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{},err};projection:=tenantProjection(tenant);return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{OperationID:call.CommandID,State:string(tenant.State),Generation:tenant.Generation,Resource:projection},nil}

func(edge *identityEdge)ListMemberships(ctx context.Context,call apiserver.EdgeCall,payload apiserver.EdgePagePayload)(apiserver.EdgePage[apiserver.IdentityMembershipProjection],error){actor,tenantID,err:=edge.authorize(ctx,call,identity.AssurancePassword);if err!=nil{return apiserver.EdgePage[apiserver.IdentityMembershipProjection]{},err};if call.ResourceID!=tenantID.String(){return apiserver.EdgePage[apiserver.IdentityMembershipProjection]{},identity.ErrForbidden};if _,err=edge.service.AuthorizeActor(ctx,actor,"identity:manage",identity.Scope{Kind:identity.ScopeTenant,TenantID:tenantID},identity.AssurancePassword);err!=nil{return apiserver.EdgePage[apiserver.IdentityMembershipProjection]{},err};limit:=int(payload.Limit);if limit==0{limit=50};cursor,err:=optionalIdentityID(payload.Cursor);if err!=nil{return apiserver.EdgePage[apiserver.IdentityMembershipProjection]{},err};values,next,total,err:=edge.store.ListTenantMemberships(ctx,tenantID,limit,cursor);if err!=nil{return apiserver.EdgePage[apiserver.IdentityMembershipProjection]{},err};items:=make([]apiserver.IdentityMembershipProjection,0,len(values));for _,value:=range values{bindings,loadErr:=edge.store.Bindings(ctx,value.Principal.ID);if loadErr!=nil{return apiserver.EdgePage[apiserver.IdentityMembershipProjection]{},loadErr};roles:=make([]string,0,len(bindings));for _,binding:=range bindings{if binding.Scope.TenantID==tenantID{roles=append(roles,binding.RoleID.String())}};sort.Strings(roles);items=append(items,apiserver.IdentityMembershipProjection{ID:value.Membership.ID.String(),TenantID:value.Membership.TenantID.String(),PrincipalID:value.Principal.ID.String(),DisplayName:value.Principal.DisplayName,RoleIDs:roles,State:string(value.Membership.State),Generation:value.Membership.Generation,UpdatedAt:value.Membership.UpdatedAt})};return apiserver.EdgePage[apiserver.IdentityMembershipProjection]{Items:items,NextCursor:next,Total:total},nil}

func(edge *identityEdge)ListRoleBindings(ctx context.Context,call apiserver.EdgeCall,payload apiserver.EdgePagePayload)(apiserver.EdgePage[apiserver.IdentityRoleBindingProjection],error){actor,tenantID,err:=edge.authorize(ctx,call,identity.AssurancePassword);if err!=nil{return apiserver.EdgePage[apiserver.IdentityRoleBindingProjection]{},err};if call.ResourceID!=tenantID.String(){return apiserver.EdgePage[apiserver.IdentityRoleBindingProjection]{},identity.ErrForbidden};if _,err=edge.service.AuthorizeActor(ctx,actor,"identity:manage",identity.Scope{Kind:identity.ScopeTenant,TenantID:tenantID},identity.AssurancePassword);err!=nil{return apiserver.EdgePage[apiserver.IdentityRoleBindingProjection]{},err};limit:=int(payload.Limit);if limit==0{limit=50};cursor,err:=optionalIdentityID(payload.Cursor);if err!=nil{return apiserver.EdgePage[apiserver.IdentityRoleBindingProjection]{},err};values,next,total,err:=edge.store.ListTenantRoleBindings(ctx,tenantID,limit,cursor);if err!=nil{return apiserver.EdgePage[apiserver.IdentityRoleBindingProjection]{},err};items:=make([]apiserver.IdentityRoleBindingProjection,0,len(values));for _,value:=range values{items=append(items,apiserver.IdentityRoleBindingProjection{ID:value.ID.String(),TenantID:value.Scope.TenantID.String(),PrincipalID:value.SubjectID.String(),RoleID:value.RoleID.String(),ScopeKind:string(value.Scope.Kind),ResourceID:value.Scope.ResourceID.String(),Generation:value.Generation,UpdatedAt:value.CreatedAt})};return apiserver.EdgePage[apiserver.IdentityRoleBindingProjection]{Items:items,NextCursor:next,Total:total},nil}

func(edge *identityEdge)ConfigureEntitlement(ctx context.Context,call apiserver.EdgeCall,payload apiserver.IdentityEntitlementPayload)(apiserver.EdgeMutation[apiserver.IdentityTenantProjection],error){actor,_,err:=edge.authorize(ctx,call,identity.AssuranceMFA);if err!=nil{return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{},err};tenantID,err:=identity.NewID(call.ResourceID);if err!=nil{return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{},err};planID,err:=identity.NewID(payload.PlanID);if err!=nil{return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{},err};plan,err:=edge.store.Plan(ctx,planID);if err!=nil{return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{},err};if plan.OwnerTenantID!=tenantID{return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{},identity.ErrForbidden};quota,err:=applyEntitlementLimits(plan.Quota,payload.Limits);if err!=nil{return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{},err};tenant,err:=edge.service.ConfigureTenantPlan(ctx,actor,tenantID,call.ExpectedGeneration,planID,quota);if err!=nil{return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{},err};projection:=tenantProjection(tenant);return apiserver.EdgeMutation[apiserver.IdentityTenantProjection]{OperationID:call.CommandID,State:string(tenant.State),Generation:tenant.Generation,Resource:projection},nil}

func(edge *identityEdge)authorize(ctx context.Context,call apiserver.EdgeCall,minimum identity.AssuranceLevel)(identity.ActorContext,identity.ID,error){if edge==nil||edge.service==nil||edge.store==nil||ctx==nil||strings.TrimSpace(call.CommandID)==""{return identity.ActorContext{},"",identity.ErrInvalid};principal,err:=identity.NewID(call.PrincipalID);if err!=nil{return identity.ActorContext{},"",err};credential,err:=identity.NewID(call.CredentialID);if err!=nil{return identity.ActorContext{},"",err};tenant,err:=identity.NewID(call.TenantID);if err!=nil{return identity.ActorContext{},"",err};session,err:=optionalIdentityID(call.SessionID);if err!=nil{return identity.ActorContext{},"",err};actor:=identity.ActorContext{PrincipalID:principal,SessionID:session,CredentialID:credential,AuthzEpoch:call.AuthzEpoch,Assurance:call.Assurance};if actor.AuthzEpoch==0||actor.Assurance<minimum{return identity.ActorContext{},"",identity.ErrAssuranceRequired};return actor,tenant,nil}

func tenantProjection(value identity.Tenant)apiserver.IdentityTenantProjection{return apiserver.IdentityTenantProjection{ID:value.ID.String(),Name:value.Name,ParentID:value.ParentTenantID.String(),PlanID:value.PlanID.String(),State:string(value.State),Generation:value.Generation,UpdatedAt:value.UpdatedAt}}

func optionalIdentityID(value string)(identity.ID,error){if value==""{return "",nil};return identity.NewID(value)}

func derivedIdentityID(prefix,value string)identity.ID{sum:=sha256.Sum256([]byte(value));id,_:=identity.NewID(prefix+"_"+hex.EncodeToString(sum[:])[:32]);return id}

func minimumChildQuota(parent identity.ResourceQuota)identity.ResourceQuota{return identity.ResourceQuota{Sites:minPositive(parent.Sites,1),Domains:minPositive(parent.Domains,1),Databases:minOptional(parent.Databases,1),Mailboxes:minOptional(parent.Mailboxes,1),FTPAccounts:minOptional(parent.FTPAccounts,1),DiskBytes:minPositive(parent.DiskBytes,1<<30),Inodes:minPositive(parent.Inodes,100000),MonthlyTransfer:minOptional(parent.MonthlyTransfer,10<<30),CPUQuotaMicros:minOptional(parent.CPUQuotaMicros,100000),MemoryBytes:minPositive(parent.MemoryBytes,256<<20),IOReadBPS:minOptional(parent.IOReadBPS,50<<20),IOWriteBPS:minOptional(parent.IOWriteBPS,25<<20),IOReadIOPS:minOptional(parent.IOReadIOPS,1000),IOWriteIOPS:minOptional(parent.IOWriteIOPS,500),PIDs:minPositive(parent.PIDs,64),PHPConcurrency:minPositive(parent.PHPConcurrency,4)}}

func minPositive(value,maximum uint64)uint64{if value<maximum{return value};return maximum}
func minOptional(value,maximum uint64)uint64{if value==0{return 0};return minPositive(value,maximum)}

func applyEntitlementLimits(quota identity.ResourceQuota,limits map[string]uint64)(identity.ResourceQuota,error){for name,value:=range limits{switch name{case"sites":quota.Sites=value;case"domains":quota.Domains=value;case"databases":quota.Databases=value;case"mailboxes":quota.Mailboxes=value;case"ftp_accounts":quota.FTPAccounts=value;case"disk_bytes":quota.DiskBytes=value;case"inodes":quota.Inodes=value;case"monthly_transfer":quota.MonthlyTransfer=value;case"cpu_quota_micros":quota.CPUQuotaMicros=value;case"memory_bytes":quota.MemoryBytes=value;case"io_read_bps":quota.IOReadBPS=value;case"io_write_bps":quota.IOWriteBPS=value;case"io_read_iops":quota.IOReadIOPS=value;case"io_write_iops":quota.IOWriteIOPS=value;case"pids":quota.PIDs=value;case"php_concurrency":quota.PHPConcurrency=value;default:return identity.ResourceQuota{},identity.ErrInvalid}};if err:=quota.Validate();err!=nil{return identity.ResourceQuota{},err};return quota,nil}

var _ apiserver.IdentityEdgeService=(*identityEdge)(nil)

