//go:build linux

package main

import (
	"bytes"
	"context"
	"database/sql"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/access"
	"github.com/aonsyed/cyberpanel/platform/internal/backup"
	backupproviders "github.com/aonsyed/cyberpanel/platform/internal/backup/providers"
	"github.com/aonsyed/cyberpanel/platform/internal/migration"
)

type migrationAuxiliaryServices struct{git *access.GitService;cron *access.CronService;backup *backupproviders.LocalRuntime}
type migrationAuxiliaryTarget struct{host *migrationHostTarget;services migrationAuxiliaryServices}
type migrationAuxiliaryDesired struct{Repository *access.GitRepository;Cron *access.CronJob;Policy *backup.BackupPolicySpec;BackupRepository *backup.RepositorySpec;ScriptDigest string;ScriptPath string}

func (host *migrationHostTarget) auxiliaryOrigin(ctx context.Context,intent migration.ImportIntent)(migration.ImportIntent,error){var raw []byte;if err:=host.db.QueryRowContext(ctx,`SELECT domain_intent_json FROM panel_migration_host_effects WHERE migration_id=? AND kind=? AND source_id=? AND target_id=?`,intent.MigrationID.String(),string(intent.Kind),intent.SourceID.String(),intent.TargetID.String()).Scan(&raw);err!=nil{return migration.ImportIntent{},err};var origin migration.ImportIntent;if json.Unmarshal(raw,&origin)!=nil||origin.MigrationID!=intent.MigrationID||origin.TargetID!=intent.TargetID||origin.Kind!=intent.Kind||migration.ValidateCanonicalImportIntent(origin)!=nil{return origin,migration.ErrConflict};return origin,nil}
func (host *migrationHostTarget) observeAuxiliary(ctx context.Context,intent migration.ImportIntent)(migration.ImportEffect,error){origin,err:=host.auxiliaryOrigin(ctx,intent);if err!=nil||host.auxiliary==nil{return migration.ImportEffect{},errors.Join(migration.ErrBlocked,err)};return host.auxiliary.Observe(ctx,origin)}
func (host *migrationHostTarget) auxiliaryProofs(ctx context.Context,entries []migration.ImportIntent,active bool)([]string,error){proofs:=[]string{};for _,intent:=range entries{if !migrationAuxiliaryKind(intent.Kind){continue};effect,err:=host.observeAuxiliary(ctx,intent);if err!=nil||effect.Status!=migration.ImportEffectApplied||effect.EvidenceDigest==""{return nil,errors.Join(migration.ErrBlocked,err)};if active&&effect.ErrorCode!=""{return nil,migration.ErrBlocked};proofs=append(proofs,effect.EvidenceDigest)};return proofs,nil}

func newMigrationAuxiliaryTarget(ctx context.Context,host *migrationHostTarget,services migrationAuxiliaryServices)(*migrationAuxiliaryTarget,error){
	if services.git==nil||services.git.Executor==nil||services.git.Store==nil||services.cron==nil||services.cron.Executor==nil||services.cron.Store==nil||services.backup==nil{return nil,migration.ErrBlocked}
	_,err:=host.db.ExecContext(ctx,`CREATE TABLE IF NOT EXISTS panel_migration_auxiliary_effects(migration_id TEXT NOT NULL,target_id TEXT NOT NULL,kind TEXT NOT NULL,input_digest TEXT NOT NULL,desired_json BLOB NOT NULL,state TEXT NOT NULL,receipt_json BLOB NOT NULL,PRIMARY KEY(migration_id,target_id))`);if err!=nil{return nil,err};return &migrationAuxiliaryTarget{host:host,services:services},nil
}

func migrationAuxiliaryKind(kind migration.ImportResourceKind)bool{return kind==migration.ImportRepository||kind==migration.ImportSchedule||kind==migration.ImportBackupPolicy}
func migrationAuxiliaryDecode(raw []byte,value any)error{if len(raw)==0||len(raw)>256<<10{return migration.ErrInvalid};decoder:=json.NewDecoder(bytes.NewReader(raw));decoder.DisallowUnknownFields();if err:=decoder.Decode(value);err!=nil{return err};if decoder.Decode(&struct{}{})!=io.EOF{return migration.ErrInvalid};return nil}

func (target *migrationAuxiliaryTarget) site(ctx context.Context,intent migration.ImportIntent,source migration.ID)(access.SiteID,migration.RuntimeScope,error){
	scope,err:=target.host.scopes.LoadByMigration(ctx,intent.MigrationID);if err!=nil{return "",scope,err};value,err:=target.host.repository.Migration(ctx,intent.MigrationID);if err!=nil{return "",scope,err};plan,err:=target.host.repository.Plan(ctx,value.PlanDigest);if err!=nil{return "",scope,err};if plan.ApprovedAt==nil||plan.ApprovalDigest==""{return "",scope,migration.ErrBlocked};for _,mapping:=range plan.Mappings{if mapping.SourceKind==string(migration.ImportSite)&&mapping.SourceID==source&&mapping.Disposition==migration.DispositionCreate{return access.SiteID(mapping.TargetID.String()),scope,nil}};return "",scope,migration.ErrBlocked
}

func (target *migrationAuxiliaryTarget) desired(ctx context.Context,intent migration.ImportIntent)(migrationAuxiliaryDesired,error){
	var desired migrationAuxiliaryDesired;if migration.ValidateCanonicalImportIntent(intent)!=nil||!migrationAuxiliaryKind(intent.Kind)||len(intent.SecretIDs)!=0||len(intent.Chunks)!=0{return desired,migration.ErrBlocked}
	switch intent.Kind{
	case migration.ImportRepository:
		var source migration.RepositoryBinding;if migrationAuxiliaryDecode(intent.Payload,&source)!=nil||source.SourceID!=intent.SourceID||source.CredentialSecretID!=""||source.AutoDeploy{return desired,fmt.Errorf("%w: only public HTTPS manual repository bindings are supported",migration.ErrBlocked)};siteID,_,err:=target.site(ctx,intent,source.SiteID);if err!=nil{return desired,err};remote,err:=access.ParseRemoteRepository(source.Origin);if err!=nil||remote.Transport!=access.GitHTTPS||remote.Port!=443{return desired,migration.ErrBlocked};provider:=access.GitProvider(source.Provider);switch remote.Host{case "github.com":if provider!=access.GitHub{return desired,migration.ErrBlocked};case "gitlab.com":if provider!=access.GitLab{return desired,migration.ErrBlocked};case "bitbucket.org":if provider!=access.Bitbucket{return desired,migration.ErrBlocked};default:return desired,fmt.Errorf("%w: public Git host not in the closed migration allowlist",migration.ErrBlocked)}
		path,err:=access.ParseRelativePath("migration-repository-"+intent.TargetID.String());if err!=nil{return desired,err};repository:=access.GitRepository{ID:access.GitRepositoryID(intent.TargetID.String()),SiteID:siteID,Provider:provider,Remote:remote,Worktree:access.FileLocator{Root:access.SiteRoot{SiteID:siteID,Kind:access.RootPrivate},Path:path},Branch:source.Branch,Strategy:access.GitManual,Generation:1};if err=repository.Validate();err!=nil{return desired,err};desired.Repository=&repository
	case migration.ImportSchedule:
		var source migration.Schedule;if migrationAuxiliaryDecode(intent.Payload,&source)!=nil||source.SourceID!=intent.SourceID||source.Kind!="cyberpanel-php83-cron-v1"||!strings.HasPrefix(source.InvocationID,"php-cron-v1:")||source.Timezone!="UTC"{return desired,fmt.Errorf("%w: legacy command hashes and non-UTC cron require an explicit typed invocation",migration.ErrBlocked)}
		// InvocationID is a versioned base64url JSON payload, integrity-bound by
		// the signed manifest. No shell command or arbitrary runtime is accepted.
		var invocation struct{Entrypoint string `json:"entrypoint"`;SHA256 string `json:"sha256"`;Arguments []string `json:"arguments"`};raw,err:=base64.RawURLEncoding.DecodeString(strings.TrimPrefix(source.InvocationID,"php-cron-v1:"));if err!=nil||len(raw)>16<<10||migrationAuxiliaryDecode(raw,&invocation)!=nil{return desired,migration.ErrInvalid};digest,err:=hex.DecodeString(invocation.SHA256);if err!=nil||len(digest)!=32||len(invocation.Arguments)>32{return desired,migration.ErrInvalid};relative,err:=access.ParseRelativePath(invocation.Entrypoint);if err!=nil||relative.IsRoot()||!strings.HasSuffix(relative.String(),".php"){return desired,migration.ErrInvalid};entrypoint,err:=access.ParseRelativePath("public/"+relative.String());if err!=nil{return desired,err};siteID,_,err:=target.site(ctx,intent,source.SiteID);if err!=nil{return desired,err};expression,err:=access.ParseCronExpression(source.Expression);if err!=nil{return desired,err}
		value,err:=target.host.repository.Migration(ctx,intent.MigrationID);if err!=nil{return desired,err};manifest,err:=target.host.repository.Manifest(ctx,value.ManifestRoot);if err!=nil{return desired,err};matched:=false;for _,sourceSite:=range manifest.Sites{if sourceSite.SourceID==source.SiteID{profile,parseErr:=migrationPHPProfile(sourceSite.PHPVersion);matched=parseErr==nil&&string(profile)=="php83"}};if !matched{return desired,fmt.Errorf("%w: cron executor requires the explicitly bound PHP 8.3 profile",migration.ErrBlocked)}
		job:=access.CronJob{ID:access.CronJobID(intent.TargetID.String()),SiteID:siteID,Name:"Migration "+intent.SourceID.String(),Schedule:expression,Timezone:"UTC",Invocation:access.CronInvocation{Kind:access.InvocationProgram,Program:&access.ProgramInvocation{Program:access.ProgramPHP,Entrypoint:entrypoint,Arguments:invocation.Arguments}},Concurrency:access.ConcurrencyForbid,TimeoutSeconds:300,Output:access.OutputCapture,Enabled:source.Enabled,Generation:1};if err=job.Validate();err!=nil{return desired,err};desired.Cron=&job;desired.ScriptDigest=invocation.SHA256;desired.ScriptPath=relative.String()
	case migration.ImportBackupPolicy:
		var source migration.BackupPolicy;if migrationAuxiliaryDecode(intent.Payload,&source)!=nil||source.SourceID!=intent.SourceID||source.CredentialSecretID!=""||!strings.HasPrefix(source.Repository,"target:"){return desired,fmt.Errorf("%w: backups require an explicit pre-registered target repository and no legacy secret",migration.ErrBlocked)};siteID,scope,err:=target.site(ctx,intent,source.SiteID);if err!=nil{return desired,err};repositoryID:=strings.TrimPrefix(source.Repository,"target:");if _,err=access.ParseRelativePath(repositoryID);err!=nil||strings.Contains(repositoryID,"/")||repositoryID==""{return desired,migration.ErrInvalid};spec,err:=target.services.backup.Catalog.Repository(ctx,scope.TenantID,backup.RepositoryID(repositoryID));if err!=nil{return desired,err};if spec.TenantID!=scope.TenantID||string(spec.Repository.Kind)!=source.Provider||target.services.backup.Set.Registry()[spec.Repository.Kind]==nil||target.services.backup.Set.ProberRegistry()[spec.Repository.Kind]==nil{return desired,migration.ErrBlocked};if _,err=access.ParseCronExpression(source.Schedule);err!=nil{return desired,err}
		var typed struct{Version uint8 `json:"version"`;Components []backup.ComponentKind `json:"components"`;Consistency backup.ConsistencyClass `json:"consistency"`;Retention backup.RetentionPolicy `json:"retention"`};if migrationAuxiliaryDecode([]byte(source.Retention),&typed)!=nil||typed.Version!=1||len(typed.Components)!=1||typed.Components[0]!=backup.ComponentFiles||typed.Consistency!=backup.ConsistencyFuzzy||typed.Retention.KeepLast==0||typed.Retention.KeepLast>10000||typed.Retention.MinimumVerifiedCopies!=1||typed.Retention.RequireDistinctFailureDomains{return desired,migration.ErrBlocked};policy:=backup.BackupPolicySpec{ID:backup.PolicyID(intent.TargetID.String()),TenantID:scope.TenantID,Scope:string(siteID),Schedule:source.Schedule,Components:[]backup.ComponentKind{backup.ComponentFiles},Repositories:[]backup.RepositoryID{spec.Repository.ID},RequiredCopies:1,Consistency:typed.Consistency,Retention:typed.Retention,Generation:1};desired.Policy=&policy;desired.BackupRepository=&spec
	};return desired,nil
}

func (target *migrationAuxiliaryTarget) claim(ctx context.Context,intent migration.ImportIntent,desired migrationAuxiliaryDesired)(string,error){
	var raw []byte;var state,digest string;err:=target.host.db.QueryRowContext(ctx,`SELECT desired_json,state,input_digest FROM panel_migration_auxiliary_effects WHERE migration_id=? AND target_id=? AND kind=?`,intent.MigrationID.String(),intent.TargetID.String(),string(intent.Kind)).Scan(&raw,&state,&digest);encoded,_:=json.Marshal(desired);if err==nil{if digest!=intent.InputDigest||!bytes.Equal(raw,encoded){return "",migration.ErrConflict};return state,nil};if !errors.Is(err,sql.ErrNoRows){return "",err}
	// Check the actual domain identity before recording creation ownership.
	if desired.Repository!=nil{_,err=target.services.git.Store.LoadRepository(ctx,desired.Repository.ID)}else if desired.Cron!=nil{_,err=target.services.cron.Store.LoadCron(ctx,desired.Cron.ID)}else{_,err=target.services.backup.Catalog.Policy(ctx,desired.Policy.TenantID,desired.Policy.ID)};if !errors.Is(err,access.ErrNotFound)&&!errors.Is(err,sql.ErrNoRows){return "",errors.Join(migration.ErrConflict,err)}
	_,err=target.host.db.ExecContext(ctx,`INSERT INTO panel_migration_auxiliary_effects(migration_id,target_id,kind,input_digest,desired_json,state,receipt_json) VALUES(?,?,?,?,?,'claimed','{}')`,intent.MigrationID.String(),intent.TargetID.String(),string(intent.Kind),intent.InputDigest,encoded);return "claimed",err
}

func (target *migrationAuxiliaryTarget) save(ctx context.Context,intent migration.ImportIntent,state string,evidence any)(migration.ImportEffect,error){effect:=migrationHostEffect(intent,evidence,1,0,1);if state=="compensated"{effect.Status=migration.ImportEffectCompensated;effect.TargetGeneration=0};raw,_:=json.Marshal(effect);_,err:=target.host.db.ExecContext(ctx,`UPDATE panel_migration_auxiliary_effects SET state=?,receipt_json=? WHERE migration_id=? AND target_id=? AND input_digest=?`,state,raw,intent.MigrationID.String(),intent.TargetID.String(),intent.InputDigest);return effect,err}

func (target *migrationAuxiliaryTarget) Apply(ctx context.Context,intent migration.ImportIntent)(migration.ImportEffect,error){
	desired,err:=target.desired(ctx,intent);if err!=nil{return migration.ImportEffect{},err};state,err:=target.claim(ctx,intent,desired);if err!=nil{return migration.ImportEffect{},err};if state=="active"||state=="activating"||state=="compensated"{return migration.ImportEffect{},migration.ErrWriteFrontier}
	if desired.Repository!=nil{return target.Observe(ctx,intent)}
	if desired.Cron!=nil{job:=*desired.Cron;job.Enabled=false;current,loadErr:=target.services.cron.Store.LoadCron(ctx,job.ID);if errors.Is(loadErr,access.ErrNotFound)||errors.Is(loadErr,sql.ErrNoRows){_,err=target.services.cron.Create(ctx,job)}else if loadErr!=nil{return migration.ImportEffect{},loadErr}else if !migrationCronMatches(current,job){return migration.ImportEffect{},migration.ErrConflict};if err!=nil{return migration.ImportEffect{},err}}
	if desired.Policy!=nil{policy:=*desired.Policy;policy.Enabled=false;current,loadErr:=target.services.backup.Catalog.Policy(ctx,policy.TenantID,policy.ID);if errors.Is(loadErr,sql.ErrNoRows){err=target.services.backup.Catalog.PutPolicy(ctx,policy,0)}else if loadErr!=nil{return migration.ImportEffect{},loadErr}else if !migrationBackupMatches(current,policy){return migration.ImportEffect{},migration.ErrConflict};if err!=nil{return migration.ImportEffect{},err}}
	return target.Observe(ctx,intent)
}

func migrationCronMatches(left,right access.CronJob)bool{return left.ID==right.ID&&left.SiteID==right.SiteID&&left.Schedule.String()==right.Schedule.String()&&left.Timezone==right.Timezone&&migrationHostDigest(left.Invocation)==migrationHostDigest(right.Invocation)&&left.Concurrency==right.Concurrency&&left.TimeoutSeconds==right.TimeoutSeconds&&left.Output==right.Output&&left.Enabled==right.Enabled}
func migrationBackupMatches(left,right backup.BackupPolicySpec)bool{left.Generation=right.Generation;return migrationHostDigest(left)==migrationHostDigest(right)}

func (target *migrationAuxiliaryTarget) script(ctx context.Context,desired migrationAuxiliaryDesired)error{relative,_:=access.ParseRelativePath(desired.ScriptPath);locator:=access.FileLocator{Root:access.SiteRoot{SiteID:desired.Cron.SiteID,Kind:access.RootPublic},Path:relative};entry,err:=target.host.files.Executor.Stat(ctx,locator);if err!=nil||entry.Kind!=access.EntryRegular||entry.Size<1||entry.Size>16<<20{return errors.Join(migration.ErrBlocked,err)};_,err=target.host.verifyMigrationFile(ctx,locator,migrationFile{Path:desired.ScriptPath,Size:entry.Size,Mode:entry.Mode,Digest:desired.ScriptDigest});return err}

func (target *migrationAuxiliaryTarget) cronReceipt(ctx context.Context,job access.CronJob)(access.CronApplyReceipt,error){jobs,err:=target.services.cron.Store.ListCrons(ctx,job.SiteID,true);if err!=nil{return access.CronApplyReceipt{},err};generation,err:=target.services.cron.Store.NextCronGeneration(ctx,job.SiteID);if err!=nil{return access.CronApplyReceipt{},err};receipt,err:=target.services.cron.Executor.ApplySchedule(ctx,job.SiteID,generation,jobs);if err!=nil||receipt.SiteID!=job.SiteID||receipt.Generation!=generation||receipt.Digest==""||receipt.Receipt==""||receipt.AppliedAt.IsZero(){return receipt,errors.Join(migration.ErrAmbiguous,err)};return receipt,target.services.cron.Store.SaveCronReceipt(ctx,receipt)}

func (target *migrationAuxiliaryTarget) backupProbe(ctx context.Context,desired migrationAuxiliaryDesired,intent migration.ImportIntent,active bool)(backupproviders.RepositoryProbe,error){
	current,err:=target.services.backup.Catalog.Repository(ctx,desired.Policy.TenantID,desired.BackupRepository.Repository.ID);if err!=nil||migrationHostDigest(current)!=migrationHostDigest(*desired.BackupRepository){return backupproviders.RepositoryProbe{},errors.Join(migration.ErrConflict,err)};var probe backupproviders.RepositoryProbe;if active{probe,err=target.services.backup.Lifecycle.Probe(ctx,current,"migration-policy-"+intent.EffectID)}else{probe,err=target.services.backup.Lifecycle.Latest(ctx,current.Repository.ID)}
	if err!=nil||probe.RepositoryID!=current.Repository.ID||probe.Kind!=current.Repository.Kind||probe.Health!=backupproviders.RepositoryHealthy||probe.DetailDigest==""||probe.ObservedAt.After(time.Now().UTC())||time.Since(probe.ObservedAt)>24*time.Hour{return probe,errors.Join(migration.ErrBlocked,err)};capabilities:=map[string]bool{};for _,value:=range probe.Capabilities{capabilities[value]=true};if !capabilities["commit_marker"]||!capabilities["stream_restore"]{return probe,migration.ErrBlocked};return probe,nil
}

func (target *migrationAuxiliaryTarget) Observe(ctx context.Context,intent migration.ImportIntent)(migration.ImportEffect,error){
	desired,err:=target.desired(ctx,intent);if err!=nil{return migration.ImportEffect{},err};state,err:=target.claim(ctx,intent,desired);if err!=nil{return migration.ImportEffect{},err};if state=="activating"||state=="compensated"{return migration.ImportEffect{},migration.ErrAmbiguous};active:=state=="active";next:="dark";if active{next="active"}
	if desired.Repository!=nil{if !active{_,loadErr:=target.services.git.Store.LoadRepository(ctx,desired.Repository.ID);if !errors.Is(loadErr,access.ErrNotFound)&&!errors.Is(loadErr,sql.ErrNoRows){return migration.ImportEffect{},errors.Join(migration.ErrConflict,loadErr)};effect,err:=target.save(ctx,intent,next,struct{State string;Desired access.GitRepository}{"remote-uncontacted-binding-staged",*desired.Repository});effect.ErrorCode="REPOSITORY_STAGED_REMOTE_UNCONTACTED";return effect,err};current,loadErr:=target.services.git.Store.LoadRepository(ctx,desired.Repository.ID);if loadErr!=nil||!migrationGitMatches(current,*desired.Repository)||current.State!=access.StateActive||current.ExecutorReceipt==""{return migration.ImportEffect{},errors.Join(migration.ErrBlocked,loadErr)};status,probeErr:=target.services.git.Status(ctx,current.ID);if probeErr!=nil||status.HeadRevision!=current.HeadRevision||status.Branch!=current.Branch{return migration.ImportEffect{},errors.Join(migration.ErrBlocked,probeErr)};return target.save(ctx,intent,next,struct{Repository access.GitRepository;Status access.GitStatus}{current,status})}
	if desired.Cron!=nil{wanted:=*desired.Cron;if !active{wanted.Enabled=false};job,loadErr:=target.services.cron.Store.LoadCron(ctx,wanted.ID);if loadErr!=nil||!migrationCronMatches(job,wanted)||job.State!=access.StateActive{return migration.ImportEffect{},errors.Join(migration.ErrBlocked,loadErr)};if err=target.script(ctx,desired);err!=nil{return migration.ImportEffect{},err};receipt,probeErr:=target.cronReceipt(ctx,job);if probeErr!=nil{return migration.ImportEffect{},probeErr};return target.save(ctx,intent,next,struct{Job access.CronJob;Receipt access.CronApplyReceipt;Script string}{job,receipt,desired.ScriptDigest})}
	wanted:=*desired.Policy;wanted.Enabled=active;policy,loadErr:=target.services.backup.Catalog.Policy(ctx,wanted.TenantID,wanted.ID);if loadErr!=nil||!migrationBackupMatches(policy,wanted){return migration.ImportEffect{},errors.Join(migration.ErrBlocked,loadErr)};probe,err:=target.backupProbe(ctx,desired,intent,active);if err!=nil{return migration.ImportEffect{},err};return target.save(ctx,intent,next,struct{Policy backup.BackupPolicySpec;Probe backupproviders.RepositoryProbe}{policy,probe})
}

func migrationGitMatches(left,right access.GitRepository)bool{return left.ID==right.ID&&left.SiteID==right.SiteID&&left.Provider==right.Provider&&left.Remote==right.Remote&&left.CredentialRef==""&&left.DeployKeyID==""&&left.Worktree==right.Worktree&&left.Branch==right.Branch&&left.Strategy==access.GitManual&&!left.AutoDeploy}

func (target *migrationAuxiliaryTarget) Activate(ctx context.Context,intent migration.ImportIntent)(migration.ImportEffect,error){
	desired,err:=target.desired(ctx,intent);if err!=nil{return migration.ImportEffect{},err};state,err:=target.claim(ctx,intent,desired);if err!=nil{return migration.ImportEffect{},err};if state=="active"{return target.Observe(ctx,intent)};if state!="dark"{return migration.ImportEffect{},migration.ErrAmbiguous};value,err:=target.host.repository.Migration(ctx,intent.MigrationID);if err!=nil{return migration.ImportEffect{},err};if err=target.host.sourceFence(ctx,value);err!=nil{return migration.ImportEffect{},err}
	if _,err=target.host.db.ExecContext(ctx,`UPDATE panel_migration_auxiliary_effects SET state='activating' WHERE migration_id=? AND target_id=? AND state='dark'`,intent.MigrationID.String(),intent.TargetID.String());err!=nil{return migration.ImportEffect{},err}
	var proof any
	if desired.Repository!=nil{repository,applyErr:=target.services.git.Attach(ctx,*desired.Repository);if applyErr!=nil||repository.State!=access.StateActive||repository.ExecutorReceipt==""{return migration.ImportEffect{},errors.Join(migration.ErrAmbiguous,applyErr)};proof=repository}
	if desired.Cron!=nil{if err=target.script(ctx,desired);err!=nil{return migration.ImportEffect{},err};current,loadErr:=target.services.cron.Store.LoadCron(ctx,desired.Cron.ID);if loadErr!=nil{return migration.ImportEffect{},loadErr};job,applyErr:=target.services.cron.Update(ctx,*desired.Cron,current.Generation);if applyErr!=nil||job.State!=access.StateActive||job.ExecutorReceipt==""{return migration.ImportEffect{},errors.Join(migration.ErrAmbiguous,applyErr)};proof=job}
	if desired.Policy!=nil{probe,probeErr:=target.backupProbe(ctx,desired,intent,true);if probeErr!=nil{return migration.ImportEffect{},probeErr};current,loadErr:=target.services.backup.Catalog.Policy(ctx,desired.Policy.TenantID,desired.Policy.ID);if loadErr!=nil{return migration.ImportEffect{},loadErr};wanted:=*desired.Policy;wanted.Enabled=true;wanted.Generation=current.Generation+1;if err=target.services.backup.Catalog.PutPolicy(ctx,wanted,current.Generation);err!=nil{return migration.ImportEffect{},err};proof=struct{Policy backup.BackupPolicySpec;Probe backupproviders.RepositoryProbe}{wanted,probe}}
	if _,err=target.save(ctx,intent,"active",proof);err!=nil{return migration.ImportEffect{},err};return target.Observe(ctx,intent)
}

func (target *migrationAuxiliaryTarget) Compensate(ctx context.Context,intent migration.ImportIntent,_ migration.ImportEffect)(migration.ImportEffect,error){
	desired,err:=target.desired(ctx,intent);if err!=nil{return migration.ImportEffect{},err};state,err:=target.claim(ctx,intent,desired);if err!=nil{return migration.ImportEffect{},err};if state=="active"||state=="activating"{return migration.ImportEffect{},migration.ErrWriteFrontier};if state=="compensated"{var raw []byte;if err=target.host.db.QueryRowContext(ctx,`SELECT receipt_json FROM panel_migration_auxiliary_effects WHERE migration_id=? AND target_id=?`,intent.MigrationID.String(),intent.TargetID.String()).Scan(&raw);err!=nil{return migration.ImportEffect{},err};var effect migration.ImportEffect;if json.Unmarshal(raw,&effect)!=nil||effect.Status!=migration.ImportEffectCompensated||effect.EvidenceDigest==""{return effect,migration.ErrAmbiguous};return effect,nil}
	var proof any
	if desired.Repository!=nil{_,loadErr:=target.services.git.Store.LoadRepository(ctx,desired.Repository.ID);if !errors.Is(loadErr,access.ErrNotFound)&&!errors.Is(loadErr,sql.ErrNoRows){return migration.ImportEffect{},errors.Join(migration.ErrConflict,loadErr)};proof=struct{ID,State string}{intent.TargetID.String(),"never-attached-staged-binding-removed"}}
	if desired.Cron!=nil{job,loadErr:=target.services.cron.Store.LoadCron(ctx,desired.Cron.ID);if loadErr!=nil||job.Enabled{return migration.ImportEffect{},errors.Join(migration.ErrAmbiguous,loadErr)};if err=target.services.cron.Delete(ctx,job.ID,job.Generation);err!=nil{return migration.ImportEffect{},err};receipt,probeErr:=target.cronReceipt(ctx,job);if probeErr!=nil{return migration.ImportEffect{},probeErr};proof=receipt}
	if desired.Policy!=nil{policy,loadErr:=target.services.backup.Catalog.Policy(ctx,desired.Policy.TenantID,desired.Policy.ID);if loadErr!=nil||policy.Enabled{return migration.ImportEffect{},errors.Join(migration.ErrAmbiguous,loadErr)};if err=target.services.backup.Catalog.DeletePolicy(ctx,policy.TenantID,policy.ID,policy.Generation);err!=nil{return migration.ImportEffect{},err};if _,err=target.services.backup.Catalog.Policy(ctx,policy.TenantID,policy.ID);!errors.Is(err,sql.ErrNoRows){return migration.ImportEffect{},errors.Join(migration.ErrConflict,err)};proof=struct{Policy backup.BackupPolicySpec;State string}{policy,"disabled-policy-deleted-repository-retained"}}
	return target.save(ctx,intent,"compensated",proof)
}
