//go:build linux

package main

import (
	"context"
	"errors"
	"strings"
	"time"

	"github.com/aonsyed/cyberpanel/platform/internal/apiserver"
	"github.com/aonsyed/cyberpanel/platform/internal/operations"
)

type operationsEdgeRepository interface{LoadResource(context.Context,operations.ResourceKind,operations.ResourceID)(operations.ResourceEnvelope,error)}
type operationsEdge struct{commands apiserver.OperationsCommandService;repository operationsEdgeRepository;node operations.ResourceID;now func()time.Time}

func newOperationsEdge(commands apiserver.OperationsCommandService,repository operationsEdgeRepository,nodeID string)(apiserver.OperationsEdgeService,error){if commands==nil||repository==nil{return nil,errors.New("operations edge dependencies are required")};node,err:=operations.NewResourceID(nodeID);if err!=nil{return nil,err};return &operationsEdge{commands:commands,repository:repository,node:node,now:time.Now},nil}

var operationsEdgeServices=[]operations.ServiceName{operations.ServiceWebEnterprise,operations.ServiceWebOpenLiteSpeed,operations.ServiceMariaDB,operations.ServicePostfix,operations.ServiceDovecot,operations.ServicePowerDNS,operations.ServicePureFTPd,operations.ServiceRedis,operations.ServiceElasticsearch,operations.ServicePanel}

func operationsServiceName(raw string)(operations.ServiceName,error){value:=operations.ServiceName(strings.TrimSpace(raw));for _,candidate:=range operationsEdgeServices{if value==candidate{return value,nil}};return "",operations.ErrInvalidResource}
func operationsPolicyID(service operations.ServiceName)operations.ResourceID{id,_:=operations.NewResourceID("service-"+string(service));return id}
func(edge *operationsEdge)header(call apiserver.EdgeCall,suffix string)(operations.CommandHeader,error){if call.TenantID!=""{return operations.CommandHeader{},operations.ErrUnauthorized};principal,err:=operations.NewResourceID(call.PrincipalID);if err!=nil{return operations.CommandHeader{},operations.ErrUnauthorized};now:=edge.now().UTC();return operations.CommandHeader{CommandID:call.CommandID+suffix,NodeID:edge.node,Actor:operations.Actor{PrincipalID:principal,Capabilities:[]operations.Capability{operations.CapabilityNodeOperations}},RequestedAt:now,Deadline:now.Add(2*time.Minute)},nil}
func(edge *operationsEdge)policy(ctx context.Context,service operations.ServiceName)(*operations.ServicePolicy,error){envelope,err:=edge.repository.LoadResource(ctx,operations.KindServicePolicy,operationsPolicyID(service));if err!=nil{return nil,err};value,err:=operations.DecodeResource(envelope);if err!=nil{return nil,err};policy,ok:=value.(*operations.ServicePolicy);if !ok{return nil,operations.ErrInvalidResource};return policy,nil}
func(edge *operationsEdge)diagnose(ctx context.Context,call apiserver.EdgeCall,service operations.ServiceName,depth operations.DiagnosticDepth,suffix string,since time.Time)(apiserver.OperationsServiceProjection,operations.OperationReceipt,error){header,err:=edge.header(call,suffix);if err!=nil{return apiserver.OperationsServiceProjection{},operations.OperationReceipt{},err};if since.IsZero(){since=edge.now().UTC().Add(-15*time.Minute)};receipt,err:=edge.commands.Handle(ctx,operations.DiagnoseService{Header:header,Service:service,Depth:depth,Since:since});if err!=nil{return apiserver.OperationsServiceProjection{},receipt,err};diagnostics:=receipt.Effect.Result.Diagnostics;if diagnostics==nil{return apiserver.OperationsServiceProjection{},receipt,operations.ErrInvalidReceipt};generation:=uint64(0);if policy,loadErr:=edge.policy(ctx,service);loadErr==nil{generation=policy.Generation};health:="healthy";if diagnostics.ActiveState!="active"{health="unavailable"};for _,check:=range diagnostics.Checks{if check.Outcome==operations.CheckFail{health="degraded";break}else if check.Outcome==operations.CheckWarn&&health=="healthy"{health="warning"}};return apiserver.OperationsServiceProjection{ID:string(service),Name:string(service),ActiveState:diagnostics.ActiveState,SubState:diagnostics.SubState,RestartCount:uint64(diagnostics.RestartCount),Health:health,Generation:generation,UpdatedAt:receipt.Effect.CompletedAt},receipt,nil}

func(edge *operationsEdge)ListServices(ctx context.Context,call apiserver.EdgeCall,page apiserver.EdgePagePayload)(apiserver.EdgePage[apiserver.OperationsServiceProjection],error){if call.TenantID!=""{return apiserver.EdgePage[apiserver.OperationsServiceProjection]{},operations.ErrUnauthorized};start:=0;if page.Cursor!=""{for start<len(operationsEdgeServices)&&string(operationsEdgeServices[start])<=page.Cursor{start++}};limit:=int(page.Limit);if limit==0{limit=100};end:=start+limit;if end>len(operationsEdgeServices){end=len(operationsEdgeServices)};items:=make([]apiserver.OperationsServiceProjection,0,end-start);for index,service:=range operationsEdgeServices[start:end]{projection,_,err:=edge.diagnose(ctx,call,service,accessEdgeID("-list-",string(service),call.CommandID),operations.DiagnosticSummary,time.Time{});if errors.Is(err,operations.ErrNotFound){continue};if err!=nil{return apiserver.EdgePage[apiserver.OperationsServiceProjection]{},err};items=append(items,projection);_ = index};next:="";if end<len(operationsEdgeServices)&&len(items)>0{next=string(operationsEdgeServices[end-1])};return apiserver.EdgePage[apiserver.OperationsServiceProjection]{Items:items,NextCursor:next,Total:uint64(len(operationsEdgeServices))},nil}

func(edge *operationsEdge)control(ctx context.Context,call apiserver.EdgeCall,action operations.ServiceAction)(apiserver.EdgeMutation[apiserver.OperationsServiceProjection],error){service,err:=operationsServiceName(call.ResourceID);if err!=nil{return apiserver.EdgeMutation[apiserver.OperationsServiceProjection]{},err};policy,err:=edge.policy(ctx,service);if err!=nil{return apiserver.EdgeMutation[apiserver.OperationsServiceProjection]{},err};if call.ExpectedGeneration==0||call.ExpectedGeneration!=policy.Generation{return apiserver.EdgeMutation[apiserver.OperationsServiceProjection]{},operations.ErrConflict};header,err:=edge.header(call,"-control");if err!=nil{return apiserver.EdgeMutation[apiserver.OperationsServiceProjection]{},err};receipt,err:=edge.commands.Handle(ctx,operations.ControlService{Header:header,Service:service,Action:action,ExpectedPolicyGeneration:policy.Generation});if err!=nil{return apiserver.EdgeMutation[apiserver.OperationsServiceProjection]{},err};projection,_,err:=edge.diagnose(ctx,call,service,operations.DiagnosticSummary,"-observe",time.Time{});if err!=nil{return apiserver.EdgeMutation[apiserver.OperationsServiceProjection]{},err};return apiserver.EdgeMutation[apiserver.OperationsServiceProjection]{OperationID:receipt.CommandID,State:string(receipt.Status),Generation:projection.Generation,Resource:projection},nil}
func(edge *operationsEdge)RestartService(ctx context.Context,call apiserver.EdgeCall)(apiserver.EdgeMutation[apiserver.OperationsServiceProjection],error){return edge.control(ctx,call,operations.ServiceRestart)}
func(edge *operationsEdge)StopService(ctx context.Context,call apiserver.EdgeCall)(apiserver.EdgeMutation[apiserver.OperationsServiceProjection],error){return edge.control(ctx,call,operations.ServiceStop)}
func(edge *operationsEdge)RunDiagnostic(ctx context.Context,call apiserver.EdgeCall,payload apiserver.OperationsDiagnosticPayload)(apiserver.EdgeMutation[apiserver.OperationsServiceProjection],error){service,err:=operationsServiceName(call.ResourceID);if err!=nil{return apiserver.EdgeMutation[apiserver.OperationsServiceProjection]{},err};depth:=operations.DiagnosticDependency;switch payload.Depth{case"quick":depth=operations.DiagnosticSummary;case"deep":depth=operations.DiagnosticDeep};projection,receipt,err:=edge.diagnose(ctx,call,service,depth,"-diagnose",payload.Since);if err!=nil{return apiserver.EdgeMutation[apiserver.OperationsServiceProjection]{},err};return apiserver.EdgeMutation[apiserver.OperationsServiceProjection]{OperationID:receipt.CommandID,State:string(receipt.Status),Generation:projection.Generation,Resource:projection},nil}

var _ apiserver.OperationsEdgeService=(*operationsEdge)(nil)
