package identity

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"
)

type OwnershipResourceKind string
const(
	OwnershipSite OwnershipResourceKind="site";OwnershipDatabase OwnershipResourceKind="database";OwnershipDNS OwnershipResourceKind="dns"
	OwnershipMail OwnershipResourceKind="mail";OwnershipFTP OwnershipResourceKind="ftp";OwnershipBackup OwnershipResourceKind="backup"
	OwnershipApplication OwnershipResourceKind="application";OwnershipSchedule OwnershipResourceKind="schedule"
)
func knownOwnershipKind(value OwnershipResourceKind)bool{switch value{case OwnershipSite,OwnershipDatabase,OwnershipDNS,OwnershipMail,OwnershipFTP,OwnershipBackup,OwnershipApplication,OwnershipSchedule:return true};return false}

type OwnershipTransferFrontier string
const(OwnershipFrontierAuthorization OwnershipTransferFrontier="authorization_rebound";OwnershipFrontierAccounting OwnershipTransferFrontier="accounting_rebound")
type OwnershipTransferState string
const(OwnershipTransferPlanned OwnershipTransferState="planned";OwnershipTransferRunning OwnershipTransferState="running";OwnershipTransferCompensating OwnershipTransferState="compensating";OwnershipTransferCompleted OwnershipTransferState="completed";OwnershipTransferFailed OwnershipTransferState="failed";OwnershipTransferRecoveryRequired OwnershipTransferState="recovery_required")
type OwnershipTransferStepState string
const(OwnershipStepPending OwnershipTransferStepState="pending";OwnershipStepAuthorizationRebound OwnershipTransferStepState="authorization_rebound";OwnershipStepAccountingRebound OwnershipTransferStepState="accounting_rebound";OwnershipStepCompleted OwnershipTransferStepState="completed";OwnershipStepCompensated OwnershipTransferStepState="compensated";OwnershipStepRecoveryRequired OwnershipTransferStepState="recovery_required")

type OwnershipTransferResource struct{Kind OwnershipResourceKind;ResourceID ID;Quota map[QuotaDimension]uint64;ExpectedGeneration uint64}
func(value OwnershipTransferResource)Validate()error{if !knownOwnershipKind(value.Kind)||!value.ResourceID.Valid()||value.ExpectedGeneration==0||len(value.Quota)>len(allQuotaDimensions){return ErrInvalid};for dimension,amount:=range value.Quota{if !knownQuotaDimension(dimension)||amount==0{return ErrInvalid}};return nil}
type OwnershipTransferReceipt struct{Adapter string;OperationID string;Digest string;Generation uint64;FrontierReached bool;ObservedAt time.Time}
func(value OwnershipTransferReceipt)Validate()error{if strings.TrimSpace(value.Adapter)==""||len(value.Adapter)>128||strings.TrimSpace(value.OperationID)==""||len(value.OperationID)>256||len(value.Digest)!=64||value.Generation==0||value.ObservedAt.IsZero(){return ErrInvalid};if _,err:=hex.DecodeString(value.Digest);err!=nil{return ErrInvalid};return nil}

type OwnershipTransferContext struct{TransferID ID;SourceTenantID ID;DestinationTenantID ID;ActorID ID;RequestDigest string}
type OwnershipTransferAdapter interface{
	Preflight(context.Context,OwnershipTransferContext,OwnershipTransferResource)error
	RebindAuthorization(context.Context,OwnershipTransferContext,OwnershipTransferResource)(OwnershipTransferReceipt,error)
	RebindAccounting(context.Context,OwnershipTransferContext,OwnershipTransferResource,OwnershipTransferReceipt)(OwnershipTransferReceipt,error)
	Compensate(context.Context,OwnershipTransferContext,OwnershipTransferResource,OwnershipTransferReceipt,OwnershipTransferReceipt)(OwnershipTransferReceipt,error)
	Recover(context.Context,OwnershipTransferContext,OwnershipTransferResource,OwnershipTransferReceipt,OwnershipTransferReceipt)(OwnershipTransferReceipt,error)
}

type OwnershipTransferStep struct{Ordinal uint16;Resource OwnershipTransferResource;State OwnershipTransferStepState;Phase OwnershipTransferFrontier;AuthorizationReceipt *OwnershipTransferReceipt;AccountingReceipt *OwnershipTransferReceipt;CompensationReceipt *OwnershipTransferReceipt;FrontierReached bool;Attempt uint64;LastError string;UpdatedAt time.Time}
type OwnershipTransfer struct{ID ID;SourceTenantID ID;DestinationTenantID ID;State OwnershipTransferState;Frontier OwnershipTransferFrontier;Revision uint64;ActorID ID;RequestDigest string;LastError string;CreatedAt time.Time;UpdatedAt time.Time;CompletedAt *time.Time;Steps []OwnershipTransferStep}
type OwnershipTransferPreview struct{SourceTenantID ID;DestinationTenantID ID;Resources []OwnershipTransferResource;QuotaAfter map[QuotaDimension]uint64;Blockers []string;RequestDigest string}
type StartOwnershipTransferCommand struct{Actor ActorContext;TransferID ID;SourceTenantID ID;DestinationTenantID ID;Frontier OwnershipTransferFrontier;Resources []OwnershipTransferResource}

type OwnershipTransferCoordinator struct{service *Service;adapters map[OwnershipResourceKind]OwnershipTransferAdapter;clock func()time.Time}
func NewOwnershipTransferCoordinator(service *Service,adapters map[OwnershipResourceKind]OwnershipTransferAdapter)(*OwnershipTransferCoordinator,error){if service==nil||service.store==nil||len(adapters)==0{return nil,ErrInvalid};copied:=map[OwnershipResourceKind]OwnershipTransferAdapter{};for kind,adapter:=range adapters{if !knownOwnershipKind(kind)||adapter==nil{return nil,ErrInvalid};copied[kind]=adapter};return &OwnershipTransferCoordinator{service:service,adapters:copied,clock:time.Now},nil}

func canonicalTransferResources(values []OwnershipTransferResource)([]OwnershipTransferResource,error){if len(values)==0||len(values)>100{return nil,ErrInvalid};result:=append([]OwnershipTransferResource(nil),values...);sort.Slice(result,func(i,j int)bool{if result[i].Kind==result[j].Kind{return result[i].ResourceID<result[j].ResourceID};return result[i].Kind<result[j].Kind});for index,value:=range result{if value.Validate()!=nil||index>0&&value.Kind==result[index-1].Kind&&value.ResourceID==result[index-1].ResourceID{return nil,ErrInvalid}};return result,nil}
func transferContext(value OwnershipTransfer)OwnershipTransferContext{return OwnershipTransferContext{TransferID:value.ID,SourceTenantID:value.SourceTenantID,DestinationTenantID:value.DestinationTenantID,ActorID:value.ActorID,RequestDigest:value.RequestDigest}}

func (c *OwnershipTransferCoordinator)authorize(ctx context.Context,actor ActorContext,source,destination ID,minimum AssuranceLevel,recent bool)error{if source==destination||!source.Valid()||!destination.Valid(){return ErrInvalid};for _,tenant:=range []ID{source,destination}{if _,err:=c.service.authorize(ctx,actor,"identity:manage",Scope{Kind:ScopeTenant,TenantID:tenant},minimum);err!=nil{return err}};if recent{return c.service.validateRecentRoleStepUp(ctx,actor)};return nil}

func quotaDemand(resources []OwnershipTransferResource)map[QuotaDimension]uint64{result:=map[QuotaDimension]uint64{};for _,resource:=range resources{for dimension,amount:=range resource.Quota{next:=result[dimension]+amount;if next<result[dimension]{result[dimension]=mathMaxUint64}else{result[dimension]=next}}};return result}
const mathMaxUint64=^uint64(0)

func (c *OwnershipTransferCoordinator)Preview(ctx context.Context,actor ActorContext,source,destination ID,resources []OwnershipTransferResource)(OwnershipTransferPreview,error){if err:=c.authorize(ctx,actor,source,destination,AssuranceMFA,false);err!=nil{return OwnershipTransferPreview{},err};resources,err:=canonicalTransferResources(resources);if err!=nil{return OwnershipTransferPreview{},err};preview:=OwnershipTransferPreview{SourceTenantID:source,DestinationTenantID:destination,Resources:resources,QuotaAfter:map[QuotaDimension]uint64{}};digest:=tenantDigest(struct{Source,Destination ID;Resources []OwnershipTransferResource}{source,destination,resources});contextValue:=OwnershipTransferContext{SourceTenantID:source,DestinationTenantID:destination,ActorID:actor.PrincipalID,RequestDigest:digest};demand:=quotaDemand(resources);for dimension,amount:=range demand{var limit,consumed,reserved uint64;var unlimited int;loadErr:=c.service.store.db.QueryRowContext(ctx,`SELECT limit_value,unlimited,consumed,reserved FROM identity_quota_ledgers WHERE tenant_id=? AND dimension=?`,destination,dimension).Scan(&limit,&unlimited,&consumed,&reserved);if errors.Is(loadErr,sql.ErrNoRows){preview.Blockers=append(preview.Blockers,"quota_missing:"+string(dimension));continue}else if loadErr!=nil{return preview,loadErr};if consumed>mathMaxUint64-reserved||consumed+reserved>mathMaxUint64-amount{preview.Blockers=append(preview.Blockers,"quota_overflow:"+string(dimension));continue};after:=consumed+reserved+amount;preview.QuotaAfter[dimension]=after;if unlimited==0&&after>limit{preview.Blockers=append(preview.Blockers,"quota_exceeded:"+string(dimension))}}
	for _,resource:=range resources{adapter:=c.adapters[resource.Kind];if adapter==nil{preview.Blockers=append(preview.Blockers,"adapter_missing:"+string(resource.Kind));continue};if preflightErr:=adapter.Preflight(ctx,contextValue,resource);preflightErr!=nil{preview.Blockers=append(preview.Blockers,"preflight:"+string(resource.Kind)+":"+resource.ResourceID.String())}}
	sort.Strings(preview.Blockers);preview.RequestDigest=tenantDigest(struct{Source,Destination ID;Resources []OwnershipTransferResource;Blockers []string}{source,destination,resources,preview.Blockers});return preview,nil}

func (c *OwnershipTransferCoordinator)audit(ctx context.Context,value OwnershipTransfer,action,outcome string)error{request:="transfer:"+value.ID.String()+"\x00revision:"+fmt.Sprint(value.Revision)+"\x00digest:"+value.RequestDigest;sum:=sha256.Sum256([]byte(action+"\x00"+request));return c.service.audit.Record(ctx,AuditEvent{ID:hex.EncodeToString(sum[:]),ActorID:value.ActorID,TenantID:value.SourceTenantID,Action:action,TargetKind:"ownership_transfer",TargetID:value.ID,Outcome:outcome,RequestHash:tenantDigest(request),At:c.clock().UTC()})}

func (c *OwnershipTransferCoordinator)Start(ctx context.Context,command StartOwnershipTransferCommand)(OwnershipTransfer,error){if !command.TransferID.Valid()||command.Frontier!=OwnershipFrontierAuthorization&&command.Frontier!=OwnershipFrontierAccounting{return OwnershipTransfer{},ErrInvalid};if err:=c.authorize(ctx,command.Actor,command.SourceTenantID,command.DestinationTenantID,AssurancePhishingResistant,true);err!=nil{return OwnershipTransfer{},err};preview,err:=c.Preview(ctx,command.Actor,command.SourceTenantID,command.DestinationTenantID,command.Resources);if err!=nil{return OwnershipTransfer{},err};if len(preview.Blockers)!=0{return OwnershipTransfer{},ErrConflict};now:=c.clock().UTC();value:=OwnershipTransfer{ID:command.TransferID,SourceTenantID:command.SourceTenantID,DestinationTenantID:command.DestinationTenantID,State:OwnershipTransferPlanned,Frontier:command.Frontier,Revision:1,ActorID:command.Actor.PrincipalID,RequestDigest:preview.RequestDigest,CreatedAt:now,UpdatedAt:now};tx,err:=c.service.store.db.BeginTx(ctx,&sql.TxOptions{Isolation:sql.LevelSerializable});if err!=nil{return OwnershipTransfer{},err};defer tx.Rollback();_,err=tx.ExecContext(ctx,`INSERT INTO identity_ownership_transfers(id,source_tenant_id,destination_tenant_id,state,frontier,revision,actor_id,request_digest,last_error,created_at,updated_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,NULL)`,value.ID,value.SourceTenantID,value.DestinationTenantID,value.State,value.Frontier,value.Revision,value.ActorID,value.RequestDigest,"",now,now);if err!=nil{return OwnershipTransfer{},err};for index,resource:=range preview.Resources{raw,_:=json.Marshal(resource);_,err=tx.ExecContext(ctx,`INSERT INTO identity_ownership_transfer_steps(transfer_id,ordinal,resource_kind,resource_id,state,phase,request_json,authorization_receipt_json,accounting_receipt_json,compensation_receipt_json,frontier_reached,attempt,last_error,updated_at) VALUES(?,?,?,?,?,?,?,'{}','{}','{}',0,0,'',?)`,value.ID,index,resource.Kind,resource.ResourceID,OwnershipStepPending,"",raw,now);if err!=nil{return OwnershipTransfer{},err};value.Steps=append(value.Steps,OwnershipTransferStep{Ordinal:uint16(index),Resource:resource,State:OwnershipStepPending,UpdatedAt:now})};if err=c.audit(ctx,value,"ownership_transfer.start","prepared");err!=nil{return OwnershipTransfer{},err};if err=tx.Commit();err!=nil{return OwnershipTransfer{},err};return value,nil}

func scanOwnershipTransfer(row interface{Scan(...any)error})(OwnershipTransfer,error){var value OwnershipTransfer;var state,frontier string;var completed sql.NullTime;err:=row.Scan(&value.ID,&value.SourceTenantID,&value.DestinationTenantID,&state,&frontier,&value.Revision,&value.ActorID,&value.RequestDigest,&value.LastError,&value.CreatedAt,&value.UpdatedAt,&completed);if errors.Is(err,sql.ErrNoRows){return value,ErrNotFound};if err!=nil{return value,err};value.State=OwnershipTransferState(state);value.Frontier=OwnershipTransferFrontier(frontier);if completed.Valid{at:=completed.Time;value.CompletedAt=&at};return value,nil}
func loadTransferSteps(ctx context.Context,db interface{QueryContext(context.Context,string,...any)(*sql.Rows,error)},transferID ID)([]OwnershipTransferStep,error){rows,err:=db.QueryContext(ctx,`SELECT ordinal,state,phase,request_json,authorization_receipt_json,accounting_receipt_json,compensation_receipt_json,frontier_reached,attempt,last_error,updated_at FROM identity_ownership_transfer_steps WHERE transfer_id=? ORDER BY ordinal LIMIT 101`,transferID);if err!=nil{return nil,err};defer rows.Close();var values []OwnershipTransferStep;for rows.Next(){var value OwnershipTransferStep;var state,phase string;var request,authorization,accounting,compensation []byte;var frontier int;if err=rows.Scan(&value.Ordinal,&state,&phase,&request,&authorization,&accounting,&compensation,&frontier,&value.Attempt,&value.LastError,&value.UpdatedAt);err!=nil{return nil,err};value.State=OwnershipTransferStepState(state);value.Phase=OwnershipTransferFrontier(phase);value.FrontierReached=frontier!=0;if json.Unmarshal(request,&value.Resource)!=nil{return nil,ErrInvalid};decode:=func(raw []byte,target **OwnershipTransferReceipt){if string(raw)=="{}"{return};var receipt OwnershipTransferReceipt;if json.Unmarshal(raw,&receipt)==nil{*target=&receipt}};decode(authorization,&value.AuthorizationReceipt);decode(accounting,&value.AccountingReceipt);decode(compensation,&value.CompensationReceipt);values=append(values,value)};if len(values)>100{return nil,ErrConflict};return values,rows.Err()}

func(c *OwnershipTransferCoordinator)Get(ctx context.Context,actor ActorContext,transferID ID)(OwnershipTransfer,error){value,err:=scanOwnershipTransfer(c.service.store.db.QueryRowContext(ctx,`SELECT id,source_tenant_id,destination_tenant_id,state,frontier,revision,actor_id,request_digest,last_error,created_at,updated_at,completed_at FROM identity_ownership_transfers WHERE id=?`,transferID));if err!=nil{return value,err};if err=c.authorize(ctx,actor,value.SourceTenantID,value.DestinationTenantID,AssurancePassword,false);err!=nil{return OwnershipTransfer{},ErrNotFound};value.Steps,err=loadTransferSteps(ctx,c.service.store.db,value.ID);return value,err}

func persistTransferStep(ctx context.Context,db *sql.DB,transferID ID,step OwnershipTransferStep)error{authorization,accounting,compensation:=[]byte("{}"),[]byte("{}"),[]byte("{}");if step.AuthorizationReceipt!=nil{authorization,_=json.Marshal(step.AuthorizationReceipt)};if step.AccountingReceipt!=nil{accounting,_=json.Marshal(step.AccountingReceipt)};if step.CompensationReceipt!=nil{compensation,_=json.Marshal(step.CompensationReceipt)};_,err:=db.ExecContext(ctx,`UPDATE identity_ownership_transfer_steps SET state=?,phase=?,authorization_receipt_json=?,accounting_receipt_json=?,compensation_receipt_json=?,frontier_reached=?,attempt=?,last_error=?,updated_at=? WHERE transfer_id=? AND ordinal=?`,step.State,step.Phase,authorization,accounting,compensation,boolInt(step.FrontierReached),step.Attempt,step.LastError,step.UpdatedAt,transferID,step.Ordinal);return err}
func persistTransferState(ctx context.Context,db *sql.DB,value OwnershipTransfer)error{result,err:=db.ExecContext(ctx,`UPDATE identity_ownership_transfers SET state=?,revision=?,last_error=?,updated_at=?,completed_at=? WHERE id=? AND revision<?`,value.State,value.Revision,value.LastError,value.UpdatedAt,value.CompletedAt,value.ID,value.Revision);if err!=nil{return err};count,_:=result.RowsAffected();if count!=1{return ErrStaleGeneration};return nil}

func frontierPassed(declared OwnershipTransferFrontier,step OwnershipTransferStep)bool{if step.FrontierReached{return true};if declared==OwnershipFrontierAuthorization{return step.AuthorizationReceipt!=nil};return step.AccountingReceipt!=nil}
func(c *OwnershipTransferCoordinator)compensate(ctx context.Context,value *OwnershipTransfer,failedAt int,cause error)error{value.State=OwnershipTransferCompensating;value.LastError=cause.Error();value.Revision++;value.UpdatedAt=c.clock().UTC();if err:=persistTransferState(ctx,c.service.store.db,*value);err!=nil{return err};contextValue:=transferContext(*value);for index:=failedAt;index>=0;index--{step:=&value.Steps[index];if step.AuthorizationReceipt==nil{continue};if frontierPassed(value.Frontier,*step){step.State=OwnershipStepRecoveryRequired;step.LastError=cause.Error();value.State=OwnershipTransferRecoveryRequired;continue};receipt,err:=c.adapters[step.Resource.Kind].Compensate(ctx,contextValue,step.Resource,*step.AuthorizationReceipt,optionalTransferReceipt(step.AccountingReceipt));step.Attempt++;step.UpdatedAt=c.clock().UTC();if err!=nil{step.State=OwnershipStepRecoveryRequired;step.LastError=err.Error();value.State=OwnershipTransferRecoveryRequired}else{step.CompensationReceipt=&receipt;step.State=OwnershipStepCompensated;step.LastError=""};if persistErr:=persistTransferStep(ctx,c.service.store.db,value.ID,*step);persistErr!=nil{return persistErr}};if value.State!=OwnershipTransferRecoveryRequired{value.State=OwnershipTransferFailed};value.Revision++;value.UpdatedAt=c.clock().UTC();if err:=persistTransferState(ctx,c.service.store.db,*value);err!=nil{return err};return cause}
func optionalTransferReceipt(value *OwnershipTransferReceipt)OwnershipTransferReceipt{if value==nil{return OwnershipTransferReceipt{}};return *value}

func(c *OwnershipTransferCoordinator)Resume(ctx context.Context,actor ActorContext,transferID ID,maxSteps int)(OwnershipTransfer,error){if maxSteps<1||maxSteps>100{return OwnershipTransfer{},ErrInvalid};value,err:=c.Get(ctx,actor,transferID);if err!=nil{return value,err};if value.State==OwnershipTransferCompleted||value.State==OwnershipTransferFailed{return value,nil};if value.State==OwnershipTransferRecoveryRequired{return value,ErrConflict};if err=c.authorize(ctx,actor,value.SourceTenantID,value.DestinationTenantID,AssuranceMFA,true);err!=nil{return value,err};value.State=OwnershipTransferRunning;value.Revision++;value.UpdatedAt=c.clock().UTC();if err=persistTransferState(ctx,c.service.store.db,value);err!=nil{return value,err};processed:=0;contextValue:=transferContext(value);for index:=range value.Steps{if processed>=maxSteps{break};step:=&value.Steps[index];if step.State==OwnershipStepCompleted||step.State==OwnershipStepCompensated{continue};adapter:=c.adapters[step.Resource.Kind];if adapter==nil{return value,c.compensate(ctx,&value,index,ErrNotFound)};if step.AuthorizationReceipt==nil{receipt,applyErr:=adapter.RebindAuthorization(ctx,contextValue,step.Resource);step.Attempt++;step.UpdatedAt=c.clock().UTC();if applyErr!=nil{return value,c.compensate(ctx,&value,index,applyErr)};if receipt.Validate()!=nil{return value,c.compensate(ctx,&value,index,ErrConflict)};step.AuthorizationReceipt=&receipt;step.State=OwnershipStepAuthorizationRebound;step.Phase=OwnershipFrontierAuthorization;step.FrontierReached=receipt.FrontierReached;if err=persistTransferStep(ctx,c.service.store.db,value.ID,*step);err!=nil{return value,err}};if step.AccountingReceipt==nil{receipt,applyErr:=adapter.RebindAccounting(ctx,contextValue,step.Resource,*step.AuthorizationReceipt);step.Attempt++;step.UpdatedAt=c.clock().UTC();if applyErr!=nil{return value,c.compensate(ctx,&value,index,applyErr)};if receipt.Validate()!=nil{return value,c.compensate(ctx,&value,index,ErrConflict)};step.AccountingReceipt=&receipt;step.State=OwnershipStepAccountingRebound;step.Phase=OwnershipFrontierAccounting;step.FrontierReached=step.FrontierReached||receipt.FrontierReached;if err=persistTransferStep(ctx,c.service.store.db,value.ID,*step);err!=nil{return value,err}};step.State=OwnershipStepCompleted;step.LastError="";step.UpdatedAt=c.clock().UTC();if err=persistTransferStep(ctx,c.service.store.db,value.ID,*step);err!=nil{return value,err};processed++};complete:=true;for _,step:=range value.Steps{complete=complete&&step.State==OwnershipStepCompleted};if complete{now:=c.clock().UTC();value.State=OwnershipTransferCompleted;value.CompletedAt=&now}else{value.State=OwnershipTransferRunning};value.Revision++;value.UpdatedAt=c.clock().UTC();if complete{if err=c.audit(ctx,value,"ownership_transfer.complete","prepared");err!=nil{return value,err}};if err=persistTransferState(ctx,c.service.store.db,value);err!=nil{return value,err};return value,nil}

func(c *OwnershipTransferCoordinator)Recover(ctx context.Context,actor ActorContext,transferID ID,maxSteps int)(OwnershipTransfer,error){if maxSteps<1||maxSteps>100{return OwnershipTransfer{},ErrInvalid};value,err:=c.Get(ctx,actor,transferID);if err!=nil{return value,err};if value.State!=OwnershipTransferRecoveryRequired{return value,ErrConflict};if err=c.authorize(ctx,actor,value.SourceTenantID,value.DestinationTenantID,AssurancePhishingResistant,true);err!=nil{return value,err};contextValue:=transferContext(value);processed:=0;for index:=range value.Steps{step:=&value.Steps[index];if step.State!=OwnershipStepRecoveryRequired||processed>=maxSteps{continue};receipt,recoverErr:=c.adapters[step.Resource.Kind].Recover(ctx,contextValue,step.Resource,optionalTransferReceipt(step.AuthorizationReceipt),optionalTransferReceipt(step.AccountingReceipt));step.Attempt++;step.UpdatedAt=c.clock().UTC();if recoverErr!=nil{step.LastError=recoverErr.Error()}else if receipt.Validate()!=nil{step.LastError=ErrConflict.Error()}else{step.CompensationReceipt=&receipt;step.State=OwnershipStepCompleted;step.LastError=""};if err=persistTransferStep(ctx,c.service.store.db,value.ID,*step);err!=nil{return value,err};processed++};remaining:=false;for _,step:=range value.Steps{remaining=remaining||step.State==OwnershipStepRecoveryRequired};if !remaining{now:=c.clock().UTC();value.State=OwnershipTransferCompleted;value.CompletedAt=&now;value.LastError=""};value.Revision++;value.UpdatedAt=c.clock().UTC();if !remaining{if err=c.audit(ctx,value,"ownership_transfer.recover","prepared");err!=nil{return value,err}};if err=persistTransferState(ctx,c.service.store.db,value);err!=nil{return value,err};return value,nil}

func(s *Service)PreviewOwnershipTransfer(ctx context.Context,actor ActorContext,source,destination ID,resources []OwnershipTransferResource)(OwnershipTransferPreview,error){if s.transfers==nil{return OwnershipTransferPreview{},ErrNotFound};return s.transfers.Preview(ctx,actor,source,destination,resources)}
func(s *Service)StartOwnershipTransfer(ctx context.Context,command StartOwnershipTransferCommand)(OwnershipTransfer,error){if s.transfers==nil{return OwnershipTransfer{},ErrNotFound};return s.transfers.Start(ctx,command)}
func(s *Service)GetOwnershipTransfer(ctx context.Context,actor ActorContext,id ID)(OwnershipTransfer,error){if s.transfers==nil{return OwnershipTransfer{},ErrNotFound};return s.transfers.Get(ctx,actor,id)}
func(s *Service)ResumeOwnershipTransfer(ctx context.Context,actor ActorContext,id ID,maxSteps int)(OwnershipTransfer,error){if s.transfers==nil{return OwnershipTransfer{},ErrNotFound};return s.transfers.Resume(ctx,actor,id,maxSteps)}
func(s *Service)RecoverOwnershipTransfer(ctx context.Context,actor ActorContext,id ID,maxSteps int)(OwnershipTransfer,error){if s.transfers==nil{return OwnershipTransfer{},ErrNotFound};return s.transfers.Recover(ctx,actor,id,maxSteps)}
