//go:build linux

// Package daemoncfg provides a root-owned, immutable generation store used by
// daemon-specific brokers. It intentionally has no process execution surface.
package daemoncfg

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"syscall"
	"time"
)

var ErrInvalid=errors.New("invalid daemon configuration generation")
var ErrConflict=errors.New("daemon configuration generation conflict")
var ErrIntegrity=errors.New("daemon configuration integrity failure")

type Artifact struct{Path string `json:"path"`;Mode uint32 `json:"mode"`;GID uint32 `json:"gid"`;Content []byte `json:"-"`;SHA256 string `json:"sha256"`}
type ManifestArtifact struct{Path string `json:"path"`;Mode uint32 `json:"mode"`;GID uint32 `json:"gid"`;Size uint64 `json:"size"`;SHA256 string `json:"sha256"`}
type Manifest struct{Version uint8 `json:"version"`;GenerationID string `json:"generation_id"`;Digest string `json:"digest"`;Artifacts []ManifestArtifact `json:"artifacts"`;CreatedAt time.Time `json:"created_at"`}
type Store struct{Root string;rootFD int}

func OpenStore(root,required string)(*Store,error){if root!=required||!filepath.IsAbs(root)||filepath.Clean(root)!=root{return nil,ErrInvalid};fd,err:=openRootOwnedTree(root);if err!=nil{return nil,err};store:=&Store{Root:root,rootFD:fd};for _,definition:=range []struct{name string;mode uint32}{{"generations",0755},{"staging",0700}}{directory,openErr:=openDirectoryAt(fd,definition.name,true,definition.mode);if openErr!=nil{store.Close();return nil,openErr};syscall.Close(directory)};return store,nil}
func (store *Store)Close()error{if store==nil||store.rootFD<0{return nil};err:=syscall.Close(store.rootFD);store.rootFD=-1;return err}
func (store *Store)Stage(ctx context.Context,id,digestValue string,artifacts []Artifact)(Manifest,error){if store==nil||store.rootFD<0||ctx==nil||!safeID(id)||!isSHA256(digestValue)||len(artifacts)==0||len(artifacts)>128{return Manifest{},ErrInvalid};normalized,err:=normalizeArtifacts(artifacts);if err!=nil{return Manifest{},err};if computedGenerationDigest(normalized)!=digestValue{return Manifest{},ErrIntegrity};generations,err:=openDirectoryAt(store.rootFD,"generations",false,0);if err!=nil{return Manifest{},err};defer syscall.Close(generations);if existing,openErr:=openDirectoryAt(generations,id,false,0);openErr==nil{defer syscall.Close(existing);manifest,verifyErr:=verifyGeneration(existing,id,digestValue,normalized);return manifest,verifyErr}else if !errors.Is(openErr,syscall.ENOENT){return Manifest{},openErr};staging,err:=openDirectoryAt(store.rootFD,"staging",false,0);if err!=nil{return Manifest{},err};defer syscall.Close(staging);stageName,err:=randomStageName(id);if err!=nil{return Manifest{},err};stage,err:=openDirectoryAt(staging,stageName,true,0700);if err!=nil{return Manifest{},err};stageOpen:=true;defer func(){if stageOpen{syscall.Close(stage)}}();for _,artifact:=range normalized{if err=ctx.Err();err!=nil{return Manifest{},err};if err=writeArtifact(stage,artifact);err!=nil{return Manifest{},err}};manifest:=Manifest{Version:1,GenerationID:id,Digest:digestValue,CreatedAt:time.Now().UTC()};for _,artifact:=range normalized{manifest.Artifacts=append(manifest.Artifacts,ManifestArtifact{Path:artifact.Path,Mode:artifact.Mode,GID:artifact.GID,Size:uint64(len(artifact.Content)),SHA256:artifact.SHA256})};raw,err:=json.Marshal(manifest);if err!=nil{return Manifest{},err};sum:=sha256.Sum256(raw);envelope,err:=json.Marshal(struct{Manifest Manifest `json:"manifest"`;ManifestSHA256 string `json:"manifest_sha256"`}{manifest,hex.EncodeToString(sum[:])});if err!=nil{return Manifest{},err};if err=writeFileAt(stage,"manifest.json",envelope,0444,0);err!=nil{return Manifest{},err};if err=syscall.Fsync(stage);err!=nil{return Manifest{},err};if err=syscall.Fchmod(stage,0555);err!=nil{return Manifest{},err};if err=syscall.Renameat(staging,stageName,generations,id);err!=nil{if errors.Is(err,syscall.EEXIST)||errors.Is(err,syscall.ENOTEMPTY){existing,openErr:=openDirectoryAt(generations,id,false,0);if openErr!=nil{return Manifest{},errors.Join(ErrConflict,openErr)};defer syscall.Close(existing);return verifyGeneration(existing,id,digestValue,normalized)};return Manifest{},err};stageOpen=false;syscall.Close(stage);if err=syscall.Fsync(generations);err!=nil{return Manifest{},err};return manifest,nil}
func randomStageName(id string)(string,error){var entropy [12]byte;if _,err:=rand.Read(entropy[:]);err!=nil{return "",err};return "stage-"+id+"-"+hex.EncodeToString(entropy[:]),nil}
func (store *Store)Current() (string,error){if store==nil||store.rootFD<0{return "",ErrInvalid};target,err:=os.Readlink(filepath.Join(store.Root,"current"));if errors.Is(err,os.ErrNotExist){return "",nil};if err!=nil{return "",err};const prefix="generations/";if !strings.HasPrefix(target,prefix)||!safeID(strings.TrimPrefix(target,prefix)){return "",ErrIntegrity};return strings.TrimPrefix(target,prefix),nil}
func (store *Store)Activate(ctx context.Context,id string)(string,error){if store==nil||store.rootFD<0||ctx==nil||!safeID(id){return "",ErrInvalid};if err:=ctx.Err();err!=nil{return "",err};generations,err:=openDirectoryAt(store.rootFD,"generations",false,0);if err!=nil{return "",err};generation,err:=openDirectoryAt(generations,id,false,0);syscall.Close(generations);if err!=nil{return "",err};syscall.Close(generation);previous,err:=store.Current();if err!=nil{return "",err};target:="generations/"+id;temporary:=".current-"+id;if err=os.Symlink(target,filepath.Join(store.Root,temporary));err!=nil{if !errors.Is(err,os.ErrExist){return "",err};existing,readErr:=os.Readlink(filepath.Join(store.Root,temporary));if readErr!=nil||existing!=target{return "",ErrConflict}};if err=os.Rename(filepath.Join(store.Root,temporary),filepath.Join(store.Root,"current"));err!=nil{return "",err};if err=syscall.Fsync(store.rootFD);err!=nil{return "",err};return previous,nil}
func (store *Store)Rollback(ctx context.Context,previous string)error{if store==nil||store.rootFD<0||ctx==nil{return ErrInvalid};if previous==""{if err:=ctx.Err();err!=nil{return err};err:=os.Remove(filepath.Join(store.Root,"current"));if errors.Is(err,os.ErrNotExist){return nil};if err!=nil{return err};return syscall.Fsync(store.rootFD)};_,err:=store.Activate(ctx,previous);return err}
func (store *Store)Verify(id,digestValue string)(Manifest,error){if store==nil||store.rootFD<0||!safeID(id)||!isSHA256(digestValue){return Manifest{},ErrInvalid};generations,err:=openDirectoryAt(store.rootFD,"generations",false,0);if err!=nil{return Manifest{},err};defer syscall.Close(generations);generation,err:=openDirectoryAt(generations,id,false,0);if err!=nil{return Manifest{},err};defer syscall.Close(generation);return verifyGeneration(generation,id,digestValue,nil)}
func computedGenerationDigest(artifacts []Artifact)string{binding:=make([]ManifestArtifact,0,len(artifacts));for _,artifact:=range artifacts{binding=append(binding,ManifestArtifact{Path:artifact.Path,Mode:artifact.Mode,GID:artifact.GID,Size:uint64(len(artifact.Content)),SHA256:artifact.SHA256})};raw,_:=json.Marshal(struct{Version uint8 `json:"version"`;Artifacts []ManifestArtifact `json:"artifacts"`}{1,binding});sum:=sha256.Sum256(raw);return hex.EncodeToString(sum[:])}
func ComputeDigest(artifacts []Artifact)(string,error){normalized,err:=normalizeArtifacts(artifacts);if err!=nil{return "",err};return computedGenerationDigest(normalized),nil}
func normalizeArtifacts(artifacts []Artifact)([]Artifact,error){result:=append([]Artifact(nil),artifacts...);sort.Slice(result,func(i,j int)bool{return result[i].Path<result[j].Path});seen:=map[string]bool{};for index:=range result{artifact:=&result[index];if !safeRelative(artifact.Path)||seen[artifact.Path]||len(artifact.Content)>64<<20||artifact.Mode&^0777!=0||artifact.Mode&0027!=0||artifact.Mode&0111!=0{return nil,ErrInvalid};seen[artifact.Path]=true;sum:=sha256.Sum256(artifact.Content);actual:=hex.EncodeToString(sum[:]);if artifact.SHA256==""{artifact.SHA256=actual}else if artifact.SHA256!=actual{return nil,ErrIntegrity};artifact.Mode&=0550;if artifact.Mode==0{artifact.Mode=0440}};return result,nil}
func writeArtifact(root int,artifact Artifact)error{segments:=strings.Split(artifact.Path,"/");directory,err:=syscall.Dup(root);if err!=nil{return err};defer syscall.Close(directory);for _,segment:=range segments[:len(segments)-1]{next,openErr:=openDirectoryAt(directory,segment,true,0555);if openErr!=nil{return openErr};syscall.Close(directory);directory=next};return writeFileAt(directory,segments[len(segments)-1],artifact.Content,artifact.Mode,artifact.GID)}
func writeFileAt(directory int,name string,content []byte,mode uint32,gid uint32)error{if !safeLeaf(name){return ErrInvalid};fd,err:=syscall.Openat(directory,name,syscall.O_WRONLY|syscall.O_CREAT|syscall.O_EXCL|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,mode);if errors.Is(err,syscall.EEXIST){return ErrConflict};if err!=nil{return err};file:=os.NewFile(uintptr(fd),name);written,writeErr:=file.Write(content);if writeErr==nil{writeErr=file.Sync()};if writeErr==nil{writeErr=syscall.Fchown(fd,0,int(gid))};if writeErr==nil{writeErr=syscall.Fchmod(fd,mode)};closeErr:=file.Close();if writeErr!=nil||closeErr!=nil||written!=len(content){return errors.Join(ErrIntegrity,writeErr,closeErr)};return syscall.Fsync(directory)}
func verifyGeneration(directory int,id,digestValue string,expected []Artifact)(Manifest,error){raw,err:=readFileAt(directory,"manifest.json",4<<20);if err!=nil{return Manifest{},err};var envelope struct{Manifest Manifest `json:"manifest"`;ManifestSHA256 string `json:"manifest_sha256"`};if json.Unmarshal(raw,&envelope)!=nil||envelope.Manifest.Version!=1||envelope.Manifest.GenerationID!=id||envelope.Manifest.Digest!=digestValue{return Manifest{},ErrIntegrity};manifestRaw,_:=json.Marshal(envelope.Manifest);sum:=sha256.Sum256(manifestRaw);if envelope.ManifestSHA256!=hex.EncodeToString(sum[:]){return Manifest{},ErrIntegrity};if expected!=nil&&len(expected)!=len(envelope.Manifest.Artifacts){return Manifest{},ErrConflict};for index,item:=range envelope.Manifest.Artifacts{if expected!=nil&&(item.Path!=expected[index].Path||item.Mode!=expected[index].Mode||item.GID!=expected[index].GID||item.SHA256!=expected[index].SHA256||item.Size!=uint64(len(expected[index].Content))){return Manifest{},ErrConflict};if err=verifyArtifact(directory,item);err!=nil{return Manifest{},err}};return envelope.Manifest,nil}
func verifyArtifact(root int,item ManifestArtifact)error{if !safeRelative(item.Path)||!isSHA256(item.SHA256){return ErrIntegrity};segments:=strings.Split(item.Path,"/");directory,err:=syscall.Dup(root);if err!=nil{return err};defer syscall.Close(directory);for _,segment:=range segments[:len(segments)-1]{next,openErr:=openDirectoryAt(directory,segment,false,0);if openErr!=nil{return openErr};syscall.Close(directory);directory=next};fd,err:=syscall.Openat(directory,segments[len(segments)-1],syscall.O_RDONLY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if err!=nil{return err};file:=os.NewFile(uintptr(fd),item.Path);defer file.Close();info,err:=file.Stat();if err!=nil||!info.Mode().IsRegular()||uint64(info.Size())!=item.Size||uint32(info.Mode().Perm())!=item.Mode{return ErrIntegrity};metadata,ok:=info.Sys().(*syscall.Stat_t);if !ok||metadata.Uid!=0||metadata.Gid!=item.GID{return ErrIntegrity};hasher:=sha256.New();written,err:=io.Copy(hasher,io.LimitReader(file,int64(item.Size)+1));if err!=nil||uint64(written)!=item.Size||hex.EncodeToString(hasher.Sum(nil))!=item.SHA256{return ErrIntegrity};return nil}
func readFileAt(directory int,name string,maximum uint64)([]byte,error){if !safeLeaf(name){return nil,ErrInvalid};fd,err:=syscall.Openat(directory,name,syscall.O_RDONLY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if err!=nil{return nil,err};file:=os.NewFile(uintptr(fd),name);defer file.Close();info,err:=file.Stat();if err!=nil||!info.Mode().IsRegular()||uint64(info.Size())>maximum{return nil,ErrIntegrity};return io.ReadAll(io.LimitReader(file,int64(maximum)+1))}
func openDirectoryAt(parent int,name string,create bool,mode uint32)(int,error){if !safeLeaf(name){return -1,ErrInvalid};fd,err:=syscall.Openat(parent,name,syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if err!=nil&&create&&errors.Is(err,syscall.ENOENT){if mkdirErr:=syscall.Mkdirat(parent,name,mode);mkdirErr!=nil&&!errors.Is(mkdirErr,syscall.EEXIST){return -1,mkdirErr};fd,err=syscall.Openat(parent,name,syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0)};if err!=nil{return -1,err};var stat syscall.Stat_t;if err=syscall.Fstat(fd,&stat);err!=nil||stat.Uid!=0||stat.Mode&syscall.S_IFMT!=syscall.S_IFDIR||stat.Mode&0022!=0{syscall.Close(fd);return -1,ErrInvalid};return fd,nil}
func openRootOwnedTree(absolute string)(int,error){current,err:=syscall.Open("/",syscall.O_RDONLY|syscall.O_DIRECTORY|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0);if err!=nil{return -1,err};for _,segment:=range strings.Split(strings.TrimPrefix(absolute,"/"),"/"){if !safeLeaf(segment){syscall.Close(current);return -1,ErrInvalid};next,openErr:=openDirectoryAt(current,segment,true,0755);syscall.Close(current);if openErr!=nil{return -1,openErr};current=next};return current,nil}
func safeRelative(value string)bool{return value!=""&&len(value)<=1024&&filepath.Clean(value)==value&&!filepath.IsAbs(value)&&!strings.HasPrefix(value,"../")&&!strings.Contains(value,"//")}
func safeLeaf(value string)bool{return value!=""&&value!="."&&value!=".."&&len(value)<=255&&!strings.Contains(value,"/")&&strings.IndexByte(value,0)<0}
func safeID(value string)bool{if len(value)<8||len(value)>128{return false};for _,r:=range value{if !(r=='-'||r=='_'||r>='0'&&r<='9'||r>='a'&&r<='z'||r>='A'&&r<='Z'){return false}};return true}
func isSHA256(value string)bool{if len(value)!=64||value!=strings.ToLower(value){return false};_,err:=hex.DecodeString(value);return err==nil}
